\echo -----------------------AMS_MODI_LOG------------------------
select now();
\timing
delete from AMS_MODI_LOG using AMS_MODI_LOG_GPTMP_TODAY where AMS_MODI_LOG.EMS_NO=AMS_MODI_LOG_GPTMP_TODAY.EMS_NO AND AMS_MODI_LOG.OP_TIME=AMS_MODI_LOG_GPTMP_TODAY.OP_TIME AND AMS_MODI_LOG.MODI_TYPE=AMS_MODI_LOG_GPTMP_TODAY.MODI_TYPE AND AMS_MODI_LOG.ITEM_NAME=AMS_MODI_LOG_GPTMP_TODAY.ITEM_NAME ;
insert into AMS_MODI_LOG (EMS_NO,OP_TIME,MODI_TYPE,ITEM_NAME,ITEM_SOURCE,ITEM_CURRENT,OP_ER,NOTE) select EMS_NO,OP_TIME,MODI_TYPE,ITEM_NAME,ITEM_SOURCE,ITEM_CURRENT,OP_ER,NOTE from AMS_MODI_LOG_GPTMP_TODAY  where CMD_TYPE='I';
\timing
