\echo -----------------------AMSLIST_BODY------------------------
select now();
\timing
delete from AMSLIST_BODY using AMSLIST_BODY_GPTMP_TODAY where AMSLIST_BODY.LIST_ID=AMSLIST_BODY_GPTMP_TODAY.LIST_ID AND AMSLIST_BODY.G_NO=AMSLIST_BODY_GPTMP_TODAY.G_NO ;
insert into AMSLIST_BODY (LIST_ID,G_NO,CODE_TS,G_NAME,G_MODEL,ORIGIN_COUNTRY,CONTR_ITEM,DECL_PRICE,REF_VALUE,CUS_VALUE,G_QTY,G_UNIT,DUTY_VALUE,TARIFF_MARK,DUTY_TYPE,REAL_DUTY,DUTY_CUT,DUTY_RATE,D_RATE,QTY_DUTY_RATE,QTY_D_RATE,TAX_TYPE,REAL_TAX,TAX_CUT,TAX_RATE,T_RATE,QTY_TAX_RATE,QTY_T_RATE) select LIST_ID,G_NO,CODE_TS,G_NAME,G_MODEL,ORIGIN_COUNTRY,CONTR_ITEM,DECL_PRICE,REF_VALUE,CUS_VALUE,G_QTY,G_UNIT,DUTY_VALUE,TARIFF_MARK,DUTY_TYPE,REAL_DUTY,DUTY_CUT,DUTY_RATE,D_RATE,QTY_DUTY_RATE,QTY_D_RATE,TAX_TYPE,REAL_TAX,TAX_CUT,TAX_RATE,T_RATE,QTY_TAX_RATE,QTY_T_RATE from AMSLIST_BODY_GPTMP_TODAY  where CMD_TYPE='I';
\timing
