\echo -----------------------APPLY_LIST------------------------
select now();
\timing
delete from APPLY_LIST using APPLY_LIST_GPTMP_TODAY where APPLY_LIST.APPL_NO=APPLY_LIST_GPTMP_TODAY.APPL_NO AND APPLY_LIST.G_NO=APPLY_LIST_GPTMP_TODAY.G_NO ;
insert into APPLY_LIST (APPL_NO,CONTACT_NO,G_NO,CODE_TS,G_NAME,PACK_TYPE,GOODS_PIECE,GOODS_AMOUNT,GOODS_WEIGHT,GOODS_PRICE) select APPL_NO,CONTACT_NO,G_NO,CODE_TS,G_NAME,PACK_TYPE,GOODS_PIECE,GOODS_AMOUNT,GOODS_WEIGHT,GOODS_PRICE from APPLY_LIST_GPTMP_TODAY  where CMD_TYPE='I';
\timing
