\echo -----------------------ARRIVAL_INFO_HEAD------------------------
select now();
\timing
delete from ARRIVAL_INFO_HEAD using ARRIVAL_INFO_HEAD_GPTMP_TODAY where ARRIVAL_INFO_HEAD.VOYAGE_NO=ARRIVAL_INFO_HEAD_GPTMP_TODAY.VOYAGE_NO AND ARRIVAL_INFO_HEAD.SHIP_ID=ARRIVAL_INFO_HEAD_GPTMP_TODAY.SHIP_ID AND ARRIVAL_INFO_HEAD.I_E_DATE=ARRIVAL_INFO_HEAD_GPTMP_TODAY.I_E_DATE AND ARRIVAL_INFO_HEAD.CUSTOMS_CODE=ARRIVAL_INFO_HEAD_GPTMP_TODAY.CUSTOMS_CODE AND ARRIVAL_INFO_HEAD.TRAF_MODE=ARRIVAL_INFO_HEAD_GPTMP_TODAY.TRAF_MODE ;
insert into ARRIVAL_INFO_HEAD (VOYAGE_NO,SHIP_ID,I_E_DATE,CUSTOMS_CODE,TRAF_MODE,I_E_FLAG,VOYAGE_NO_MOD,ARRIVE_DATE,RECV_DATE,SEQ_NO) select VOYAGE_NO,SHIP_ID,I_E_DATE,CUSTOMS_CODE,TRAF_MODE,I_E_FLAG,VOYAGE_NO_MOD,ARRIVE_DATE,RECV_DATE,SEQ_NO from ARRIVAL_INFO_HEAD_GPTMP_TODAY  where CMD_TYPE='I';
\timing
