\echo -----------------------BAK_EX_FASCICLE_LIST------------------------
select now();
\timing
delete from BAK_EX_FASCICLE_LIST using BAK_EX_FASCICLE_LIST_GPTMP_TODAY where BAK_EX_FASCICLE_LIST.FASCICLE_NO=BAK_EX_FASCICLE_LIST_GPTMP_TODAY.FASCICLE_NO AND BAK_EX_FASCICLE_LIST.CONTR_ITEM=BAK_EX_FASCICLE_LIST_GPTMP_TODAY.CONTR_ITEM ;
insert into BAK_EX_FASCICLE_LIST (MANUAL_NO,FASCICLE_NO,CONTR_ITEM,APPR_QTY,FACT_QTY) select MANUAL_NO,FASCICLE_NO,CONTR_ITEM,APPR_QTY,FACT_QTY from BAK_EX_FASCICLE_LIST_GPTMP_TODAY  where CMD_TYPE='I';
\timing
