\echo -----------------------BAK_CONSUME------------------------
select now();
\timing
delete from BAK_CONSUME using BAK_CONSUME_GPTMP_TODAY where BAK_CONSUME.MANUAL_NO=BAK_CONSUME_GPTMP_TODAY.MANUAL_NO AND BAK_CONSUME.CONTR_ITEM=BAK_CONSUME_GPTMP_TODAY.CONTR_ITEM AND BAK_CONSUME.EX_NO=BAK_CONSUME_GPTMP_TODAY.EX_NO ;
insert into BAK_CONSUME (MANUAL_NO,CONTR_ITEM,EX_NO,APPR_CONSUME,APPR_DAMAGE,DECL_CONSUME,DECL_DAMAGE) select MANUAL_NO,CONTR_ITEM,EX_NO,APPR_CONSUME,APPR_DAMAGE,DECL_CONSUME,DECL_DAMAGE from BAK_CONSUME_GPTMP_TODAY  where CMD_TYPE='I';
\timing
