\echo -----------------------BAK_DCG_DEDUCT_LOG------------------------
select now();
\timing
delete from BAK_DCG_DEDUCT_LOG using BAK_DCG_DEDUCT_LOG_GPTMP_TODAY where BAK_DCG_DEDUCT_LOG.ENTRY_ID=BAK_DCG_DEDUCT_LOG_GPTMP_TODAY.ENTRY_ID AND BAK_DCG_DEDUCT_LOG.DCG_NO=BAK_DCG_DEDUCT_LOG_GPTMP_TODAY.DCG_NO AND BAK_DCG_DEDUCT_LOG.CREATE_DATE=BAK_DCG_DEDUCT_LOG_GPTMP_TODAY.CREATE_DATE AND BAK_DCG_DEDUCT_LOG.JOU_MARK=BAK_DCG_DEDUCT_LOG_GPTMP_TODAY.JOU_MARK ;
insert into BAK_DCG_DEDUCT_LOG (ENTRY_ID,DCG_NO,CREATE_DATE,JOU_MARK,NOTE,VERIFY_ER) select ENTRY_ID,DCG_NO,CREATE_DATE,JOU_MARK,NOTE,VERIFY_ER from BAK_DCG_DEDUCT_LOG_GPTMP_TODAY  where CMD_TYPE='I';
\timing
