\echo -----------------------BAK_DCG_BILL_LIST------------------------
select now();
\timing
delete from BAK_DCG_BILL_LIST using BAK_DCG_BILL_LIST_GPTMP_TODAY where BAK_DCG_BILL_LIST.BILL_NO=BAK_DCG_BILL_LIST_GPTMP_TODAY.BILL_NO AND BAK_DCG_BILL_LIST.G_TYPE=BAK_DCG_BILL_LIST_GPTMP_TODAY.G_TYPE AND BAK_DCG_BILL_LIST.G_NO=BAK_DCG_BILL_LIST_GPTMP_TODAY.G_NO ;
insert into BAK_DCG_BILL_LIST (BILL_NO,G_TYPE,G_NO,DCG_G_NO,QTY,CHECK_DATE,COP_QTY,COP_UNIT,G_MARK) select BILL_NO,G_TYPE,G_NO,DCG_G_NO,QTY,CHECK_DATE,COP_QTY,COP_UNIT,G_MARK from BAK_DCG_BILL_LIST_GPTMP_TODAY  where CMD_TYPE='I';
\timing
