\echo -----------------------BAK_DCG_DEDUCT------------------------
select now();
\timing
delete from BAK_DCG_DEDUCT using BAK_DCG_DEDUCT_GPTMP_TODAY where BAK_DCG_DEDUCT.ENTRY_ID=BAK_DCG_DEDUCT_GPTMP_TODAY.ENTRY_ID AND BAK_DCG_DEDUCT.DCG_NO=BAK_DCG_DEDUCT_GPTMP_TODAY.DCG_NO AND BAK_DCG_DEDUCT.G_TYPE=BAK_DCG_DEDUCT_GPTMP_TODAY.G_TYPE AND BAK_DCG_DEDUCT.ENTRY_G_NO=BAK_DCG_DEDUCT_GPTMP_TODAY.ENTRY_G_NO ;
insert into BAK_DCG_DEDUCT (ENTRY_ID,DCG_NO,G_TYPE,ENTRY_G_NO,DCG_G_NO,EMS_NO,EMS_G_NO,QTY,VERIFY_DATE,VERIFY_ER) select ENTRY_ID,DCG_NO,G_TYPE,ENTRY_G_NO,DCG_G_NO,EMS_NO,EMS_G_NO,QTY,VERIFY_DATE,VERIFY_ER from BAK_DCG_DEDUCT_GPTMP_TODAY  where CMD_TYPE='I';
\timing
