\echo -----------------------BAK_BWS_EXAM_CERT_LIST------------------------
select now();
\timing
delete from BAK_BWS_EXAM_CERT_LIST using BAK_BWS_EXAM_CERT_LIST_GPTMP_TODAY where BAK_BWS_EXAM_CERT_LIST.BWS_EXAM_NO=BAK_BWS_EXAM_CERT_LIST_GPTMP_TODAY.BWS_EXAM_NO AND BAK_BWS_EXAM_CERT_LIST.G_NO=BAK_BWS_EXAM_CERT_LIST_GPTMP_TODAY.G_NO ;
insert into BAK_BWS_EXAM_CERT_LIST (BWS_EXAM_NO,G_NO,CERT_NO,PACK_NO,GROSS_WT,BILL_NO) select BWS_EXAM_NO,G_NO,CERT_NO,PACK_NO,GROSS_WT,BILL_NO from BAK_BWS_EXAM_CERT_LIST_GPTMP_TODAY  where CMD_TYPE='I';
\timing
