\echo -----------------------BAK_BWS_EXAM_GOOD_LIST------------------------
select now();
\timing
delete from BAK_BWS_EXAM_GOOD_LIST using BAK_BWS_EXAM_GOOD_LIST_GPTMP_TODAY where BAK_BWS_EXAM_GOOD_LIST.BWS_EXAM_NO=BAK_BWS_EXAM_GOOD_LIST_GPTMP_TODAY.BWS_EXAM_NO AND BAK_BWS_EXAM_GOOD_LIST.G_NO=BAK_BWS_EXAM_GOOD_LIST_GPTMP_TODAY.G_NO ;
insert into BAK_BWS_EXAM_GOOD_LIST (BWS_EXAM_NO,G_NO,CERT_NO,CERT_G_NO,G_NAME,QTY,UNIT) select BWS_EXAM_NO,G_NO,CERT_NO,CERT_G_NO,G_NAME,QTY,UNIT from BAK_BWS_EXAM_GOOD_LIST_GPTMP_TODAY  where CMD_TYPE='I';
\timing
