\echo -----------------------BAK_BWS_EXAM_HEAD------------------------
select now();
\timing
delete from BAK_BWS_EXAM_HEAD using BAK_BWS_EXAM_HEAD_GPTMP_TODAY where BAK_BWS_EXAM_HEAD.BWS_EXAM_NO=BAK_BWS_EXAM_HEAD_GPTMP_TODAY.BWS_EXAM_NO ;
insert into BAK_BWS_EXAM_HEAD (BWS_EXAM_NO,EPORT_NO,EXAM_TYPE,CERT_TYPE,I_E_FLAG,BWS_NO,MASTER_CUSTOMS,TRADE_CODE,TRADE_NAME,TRANSIT_CODE,TRANSIT_NAME,ENTRUST_CODE,ENTRUST_NAME,VEHICLE_NT,TOTAL_PACK_NO,TOTAL_WEIGHT,IC_CARD,SHIP_ID,CONTA_ID1,SEAL_NO1,CONTA_ID2,SEAL_NO2,INPUT_DATE,INPUT_ER,DECLARE_DATE,NOTE,CHK_MARK,PASS_MODE,PASS_TIME,KK_CODE,KK_PASS_WEIGHT,PASS_REASON) select BWS_EXAM_NO,EPORT_NO,EXAM_TYPE,CERT_TYPE,I_E_FLAG,BWS_NO,MASTER_CUSTOMS,TRADE_CODE,TRADE_NAME,TRANSIT_CODE,TRANSIT_NAME,ENTRUST_CODE,ENTRUST_NAME,VEHICLE_NT,TOTAL_PACK_NO,TOTAL_WEIGHT,IC_CARD,SHIP_ID,CONTA_ID1,SEAL_NO1,CONTA_ID2,SEAL_NO2,INPUT_DATE,INPUT_ER,DECLARE_DATE,NOTE,CHK_MARK,PASS_MODE,PASS_TIME,KK_CODE,KK_PASS_WEIGHT,PASS_REASON from BAK_BWS_EXAM_HEAD_GPTMP_TODAY  where CMD_TYPE='I';
\timing
