\echo -----------------------BANK_ACCOUNT------------------------
select now();
\timing
delete from BANK_ACCOUNT using BANK_ACCOUNT_GPTMP_TODAY where BANK_ACCOUNT.MANUAL_NO=BANK_ACCOUNT_GPTMP_TODAY.MANUAL_NO AND BANK_ACCOUNT.ID_STAT=BANK_ACCOUNT_GPTMP_TODAY.ID_STAT AND BANK_ACCOUNT.RECEIVE_DATE=BANK_ACCOUNT_GPTMP_TODAY.RECEIVE_DATE ;
insert into BANK_ACCOUNT (MANUAL_NO,ID_STAT,RECEIVE_DATE,M_CONTR_NO,M_OWNER_NAME,M_LIMIT_DATE,M_ACCOUNT_AMT,M_DEAL_MARK,M_TYPE_DATE,M_BANK_NOTE_NO,M_BANK_OPEN_DATE,M_BANK_NOTE_DATE,M_APPR_DATE,M_NEXT_FLAG,CONTR_NO,OWNER_NAME,LIMIT_DATE,ACCOUNT_AMT,DEAL_MARK,TYPE_DATE,BANK_NOTE_NO,BANK_OPEN_DATE,BANK_NOTE_DATE,APPR_DATE,BANK_ID,NEXT_FLAG,PORT_CODE,COMP_RESULT) select MANUAL_NO,ID_STAT,RECEIVE_DATE,M_CONTR_NO,M_OWNER_NAME,M_LIMIT_DATE,M_ACCOUNT_AMT,M_DEAL_MARK,M_TYPE_DATE,M_BANK_NOTE_NO,M_BANK_OPEN_DATE,M_BANK_NOTE_DATE,M_APPR_DATE,M_NEXT_FLAG,CONTR_NO,OWNER_NAME,LIMIT_DATE,ACCOUNT_AMT,DEAL_MARK,TYPE_DATE,BANK_NOTE_NO,BANK_OPEN_DATE,BANK_NOTE_DATE,APPR_DATE,BANK_ID,NEXT_FLAG,PORT_CODE,COMP_RESULT from BANK_ACCOUNT_GPTMP_TODAY  where CMD_TYPE='I';
\timing
