\echo -----------------------BCK_COP_LIST_TEMP------------------------
select now();
\timing
delete from BCK_COP_LIST_TEMP using BCK_COP_LIST_TEMP_GPTMP_TODAY where BCK_COP_LIST_TEMP.TRADE_CO=BCK_COP_LIST_TEMP_GPTMP_TODAY.TRADE_CO AND BCK_COP_LIST_TEMP.RISK_NO=BCK_COP_LIST_TEMP_GPTMP_TODAY.RISK_NO AND BCK_COP_LIST_TEMP.CUSTOMS_CODE=BCK_COP_LIST_TEMP_GPTMP_TODAY.CUSTOMS_CODE ;
insert into BCK_COP_LIST_TEMP (TRADE_CO,RISK_NO,CUSTOMS_CODE,RISK_VALUE,VALUE) select TRADE_CO,RISK_NO,CUSTOMS_CODE,RISK_VALUE,VALUE from BCK_COP_LIST_TEMP_GPTMP_TODAY  where CMD_TYPE='I';
\timing
