\echo -----------------------BCK_WORKFLOW------------------------
select now();
\timing
delete from BCK_WORKFLOW using BCK_WORKFLOW_GPTMP_TODAY where BCK_WORKFLOW.BCK_NO=BCK_WORKFLOW_GPTMP_TODAY.BCK_NO AND BCK_WORKFLOW.STEP_ID=BCK_WORKFLOW_GPTMP_TODAY.STEP_ID AND BCK_WORKFLOW.OPER_ID=BCK_WORKFLOW_GPTMP_TODAY.OPER_ID AND BCK_WORKFLOW.CREATE_DATE=BCK_WORKFLOW_GPTMP_TODAY.CREATE_DATE ;
insert into BCK_WORKFLOW (BCK_NO,CREATE_DATE,STEP_ID,OPER_ID,NOTE,OPER_ER,REALTIVE_NO) select BCK_NO,CREATE_DATE,STEP_ID,OPER_ID,NOTE,OPER_ER,REALTIVE_NO from BCK_WORKFLOW_GPTMP_TODAY  where CMD_TYPE='I';
\timing
