\echo -----------------------BCK_HANDOVER------------------------
select now();
\timing
delete from BCK_HANDOVER using BCK_HANDOVER_GPTMP_TODAY where BCK_HANDOVER.HANDOVER_NO=BCK_HANDOVER_GPTMP_TODAY.HANDOVER_NO ;
insert into BCK_HANDOVER (HANDOVER_NO,CREATE_DATE,HANDOVER_TYPE,HANDOVER_DEP,ACCEPT_DEP,SUSPECT_CO,SUSPECT_ER,SUSPECT_NOTE,ACCEPT_STATUS,SUSPECT_STATUS,SUSPECT_AMT,FEEDBACK,ADDENDA_LIST,OTHER_DOC,ACTOR_NOTION,MASTER_NOTION,DEP_NOTION) select HANDOVER_NO,CREATE_DATE,HANDOVER_TYPE,HANDOVER_DEP,ACCEPT_DEP,SUSPECT_CO,SUSPECT_ER,SUSPECT_NOTE,ACCEPT_STATUS,SUSPECT_STATUS,SUSPECT_AMT,FEEDBACK,ADDENDA_LIST,OTHER_DOC,ACTOR_NOTION,MASTER_NOTION,DEP_NOTION from BCK_HANDOVER_GPTMP_TODAY  where CMD_TYPE='I';
\timing
