\echo -----------------------BCK_STOCK_LIST------------------------
select now();
\timing
delete from BCK_STOCK_LIST using BCK_STOCK_LIST_GPTMP_TODAY where BCK_STOCK_LIST.SEQ_NO=BCK_STOCK_LIST_GPTMP_TODAY.SEQ_NO AND BCK_STOCK_LIST.LIST_NO=BCK_STOCK_LIST_GPTMP_TODAY.LIST_NO ;
insert into BCK_STOCK_LIST (SEQ_NO,LIST_NO,TRADE_CODE,COP_INNER_NO,ITEM_NO,CODE_T_S,G_NAME,G_MODEL,UNIT,IMG_STOCK_QTY,IMG_ONLINE_QTY,IMG_IN_QTY,EXG_CONV_QTY,OUT_IMG_QTY,ABAN_QTY,ON_WAY_QTY,T_STOCK_QTY) select SEQ_NO,LIST_NO,TRADE_CODE,COP_INNER_NO,ITEM_NO,CODE_T_S,G_NAME,G_MODEL,UNIT,IMG_STOCK_QTY,IMG_ONLINE_QTY,IMG_IN_QTY,EXG_CONV_QTY,OUT_IMG_QTY,ABAN_QTY,ON_WAY_QTY,T_STOCK_QTY from BCK_STOCK_LIST_GPTMP_TODAY  where CMD_TYPE='I';
\timing
