\echo -----------------------BCK_HANDOVER_TYPE------------------------
select now();
\timing
delete from BCK_HANDOVER_TYPE using BCK_HANDOVER_TYPE_GPTMP_TODAY where BCK_HANDOVER_TYPE.HANDOVER_TYPE=BCK_HANDOVER_TYPE_GPTMP_TODAY.HANDOVER_TYPE AND BCK_HANDOVER_TYPE.ID=BCK_HANDOVER_TYPE_GPTMP_TODAY.ID ;
insert into BCK_HANDOVER_TYPE (HANDOVER_TYPE,ID,DESCRIPTION) select HANDOVER_TYPE,ID,DESCRIPTION from BCK_HANDOVER_TYPE_GPTMP_TODAY  where CMD_TYPE='I';
\timing
