\echo -----------------------BCK_COP_PARA_HEAD------------------------
select now();
\timing
delete from BCK_COP_PARA_HEAD using BCK_COP_PARA_HEAD_GPTMP_TODAY where BCK_COP_PARA_HEAD.RISK_NO=BCK_COP_PARA_HEAD_GPTMP_TODAY.RISK_NO AND BCK_COP_PARA_HEAD.CUSTOMS_CODE=BCK_COP_PARA_HEAD_GPTMP_TODAY.CUSTOMS_CODE ;
insert into BCK_COP_PARA_HEAD (RISK_NO,CUSTOMS_CODE,RISK_NAME,RISK_DESC,WEIGHT_VALUE,WEIGHT_TYPE,DEGREE,SOURCE,SWITCH,NOTE) select RISK_NO,CUSTOMS_CODE,RISK_NAME,RISK_DESC,WEIGHT_VALUE,WEIGHT_TYPE,DEGREE,SOURCE,SWITCH,NOTE from BCK_COP_PARA_HEAD_GPTMP_TODAY  where CMD_TYPE='I';
\timing
