\echo -----------------------BCK_COP_LIST------------------------
select now();
\timing
delete from BCK_COP_LIST using BCK_COP_LIST_GPTMP_TODAY where BCK_COP_LIST.TRADE_CODE=BCK_COP_LIST_GPTMP_TODAY.TRADE_CODE AND BCK_COP_LIST.RISK_NO=BCK_COP_LIST_GPTMP_TODAY.RISK_NO AND BCK_COP_LIST.CUSTOMS_CODE=BCK_COP_LIST_GPTMP_TODAY.CUSTOMS_CODE ;
insert into BCK_COP_LIST (TRADE_CODE,RISK_NO,CUSTOMS_CODE,RISK_VALUE) select TRADE_CODE,RISK_NO,CUSTOMS_CODE,RISK_VALUE from BCK_COP_LIST_GPTMP_TODAY  where CMD_TYPE='I';
\timing
