\echo -----------------------BCK_COP_PARA_LIST------------------------
select now();
\timing
delete from BCK_COP_PARA_LIST using BCK_COP_PARA_LIST_GPTMP_TODAY where BCK_COP_PARA_LIST.RISK_NO=BCK_COP_PARA_LIST_GPTMP_TODAY.RISK_NO AND BCK_COP_PARA_LIST.RISK_VALUE=BCK_COP_PARA_LIST_GPTMP_TODAY.RISK_VALUE AND BCK_COP_PARA_LIST.CUSTOMS_CODE=BCK_COP_PARA_LIST_GPTMP_TODAY.CUSTOMS_CODE ;
insert into BCK_COP_PARA_LIST (RISK_NO,RISK_VALUE,CUSTOMS_CODE,RISK_LIST_DESC) select RISK_NO,RISK_VALUE,CUSTOMS_CODE,RISK_LIST_DESC from BCK_COP_PARA_LIST_GPTMP_TODAY  where CMD_TYPE='I';
\timing
