\echo -----------------------BCK_EXECUTOR------------------------
select now();
\timing
delete from BCK_EXECUTOR using BCK_EXECUTOR_GPTMP_TODAY where BCK_EXECUTOR.BCK_NO=BCK_EXECUTOR_GPTMP_TODAY.BCK_NO AND BCK_EXECUTOR.EXECUTOR=BCK_EXECUTOR_GPTMP_TODAY.EXECUTOR ;
insert into BCK_EXECUTOR (BCK_NO,EXECUTOR) select BCK_NO,EXECUTOR from BCK_EXECUTOR_GPTMP_TODAY  where CMD_TYPE='I';
\timing
