\echo -----------------------BTI_DATA_CONTA_LIST------------------------
select now();
\timing
delete from BTI_DATA_CONTA_LIST using BTI_DATA_CONTA_LIST_GPTMP_TODAY where BTI_DATA_CONTA_LIST.UCR_CODE=BTI_DATA_CONTA_LIST_GPTMP_TODAY.UCR_CODE AND BTI_DATA_CONTA_LIST.CONTAINER_ID=BTI_DATA_CONTA_LIST_GPTMP_TODAY.CONTAINER_ID ;
insert into BTI_DATA_CONTA_LIST (UCR_CODE,CONTAINER_ID,SEAL_NO) select UCR_CODE,CONTAINER_ID,SEAL_NO from BTI_DATA_CONTA_LIST_GPTMP_TODAY  where CMD_TYPE='I';
\timing
