\echo -----------------------BTI_DATA_TS_LIST------------------------
select now();
\timing
delete from BTI_DATA_TS_LIST using BTI_DATA_TS_LIST_GPTMP_TODAY where BTI_DATA_TS_LIST.UCR_CODE=BTI_DATA_TS_LIST_GPTMP_TODAY.UCR_CODE AND BTI_DATA_TS_LIST.G_NO=BTI_DATA_TS_LIST_GPTMP_TODAY.G_NO ;
insert into BTI_DATA_TS_LIST (UCR_CODE,G_NO,CODE_TS,G_NAME,PACK_NO) select UCR_CODE,G_NO,CODE_TS,G_NAME,PACK_NO from BTI_DATA_TS_LIST_GPTMP_TODAY  where CMD_TYPE='I';
\timing
