\echo -----------------------BWS_GB_LIST------------------------
select now();
\timing
delete from BWS_GB_LIST using BWS_GB_LIST_GPTMP_TODAY where BWS_GB_LIST.BWS_NO=BWS_GB_LIST_GPTMP_TODAY.BWS_NO AND BWS_GB_LIST.G_NO=BWS_GB_LIST_GPTMP_TODAY.G_NO ;
insert into BWS_GB_LIST (BWS_NO,G_NO,BWS_G_NO,COP_G_NO,CODE_TS,CLASS_MARK,G_NAME,G_MODEL,UNIT,UNIT_1,UNIT_2,DEC_PRICE,CURR,COUNTRY_CODE,DUTY_MODE,USE_TYPE,MODIFY_MARK,NOTE) select BWS_NO,G_NO,BWS_G_NO,COP_G_NO,CODE_TS,CLASS_MARK,G_NAME,G_MODEL,UNIT,UNIT_1,UNIT_2,DEC_PRICE,CURR,COUNTRY_CODE,DUTY_MODE,USE_TYPE,MODIFY_MARK,NOTE from BWS_GB_LIST_GPTMP_TODAY  where CMD_TYPE='I';
\timing
