\echo -----------------------BWS_VAR------------------------
select now();
\timing
delete from BWS_VAR using BWS_VAR_GPTMP_TODAY where BWS_VAR.VAR_TYPE=BWS_VAR_GPTMP_TODAY.VAR_TYPE AND BWS_VAR.VAR_ID=BWS_VAR_GPTMP_TODAY.VAR_ID AND BWS_VAR.VAR_SUB_ID=BWS_VAR_GPTMP_TODAY.VAR_SUB_ID AND BWS_VAR.CUSTOMS_CODE=BWS_VAR_GPTMP_TODAY.CUSTOMS_CODE ;
insert into BWS_VAR (VAR_TYPE,VAR_ID,VAR_SUB_ID,CUSTOMS_CODE,VAR_VALUE,VAR_VALUE1,VAR_VALUE2,VAR_VALUE3,VAR_DESC,MODIFY_TIME,VAR_ENABLED) select VAR_TYPE,VAR_ID,VAR_SUB_ID,CUSTOMS_CODE,VAR_VALUE,VAR_VALUE1,VAR_VALUE2,VAR_VALUE3,VAR_DESC,MODIFY_TIME,VAR_ENABLED from BWS_VAR_GPTMP_TODAY  where CMD_TYPE='I';
\timing
