\echo -----------------------BWS_WORKFLOW------------------------
select now();
\timing
delete from BWS_WORKFLOW using BWS_WORKFLOW_GPTMP_TODAY where BWS_WORKFLOW.BWS_ID=BWS_WORKFLOW_GPTMP_TODAY.BWS_ID AND BWS_WORKFLOW.STEP_ID=BWS_WORKFLOW_GPTMP_TODAY.STEP_ID AND BWS_WORKFLOW.CREATE_DATE=BWS_WORKFLOW_GPTMP_TODAY.CREATE_DATE ;
insert into BWS_WORKFLOW (BWS_ID,STEP_ID,CREATE_DATE,PROC_ER,PROC_ID,PROC_POS,PROC_RESULT) select BWS_ID,STEP_ID,CREATE_DATE,PROC_ER,PROC_ID,PROC_POS,PROC_RESULT from BWS_WORKFLOW_GPTMP_TODAY  where CMD_TYPE='I';
\timing
