\echo -----------------------BWS_AUDIT_LIST------------------------
select now();
\timing
delete from BWS_AUDIT_LIST using BWS_AUDIT_LIST_GPTMP_TODAY where BWS_AUDIT_LIST.AUDIT_NO=BWS_AUDIT_LIST_GPTMP_TODAY.AUDIT_NO AND BWS_AUDIT_LIST.G_NO=BWS_AUDIT_LIST_GPTMP_TODAY.G_NO ;
insert into BWS_AUDIT_LIST (AUDIT_NO,G_NO,G_TYPE,CODE_TS,G_NAME,G_MODEL,BWS_G_NO,QTY,UNIT,AMOUNT,CURR) select AUDIT_NO,G_NO,G_TYPE,CODE_TS,G_NAME,G_MODEL,BWS_G_NO,QTY,UNIT,AMOUNT,CURR from BWS_AUDIT_LIST_GPTMP_TODAY  where CMD_TYPE='I';
\timing
