\echo -----------------------BWS_EXAM_PASSCERT------------------------
select now();
\timing
delete from BWS_EXAM_PASSCERT using BWS_EXAM_PASSCERT_GPTMP_TODAY where BWS_EXAM_PASSCERT.CERT_NO=BWS_EXAM_PASSCERT_GPTMP_TODAY.CERT_NO ;
insert into BWS_EXAM_PASSCERT (CERT_NO,CERT_TYPE,FLAG,FLAG1,CREATE_DATE,NOTE) select CERT_NO,CERT_TYPE,FLAG,FLAG1,CREATE_DATE,NOTE from BWS_EXAM_PASSCERT_GPTMP_TODAY  where CMD_TYPE='I';
\timing
