\echo -----------------------BWS_MANIFEST_HEAD------------------------
select now();
\timing
delete from BWS_MANIFEST_HEAD using BWS_MANIFEST_HEAD_GPTMP_TODAY where BWS_MANIFEST_HEAD.BWS_MANIFEST_NO=BWS_MANIFEST_HEAD_GPTMP_TODAY.BWS_MANIFEST_NO ;
insert into BWS_MANIFEST_HEAD (BWS_MANIFEST_NO,EPORT_NO,BWS_NO,MASTER_CUSTOMS,DECLARE_CODE,DECLARE_NAME,DECLARE_DATE,I_E_DATE,I_E_PORT,TRAF_MODE,MANIFEST_NO,SHIP_ID,VOYAGE_NO,SHIP_NAME_CN,SHIP_NAME_EN,BILL_NUM,PACK_NO,GROSS_WT,CONTA_NUM,CHK_MARK,DESTINATION_PLACE) select BWS_MANIFEST_NO,EPORT_NO,BWS_NO,MASTER_CUSTOMS,DECLARE_CODE,DECLARE_NAME,DECLARE_DATE,I_E_DATE,I_E_PORT,TRAF_MODE,MANIFEST_NO,SHIP_ID,VOYAGE_NO,SHIP_NAME_CN,SHIP_NAME_EN,BILL_NUM,PACK_NO,GROSS_WT,CONTA_NUM,CHK_MARK,DESTINATION_PLACE from BWS_MANIFEST_HEAD_GPTMP_TODAY  where CMD_TYPE='I';
\timing
