\echo -----------------------BWS_DCR_LIST------------------------
select now();
\timing
delete from BWS_DCR_LIST using BWS_DCR_LIST_GPTMP_TODAY where BWS_DCR_LIST.BWS_NO=BWS_DCR_LIST_GPTMP_TODAY.BWS_NO AND BWS_DCR_LIST.DCR_TIMES=BWS_DCR_LIST_GPTMP_TODAY.DCR_TIMES AND BWS_DCR_LIST.G_NO=BWS_DCR_LIST_GPTMP_TODAY.G_NO ;
insert into BWS_DCR_LIST (BWS_NO,DCR_TIMES,G_NO,COP_G_NO,CODE_TS,G_NAME,G_MODEL,REMAIN_QTY,FACT_REMAIN_QTY,UNIT,REMAIN_AMOUNT,FACT_REMAIN_AMOUNT,CURR,NOTE,QTY,AMOUNT,H_REMAIN_QTY,H_REMAIN_AMOUNT) select BWS_NO,DCR_TIMES,G_NO,COP_G_NO,CODE_TS,G_NAME,G_MODEL,REMAIN_QTY,FACT_REMAIN_QTY,UNIT,REMAIN_AMOUNT,FACT_REMAIN_AMOUNT,CURR,NOTE,QTY,AMOUNT,H_REMAIN_QTY,H_REMAIN_AMOUNT from BWS_DCR_LIST_GPTMP_TODAY  where CMD_TYPE='I';
\timing
