\echo -----------------------BWS_DEDUCT_LOG------------------------
select now();
\timing
delete from BWS_DEDUCT_LOG using BWS_DEDUCT_LOG_GPTMP_TODAY where BWS_DEDUCT_LOG.BWS_ID=BWS_DEDUCT_LOG_GPTMP_TODAY.BWS_ID AND BWS_DEDUCT_LOG.BWS_NO=BWS_DEDUCT_LOG_GPTMP_TODAY.BWS_NO AND BWS_DEDUCT_LOG.CREATE_DATE=BWS_DEDUCT_LOG_GPTMP_TODAY.CREATE_DATE AND BWS_DEDUCT_LOG.JOU_MARK=BWS_DEDUCT_LOG_GPTMP_TODAY.JOU_MARK ;
insert into BWS_DEDUCT_LOG (BWS_ID,BWS_NO,CREATE_DATE,JOU_MARK,NOTE,VERIFY_ER) select BWS_ID,BWS_NO,CREATE_DATE,JOU_MARK,NOTE,VERIFY_ER from BWS_DEDUCT_LOG_GPTMP_TODAY  where CMD_TYPE='I';
\timing
