\echo -----------------------BWS_EXAM_GOOD_LIST------------------------
select now();
\timing
delete from BWS_EXAM_GOOD_LIST using BWS_EXAM_GOOD_LIST_GPTMP_TODAY where BWS_EXAM_GOOD_LIST.BWS_EXAM_NO=BWS_EXAM_GOOD_LIST_GPTMP_TODAY.BWS_EXAM_NO AND BWS_EXAM_GOOD_LIST.G_NO=BWS_EXAM_GOOD_LIST_GPTMP_TODAY.G_NO ;
insert into BWS_EXAM_GOOD_LIST (BWS_EXAM_NO,G_NO,CERT_NO,CERT_G_NO,G_NAME,QTY,UNIT) select BWS_EXAM_NO,G_NO,CERT_NO,CERT_G_NO,G_NAME,QTY,UNIT from BWS_EXAM_GOOD_LIST_GPTMP_TODAY  where CMD_TYPE='I';
\timing
