\echo -----------------------CCTS_PERFORMANCE------------------------
select now();
\timing
delete from CCTS_PERFORMANCE using CCTS_PERFORMANCE_GPTMP_TODAY where CCTS_PERFORMANCE.SEQUENCE_NO=CCTS_PERFORMANCE_GPTMP_TODAY.SEQUENCE_NO ;
insert into CCTS_PERFORMANCE (SEQUENCE_NO,FORM_TYPE,ENTRY_ID,CUSTOMS_CODE,CREATE_DATE,DEL_DIGIT,MODI_DIGIT,REJECT_DIGIT,VAL_DIGIT,CHK_DIGIT,FIT_DIGIT,SPARE_DIGIT,VAL_TOTAL,NOTE) select SEQUENCE_NO,FORM_TYPE,ENTRY_ID,CUSTOMS_CODE,CREATE_DATE,DEL_DIGIT,MODI_DIGIT,REJECT_DIGIT,VAL_DIGIT,CHK_DIGIT,FIT_DIGIT,SPARE_DIGIT,VAL_TOTAL,NOTE from CCTS_PERFORMANCE_GPTMP_TODAY  where CMD_TYPE='I';
\timing
