\echo -----------------------CCTS_ERROR_LOG------------------------
select now();
\timing
delete from CCTS_ERROR_LOG using CCTS_ERROR_LOG_GPTMP_TODAY where CCTS_ERROR_LOG.SEQUENCE_NO=CCTS_ERROR_LOG_GPTMP_TODAY.SEQUENCE_NO ;
insert into CCTS_ERROR_LOG (SEQUENCE_NO,FORM_TYPE,ENTRY_ID,G_NO,POSITION_ID,SUB_POSITION_ID,COMMENTS,CREATE_DATE) select SEQUENCE_NO,FORM_TYPE,ENTRY_ID,G_NO,POSITION_ID,SUB_POSITION_ID,COMMENTS,CREATE_DATE from CCTS_ERROR_LOG_GPTMP_TODAY  where CMD_TYPE='I';
\timing
