\echo -----------------------CDL_ENTRY_HEAD------------------------
select now();
\timing
delete from CDL_ENTRY_HEAD using CDL_ENTRY_HEAD_GPTMP_TODAY where CDL_ENTRY_HEAD.PRE_ENTRY_ID=CDL_ENTRY_HEAD_GPTMP_TODAY.PRE_ENTRY_ID ;
insert into CDL_ENTRY_HEAD (PRE_ENTRY_ID,ENTRY_ID,LIST_DATE,I_E_PORT,TRADE_CO,OWNER_CODE,TRADE_MODE,TRADE_COUNTRY,DESTINATION_PORT,TRAF_MODE,DECL_PORT,MANUAL_NO) select PRE_ENTRY_ID,ENTRY_ID,LIST_DATE,I_E_PORT,TRADE_CO,OWNER_CODE,TRADE_MODE,TRADE_COUNTRY,DESTINATION_PORT,TRAF_MODE,DECL_PORT,MANUAL_NO from CDL_ENTRY_HEAD_GPTMP_TODAY  where CMD_TYPE='I';
\timing
