\echo -----------------------CDL_STATUS_DETAIL------------------------
select now();
\timing
delete from CDL_STATUS_DETAIL using CDL_STATUS_DETAIL_GPTMP_TODAY where CDL_STATUS_DETAIL.LIST_NO=CDL_STATUS_DETAIL_GPTMP_TODAY.LIST_NO AND CDL_STATUS_DETAIL.DETAIL_COUNT=CDL_STATUS_DETAIL_GPTMP_TODAY.DETAIL_COUNT ;
insert into CDL_STATUS_DETAIL (LIST_NO,DETAIL_COUNT,STATUS_NUMBER,STATUS_RESULT,STATUS_DETAIL) select LIST_NO,DETAIL_COUNT,STATUS_NUMBER,STATUS_RESULT,STATUS_DETAIL from CDL_STATUS_DETAIL_GPTMP_TODAY  where CMD_TYPE='I';
\timing
