\echo -----------------------CDL_CONTAINER------------------------
select now();
\timing
delete from CDL_CONTAINER using CDL_CONTAINER_GPTMP_TODAY where CDL_CONTAINER.LIST_NO=CDL_CONTAINER_GPTMP_TODAY.LIST_NO AND CDL_CONTAINER.CONTAINER_ID=CDL_CONTAINER_GPTMP_TODAY.CONTAINER_ID ;
insert into CDL_CONTAINER (LIST_NO,CONTAINER_ID,CONTAINER_WT) select LIST_NO,CONTAINER_ID,CONTAINER_WT from CDL_CONTAINER_GPTMP_TODAY  where CMD_TYPE='I';
\timing
