\echo -----------------------CDL_WORKFLOW------------------------
select now();
\timing
delete from CDL_WORKFLOW using CDL_WORKFLOW_GPTMP_TODAY where CDL_WORKFLOW.LIST_NO=CDL_WORKFLOW_GPTMP_TODAY.LIST_NO AND CDL_WORKFLOW.STEP_ID=CDL_WORKFLOW_GPTMP_TODAY.STEP_ID AND CDL_WORKFLOW.CREATE_DATE=CDL_WORKFLOW_GPTMP_TODAY.CREATE_DATE ;
insert into CDL_WORKFLOW (LIST_NO,STEP_ID,CREATE_DATE,PROC_POS,STATUS_CODE,PROC_ER,PROC_RESULT,PREV_POS,PREV_ER,RECHK_MARK,RECHK_COMM) select LIST_NO,STEP_ID,CREATE_DATE,PROC_POS,STATUS_CODE,PROC_ER,PROC_RESULT,PREV_POS,PREV_ER,RECHK_MARK,RECHK_COMM from CDL_WORKFLOW_GPTMP_TODAY  where CMD_TYPE='I';
\timing
