\echo -----------------------CDL_COMMODITY------------------------
select now();
\timing
delete from CDL_COMMODITY using CDL_COMMODITY_GPTMP_TODAY where CDL_COMMODITY.RECORDS_NO=CDL_COMMODITY_GPTMP_TODAY.RECORDS_NO AND CDL_COMMODITY.G_NO=CDL_COMMODITY_GPTMP_TODAY.G_NO ;
insert into CDL_COMMODITY (RECORDS_NO,PRE_RECORDS_NO,TRADE_CO,G_NO,FIT_FLAG,CODE_TS,G_NAME,G_MODEL,G_UNIT,DECL_PRICE,TRADE_CURR,I_E_FLAG,ORIGIN_COUNTRY,DISTRICT_CODE,LICENSE_NO,LICENSE_COUNT,LICENSE_DATE,MOD_TYPE,CUSTOMS_CODE) select RECORDS_NO,PRE_RECORDS_NO,TRADE_CO,G_NO,FIT_FLAG,CODE_TS,G_NAME,G_MODEL,G_UNIT,DECL_PRICE,TRADE_CURR,I_E_FLAG,ORIGIN_COUNTRY,DISTRICT_CODE,LICENSE_NO,LICENSE_COUNT,LICENSE_DATE,MOD_TYPE,CUSTOMS_CODE from CDL_COMMODITY_GPTMP_TODAY  where CMD_TYPE='I';
\timing
