\echo -----------------------CDL_COMP_COMM_MODIFY_LOG------------------------
select now();
\timing
delete from CDL_COMP_COMM_MODIFY_LOG using CDL_COMP_COMM_MODIFY_LOG_GPTMP_TODAY where CDL_COMP_COMM_MODIFY_LOG.TRADE_CO=CDL_COMP_COMM_MODIFY_LOG_GPTMP_TODAY.TRADE_CO AND CDL_COMP_COMM_MODIFY_LOG.OP_TIME=CDL_COMP_COMM_MODIFY_LOG_GPTMP_TODAY.OP_TIME AND CDL_COMP_COMM_MODIFY_LOG.MODI_TYPE=CDL_COMP_COMM_MODIFY_LOG_GPTMP_TODAY.MODI_TYPE AND CDL_COMP_COMM_MODIFY_LOG.ITEM_NAME=CDL_COMP_COMM_MODIFY_LOG_GPTMP_TODAY.ITEM_NAME ;
insert into CDL_COMP_COMM_MODIFY_LOG (TRADE_CO,RECORDS_NO,OP_TIME,MODI_TYPE,ITEM_NAME,ITEM_SOURCE,ITEM_CURRENT,NOTES,CUSTOMS_CODE) select TRADE_CO,RECORDS_NO,OP_TIME,MODI_TYPE,ITEM_NAME,ITEM_SOURCE,ITEM_CURRENT,NOTES,CUSTOMS_CODE from CDL_COMP_COMM_MODIFY_LOG_GPTMP_TODAY  where CMD_TYPE='I';
\timing
