\echo -----------------------CDL_EMS_DEDUCT_LOG------------------------
select now();
\timing
delete from CDL_EMS_DEDUCT_LOG using CDL_EMS_DEDUCT_LOG_GPTMP_TODAY where CDL_EMS_DEDUCT_LOG.ENTRY_ID=CDL_EMS_DEDUCT_LOG_GPTMP_TODAY.ENTRY_ID AND CDL_EMS_DEDUCT_LOG.EMS_NO=CDL_EMS_DEDUCT_LOG_GPTMP_TODAY.EMS_NO AND CDL_EMS_DEDUCT_LOG.CREATE_DATE=CDL_EMS_DEDUCT_LOG_GPTMP_TODAY.CREATE_DATE AND CDL_EMS_DEDUCT_LOG.JOU_MARK=CDL_EMS_DEDUCT_LOG_GPTMP_TODAY.JOU_MARK ;
insert into CDL_EMS_DEDUCT_LOG (ENTRY_ID,EMS_NO,CREATE_DATE,JOU_MARK,NOTE,VERIFY_ER) select ENTRY_ID,EMS_NO,CREATE_DATE,JOU_MARK,NOTE,VERIFY_ER from CDL_EMS_DEDUCT_LOG_GPTMP_TODAY  where CMD_TYPE='I';
\timing
