\echo -----------------------CDL_LICENSE_DEDUCT------------------------
select now();
\timing
delete from CDL_LICENSE_DEDUCT using CDL_LICENSE_DEDUCT_GPTMP_TODAY where CDL_LICENSE_DEDUCT.LIST_NO=CDL_LICENSE_DEDUCT_GPTMP_TODAY.LIST_NO AND CDL_LICENSE_DEDUCT.G_NO=CDL_LICENSE_DEDUCT_GPTMP_TODAY.G_NO AND CDL_LICENSE_DEDUCT.TRADE_CO=CDL_LICENSE_DEDUCT_GPTMP_TODAY.TRADE_CO AND CDL_LICENSE_DEDUCT.OP_TIME=CDL_LICENSE_DEDUCT_GPTMP_TODAY.OP_TIME ;
insert into CDL_LICENSE_DEDUCT (LIST_NO,G_NO,TRADE_CO,QTY_ORI,QTY,DEDUCT_MODE,OP_TIME,OP_ER) select LIST_NO,G_NO,TRADE_CO,QTY_ORI,QTY,DEDUCT_MODE,OP_TIME,OP_ER from CDL_LICENSE_DEDUCT_GPTMP_TODAY  where CMD_TYPE='I';
\timing
