\echo -----------------------CDL_DEL_CONTAINER_LOG------------------------
select now();
\timing
delete from CDL_DEL_CONTAINER_LOG using CDL_DEL_CONTAINER_LOG_GPTMP_TODAY where CDL_DEL_CONTAINER_LOG.LIST_NO=CDL_DEL_CONTAINER_LOG_GPTMP_TODAY.LIST_NO AND CDL_DEL_CONTAINER_LOG.CONTAINER_ID=CDL_DEL_CONTAINER_LOG_GPTMP_TODAY.CONTAINER_ID AND CDL_DEL_CONTAINER_LOG.CONTAINER_WT=CDL_DEL_CONTAINER_LOG_GPTMP_TODAY.CONTAINER_WT ;
insert into CDL_DEL_CONTAINER_LOG (LIST_NO,CONTAINER_ID,CONTAINER_WT) select LIST_NO,CONTAINER_ID,CONTAINER_WT from CDL_DEL_CONTAINER_LOG_GPTMP_TODAY  where CMD_TYPE='I';
\timing
