\echo -----------------------CDL_COMPANY------------------------
select now();
\timing
delete from CDL_COMPANY using CDL_COMPANY_GPTMP_TODAY where CDL_COMPANY.TRADE_CO=CDL_COMPANY_GPTMP_TODAY.TRADE_CO AND CDL_COMPANY.CUSTOMS_CODE=CDL_COMPANY_GPTMP_TODAY.CUSTOMS_CODE AND CDL_COMPANY.TRADE_BONDED_FLAG=CDL_COMPANY_GPTMP_TODAY.TRADE_BONDED_FLAG ;
insert into CDL_COMPANY (TRADE_CO,TRADE_NAME,CUSTOMS_CODE,APP_MOD_FLAG,TRADE_BONDED_FLAG,GRT_TYPE,GRT_PRICE,GRT_DATE,APPROVE_DATE,IE_COUNT,PRE_COP_NO) select TRADE_CO,TRADE_NAME,CUSTOMS_CODE,APP_MOD_FLAG,TRADE_BONDED_FLAG,GRT_TYPE,GRT_PRICE,GRT_DATE,APPROVE_DATE,IE_COUNT,PRE_COP_NO from CDL_COMPANY_GPTMP_TODAY  where CMD_TYPE='I';
\timing
