\echo -----------------------CDL_DEL_CERTIFICATE_LOG------------------------
select now();
\timing
delete from CDL_DEL_CERTIFICATE_LOG using CDL_DEL_CERTIFICATE_LOG_GPTMP_TODAY where CDL_DEL_CERTIFICATE_LOG.LIST_NO=CDL_DEL_CERTIFICATE_LOG_GPTMP_TODAY.LIST_NO AND CDL_DEL_CERTIFICATE_LOG.DOCU_CODE=CDL_DEL_CERTIFICATE_LOG_GPTMP_TODAY.DOCU_CODE AND CDL_DEL_CERTIFICATE_LOG.CERT_CODE=CDL_DEL_CERTIFICATE_LOG_GPTMP_TODAY.CERT_CODE ;
insert into CDL_DEL_CERTIFICATE_LOG (LIST_NO,DOCU_CODE,CERT_CODE) select LIST_NO,DOCU_CODE,CERT_CODE from CDL_DEL_CERTIFICATE_LOG_GPTMP_TODAY  where CMD_TYPE='I';
\timing
