\echo -----------------------CHK_COUNTER------------------------
select now();
\timing
delete from CHK_COUNTER using CHK_COUNTER_GPTMP_TODAY where CHK_COUNTER.CUSTOMS_CODE=CHK_COUNTER_GPTMP_TODAY.CUSTOMS_CODE AND CHK_COUNTER.I_E_FLAG=CHK_COUNTER_GPTMP_TODAY.I_E_FLAG AND CHK_COUNTER.COUNTER_TYPE=CHK_COUNTER_GPTMP_TODAY.COUNTER_TYPE AND CHK_COUNTER.COUNT_DATE=CHK_COUNTER_GPTMP_TODAY.COUNT_DATE ;
insert into CHK_COUNTER (CUSTOMS_CODE,I_E_FLAG,COUNTER_TYPE,COUNT_DATE,COUNTER) select CUSTOMS_CODE,I_E_FLAG,COUNTER_TYPE,COUNT_DATE,COUNTER from CHK_COUNTER_GPTMP_TODAY  where CMD_TYPE='I';
\timing
