\echo -----------------------CHK_RATE_LIMIT------------------------
select now();
\timing
delete from CHK_RATE_LIMIT using CHK_RATE_LIMIT_GPTMP_TODAY where CHK_RATE_LIMIT.CUSTOMS_CODE=CHK_RATE_LIMIT_GPTMP_TODAY.CUSTOMS_CODE AND CHK_RATE_LIMIT.I_E_FLAG=CHK_RATE_LIMIT_GPTMP_TODAY.I_E_FLAG ;
insert into CHK_RATE_LIMIT (CUSTOMS_CODE,I_E_FLAG,MAX_CHK_RATE,MAX_OPEN_RATE,RANDOM_CHK_RATE) select CUSTOMS_CODE,I_E_FLAG,MAX_CHK_RATE,MAX_OPEN_RATE,RANDOM_CHK_RATE from CHK_RATE_LIMIT_GPTMP_TODAY  where CMD_TYPE='I';
\timing
