\echo -----------------------CHKHS_MNLPROC------------------------
select now();
\timing
delete from CHKHS_MNLPROC using CHKHS_MNLPROC_GPTMP_TODAY where CHKHS_MNLPROC.ORDER_NO=CHKHS_MNLPROC_GPTMP_TODAY.ORDER_NO AND CHKHS_MNLPROC.MANUAL_SCH=CHKHS_MNLPROC_GPTMP_TODAY.MANUAL_SCH ;
insert into CHKHS_MNLPROC (MANUAL_NO,PRE_MANUAL_NO,ORDER_NO,MANUAL_SCH,M_FLAG,TRADE_NAME,OPER_ER,OPER_DATE,NOTE) select MANUAL_NO,PRE_MANUAL_NO,ORDER_NO,MANUAL_SCH,M_FLAG,TRADE_NAME,OPER_ER,OPER_DATE,NOTE from CHKHS_MNLPROC_GPTMP_TODAY  where CMD_TYPE='I';
\timing
