\echo -----------------------CIC_SEND_REL------------------------
select now();
\timing
delete from CIC_SEND_REL using CIC_SEND_REL_GPTMP_TODAY where CIC_SEND_REL.CPT_NO=CIC_SEND_REL_GPTMP_TODAY.CPT_NO AND CIC_SEND_REL.SEND_TIMES=CIC_SEND_REL_GPTMP_TODAY.SEND_TIMES ;
insert into CIC_SEND_REL (CPT_NO,CIC_NO,SEND_TIMES,SEND_ER,SEND_TYPE,SEND_DATE,RECV_DATE,RECV_FLAG,NOTE) select CPT_NO,CIC_NO,SEND_TIMES,SEND_ER,SEND_TYPE,SEND_DATE,RECV_DATE,RECV_FLAG,NOTE from CIC_SEND_REL_GPTMP_TODAY  where CMD_TYPE='I';
\timing
