\echo -----------------------CIC_LIST------------------------
select now();
\timing
delete from CIC_LIST using CIC_LIST_GPTMP_TODAY where CIC_LIST.CPT_NO=CIC_LIST_GPTMP_TODAY.CPT_NO AND CIC_LIST.ITEM_NO=CIC_LIST_GPTMP_TODAY.ITEM_NO ;
insert into CIC_LIST (CPT_NO,ITEM_NO,CODE_TS,ORIGIN_COUNTRY,G_NAME,G_MODEL,COLOR,ENGINE_NO,CAR_COVER_NO,QTY_EXHAUST,QTY,PRICE,CURR,PACK_NO,MARK_NO,SPARE_FLAG,NOTE,FCT_DATE) select CPT_NO,ITEM_NO,CODE_TS,ORIGIN_COUNTRY,G_NAME,G_MODEL,COLOR,ENGINE_NO,CAR_COVER_NO,QTY_EXHAUST,QTY,PRICE,CURR,PACK_NO,MARK_NO,SPARE_FLAG,NOTE,FCT_DATE from CIC_LIST_GPTMP_TODAY  where CMD_TYPE='I';
\timing
