\echo -----------------------CLC_GPR_RATIO------------------------
select now();
\timing
delete from CLC_GPR_RATIO using CLC_GPR_RATIO_GPTMP_TODAY where CLC_GPR_RATIO.CUSTOMS_CODE=CLC_GPR_RATIO_GPTMP_TODAY.CUSTOMS_CODE AND CLC_GPR_RATIO.I_E_FLAG=CLC_GPR_RATIO_GPTMP_TODAY.I_E_FLAG ;
insert into CLC_GPR_RATIO (CUSTOMS_CODE,I_E_FLAG,RATIO_NUM) select CUSTOMS_CODE,I_E_FLAG,RATIO_NUM from CLC_GPR_RATIO_GPTMP_TODAY  where CMD_TYPE='I';
\timing
