\echo -----------------------CLC_GPR_RATIO_BAK------------------------
select now();
\timing
delete from CLC_GPR_RATIO_BAK using CLC_GPR_RATIO_BAK_GPTMP_TODAY where CLC_GPR_RATIO_BAK.CUSTOMS_CODE=CLC_GPR_RATIO_BAK_GPTMP_TODAY.CUSTOMS_CODE AND CLC_GPR_RATIO_BAK.I_E_FLAG=CLC_GPR_RATIO_BAK_GPTMP_TODAY.I_E_FLAG AND CLC_GPR_RATIO_BAK.OP_TIME=CLC_GPR_RATIO_BAK_GPTMP_TODAY.OP_TIME ;
insert into CLC_GPR_RATIO_BAK (CUSTOMS_CODE,I_E_FLAG,RATIO_NUM,OP_TIME,OP_ER,OP_CUSTOMS) select CUSTOMS_CODE,I_E_FLAG,RATIO_NUM,OP_TIME,OP_ER,OP_CUSTOMS from CLC_GPR_RATIO_BAK_GPTMP_TODAY  where CMD_TYPE='I';
\timing
