\echo -----------------------CNS_COUNTER_TABLE------------------------
select now();
\timing
delete from CNS_COUNTER_TABLE using CNS_COUNTER_TABLE_GPTMP_TODAY where CNS_COUNTER_TABLE.CUSTOMS_CODE=CNS_COUNTER_TABLE_GPTMP_TODAY.CUSTOMS_CODE ;
insert into CNS_COUNTER_TABLE (CUSTOMS_CODE,COUNTER) select CUSTOMS_CODE,COUNTER from CNS_COUNTER_TABLE_GPTMP_TODAY  where CMD_TYPE='I';
\timing
