\echo -----------------------CO_CLASS_REL------------------------
select now();
\timing
delete from CO_CLASS_REL using CO_CLASS_REL_GPTMP_TODAY where CO_CLASS_REL.TRADE_CO=CO_CLASS_REL_GPTMP_TODAY.TRADE_CO AND CO_CLASS_REL.CLASS_NO=CO_CLASS_REL_GPTMP_TODAY.CLASS_NO ;
insert into CO_CLASS_REL (TRADE_CO,CLASS_NO,CLASS_SOURCE,CLASS_DEST,CLASS_OPER_CODE,CLASS_OPER_DATE,CLASS_DPT_CODE,CLASS_DPT_DATE,CLASS_NOTE) select TRADE_CO,CLASS_NO,CLASS_SOURCE,CLASS_DEST,CLASS_OPER_CODE,CLASS_OPER_DATE,CLASS_DPT_CODE,CLASS_DPT_DATE,CLASS_NOTE from CO_CLASS_REL_GPTMP_TODAY  where CMD_TYPE='I';
\timing
