\echo -----------------------CONSUME------------------------
select now();
\timing
delete from CONSUME using CONSUME_GPTMP_TODAY where CONSUME.MANUAL_NO=CONSUME_GPTMP_TODAY.MANUAL_NO AND CONSUME.CONTR_ITEM=CONSUME_GPTMP_TODAY.CONTR_ITEM AND CONSUME.EX_NO=CONSUME_GPTMP_TODAY.EX_NO ;
insert into CONSUME (MANUAL_NO,CONTR_ITEM,EX_NO,APPR_CONSUME,APPR_DAMAGE,DECL_CONSUME,DECL_DAMAGE) select MANUAL_NO,CONTR_ITEM,EX_NO,APPR_CONSUME,APPR_DAMAGE,DECL_CONSUME,DECL_DAMAGE from CONSUME_GPTMP_TODAY  where CMD_TYPE='I';
\timing
