\echo -----------------------CONSUME_GOODS------------------------
select now();
\timing
delete from CONSUME_GOODS using CONSUME_GOODS_GPTMP_TODAY where CONSUME_GOODS.CODE_TS=CONSUME_GOODS_GPTMP_TODAY.CODE_TS AND CONSUME_GOODS.G_NO=CONSUME_GOODS_GPTMP_TODAY.G_NO AND CONSUME_GOODS.G_FLAG=CONSUME_GOODS_GPTMP_TODAY.G_FLAG ;
insert into CONSUME_GOODS (CODE_TS,G_NO,G_FLAG,G_NAME,G_MODEL,UNIT_1,TRADE_COUNTRY,INFO_SOURCE,INPUT_DATE,NOTE_S) select CODE_TS,G_NO,G_FLAG,G_NAME,G_MODEL,UNIT_1,TRADE_COUNTRY,INFO_SOURCE,INPUT_DATE,NOTE_S from CONSUME_GOODS_GPTMP_TODAY  where CMD_TYPE='I';
\timing
