\echo -----------------------CONTRACT_WORKFLOW------------------------
select now();
\timing
delete from CONTRACT_WORKFLOW using CONTRACT_WORKFLOW_GPTMP_TODAY where CONTRACT_WORKFLOW.MANUAL_NO=CONTRACT_WORKFLOW_GPTMP_TODAY.MANUAL_NO AND CONTRACT_WORKFLOW.STEP_ID=CONTRACT_WORKFLOW_GPTMP_TODAY.STEP_ID AND CONTRACT_WORKFLOW.PROC_DATE=CONTRACT_WORKFLOW_GPTMP_TODAY.PROC_DATE ;
insert into CONTRACT_WORKFLOW (MANUAL_NO,STEP_ID,PROC_DATE,PROC_ER,PROC_ID,PROC_POS,STATUS_STATE) select MANUAL_NO,STEP_ID,PROC_DATE,PROC_ER,PROC_ID,PROC_POS,STATUS_STATE from CONTRACT_WORKFLOW_GPTMP_TODAY  where CMD_TYPE='I';
\timing
