\echo -----------------------CONVEYANCE_SEGMENT------------------------
select now();
\timing
delete from CONVEYANCE_SEGMENT using CONVEYANCE_SEGMENT_GPTMP_TODAY where CONVEYANCE_SEGMENT.SHIP_ID=CONVEYANCE_SEGMENT_GPTMP_TODAY.SHIP_ID AND CONVEYANCE_SEGMENT.TRAF_MODE=CONVEYANCE_SEGMENT_GPTMP_TODAY.TRAF_MODE AND CONVEYANCE_SEGMENT.VOYAGE_NO=CONVEYANCE_SEGMENT_GPTMP_TODAY.VOYAGE_NO AND CONVEYANCE_SEGMENT.I_E_FLAG=CONVEYANCE_SEGMENT_GPTMP_TODAY.I_E_FLAG AND CONVEYANCE_SEGMENT.LOAD_PORT=CONVEYANCE_SEGMENT_GPTMP_TODAY.LOAD_PORT AND CONVEYANCE_SEGMENT.DESTINATION_PORT=CONVEYANCE_SEGMENT_GPTMP_TODAY.DESTINATION_PORT AND CONVEYANCE_SEGMENT.CUSTOMS_CODE=CONVEYANCE_SEGMENT_GPTMP_TODAY.CUSTOMS_CODE AND CONVEYANCE_SEGMENT.I_E_DATE=CONVEYANCE_SEGMENT_GPTMP_TODAY.I_E_DATE ;
insert into CONVEYANCE_SEGMENT (SHIP_ID,TRAF_MODE,VOYAGE_NO,I_E_FLAG,LOAD_PORT,DESTINATION_PORT,CUSTOMS_CODE,I_E_DATE) select SHIP_ID,TRAF_MODE,VOYAGE_NO,I_E_FLAG,LOAD_PORT,DESTINATION_PORT,CUSTOMS_CODE,I_E_DATE from CONVEYANCE_SEGMENT_GPTMP_TODAY  where CMD_TYPE='I';
\timing
