\echo -----------------------CONVEYANCE------------------------
select now();
\timing
delete from CONVEYANCE using CONVEYANCE_GPTMP_TODAY where CONVEYANCE.SHIP_ID=CONVEYANCE_GPTMP_TODAY.SHIP_ID AND CONVEYANCE.TRAF_MODE=CONVEYANCE_GPTMP_TODAY.TRAF_MODE ;
insert into CONVEYANCE (SHIP_ID,TRAF_MODE,SHIP_NAME_EN,SHIP_NAME_CN,SHIP_NAME_ORI,COUNTRY_CODE,SHIP_TYPE,SHIP_ATTR,SHIP_USE_CODE,TONNAGE,CREATE_DATE,CREATE_ER,CUSTOMS_CODE) select SHIP_ID,TRAF_MODE,SHIP_NAME_EN,SHIP_NAME_CN,SHIP_NAME_ORI,COUNTRY_CODE,SHIP_TYPE,SHIP_ATTR,SHIP_USE_CODE,TONNAGE,CREATE_DATE,CREATE_ER,CUSTOMS_CODE from CONVEYANCE_GPTMP_TODAY  where CMD_TYPE='I';
\timing
