\echo -----------------------CORP_TABLE------------------------
select now();
\timing
delete from CORP_TABLE using CORP_TABLE_GPTMP_TODAY where CORP_TABLE.FIELD_ID=CORP_TABLE_GPTMP_TODAY.FIELD_ID AND CORP_TABLE.TABLE_ID=CORP_TABLE_GPTMP_TODAY.TABLE_ID ;
insert into CORP_TABLE (FIELD_ID,TABLE_ID,TABLE_NAME,FIELD_NAME) select FIELD_ID,TABLE_ID,TABLE_NAME,FIELD_NAME from CORP_TABLE_GPTMP_TODAY  where CMD_TYPE='I';
\timing
