\echo -----------------------COUNTER_TABLE------------------------
select now();
\timing
delete from COUNTER_TABLE using COUNTER_TABLE_GPTMP_TODAY where COUNTER_TABLE.COUNTER_TYPE=COUNTER_TABLE_GPTMP_TODAY.COUNTER_TYPE AND COUNTER_TABLE.CUSTOMS_CODE=COUNTER_TABLE_GPTMP_TODAY.CUSTOMS_CODE AND COUNTER_TABLE.I_E_FLAG=COUNTER_TABLE_GPTMP_TODAY.I_E_FLAG AND COUNTER_TABLE.C_DATE=COUNTER_TABLE_GPTMP_TODAY.C_DATE ;
insert into COUNTER_TABLE (COUNTER_TYPE,CUSTOMS_CODE,I_E_FLAG,C_DATE,COUNTER) select COUNTER_TYPE,CUSTOMS_CODE,I_E_FLAG,C_DATE,COUNTER from COUNTER_TABLE_GPTMP_TODAY  where CMD_TYPE='I';
\timing
