\echo -----------------------CTS_PERIOD------------------------
select now();
\timing
delete from CTS_PERIOD using CTS_PERIOD_GPTMP_TODAY where CTS_PERIOD.CUSTOMS_CODE=CTS_PERIOD_GPTMP_TODAY.CUSTOMS_CODE ;
insert into CTS_PERIOD (CUSTOMS_CODE,EXAM_PERIOD,CHK_PERIOD,PROC_PERIOD,OP_ER,OP_TIME) select CUSTOMS_CODE,EXAM_PERIOD,CHK_PERIOD,PROC_PERIOD,OP_ER,OP_TIME from CTS_PERIOD_GPTMP_TODAY  where CMD_TYPE='I';
\timing
