\echo -----------------------CUSTOMS_ESEAL_CONFIG------------------------
select now();
\timing
delete from CUSTOMS_ESEAL_CONFIG using CUSTOMS_ESEAL_CONFIG_GPTMP_TODAY where CUSTOMS_ESEAL_CONFIG.CUSTOMS_CODE=CUSTOMS_ESEAL_CONFIG_GPTMP_TODAY.CUSTOMS_CODE AND CUSTOMS_ESEAL_CONFIG.FLAG_TYPE=CUSTOMS_ESEAL_CONFIG_GPTMP_TODAY.FLAG_TYPE AND CUSTOMS_ESEAL_CONFIG.I_E_FLAG=CUSTOMS_ESEAL_CONFIG_GPTMP_TODAY.I_E_FLAG ;
insert into CUSTOMS_ESEAL_CONFIG (CUSTOMS_CODE,FLAG_TYPE,I_E_FLAG,ESEAL_FLAG,ESEAL_MODE,OP_ID,OP_DATE) select CUSTOMS_CODE,FLAG_TYPE,I_E_FLAG,ESEAL_FLAG,ESEAL_MODE,OP_ID,OP_DATE from CUSTOMS_ESEAL_CONFIG_GPTMP_TODAY  where CMD_TYPE='I';
\timing
