\echo -----------------------DCG_BILL_HEAD------------------------
select now();
\timing
delete from DCG_BILL_HEAD using DCG_BILL_HEAD_GPTMP_TODAY where DCG_BILL_HEAD.BILL_NO=DCG_BILL_HEAD_GPTMP_TODAY.BILL_NO ;
insert into DCG_BILL_HEAD (BILL_NO,BILL_FLAG,EPORT_NO,DCG_NO,EX_COP_BILL_NO,EX_TRADE_CODE,EX_DECLARE_ER,EX_DECLARE_DATE,IM_COP_BILL_NO,IM_TRADE_CODE,IM_DECLARE_ER,IM_DECLARE_DATE,IM_DATE,CONTR_NO,VE_TYPE,SHIP_ID,EX_DATE,STATUS,PRE_FLAG,EXE_MARK,CUSTOMS_CODE,BAR_CODE,NOTE) select BILL_NO,BILL_FLAG,EPORT_NO,DCG_NO,EX_COP_BILL_NO,EX_TRADE_CODE,EX_DECLARE_ER,EX_DECLARE_DATE,IM_COP_BILL_NO,IM_TRADE_CODE,IM_DECLARE_ER,IM_DECLARE_DATE,IM_DATE,CONTR_NO,VE_TYPE,SHIP_ID,EX_DATE,STATUS,PRE_FLAG,EXE_MARK,CUSTOMS_CODE,BAR_CODE,NOTE from DCG_BILL_HEAD_GPTMP_TODAY  where CMD_TYPE='I';
\timing
