\echo -----------------------DCG_DEDUCT------------------------
select now();
\timing
delete from DCG_DEDUCT using DCG_DEDUCT_GPTMP_TODAY where DCG_DEDUCT.ENTRY_ID=DCG_DEDUCT_GPTMP_TODAY.ENTRY_ID AND DCG_DEDUCT.DCG_NO=DCG_DEDUCT_GPTMP_TODAY.DCG_NO AND DCG_DEDUCT.G_TYPE=DCG_DEDUCT_GPTMP_TODAY.G_TYPE AND DCG_DEDUCT.ENTRY_G_NO=DCG_DEDUCT_GPTMP_TODAY.ENTRY_G_NO ;
insert into DCG_DEDUCT (ENTRY_ID,DCG_NO,G_TYPE,ENTRY_G_NO,DCG_G_NO,EMS_NO,EMS_G_NO,QTY,VERIFY_DATE,VERIFY_ER) select ENTRY_ID,DCG_NO,G_TYPE,ENTRY_G_NO,DCG_G_NO,EMS_NO,EMS_G_NO,QTY,VERIFY_DATE,VERIFY_ER from DCG_DEDUCT_GPTMP_TODAY  where CMD_TYPE='I';
\timing
