\echo -----------------------DCG_BILL_LIST------------------------
select now();
\timing
delete from DCG_BILL_LIST using DCG_BILL_LIST_GPTMP_TODAY where DCG_BILL_LIST.BILL_NO=DCG_BILL_LIST_GPTMP_TODAY.BILL_NO AND DCG_BILL_LIST.G_TYPE=DCG_BILL_LIST_GPTMP_TODAY.G_TYPE AND DCG_BILL_LIST.G_NO=DCG_BILL_LIST_GPTMP_TODAY.G_NO ;
insert into DCG_BILL_LIST (BILL_NO,G_TYPE,G_NO,DCG_G_NO,QTY,CHECK_DATE,COP_QTY,COP_UNIT,G_MARK) select BILL_NO,G_TYPE,G_NO,DCG_G_NO,QTY,CHECK_DATE,COP_QTY,COP_UNIT,G_MARK from DCG_BILL_LIST_GPTMP_TODAY  where CMD_TYPE='I';
\timing
