\echo -----------------------DCG_WORKFLOW------------------------
select now();
\timing
delete from DCG_WORKFLOW using DCG_WORKFLOW_GPTMP_TODAY where DCG_WORKFLOW.DCG_NO=DCG_WORKFLOW_GPTMP_TODAY.DCG_NO AND DCG_WORKFLOW.STEP_ID=DCG_WORKFLOW_GPTMP_TODAY.STEP_ID AND DCG_WORKFLOW.CREATE_DATE=DCG_WORKFLOW_GPTMP_TODAY.CREATE_DATE ;
insert into DCG_WORKFLOW (DCG_NO,STEP_ID,CREATE_DATE,PROC_ER,PROC_ID,PROC_POS,PROC_RESULT) select DCG_NO,STEP_ID,CREATE_DATE,PROC_ER,PROC_ID,PROC_POS,PROC_RESULT from DCG_WORKFLOW_GPTMP_TODAY  where CMD_TYPE='I';
\timing
