\echo -----------------------DCG_DEDUCT_LOG------------------------
select now();
\timing
delete from DCG_DEDUCT_LOG using DCG_DEDUCT_LOG_GPTMP_TODAY where DCG_DEDUCT_LOG.ENTRY_ID=DCG_DEDUCT_LOG_GPTMP_TODAY.ENTRY_ID AND DCG_DEDUCT_LOG.DCG_NO=DCG_DEDUCT_LOG_GPTMP_TODAY.DCG_NO AND DCG_DEDUCT_LOG.CREATE_DATE=DCG_DEDUCT_LOG_GPTMP_TODAY.CREATE_DATE AND DCG_DEDUCT_LOG.JOU_MARK=DCG_DEDUCT_LOG_GPTMP_TODAY.JOU_MARK ;
insert into DCG_DEDUCT_LOG (ENTRY_ID,DCG_NO,CREATE_DATE,JOU_MARK,NOTE,VERIFY_ER) select ENTRY_ID,DCG_NO,CREATE_DATE,JOU_MARK,NOTE,VERIFY_ER from DCG_DEDUCT_LOG_GPTMP_TODAY  where CMD_TYPE='I';
\timing
