\echo -----------------------DECLOG_MODIFY_REL------------------------
select now();
\timing
delete from DECLOG_MODIFY_REL using DECLOG_MODIFY_REL_GPTMP_TODAY where DECLOG_MODIFY_REL.LOG_ID=DECLOG_MODIFY_REL_GPTMP_TODAY.LOG_ID ;
insert into DECLOG_MODIFY_REL (LOG_ID,LOG_DECL_CO,LOG_DECL_CUST,LOG_MODE,LOG_ITEM,LOG_OLD,LOG_NEW,LOG_OPER_ID,LOG_CUSTOMS_CODE,LOG_DATE,LOG_COMPUTER) select LOG_ID,LOG_DECL_CO,LOG_DECL_CUST,LOG_MODE,LOG_ITEM,LOG_OLD,LOG_NEW,LOG_OPER_ID,LOG_CUSTOMS_CODE,LOG_DATE,LOG_COMPUTER from DECLOG_MODIFY_REL_GPTMP_TODAY  where CMD_TYPE='I';
\timing
