\echo -----------------------DECL_CO_ENTRY_COUNT------------------------
select now();
\timing
delete from DECL_CO_ENTRY_COUNT using DECL_CO_ENTRY_COUNT_GPTMP_TODAY where DECL_CO_ENTRY_COUNT.DECL_CO=DECL_CO_ENTRY_COUNT_GPTMP_TODAY.DECL_CO AND DECL_CO_ENTRY_COUNT.RANDOM=DECL_CO_ENTRY_COUNT_GPTMP_TODAY.RANDOM ;
insert into DECL_CO_ENTRY_COUNT (DECL_CO,GEN_DATE,RANDOM,ENTRY_DECL,ENTRY_END,FAULT_ENTRY,SCORE_DEDUCT) select DECL_CO,GEN_DATE,RANDOM,ENTRY_DECL,ENTRY_END,FAULT_ENTRY,SCORE_DEDUCT from DECL_CO_ENTRY_COUNT_GPTMP_TODAY  where CMD_TYPE='I';
\timing
