\echo -----------------------DECLOG_SCORE_HEAD------------------------
select now();
\timing
delete from DECLOG_SCORE_HEAD using DECLOG_SCORE_HEAD_GPTMP_TODAY where DECLOG_SCORE_HEAD.DECL_CO=DECLOG_SCORE_HEAD_GPTMP_TODAY.DECL_CO AND DECLOG_SCORE_HEAD.FORM_ID=DECLOG_SCORE_HEAD_GPTMP_TODAY.FORM_ID AND DECLOG_SCORE_HEAD.SCORE_TIME=DECLOG_SCORE_HEAD_GPTMP_TODAY.SCORE_TIME ;
insert into DECLOG_SCORE_HEAD (DECL_CO,FORM_ID,AGENT_CODE,SCORE_STEP,ERROR_SCORE,SCORE_TIME,SCORE_PROC_ER,CUSTOMS_CODE,RETURN_REASON,RETURN_PROC_ER,RETURN_DATE) select DECL_CO,FORM_ID,AGENT_CODE,SCORE_STEP,ERROR_SCORE,SCORE_TIME,SCORE_PROC_ER,CUSTOMS_CODE,RETURN_REASON,RETURN_PROC_ER,RETURN_DATE from DECLOG_SCORE_HEAD_GPTMP_TODAY  where CMD_TYPE='I';
\timing
