\echo -----------------------DECL_CO_ENTRY_COUNT_TEMP------------------------
select now();
\timing
delete from DECL_CO_ENTRY_COUNT_TEMP using DECL_CO_ENTRY_COUNT_TEMP_GPTMP_TODAY where DECL_CO_ENTRY_COUNT_TEMP.GEN_DATE=DECL_CO_ENTRY_COUNT_TEMP_GPTMP_TODAY.GEN_DATE AND DECL_CO_ENTRY_COUNT_TEMP.DECL_CO=DECL_CO_ENTRY_COUNT_TEMP_GPTMP_TODAY.DECL_CO AND DECL_CO_ENTRY_COUNT_TEMP.RANDOM=DECL_CO_ENTRY_COUNT_TEMP_GPTMP_TODAY.RANDOM ;
insert into DECL_CO_ENTRY_COUNT_TEMP (DECL_CO,GEN_DATE,RANDOM) select DECL_CO,GEN_DATE,RANDOM from DECL_CO_ENTRY_COUNT_TEMP_GPTMP_TODAY  where CMD_TYPE='I';
\timing
