\echo -----------------------DEL_EGS_ARC_AGENT_LIST------------------------
select now();
\timing
delete from DEL_EGS_ARC_AGENT_LIST using DEL_EGS_ARC_AGENT_LIST_GPTMP_TODAY where DEL_EGS_ARC_AGENT_LIST.EGS_NO=DEL_EGS_ARC_AGENT_LIST_GPTMP_TODAY.EGS_NO AND DEL_EGS_ARC_AGENT_LIST.AGENT_NO=DEL_EGS_ARC_AGENT_LIST_GPTMP_TODAY.AGENT_NO ;
insert into DEL_EGS_ARC_AGENT_LIST (EGS_NO,AGENT_NO,AGENT_CODE,AGENT_NAME) select EGS_NO,AGENT_NO,AGENT_CODE,AGENT_NAME from DEL_EGS_ARC_AGENT_LIST_GPTMP_TODAY  where CMD_TYPE='I';
\timing
