\echo -----------------------DEL_MOD_APPLY------------------------
select now();
\timing
delete from DEL_MOD_APPLY using DEL_MOD_APPLY_GPTMP_TODAY where DEL_MOD_APPLY.ENTRY_ID=DEL_MOD_APPLY_GPTMP_TODAY.ENTRY_ID AND DEL_MOD_APPLY.APPLY_TIME=DEL_MOD_APPLY_GPTMP_TODAY.APPLY_TIME ;
insert into DEL_MOD_APPLY (ENTRY_ID,APPLY_TIME,APPLY_FLAG,APPLY_ER,APPLY_MARK,APPLY_COMM,RSK_CLASS,OP_FLAG,OP_TIME,OP_ER,OP_MARK,OP_COMM) select ENTRY_ID,APPLY_TIME,APPLY_FLAG,APPLY_ER,APPLY_MARK,APPLY_COMM,RSK_CLASS,OP_FLAG,OP_TIME,OP_ER,OP_MARK,OP_COMM from DEL_MOD_APPLY_GPTMP_TODAY  where CMD_TYPE='I';
\timing
