\echo -----------------------DST_EXG------------------------
select now();
\timing
delete from DST_EXG using DST_EXG_GPTMP_TODAY where DST_EXG.PRE_NO=DST_EXG_GPTMP_TODAY.PRE_NO AND DST_EXG.G_NO=DST_EXG_GPTMP_TODAY.G_NO AND DST_EXG.ORIGIN_COUNTRY=DST_EXG_GPTMP_TODAY.ORIGIN_COUNTRY ;
insert into DST_EXG (DST_SEQ_NO,PRE_NO,REL_NO,G_NO,CODE_TS,G_NAME,G_MODEL,G_QTY,G_UNIT,UNIT_1,QTY_1,DECL_PRICE,PRICE_1,TRADE_TOTAL,TRADE_CURR,ORIGIN_COUNTRY,VERSION,MODIFY_MARK,DECL_DUTY,DECL_TAX,DECL_OTHER,DECL_TOTAL,CHK_DUTY,CHK_TAX,CHK_INTEREST,CHK_OTHER,CHK_TOTAL,IMG_PRICE,CONTRACT_PRICE,NORMAL_PRICE,PARAM_PRICE,NOTE,FACT_QTY) select DST_SEQ_NO,PRE_NO,REL_NO,G_NO,CODE_TS,G_NAME,G_MODEL,G_QTY,G_UNIT,UNIT_1,QTY_1,DECL_PRICE,PRICE_1,TRADE_TOTAL,TRADE_CURR,ORIGIN_COUNTRY,VERSION,MODIFY_MARK,DECL_DUTY,DECL_TAX,DECL_OTHER,DECL_TOTAL,CHK_DUTY,CHK_TAX,CHK_INTEREST,CHK_OTHER,CHK_TOTAL,IMG_PRICE,CONTRACT_PRICE,NORMAL_PRICE,PARAM_PRICE,NOTE,FACT_QTY from DST_EXG_GPTMP_TODAY  where CMD_TYPE='I';
\timing
