\echo -----------------------DST_IMG------------------------
select now();
\timing
delete from DST_IMG using DST_IMG_GPTMP_TODAY where DST_IMG.PRE_NO=DST_IMG_GPTMP_TODAY.PRE_NO AND DST_IMG.G_NO=DST_IMG_GPTMP_TODAY.G_NO AND DST_IMG.ORIGIN_COUNTRY=DST_IMG_GPTMP_TODAY.ORIGIN_COUNTRY ;
insert into DST_IMG (DST_SEQ_NO,PRE_NO,REL_NO,G_NO,CODE_TS,G_NAME,G_MODEL,G_QTY,G_UNIT,UNIT_1,QTY_1,DECL_PRICE,PRICE_1,TRADE_TOTAL,TRADE_CURR,ORIGIN_COUNTRY,MODIFY_MARK,DECL_DUTY,DECL_TAX,DECL_OTHER,DECL_TOTAL,CHK_DUTY,CHK_TAX,CHK_INTEREST,CHK_OTHER,CHK_TOTAL,IMG_PRICE,CONTRACT_PRICE,NORMAL_PRICE,PARAM_PRICE,NOTE,FACT_QTY) select DST_SEQ_NO,PRE_NO,REL_NO,G_NO,CODE_TS,G_NAME,G_MODEL,G_QTY,G_UNIT,UNIT_1,QTY_1,DECL_PRICE,PRICE_1,TRADE_TOTAL,TRADE_CURR,ORIGIN_COUNTRY,MODIFY_MARK,DECL_DUTY,DECL_TAX,DECL_OTHER,DECL_TOTAL,CHK_DUTY,CHK_TAX,CHK_INTEREST,CHK_OTHER,CHK_TOTAL,IMG_PRICE,CONTRACT_PRICE,NORMAL_PRICE,PARAM_PRICE,NOTE,FACT_QTY from DST_IMG_GPTMP_TODAY  where CMD_TYPE='I';
\timing
