\echo -----------------------DST_DEDUCT------------------------
select now();
\timing
delete from DST_DEDUCT using DST_DEDUCT_GPTMP_TODAY where DST_DEDUCT.PRE_NO=DST_DEDUCT_GPTMP_TODAY.PRE_NO AND DST_DEDUCT.G_NO=DST_DEDUCT_GPTMP_TODAY.G_NO AND DST_DEDUCT.ORIGIN_COUNTRY=DST_DEDUCT_GPTMP_TODAY.ORIGIN_COUNTRY AND DST_DEDUCT.ENTRY_ID=DST_DEDUCT_GPTMP_TODAY.ENTRY_ID AND DST_DEDUCT.ENTRY_G_NO=DST_DEDUCT_GPTMP_TODAY.ENTRY_G_NO ;
insert into DST_DEDUCT (PRE_NO,REL_NO,G_NO,ENTRY_ID,ENTRY_G_NO,I_E_FLAG,G_QTY,VERIFY_DATE,VERIFY_ER,ORIGIN_COUNTRY) select PRE_NO,REL_NO,G_NO,ENTRY_ID,ENTRY_G_NO,I_E_FLAG,G_QTY,VERIFY_DATE,VERIFY_ER,ORIGIN_COUNTRY from DST_DEDUCT_GPTMP_TODAY  where CMD_TYPE='I';
\timing
