\echo -----------------------DTT_COP_PARAM------------------------
select now();
\timing
delete from DTT_COP_PARAM using DTT_COP_PARAM_GPTMP_TODAY where DTT_COP_PARAM.CORP_CODE=DTT_COP_PARAM_GPTMP_TODAY.CORP_CODE AND DTT_COP_PARAM.CUSTOMS_CODE=DTT_COP_PARAM_GPTMP_TODAY.CUSTOMS_CODE ;
insert into DTT_COP_PARAM (CORP_CODE,CUSTOMS_CODE,CORP_NAME,PROC_ER,PROC_DATE) select CORP_CODE,CUSTOMS_CODE,CORP_NAME,PROC_ER,PROC_DATE from DTT_COP_PARAM_GPTMP_TODAY  where CMD_TYPE='I';
\timing
