\echo -----------------------ECO_PARTS------------------------
select now();
\timing
delete from ECO_PARTS using ECO_PARTS_GPTMP_TODAY where ECO_PARTS.CERTIFICATE_NO=ECO_PARTS_GPTMP_TODAY.CERTIFICATE_NO AND ECO_PARTS.G_NO=ECO_PARTS_GPTMP_TODAY.G_NO AND ECO_PARTS.PART_SEQ=ECO_PARTS_GPTMP_TODAY.PART_SEQ ;
insert into ECO_PARTS (CERTIFICATE_NO,G_NO,PART_SEQ,PART_HSCODE,PART_NAME,UNIT_PRICE,ORIGIN_COUNTRY,AMT_PERCENT) select CERTIFICATE_NO,G_NO,PART_SEQ,PART_HSCODE,PART_NAME,UNIT_PRICE,ORIGIN_COUNTRY,AMT_PERCENT from ECO_PARTS_GPTMP_TODAY  where CMD_TYPE='I';
\timing
