\echo -----------------------ECO_WORKFLOW------------------------
select now();
\timing
delete from ECO_WORKFLOW using ECO_WORKFLOW_GPTMP_TODAY where ECO_WORKFLOW.CERTIFICATE_NO=ECO_WORKFLOW_GPTMP_TODAY.CERTIFICATE_NO AND ECO_WORKFLOW.TRANSFER_NUM=ECO_WORKFLOW_GPTMP_TODAY.TRANSFER_NUM AND ECO_WORKFLOW.PROCESS_STATUS=ECO_WORKFLOW_GPTMP_TODAY.PROCESS_STATUS AND ECO_WORKFLOW.PROCESS_DATE=ECO_WORKFLOW_GPTMP_TODAY.PROCESS_DATE ;
insert into ECO_WORKFLOW (CERTIFICATE_NO,TRANSFER_NUM,PROCESS_STATUS,PROCESS_DATE,ENTRY_ID,NOTE) select CERTIFICATE_NO,TRANSFER_NUM,PROCESS_STATUS,PROCESS_DATE,ENTRY_ID,NOTE from ECO_WORKFLOW_GPTMP_TODAY  where CMD_TYPE='I';
\timing
