\echo -----------------------ECO_LIST------------------------
select now();
\timing
delete from ECO_LIST using ECO_LIST_GPTMP_TODAY where ECO_LIST.CERTIFICATE_NO=ECO_LIST_GPTMP_TODAY.CERTIFICATE_NO AND ECO_LIST.G_NO=ECO_LIST_GPTMP_TODAY.G_NO ;
insert into ECO_LIST (CERTIFICATE_NO,G_NO,MARK,PACK_AND_DESC,CODE_TS,ORIGINAL_CRITERION,G_QTY,G_UNIT,GROSS_WEIGHT,NET_WEIGHT,QTY_1,UNIT_1,QTY_2,UNIT_2,FOB_CURR,FOB_AMOUNT) select CERTIFICATE_NO,G_NO,MARK,PACK_AND_DESC,CODE_TS,ORIGINAL_CRITERION,G_QTY,G_UNIT,GROSS_WEIGHT,NET_WEIGHT,QTY_1,UNIT_1,QTY_2,UNIT_2,FOB_CURR,FOB_AMOUNT from ECO_LIST_GPTMP_TODAY  where CMD_TYPE='I';
\timing
