\echo -----------------------EGS_ARC_AGENT_LIST------------------------
select now();
\timing
delete from EGS_ARC_AGENT_LIST using EGS_ARC_AGENT_LIST_GPTMP_TODAY where EGS_ARC_AGENT_LIST.EGS_NO=EGS_ARC_AGENT_LIST_GPTMP_TODAY.EGS_NO AND EGS_ARC_AGENT_LIST.AGENT_NO=EGS_ARC_AGENT_LIST_GPTMP_TODAY.AGENT_NO ;
insert into EGS_ARC_AGENT_LIST (EGS_NO,AGENT_NO,AGENT_CODE,AGENT_NAME) select EGS_NO,AGENT_NO,AGENT_CODE,AGENT_NAME from EGS_ARC_AGENT_LIST_GPTMP_TODAY  where CMD_TYPE='I';
\timing
