\echo -----------------------EGS_PATROL_LIST------------------------
select now();
\timing
delete from EGS_PATROL_LIST using EGS_PATROL_LIST_GPTMP_TODAY where EGS_PATROL_LIST.PAT_NO=EGS_PATROL_LIST_GPTMP_TODAY.PAT_NO AND EGS_PATROL_LIST.G_NO=EGS_PATROL_LIST_GPTMP_TODAY.G_NO ;
insert into EGS_PATROL_LIST (PAT_NO,MERCHANT_NO,MERCHANT_NAME,MERCHANT_COUNTRY,G_NO,CODE_TS,G_CERT_FLAG,G_NAME,G_MODEL,QTY1,QTY2,DECL_QTY,UNIT1,UNIT2,DECL_UNIT,DECL_PRICE,DECL_TOTAL,TRADE_CURR,ORIGIN_COUNTRY,DECL_NO,DECL_G_NO) select PAT_NO,MERCHANT_NO,MERCHANT_NAME,MERCHANT_COUNTRY,G_NO,CODE_TS,G_CERT_FLAG,G_NAME,G_MODEL,QTY1,QTY2,DECL_QTY,UNIT1,UNIT2,DECL_UNIT,DECL_PRICE,DECL_TOTAL,TRADE_CURR,ORIGIN_COUNTRY,DECL_NO,DECL_G_NO from EGS_PATROL_LIST_GPTMP_TODAY  where CMD_TYPE='I';
\timing
