\echo -----------------------EGS_ARC_MERCHANT_LIST------------------------
select now();
\timing
delete from EGS_ARC_MERCHANT_LIST using EGS_ARC_MERCHANT_LIST_GPTMP_TODAY where EGS_ARC_MERCHANT_LIST.EGS_NO=EGS_ARC_MERCHANT_LIST_GPTMP_TODAY.EGS_NO AND EGS_ARC_MERCHANT_LIST.AGENT_CODE=EGS_ARC_MERCHANT_LIST_GPTMP_TODAY.AGENT_CODE AND EGS_ARC_MERCHANT_LIST.MERCHANT_NO=EGS_ARC_MERCHANT_LIST_GPTMP_TODAY.MERCHANT_NO ;
insert into EGS_ARC_MERCHANT_LIST (EGS_NO,MERCHANT_NO,MERCHANT_NAME,MERCHANT_COUNTRY,EXHIBITION_NO,EXHIBITION_SITE_NO,AGENT_CODE) select EGS_NO,MERCHANT_NO,MERCHANT_NAME,MERCHANT_COUNTRY,EXHIBITION_NO,EXHIBITION_SITE_NO,AGENT_CODE from EGS_ARC_MERCHANT_LIST_GPTMP_TODAY  where CMD_TYPE='I';
\timing
