\echo -----------------------EGS_LEND_HEAD------------------------
select now();
\timing
delete from EGS_LEND_HEAD using EGS_LEND_HEAD_GPTMP_TODAY where EGS_LEND_HEAD.LEND_NO=EGS_LEND_HEAD_GPTMP_TODAY.LEND_NO ;
insert into EGS_LEND_HEAD (EGS_NO,EGS_NAME,PRE_LEND_NO,LEND_NO,MASTER_CUSTOMS,LEND_DATE,LEND_LIMIT,DECLARE_NO,DECLARE_PHONE,DEPOSIT_MARK,GUARANTEE_AMT,LEND_COMPANY,LEND_CONTACTOR,LEND_TELEPHONE,AGENT_CODE,AGENT_NAME,NOTES,OUT_AUDIT_DATE,OUT_AUDIT_ER,OUT_AUDIT_NOTE,OUT_DATE,OUT_ER,IN_AUDIT_DATE,IN_AUDIT_ER,IN_DATE,IN_ER,DECLARE_SOURCE,CHK_MARK,EXE_MARK) select EGS_NO,EGS_NAME,PRE_LEND_NO,LEND_NO,MASTER_CUSTOMS,LEND_DATE,LEND_LIMIT,DECLARE_NO,DECLARE_PHONE,DEPOSIT_MARK,GUARANTEE_AMT,LEND_COMPANY,LEND_CONTACTOR,LEND_TELEPHONE,AGENT_CODE,AGENT_NAME,NOTES,OUT_AUDIT_DATE,OUT_AUDIT_ER,OUT_AUDIT_NOTE,OUT_DATE,OUT_ER,IN_AUDIT_DATE,IN_AUDIT_ER,IN_DATE,IN_ER,DECLARE_SOURCE,CHK_MARK,EXE_MARK from EGS_LEND_HEAD_GPTMP_TODAY  where CMD_TYPE='I';
\timing
