\echo -----------------------EGS_WORKFLOW------------------------
select now();
\timing
delete from EGS_WORKFLOW using EGS_WORKFLOW_GPTMP_TODAY where EGS_WORKFLOW.EGS_NO=EGS_WORKFLOW_GPTMP_TODAY.EGS_NO AND EGS_WORKFLOW.STEP_ID=EGS_WORKFLOW_GPTMP_TODAY.STEP_ID AND EGS_WORKFLOW.CREATE_DATE=EGS_WORKFLOW_GPTMP_TODAY.CREATE_DATE ;
insert into EGS_WORKFLOW (EGS_NO,EGS_TYPE,STEP_ID,CREATE_DATE,PROC_ER,MASTER_CUSTOMS,PROC_RESULT,NOTE) select EGS_NO,EGS_TYPE,STEP_ID,CREATE_DATE,PROC_ER,MASTER_CUSTOMS,PROC_RESULT,NOTE from EGS_WORKFLOW_GPTMP_TODAY  where CMD_TYPE='I';
\timing
