\echo -----------------------EGS_DEDUCT------------------------
select now();
\timing
delete from EGS_DEDUCT using EGS_DEDUCT_GPTMP_TODAY where EGS_DEDUCT.DECL_NO=EGS_DEDUCT_GPTMP_TODAY.DECL_NO AND EGS_DEDUCT.DECL_G_NO=EGS_DEDUCT_GPTMP_TODAY.DECL_G_NO AND EGS_DEDUCT.CLR_NO=EGS_DEDUCT_GPTMP_TODAY.CLR_NO AND EGS_DEDUCT.CLR_G_NO=EGS_DEDUCT_GPTMP_TODAY.CLR_G_NO ;
insert into EGS_DEDUCT (DECL_NO,DECL_G_NO,CLR_NO,CLR_G_NO,CLR_QTY,CLR_MODE,CLR_DATE,CLR_ER,NOTES) select DECL_NO,DECL_G_NO,CLR_NO,CLR_G_NO,CLR_QTY,CLR_MODE,CLR_DATE,CLR_ER,NOTES from EGS_DEDUCT_GPTMP_TODAY  where CMD_TYPE='I';
\timing
