\echo -----------------------EGS_CLEAR_CERT------------------------
select now();
\timing
delete from EGS_CLEAR_CERT using EGS_CLEAR_CERT_GPTMP_TODAY where EGS_CLEAR_CERT.CLR_NO=EGS_CLEAR_CERT_GPTMP_TODAY.CLR_NO AND EGS_CLEAR_CERT.CERT_CODE=EGS_CLEAR_CERT_GPTMP_TODAY.CERT_CODE AND EGS_CLEAR_CERT.CERT_NO=EGS_CLEAR_CERT_GPTMP_TODAY.CERT_NO ;
insert into EGS_CLEAR_CERT (CLR_NO,CERT_CODE,CERT_NO) select CLR_NO,CERT_CODE,CERT_NO from EGS_CLEAR_CERT_GPTMP_TODAY  where CMD_TYPE='I';
\timing
