\echo -----------------------EGS_DECLARE_CERT------------------------
select now();
\timing
delete from EGS_DECLARE_CERT using EGS_DECLARE_CERT_GPTMP_TODAY where EGS_DECLARE_CERT.DECL_NO=EGS_DECLARE_CERT_GPTMP_TODAY.DECL_NO AND EGS_DECLARE_CERT.CERT_CODE=EGS_DECLARE_CERT_GPTMP_TODAY.CERT_CODE AND EGS_DECLARE_CERT.CERT_NO=EGS_DECLARE_CERT_GPTMP_TODAY.CERT_NO ;
insert into EGS_DECLARE_CERT (DECL_NO,CERT_CODE,CERT_NO) select DECL_NO,CERT_CODE,CERT_NO from EGS_DECLARE_CERT_GPTMP_TODAY  where CMD_TYPE='I';
\timing
