\echo -----------------------EMS_APPR_LIST------------------------
select now();
\timing
delete from EMS_APPR_LIST using EMS_APPR_LIST_GPTMP_TODAY where EMS_APPR_LIST.APPR_NO=EMS_APPR_LIST_GPTMP_TODAY.APPR_NO AND EMS_APPR_LIST.G_TYPE=EMS_APPR_LIST_GPTMP_TODAY.G_TYPE AND EMS_APPR_LIST.G_NO=EMS_APPR_LIST_GPTMP_TODAY.G_NO AND EMS_APPR_LIST.RECEIVE_TIMES=EMS_APPR_LIST_GPTMP_TODAY.RECEIVE_TIMES ;
insert into EMS_APPR_LIST (APPR_NO,G_TYPE,G_NO,RECEIVE_TIMES,CODE_TS,G_NAME,G_MODEL,UNIT,UNIT_PRICE,QTY,AMT,ORIGIN_COUNTRY,UNIT_1,FACTOR_1,NOTE,CURR,MODIFY_MARK) select APPR_NO,G_TYPE,G_NO,RECEIVE_TIMES,CODE_TS,G_NAME,G_MODEL,UNIT,UNIT_PRICE,QTY,AMT,ORIGIN_COUNTRY,UNIT_1,FACTOR_1,NOTE,CURR,MODIFY_MARK from EMS_APPR_LIST_GPTMP_TODAY  where CMD_TYPE='I';
\timing
