\echo -----------------------EMS_DEDUCT------------------------
select now();
\timing
delete from EMS_DEDUCT using EMS_DEDUCT_GPTMP_TODAY where EMS_DEDUCT.ENTRY_ID=EMS_DEDUCT_GPTMP_TODAY.ENTRY_ID AND EMS_DEDUCT.EMS_NO=EMS_DEDUCT_GPTMP_TODAY.EMS_NO AND EMS_DEDUCT.G_TYPE=EMS_DEDUCT_GPTMP_TODAY.G_TYPE AND EMS_DEDUCT.ENTRY_G_NO=EMS_DEDUCT_GPTMP_TODAY.ENTRY_G_NO ;
insert into EMS_DEDUCT (ENTRY_ID,EMS_NO,G_TYPE,EMS_G_NO,ENTRY_G_NO,EXG_VERSION,IN_QTY,I_ACCOUNT,I_WT,I_E_FLAG,I_CURR,I_E_PORT,TRADE_MODE,TRAF_MODE,VERIFY_MODE,VERIFY_DATE,VERIFY_ER,JOU_MARK,I_E_DATE,USD_ACCOUNT) select ENTRY_ID,EMS_NO,G_TYPE,EMS_G_NO,ENTRY_G_NO,EXG_VERSION,IN_QTY,I_ACCOUNT,I_WT,I_E_FLAG,I_CURR,I_E_PORT,TRADE_MODE,TRAF_MODE,VERIFY_MODE,VERIFY_DATE,VERIFY_ER,JOU_MARK,I_E_DATE,USD_ACCOUNT from EMS_DEDUCT_GPTMP_TODAY  where CMD_TYPE='I';
\timing
