\echo -----------------------EMS_VAR------------------------
select now();
\timing
delete from EMS_VAR using EMS_VAR_GPTMP_TODAY where EMS_VAR.VAR_TYPE=EMS_VAR_GPTMP_TODAY.VAR_TYPE AND EMS_VAR.VAR_ID=EMS_VAR_GPTMP_TODAY.VAR_ID AND EMS_VAR.VAR_SUB_ID=EMS_VAR_GPTMP_TODAY.VAR_SUB_ID AND EMS_VAR.CUSTOMS_CODE=EMS_VAR_GPTMP_TODAY.CUSTOMS_CODE ;
insert into EMS_VAR (VAR_TYPE,VAR_ID,VAR_SUB_ID,CUSTOMS_CODE,VAR_VALUE,VAR_VALUE1,VAR_VALUE2,VAR_VALUE3,VAR_DESC,MODIFY_TIME,VAR_ENABLED) select VAR_TYPE,VAR_ID,VAR_SUB_ID,CUSTOMS_CODE,VAR_VALUE,VAR_VALUE1,VAR_VALUE2,VAR_VALUE3,VAR_DESC,MODIFY_TIME,VAR_ENABLED from EMS_VAR_GPTMP_TODAY  where CMD_TYPE='I';
\timing
