\echo -----------------------EMS_CLR_TMP------------------------
select now();
\timing
delete from EMS_CLR_TMP using EMS_CLR_TMP_GPTMP_TODAY where EMS_CLR_TMP.EMS_NO=EMS_CLR_TMP_GPTMP_TODAY.EMS_NO AND EMS_CLR_TMP.G_TYPE=EMS_CLR_TMP_GPTMP_TODAY.G_TYPE AND EMS_CLR_TMP.G_NO=EMS_CLR_TMP_GPTMP_TODAY.G_NO ;
insert into EMS_CLR_TMP (EMS_NO,G_TYPE,G_NO,CM_QTY,CM_AMOUNT,CLR_INC_QTY,CLR_CUT_QTY,USD_PRICE,OTHER_PRICE,NOTE) select EMS_NO,G_TYPE,G_NO,CM_QTY,CM_AMOUNT,CLR_INC_QTY,CLR_CUT_QTY,USD_PRICE,OTHER_PRICE,NOTE from EMS_CLR_TMP_GPTMP_TODAY  where CMD_TYPE='I';
\timing
