\echo -----------------------EMS_DCR_RUB_LIST------------------------
select now();
\timing
delete from EMS_DCR_RUB_LIST using EMS_DCR_RUB_LIST_GPTMP_TODAY where EMS_DCR_RUB_LIST.EMS_NO=EMS_DCR_RUB_LIST_GPTMP_TODAY.EMS_NO AND EMS_DCR_RUB_LIST.DCR_TIMES=EMS_DCR_RUB_LIST_GPTMP_TODAY.DCR_TIMES AND EMS_DCR_RUB_LIST.G_TYPE=EMS_DCR_RUB_LIST_GPTMP_TODAY.G_TYPE AND EMS_DCR_RUB_LIST.G_NO=EMS_DCR_RUB_LIST_GPTMP_TODAY.G_NO ;
insert into EMS_DCR_RUB_LIST (EMS_NO,DCR_TIMES,G_TYPE,G_NO,COP_G_NO,CODE_TS,CLASS_MARK,G_NAME,G_MODEL,UNIT,DEC_PRICE,CURR,DEC_PRICE_RMB,QTY,USE_TYPE,NOTE_1,NOTE,MODIFY_MARK) select EMS_NO,DCR_TIMES,G_TYPE,G_NO,COP_G_NO,CODE_TS,CLASS_MARK,G_NAME,G_MODEL,UNIT,DEC_PRICE,CURR,DEC_PRICE_RMB,QTY,USE_TYPE,NOTE_1,NOTE,MODIFY_MARK from EMS_DCR_RUB_LIST_GPTMP_TODAY  where CMD_TYPE='I';
\timing
