\echo -----------------------EMS_PRESS------------------------
select now();
\timing
delete from EMS_PRESS using EMS_PRESS_GPTMP_TODAY where EMS_PRESS.PARA_TYPE=EMS_PRESS_GPTMP_TODAY.PARA_TYPE AND EMS_PRESS.PARA_NAME=EMS_PRESS_GPTMP_TODAY.PARA_NAME ;
insert into EMS_PRESS (PARA_TYPE,PARA_ID,PARA_NAME,PARA_EXP,PARA_FLAG,PARA_VALUE,PARA_MARK) select PARA_TYPE,PARA_ID,PARA_NAME,PARA_EXP,PARA_FLAG,PARA_VALUE,PARA_MARK from EMS_PRESS_GPTMP_TODAY  where CMD_TYPE='I';
\timing
