\echo -----------------------EMS_ENP_JOU------------------------
select now();
\timing
delete from EMS_ENP_JOU using EMS_ENP_JOU_GPTMP_TODAY where EMS_ENP_JOU.ENP_ID=EMS_ENP_JOU_GPTMP_TODAY.ENP_ID AND EMS_ENP_JOU.ENP_SEQ=EMS_ENP_JOU_GPTMP_TODAY.ENP_SEQ AND EMS_ENP_JOU.ENP_NO=EMS_ENP_JOU_GPTMP_TODAY.ENP_NO ;
insert into EMS_ENP_JOU (ENP_ID,ENP_SEQ,ENP_NO,PROCESS_DATE,PROCESS_MARK,PROCESS_STATUS,NOTE_1) select ENP_ID,ENP_SEQ,ENP_NO,PROCESS_DATE,PROCESS_MARK,PROCESS_STATUS,NOTE_1 from EMS_ENP_JOU_GPTMP_TODAY  where CMD_TYPE='I';
\timing
