\echo -----------------------EMS_DCR_CONSUME------------------------
select now();
\timing
delete from EMS_DCR_CONSUME using EMS_DCR_CONSUME_GPTMP_TODAY where EMS_DCR_CONSUME.EMS_NO=EMS_DCR_CONSUME_GPTMP_TODAY.EMS_NO AND EMS_DCR_CONSUME.EXG_NO=EMS_DCR_CONSUME_GPTMP_TODAY.EXG_NO AND EMS_DCR_CONSUME.EXG_VERSION=EMS_DCR_CONSUME_GPTMP_TODAY.EXG_VERSION AND EMS_DCR_CONSUME.IMG_NO=EMS_DCR_CONSUME_GPTMP_TODAY.IMG_NO AND EMS_DCR_CONSUME.MODIFY_TIMES=EMS_DCR_CONSUME_GPTMP_TODAY.MODIFY_TIMES ;
insert into EMS_DCR_CONSUME (EMS_NO,EXG_NO,EXG_VERSION,IMG_NO,MODIFY_TIMES,DEC_CM,DEC_DM,OTHER_CM,OTHER_DM,CM_MARK,PRODUCT_MARK,PRODUCT_TYPE,MODIFY_MARK,CONTROL_MARK,NOTE,ETL_MARK) select EMS_NO,EXG_NO,EXG_VERSION,IMG_NO,MODIFY_TIMES,DEC_CM,DEC_DM,OTHER_CM,OTHER_DM,CM_MARK,PRODUCT_MARK,PRODUCT_TYPE,MODIFY_MARK,CONTROL_MARK,NOTE,ETL_MARK from EMS_DCR_CONSUME_GPTMP_TODAY  where CMD_TYPE='I';
\timing
