\echo -----------------------EMS_VERIFY_DETAIL------------------------
select now();
\timing
delete from EMS_VERIFY_DETAIL using EMS_VERIFY_DETAIL_GPTMP_TODAY where EMS_VERIFY_DETAIL.EMS_NO=EMS_VERIFY_DETAIL_GPTMP_TODAY.EMS_NO AND EMS_VERIFY_DETAIL.G_TYPE=EMS_VERIFY_DETAIL_GPTMP_TODAY.G_TYPE AND EMS_VERIFY_DETAIL.G_NO=EMS_VERIFY_DETAIL_GPTMP_TODAY.G_NO AND EMS_VERIFY_DETAIL.D_TYPE=EMS_VERIFY_DETAIL_GPTMP_TODAY.D_TYPE AND EMS_VERIFY_DETAIL.E_TYPE=EMS_VERIFY_DETAIL_GPTMP_TODAY.E_TYPE ;
insert into EMS_VERIFY_DETAIL (EMS_NO,G_TYPE,G_NO,D_TYPE,E_TYPE,QTY) select EMS_NO,G_TYPE,G_NO,D_TYPE,E_TYPE,QTY from EMS_VERIFY_DETAIL_GPTMP_TODAY  where CMD_TYPE='I';
\timing
