\echo -----------------------EMS_CONSUME_CLR------------------------
select now();
\timing
delete from EMS_CONSUME_CLR using EMS_CONSUME_CLR_GPTMP_TODAY where EMS_CONSUME_CLR.EMS_NO=EMS_CONSUME_CLR_GPTMP_TODAY.EMS_NO AND EMS_CONSUME_CLR.IMG_NO=EMS_CONSUME_CLR_GPTMP_TODAY.IMG_NO ;
insert into EMS_CONSUME_CLR (EMS_NO,IMG_NO,G_NAME,QTY,EX_QTY,REM_QTY,UNIT,REM_RATIO,MODIFY_MARK,ETL_MARK) select EMS_NO,IMG_NO,G_NAME,QTY,EX_QTY,REM_QTY,UNIT,REM_RATIO,MODIFY_MARK,ETL_MARK from EMS_CONSUME_CLR_GPTMP_TODAY  where CMD_TYPE='I';
\timing
