\echo -----------------------EMS_PRESS_CLEAR------------------------
select now();
\timing
delete from EMS_PRESS_CLEAR using EMS_PRESS_CLEAR_GPTMP_TODAY where EMS_PRESS_CLEAR.EMS_NO=EMS_PRESS_CLEAR_GPTMP_TODAY.EMS_NO AND EMS_PRESS_CLEAR.PR_NO=EMS_PRESS_CLEAR_GPTMP_TODAY.PR_NO ;
insert into EMS_PRESS_CLEAR (EMS_NO,PR_NO,PR_COUNT,PR_CUSTOMS,PR_DEPARTMENT,PR_DATE) select EMS_NO,PR_NO,PR_COUNT,PR_CUSTOMS,PR_DEPARTMENT,PR_DATE from EMS_PRESS_CLEAR_GPTMP_TODAY  where CMD_TYPE='I';
\timing
