\echo -----------------------EMS_DEDUCT_LOG------------------------
select now();
\timing
delete from EMS_DEDUCT_LOG using EMS_DEDUCT_LOG_GPTMP_TODAY where EMS_DEDUCT_LOG.ENTRY_ID=EMS_DEDUCT_LOG_GPTMP_TODAY.ENTRY_ID AND EMS_DEDUCT_LOG.EMS_NO=EMS_DEDUCT_LOG_GPTMP_TODAY.EMS_NO AND EMS_DEDUCT_LOG.CREATE_DATE=EMS_DEDUCT_LOG_GPTMP_TODAY.CREATE_DATE AND EMS_DEDUCT_LOG.JOU_MARK=EMS_DEDUCT_LOG_GPTMP_TODAY.JOU_MARK ;
insert into EMS_DEDUCT_LOG (ENTRY_ID,EMS_NO,CREATE_DATE,JOU_MARK,NOTE,VERIFY_ER) select ENTRY_ID,EMS_NO,CREATE_DATE,JOU_MARK,NOTE,VERIFY_ER from EMS_DEDUCT_LOG_GPTMP_TODAY  where CMD_TYPE='I';
\timing
