\echo -----------------------EMS_CONSUME------------------------
select now();
\timing
delete from EMS_CONSUME using EMS_CONSUME_GPTMP_TODAY where EMS_CONSUME.EMS_NO=EMS_CONSUME_GPTMP_TODAY.EMS_NO AND EMS_CONSUME.EXG_NO=EMS_CONSUME_GPTMP_TODAY.EXG_NO AND EMS_CONSUME.EXG_VERSION=EMS_CONSUME_GPTMP_TODAY.EXG_VERSION AND EMS_CONSUME.IMG_NO=EMS_CONSUME_GPTMP_TODAY.IMG_NO ;
insert into EMS_CONSUME (EMS_NO,EXG_NO,EXG_VERSION,IMG_NO,MODIFY_TIMES,DEC_CM,DEC_DM,OTHER_CM,OTHER_DM,CM_MARK,PRODUCT_MARK,PRODUCT_TYPE,MODIFY_MARK,CONTROL_MARK,NOTE,ETL_MARK) select EMS_NO,EXG_NO,EXG_VERSION,IMG_NO,MODIFY_TIMES,DEC_CM,DEC_DM,OTHER_CM,OTHER_DM,CM_MARK,PRODUCT_MARK,PRODUCT_TYPE,MODIFY_MARK,CONTROL_MARK,NOTE,ETL_MARK from EMS_CONSUME_GPTMP_TODAY  where CMD_TYPE='I';
\timing
