\echo -----------------------EMS_COMPLEX------------------------
select now();
\timing
delete from EMS_COMPLEX using EMS_COMPLEX_GPTMP_TODAY where EMS_COMPLEX.GOODS_TYPE=EMS_COMPLEX_GPTMP_TODAY.GOODS_TYPE AND EMS_COMPLEX.G_TYPE=EMS_COMPLEX_GPTMP_TODAY.G_TYPE AND EMS_COMPLEX.CODE_TS=EMS_COMPLEX_GPTMP_TODAY.CODE_TS AND EMS_COMPLEX.CLASSIFY=EMS_COMPLEX_GPTMP_TODAY.CLASSIFY ;
insert into EMS_COMPLEX (GOODS_TYPE,G_TYPE,CODE_TS,G_NAME,CLASSIFY,INPUT_DATE,LIMIT_TYPE,LIMIT_DESC,NOTE) select GOODS_TYPE,G_TYPE,CODE_TS,G_NAME,CLASSIFY,INPUT_DATE,LIMIT_TYPE,LIMIT_DESC,NOTE from EMS_COMPLEX_GPTMP_TODAY  where CMD_TYPE='I';
\timing
