\echo -----------------------ENTRY_CONTAINER------------------------
select now();
\timing
delete from ENTRY_CONTAINER using ENTRY_CONTAINER_GPTMP_TODAY where ENTRY_CONTAINER.ENTRY_ID=ENTRY_CONTAINER_GPTMP_TODAY.ENTRY_ID AND ENTRY_CONTAINER.CONTAINER_ID=ENTRY_CONTAINER_GPTMP_TODAY.CONTAINER_ID ;
insert into ENTRY_CONTAINER (ENTRY_ID,CONTAINER_ID,CONTAINER_WT) select ENTRY_ID,CONTAINER_ID,CONTAINER_WT from ENTRY_CONTAINER_GPTMP_TODAY  where CMD_TYPE='I';
\timing
