\echo -----------------------ENTRY_CONTAINER_LOG------------------------
select now();
\timing
delete from ENTRY_CONTAINER_LOG using ENTRY_CONTAINER_LOG_GPTMP_TODAY where ENTRY_CONTAINER_LOG.ENTRY_ID=ENTRY_CONTAINER_LOG_GPTMP_TODAY.ENTRY_ID AND ENTRY_CONTAINER_LOG.CONTAINER_ID=ENTRY_CONTAINER_LOG_GPTMP_TODAY.CONTAINER_ID AND ENTRY_CONTAINER_LOG.OP_TIME=ENTRY_CONTAINER_LOG_GPTMP_TODAY.OP_TIME ;
insert into ENTRY_CONTAINER_LOG (ENTRY_ID,CONTAINER_ID,CONTAINER_WT,OP_TIME) select ENTRY_ID,CONTAINER_ID,CONTAINER_WT,OP_TIME from ENTRY_CONTAINER_LOG_GPTMP_TODAY  where CMD_TYPE='I';
\timing
