\echo -----------------------ENTRY_GPM_RTX_SENDLOG------------------------
select now();
\timing
delete from ENTRY_GPM_RTX_SENDLOG using ENTRY_GPM_RTX_SENDLOG_GPTMP_TODAY where ENTRY_GPM_RTX_SENDLOG.ENTRY_ID=ENTRY_GPM_RTX_SENDLOG_GPTMP_TODAY.ENTRY_ID AND ENTRY_GPM_RTX_SENDLOG.SIGN_TYPE=ENTRY_GPM_RTX_SENDLOG_GPTMP_TODAY.SIGN_TYPE AND ENTRY_GPM_RTX_SENDLOG.PROC_MODE=ENTRY_GPM_RTX_SENDLOG_GPTMP_TODAY.PROC_MODE AND ENTRY_GPM_RTX_SENDLOG.SEND_DATE=ENTRY_GPM_RTX_SENDLOG_GPTMP_TODAY.SEND_DATE ;
insert into ENTRY_GPM_RTX_SENDLOG (ENTRY_ID,SIGN_TYPE,PROC_MODE,SEND_DATE,SEND_FILE_NAME,SEND_ER) select ENTRY_ID,SIGN_TYPE,PROC_MODE,SEND_DATE,SEND_FILE_NAME,SEND_ER from ENTRY_GPM_RTX_SENDLOG_GPTMP_TODAY  where CMD_TYPE='I';
\timing
