\echo -----------------------ENTRY_WORKFLOW------------------------
select now();
\timing
delete from ENTRY_WORKFLOW using ENTRY_WORKFLOW_GPTMP_TODAY where ENTRY_WORKFLOW.ENTRY_ID=ENTRY_WORKFLOW_GPTMP_TODAY.ENTRY_ID AND ENTRY_WORKFLOW.STEP_ID=ENTRY_WORKFLOW_GPTMP_TODAY.STEP_ID AND ENTRY_WORKFLOW.CREATE_DATE=ENTRY_WORKFLOW_GPTMP_TODAY.CREATE_DATE ;
insert into ENTRY_WORKFLOW (ENTRY_ID,STEP_ID,CREATE_DATE,PROC_POS,STATUS_CODE,PROC_ER,PROC_RESULT,PREV_POS,PREV_ER,RECHK_MARK,RECHK_COMM) select ENTRY_ID,STEP_ID,CREATE_DATE,PROC_POS,STATUS_CODE,PROC_ER,PROC_RESULT,PREV_POS,PREV_ER,RECHK_MARK,RECHK_COMM from ENTRY_WORKFLOW_GPTMP_TODAY  where CMD_TYPE='I';
\timing
