\echo -----------------------ENTRY_MODI_LOG------------------------
select now();
\timing
delete from ENTRY_MODI_LOG using ENTRY_MODI_LOG_GPTMP_TODAY where ENTRY_MODI_LOG.ENTRY_ID=ENTRY_MODI_LOG_GPTMP_TODAY.ENTRY_ID AND ENTRY_MODI_LOG.OP_TIME=ENTRY_MODI_LOG_GPTMP_TODAY.OP_TIME AND ENTRY_MODI_LOG.MODI_TYPE=ENTRY_MODI_LOG_GPTMP_TODAY.MODI_TYPE AND ENTRY_MODI_LOG.ITEM_NAME=ENTRY_MODI_LOG_GPTMP_TODAY.ITEM_NAME ;
insert into ENTRY_MODI_LOG (ENTRY_ID,OP_TIME,MODI_TYPE,ITEM_NAME,ITEM_SOURCE,NOTES,ITEM_CURRENT) select ENTRY_ID,OP_TIME,MODI_TYPE,ITEM_NAME,ITEM_SOURCE,NOTES,ITEM_CURRENT from ENTRY_MODI_LOG_GPTMP_TODAY  where CMD_TYPE='I';
\timing
