\echo -----------------------ENTRY_PROC_LOG------------------------
select now();
\timing
delete from ENTRY_PROC_LOG using ENTRY_PROC_LOG_GPTMP_TODAY where ENTRY_PROC_LOG.ENTRY_ID=ENTRY_PROC_LOG_GPTMP_TODAY.ENTRY_ID AND ENTRY_PROC_LOG.OP_TIME=ENTRY_PROC_LOG_GPTMP_TODAY.OP_TIME AND ENTRY_PROC_LOG.OP_STEP=ENTRY_PROC_LOG_GPTMP_TODAY.OP_STEP ;
insert into ENTRY_PROC_LOG (ENTRY_ID,OP_TIME,OP_STEP,OP_TYPE,OP_SOURCE,OP_DESCRIPTION) select ENTRY_ID,OP_TIME,OP_STEP,OP_TYPE,OP_SOURCE,OP_DESCRIPTION from ENTRY_PROC_LOG_GPTMP_TODAY  where CMD_TYPE='I';
\timing
