\echo -----------------------EPA_SCARP_CERT------------------------
select now();
\timing
delete from EPA_SCARP_CERT using EPA_SCARP_CERT_GPTMP_TODAY where EPA_SCARP_CERT.CERTIFICATE_NO=EPA_SCARP_CERT_GPTMP_TODAY.CERTIFICATE_NO ;
insert into EPA_SCARP_CERT (CERTIFICATE_NO,TRANSFER_NUM,ISSUE_ORGANIZATION,ISSUE_DATE,BEGIN_DATE,END_DATE,OWNER_REG_NO,OWNER_CODE,OWNER_NAME,TRADE_REG_NO,TRADE_CO,TRADE_NAME,CODE_TS,G_NAME,G_QTY,G_UNIT,ORIGIN_COUNTRY,TRADE_MODE,I_E_PORT1,I_E_PORT2,I_E_PORT3,NOTE,OP_MODE,RECV_DATE) select CERTIFICATE_NO,TRANSFER_NUM,ISSUE_ORGANIZATION,ISSUE_DATE,BEGIN_DATE,END_DATE,OWNER_REG_NO,OWNER_CODE,OWNER_NAME,TRADE_REG_NO,TRADE_CO,TRADE_NAME,CODE_TS,G_NAME,G_QTY,G_UNIT,ORIGIN_COUNTRY,TRADE_MODE,I_E_PORT1,I_E_PORT2,I_E_PORT3,NOTE,OP_MODE,RECV_DATE from EPA_SCARP_CERT_GPTMP_TODAY  where CMD_TYPE='I';
\timing
