\echo -----------------------EPA_CHK------------------------
select now();
\timing
delete from EPA_CHK using EPA_CHK_GPTMP_TODAY where EPA_CHK.ENTRY_ID=EPA_CHK_GPTMP_TODAY.ENTRY_ID AND EPA_CHK.CERTIFICATE_NO=EPA_CHK_GPTMP_TODAY.CERTIFICATE_NO AND EPA_CHK.CERT_TYPE=EPA_CHK_GPTMP_TODAY.CERT_TYPE ;
insert into EPA_CHK (ENTRY_ID,CERTIFICATE_NO,CERT_TYPE,CHK_ER,CHK_DATE,REL_ER,REL_DATE,REL_QTY,NOTE) select ENTRY_ID,CERTIFICATE_NO,CERT_TYPE,CHK_ER,CHK_DATE,REL_ER,REL_DATE,REL_QTY,NOTE from EPA_CHK_GPTMP_TODAY  where CMD_TYPE='I';
\timing
