\echo -----------------------EX_ARRIVAL_ERR_CHK------------------------
select now();
\timing
delete from EX_ARRIVAL_ERR_CHK using EX_ARRIVAL_ERR_CHK_GPTMP_TODAY where EX_ARRIVAL_ERR_CHK.ENTRY_ID=EX_ARRIVAL_ERR_CHK_GPTMP_TODAY.ENTRY_ID AND EX_ARRIVAL_ERR_CHK.CHK_DATE=EX_ARRIVAL_ERR_CHK_GPTMP_TODAY.CHK_DATE ;
insert into EX_ARRIVAL_ERR_CHK (ENTRY_ID,CHK_FLAG,CHK_DATE,CHK_ER) select ENTRY_ID,CHK_FLAG,CHK_DATE,CHK_ER from EX_ARRIVAL_ERR_CHK_GPTMP_TODAY  where CMD_TYPE='I';
\timing
