\echo -----------------------EX_ARRIVAL_SHIP------------------------
select now();
\timing
delete from EX_ARRIVAL_SHIP using EX_ARRIVAL_SHIP_GPTMP_TODAY where EX_ARRIVAL_SHIP.VOYAGE_NO=EX_ARRIVAL_SHIP_GPTMP_TODAY.VOYAGE_NO AND EX_ARRIVAL_SHIP.SHIP_NAME_EN=EX_ARRIVAL_SHIP_GPTMP_TODAY.SHIP_NAME_EN AND EX_ARRIVAL_SHIP.CUSTOMS_CODE=EX_ARRIVAL_SHIP_GPTMP_TODAY.CUSTOMS_CODE AND EX_ARRIVAL_SHIP.SHIP_ID=EX_ARRIVAL_SHIP_GPTMP_TODAY.SHIP_ID ;
insert into EX_ARRIVAL_SHIP (VOYAGE_NO,SHIP_NAME_EN,CUSTOMS_CODE,SHIP_ID,I_E_DATE,TRAF_MODE,REC_NO) select VOYAGE_NO,SHIP_NAME_EN,CUSTOMS_CODE,SHIP_ID,I_E_DATE,TRAF_MODE,REC_NO from EX_ARRIVAL_SHIP_GPTMP_TODAY  where CMD_TYPE='I';
\timing
