\echo -----------------------EX_CONTRACT_CLEAR------------------------
select now();
\timing
delete from EX_CONTRACT_CLEAR using EX_CONTRACT_CLEAR_GPTMP_TODAY where EX_CONTRACT_CLEAR.MANUAL_NO=EX_CONTRACT_CLEAR_GPTMP_TODAY.MANUAL_NO AND EX_CONTRACT_CLEAR.CONTR_ITEM=EX_CONTRACT_CLEAR_GPTMP_TODAY.CONTR_ITEM ;
insert into EX_CONTRACT_CLEAR (MANUAL_NO,CONTR_ITEM,APPR_AMT,FACT_AMT,APPR_QTY,FACT_QTY,PRODU_EX_AMT,PRODU_EX_QTY,PRODU_TAX_AMT,PRODU_TAX_QTY,REMAIN_AMT,REMAIN_QTY,ABANDON_AMT,ABANDON_QTY,ABANDON_DATE,ABANDON_ER,UNIT_1,CLEAR_ER,CLEAR_DATE,CLOSE_ER,CLOSE_DATE) select MANUAL_NO,CONTR_ITEM,APPR_AMT,FACT_AMT,APPR_QTY,FACT_QTY,PRODU_EX_AMT,PRODU_EX_QTY,PRODU_TAX_AMT,PRODU_TAX_QTY,REMAIN_AMT,REMAIN_QTY,ABANDON_AMT,ABANDON_QTY,ABANDON_DATE,ABANDON_ER,UNIT_1,CLEAR_ER,CLEAR_DATE,CLOSE_ER,CLOSE_DATE from EX_CONTRACT_CLEAR_GPTMP_TODAY  where CMD_TYPE='I';
\timing
