\echo -----------------------EX_CDL_MNL_DEDUCT------------------------
select now();
\timing
delete from EX_CDL_MNL_DEDUCT using EX_CDL_MNL_DEDUCT_GPTMP_TODAY where EX_CDL_MNL_DEDUCT.MANUAL_NO=EX_CDL_MNL_DEDUCT_GPTMP_TODAY.MANUAL_NO AND EX_CDL_MNL_DEDUCT.ENTRY_ID=EX_CDL_MNL_DEDUCT_GPTMP_TODAY.ENTRY_ID AND EX_CDL_MNL_DEDUCT.G_NO=EX_CDL_MNL_DEDUCT_GPTMP_TODAY.G_NO ;
insert into EX_CDL_MNL_DEDUCT (MANUAL_NO,CONTR_ITEM,ENTRY_ID,ENTRY_ITEM,I_E_PORT,I_E_DATE,G_NO,IN_QTY,I_ACCOUNT,I_CURR,DUTY_MODE,VERIFY_MODE,VERIFY_DATE,VERIFY_ER) select MANUAL_NO,CONTR_ITEM,ENTRY_ID,ENTRY_ITEM,I_E_PORT,I_E_DATE,G_NO,IN_QTY,I_ACCOUNT,I_CURR,DUTY_MODE,VERIFY_MODE,VERIFY_DATE,VERIFY_ER from EX_CDL_MNL_DEDUCT_GPTMP_TODAY  where CMD_TYPE='I';
\timing
