\echo -----------------------EX_CONTA_ENTRY_CHK------------------------
select now();
\timing
delete from EX_CONTA_ENTRY_CHK using EX_CONTA_ENTRY_CHK_GPTMP_TODAY where EX_CONTA_ENTRY_CHK.CONTA_ID=EX_CONTA_ENTRY_CHK_GPTMP_TODAY.CONTA_ID AND EX_CONTA_ENTRY_CHK.BILL_NO=EX_CONTA_ENTRY_CHK_GPTMP_TODAY.BILL_NO AND EX_CONTA_ENTRY_CHK.REC_NO=EX_CONTA_ENTRY_CHK_GPTMP_TODAY.REC_NO AND EX_CONTA_ENTRY_CHK.ENTRY_ID=EX_CONTA_ENTRY_CHK_GPTMP_TODAY.ENTRY_ID ;
insert into EX_CONTA_ENTRY_CHK (CONTA_ID,BILL_NO,REC_NO,ENTRY_ID,CHK_DATE,CHK_ER) select CONTA_ID,BILL_NO,REC_NO,ENTRY_ID,CHK_DATE,CHK_ER from EX_CONTA_ENTRY_CHK_GPTMP_TODAY  where CMD_TYPE='I';
\timing
