\echo -----------------------EX_COP_RATE------------------------
select now();
\timing
delete from EX_COP_RATE using EX_COP_RATE_GPTMP_TODAY where EX_COP_RATE.TRADE_CO=EX_COP_RATE_GPTMP_TODAY.TRADE_CO AND EX_COP_RATE.CHKSTDATE=EX_COP_RATE_GPTMP_TODAY.CHKSTDATE AND EX_COP_RATE.CHKENDDATE=EX_COP_RATE_GPTMP_TODAY.CHKENDDATE ;
insert into EX_COP_RATE (TRADE_CO,CHKSTDATE,CHKENDDATE,CORCORPNAME,CHKRATE,RECV_DATE) select TRADE_CO,CHKSTDATE,CHKENDDATE,CORCORPNAME,CHKRATE,RECV_DATE from EX_COP_RATE_GPTMP_TODAY  where CMD_TYPE='I';
\timing
