\echo -----------------------EX_DECL_HIS_LIST------------------------
select now();
\timing
delete from EX_DECL_HIS_LIST using EX_DECL_HIS_LIST_GPTMP_TODAY where EX_DECL_HIS_LIST.PRE_NO=EX_DECL_HIS_LIST_GPTMP_TODAY.PRE_NO AND EX_DECL_HIS_LIST.RECORD_NUMBER=EX_DECL_HIS_LIST_GPTMP_TODAY.RECORD_NUMBER AND EX_DECL_HIS_LIST.G_NO=EX_DECL_HIS_LIST_GPTMP_TODAY.G_NO ;
insert into EX_DECL_HIS_LIST (PRE_NO,TURN_NO,BATCH_NO,RECORD_NUMBER,G_NO,CODE_TS,G_NAME,PACK_TYPE,GOODS_PIECE,GOODS_AMOUNT,GOODS_UNIT,GOODS_WEIGHT,GOODS_PRICE,GOODS_CURR,GOODS_CHK_MARK) select PRE_NO,TURN_NO,BATCH_NO,RECORD_NUMBER,G_NO,CODE_TS,G_NAME,PACK_TYPE,GOODS_PIECE,GOODS_AMOUNT,GOODS_UNIT,GOODS_WEIGHT,GOODS_PRICE,GOODS_CURR,GOODS_CHK_MARK from EX_DECL_HIS_LIST_GPTMP_TODAY  where CMD_TYPE='I';
\timing
