\echo -----------------------EX_FASCICLE_LIST------------------------
select now();
\timing
delete from EX_FASCICLE_LIST using EX_FASCICLE_LIST_GPTMP_TODAY where EX_FASCICLE_LIST.FASCICLE_NO=EX_FASCICLE_LIST_GPTMP_TODAY.FASCICLE_NO AND EX_FASCICLE_LIST.CONTR_ITEM=EX_FASCICLE_LIST_GPTMP_TODAY.CONTR_ITEM ;
insert into EX_FASCICLE_LIST (MANUAL_NO,FASCICLE_NO,CONTR_ITEM,APPR_QTY,FACT_QTY) select MANUAL_NO,FASCICLE_NO,CONTR_ITEM,APPR_QTY,FACT_QTY from EX_FASCICLE_LIST_GPTMP_TODAY  where CMD_TYPE='I';
\timing
