\echo -----------------------EX_TRANS_GOODS_CONTA_REL------------------------
select now();
\timing
delete from EX_TRANS_GOODS_CONTA_REL using EX_TRANS_GOODS_CONTA_REL_GPTMP_TODAY where EX_TRANS_GOODS_CONTA_REL.PRE_NO=EX_TRANS_GOODS_CONTA_REL_GPTMP_TODAY.PRE_NO AND EX_TRANS_GOODS_CONTA_REL.RECORD_NUMBER=EX_TRANS_GOODS_CONTA_REL_GPTMP_TODAY.RECORD_NUMBER AND EX_TRANS_GOODS_CONTA_REL.G_NO=EX_TRANS_GOODS_CONTA_REL_GPTMP_TODAY.G_NO AND EX_TRANS_GOODS_CONTA_REL.CONTA_NO=EX_TRANS_GOODS_CONTA_REL_GPTMP_TODAY.CONTA_NO ;
insert into EX_TRANS_GOODS_CONTA_REL (PRE_NO,RECORD_NUMBER,G_NO,CONTA_NO,CONTA_GOODS_COUNT,CONTA_GOODS_WEIGHT,SEND_PORT,RECV_PORT) select PRE_NO,RECORD_NUMBER,G_NO,CONTA_NO,CONTA_GOODS_COUNT,CONTA_GOODS_WEIGHT,SEND_PORT,RECV_PORT from EX_TRANS_GOODS_CONTA_REL_GPTMP_TODAY  where CMD_TYPE='I';
\timing
