\echo -----------------------EX_TRN_CONTA_ENTRY_ARV------------------------
select now();
\timing
delete from EX_TRN_CONTA_ENTRY_ARV using EX_TRN_CONTA_ENTRY_ARV_GPTMP_TODAY where EX_TRN_CONTA_ENTRY_ARV.ENTRY_ID=EX_TRN_CONTA_ENTRY_ARV_GPTMP_TODAY.ENTRY_ID AND EX_TRN_CONTA_ENTRY_ARV.CONTA_ID=EX_TRN_CONTA_ENTRY_ARV_GPTMP_TODAY.CONTA_ID ;
insert into EX_TRN_CONTA_ENTRY_ARV (ENTRY_ID,CONTA_ID,CUSTOMS_CODE,TRAF_MODE,TRAF_NAME,VOYAGE_NO,BILL_NO,PACK_NO,GROSS_WT,ARV_FLAG,TRN_MODE) select ENTRY_ID,CONTA_ID,CUSTOMS_CODE,TRAF_MODE,TRAF_NAME,VOYAGE_NO,BILL_NO,PACK_NO,GROSS_WT,ARV_FLAG,TRN_MODE from EX_TRN_CONTA_ENTRY_ARV_GPTMP_TODAY  where CMD_TYPE='I';
\timing
