\echo -----------------------EX_TRANS_LIST_REL------------------------
select now();
\timing
delete from EX_TRANS_LIST_REL using EX_TRANS_LIST_REL_GPTMP_TODAY where EX_TRANS_LIST_REL.PRE_NO=EX_TRANS_LIST_REL_GPTMP_TODAY.PRE_NO AND EX_TRANS_LIST_REL.RECORD_NUMBER=EX_TRANS_LIST_REL_GPTMP_TODAY.RECORD_NUMBER ;
insert into EX_TRANS_LIST_REL (PRE_NO,RECORD_NUMBER,TRAF_MODE,SHIP_ID,SHIP_NAME_EN,VOYAGE_NO,BILL_NO,I_E_DATE,ENTRY_NO,BIND_FLAG,REC_FLAG,PACK_NO,GROSS_WT,GOODS_COUNT,CONTA_C,OWNER_NAME,EX_CHECK_FLAG,EX_CHECK_TIME,REAL_PACK_NO,REAL_GROSS_WT,NOTE,SEND_PORT,RECV_PORT) select PRE_NO,RECORD_NUMBER,TRAF_MODE,SHIP_ID,SHIP_NAME_EN,VOYAGE_NO,BILL_NO,I_E_DATE,ENTRY_NO,BIND_FLAG,REC_FLAG,PACK_NO,GROSS_WT,GOODS_COUNT,CONTA_C,OWNER_NAME,EX_CHECK_FLAG,EX_CHECK_TIME,REAL_PACK_NO,REAL_GROSS_WT,NOTE,SEND_PORT,RECV_PORT from EX_TRANS_LIST_REL_GPTMP_TODAY  where CMD_TYPE='I';
\timing
