\echo -----------------------EXA_APPL_CLOSE------------------------
select now();
\timing
delete from EXA_APPL_CLOSE using EXA_APPL_CLOSE_GPTMP_TODAY where EXA_APPL_CLOSE.MANUAL_NO=EXA_APPL_CLOSE_GPTMP_TODAY.MANUAL_NO AND EXA_APPL_CLOSE.CONTR_ITEM=EXA_APPL_CLOSE_GPTMP_TODAY.CONTR_ITEM ;
insert into EXA_APPL_CLOSE (MANUAL_NO,CONTR_ITEM,CODE_TS,G_NAME,G_MODEL,G_QTY,DECL_PRICE,G_AMT,PROC_MODE,BOOK_NO) select MANUAL_NO,CONTR_ITEM,CODE_TS,G_NAME,G_MODEL,G_QTY,DECL_PRICE,G_AMT,PROC_MODE,BOOK_NO from EXA_APPL_CLOSE_GPTMP_TODAY  where CMD_TYPE='I';
\timing
