\echo -----------------------EXAM_CONTA_END_LOG------------------------
select now();
\timing
delete from EXAM_CONTA_END_LOG using EXAM_CONTA_END_LOG_GPTMP_TODAY where EXAM_CONTA_END_LOG.EXAM_REC_ID=EXAM_CONTA_END_LOG_GPTMP_TODAY.EXAM_REC_ID AND EXAM_CONTA_END_LOG.END_TIME=EXAM_CONTA_END_LOG_GPTMP_TODAY.END_TIME ;
insert into EXAM_CONTA_END_LOG (EXAM_REC_ID,RSK_NO,END_ER,END_TIME,END_REASON) select EXAM_REC_ID,RSK_NO,END_ER,END_TIME,END_REASON from EXAM_CONTA_END_LOG_GPTMP_TODAY  where CMD_TYPE='I';
\timing
