\echo -----------------------EXAM_CONTA_LIST------------------------
select now();
\timing
delete from EXAM_CONTA_LIST using EXAM_CONTA_LIST_GPTMP_TODAY where EXAM_CONTA_LIST.EXAM_REC_ID=EXAM_CONTA_LIST_GPTMP_TODAY.EXAM_REC_ID AND EXAM_CONTA_LIST.CONTA_ID=EXAM_CONTA_LIST_GPTMP_TODAY.CONTA_ID ;
insert into EXAM_CONTA_LIST (EXAM_REC_ID,CONTA_ID,HOLLOW_AREA1,HOLLOW_AREA2,CHK_SEAL,CHK_TRUNK,CHK_CONTA_ID,EXAM_RESULT) select EXAM_REC_ID,CONTA_ID,HOLLOW_AREA1,HOLLOW_AREA2,CHK_SEAL,CHK_TRUNK,CHK_CONTA_ID,EXAM_RESULT from EXAM_CONTA_LIST_GPTMP_TODAY  where CMD_TYPE='I';
\timing
