\echo -----------------------EXC_ELE------------------------
select now();
\timing
delete from EXC_ELE using EXC_ELE_GPTMP_TODAY where EXC_ELE.HXD_NO=EXC_ELE_GPTMP_TODAY.HXD_NO ;
insert into EXC_ELE (SEQ_NO,HXD_NO,WGJ_CODE,ENT_CODE,TRADE_CO,WGJ_STATE,REASON_CODE,PROVIDE_DATE,PROVIDE_NAME,OPER_DATE,OPER_NAME,HG_STATE,HG_OPER_DATE,HG_OPER_NAME,LOSS_STATE,LOSS_DATE,LOSS_NAME,PORT_CODE,PORT_DATE,PORT_NAME,DEAL_STATE,DEAL_DATE,DEAL_NAME,PAPER_BILL,RECV_DATE,CANCEL_DATE,ENTRY_ID,CUS_CODE,DECL_DATE,CHK_MARK,DATA_SIGN) select SEQ_NO,HXD_NO,WGJ_CODE,ENT_CODE,TRADE_CO,WGJ_STATE,REASON_CODE,PROVIDE_DATE,PROVIDE_NAME,OPER_DATE,OPER_NAME,HG_STATE,HG_OPER_DATE,HG_OPER_NAME,LOSS_STATE,LOSS_DATE,LOSS_NAME,PORT_CODE,PORT_DATE,PORT_NAME,DEAL_STATE,DEAL_DATE,DEAL_NAME,PAPER_BILL,RECV_DATE,CANCEL_DATE,ENTRY_ID,CUS_CODE,DECL_DATE,CHK_MARK,DATA_SIGN from EXC_ELE_GPTMP_TODAY  where CMD_TYPE='I';
\timing
