\echo -----------------------EXC_EXAM------------------------
select now();
\timing
delete from EXC_EXAM using EXC_EXAM_GPTMP_TODAY where EXC_EXAM.HXD_NO=EXC_EXAM_GPTMP_TODAY.HXD_NO ;
insert into EXC_EXAM (SEQ_NO,HXD_NO,ENTRY_ID,CUS_CODE,DECL_DATE,IMPLE_DATE,IMPLE_ER,RET_DATE,EXC_MARK,DELE_DATE,DELE_ER,DATA_SIGN) select SEQ_NO,HXD_NO,ENTRY_ID,CUS_CODE,DECL_DATE,IMPLE_DATE,IMPLE_ER,RET_DATE,EXC_MARK,DELE_DATE,DELE_ER,DATA_SIGN from EXC_EXAM_GPTMP_TODAY  where CMD_TYPE='I';
\timing
