\echo -----------------------EXTERNAL_JOU------------------------
select now();
\timing
delete from EXTERNAL_JOU using EXTERNAL_JOU_GPTMP_TODAY where EXTERNAL_JOU.MANUAL_NO=EXTERNAL_JOU_GPTMP_TODAY.MANUAL_NO AND EXTERNAL_JOU.CUSTOMS_CODE=EXTERNAL_JOU_GPTMP_TODAY.CUSTOMS_CODE AND EXTERNAL_JOU.APPL_NO=EXTERNAL_JOU_GPTMP_TODAY.APPL_NO ;
insert into EXTERNAL_JOU (MANUAL_NO,CUSTOMS_CODE,APPL_NO,FASCICLE_NO,E_DATE,APPL_ER,APPL_DATE,RETURN_DATE,RETURN_FLAG,PASSWORD,NOTE_S) select MANUAL_NO,CUSTOMS_CODE,APPL_NO,FASCICLE_NO,E_DATE,APPL_ER,APPL_DATE,RETURN_DATE,RETURN_FLAG,PASSWORD,NOTE_S from EXTERNAL_JOU_GPTMP_TODAY  where CMD_TYPE='I';
\timing
