\echo -----------------------FCB_RSK------------------------
select now();
\timing
delete from FCB_RSK using FCB_RSK_GPTMP_TODAY where FCB_RSK.FCB_ID=FCB_RSK_GPTMP_TODAY.FCB_ID AND FCB_RSK.CUSTOMS_CODE=FCB_RSK_GPTMP_TODAY.CUSTOMS_CODE ;
insert into FCB_RSK (FCB_ID,CUSTOMS_CODE,INPUT_ER,INPUT_TIME,REQUIRE,RELEASE_ER,RELEASE_TIME,RESULT) select FCB_ID,CUSTOMS_CODE,INPUT_ER,INPUT_TIME,REQUIRE,RELEASE_ER,RELEASE_TIME,RESULT from FCB_RSK_GPTMP_TODAY  where CMD_TYPE='I';
\timing
