\echo -----------------------FCB_WORKFLOW------------------------
select now();
\timing
delete from FCB_WORKFLOW using FCB_WORKFLOW_GPTMP_TODAY where FCB_WORKFLOW.FCB_ID=FCB_WORKFLOW_GPTMP_TODAY.FCB_ID AND FCB_WORKFLOW.STEP_ID=FCB_WORKFLOW_GPTMP_TODAY.STEP_ID AND FCB_WORKFLOW.CREATE_DATE=FCB_WORKFLOW_GPTMP_TODAY.CREATE_DATE ;
insert into FCB_WORKFLOW (FCB_ID,STEP_ID,CREATE_DATE,PROC_ER,PROC_RESULT,RECHK_COMM,PORT_CUS,MAIN_CUS) select FCB_ID,STEP_ID,CREATE_DATE,PROC_ER,PROC_RESULT,RECHK_COMM,PORT_CUS,MAIN_CUS from FCB_WORKFLOW_GPTMP_TODAY  where CMD_TYPE='I';
\timing
