\echo -----------------------FCB_CONTA------------------------
select now();
\timing
delete from FCB_CONTA using FCB_CONTA_GPTMP_TODAY where FCB_CONTA.FCB_ID=FCB_CONTA_GPTMP_TODAY.FCB_ID AND FCB_CONTA.CONTA_ID=FCB_CONTA_GPTMP_TODAY.CONTA_ID ;
insert into FCB_CONTA (FCB_ID,CONTA_ID,ESEAL_ID,CONTA_MODEL,CONTA_TYPE,PORT_CUS,MAIN_CUS,DE_CONSOLIDATOR,CONTA_WT,NOTE) select FCB_ID,CONTA_ID,ESEAL_ID,CONTA_MODEL,CONTA_TYPE,PORT_CUS,MAIN_CUS,DE_CONSOLIDATOR,CONTA_WT,NOTE from FCB_CONTA_GPTMP_TODAY  where CMD_TYPE='I';
\timing
