\echo -----------------------FORFEIT_FORM------------------------
select now();
\timing
delete from FORFEIT_FORM using FORFEIT_FORM_GPTMP_TODAY where FORFEIT_FORM.FMS_ID=FORFEIT_FORM_GPTMP_TODAY.FMS_ID ;
insert into FORFEIT_FORM (FMS_ID,DEPARTMENT,DEPARTMENT_NOTE,DISTRICT_CODE,PAYER_NAME,FMS_CLASS,FMS_AMOUNT,OPER_CODE,LAW_ID,TAX_FLAG,LIMIT_DAY,FMS_MODE,CREATE_DATE,CUSTOMS_CODE,SECTION_ID,GROUP_ID) select FMS_ID,DEPARTMENT,DEPARTMENT_NOTE,DISTRICT_CODE,PAYER_NAME,FMS_CLASS,FMS_AMOUNT,OPER_CODE,LAW_ID,TAX_FLAG,LIMIT_DAY,FMS_MODE,CREATE_DATE,CUSTOMS_CODE,SECTION_ID,GROUP_ID from FORFEIT_FORM_GPTMP_TODAY  where CMD_TYPE='I';
\timing
