\echo -----------------------GUARANTEE_LIST------------------------
select now();
\timing
delete from GUARANTEE_LIST using GUARANTEE_LIST_GPTMP_TODAY where GUARANTEE_LIST.ENTRY_ID=GUARANTEE_LIST_GPTMP_TODAY.ENTRY_ID AND GUARANTEE_LIST.G_NO=GUARANTEE_LIST_GPTMP_TODAY.G_NO AND GUARANTEE_LIST.TAX_TYPE=GUARANTEE_LIST_GPTMP_TODAY.TAX_TYPE ;
insert into GUARANTEE_LIST (ENTRY_ID,G_NO,CODE_TS,GRT_ACCOUNT,GRT_RATE,APP_REASON,TAX_TYPE,ACTION_NO,COMPANY_NAME_CN,COMPANY_NAME_EN) select ENTRY_ID,G_NO,CODE_TS,GRT_ACCOUNT,GRT_RATE,APP_REASON,TAX_TYPE,ACTION_NO,COMPANY_NAME_CN,COMPANY_NAME_EN from GUARANTEE_LIST_GPTMP_TODAY  where CMD_TYPE='I';
\timing
