\echo -----------------------H2000_SMS_SEND------------------------
select now();
\timing
delete from H2000_SMS_SEND using H2000_SMS_SEND_GPTMP_TODAY where H2000_SMS_SEND.SEQUENCE_NO=H2000_SMS_SEND_GPTMP_TODAY.SEQUENCE_NO AND H2000_SMS_SEND.FORM_ID=H2000_SMS_SEND_GPTMP_TODAY.FORM_ID AND H2000_SMS_SEND.SYSTEM_ID=H2000_SMS_SEND_GPTMP_TODAY.SYSTEM_ID AND H2000_SMS_SEND.POS_ID=H2000_SMS_SEND_GPTMP_TODAY.POS_ID AND H2000_SMS_SEND.OP_TIME=H2000_SMS_SEND_GPTMP_TODAY.OP_TIME AND H2000_SMS_SEND.PHONE_NO=H2000_SMS_SEND_GPTMP_TODAY.PHONE_NO ;
insert into H2000_SMS_SEND (SEQUENCE_NO,FORM_ID,CUSTOMS_CODE,SYSTEM_ID,POS_ID,OP_TIME,PHONE_NO,MSG_TEXT,PROC_FLAG,NOTES) select SEQUENCE_NO,FORM_ID,CUSTOMS_CODE,SYSTEM_ID,POS_ID,OP_TIME,PHONE_NO,MSG_TEXT,PROC_FLAG,NOTES from H2000_SMS_SEND_GPTMP_TODAY  where CMD_TYPE='I';
\timing
