\echo -----------------------H2000_SMS_SENDLOG------------------------
select now();
\timing
delete from H2000_SMS_SENDLOG using H2000_SMS_SENDLOG_GPTMP_TODAY where H2000_SMS_SENDLOG.SEQUENCE_NO=H2000_SMS_SENDLOG_GPTMP_TODAY.SEQUENCE_NO AND H2000_SMS_SENDLOG.FORM_ID=H2000_SMS_SENDLOG_GPTMP_TODAY.FORM_ID AND H2000_SMS_SENDLOG.SYSTEM_ID=H2000_SMS_SENDLOG_GPTMP_TODAY.SYSTEM_ID AND H2000_SMS_SENDLOG.POS_ID=H2000_SMS_SENDLOG_GPTMP_TODAY.POS_ID AND H2000_SMS_SENDLOG.OP_TIME=H2000_SMS_SENDLOG_GPTMP_TODAY.OP_TIME AND H2000_SMS_SENDLOG.PHONE_NO=H2000_SMS_SENDLOG_GPTMP_TODAY.PHONE_NO ;
insert into H2000_SMS_SENDLOG (SEQUENCE_NO,FORM_ID,CUSTOMS_CODE,SYSTEM_ID,POS_ID,OP_TIME,PHONE_NO,MSG_TEXT,NOTES,LOG_TIME) select SEQUENCE_NO,FORM_ID,CUSTOMS_CODE,SYSTEM_ID,POS_ID,OP_TIME,PHONE_NO,MSG_TEXT,NOTES,LOG_TIME from H2000_SMS_SENDLOG_GPTMP_TODAY  where CMD_TYPE='I';
\timing
