\echo -----------------------HIS_TRN_COP_REL------------------------
select now();
\timing
delete from HIS_TRN_COP_REL using HIS_TRN_COP_REL_GPTMP_TODAY where HIS_TRN_COP_REL.CO_REG_NO=HIS_TRN_COP_REL_GPTMP_TODAY.CO_REG_NO AND HIS_TRN_COP_REL.MODI_COUNT=HIS_TRN_COP_REL_GPTMP_TODAY.MODI_COUNT ;
insert into HIS_TRN_COP_REL (CO_REG_NO,CO_CUSTOMS_NO,MAIN_PORT,CO_NAME,CO_ADDRESS,CO_PHONE_NO,VALID_FLAG,VALID_DATE,INPUT_DATE,INPUT_OP_ID,PERMIT_FLAG,PERMIT_DATE,PERMIT_OP_ID,MODI_OP_ID,MODI_TIME,MODI_COUNT,RESERV_FIELD,CO_REG_TYPE,CO_PROPERTY,CO_DEAL_RANGE,CO_AUTHORIZE_NO,CO_DEAL_DATE,CO_CORPORATION_REP,CO_ABROAD_NAME,GANG_AO_CARS,GANG_AO_CARS_USED,CK_FLAG,NOTE_FIELD) select CO_REG_NO,CO_CUSTOMS_NO,MAIN_PORT,CO_NAME,CO_ADDRESS,CO_PHONE_NO,VALID_FLAG,VALID_DATE,INPUT_DATE,INPUT_OP_ID,PERMIT_FLAG,PERMIT_DATE,PERMIT_OP_ID,MODI_OP_ID,MODI_TIME,MODI_COUNT,RESERV_FIELD,CO_REG_TYPE,CO_PROPERTY,CO_DEAL_RANGE,CO_AUTHORIZE_NO,CO_DEAL_DATE,CO_CORPORATION_REP,CO_ABROAD_NAME,GANG_AO_CARS,GANG_AO_CARS_USED,CK_FLAG,NOTE_FIELD from HIS_TRN_COP_REL_GPTMP_TODAY  where CMD_TYPE='I';
\timing
