\echo -----------------------IM_CONTRACT_LIST------------------------
select now();
\timing
delete from IM_CONTRACT_LIST using IM_CONTRACT_LIST_GPTMP_TODAY where IM_CONTRACT_LIST.MANUAL_NO=IM_CONTRACT_LIST_GPTMP_TODAY.MANUAL_NO AND IM_CONTRACT_LIST.CONTR_ITEM=IM_CONTRACT_LIST_GPTMP_TODAY.CONTR_ITEM ;
insert into IM_CONTRACT_LIST (MANUAL_NO,CONTR_ITEM,CODE_TS,CLASS_MARK,G_NAME,G_MODEL,ORIGIN_COUNTRY,DUTY_MODE,DUTY_RATIO,LOCAL_CONTR,APPR_AMT,FACT_AMT,UNIT_PRICE,APPR_QTY,FACT_QTY,TRANSFER_QTY,UNIT_1,IN_COUNT,IM_MODE,CONSUME_NOTE) select MANUAL_NO,CONTR_ITEM,CODE_TS,CLASS_MARK,G_NAME,G_MODEL,ORIGIN_COUNTRY,DUTY_MODE,DUTY_RATIO,LOCAL_CONTR,APPR_AMT,FACT_AMT,UNIT_PRICE,APPR_QTY,FACT_QTY,TRANSFER_QTY,UNIT_1,IN_COUNT,IM_MODE,CONSUME_NOTE from IM_CONTRACT_LIST_GPTMP_TODAY  where CMD_TYPE='I';
\timing
