\echo -----------------------IM_CDL_MNL_DEDUCT------------------------
select now();
\timing
delete from IM_CDL_MNL_DEDUCT using IM_CDL_MNL_DEDUCT_GPTMP_TODAY where IM_CDL_MNL_DEDUCT.MANUAL_NO=IM_CDL_MNL_DEDUCT_GPTMP_TODAY.MANUAL_NO AND IM_CDL_MNL_DEDUCT.ENTRY_ID=IM_CDL_MNL_DEDUCT_GPTMP_TODAY.ENTRY_ID AND IM_CDL_MNL_DEDUCT.G_NO=IM_CDL_MNL_DEDUCT_GPTMP_TODAY.G_NO ;
insert into IM_CDL_MNL_DEDUCT (MANUAL_NO,CONTR_ITEM,ENTRY_ID,ENTRY_ITEM,I_E_PORT,I_E_DATE,G_NO,IN_QTY,I_ACCOUNT,I_CURR,DUTY_MODE,VERIFY_MODE,VERIFY_DATE,VERIFY_ER,DUTY_PRINT) select MANUAL_NO,CONTR_ITEM,ENTRY_ID,ENTRY_ITEM,I_E_PORT,I_E_DATE,G_NO,IN_QTY,I_ACCOUNT,I_CURR,DUTY_MODE,VERIFY_MODE,VERIFY_DATE,VERIFY_ER,DUTY_PRINT from IM_CDL_MNL_DEDUCT_GPTMP_TODAY  where CMD_TYPE='I';
\timing
