\echo -----------------------IM_COP_RATE------------------------
select now();
\timing
delete from IM_COP_RATE using IM_COP_RATE_GPTMP_TODAY where IM_COP_RATE.TRADE_CO=IM_COP_RATE_GPTMP_TODAY.TRADE_CO AND IM_COP_RATE.CHKSTDATE=IM_COP_RATE_GPTMP_TODAY.CHKSTDATE AND IM_COP_RATE.CHKENDDATE=IM_COP_RATE_GPTMP_TODAY.CHKENDDATE ;
insert into IM_COP_RATE (TRADE_CO,CHKSTDATE,CHKENDDATE,CORCORPNAME,CHKRATE,RECV_DATE) select TRADE_CO,CHKSTDATE,CHKENDDATE,CORCORPNAME,CHKRATE,RECV_DATE from IM_COP_RATE_GPTMP_TODAY  where CMD_TYPE='I';
\timing
