\echo -----------------------IM_EXAM_MANA_LIST------------------------
select now();
\timing
delete from IM_EXAM_MANA_LIST using IM_EXAM_MANA_LIST_GPTMP_TODAY where IM_EXAM_MANA_LIST.LICENSE_NO=IM_EXAM_MANA_LIST_GPTMP_TODAY.LICENSE_NO AND IM_EXAM_MANA_LIST.L_G_NO=IM_EXAM_MANA_LIST_GPTMP_TODAY.L_G_NO ;
insert into IM_EXAM_MANA_LIST (LICENSE_NO,L_G_NO,L_FACT_AQTY,L_FACT_AUSED,L_REUSE1,L_REUSE2) select LICENSE_NO,L_G_NO,L_FACT_AQTY,L_FACT_AUSED,L_REUSE1,L_REUSE2 from IM_EXAM_MANA_LIST_GPTMP_TODAY  where CMD_TYPE='I';
\timing
