\echo -----------------------IM_EXAM_MANA_HEAD------------------------
select now();
\timing
delete from IM_EXAM_MANA_HEAD using IM_EXAM_MANA_HEAD_GPTMP_TODAY where IM_EXAM_MANA_HEAD.LICENSE_NO=IM_EXAM_MANA_HEAD_GPTMP_TODAY.LICENSE_NO ;
insert into IM_EXAM_MANA_HEAD (LICENSE_NO,FACT_AQTY,FACT_AUSED,FACT_MARK,EXE_MARK,DELAY_MARK,CLOSE_MARK,CLOSE_DATE,CLOSE_TIME,CLOSE_ER,EXE_PORT,TRAN_PORT,TRAN_DATE,TRAN_TIME,CHECK_MARK,CHECK_DATE,CHECK_TIME,CHECK_ER,SEND_GEN_DATE,SEND_FOR_DATE,SOURCE_PORT,NOTE_S,OVER_ALLOW,SECURITY_ID,REUSE1,REUSE2) select LICENSE_NO,FACT_AQTY,FACT_AUSED,FACT_MARK,EXE_MARK,DELAY_MARK,CLOSE_MARK,CLOSE_DATE,CLOSE_TIME,CLOSE_ER,EXE_PORT,TRAN_PORT,TRAN_DATE,TRAN_TIME,CHECK_MARK,CHECK_DATE,CHECK_TIME,CHECK_ER,SEND_GEN_DATE,SEND_FOR_DATE,SOURCE_PORT,NOTE_S,OVER_ALLOW,SECURITY_ID,REUSE1,REUSE2 from IM_EXAM_MANA_HEAD_GPTMP_TODAY  where CMD_TYPE='I';
\timing
