\echo -----------------------IM_FASCICLE_LIST------------------------
select now();
\timing
delete from IM_FASCICLE_LIST using IM_FASCICLE_LIST_GPTMP_TODAY where IM_FASCICLE_LIST.FASCICLE_NO=IM_FASCICLE_LIST_GPTMP_TODAY.FASCICLE_NO AND IM_FASCICLE_LIST.CONTR_ITEM=IM_FASCICLE_LIST_GPTMP_TODAY.CONTR_ITEM ;
insert into IM_FASCICLE_LIST (MANUAL_NO,FASCICLE_NO,CONTR_ITEM,APPR_QTY,FACT_QTY) select MANUAL_NO,FASCICLE_NO,CONTR_ITEM,APPR_QTY,FACT_QTY from IM_FASCICLE_LIST_GPTMP_TODAY  where CMD_TYPE='I';
\timing
