\echo -----------------------IM_TRANS_HIS_CONTA_REL------------------------
select now();
\timing
delete from IM_TRANS_HIS_CONTA_REL using IM_TRANS_HIS_CONTA_REL_GPTMP_TODAY where IM_TRANS_HIS_CONTA_REL.PRE_NO=IM_TRANS_HIS_CONTA_REL_GPTMP_TODAY.PRE_NO AND IM_TRANS_HIS_CONTA_REL.RECORD_NUMBER=IM_TRANS_HIS_CONTA_REL_GPTMP_TODAY.RECORD_NUMBER AND IM_TRANS_HIS_CONTA_REL.CONTA_NO=IM_TRANS_HIS_CONTA_REL_GPTMP_TODAY.CONTA_NO ;
insert into IM_TRANS_HIS_CONTA_REL (PRE_NO,RECORD_NUMBER,CONTA_NO,TRANS_NAME,TRANS_WEIGHT,CONTA_MODEL,SEAL_NO,SEAL_NUM,CONTA_CHECK_MARK,CONTA_CHK_ER,CONTA_CHK_TIME,EXAM_FLAG,CONTA1) select PRE_NO,RECORD_NUMBER,CONTA_NO,TRANS_NAME,TRANS_WEIGHT,CONTA_MODEL,SEAL_NO,SEAL_NUM,CONTA_CHECK_MARK,CONTA_CHK_ER,CONTA_CHK_TIME,EXAM_FLAG,CONTA1 from IM_TRANS_HIS_CONTA_REL_GPTMP_TODAY  where CMD_TYPE='I';
\timing
