\echo -----------------------INCOME_INFO------------------------
select now();
\timing
delete from INCOME_INFO using INCOME_INFO_GPTMP_TODAY where INCOME_INFO.RPTNO=INCOME_INFO_GPTMP_TODAY.RPTNO ;
insert into INCOME_INFO (RPTNO,CORCORPNAME,TRADE_CO,CSTSETCODE,TXCCY,TXAMT,INCHARGECCY,INCHARGEAMT,OUTCHARGECCY,OUTCHARGEAMT,OPPNAME,COUNTRYCODE,RCVTYPE,ISWRITEOFF,RECV_DATE) select RPTNO,CORCORPNAME,TRADE_CO,CSTSETCODE,TXCCY,TXAMT,INCHARGECCY,INCHARGEAMT,OUTCHARGECCY,OUTCHARGEAMT,OPPNAME,COUNTRYCODE,RCVTYPE,ISWRITEOFF,RECV_DATE from INCOME_INFO_GPTMP_TODAY  where CMD_TYPE='I';
\timing
