\echo -----------------------INVESTER_REL------------------------
select now();
\timing
delete from INVESTER_REL using INVESTER_REL_GPTMP_TODAY where INVESTER_REL.TRADE_CO=INVESTER_REL_GPTMP_TODAY.TRADE_CO AND INVESTER_REL.INV_NO=INVESTER_REL_GPTMP_TODAY.INV_NO ;
insert into INVESTER_REL (TRADE_CO,INV_NO,INV_CO,INV_MOD,INV_FUND,ACT_FUND,INV_DATE,INV_COUNTRY) select TRADE_CO,INV_NO,INV_CO,INV_MOD,INV_FUND,ACT_FUND,INV_DATE,INV_COUNTRY from INVESTER_REL_GPTMP_TODAY  where CMD_TYPE='I';
\timing
