\echo -----------------------INVLOG_REL------------------------
select now();
\timing
delete from INVLOG_REL using INVLOG_REL_GPTMP_TODAY where INVLOG_REL.LOG_ID=INVLOG_REL_GPTMP_TODAY.LOG_ID ;
insert into INVLOG_REL (LOG_ID,LOG_MODE,LOG_DATE,LOG_OPER_ID,LOG_CUSTOMS_CODE,LOG_COMPUTER,TRADE_CO,INV_NO,INV_CO,INV_MOD,INV_FUND,ACT_FUND,INV_DATE,INV_COUNTRY) select LOG_ID,LOG_MODE,LOG_DATE,LOG_OPER_ID,LOG_CUSTOMS_CODE,LOG_COMPUTER,TRADE_CO,INV_NO,INV_CO,INV_MOD,INV_FUND,ACT_FUND,INV_DATE,INV_COUNTRY from INVLOG_REL_GPTMP_TODAY  where CMD_TYPE='I';
\timing
