\echo -----------------------JOB_PARAMETER------------------------
select now();
\timing
delete from JOB_PARAMETER using JOB_PARAMETER_GPTMP_TODAY where JOB_PARAMETER.JOB_NAME=JOB_PARAMETER_GPTMP_TODAY.JOB_NAME AND JOB_PARAMETER.PARAMETER_NAME=JOB_PARAMETER_GPTMP_TODAY.PARAMETER_NAME AND JOB_PARAMETER.PARAMETER_VALUE=JOB_PARAMETER_GPTMP_TODAY.PARAMETER_VALUE ;
insert into JOB_PARAMETER (JOB_NAME,PARAMETER_NAME,PARAMETER_VALUE,UPDATE_TIME,NOTES) select JOB_NAME,PARAMETER_NAME,PARAMETER_VALUE,UPDATE_TIME,NOTES from JOB_PARAMETER_GPTMP_TODAY  where CMD_TYPE='I';
\timing
