\echo -----------------------LSP_LIST------------------------
select now();
\timing
delete from LSP_LIST using LSP_LIST_GPTMP_TODAY where LSP_LIST.LSP_ID=LSP_LIST_GPTMP_TODAY.LSP_ID AND LSP_LIST.LSP_TYPE=LSP_LIST_GPTMP_TODAY.LSP_TYPE AND LSP_LIST.I_E_FLAG=LSP_LIST_GPTMP_TODAY.I_E_FLAG AND LSP_LIST.G_NO=LSP_LIST_GPTMP_TODAY.G_NO ;
insert into LSP_LIST (LSP_ID,LSP_TYPE,I_E_FLAG,G_NO,CODE_TS,G_NAME,G_MODEL,ORIGIN_COUNTRY,TRADE_TOTAL,TRADE_CURR,G_QTY,G_UNIT,QTY_1,UNIT_1,PACK_NO,PACK_TYPE,NOTE) select LSP_ID,LSP_TYPE,I_E_FLAG,G_NO,CODE_TS,G_NAME,G_MODEL,ORIGIN_COUNTRY,TRADE_TOTAL,TRADE_CURR,G_QTY,G_UNIT,QTY_1,UNIT_1,PACK_NO,PACK_TYPE,NOTE from LSP_LIST_GPTMP_TODAY  where CMD_TYPE='I';
\timing
