\echo -----------------------MANA_REL------------------------
select now();
\timing
delete from MANA_REL using MANA_REL_GPTMP_TODAY where MANA_REL.TRADE_CO=MANA_REL_GPTMP_TODAY.TRADE_CO AND MANA_REL.MANAG_NO=MANA_REL_GPTMP_TODAY.MANAG_NO ;
insert into MANA_REL (TRADE_CO,MANAG_NO,MANAG_NAME,MANAG_TITLE,MANAG_NAT,MANAG_ID,MANAG_BIR,MANAG_SEX,MANAG_ADDR,MANAG_TEL_BP,MANAG_NOTE,MANAG_DEGREE,MANAG_MAR) select TRADE_CO,MANAG_NO,MANAG_NAME,MANAG_TITLE,MANAG_NAT,MANAG_ID,MANAG_BIR,MANAG_SEX,MANAG_ADDR,MANAG_TEL_BP,MANAG_NOTE,MANAG_DEGREE,MANAG_MAR from MANA_REL_GPTMP_TODAY  where CMD_TYPE='I';
\timing
