\echo -----------------------MANIFEST_CHK------------------------
select now();
\timing
delete from MANIFEST_CHK using MANIFEST_CHK_GPTMP_TODAY where MANIFEST_CHK.BILL_NO=MANIFEST_CHK_GPTMP_TODAY.BILL_NO AND MANIFEST_CHK.SHIP_ID=MANIFEST_CHK_GPTMP_TODAY.SHIP_ID AND MANIFEST_CHK.VOYAGE_NO=MANIFEST_CHK_GPTMP_TODAY.VOYAGE_NO AND MANIFEST_CHK.CUSTOMS_CODE=MANIFEST_CHK_GPTMP_TODAY.CUSTOMS_CODE AND MANIFEST_CHK.TRAF_MODE=MANIFEST_CHK_GPTMP_TODAY.TRAF_MODE AND MANIFEST_CHK.I_E_FLAG=MANIFEST_CHK_GPTMP_TODAY.I_E_FLAG AND MANIFEST_CHK.FORM_ID=MANIFEST_CHK_GPTMP_TODAY.FORM_ID ;
insert into MANIFEST_CHK (I_E_FLAG,FORM_ID,SHIP_ID,VOYAGE_NO,BILL_NO,TRAF_MODE,CUSTOMS_CODE,SHIP_NAME_EN,FORM_FLAG,PACK_NO,GROSS_WT,CHK_MARK,CHK_ER,CHK_DATE,DELAY_DAYS,REL_ER,REL_DATE,COUNTRY_CODE,NOTES) select I_E_FLAG,FORM_ID,SHIP_ID,VOYAGE_NO,BILL_NO,TRAF_MODE,CUSTOMS_CODE,SHIP_NAME_EN,FORM_FLAG,PACK_NO,GROSS_WT,CHK_MARK,CHK_ER,CHK_DATE,DELAY_DAYS,REL_ER,REL_DATE,COUNTRY_CODE,NOTES from MANIFEST_CHK_GPTMP_TODAY  where CMD_TYPE='I';
\timing
