\echo -----------------------MANIFEST_HEAD_XMS_LOG------------------------
select now();
\timing
delete from MANIFEST_HEAD_XMS_LOG using MANIFEST_HEAD_XMS_LOG_GPTMP_TODAY where MANIFEST_HEAD_XMS_LOG.VOYAGE_NO=MANIFEST_HEAD_XMS_LOG_GPTMP_TODAY.VOYAGE_NO AND MANIFEST_HEAD_XMS_LOG.SHIP_ID=MANIFEST_HEAD_XMS_LOG_GPTMP_TODAY.SHIP_ID AND MANIFEST_HEAD_XMS_LOG.CUSTOMS_CODE=MANIFEST_HEAD_XMS_LOG_GPTMP_TODAY.CUSTOMS_CODE AND MANIFEST_HEAD_XMS_LOG.I_E_DATE=MANIFEST_HEAD_XMS_LOG_GPTMP_TODAY.I_E_DATE AND MANIFEST_HEAD_XMS_LOG.TRAF_MODE=MANIFEST_HEAD_XMS_LOG_GPTMP_TODAY.TRAF_MODE AND MANIFEST_HEAD_XMS_LOG.I_E_FLAG=MANIFEST_HEAD_XMS_LOG_GPTMP_TODAY.I_E_FLAG ;
insert into MANIFEST_HEAD_XMS_LOG (I_E_FLAG,CUSTOMS_CODE,TRAF_MODE,VOYAGE_NO,SHIP_ID,I_E_DATE,CREATE_DATE) select I_E_FLAG,CUSTOMS_CODE,TRAF_MODE,VOYAGE_NO,SHIP_ID,I_E_DATE,CREATE_DATE from MANIFEST_HEAD_XMS_LOG_GPTMP_TODAY  where CMD_TYPE='I';
\timing
