\echo -----------------------MANIFEST_LIST_CONTA------------------------
select now();
\timing
delete from MANIFEST_LIST_CONTA using MANIFEST_LIST_CONTA_GPTMP_TODAY where MANIFEST_LIST_CONTA.VOYAGE_NO=MANIFEST_LIST_CONTA_GPTMP_TODAY.VOYAGE_NO AND MANIFEST_LIST_CONTA.CUSTOMS_CODE=MANIFEST_LIST_CONTA_GPTMP_TODAY.CUSTOMS_CODE AND MANIFEST_LIST_CONTA.TRAF_MODE=MANIFEST_LIST_CONTA_GPTMP_TODAY.TRAF_MODE AND MANIFEST_LIST_CONTA.I_E_FLAG=MANIFEST_LIST_CONTA_GPTMP_TODAY.I_E_FLAG AND MANIFEST_LIST_CONTA.BILL_NO=MANIFEST_LIST_CONTA_GPTMP_TODAY.BILL_NO AND MANIFEST_LIST_CONTA.CONTA_ID=MANIFEST_LIST_CONTA_GPTMP_TODAY.CONTA_ID AND MANIFEST_LIST_CONTA.SHIP_ID=MANIFEST_LIST_CONTA_GPTMP_TODAY.SHIP_ID ;
insert into MANIFEST_LIST_CONTA (I_E_FLAG,CUSTOMS_CODE,TRAF_MODE,VOYAGE_NO,BILL_NO,CONTA_ID,SHIP_ID,RSK_ER,RSK_DATE,RSK_CODE,RSK_LEVEL,RSK_RESULT,RELEASE_ER,RELEASE_DATE) select I_E_FLAG,CUSTOMS_CODE,TRAF_MODE,VOYAGE_NO,BILL_NO,CONTA_ID,SHIP_ID,RSK_ER,RSK_DATE,RSK_CODE,RSK_LEVEL,RSK_RESULT,RELEASE_ER,RELEASE_DATE from MANIFEST_LIST_CONTA_GPTMP_TODAY  where CMD_TYPE='I';
\timing
