\echo -----------------------MANIFEST_CONTA------------------------
select now();
\timing
delete from MANIFEST_CONTA using MANIFEST_CONTA_GPTMP_TODAY where MANIFEST_CONTA.VOYAGE_NO=MANIFEST_CONTA_GPTMP_TODAY.VOYAGE_NO AND MANIFEST_CONTA.TRAF_MODE=MANIFEST_CONTA_GPTMP_TODAY.TRAF_MODE AND MANIFEST_CONTA.I_E_FLAG=MANIFEST_CONTA_GPTMP_TODAY.I_E_FLAG AND MANIFEST_CONTA.BILL_NO=MANIFEST_CONTA_GPTMP_TODAY.BILL_NO AND MANIFEST_CONTA.CONTA_ID=MANIFEST_CONTA_GPTMP_TODAY.CONTA_ID AND MANIFEST_CONTA.SHIP_ID=MANIFEST_CONTA_GPTMP_TODAY.SHIP_ID ;
insert into MANIFEST_CONTA (I_E_FLAG,TRAF_MODE,VOYAGE_NO,BILL_NO,CONTA_ID,SHIP_ID,CONTA_MODEL,SEAL_NO,CONTA_WT,CONTA_FLAG,PACK_NO,MAIN_G_NAME,NOTES,CUSTOMS_CODE) select I_E_FLAG,TRAF_MODE,VOYAGE_NO,BILL_NO,CONTA_ID,SHIP_ID,CONTA_MODEL,SEAL_NO,CONTA_WT,CONTA_FLAG,PACK_NO,MAIN_G_NAME,NOTES,CUSTOMS_CODE from MANIFEST_CONTA_GPTMP_TODAY  where CMD_TYPE='I';
\timing
