\echo -----------------------MNL_PARA------------------------
select now();
\timing
delete from MNL_PARA using MNL_PARA_GPTMP_TODAY where MNL_PARA.PARA_TYPE=MNL_PARA_GPTMP_TODAY.PARA_TYPE AND MNL_PARA.PARA_ID=MNL_PARA_GPTMP_TODAY.PARA_ID ;
insert into MNL_PARA (PARA_TYPE,PARA_ID,PARA_NAME,PARA_EXP,PARA_FLAG,PARA_VALUE,PARA_MARK) select PARA_TYPE,PARA_ID,PARA_NAME,PARA_EXP,PARA_FLAG,PARA_VALUE,PARA_MARK from MNL_PARA_GPTMP_TODAY  where CMD_TYPE='I';
\timing
