\echo -----------------------MNL_PRESS------------------------
select now();
\timing
delete from MNL_PRESS using MNL_PRESS_GPTMP_TODAY where MNL_PRESS.PARA_TYPE=MNL_PRESS_GPTMP_TODAY.PARA_TYPE AND MNL_PRESS.PARA_NAME=MNL_PRESS_GPTMP_TODAY.PARA_NAME ;
insert into MNL_PRESS (PARA_TYPE,PARA_ID,PARA_NAME,PARA_EXP,PARA_FLAG,PARA_VALUE,PARA_MARK) select PARA_TYPE,PARA_ID,PARA_NAME,PARA_EXP,PARA_FLAG,PARA_VALUE,PARA_MARK from MNL_PRESS_GPTMP_TODAY  where CMD_TYPE='I';
\timing
