\echo -----------------------MNL_RECEIVE_RECEIPT------------------------
select now();
\timing
delete from MNL_RECEIVE_RECEIPT using MNL_RECEIVE_RECEIPT_GPTMP_TODAY where MNL_RECEIVE_RECEIPT.MANUAL_NO=MNL_RECEIVE_RECEIPT_GPTMP_TODAY.MANUAL_NO AND MNL_RECEIVE_RECEIPT.SEND_CUSTOMS=MNL_RECEIVE_RECEIPT_GPTMP_TODAY.SEND_CUSTOMS AND MNL_RECEIVE_RECEIPT.CUSTOMS_CODE=MNL_RECEIVE_RECEIPT_GPTMP_TODAY.CUSTOMS_CODE AND MNL_RECEIVE_RECEIPT.H2000_RECEIVE_DATE=MNL_RECEIVE_RECEIPT_GPTMP_TODAY.H2000_RECEIVE_DATE ;
insert into MNL_RECEIVE_RECEIPT (MANUAL_NO,SEND_CUSTOMS,CUSTOMS_CODE,H2000_RECEIVE_DATE,RECEIVE_DATE,TYPE,SEND_TIMES,APPL_NO,FLAG,NOTE) select MANUAL_NO,SEND_CUSTOMS,CUSTOMS_CODE,H2000_RECEIVE_DATE,RECEIVE_DATE,TYPE,SEND_TIMES,APPL_NO,FLAG,NOTE from MNL_RECEIVE_RECEIPT_GPTMP_TODAY  where CMD_TYPE='I';
\timing
