\echo -----------------------MNLBAK_CONSUME------------------------
select now();
\timing
delete from MNLBAK_CONSUME using MNLBAK_CONSUME_GPTMP_TODAY where MNLBAK_CONSUME.MANUAL_NO=MNLBAK_CONSUME_GPTMP_TODAY.MANUAL_NO AND MNLBAK_CONSUME.CONTR_ITEM=MNLBAK_CONSUME_GPTMP_TODAY.CONTR_ITEM AND MNLBAK_CONSUME.EX_NO=MNLBAK_CONSUME_GPTMP_TODAY.EX_NO ;
insert into MNLBAK_CONSUME (MANUAL_NO,CONTR_ITEM,EX_NO,APPR_CONSUME,APPR_DAMAGE,DECL_CONSUME,DECL_DAMAGE) select MANUAL_NO,CONTR_ITEM,EX_NO,APPR_CONSUME,APPR_DAMAGE,DECL_CONSUME,DECL_DAMAGE from MNLBAK_CONSUME_GPTMP_TODAY  where CMD_TYPE='I';
\timing
