\echo -----------------------MNLBAK_CONTRACT_WORKFLOW------------------------
select now();
\timing
delete from MNLBAK_CONTRACT_WORKFLOW using MNLBAK_CONTRACT_WORKFLOW_GPTMP_TODAY where MNLBAK_CONTRACT_WORKFLOW.MANUAL_NO=MNLBAK_CONTRACT_WORKFLOW_GPTMP_TODAY.MANUAL_NO AND MNLBAK_CONTRACT_WORKFLOW.STEP_ID=MNLBAK_CONTRACT_WORKFLOW_GPTMP_TODAY.STEP_ID AND MNLBAK_CONTRACT_WORKFLOW.PROC_DATE=MNLBAK_CONTRACT_WORKFLOW_GPTMP_TODAY.PROC_DATE ;
insert into MNLBAK_CONTRACT_WORKFLOW (MANUAL_NO,STEP_ID,PROC_DATE,PROC_ER,PROC_ID,PROC_POS,STATUS_STATE) select MANUAL_NO,STEP_ID,PROC_DATE,PROC_ER,PROC_ID,PROC_POS,STATUS_STATE from MNLBAK_CONTRACT_WORKFLOW_GPTMP_TODAY  where CMD_TYPE='I';
\timing
