\echo -----------------------MNLBAK_EX_CONTRACT_CLEAR------------------------
select now();
\timing
delete from MNLBAK_EX_CONTRACT_CLEAR using MNLBAK_EX_CONTRACT_CLEAR_GPTMP_TODAY where MNLBAK_EX_CONTRACT_CLEAR.MANUAL_NO=MNLBAK_EX_CONTRACT_CLEAR_GPTMP_TODAY.MANUAL_NO AND MNLBAK_EX_CONTRACT_CLEAR.CONTR_ITEM=MNLBAK_EX_CONTRACT_CLEAR_GPTMP_TODAY.CONTR_ITEM ;
insert into MNLBAK_EX_CONTRACT_CLEAR (MANUAL_NO,CONTR_ITEM,APPR_AMT,FACT_AMT,APPR_QTY,FACT_QTY,PRODU_EX_AMT,PRODU_EX_QTY,PRODU_TAX_AMT,PRODU_TAX_QTY,REMAIN_AMT,REMAIN_QTY,ABANDON_AMT,ABANDON_QTY,ABANDON_DATE,ABANDON_ER,UNIT_1,CLEAR_ER,CLEAR_DATE,CLOSE_ER,CLOSE_DATE) select MANUAL_NO,CONTR_ITEM,APPR_AMT,FACT_AMT,APPR_QTY,FACT_QTY,PRODU_EX_AMT,PRODU_EX_QTY,PRODU_TAX_AMT,PRODU_TAX_QTY,REMAIN_AMT,REMAIN_QTY,ABANDON_AMT,ABANDON_QTY,ABANDON_DATE,ABANDON_ER,UNIT_1,CLEAR_ER,CLEAR_DATE,CLOSE_ER,CLOSE_DATE from MNLBAK_EX_CONTRACT_CLEAR_GPTMP_TODAY  where CMD_TYPE='I';
\timing
