\echo -----------------------MNLBAK_FEE_INVOICE------------------------
select now();
\timing
delete from MNLBAK_FEE_INVOICE using MNLBAK_FEE_INVOICE_GPTMP_TODAY where MNLBAK_FEE_INVOICE.MANUAL_NO=MNLBAK_FEE_INVOICE_GPTMP_TODAY.MANUAL_NO AND MNLBAK_FEE_INVOICE.F_NO=MNLBAK_FEE_INVOICE_GPTMP_TODAY.F_NO ;
insert into MNLBAK_FEE_INVOICE (MANUAL_NO,F_NO,FEE_ID,CREATE_DATE,CHK_ER,TYPE_ER,TYPE_DATE,FINANCIAL_FLAG,FINANCIAL_DATE,BOOK_NO,FEE_AMT,NOTE_S) select MANUAL_NO,F_NO,FEE_ID,CREATE_DATE,CHK_ER,TYPE_ER,TYPE_DATE,FINANCIAL_FLAG,FINANCIAL_DATE,BOOK_NO,FEE_AMT,NOTE_S from MNLBAK_FEE_INVOICE_GPTMP_TODAY  where CMD_TYPE='I';
\timing
