\echo -----------------------MNLBAK_SERVICE_LIST------------------------
select now();
\timing
delete from MNLBAK_SERVICE_LIST using MNLBAK_SERVICE_LIST_GPTMP_TODAY where MNLBAK_SERVICE_LIST.MANUAL_NO=MNLBAK_SERVICE_LIST_GPTMP_TODAY.MANUAL_NO AND MNLBAK_SERVICE_LIST.F_NO=MNLBAK_SERVICE_LIST_GPTMP_TODAY.F_NO ;
insert into MNLBAK_SERVICE_LIST (MANUAL_NO,F_NO,FEE_TYPE,FEE_RATE,G_NO,G_NAME,FEE_AMT,FEE_CURR,FEE_RMB,SERVICE_FEE) select MANUAL_NO,F_NO,FEE_TYPE,FEE_RATE,G_NO,G_NAME,FEE_AMT,FEE_CURR,FEE_RMB,SERVICE_FEE from MNLBAK_SERVICE_LIST_GPTMP_TODAY  where CMD_TYPE='I';
\timing
