\echo -----------------------MNLBAK_EX_FASCICLE_LIST------------------------
select now();
\timing
delete from MNLBAK_EX_FASCICLE_LIST using MNLBAK_EX_FASCICLE_LIST_GPTMP_TODAY where MNLBAK_EX_FASCICLE_LIST.FASCICLE_NO=MNLBAK_EX_FASCICLE_LIST_GPTMP_TODAY.FASCICLE_NO AND MNLBAK_EX_FASCICLE_LIST.CONTR_ITEM=MNLBAK_EX_FASCICLE_LIST_GPTMP_TODAY.CONTR_ITEM ;
insert into MNLBAK_EX_FASCICLE_LIST (MANUAL_NO,FASCICLE_NO,CONTR_ITEM,APPR_QTY,FACT_QTY) select MANUAL_NO,FASCICLE_NO,CONTR_ITEM,APPR_QTY,FACT_QTY from MNLBAK_EX_FASCICLE_LIST_GPTMP_TODAY  where CMD_TYPE='I';
\timing
