\echo -----------------------NORSK_COMPANY------------------------
select now();
\timing
delete from NORSK_COMPANY using NORSK_COMPANY_GPTMP_TODAY where NORSK_COMPANY.CCTS_CODE=NORSK_COMPANY_GPTMP_TODAY.CCTS_CODE ;
insert into NORSK_COMPANY (CCTS_CODE,TRADE_CO,TRADE_NAME,BEGIN_DATE,END_DATE,CUSTOMS_CODE,INPUT_ID,AUTHORIZE_ID,OP_TIME,I_E_FLAG) select CCTS_CODE,TRADE_CO,TRADE_NAME,BEGIN_DATE,END_DATE,CUSTOMS_CODE,INPUT_ID,AUTHORIZE_ID,OP_TIME,I_E_FLAG from NORSK_COMPANY_GPTMP_TODAY  where CMD_TYPE='I';
\timing
