\echo -----------------------NORSK_CONDITION------------------------
select now();
\timing
delete from NORSK_CONDITION using NORSK_CONDITION_GPTMP_TODAY where NORSK_CONDITION.CCTS_CODE=NORSK_CONDITION_GPTMP_TODAY.CCTS_CODE ;
insert into NORSK_CONDITION (CCTS_CODE,RSK_COND,RSK_COND_MID,RSK_COND_TXT,NOTE,BEGIN_DATE,END_DATE,CUSTOMS_CODE,INPUT_ID,AUTHORIZE_ID,OP_TIME) select CCTS_CODE,RSK_COND,RSK_COND_MID,RSK_COND_TXT,NOTE,BEGIN_DATE,END_DATE,CUSTOMS_CODE,INPUT_ID,AUTHORIZE_ID,OP_TIME from NORSK_CONDITION_GPTMP_TODAY  where CMD_TYPE='I';
\timing
