\echo -----------------------NORSK_CONDITION_BAK------------------------
select now();
\timing
delete from NORSK_CONDITION_BAK using NORSK_CONDITION_BAK_GPTMP_TODAY where NORSK_CONDITION_BAK.CCTS_CODE=NORSK_CONDITION_BAK_GPTMP_TODAY.CCTS_CODE AND NORSK_CONDITION_BAK.OP_BAK_TIME=NORSK_CONDITION_BAK_GPTMP_TODAY.OP_BAK_TIME ;
insert into NORSK_CONDITION_BAK (CCTS_CODE,RSK_COND,RSK_COND_MID,RSK_COND_TXT,NOTE,BEGIN_DATE,END_DATE,CUSTOMS_CODE,INPUT_ID,AUTHORIZE_ID,OP_TIME,OP_BAK_TYPE,OP_BAK_CUSTOMS,OP_BAK_MAN,OP_BAK_TIME) select CCTS_CODE,RSK_COND,RSK_COND_MID,RSK_COND_TXT,NOTE,BEGIN_DATE,END_DATE,CUSTOMS_CODE,INPUT_ID,AUTHORIZE_ID,OP_TIME,OP_BAK_TYPE,OP_BAK_CUSTOMS,OP_BAK_MAN,OP_BAK_TIME from NORSK_CONDITION_BAK_GPTMP_TODAY  where CMD_TYPE='I';
\timing
