\echo -----------------------OCC_EXAM------------------------
select now();
\timing
delete from OCC_EXAM using OCC_EXAM_GPTMP_TODAY where OCC_EXAM.CERTIFICATE_NO=OCC_EXAM_GPTMP_TODAY.CERTIFICATE_NO AND OCC_EXAM.AGREEMENT_ID=OCC_EXAM_GPTMP_TODAY.AGREEMENT_ID AND OCC_EXAM.ISSUE_PLACE=OCC_EXAM_GPTMP_TODAY.ISSUE_PLACE AND OCC_EXAM.G_NO=OCC_EXAM_GPTMP_TODAY.G_NO AND OCC_EXAM.ENTRY_G_NO=OCC_EXAM_GPTMP_TODAY.ENTRY_G_NO ;
insert into OCC_EXAM (CERTIFICATE_NO,AGREEMENT_ID,ISSUE_PLACE,ENTRY_ID,BASE_ID,G_NO,ENTRY_G_NO,FACT_AQTY,FACT_TOTAL,FACT_CURR,CHK_DATE,CHK_ER,VERIFY_DATE,VERIFY_ER,RETURN_DATE,REUSE1,REUSE2,HASH_SIGN) select CERTIFICATE_NO,AGREEMENT_ID,ISSUE_PLACE,ENTRY_ID,BASE_ID,G_NO,ENTRY_G_NO,FACT_AQTY,FACT_TOTAL,FACT_CURR,CHK_DATE,CHK_ER,VERIFY_DATE,VERIFY_ER,RETURN_DATE,REUSE1,REUSE2,HASH_SIGN from OCC_EXAM_GPTMP_TODAY  where CMD_TYPE='I';
\timing
