\echo -----------------------OCC_ELE_LIST------------------------
select now();
\timing
delete from OCC_ELE_LIST using OCC_ELE_LIST_GPTMP_TODAY where OCC_ELE_LIST.CERTIFICATE_NO=OCC_ELE_LIST_GPTMP_TODAY.CERTIFICATE_NO AND OCC_ELE_LIST.AGREEMENT_ID=OCC_ELE_LIST_GPTMP_TODAY.AGREEMENT_ID AND OCC_ELE_LIST.ISSUE_PLACE=OCC_ELE_LIST_GPTMP_TODAY.ISSUE_PLACE AND OCC_ELE_LIST.G_NO=OCC_ELE_LIST_GPTMP_TODAY.G_NO ;
insert into OCC_ELE_LIST (CERTIFICATE_NO,AGREEMENT_ID,ISSUE_PLACE,G_NO,CODE_TS,G_NAME_MODEL,PACK_NO,PACK_TYPE,G_QTY,G_UNIT,FOB_VALUE,FOB_CURRENCY,BRAND_NAME,REUSE1,REUSE2,HASH_SIGN) select CERTIFICATE_NO,AGREEMENT_ID,ISSUE_PLACE,G_NO,CODE_TS,G_NAME_MODEL,PACK_NO,PACK_TYPE,G_QTY,G_UNIT,FOB_VALUE,FOB_CURRENCY,BRAND_NAME,REUSE1,REUSE2,HASH_SIGN from OCC_ELE_LIST_GPTMP_TODAY  where CMD_TYPE='I';
\timing
