\echo -----------------------PAPERLESS_SELFSAVE_CERT------------------------
select now();
\timing
delete from PAPERLESS_SELFSAVE_CERT using PAPERLESS_SELFSAVE_CERT_GPTMP_TODAY where PAPERLESS_SELFSAVE_CERT.ENTRY_ID=PAPERLESS_SELFSAVE_CERT_GPTMP_TODAY.ENTRY_ID ;
insert into PAPERLESS_SELFSAVE_CERT (ENTRY_ID,I_E_FLAG,DECL_PORT,REL_TIME,AGENT_CODE,TRADE_CO,TRADE_NAME,AGENT_NAME,PRINT_TIME,PROC_MARK,D_DATE) select ENTRY_ID,I_E_FLAG,DECL_PORT,REL_TIME,AGENT_CODE,TRADE_CO,TRADE_NAME,AGENT_NAME,PRINT_TIME,PROC_MARK,D_DATE from PAPERLESS_SELFSAVE_CERT_GPTMP_TODAY  where CMD_TYPE='I';
\timing
