\echo -----------------------PAYOUT_REMIT_HEAD------------------------
select now();
\timing
delete from PAYOUT_REMIT_HEAD using PAYOUT_REMIT_HEAD_GPTMP_TODAY where PAYOUT_REMIT_HEAD.RPTNO=PAYOUT_REMIT_HEAD_GPTMP_TODAY.RPTNO ;
insert into PAYOUT_REMIT_HEAD (RPTNO,RPTUSER,TRADE_CO,RCVNAME,ACTUCCY,ACTUAMT,CSTSETCODE,COUNTRYCODE,CSTCNTRCTNO,INVOICENO,LCBGNO,CUS_TRADE_CO,RECV_DATE) select RPTNO,RPTUSER,TRADE_CO,RCVNAME,ACTUCCY,ACTUAMT,CSTSETCODE,COUNTRYCODE,CSTCNTRCTNO,INVOICENO,LCBGNO,CUS_TRADE_CO,RECV_DATE from PAYOUT_REMIT_HEAD_GPTMP_TODAY  where CMD_TYPE='I';
\timing
