\echo -----------------------PAYOUT_REMIT_LIST------------------------
select now();
\timing
delete from PAYOUT_REMIT_LIST using PAYOUT_REMIT_LIST_GPTMP_TODAY where PAYOUT_REMIT_LIST.RPTNO=PAYOUT_REMIT_LIST_GPTMP_TODAY.RPTNO AND PAYOUT_REMIT_LIST.ENTRY_ID=PAYOUT_REMIT_LIST_GPTMP_TODAY.ENTRY_ID ;
insert into PAYOUT_REMIT_LIST (RPTNO,ENTRY_ID,CUSTOMCCY,CUSTOMAMT,WRITEOFFAMT,RECV_DATE) select RPTNO,ENTRY_ID,CUSTOMCCY,CUSTOMAMT,WRITEOFFAMT,RECV_DATE from PAYOUT_REMIT_LIST_GPTMP_TODAY  where CMD_TYPE='I';
\timing
