\echo -----------------------PES_NOTE------------------------
select now();
\timing
delete from PES_NOTE using PES_NOTE_GPTMP_TODAY where PES_NOTE.NOTE_NO=PES_NOTE_GPTMP_TODAY.NOTE_NO ;
insert into PES_NOTE (NOTE_NO,NOTE_TYPE,I_E_FLAG,ID_STAT,APPR_DATE,BEGIN_DATE,END_DATE,TRADE_CODE,TRADE_NAME,CODE_TS,G_NAME,G_USE,QTY,UNIT,DISTRICT_CODE,TRADE_MODE,I_E_PORT,STAT,VERIFY_DATE,VERIFY_ER,CLEAR_DATE,CLEAR_ER) select NOTE_NO,NOTE_TYPE,I_E_FLAG,ID_STAT,APPR_DATE,BEGIN_DATE,END_DATE,TRADE_CODE,TRADE_NAME,CODE_TS,G_NAME,G_USE,QTY,UNIT,DISTRICT_CODE,TRADE_MODE,I_E_PORT,STAT,VERIFY_DATE,VERIFY_ER,CLEAR_DATE,CLEAR_ER from PES_NOTE_GPTMP_TODAY  where CMD_TYPE='I';
\timing
