\echo -----------------------PES_WORKFLOW------------------------
select now();
\timing
delete from PES_WORKFLOW using PES_WORKFLOW_GPTMP_TODAY where PES_WORKFLOW.NOTE_NO=PES_WORKFLOW_GPTMP_TODAY.NOTE_NO AND PES_WORKFLOW.NOTE_TYPE=PES_WORKFLOW_GPTMP_TODAY.NOTE_TYPE AND PES_WORKFLOW.PROCESS_DATE=PES_WORKFLOW_GPTMP_TODAY.PROCESS_DATE AND PES_WORKFLOW.STEP_ID=PES_WORKFLOW_GPTMP_TODAY.STEP_ID ;
insert into PES_WORKFLOW (NOTE_NO,NOTE_TYPE,PROCESS_DATE,STEP_ID,PROCESS_STATUS,STAT,ENTRY_ID,NOTE,PROCESS_ER) select NOTE_NO,NOTE_TYPE,PROCESS_DATE,STEP_ID,PROCESS_STATUS,STAT,ENTRY_ID,NOTE,PROCESS_ER from PES_WORKFLOW_GPTMP_TODAY  where CMD_TYPE='I';
\timing
