\echo -----------------------PORT_BIND_REL------------------------
select now();
\timing
delete from PORT_BIND_REL using PORT_BIND_REL_GPTMP_TODAY where PORT_BIND_REL.BIND_NO=PORT_BIND_REL_GPTMP_TODAY.BIND_NO AND PORT_BIND_REL.PRE_NO=PORT_BIND_REL_GPTMP_TODAY.PRE_NO ;
insert into PORT_BIND_REL (BIND_NO,PRE_NO,REC_MARK,SPARE_FIELD) select BIND_NO,PRE_NO,REC_MARK,SPARE_FIELD from PORT_BIND_REL_GPTMP_TODAY  where CMD_TYPE='I';
\timing
