\echo -----------------------PRE_DECL_REL------------------------
select now();
\timing
delete from PRE_DECL_REL using PRE_DECL_REL_GPTMP_TODAY where PRE_DECL_REL.DECL_TRAIN_CO=PRE_DECL_REL_GPTMP_TODAY.DECL_TRAIN_CO ;
insert into PRE_DECL_REL (TRADE_CO,DECL_TRAIN_CO,DECL_ZG_CODE,DECL_NAME,DECL_SEX,DECL_DEGREE,DECL_ID_CODE,DECL_TEL_BP_CODE,DECL_APPL_TIME,DECL_TEST_SCORE,DECL_APPL_FLAG,DECL_INP_DATE,DECL_NOTE) select TRADE_CO,DECL_TRAIN_CO,DECL_ZG_CODE,DECL_NAME,DECL_SEX,DECL_DEGREE,DECL_ID_CODE,DECL_TEL_BP_CODE,DECL_APPL_TIME,DECL_TEST_SCORE,DECL_APPL_FLAG,DECL_INP_DATE,DECL_NOTE from PRE_DECL_REL_GPTMP_TODAY  where CMD_TYPE='I';
\timing
