\echo -----------------------PRE_CONSUME------------------------
select now();
\timing
delete from PRE_CONSUME using PRE_CONSUME_GPTMP_TODAY where PRE_CONSUME.MANUAL_NO=PRE_CONSUME_GPTMP_TODAY.MANUAL_NO AND PRE_CONSUME.CONTR_ITEM=PRE_CONSUME_GPTMP_TODAY.CONTR_ITEM AND PRE_CONSUME.EX_NO=PRE_CONSUME_GPTMP_TODAY.EX_NO ;
insert into PRE_CONSUME (MANUAL_NO,CONTR_ITEM,EX_NO,APPR_CONSUME,APPR_DAMAGE,DECL_CONSUME,DECL_DAMAGE) select MANUAL_NO,CONTR_ITEM,EX_NO,APPR_CONSUME,APPR_DAMAGE,DECL_CONSUME,DECL_DAMAGE from PRE_CONSUME_GPTMP_TODAY  where CMD_TYPE='I';
\timing
