\echo -----------------------PRE_APPL_CLOSE_CONSUME------------------------
select now();
\timing
delete from PRE_APPL_CLOSE_CONSUME using PRE_APPL_CLOSE_CONSUME_GPTMP_TODAY where PRE_APPL_CLOSE_CONSUME.MANUAL_NO=PRE_APPL_CLOSE_CONSUME_GPTMP_TODAY.MANUAL_NO AND PRE_APPL_CLOSE_CONSUME.CONTR_ITEM=PRE_APPL_CLOSE_CONSUME_GPTMP_TODAY.CONTR_ITEM AND PRE_APPL_CLOSE_CONSUME.EX_NO=PRE_APPL_CLOSE_CONSUME_GPTMP_TODAY.EX_NO ;
insert into PRE_APPL_CLOSE_CONSUME (MANUAL_NO,CONTR_ITEM,CODE_TS,G_NAME,G_MODEL,EX_NO,DECL_CONSUME,DECL_DAMAGE) select MANUAL_NO,CONTR_ITEM,CODE_TS,G_NAME,G_MODEL,EX_NO,DECL_CONSUME,DECL_DAMAGE from PRE_APPL_CLOSE_CONSUME_GPTMP_TODAY  where CMD_TYPE='I';
\timing
