\echo -----------------------PRE_EX_APPL_CLOSE------------------------
select now();
\timing
delete from PRE_EX_APPL_CLOSE using PRE_EX_APPL_CLOSE_GPTMP_TODAY where PRE_EX_APPL_CLOSE.MANUAL_NO=PRE_EX_APPL_CLOSE_GPTMP_TODAY.MANUAL_NO AND PRE_EX_APPL_CLOSE.CONTR_ITEM=PRE_EX_APPL_CLOSE_GPTMP_TODAY.CONTR_ITEM ;
insert into PRE_EX_APPL_CLOSE (MANUAL_NO,CONTR_ITEM,CODE_TS,G_NAME,G_MODEL,FACT_QTY,T_IN_QTY,T_EX_QTY,REMAIN_QTY,PROC_MODE,CORR_MANUAL_NO) select MANUAL_NO,CONTR_ITEM,CODE_TS,G_NAME,G_MODEL,FACT_QTY,T_IN_QTY,T_EX_QTY,REMAIN_QTY,PROC_MODE,CORR_MANUAL_NO from PRE_EX_APPL_CLOSE_GPTMP_TODAY  where CMD_TYPE='I';
\timing
