\echo -----------------------PRESS_CLEAR------------------------
select now();
\timing
delete from PRESS_CLEAR using PRESS_CLEAR_GPTMP_TODAY where PRESS_CLEAR.MANUAL_NO=PRESS_CLEAR_GPTMP_TODAY.MANUAL_NO AND PRESS_CLEAR.PR_NO=PRESS_CLEAR_GPTMP_TODAY.PR_NO ;
insert into PRESS_CLEAR (MANUAL_NO,PR_NO,PR_COUNT,PR_CUSTOMS,PR_DEPARTMENT,PR_DATE) select MANUAL_NO,PR_NO,PR_COUNT,PR_CUSTOMS,PR_DEPARTMENT,PR_DATE from PRESS_CLEAR_GPTMP_TODAY  where CMD_TYPE='I';
\timing
