\echo -----------------------PROJECT_LIST------------------------
select now();
\timing
delete from PROJECT_LIST using PROJECT_LIST_GPTMP_TODAY where PROJECT_LIST.PROJECT_ID=PROJECT_LIST_GPTMP_TODAY.PROJECT_ID AND PROJECT_LIST.MODIFY_TIMES=PROJECT_LIST_GPTMP_TODAY.MODIFY_TIMES AND PROJECT_LIST.G_NO=PROJECT_LIST_GPTMP_TODAY.G_NO ;
insert into PROJECT_LIST (PROJECT_ID,MODIFY_TIMES,G_NO,CODE_TS,CLASS_MARK,G_NAME,G_MODEL,ORIGIN_COUNTRY,G_UNIT,G_QTY,UNIT_1,QTY_1,UNIT_2,QTY_2,DECL_TOTAL,TRADE_CURR,USED_QTY,USED_AMT,FACT_QTY,FACT_AMT,DUTY_MODE,D_RATE,T_RATE,O_RATE,DUTY_RATE,TAX_RATE,OTHER_RATE,CHECK_MARK,RESERVE1,NOTE) select PROJECT_ID,MODIFY_TIMES,G_NO,CODE_TS,CLASS_MARK,G_NAME,G_MODEL,ORIGIN_COUNTRY,G_UNIT,G_QTY,UNIT_1,QTY_1,UNIT_2,QTY_2,DECL_TOTAL,TRADE_CURR,USED_QTY,USED_AMT,FACT_QTY,FACT_AMT,DUTY_MODE,D_RATE,T_RATE,O_RATE,DUTY_RATE,TAX_RATE,OTHER_RATE,CHECK_MARK,RESERVE1,NOTE from PROJECT_LIST_GPTMP_TODAY  where CMD_TYPE='I';
\timing
