\echo -----------------------PROJECT_MAX_NO------------------------
select now();
\timing
delete from PROJECT_MAX_NO using PROJECT_MAX_NO_GPTMP_TODAY where PROJECT_MAX_NO.MASTER_CUSTOMS=PROJECT_MAX_NO_GPTMP_TODAY.MASTER_CUSTOMS AND PROJECT_MAX_NO.YEAR_2=PROJECT_MAX_NO_GPTMP_TODAY.YEAR_2 AND PROJECT_MAX_NO.CUT_MODE=PROJECT_MAX_NO_GPTMP_TODAY.CUT_MODE ;
insert into PROJECT_MAX_NO (MASTER_CUSTOMS,YEAR_2,CUT_MODE,MAX_NO) select MASTER_CUSTOMS,YEAR_2,CUT_MODE,MAX_NO from PROJECT_MAX_NO_GPTMP_TODAY  where CMD_TYPE='I';
\timing
