\echo -----------------------PROJECT_MAX_NO_2007------------------------
select now();
\timing
delete from PROJECT_MAX_NO_2007 using PROJECT_MAX_NO_2007_GPTMP_TODAY where PROJECT_MAX_NO_2007.MASTER_CUSTOMS=PROJECT_MAX_NO_2007_GPTMP_TODAY.MASTER_CUSTOMS AND PROJECT_MAX_NO_2007.YEAR_4=PROJECT_MAX_NO_2007_GPTMP_TODAY.YEAR_4 AND PROJECT_MAX_NO_2007.CUT_MODE=PROJECT_MAX_NO_2007_GPTMP_TODAY.CUT_MODE ;
insert into PROJECT_MAX_NO_2007 (MASTER_CUSTOMS,YEAR_4,CUT_MODE,MAX_NO) select MASTER_CUSTOMS,YEAR_4,CUT_MODE,MAX_NO from PROJECT_MAX_NO_2007_GPTMP_TODAY  where CMD_TYPE='I';
\timing
