\echo -----------------------RAM_PRINT_LOG------------------------
select now();
\timing
delete from RAM_PRINT_LOG using RAM_PRINT_LOG_GPTMP_TODAY where RAM_PRINT_LOG.RAM_ID=RAM_PRINT_LOG_GPTMP_TODAY.RAM_ID AND RAM_PRINT_LOG.PRINT_DATE=RAM_PRINT_LOG_GPTMP_TODAY.PRINT_DATE ;
insert into RAM_PRINT_LOG (RAM_ID,PRINT_DATE,PRINT_ER) select RAM_ID,PRINT_DATE,PRINT_ER from RAM_PRINT_LOG_GPTMP_TODAY  where CMD_TYPE='I';
\timing
