\echo -----------------------RAM_RG_COPINFO------------------------
select now();
\timing
delete from RAM_RG_COPINFO using RAM_RG_COPINFO_GPTMP_TODAY where RAM_RG_COPINFO.RAM_ID=RAM_RG_COPINFO_GPTMP_TODAY.RAM_ID AND RAM_RG_COPINFO.TYPE=RAM_RG_COPINFO_GPTMP_TODAY.TYPE AND RAM_RG_COPINFO.COP_NO=RAM_RG_COPINFO_GPTMP_TODAY.COP_NO ;
insert into RAM_RG_COPINFO (RAM_ID,TYPE,COP_NO,COP_CODE,COP_NAME,COP_TYPE,MASTER_CUSTOMS,CHANGE_NOTE,NOTE,LINKMAN,YD_CHK_DATE,YD_CHK_ER,YD_CHK_MARK,YD_CHK_NOTE,YD_LINK_NO) select RAM_ID,TYPE,COP_NO,COP_CODE,COP_NAME,COP_TYPE,MASTER_CUSTOMS,CHANGE_NOTE,NOTE,LINKMAN,YD_CHK_DATE,YD_CHK_ER,YD_CHK_MARK,YD_CHK_NOTE,YD_LINK_NO from RAM_RG_COPINFO_GPTMP_TODAY  where CMD_TYPE='I';
\timing
