\echo -----------------------RAM_RG_COP_OWNER------------------------
select now();
\timing
delete from RAM_RG_COP_OWNER using RAM_RG_COP_OWNER_GPTMP_TODAY where RAM_RG_COP_OWNER.RAM_ID=RAM_RG_COP_OWNER_GPTMP_TODAY.RAM_ID AND RAM_RG_COP_OWNER.TYPE=RAM_RG_COP_OWNER_GPTMP_TODAY.TYPE AND RAM_RG_COP_OWNER.COP_NO=RAM_RG_COP_OWNER_GPTMP_TODAY.COP_NO AND RAM_RG_COP_OWNER.OWNER_NO=RAM_RG_COP_OWNER_GPTMP_TODAY.OWNER_NO ;
insert into RAM_RG_COP_OWNER (RAM_ID,TYPE,COP_NO,OWNER_NO,OWNER_NAME,COUNTRY,INVEST_RATE) select RAM_ID,TYPE,COP_NO,OWNER_NO,OWNER_NAME,COUNTRY,INVEST_RATE from RAM_RG_COP_OWNER_GPTMP_TODAY  where CMD_TYPE='I';
\timing
