\echo -----------------------RAM_RG_COP_PROJECT------------------------
select now();
\timing
delete from RAM_RG_COP_PROJECT using RAM_RG_COP_PROJECT_GPTMP_TODAY where RAM_RG_COP_PROJECT.RAM_ID=RAM_RG_COP_PROJECT_GPTMP_TODAY.RAM_ID AND RAM_RG_COP_PROJECT.TYPE=RAM_RG_COP_PROJECT_GPTMP_TODAY.TYPE AND RAM_RG_COP_PROJECT.COP_NO=RAM_RG_COP_PROJECT_GPTMP_TODAY.COP_NO AND RAM_RG_COP_PROJECT.PROJECT_NO=RAM_RG_COP_PROJECT_GPTMP_TODAY.PROJECT_NO ;
insert into RAM_RG_COP_PROJECT (RAM_ID,TYPE,COP_NO,PROJECT_NO,PROJECT_ID,PROJECT_NAME,PROJECT_FUND,PROJECT_TYPE,INVEST_AMT,INVEST_CURR,QUOTA_AMT,QUOTA_FREE) select RAM_ID,TYPE,COP_NO,PROJECT_NO,PROJECT_ID,PROJECT_NAME,PROJECT_FUND,PROJECT_TYPE,INVEST_AMT,INVEST_CURR,QUOTA_AMT,QUOTA_FREE from RAM_RG_COP_PROJECT_GPTMP_TODAY  where CMD_TYPE='I';
\timing
