\echo -----------------------RCP_PAYMENT_HEAD_BAK------------------------
select now();
\timing
delete from RCP_PAYMENT_HEAD_BAK using RCP_PAYMENT_HEAD_BAK_GPTMP_TODAY where RCP_PAYMENT_HEAD_BAK.LEVYNO=RCP_PAYMENT_HEAD_BAK_GPTMP_TODAY.LEVYNO ;
insert into RCP_PAYMENT_HEAD_BAK (LEVYNO,BANKORGCODE,PAYERNAME,PAYERORGCODE,PAYERCGACCODE,PAYERACCT,PAYEENAME,PAYEECOUNTRYCODE,SWIFTBIC,PAYERDATE,PAYERCNY,PAYERAMT,CUSTOMSAMT,PREPAYERAMT,REFUNDMENTAMT,BALANCEMODE,ACCOUNTPERIOD,BANKTRANO,ADDWORD) select LEVYNO,BANKORGCODE,PAYERNAME,PAYERORGCODE,PAYERCGACCODE,PAYERACCT,PAYEENAME,PAYEECOUNTRYCODE,SWIFTBIC,PAYERDATE,PAYERCNY,PAYERAMT,CUSTOMSAMT,PREPAYERAMT,REFUNDMENTAMT,BALANCEMODE,ACCOUNTPERIOD,BANKTRANO,ADDWORD from RCP_PAYMENT_HEAD_BAK_GPTMP_TODAY  where CMD_TYPE='I';
\timing
