\echo -----------------------RCP_RECORD_LIST_BAK------------------------
select now();
\timing
delete from RCP_RECORD_LIST_BAK using RCP_RECORD_LIST_BAK_GPTMP_TODAY where RCP_RECORD_LIST_BAK.LEVYNO=RCP_RECORD_LIST_BAK_GPTMP_TODAY.LEVYNO AND RCP_RECORD_LIST_BAK.LISTNO=RCP_RECORD_LIST_BAK_GPTMP_TODAY.LISTNO ;
insert into RCP_RECORD_LIST_BAK (LEVYNO,LISTNO,COUNTRYAREA,BANKNAMEOUT,BANKACCTOUT,BANKAMTOUT,RECDATEOUT,REMARK) select LEVYNO,LISTNO,COUNTRYAREA,BANKNAMEOUT,BANKACCTOUT,BANKAMTOUT,RECDATEOUT,REMARK from RCP_RECORD_LIST_BAK_GPTMP_TODAY  where CMD_TYPE='I';
\timing
