\echo -----------------------RCP_INCOME_LIST_BAK------------------------
select now();
\timing
delete from RCP_INCOME_LIST_BAK using RCP_INCOME_LIST_BAK_GPTMP_TODAY where RCP_INCOME_LIST_BAK.LEVYNO=RCP_INCOME_LIST_BAK_GPTMP_TODAY.LEVYNO AND RCP_INCOME_LIST_BAK.LISTNO=RCP_INCOME_LIST_BAK_GPTMP_TODAY.LISTNO ;
insert into RCP_INCOME_LIST_BAK (LEVYNO,LISTNO,CUSTOMSDATE) select LEVYNO,LISTNO,CUSTOMSDATE from RCP_INCOME_LIST_BAK_GPTMP_TODAY  where CMD_TYPE='I';
\timing
