\echo -----------------------RCP_RECORD_LIST------------------------
select now();
\timing
delete from RCP_RECORD_LIST using RCP_RECORD_LIST_GPTMP_TODAY where RCP_RECORD_LIST.LEVYNO=RCP_RECORD_LIST_GPTMP_TODAY.LEVYNO AND RCP_RECORD_LIST.LISTNO=RCP_RECORD_LIST_GPTMP_TODAY.LISTNO ;
insert into RCP_RECORD_LIST (LEVYNO,LISTNO,COUNTRYAREA,BANKNAMEOUT,BANKACCTOUT,BANKAMTOUT,RECDATEOUT,REMARK) select LEVYNO,LISTNO,COUNTRYAREA,BANKNAMEOUT,BANKACCTOUT,BANKAMTOUT,RECDATEOUT,REMARK from RCP_RECORD_LIST_GPTMP_TODAY  where CMD_TYPE='I';
\timing
