\echo -----------------------RCP_PAYMENT_LIST_BAK------------------------
select now();
\timing
delete from RCP_PAYMENT_LIST_BAK using RCP_PAYMENT_LIST_BAK_GPTMP_TODAY where RCP_PAYMENT_LIST_BAK.LEVYNO=RCP_PAYMENT_LIST_BAK_GPTMP_TODAY.LEVYNO AND RCP_PAYMENT_LIST_BAK.LISTNO=RCP_PAYMENT_LIST_BAK_GPTMP_TODAY.LISTNO ;
insert into RCP_PAYMENT_LIST_BAK (LEVYNO,LISTNO,CUSTOMSDATE) select LEVYNO,LISTNO,CUSTOMSDATE from RCP_PAYMENT_LIST_BAK_GPTMP_TODAY  where CMD_TYPE='I';
\timing
