\echo -----------------------RCP_PAYMENT_HEAD------------------------
select now();
\timing
delete from RCP_PAYMENT_HEAD using RCP_PAYMENT_HEAD_GPTMP_TODAY where RCP_PAYMENT_HEAD.LEVYNO=RCP_PAYMENT_HEAD_GPTMP_TODAY.LEVYNO ;
insert into RCP_PAYMENT_HEAD (LEVYNO,BANKORGCODE,PAYERNAME,PAYERORGCODE,PAYERCGACCODE,PAYERACCT,PAYEENAME,PAYEECOUNTRYCODE,SWIFTBIC,PAYERDATE,PAYERCNY,PAYERAMT,CUSTOMSAMT,PREPAYERAMT,REFUNDMENTAMT,BALANCEMODE,ACCOUNTPERIOD,BANKTRANO,ADDWORD) select LEVYNO,BANKORGCODE,PAYERNAME,PAYERORGCODE,PAYERCGACCODE,PAYERACCT,PAYEENAME,PAYEECOUNTRYCODE,SWIFTBIC,PAYERDATE,PAYERCNY,PAYERAMT,CUSTOMSAMT,PREPAYERAMT,REFUNDMENTAMT,BALANCEMODE,ACCOUNTPERIOD,BANKTRANO,ADDWORD from RCP_PAYMENT_HEAD_GPTMP_TODAY  where CMD_TYPE='I';
\timing
