\echo -----------------------RCP_INCOME_HEAD------------------------
select now();
\timing
delete from RCP_INCOME_HEAD using RCP_INCOME_HEAD_GPTMP_TODAY where RCP_INCOME_HEAD.LEVYNO=RCP_INCOME_HEAD_GPTMP_TODAY.LEVYNO ;
insert into RCP_INCOME_HEAD (LEVYNO,BANKORGCODE,PAYEENAME,PAYEEORGCODE,PAYEECGACCODE,PAYEEACCT,PAYERNAME,PAYERCOUNTRYCODE,SWIFTBIC,PAYEEDATE,PAYEECNY,PAYEEAMT,CUSTOMSAMT,PREPAYEEAMT,REFUNDMENTAMT,BALANCEMODE,ACCOUNTPERIOD,BANKTRANO,ADDWORD) select LEVYNO,BANKORGCODE,PAYEENAME,PAYEEORGCODE,PAYEECGACCODE,PAYEEACCT,PAYERNAME,PAYERCOUNTRYCODE,SWIFTBIC,PAYEEDATE,PAYEECNY,PAYEEAMT,CUSTOMSAMT,PREPAYEEAMT,REFUNDMENTAMT,BALANCEMODE,ACCOUNTPERIOD,BANKTRANO,ADDWORD from RCP_INCOME_HEAD_GPTMP_TODAY  where CMD_TYPE='I';
\timing
