\echo -----------------------RCP_RECORD_HEAD------------------------
select now();
\timing
delete from RCP_RECORD_HEAD using RCP_RECORD_HEAD_GPTMP_TODAY where RCP_RECORD_HEAD.LEVYNO=RCP_RECORD_HEAD_GPTMP_TODAY.LEVYNO ;
insert into RCP_RECORD_HEAD (LEVYNO,ORGCODE,CGACCODE,ORGNAME,ENTRYID,TRADEDATE,TOTALAMT,BALANCEMODE,PACTNO,PRERECDATE,PRERECAMT) select LEVYNO,ORGCODE,CGACCODE,ORGNAME,ENTRYID,TRADEDATE,TOTALAMT,BALANCEMODE,PACTNO,PRERECDATE,PRERECAMT from RCP_RECORD_HEAD_GPTMP_TODAY  where CMD_TYPE='I';
\timing
