\echo -----------------------RED_MAX_NO_2007------------------------
select now();
\timing
delete from RED_MAX_NO_2007 using RED_MAX_NO_2007_GPTMP_TODAY where RED_MAX_NO_2007.MASTER_CUSTOMS=RED_MAX_NO_2007_GPTMP_TODAY.MASTER_CUSTOMS AND RED_MAX_NO_2007.YEAR_2=RED_MAX_NO_2007_GPTMP_TODAY.YEAR_2 ;
insert into RED_MAX_NO_2007 (MASTER_CUSTOMS,YEAR_2,MAX_NO) select MASTER_CUSTOMS,YEAR_2,MAX_NO from RED_MAX_NO_2007_GPTMP_TODAY  where CMD_TYPE='I';
\timing
