\echo -----------------------RED_RECEIVE_RECEIPT------------------------
select now();
\timing
delete from RED_RECEIVE_RECEIPT using RED_RECEIVE_RECEIPT_GPTMP_TODAY where RED_RECEIVE_RECEIPT.CUT_ID=RED_RECEIVE_RECEIPT_GPTMP_TODAY.CUT_ID AND RED_RECEIVE_RECEIPT.SEND_TIMES=RED_RECEIVE_RECEIPT_GPTMP_TODAY.SEND_TIMES ;
insert into RED_RECEIVE_RECEIPT (CUT_ID,SEND_TIMES,SEND_CUSTOMS,REC_CUSTOMS_CODE,RECEIVE_DATE,TYPE,LINE,VERSION,FLAG,NOTE) select CUT_ID,SEND_TIMES,SEND_CUSTOMS,REC_CUSTOMS_CODE,RECEIVE_DATE,TYPE,LINE,VERSION,FLAG,NOTE from RED_RECEIVE_RECEIPT_GPTMP_TODAY  where CMD_TYPE='I';
\timing
