\echo -----------------------RED_MAX_NO------------------------
select now();
\timing
delete from RED_MAX_NO using RED_MAX_NO_GPTMP_TODAY where RED_MAX_NO.MASTER_CUSTOMS=RED_MAX_NO_GPTMP_TODAY.MASTER_CUSTOMS AND RED_MAX_NO.YEAR_1=RED_MAX_NO_GPTMP_TODAY.YEAR_1 AND RED_MAX_NO.CLASS=RED_MAX_NO_GPTMP_TODAY.CLASS ;
insert into RED_MAX_NO (MASTER_CUSTOMS,YEAR_1,CLASS,MAX_NO) select MASTER_CUSTOMS,YEAR_1,CLASS,MAX_NO from RED_MAX_NO_GPTMP_TODAY  where CMD_TYPE='I';
\timing
