\echo -----------------------RED_SERVICE_FEE------------------------
select now();
\timing
delete from RED_SERVICE_FEE using RED_SERVICE_FEE_GPTMP_TODAY where RED_SERVICE_FEE.MANUAL_NO=RED_SERVICE_FEE_GPTMP_TODAY.MANUAL_NO ;
insert into RED_SERVICE_FEE (MANUAL_NO,DUE_FEE_AMT,PAY_FEE_AMT,CREATE_DATE,RETURN_ID,RETURN_FLAG,REMAIN_AMT) select MANUAL_NO,DUE_FEE_AMT,PAY_FEE_AMT,CREATE_DATE,RETURN_ID,RETURN_FLAG,REMAIN_AMT from RED_SERVICE_FEE_GPTMP_TODAY  where CMD_TYPE='I';
\timing
