\echo -----------------------RETURN_REL------------------------
select now();
\timing
delete from RETURN_REL using RETURN_REL_GPTMP_TODAY where RETURN_REL.RET_TRANS_NO=RETURN_REL_GPTMP_TODAY.RET_TRANS_NO AND RETURN_REL.RET_TYPE=RETURN_REL_GPTMP_TODAY.RET_TYPE AND RETURN_REL.RET_TIME=RETURN_REL_GPTMP_TODAY.RET_TIME ;
insert into RETURN_REL (RET_TRANS_NO,RET_TYPE,RET_TIME,RET_CODE,RET_MESS) select RET_TRANS_NO,RET_TYPE,RET_TIME,RET_CODE,RET_MESS from RETURN_REL_GPTMP_TODAY  where CMD_TYPE='I';
\timing
