\echo -----------------------RSK_REPLICATION_LOG------------------------
select now();
\timing
delete from RSK_REPLICATION_LOG using RSK_REPLICATION_LOG_GPTMP_TODAY where RSK_REPLICATION_LOG.CUSTOMS_CODE=RSK_REPLICATION_LOG_GPTMP_TODAY.CUSTOMS_CODE AND RSK_REPLICATION_LOG.TABLE_NAME=RSK_REPLICATION_LOG_GPTMP_TODAY.TABLE_NAME AND RSK_REPLICATION_LOG.REPLI_DATE=RSK_REPLICATION_LOG_GPTMP_TODAY.REPLI_DATE ;
insert into RSK_REPLICATION_LOG (CUSTOMS_CODE,TABLE_NAME,TABLE_C_NAME,REPLI_DATE,REPLI_ER) select CUSTOMS_CODE,TABLE_NAME,TABLE_C_NAME,REPLI_DATE,REPLI_ER from RSK_REPLICATION_LOG_GPTMP_TODAY  where CMD_TYPE='I';
\timing
