\echo -----------------------RSK_CONDITION_BAK------------------------
select now();
\timing
delete from RSK_CONDITION_BAK using RSK_CONDITION_BAK_GPTMP_TODAY where RSK_CONDITION_BAK.CCTS_CODE=RSK_CONDITION_BAK_GPTMP_TODAY.CCTS_CODE AND RSK_CONDITION_BAK.OP_BAK_TIME=RSK_CONDITION_BAK_GPTMP_TODAY.OP_BAK_TIME ;
insert into RSK_CONDITION_BAK (CCTS_CODE,TRADE_CO,TRADE_NAME,CORP_TYPE,RSK_COND,RSK_COND_MID,RSK_COND_TXT,BEGIN_DATE,END_DATE,CUSTOMS_CODE,SMUGGLE_MODE,INPUT_ID,AUTHORIZE_ID,OP_TIME,OP_BAK_TYPE,OP_BAK_CUSTOMS,OP_BAK_MAN,OP_BAK_TIME) select CCTS_CODE,TRADE_CO,TRADE_NAME,CORP_TYPE,RSK_COND,RSK_COND_MID,RSK_COND_TXT,BEGIN_DATE,END_DATE,CUSTOMS_CODE,SMUGGLE_MODE,INPUT_ID,AUTHORIZE_ID,OP_TIME,OP_BAK_TYPE,OP_BAK_CUSTOMS,OP_BAK_MAN,OP_BAK_TIME from RSK_CONDITION_BAK_GPTMP_TODAY  where CMD_TYPE='I';
\timing
