\echo -----------------------RSK_CONTA_CAPACITY------------------------
select now();
\timing
delete from RSK_CONTA_CAPACITY using RSK_CONTA_CAPACITY_GPTMP_TODAY where RSK_CONTA_CAPACITY.CCTS_CODE=RSK_CONTA_CAPACITY_GPTMP_TODAY.CCTS_CODE ;
insert into RSK_CONTA_CAPACITY (CCTS_CODE,CONTA_MODEL,CONTA_BULK,CONTA_WEIGHT_LOW,CONTA_WEIGHT_HIGH,CUSTOMS_CODE,INPUT_ID,BEGIN_DATE,END_DATE) select CCTS_CODE,CONTA_MODEL,CONTA_BULK,CONTA_WEIGHT_LOW,CONTA_WEIGHT_HIGH,CUSTOMS_CODE,INPUT_ID,BEGIN_DATE,END_DATE from RSK_CONTA_CAPACITY_GPTMP_TODAY  where CMD_TYPE='I';
\timing
