\echo -----------------------RSK_CODE_TS------------------------
select now();
\timing
delete from RSK_CODE_TS using RSK_CODE_TS_GPTMP_TODAY where RSK_CODE_TS.CCTS_CODE=RSK_CODE_TS_GPTMP_TODAY.CCTS_CODE ;
insert into RSK_CODE_TS (CCTS_CODE,CODE_TS,I_E_FLAG,CUSTOMS_CODE,BEGIN_DATE,END_DATE,INPUT_ID,AUTHORIZE_ID,OP_TIME,NOTE) select CCTS_CODE,CODE_TS,I_E_FLAG,CUSTOMS_CODE,BEGIN_DATE,END_DATE,INPUT_ID,AUTHORIZE_ID,OP_TIME,NOTE from RSK_CODE_TS_GPTMP_TODAY  where CMD_TYPE='I';
\timing
