\echo -----------------------RSK_CONTA_CAPACITY_BAK------------------------
select now();
\timing
delete from RSK_CONTA_CAPACITY_BAK using RSK_CONTA_CAPACITY_BAK_GPTMP_TODAY where RSK_CONTA_CAPACITY_BAK.CCTS_CODE=RSK_CONTA_CAPACITY_BAK_GPTMP_TODAY.CCTS_CODE AND RSK_CONTA_CAPACITY_BAK.OP_BAK_TIME=RSK_CONTA_CAPACITY_BAK_GPTMP_TODAY.OP_BAK_TIME ;
insert into RSK_CONTA_CAPACITY_BAK (CCTS_CODE,CONTA_MODEL,CONTA_BULK,CONTA_WEIGHT_LOW,CONTA_WEIGHT_HIGH,CUSTOMS_CODE,INPUT_ID,BEGIN_DATE,END_DATE,OP_BAK_TYPE,OP_BAK_CUSTOMS,OP_BAK_MAN,OP_BAK_TIME) select CCTS_CODE,CONTA_MODEL,CONTA_BULK,CONTA_WEIGHT_LOW,CONTA_WEIGHT_HIGH,CUSTOMS_CODE,INPUT_ID,BEGIN_DATE,END_DATE,OP_BAK_TYPE,OP_BAK_CUSTOMS,OP_BAK_MAN,OP_BAK_TIME from RSK_CONTA_CAPACITY_BAK_GPTMP_TODAY  where CMD_TYPE='I';
\timing
