\echo -----------------------RSK_CASE_TRANSFER_G_NO------------------------
select now();
\timing
delete from RSK_CASE_TRANSFER_G_NO using RSK_CASE_TRANSFER_G_NO_GPTMP_TODAY where RSK_CASE_TRANSFER_G_NO.ENTRY_ID=RSK_CASE_TRANSFER_G_NO_GPTMP_TODAY.ENTRY_ID AND RSK_CASE_TRANSFER_G_NO.CASE_ID=RSK_CASE_TRANSFER_G_NO_GPTMP_TODAY.CASE_ID AND RSK_CASE_TRANSFER_G_NO.G_NO=RSK_CASE_TRANSFER_G_NO_GPTMP_TODAY.G_NO ;
insert into RSK_CASE_TRANSFER_G_NO (ENTRY_ID,CASE_ID,G_NO,G_NAME) select ENTRY_ID,CASE_ID,G_NO,G_NAME from RSK_CASE_TRANSFER_G_NO_GPTMP_TODAY  where CMD_TYPE='I';
\timing
