\echo -----------------------RSK_CASE_FEEDBACK_LIST------------------------
select now();
\timing
delete from RSK_CASE_FEEDBACK_LIST using RSK_CASE_FEEDBACK_LIST_GPTMP_TODAY where RSK_CASE_FEEDBACK_LIST.ENTRY_ID=RSK_CASE_FEEDBACK_LIST_GPTMP_TODAY.ENTRY_ID AND RSK_CASE_FEEDBACK_LIST.CASE_ID=RSK_CASE_FEEDBACK_LIST_GPTMP_TODAY.CASE_ID AND RSK_CASE_FEEDBACK_LIST.PROC_NO=RSK_CASE_FEEDBACK_LIST_GPTMP_TODAY.PROC_NO ;
insert into RSK_CASE_FEEDBACK_LIST (ENTRY_ID,CASE_ID,PROC_NO,PROC_RESULT) select ENTRY_ID,CASE_ID,PROC_NO,PROC_RESULT from RSK_CASE_FEEDBACK_LIST_GPTMP_TODAY  where CMD_TYPE='I';
\timing
