\echo -----------------------RSK_CONDITION------------------------
select now();
\timing
delete from RSK_CONDITION using RSK_CONDITION_GPTMP_TODAY where RSK_CONDITION.CCTS_CODE=RSK_CONDITION_GPTMP_TODAY.CCTS_CODE ;
insert into RSK_CONDITION (CCTS_CODE,TRADE_CO,TRADE_NAME,CORP_TYPE,RSK_COND,RSK_COND_MID,RSK_COND_TXT,BEGIN_DATE,END_DATE,CUSTOMS_CODE,SMUGGLE_MODE,INPUT_ID,AUTHORIZE_ID,OP_TIME) select CCTS_CODE,TRADE_CO,TRADE_NAME,CORP_TYPE,RSK_COND,RSK_COND_MID,RSK_COND_TXT,BEGIN_DATE,END_DATE,CUSTOMS_CODE,SMUGGLE_MODE,INPUT_ID,AUTHORIZE_ID,OP_TIME from RSK_CONDITION_GPTMP_TODAY  where CMD_TYPE='I';
\timing
