\echo -----------------------RSK_FIT_LOG_REL------------------------
select now();
\timing
delete from RSK_FIT_LOG_REL using RSK_FIT_LOG_REL_GPTMP_TODAY where RSK_FIT_LOG_REL.RSK_NO=RSK_FIT_LOG_REL_GPTMP_TODAY.RSK_NO AND RSK_FIT_LOG_REL.FORM_ID=RSK_FIT_LOG_REL_GPTMP_TODAY.FORM_ID AND RSK_FIT_LOG_REL.D_DATE=RSK_FIT_LOG_REL_GPTMP_TODAY.D_DATE ;
insert into RSK_FIT_LOG_REL (RSK_NO,FORM_ID,FORM_TYPE,I_E_FLAG,D_DATE,R_DATE,FIT_FLAG,INFO_LOCK_FLAG,RSK_REQUEST_DETAIL,EXAM_CONTA_FLAG,RSK_BEFORE) select RSK_NO,FORM_ID,FORM_TYPE,I_E_FLAG,D_DATE,R_DATE,FIT_FLAG,INFO_LOCK_FLAG,RSK_REQUEST_DETAIL,EXAM_CONTA_FLAG,RSK_BEFORE from RSK_FIT_LOG_REL_GPTMP_TODAY  where CMD_TYPE='I';
\timing
