\echo -----------------------RSK_CASE_FEEDBACK_HEAD------------------------
select now();
\timing
delete from RSK_CASE_FEEDBACK_HEAD using RSK_CASE_FEEDBACK_HEAD_GPTMP_TODAY where RSK_CASE_FEEDBACK_HEAD.ENTRY_ID=RSK_CASE_FEEDBACK_HEAD_GPTMP_TODAY.ENTRY_ID AND RSK_CASE_FEEDBACK_HEAD.CASE_ID=RSK_CASE_FEEDBACK_HEAD_GPTMP_TODAY.CASE_ID ;
insert into RSK_CASE_FEEDBACK_HEAD (ENTRY_ID,CASE_ID,TRADE_NAME,AGENT_NAME,BILL_NO,D_DATE,I_E_DATE,EXAM_ER1,EXAM_PROC_TIME,CASE_PROPERTY,ADMIN_PUNISH_CERT_NO,NOTE_S,OP_ER,CASE_VALUE,TRANSFER_DEPARTMENT,RECEIVE_DEPARTMENT) select ENTRY_ID,CASE_ID,TRADE_NAME,AGENT_NAME,BILL_NO,D_DATE,I_E_DATE,EXAM_ER1,EXAM_PROC_TIME,CASE_PROPERTY,ADMIN_PUNISH_CERT_NO,NOTE_S,OP_ER,CASE_VALUE,TRANSFER_DEPARTMENT,RECEIVE_DEPARTMENT from RSK_CASE_FEEDBACK_HEAD_GPTMP_TODAY  where CMD_TYPE='I';
\timing
