\echo -----------------------RSK_CASE_TRANSFER_HEAD------------------------
select now();
\timing
delete from RSK_CASE_TRANSFER_HEAD using RSK_CASE_TRANSFER_HEAD_GPTMP_TODAY where RSK_CASE_TRANSFER_HEAD.ENTRY_ID=RSK_CASE_TRANSFER_HEAD_GPTMP_TODAY.ENTRY_ID AND RSK_CASE_TRANSFER_HEAD.CASE_ID=RSK_CASE_TRANSFER_HEAD_GPTMP_TODAY.CASE_ID ;
insert into RSK_CASE_TRANSFER_HEAD (ENTRY_ID,CASE_ID,G_NAME,GROSS_WT,TRADE_TOTAL,TRADE_NAME,AGENT_NAME,BILL_NO,D_DATE,TRAF_MODE,I_E_DATE,EXAM_ER1,CASE_DESCRIBATION,TRANSFER_DEPARTMENT,TRANSFER_REASON,TRANSFER_ER,TRANSFER_TIME,RECEIVE_DEPARTMENT) select ENTRY_ID,CASE_ID,G_NAME,GROSS_WT,TRADE_TOTAL,TRADE_NAME,AGENT_NAME,BILL_NO,D_DATE,TRAF_MODE,I_E_DATE,EXAM_ER1,CASE_DESCRIBATION,TRANSFER_DEPARTMENT,TRANSFER_REASON,TRANSFER_ER,TRANSFER_TIME,RECEIVE_DEPARTMENT from RSK_CASE_TRANSFER_HEAD_GPTMP_TODAY  where CMD_TYPE='I';
\timing
