\echo -----------------------RSK_CODE_TS_BAK------------------------
select now();
\timing
delete from RSK_CODE_TS_BAK using RSK_CODE_TS_BAK_GPTMP_TODAY where RSK_CODE_TS_BAK.CCTS_CODE=RSK_CODE_TS_BAK_GPTMP_TODAY.CCTS_CODE AND RSK_CODE_TS_BAK.OP_BAK_TIME=RSK_CODE_TS_BAK_GPTMP_TODAY.OP_BAK_TIME ;
insert into RSK_CODE_TS_BAK (CCTS_CODE,CODE_TS,I_E_FLAG,CUSTOMS_CODE,BEGIN_DATE,END_DATE,INPUT_ID,AUTHORIZE_ID,OP_TIME,NOTE,OP_BAK_TYPE,OP_BAK_CUSTOMS,OP_BAK_MAN,OP_BAK_TIME) select CCTS_CODE,CODE_TS,I_E_FLAG,CUSTOMS_CODE,BEGIN_DATE,END_DATE,INPUT_ID,AUTHORIZE_ID,OP_TIME,NOTE,OP_BAK_TYPE,OP_BAK_CUSTOMS,OP_BAK_MAN,OP_BAK_TIME from RSK_CODE_TS_BAK_GPTMP_TODAY  where CMD_TYPE='I';
\timing
