\echo -----------------------RSK_EXAM_OP_LOG------------------------
select now();
\timing
delete from RSK_EXAM_OP_LOG using RSK_EXAM_OP_LOG_GPTMP_TODAY where RSK_EXAM_OP_LOG.EXAM_REC_ID=RSK_EXAM_OP_LOG_GPTMP_TODAY.EXAM_REC_ID AND RSK_EXAM_OP_LOG.OP_TIME=RSK_EXAM_OP_LOG_GPTMP_TODAY.OP_TIME AND RSK_EXAM_OP_LOG.MODI_TYPE=RSK_EXAM_OP_LOG_GPTMP_TODAY.MODI_TYPE AND RSK_EXAM_OP_LOG.TABLE_NAME=RSK_EXAM_OP_LOG_GPTMP_TODAY.TABLE_NAME AND RSK_EXAM_OP_LOG.ITEM_NAME=RSK_EXAM_OP_LOG_GPTMP_TODAY.ITEM_NAME ;
insert into RSK_EXAM_OP_LOG (EXAM_REC_ID,OP_TIME,OP_ER,MODI_TYPE,FORM_ID,TABLE_NAME,ITEM_NAME,ITEM_SOURCE,ITEM_CURRENT,NOTE) select EXAM_REC_ID,OP_TIME,OP_ER,MODI_TYPE,FORM_ID,TABLE_NAME,ITEM_NAME,ITEM_SOURCE,ITEM_CURRENT,NOTE from RSK_EXAM_OP_LOG_GPTMP_TODAY  where CMD_TYPE='I';
\timing
