\echo -----------------------RSK_UNLOCK_OP_LOG------------------------
select now();
\timing
delete from RSK_UNLOCK_OP_LOG using RSK_UNLOCK_OP_LOG_GPTMP_TODAY where RSK_UNLOCK_OP_LOG.FORM_ID=RSK_UNLOCK_OP_LOG_GPTMP_TODAY.FORM_ID AND RSK_UNLOCK_OP_LOG.RSK_NO=RSK_UNLOCK_OP_LOG_GPTMP_TODAY.RSK_NO AND RSK_UNLOCK_OP_LOG.UNLOCK_TIME=RSK_UNLOCK_OP_LOG_GPTMP_TODAY.UNLOCK_TIME ;
insert into RSK_UNLOCK_OP_LOG (FORM_ID,RSK_NO,FORM_TYPE,CUSTOMS_CODE,UNLOCK_ER,UNLOCK_TIME,UNLOCK_REASON) select FORM_ID,RSK_NO,FORM_TYPE,CUSTOMS_CODE,UNLOCK_ER,UNLOCK_TIME,UNLOCK_REASON from RSK_UNLOCK_OP_LOG_GPTMP_TODAY  where CMD_TYPE='I';
\timing
