\echo -----------------------RSK_RECHECK_REL------------------------
select now();
\timing
delete from RSK_RECHECK_REL using RSK_RECHECK_REL_GPTMP_TODAY where RSK_RECHECK_REL.FORM_ID=RSK_RECHECK_REL_GPTMP_TODAY.FORM_ID ;
insert into RSK_RECHECK_REL (FORM_ID,CHECK_FLAG,LOCK_OP_CUSTOMS,LOCK_OP_ID,LOCK_OP_TEL,LOCK_DATE,UNLOCK_CUSTOMS,UNLOCK_OP_ID,UNLOCK_DATE,RSK_NO) select FORM_ID,CHECK_FLAG,LOCK_OP_CUSTOMS,LOCK_OP_ID,LOCK_OP_TEL,LOCK_DATE,UNLOCK_CUSTOMS,UNLOCK_OP_ID,UNLOCK_DATE,RSK_NO from RSK_RECHECK_REL_GPTMP_TODAY  where CMD_TYPE='I';
\timing
