\echo -----------------------RSK_VS_EXAM------------------------
select now();
\timing
delete from RSK_VS_EXAM using RSK_VS_EXAM_GPTMP_TODAY where RSK_VS_EXAM.FORM_ID=RSK_VS_EXAM_GPTMP_TODAY.FORM_ID AND RSK_VS_EXAM.FORM_TYPE=RSK_VS_EXAM_GPTMP_TODAY.FORM_TYPE AND RSK_VS_EXAM.RSK_NO=RSK_VS_EXAM_GPTMP_TODAY.RSK_NO AND RSK_VS_EXAM.D_DATE=RSK_VS_EXAM_GPTMP_TODAY.D_DATE AND RSK_VS_EXAM.EXAM_REC_ID=RSK_VS_EXAM_GPTMP_TODAY.EXAM_REC_ID ;
insert into RSK_VS_EXAM (FORM_ID,FORM_TYPE,RSK_NO,D_DATE,EXAM_REC_ID) select FORM_ID,FORM_TYPE,RSK_NO,D_DATE,EXAM_REC_ID from RSK_VS_EXAM_GPTMP_TODAY  where CMD_TYPE='I';
\timing
