\echo -----------------------SERVICE_LIST------------------------
select now();
\timing
delete from SERVICE_LIST using SERVICE_LIST_GPTMP_TODAY where SERVICE_LIST.MANUAL_NO=SERVICE_LIST_GPTMP_TODAY.MANUAL_NO AND SERVICE_LIST.F_NO=SERVICE_LIST_GPTMP_TODAY.F_NO ;
insert into SERVICE_LIST (MANUAL_NO,F_NO,FEE_TYPE,FEE_RATE,G_NO,G_NAME,FEE_AMT,FEE_CURR,FEE_RMB,SERVICE_FEE) select MANUAL_NO,F_NO,FEE_TYPE,FEE_RATE,G_NO,G_NAME,FEE_AMT,FEE_CURR,FEE_RMB,SERVICE_FEE from SERVICE_LIST_GPTMP_TODAY  where CMD_TYPE='I';
\timing
