\echo -----------------------SHIP_TONNAGE------------------------
select now();
\timing
delete from SHIP_TONNAGE using SHIP_TONNAGE_GPTMP_TODAY where SHIP_TONNAGE.LICENSE_NO=SHIP_TONNAGE_GPTMP_TODAY.LICENSE_NO ;
insert into SHIP_TONNAGE (LICENSE_NO,SHIP_ID,SHIP_NAME_EN,SHIP_NAME_CN,SHIP_NAME_ORI,COUNTRY_CODE,SHIP_TYPE,SHIP_ATTR,SHIP_USE_CODE,TONNAGE,TON_MOD_FLAG,I_E_DATE,DECL_CODE,TONNAGE_TERM,SHIP_AGENT_CODE,SHIP_AGENT_NAME,DUTYFORM_NO,REAL_DUTY,INPUT_DATE,INPUT_ER,GRANT_DATE,GRANT_ER,SIGN_NAME,BEGIN_DATE,END_DATE,DUTY_MODE,DEFER_REASON,OP_FLAG,PROC_RESULT,TAX_RATE,HASH_SIGN,MANUAL_LIC_NO,NOTE_MAN,NOTE_AUTO) select LICENSE_NO,SHIP_ID,SHIP_NAME_EN,SHIP_NAME_CN,SHIP_NAME_ORI,COUNTRY_CODE,SHIP_TYPE,SHIP_ATTR,SHIP_USE_CODE,TONNAGE,TON_MOD_FLAG,I_E_DATE,DECL_CODE,TONNAGE_TERM,SHIP_AGENT_CODE,SHIP_AGENT_NAME,DUTYFORM_NO,REAL_DUTY,INPUT_DATE,INPUT_ER,GRANT_DATE,GRANT_ER,SIGN_NAME,BEGIN_DATE,END_DATE,DUTY_MODE,DEFER_REASON,OP_FLAG,PROC_RESULT,TAX_RATE,HASH_SIGN,MANUAL_LIC_NO,NOTE_MAN,NOTE_AUTO from SHIP_TONNAGE_GPTMP_TODAY  where CMD_TYPE='I';
\timing
