\echo -----------------------STATUS_DETAIL------------------------
select now();
\timing
delete from STATUS_DETAIL using STATUS_DETAIL_GPTMP_TODAY where STATUS_DETAIL.ENTRY_ID=STATUS_DETAIL_GPTMP_TODAY.ENTRY_ID AND STATUS_DETAIL.DETAIL_COUNT=STATUS_DETAIL_GPTMP_TODAY.DETAIL_COUNT ;
insert into STATUS_DETAIL (ENTRY_ID,DETAIL_COUNT,STATUS_NUMBER,STATUS_RESULT,STATUS_DETAIL) select ENTRY_ID,DETAIL_COUNT,STATUS_NUMBER,STATUS_RESULT,STATUS_DETAIL from STATUS_DETAIL_GPTMP_TODAY  where CMD_TYPE='I';
\timing
