\echo -----------------------STF_RECORD------------------------
select now();
\timing
delete from STF_RECORD using STF_RECORD_GPTMP_TODAY where STF_RECORD.ENTRY_ID=STF_RECORD_GPTMP_TODAY.ENTRY_ID ;
insert into STF_RECORD (ENTRY_ID,STF_ID,I_E_FLAG,MANUAL_NO,STF_DATE1,STF_ER1,STF_DATE2,STF_ER2,ROOM_NO,NOTE_TEXT) select ENTRY_ID,STF_ID,I_E_FLAG,MANUAL_NO,STF_DATE1,STF_ER1,STF_DATE2,STF_ER2,ROOM_NO,NOTE_TEXT from STF_RECORD_GPTMP_TODAY  where CMD_TYPE='I';
\timing
