\echo -----------------------STL_DATA_TS_LIST------------------------
select now();
\timing
delete from STL_DATA_TS_LIST using STL_DATA_TS_LIST_GPTMP_TODAY where STL_DATA_TS_LIST.UCR_CODE=STL_DATA_TS_LIST_GPTMP_TODAY.UCR_CODE AND STL_DATA_TS_LIST.G_NO=STL_DATA_TS_LIST_GPTMP_TODAY.G_NO ;
insert into STL_DATA_TS_LIST (UCR_CODE,G_NO,CODE_TS,G_NAME,PACK_NO) select UCR_CODE,G_NO,CODE_TS,G_NAME,PACK_NO from STL_DATA_TS_LIST_GPTMP_TODAY  where CMD_TYPE='I';
\timing
