\echo -----------------------STL_DATA_CONTA_LIST------------------------
select now();
\timing
delete from STL_DATA_CONTA_LIST using STL_DATA_CONTA_LIST_GPTMP_TODAY where STL_DATA_CONTA_LIST.UCR_CODE=STL_DATA_CONTA_LIST_GPTMP_TODAY.UCR_CODE AND STL_DATA_CONTA_LIST.CONTAINER_ID=STL_DATA_CONTA_LIST_GPTMP_TODAY.CONTAINER_ID ;
insert into STL_DATA_CONTA_LIST (UCR_CODE,CONTAINER_ID,SEAL_NO) select UCR_CODE,CONTAINER_ID,SEAL_NO from STL_DATA_CONTA_LIST_GPTMP_TODAY  where CMD_TYPE='I';
\timing
