\echo -----------------------TCS_DETAIL_LIST------------------------
select now();
\timing
delete from TCS_DETAIL_LIST using TCS_DETAIL_LIST_GPTMP_TODAY where TCS_DETAIL_LIST.ACCOUNT_ORG_CODE=TCS_DETAIL_LIST_GPTMP_TODAY.ACCOUNT_ORG_CODE AND TCS_DETAIL_LIST.IN_TREASURY_DATE=TCS_DETAIL_LIST_GPTMP_TODAY.IN_TREASURY_DATE AND TCS_DETAIL_LIST.PACK_NO=TCS_DETAIL_LIST_GPTMP_TODAY.PACK_NO AND TCS_DETAIL_LIST.ITEM_NO=TCS_DETAIL_LIST_GPTMP_TODAY.ITEM_NO ;
insert into TCS_DETAIL_LIST (ACCOUNT_ORG_CODE,IN_TREASURY_DATE,PACK_NO,CURRENT_PACK_NO,ITEM_NO,ENTRY_ID,TAX_ID,EXPORT_VOU_TYPE,TREASURY_CODE,BUDGET_LEVEL_CODE,BUDGET_SUBJECT_CODE,TRA_AMT,ORIGIN,REMARK1,REMARK2,REMARK3,DEAL_MARK,DEAL_TIME,DEAL_NOTE) select ACCOUNT_ORG_CODE,IN_TREASURY_DATE,PACK_NO,CURRENT_PACK_NO,ITEM_NO,ENTRY_ID,TAX_ID,EXPORT_VOU_TYPE,TREASURY_CODE,BUDGET_LEVEL_CODE,BUDGET_SUBJECT_CODE,TRA_AMT,ORIGIN,REMARK1,REMARK2,REMARK3,DEAL_MARK,DEAL_TIME,DEAL_NOTE from TCS_DETAIL_LIST_GPTMP_TODAY  where CMD_TYPE='I';
\timing
