\echo -----------------------TCS_DETAIL_HEAD------------------------
select now();
\timing
delete from TCS_DETAIL_HEAD using TCS_DETAIL_HEAD_GPTMP_TODAY where TCS_DETAIL_HEAD.ACCOUNT_ORG_CODE=TCS_DETAIL_HEAD_GPTMP_TODAY.ACCOUNT_ORG_CODE AND TCS_DETAIL_HEAD.IN_TREASURY_DATE=TCS_DETAIL_HEAD_GPTMP_TODAY.IN_TREASURY_DATE AND TCS_DETAIL_HEAD.PACK_NO=TCS_DETAIL_HEAD_GPTMP_TODAY.PACK_NO AND TCS_DETAIL_HEAD.CURRENT_PACK_NO=TCS_DETAIL_HEAD_GPTMP_TODAY.CURRENT_PACK_NO ;
insert into TCS_DETAIL_HEAD (MSG_ID,ACCOUNT_ORG_CODE,IN_TREASURY_DATE,PACK_NO,CHILD_PACK_NUM,CURRENT_PACK_NO,ALL_NUM,ALL_AMOUNT,CURRENT_NUM,CURRENT_AMOUNT,VERIFY_MARK,VERIFY_NOTE,MAX_ITEM_NO,RECEIVE_DATE) select MSG_ID,ACCOUNT_ORG_CODE,IN_TREASURY_DATE,PACK_NO,CHILD_PACK_NUM,CURRENT_PACK_NO,ALL_NUM,ALL_AMOUNT,CURRENT_NUM,CURRENT_AMOUNT,VERIFY_MARK,VERIFY_NOTE,MAX_ITEM_NO,RECEIVE_DATE from TCS_DETAIL_HEAD_GPTMP_TODAY  where CMD_TYPE='I';
\timing
