\echo -----------------------TEP_REC_LOG------------------------
select now();
\timing
delete from TEP_REC_LOG using TEP_REC_LOG_GPTMP_TODAY where TEP_REC_LOG.REC_DATE=TEP_REC_LOG_GPTMP_TODAY.REC_DATE AND TEP_REC_LOG.REC_TYPE=TEP_REC_LOG_GPTMP_TODAY.REC_TYPE AND TEP_REC_LOG.TRANS_NO=TEP_REC_LOG_GPTMP_TODAY.TRANS_NO ;
insert into TEP_REC_LOG (REC_DATE,TRANS_NO,REC_TIME,REC_SIGN,REC_TYPE,ENTRY_ID,TAX_ID,TAX_TYPE,GUA_ID,PAY_STATUS,DUTY_FLAG,AMOUNT,P_LIMIT,RESULT_NO,DESCRIPTION) select REC_DATE,TRANS_NO,REC_TIME,REC_SIGN,REC_TYPE,ENTRY_ID,TAX_ID,TAX_TYPE,GUA_ID,PAY_STATUS,DUTY_FLAG,AMOUNT,P_LIMIT,RESULT_NO,DESCRIPTION from TEP_REC_LOG_GPTMP_TODAY  where CMD_TYPE='I';
\timing
