\echo -----------------------TEP_COMPANY------------------------
select now();
\timing
delete from TEP_COMPANY using TEP_COMPANY_GPTMP_TODAY where TEP_COMPANY.TEP_NO=TEP_COMPANY_GPTMP_TODAY.TEP_NO ;
insert into TEP_COMPANY (PRE_TEP_NO,TEP_NO,TEP_TYPE,APPLY_DATE,RECORD_DATE,PLATFORM_NAME,CUSTOM_CODE,TRADE_CODE,ORG_CODE,AGREE_NO,LINKMAN,ADDRESS,PHONE,BANK_NAME,APPLY_STATE,BANK_VOUCH_ID,BANK_ID,VOUCH_BANK_NAME,VOUCH_MONEY,VOUCH_BEGIN_DATE,VOUCH_END_DATE,AUDIT_STATE,AUDIT_ER,AUDIT_NOTE,AUDIT_DATE,SPT1,SPT2,SPT3) select PRE_TEP_NO,TEP_NO,TEP_TYPE,APPLY_DATE,RECORD_DATE,PLATFORM_NAME,CUSTOM_CODE,TRADE_CODE,ORG_CODE,AGREE_NO,LINKMAN,ADDRESS,PHONE,BANK_NAME,APPLY_STATE,BANK_VOUCH_ID,BANK_ID,VOUCH_BANK_NAME,VOUCH_MONEY,VOUCH_BEGIN_DATE,VOUCH_END_DATE,AUDIT_STATE,AUDIT_ER,AUDIT_NOTE,AUDIT_DATE,SPT1,SPT2,SPT3 from TEP_COMPANY_GPTMP_TODAY  where CMD_TYPE='I';
\timing
