\echo -----------------------TEP_ERR_LOG------------------------
select now();
\timing
delete from TEP_ERR_LOG using TEP_ERR_LOG_GPTMP_TODAY where TEP_ERR_LOG.ERR_NO=TEP_ERR_LOG_GPTMP_TODAY.ERR_NO AND TEP_ERR_LOG.CREATE_DATE=TEP_ERR_LOG_GPTMP_TODAY.CREATE_DATE ;
insert into TEP_ERR_LOG (ERR_NO,CREATE_DATE,TEP_TYPE,STEP_ID,NOTE) select ERR_NO,CREATE_DATE,TEP_TYPE,STEP_ID,NOTE from TEP_ERR_LOG_GPTMP_TODAY  where CMD_TYPE='I';
\timing
