\echo -----------------------TEP_EPLAT_RESPONSE------------------------
select now();
\timing
delete from TEP_EPLAT_RESPONSE using TEP_EPLAT_RESPONSE_GPTMP_TODAY where TEP_EPLAT_RESPONSE.MSG_TYPE=TEP_EPLAT_RESPONSE_GPTMP_TODAY.MSG_TYPE AND TEP_EPLAT_RESPONSE.CREATE_DATE=TEP_EPLAT_RESPONSE_GPTMP_TODAY.CREATE_DATE ;
insert into TEP_EPLAT_RESPONSE (MSG_TYPE,CREATE_DATE,CUSTOMS_CODE,RETURN_CODE,ERR_RETURN_CODE,ERR_RETURN_INFO,SPT1) select MSG_TYPE,CREATE_DATE,CUSTOMS_CODE,RETURN_CODE,ERR_RETURN_CODE,ERR_RETURN_INFO,SPT1 from TEP_EPLAT_RESPONSE_GPTMP_TODAY  where CMD_TYPE='I';
\timing
