\echo -----------------------TEP_DEBIT_REC_REQUEST------------------------
select now();
\timing
delete from TEP_DEBIT_REC_REQUEST using TEP_DEBIT_REC_REQUEST_GPTMP_TODAY where TEP_DEBIT_REC_REQUEST.REQUEST_DATE=TEP_DEBIT_REC_REQUEST_GPTMP_TODAY.REQUEST_DATE AND TEP_DEBIT_REC_REQUEST.TRANS_NO=TEP_DEBIT_REC_REQUEST_GPTMP_TODAY.TRANS_NO ;
insert into TEP_DEBIT_REC_REQUEST (REQUEST_DATE,TRANS_NO,REQUEST_TIME,PAY_STATUS,ENTRY_ID,DUTY_FLAG,TAX_TYPE,TAX_ID,GUA_ID,AMOUNT,P_LIMIT,MEMO) select REQUEST_DATE,TRANS_NO,REQUEST_TIME,PAY_STATUS,ENTRY_ID,DUTY_FLAG,TAX_TYPE,TAX_ID,GUA_ID,AMOUNT,P_LIMIT,MEMO from TEP_DEBIT_REC_REQUEST_GPTMP_TODAY  where CMD_TYPE='I';
\timing
