\echo -----------------------TEP_DEBIT_REC_RESPONSE------------------------
select now();
\timing
delete from TEP_DEBIT_REC_RESPONSE using TEP_DEBIT_REC_RESPONSE_GPTMP_TODAY where TEP_DEBIT_REC_RESPONSE.TRANS_NO=TEP_DEBIT_REC_RESPONSE_GPTMP_TODAY.TRANS_NO AND TEP_DEBIT_REC_RESPONSE.RESPONSE_DATE=TEP_DEBIT_REC_RESPONSE_GPTMP_TODAY.RESPONSE_DATE ;
insert into TEP_DEBIT_REC_RESPONSE (TRANS_NO,RESPONSE_DATE,RESPONSE_TIME,REC_CODE,MEMO) select TRANS_NO,RESPONSE_DATE,RESPONSE_TIME,REC_CODE,MEMO from TEP_DEBIT_REC_RESPONSE_GPTMP_TODAY  where CMD_TYPE='I';
\timing
