\echo -----------------------TEP_VOUCHER_REC_LIST_DETAIL------------------------
select now();
\timing
delete from TEP_VOUCHER_REC_LIST_DETAIL using TEP_VOUCHER_REC_LIST_DETAIL_GPTMP_TODAY where TEP_VOUCHER_REC_LIST_DETAIL.VOUCHER_RECEIVABLE_SEQ_NO=TEP_VOUCHER_REC_LIST_DETAIL_GPTMP_TODAY.VOUCHER_RECEIVABLE_SEQ_NO AND TEP_VOUCHER_REC_LIST_DETAIL.PAYEE_CODE=TEP_VOUCHER_REC_LIST_DETAIL_GPTMP_TODAY.PAYEE_CODE AND TEP_VOUCHER_REC_LIST_DETAIL.BANK_CODE=TEP_VOUCHER_REC_LIST_DETAIL_GPTMP_TODAY.BANK_CODE AND TEP_VOUCHER_REC_LIST_DETAIL.PAYEE_BANK_ACCOUNT=TEP_VOUCHER_REC_LIST_DETAIL_GPTMP_TODAY.PAYEE_BANK_ACCOUNT ;
insert into TEP_VOUCHER_REC_LIST_DETAIL (VOUCHER_RECEIVABLE_SEQ_NO,BANK_CODE,PAYEE_BANK_ACCOUNT,PAYEE_CODE,PAYEE_BANK_NAME,PAYEE_BRANCH_CODE,PAYEE_BANK_ACCOUNT_NAME) select VOUCHER_RECEIVABLE_SEQ_NO,BANK_CODE,PAYEE_BANK_ACCOUNT,PAYEE_CODE,PAYEE_BANK_NAME,PAYEE_BRANCH_CODE,PAYEE_BANK_ACCOUNT_NAME from TEP_VOUCHER_REC_LIST_DETAIL_GPTMP_TODAY  where CMD_TYPE='I';
\timing
