\echo -----------------------TMP_EMS_CONSUME------------------------
select now();
\timing
delete from TMP_EMS_CONSUME using TMP_EMS_CONSUME_GPTMP_TODAY where TMP_EMS_CONSUME.EMS_NO=TMP_EMS_CONSUME_GPTMP_TODAY.EMS_NO AND TMP_EMS_CONSUME.EXG_NO=TMP_EMS_CONSUME_GPTMP_TODAY.EXG_NO AND TMP_EMS_CONSUME.EXG_VERSION=TMP_EMS_CONSUME_GPTMP_TODAY.EXG_VERSION AND TMP_EMS_CONSUME.IMG_NO=TMP_EMS_CONSUME_GPTMP_TODAY.IMG_NO ;
insert into TMP_EMS_CONSUME (EMS_NO,EXG_NO,EXG_VERSION,IMG_NO,MODIFY_TIMES,DEC_CM,DEC_DM,OTHER_CM,OTHER_DM,CM_MARK,PRODUCT_MARK,PRODUCT_TYPE,MODIFY_MARK,CONTROL_MARK,NOTE,ETL_MARK) select EMS_NO,EXG_NO,EXG_VERSION,IMG_NO,MODIFY_TIMES,DEC_CM,DEC_DM,OTHER_CM,OTHER_DM,CM_MARK,PRODUCT_MARK,PRODUCT_TYPE,MODIFY_MARK,CONTROL_MARK,NOTE,ETL_MARK from TMP_EMS_CONSUME_GPTMP_TODAY  where CMD_TYPE='I';
\timing
