\echo -----------------------TRANSFER_FEE------------------------
select now();
\timing
delete from TRANSFER_FEE using TRANSFER_FEE_GPTMP_TODAY where TRANSFER_FEE.MANUAL_NO=TRANSFER_FEE_GPTMP_TODAY.MANUAL_NO AND TRANSFER_FEE.RTN_MANUAL_NO=TRANSFER_FEE_GPTMP_TODAY.RTN_MANUAL_NO ;
insert into TRANSFER_FEE (MANUAL_NO,RTN_MANUAL_NO,TRANSFER_FEE) select MANUAL_NO,RTN_MANUAL_NO,TRANSFER_FEE from TRANSFER_FEE_GPTMP_TODAY  where CMD_TYPE='I';
\timing
