\echo -----------------------TRANSFER_FEE_LOG------------------------
select now();
\timing
delete from TRANSFER_FEE_LOG using TRANSFER_FEE_LOG_GPTMP_TODAY where TRANSFER_FEE_LOG.MANUAL_NO=TRANSFER_FEE_LOG_GPTMP_TODAY.MANUAL_NO AND TRANSFER_FEE_LOG.RTN_MANUAL_NO=TRANSFER_FEE_LOG_GPTMP_TODAY.RTN_MANUAL_NO AND TRANSFER_FEE_LOG.CREATE_DATE=TRANSFER_FEE_LOG_GPTMP_TODAY.CREATE_DATE ;
insert into TRANSFER_FEE_LOG (MANUAL_NO,RTN_MANUAL_NO,CREATE_DATE,TRANSFER_FEE) select MANUAL_NO,RTN_MANUAL_NO,CREATE_DATE,TRANSFER_FEE from TRANSFER_FEE_LOG_GPTMP_TODAY  where CMD_TYPE='I';
\timing
