\echo -----------------------TRN_EXAM_MAX_SEQ------------------------
select now();
\timing
delete from TRN_EXAM_MAX_SEQ using TRN_EXAM_MAX_SEQ_GPTMP_TODAY where TRN_EXAM_MAX_SEQ.TYPE=TRN_EXAM_MAX_SEQ_GPTMP_TODAY.TYPE AND TRN_EXAM_MAX_SEQ.YEARAREA=TRN_EXAM_MAX_SEQ_GPTMP_TODAY.YEARAREA ;
insert into TRN_EXAM_MAX_SEQ (TYPE,YEARAREA,MAX_SEQ) select TYPE,YEARAREA,MAX_SEQ from TRN_EXAM_MAX_SEQ_GPTMP_TODAY  where CMD_TYPE='I';
\timing
