\echo -----------------------TRN_COP_REL------------------------
select now();
\timing
delete from TRN_COP_REL using TRN_COP_REL_GPTMP_TODAY where TRN_COP_REL.CO_REG_NO=TRN_COP_REL_GPTMP_TODAY.CO_REG_NO ;
insert into TRN_COP_REL (CO_REG_NO,CO_CUSTOMS_NO,MAIN_PORT,CO_NAME,CO_ADDRESS,CO_PHONE_NO,VALID_FLAG,VALID_DATE,INPUT_DATE,INPUT_OP_ID,PERMIT_FLAG,PERMIT_DATE,PERMIT_OP_ID,RESERV_FIELD,CO_REG_TYPE,CO_PROPERTY,CO_DEAL_RANGE,CO_AUTHORIZE_NO,CO_DEAL_DATE,CO_CORPORATION_REP,CO_ABROAD_NAME,GANG_AO_CARS,GANG_AO_CARS_USED,CK_FLAG,NOTE_FIELD) select CO_REG_NO,CO_CUSTOMS_NO,MAIN_PORT,CO_NAME,CO_ADDRESS,CO_PHONE_NO,VALID_FLAG,VALID_DATE,INPUT_DATE,INPUT_OP_ID,PERMIT_FLAG,PERMIT_DATE,PERMIT_OP_ID,RESERV_FIELD,CO_REG_TYPE,CO_PROPERTY,CO_DEAL_RANGE,CO_AUTHORIZE_NO,CO_DEAL_DATE,CO_CORPORATION_REP,CO_ABROAD_NAME,GANG_AO_CARS,GANG_AO_CARS_USED,CK_FLAG,NOTE_FIELD from TRN_COP_REL_GPTMP_TODAY  where CMD_TYPE='I';
\timing
