\echo -----------------------TRN_VEHICLE------------------------
select now();
\timing
delete from TRN_VEHICLE using TRN_VEHICLE_GPTMP_TODAY where TRN_VEHICLE.CUSTOM_NO=TRN_VEHICLE_GPTMP_TODAY.CUSTOM_NO ;
insert into TRN_VEHICLE (CUSTOM_NO,VALID_FLAG,CK_FLAG,MAN_CUSTOM_NO,DR_NAME,DR_SFZ,CO_NAME,CAR_NO,CAR_EC_NO,VALID_DATE,OPERATOR_NO,INPUT_DATE,CO_ADDRESS,CO_TELE,CO_MAIL,TRAF_FLAG,TRAF_NOTE) select CUSTOM_NO,VALID_FLAG,CK_FLAG,MAN_CUSTOM_NO,DR_NAME,DR_SFZ,CO_NAME,CAR_NO,CAR_EC_NO,VALID_DATE,OPERATOR_NO,INPUT_DATE,CO_ADDRESS,CO_TELE,CO_MAIL,TRAF_FLAG,TRAF_NOTE from TRN_VEHICLE_GPTMP_TODAY  where CMD_TYPE='I';
\timing
