\echo -----------------------TRN_CHECK------------------------
select now();
\timing
delete from TRN_CHECK using TRN_CHECK_GPTMP_TODAY where TRN_CHECK.NO=TRN_CHECK_GPTMP_TODAY.NO ;
insert into TRN_CHECK (NO,I_E_FLAG,CODE_S,CODE_E,GOODS_NAME,AGENT_NAME,TRANS_NAME,TRAF_NAME,PORT_CO,RESULT_MARK,RESULT_STATUS,EFFECT_D_S,EFFECT_D_E,ISSUE_PORT,ISSUE_OP_ID,ISSUE_TIME,MODI_TIME) select NO,I_E_FLAG,CODE_S,CODE_E,GOODS_NAME,AGENT_NAME,TRANS_NAME,TRAF_NAME,PORT_CO,RESULT_MARK,RESULT_STATUS,EFFECT_D_S,EFFECT_D_E,ISSUE_PORT,ISSUE_OP_ID,ISSUE_TIME,MODI_TIME from TRN_CHECK_GPTMP_TODAY  where CMD_TYPE='I';
\timing
