\echo -----------------------TRN_ALC_REL------------------------
select now();
\timing
delete from TRN_ALC_REL using TRN_ALC_REL_GPTMP_TODAY where TRN_ALC_REL.CUSTOMS_CODE=TRN_ALC_REL_GPTMP_TODAY.CUSTOMS_CODE AND TRN_ALC_REL.TRN_MODE=TRN_ALC_REL_GPTMP_TODAY.TRN_MODE AND TRN_ALC_REL.TRAF_MODE=TRN_ALC_REL_GPTMP_TODAY.TRAF_MODE ;
insert into TRN_ALC_REL (CUSTOMS_CODE,TRN_MODE,TRAF_MODE,ALC_REL_FLAG,OP_ER,OP_DATE) select CUSTOMS_CODE,TRN_MODE,TRAF_MODE,ALC_REL_FLAG,OP_ER,OP_DATE from TRN_ALC_REL_GPTMP_TODAY  where CMD_TYPE='I';
\timing
