\echo -----------------------TRN_POP_COP_REL------------------------
select now();
\timing
delete from TRN_POP_COP_REL using TRN_POP_COP_REL_GPTMP_TODAY where TRN_POP_COP_REL.AGENT_CODE=TRN_POP_COP_REL_GPTMP_TODAY.AGENT_CODE AND TRN_POP_COP_REL.CUSTOMS_CODE=TRN_POP_COP_REL_GPTMP_TODAY.CUSTOMS_CODE ;
insert into TRN_POP_COP_REL (AGENT_CODE,AGENT_NAME,CUSTOMS_CODE,OTHER_COP,OTHER_RECV_PORT,VALID_FLAG,OP_ER,OP_DATE) select AGENT_CODE,AGENT_NAME,CUSTOMS_CODE,OTHER_COP,OTHER_RECV_PORT,VALID_FLAG,OP_ER,OP_DATE from TRN_POP_COP_REL_GPTMP_TODAY  where CMD_TYPE='I';
\timing
