\echo ------------------AGREEMENT_GOODS_LIST----------------
select now();
\timing
insert into AGREEMENT_GOODS_LIST_GPTMP (CMD_TYPE,ENTRY_ID, G_NO) select CMD_TYPE,ENTRY_ID, G_NO from AGREEMENT_GOODS_LIST_INC_EXT;

delete from AGREEMENT_GOODS_LIST using AGREEMENT_GOODS_LIST_GPTMP where AGREEMENT_GOODS_LIST_GPTMP.ENTRY_ID=AGREEMENT_GOODS_LIST.ENTRY_ID AND AGREEMENT_GOODS_LIST_GPTMP.G_NO=AGREEMENT_GOODS_LIST.G_NO ;

insert into AGREEMENT_GOODS_LIST(ENTRY_ID,G_NO,D_DATE,CODE_TS,G_NAME,AGREEMENT_ID,QTY_1,UNIT_1,ORIGIN_COUNTRY,RMB_PRICE,USD_PRICE,CREATE_DATE) select ENTRY_ID,G_NO,D_DATE,CODE_TS,G_NAME,AGREEMENT_ID,QTY_1,UNIT_1,ORIGIN_COUNTRY,RMB_PRICE,USD_PRICE,CREATE_DATE from AGREEMENT_GOODS_LIST_INC_EXT where CMD_TYPE='I';

delete from AGREEMENT_GOODS_LIST_GPTMP;

\timing
