\echo ------------------AMS_MODI_LOG----------------
select now();
\timing
insert into AMS_MODI_LOG_GPTMP (CMD_TYPE,EMS_NO, OP_TIME, MODI_TYPE, ITEM_NAME) select CMD_TYPE,EMS_NO, OP_TIME, MODI_TYPE, ITEM_NAME from AMS_MODI_LOG_INC_EXT;

delete from AMS_MODI_LOG using AMS_MODI_LOG_GPTMP where AMS_MODI_LOG_GPTMP.EMS_NO=AMS_MODI_LOG.EMS_NO AND AMS_MODI_LOG_GPTMP.OP_TIME=AMS_MODI_LOG.OP_TIME AND AMS_MODI_LOG_GPTMP.MODI_TYPE=AMS_MODI_LOG.MODI_TYPE AND AMS_MODI_LOG_GPTMP.ITEM_NAME=AMS_MODI_LOG.ITEM_NAME ;

insert into AMS_MODI_LOG(EMS_NO,OP_TIME,MODI_TYPE,ITEM_NAME,ITEM_SOURCE,ITEM_CURRENT,OP_ER,NOTE) select EMS_NO,OP_TIME,MODI_TYPE,ITEM_NAME,ITEM_SOURCE,ITEM_CURRENT,OP_ER,NOTE from AMS_MODI_LOG_INC_EXT where CMD_TYPE='I';

delete from AMS_MODI_LOG_GPTMP;

\timing
