\echo ------------------ARRIVAL_INFO_LIST----------------
select now();
\timing
insert into ARRIVAL_INFO_LIST_GPTMP (CMD_TYPE,BILL_NO, VOYAGE_NO, SHIP_ID, I_E_DATE, CUSTOMS_CODE, TRAF_MODE) select CMD_TYPE,BILL_NO, VOYAGE_NO, SHIP_ID, I_E_DATE, CUSTOMS_CODE, TRAF_MODE from ARRIVAL_INFO_LIST_INC_EXT;

delete from ARRIVAL_INFO_LIST using ARRIVAL_INFO_LIST_GPTMP where ARRIVAL_INFO_LIST_GPTMP.BILL_NO=ARRIVAL_INFO_LIST.BILL_NO AND ARRIVAL_INFO_LIST_GPTMP.VOYAGE_NO=ARRIVAL_INFO_LIST.VOYAGE_NO AND ARRIVAL_INFO_LIST_GPTMP.SHIP_ID=ARRIVAL_INFO_LIST.SHIP_ID AND ARRIVAL_INFO_LIST_GPTMP.I_E_DATE=ARRIVAL_INFO_LIST.I_E_DATE AND ARRIVAL_INFO_LIST_GPTMP.CUSTOMS_CODE=ARRIVAL_INFO_LIST.CUSTOMS_CODE AND ARRIVAL_INFO_LIST_GPTMP.TRAF_MODE=ARRIVAL_INFO_LIST.TRAF_MODE ;

insert into ARRIVAL_INFO_LIST(BILL_NO,VOYAGE_NO,SHIP_ID,I_E_DATE,CUSTOMS_CODE,TRAF_MODE,I_E_FLAG,VOYAGE_NO_MOD,ARRIVE_DATE,RECV_DATE,DISCHARGE_PLACE,TAL_FLAG,PACK_NO,GROSS_WT,SEQ_NO) select BILL_NO,VOYAGE_NO,SHIP_ID,I_E_DATE,CUSTOMS_CODE,TRAF_MODE,I_E_FLAG,VOYAGE_NO_MOD,ARRIVE_DATE,RECV_DATE,DISCHARGE_PLACE,TAL_FLAG,PACK_NO,GROSS_WT,SEQ_NO from ARRIVAL_INFO_LIST_INC_EXT where CMD_TYPE='I';

delete from ARRIVAL_INFO_LIST_GPTMP;

\timing
