\echo ------------------BAK_BWS_EXAM_CERT_LIST----------------
select now();
\timing
insert into BAK_BWS_EXAM_CERT_LIST_GPTMP (CMD_TYPE,BWS_EXAM_NO, G_NO) select CMD_TYPE,BWS_EXAM_NO, G_NO from BAK_BWS_EXAM_CERT_LIST_INC_EXT;

delete from BAK_BWS_EXAM_CERT_LIST using BAK_BWS_EXAM_CERT_LIST_GPTMP where BAK_BWS_EXAM_CERT_LIST_GPTMP.BWS_EXAM_NO=BAK_BWS_EXAM_CERT_LIST.BWS_EXAM_NO AND BAK_BWS_EXAM_CERT_LIST_GPTMP.G_NO=BAK_BWS_EXAM_CERT_LIST.G_NO ;

insert into BAK_BWS_EXAM_CERT_LIST(BWS_EXAM_NO,G_NO,CERT_NO,PACK_NO,GROSS_WT,BILL_NO) select BWS_EXAM_NO,G_NO,CERT_NO,PACK_NO,GROSS_WT,BILL_NO from BAK_BWS_EXAM_CERT_LIST_INC_EXT where CMD_TYPE='I';

delete from BAK_BWS_EXAM_CERT_LIST_GPTMP;

\timing
