\echo ------------------BAK_EX_FASCICLE_LIST----------------
select now();
\timing
insert into BAK_EX_FASCICLE_LIST_GPTMP (CMD_TYPE,FASCICLE_NO, CONTR_ITEM) select CMD_TYPE,FASCICLE_NO, CONTR_ITEM from BAK_EX_FASCICLE_LIST_INC_EXT;

delete from BAK_EX_FASCICLE_LIST using BAK_EX_FASCICLE_LIST_GPTMP where BAK_EX_FASCICLE_LIST_GPTMP.FASCICLE_NO=BAK_EX_FASCICLE_LIST.FASCICLE_NO AND BAK_EX_FASCICLE_LIST_GPTMP.CONTR_ITEM=BAK_EX_FASCICLE_LIST.CONTR_ITEM ;

insert into BAK_EX_FASCICLE_LIST(MANUAL_NO,FASCICLE_NO,CONTR_ITEM,APPR_QTY,FACT_QTY) select MANUAL_NO,FASCICLE_NO,CONTR_ITEM,APPR_QTY,FACT_QTY from BAK_EX_FASCICLE_LIST_INC_EXT where CMD_TYPE='I';

delete from BAK_EX_FASCICLE_LIST_GPTMP;

\timing
