\echo ------------------BAK_DCG_LIST----------------
select now();
\timing
insert into BAK_DCG_LIST_GPTMP (CMD_TYPE,DCG_NO, G_TYPE, G_NO) select CMD_TYPE,DCG_NO, G_TYPE, G_NO from BAK_DCG_LIST_INC_EXT;

delete from BAK_DCG_LIST using BAK_DCG_LIST_GPTMP where BAK_DCG_LIST_GPTMP.DCG_NO=BAK_DCG_LIST.DCG_NO AND BAK_DCG_LIST_GPTMP.G_TYPE=BAK_DCG_LIST.G_TYPE AND BAK_DCG_LIST_GPTMP.G_NO=BAK_DCG_LIST.G_NO ;

insert into BAK_DCG_LIST(DCG_NO,G_TYPE,G_NO,EX_G_NO,EMS_NO,EMS_G_NO,CODE_TS,G_NAME,G_MODEL,UNIT,QTY,UNIT_1,QTY_1,FACT_QTY,FACT_COUNT,BACK_COUNT,DEDUCT_QTY,DEDUCT_DATE,G_MARK,PAUSE_MARK,BAK_CODE_TS,MODIFY_MARK) select DCG_NO,G_TYPE,G_NO,EX_G_NO,EMS_NO,EMS_G_NO,CODE_TS,G_NAME,G_MODEL,UNIT,QTY,UNIT_1,QTY_1,FACT_QTY,FACT_COUNT,BACK_COUNT,DEDUCT_QTY,DEDUCT_DATE,G_MARK,PAUSE_MARK,BAK_CODE_TS,MODIFY_MARK from BAK_DCG_LIST_INC_EXT where CMD_TYPE='I';

delete from BAK_DCG_LIST_GPTMP;

\timing
