\echo ------------------BCK_COP_LIST----------------
select now();
\timing
insert into BCK_COP_LIST_GPTMP (CMD_TYPE,TRADE_CODE, RISK_NO, CUSTOMS_CODE) select CMD_TYPE,TRADE_CODE, RISK_NO, CUSTOMS_CODE from BCK_COP_LIST_INC_EXT;

delete from BCK_COP_LIST using BCK_COP_LIST_GPTMP where BCK_COP_LIST_GPTMP.TRADE_CODE=BCK_COP_LIST.TRADE_CODE AND BCK_COP_LIST_GPTMP.RISK_NO=BCK_COP_LIST.RISK_NO AND BCK_COP_LIST_GPTMP.CUSTOMS_CODE=BCK_COP_LIST.CUSTOMS_CODE ;

insert into BCK_COP_LIST(TRADE_CODE,RISK_NO,CUSTOMS_CODE,RISK_VALUE) select TRADE_CODE,RISK_NO,CUSTOMS_CODE,RISK_VALUE from BCK_COP_LIST_INC_EXT where CMD_TYPE='I';

delete from BCK_COP_LIST_GPTMP;

\timing
