\echo ------------------BCK_WORKFLOW----------------
select now();
\timing
insert into BCK_WORKFLOW_GPTMP (CMD_TYPE,BCK_NO, STEP_ID, OPER_ID, CREATE_DATE) select CMD_TYPE,BCK_NO, STEP_ID, OPER_ID, CREATE_DATE from BCK_WORKFLOW_INC_EXT;

delete from BCK_WORKFLOW using BCK_WORKFLOW_GPTMP where BCK_WORKFLOW_GPTMP.BCK_NO=BCK_WORKFLOW.BCK_NO AND BCK_WORKFLOW_GPTMP.STEP_ID=BCK_WORKFLOW.STEP_ID AND BCK_WORKFLOW_GPTMP.OPER_ID=BCK_WORKFLOW.OPER_ID AND BCK_WORKFLOW_GPTMP.CREATE_DATE=BCK_WORKFLOW.CREATE_DATE ;

insert into BCK_WORKFLOW(BCK_NO,CREATE_DATE,STEP_ID,OPER_ID,NOTE,OPER_ER,REALTIVE_NO) select BCK_NO,CREATE_DATE,STEP_ID,OPER_ID,NOTE,OPER_ER,REALTIVE_NO from BCK_WORKFLOW_INC_EXT where CMD_TYPE='I';

delete from BCK_WORKFLOW_GPTMP;

\timing
