\echo ------------------BCK_EXECUTOR----------------
select now();
\timing
insert into BCK_EXECUTOR_GPTMP (CMD_TYPE,BCK_NO, EXECUTOR) select CMD_TYPE,BCK_NO, EXECUTOR from BCK_EXECUTOR_INC_EXT;

delete from BCK_EXECUTOR using BCK_EXECUTOR_GPTMP where BCK_EXECUTOR_GPTMP.BCK_NO=BCK_EXECUTOR.BCK_NO AND BCK_EXECUTOR_GPTMP.EXECUTOR=BCK_EXECUTOR.EXECUTOR ;

insert into BCK_EXECUTOR(BCK_NO,EXECUTOR) select BCK_NO,EXECUTOR from BCK_EXECUTOR_INC_EXT where CMD_TYPE='I';

delete from BCK_EXECUTOR_GPTMP;

\timing
