\echo ------------------BCK_COP_PARA_LIST----------------
select now();
\timing
insert into BCK_COP_PARA_LIST_GPTMP (CMD_TYPE,RISK_NO, RISK_VALUE, CUSTOMS_CODE) select CMD_TYPE,RISK_NO, RISK_VALUE, CUSTOMS_CODE from BCK_COP_PARA_LIST_INC_EXT;

delete from BCK_COP_PARA_LIST using BCK_COP_PARA_LIST_GPTMP where BCK_COP_PARA_LIST_GPTMP.RISK_NO=BCK_COP_PARA_LIST.RISK_NO AND BCK_COP_PARA_LIST_GPTMP.RISK_VALUE=BCK_COP_PARA_LIST.RISK_VALUE AND BCK_COP_PARA_LIST_GPTMP.CUSTOMS_CODE=BCK_COP_PARA_LIST.CUSTOMS_CODE ;

insert into BCK_COP_PARA_LIST(RISK_NO,RISK_VALUE,CUSTOMS_CODE,RISK_LIST_DESC) select RISK_NO,RISK_VALUE,CUSTOMS_CODE,RISK_LIST_DESC from BCK_COP_PARA_LIST_INC_EXT where CMD_TYPE='I';

delete from BCK_COP_PARA_LIST_GPTMP;

\timing
