\echo ------------------BTI_DATA_CONTA_LIST----------------
select now();
\timing
insert into BTI_DATA_CONTA_LIST_GPTMP (CMD_TYPE,UCR_CODE, CONTAINER_ID) select CMD_TYPE,UCR_CODE, CONTAINER_ID from BTI_DATA_CONTA_LIST_INC_EXT;

delete from BTI_DATA_CONTA_LIST using BTI_DATA_CONTA_LIST_GPTMP where BTI_DATA_CONTA_LIST_GPTMP.UCR_CODE=BTI_DATA_CONTA_LIST.UCR_CODE AND BTI_DATA_CONTA_LIST_GPTMP.CONTAINER_ID=BTI_DATA_CONTA_LIST.CONTAINER_ID ;

insert into BTI_DATA_CONTA_LIST(UCR_CODE,CONTAINER_ID,SEAL_NO) select UCR_CODE,CONTAINER_ID,SEAL_NO from BTI_DATA_CONTA_LIST_INC_EXT where CMD_TYPE='I';

delete from BTI_DATA_CONTA_LIST_GPTMP;

\timing
