\echo ------------------BWS_GB_LIST----------------
select now();
\timing
insert into BWS_GB_LIST_GPTMP (CMD_TYPE,BWS_NO, G_NO) select CMD_TYPE,BWS_NO, G_NO from BWS_GB_LIST_INC_EXT;

delete from BWS_GB_LIST using BWS_GB_LIST_GPTMP where BWS_GB_LIST_GPTMP.BWS_NO=BWS_GB_LIST.BWS_NO AND BWS_GB_LIST_GPTMP.G_NO=BWS_GB_LIST.G_NO ;

insert into BWS_GB_LIST(BWS_NO,G_NO,BWS_G_NO,COP_G_NO,CODE_TS,CLASS_MARK,G_NAME,G_MODEL,UNIT,UNIT_1,UNIT_2,DEC_PRICE,CURR,COUNTRY_CODE,DUTY_MODE,USE_TYPE,MODIFY_MARK,NOTE) select BWS_NO,G_NO,BWS_G_NO,COP_G_NO,CODE_TS,CLASS_MARK,G_NAME,G_MODEL,UNIT,UNIT_1,UNIT_2,DEC_PRICE,CURR,COUNTRY_CODE,DUTY_MODE,USE_TYPE,MODIFY_MARK,NOTE from BWS_GB_LIST_INC_EXT where CMD_TYPE='I';

delete from BWS_GB_LIST_GPTMP;

\timing
