\echo ------------------BWS_EXAM_CERT_LIST----------------
select now();
\timing
insert into BWS_EXAM_CERT_LIST_GPTMP (CMD_TYPE,BWS_EXAM_NO, G_NO) select CMD_TYPE,BWS_EXAM_NO, G_NO from BWS_EXAM_CERT_LIST_INC_EXT;

delete from BWS_EXAM_CERT_LIST using BWS_EXAM_CERT_LIST_GPTMP where BWS_EXAM_CERT_LIST_GPTMP.BWS_EXAM_NO=BWS_EXAM_CERT_LIST.BWS_EXAM_NO AND BWS_EXAM_CERT_LIST_GPTMP.G_NO=BWS_EXAM_CERT_LIST.G_NO ;

insert into BWS_EXAM_CERT_LIST(BWS_EXAM_NO,G_NO,CERT_NO,PACK_NO,GROSS_WT,BILL_NO) select BWS_EXAM_NO,G_NO,CERT_NO,PACK_NO,GROSS_WT,BILL_NO from BWS_EXAM_CERT_LIST_INC_EXT where CMD_TYPE='I';

delete from BWS_EXAM_CERT_LIST_GPTMP;

\timing
