\echo ------------------BWS_EXAM_PASSCERT----------------
select now();
\timing
insert into BWS_EXAM_PASSCERT_GPTMP (CMD_TYPE,CERT_NO) select CMD_TYPE,CERT_NO from BWS_EXAM_PASSCERT_INC_EXT;

delete from BWS_EXAM_PASSCERT using BWS_EXAM_PASSCERT_GPTMP where BWS_EXAM_PASSCERT_GPTMP.CERT_NO=BWS_EXAM_PASSCERT.CERT_NO ;

insert into BWS_EXAM_PASSCERT(CERT_NO,CERT_TYPE,FLAG,FLAG1,CREATE_DATE,NOTE) select CERT_NO,CERT_TYPE,FLAG,FLAG1,CREATE_DATE,NOTE from BWS_EXAM_PASSCERT_INC_EXT where CMD_TYPE='I';

delete from BWS_EXAM_PASSCERT_GPTMP;

\timing
