\echo ------------------BWS_DCR_BILL_LIST----------------
select now();
\timing
insert into BWS_DCR_BILL_LIST_GPTMP (CMD_TYPE,BWS_NO, DCR_TIMES, G_TYPE, G_NO) select CMD_TYPE,BWS_NO, DCR_TIMES, G_TYPE, G_NO from BWS_DCR_BILL_LIST_INC_EXT;

delete from BWS_DCR_BILL_LIST using BWS_DCR_BILL_LIST_GPTMP where BWS_DCR_BILL_LIST_GPTMP.BWS_NO=BWS_DCR_BILL_LIST.BWS_NO AND BWS_DCR_BILL_LIST_GPTMP.DCR_TIMES=BWS_DCR_BILL_LIST.DCR_TIMES AND BWS_DCR_BILL_LIST_GPTMP.G_TYPE=BWS_DCR_BILL_LIST.G_TYPE AND BWS_DCR_BILL_LIST_GPTMP.G_NO=BWS_DCR_BILL_LIST.G_NO ;

insert into BWS_DCR_BILL_LIST(BWS_NO,DCR_TIMES,G_TYPE,G_NO,CUSTOMS_CODE,TRANS_MODE,DECLARE_DATE,TRANS_DATE,DU_CODE,NOTE) select BWS_NO,DCR_TIMES,G_TYPE,G_NO,CUSTOMS_CODE,TRANS_MODE,DECLARE_DATE,TRANS_DATE,DU_CODE,NOTE from BWS_DCR_BILL_LIST_INC_EXT where CMD_TYPE='I';

delete from BWS_DCR_BILL_LIST_GPTMP;

\timing
