\echo ------------------BWS_DEDUCT_LOG----------------
select now();
\timing
insert into BWS_DEDUCT_LOG_GPTMP (CMD_TYPE,BWS_ID, BWS_NO, CREATE_DATE, JOU_MARK) select CMD_TYPE,BWS_ID, BWS_NO, CREATE_DATE, JOU_MARK from BWS_DEDUCT_LOG_INC_EXT;

delete from BWS_DEDUCT_LOG using BWS_DEDUCT_LOG_GPTMP where BWS_DEDUCT_LOG_GPTMP.BWS_ID=BWS_DEDUCT_LOG.BWS_ID AND BWS_DEDUCT_LOG_GPTMP.BWS_NO=BWS_DEDUCT_LOG.BWS_NO AND BWS_DEDUCT_LOG_GPTMP.CREATE_DATE=BWS_DEDUCT_LOG.CREATE_DATE AND BWS_DEDUCT_LOG_GPTMP.JOU_MARK=BWS_DEDUCT_LOG.JOU_MARK ;

insert into BWS_DEDUCT_LOG(BWS_ID,BWS_NO,CREATE_DATE,JOU_MARK,NOTE,VERIFY_ER) select BWS_ID,BWS_NO,CREATE_DATE,JOU_MARK,NOTE,VERIFY_ER from BWS_DEDUCT_LOG_INC_EXT where CMD_TYPE='I';

delete from BWS_DEDUCT_LOG_GPTMP;

\timing
