\echo ------------------CCTS_PERFORMANCE----------------
select now();
\timing
insert into CCTS_PERFORMANCE_GPTMP (CMD_TYPE,SEQUENCE_NO) select CMD_TYPE,SEQUENCE_NO from CCTS_PERFORMANCE_INC_EXT;

delete from CCTS_PERFORMANCE using CCTS_PERFORMANCE_GPTMP where CCTS_PERFORMANCE_GPTMP.SEQUENCE_NO=CCTS_PERFORMANCE.SEQUENCE_NO ;

insert into CCTS_PERFORMANCE(SEQUENCE_NO,FORM_TYPE,ENTRY_ID,CUSTOMS_CODE,CREATE_DATE,DEL_DIGIT,MODI_DIGIT,REJECT_DIGIT,VAL_DIGIT,CHK_DIGIT,FIT_DIGIT,SPARE_DIGIT,VAL_TOTAL,NOTE) select SEQUENCE_NO,FORM_TYPE,ENTRY_ID,CUSTOMS_CODE,CREATE_DATE,DEL_DIGIT,MODI_DIGIT,REJECT_DIGIT,VAL_DIGIT,CHK_DIGIT,FIT_DIGIT,SPARE_DIGIT,VAL_TOTAL,NOTE from CCTS_PERFORMANCE_INC_EXT where CMD_TYPE='I';

delete from CCTS_PERFORMANCE_GPTMP;

\timing
