\echo ------------------CDL_COMMODITY----------------
select now();
\timing
insert into CDL_COMMODITY_GPTMP (CMD_TYPE,RECORDS_NO, G_NO) select CMD_TYPE,RECORDS_NO, G_NO from CDL_COMMODITY_INC_EXT;

delete from CDL_COMMODITY using CDL_COMMODITY_GPTMP where CDL_COMMODITY_GPTMP.RECORDS_NO=CDL_COMMODITY.RECORDS_NO AND CDL_COMMODITY_GPTMP.G_NO=CDL_COMMODITY.G_NO ;

insert into CDL_COMMODITY(RECORDS_NO,PRE_RECORDS_NO,TRADE_CO,G_NO,FIT_FLAG,CODE_TS,G_NAME,G_MODEL,G_UNIT,DECL_PRICE,TRADE_CURR,I_E_FLAG,ORIGIN_COUNTRY,DISTRICT_CODE,LICENSE_NO,LICENSE_COUNT,LICENSE_DATE,MOD_TYPE,CUSTOMS_CODE) select RECORDS_NO,PRE_RECORDS_NO,TRADE_CO,G_NO,FIT_FLAG,CODE_TS,G_NAME,G_MODEL,G_UNIT,DECL_PRICE,TRADE_CURR,I_E_FLAG,ORIGIN_COUNTRY,DISTRICT_CODE,LICENSE_NO,LICENSE_COUNT,LICENSE_DATE,MOD_TYPE,CUSTOMS_CODE from CDL_COMMODITY_INC_EXT where CMD_TYPE='I';

delete from CDL_COMMODITY_GPTMP;

\timing
