\echo ------------------CDL_COMPANY----------------
select now();
\timing
insert into CDL_COMPANY_GPTMP (CMD_TYPE,TRADE_CO, CUSTOMS_CODE, TRADE_BONDED_FLAG) select CMD_TYPE,TRADE_CO, CUSTOMS_CODE, TRADE_BONDED_FLAG from CDL_COMPANY_INC_EXT;

delete from CDL_COMPANY using CDL_COMPANY_GPTMP where CDL_COMPANY_GPTMP.TRADE_CO=CDL_COMPANY.TRADE_CO AND CDL_COMPANY_GPTMP.CUSTOMS_CODE=CDL_COMPANY.CUSTOMS_CODE AND CDL_COMPANY_GPTMP.TRADE_BONDED_FLAG=CDL_COMPANY.TRADE_BONDED_FLAG ;

insert into CDL_COMPANY(TRADE_CO,TRADE_NAME,CUSTOMS_CODE,APP_MOD_FLAG,TRADE_BONDED_FLAG,GRT_TYPE,GRT_PRICE,GRT_DATE,APPROVE_DATE,IE_COUNT,PRE_COP_NO) select TRADE_CO,TRADE_NAME,CUSTOMS_CODE,APP_MOD_FLAG,TRADE_BONDED_FLAG,GRT_TYPE,GRT_PRICE,GRT_DATE,APPROVE_DATE,IE_COUNT,PRE_COP_NO from CDL_COMPANY_INC_EXT where CMD_TYPE='I';

delete from CDL_COMPANY_GPTMP;

\timing
