\echo ------------------CDL_MODI_LOG----------------
select now();
\timing
insert into CDL_MODI_LOG_GPTMP (CMD_TYPE,LIST_NO, OP_TIME, MODI_TYPE, ITEM_NAME) select CMD_TYPE,LIST_NO, OP_TIME, MODI_TYPE, ITEM_NAME from CDL_MODI_LOG_INC_EXT;

delete from CDL_MODI_LOG using CDL_MODI_LOG_GPTMP where CDL_MODI_LOG_GPTMP.LIST_NO=CDL_MODI_LOG.LIST_NO AND CDL_MODI_LOG_GPTMP.OP_TIME=CDL_MODI_LOG.OP_TIME AND CDL_MODI_LOG_GPTMP.MODI_TYPE=CDL_MODI_LOG.MODI_TYPE AND CDL_MODI_LOG_GPTMP.ITEM_NAME=CDL_MODI_LOG.ITEM_NAME ;

insert into CDL_MODI_LOG(LIST_NO,OP_TIME,MODI_TYPE,ITEM_NAME,ITEM_SOURCE,ITEM_CURRENT,NOTES) select LIST_NO,OP_TIME,MODI_TYPE,ITEM_NAME,ITEM_SOURCE,ITEM_CURRENT,NOTES from CDL_MODI_LOG_INC_EXT where CMD_TYPE='I';

delete from CDL_MODI_LOG_GPTMP;

\timing
