\echo ------------------CDL_DEL_CONTAINER_LOG----------------
select now();
\timing
insert into CDL_DEL_CONTAINER_LOG_GPTMP (CMD_TYPE,LIST_NO, CONTAINER_ID, CONTAINER_WT) select CMD_TYPE,LIST_NO, CONTAINER_ID, CONTAINER_WT from CDL_DEL_CONTAINER_LOG_INC_EXT;

delete from CDL_DEL_CONTAINER_LOG using CDL_DEL_CONTAINER_LOG_GPTMP where CDL_DEL_CONTAINER_LOG_GPTMP.LIST_NO=CDL_DEL_CONTAINER_LOG.LIST_NO AND CDL_DEL_CONTAINER_LOG_GPTMP.CONTAINER_ID=CDL_DEL_CONTAINER_LOG.CONTAINER_ID AND CDL_DEL_CONTAINER_LOG_GPTMP.CONTAINER_WT=CDL_DEL_CONTAINER_LOG.CONTAINER_WT ;

insert into CDL_DEL_CONTAINER_LOG(LIST_NO,CONTAINER_ID,CONTAINER_WT) select LIST_NO,CONTAINER_ID,CONTAINER_WT from CDL_DEL_CONTAINER_LOG_INC_EXT where CMD_TYPE='I';

delete from CDL_DEL_CONTAINER_LOG_GPTMP;

\timing
