\echo ------------------CDL_WORKFLOW----------------
select now();
\timing
insert into CDL_WORKFLOW_GPTMP (CMD_TYPE,LIST_NO, STEP_ID, CREATE_DATE) select CMD_TYPE,LIST_NO, STEP_ID, CREATE_DATE from CDL_WORKFLOW_INC_EXT;

delete from CDL_WORKFLOW using CDL_WORKFLOW_GPTMP where CDL_WORKFLOW_GPTMP.LIST_NO=CDL_WORKFLOW.LIST_NO AND CDL_WORKFLOW_GPTMP.STEP_ID=CDL_WORKFLOW.STEP_ID AND CDL_WORKFLOW_GPTMP.CREATE_DATE=CDL_WORKFLOW.CREATE_DATE ;

insert into CDL_WORKFLOW(LIST_NO,STEP_ID,CREATE_DATE,PROC_POS,STATUS_CODE,PROC_ER,PROC_RESULT,PREV_POS,PREV_ER,RECHK_MARK,RECHK_COMM) select LIST_NO,STEP_ID,CREATE_DATE,PROC_POS,STATUS_CODE,PROC_ER,PROC_RESULT,PREV_POS,PREV_ER,RECHK_MARK,RECHK_COMM from CDL_WORKFLOW_INC_EXT where CMD_TYPE='I';

delete from CDL_WORKFLOW_GPTMP;

\timing
