\echo ------------------CDL_EMS_DEDUCT_LOG----------------
select now();
\timing
insert into CDL_EMS_DEDUCT_LOG_GPTMP (CMD_TYPE,ENTRY_ID, EMS_NO, CREATE_DATE, JOU_MARK) select CMD_TYPE,ENTRY_ID, EMS_NO, CREATE_DATE, JOU_MARK from CDL_EMS_DEDUCT_LOG_INC_EXT;

delete from CDL_EMS_DEDUCT_LOG using CDL_EMS_DEDUCT_LOG_GPTMP where CDL_EMS_DEDUCT_LOG_GPTMP.ENTRY_ID=CDL_EMS_DEDUCT_LOG.ENTRY_ID AND CDL_EMS_DEDUCT_LOG_GPTMP.EMS_NO=CDL_EMS_DEDUCT_LOG.EMS_NO AND CDL_EMS_DEDUCT_LOG_GPTMP.CREATE_DATE=CDL_EMS_DEDUCT_LOG.CREATE_DATE AND CDL_EMS_DEDUCT_LOG_GPTMP.JOU_MARK=CDL_EMS_DEDUCT_LOG.JOU_MARK ;

insert into CDL_EMS_DEDUCT_LOG(ENTRY_ID,EMS_NO,CREATE_DATE,JOU_MARK,NOTE,VERIFY_ER) select ENTRY_ID,EMS_NO,CREATE_DATE,JOU_MARK,NOTE,VERIFY_ER from CDL_EMS_DEDUCT_LOG_INC_EXT where CMD_TYPE='I';

delete from CDL_EMS_DEDUCT_LOG_GPTMP;

\timing
