\echo ------------------CDL_DEL_CERTIFICATE_LOG----------------
select now();
\timing
insert into CDL_DEL_CERTIFICATE_LOG_GPTMP (CMD_TYPE,LIST_NO, DOCU_CODE, CERT_CODE) select CMD_TYPE,LIST_NO, DOCU_CODE, CERT_CODE from CDL_DEL_CERTIFICATE_LOG_INC_EXT;

delete from CDL_DEL_CERTIFICATE_LOG using CDL_DEL_CERTIFICATE_LOG_GPTMP where CDL_DEL_CERTIFICATE_LOG_GPTMP.LIST_NO=CDL_DEL_CERTIFICATE_LOG.LIST_NO AND CDL_DEL_CERTIFICATE_LOG_GPTMP.DOCU_CODE=CDL_DEL_CERTIFICATE_LOG.DOCU_CODE AND CDL_DEL_CERTIFICATE_LOG_GPTMP.CERT_CODE=CDL_DEL_CERTIFICATE_LOG.CERT_CODE ;

insert into CDL_DEL_CERTIFICATE_LOG(LIST_NO,DOCU_CODE,CERT_CODE) select LIST_NO,DOCU_CODE,CERT_CODE from CDL_DEL_CERTIFICATE_LOG_INC_EXT where CMD_TYPE='I';

delete from CDL_DEL_CERTIFICATE_LOG_GPTMP;

\timing
