\echo ------------------CDL_CERTIFICATE----------------
select now();
\timing
insert into CDL_CERTIFICATE_GPTMP (CMD_TYPE,LIST_NO, DOCU_CODE, CERT_CODE) select CMD_TYPE,LIST_NO, DOCU_CODE, CERT_CODE from CDL_CERTIFICATE_INC_EXT;

delete from CDL_CERTIFICATE using CDL_CERTIFICATE_GPTMP where CDL_CERTIFICATE_GPTMP.LIST_NO=CDL_CERTIFICATE.LIST_NO AND CDL_CERTIFICATE_GPTMP.DOCU_CODE=CDL_CERTIFICATE.DOCU_CODE AND CDL_CERTIFICATE_GPTMP.CERT_CODE=CDL_CERTIFICATE.CERT_CODE ;

insert into CDL_CERTIFICATE(LIST_NO,DOCU_CODE,CERT_CODE) select LIST_NO,DOCU_CODE,CERT_CODE from CDL_CERTIFICATE_INC_EXT where CMD_TYPE='I';

delete from CDL_CERTIFICATE_GPTMP;

\timing
