\echo ------------------CDL_HEAD----------------
select now();
\timing
insert into CDL_HEAD_GPTMP (CMD_TYPE,LIST_NO) select CMD_TYPE,LIST_NO from CDL_HEAD_INC_EXT;

delete from CDL_HEAD using CDL_HEAD_GPTMP where CDL_HEAD_GPTMP.LIST_NO=CDL_HEAD.LIST_NO ;

insert into CDL_HEAD(LIST_NO,PRE_LIST_NO,I_E_FLAG,I_E_PORT,I_E_DATE,D_DATE,MANUAL_NO,TRADE_CO,TRADE_NAME,OWNER_CODE,OWNER_NAME,TRAF_MODE,TRAF_NAME,VOYAGE_NO,BILL_NO,TRADE_MODE,LICENSE_NO,TRADE_COUNTRY,DESTINATION_PORT,PACK_NO,WRAP_TYPE,GROSS_WT,NET_WT,NOTE_S,INPUT_NO,INPUT_CO,INPUT_NAME,AGENT_CODE,AGENT_NAME,DECL_PORT,INPUT_DATE,CTR_NOTES,STATUS_RESULT,IS_DECL,MODI_NO,EDI_REMARK,HASH_SIGN,EXCHANGE_RATE,RTX_DATE) select LIST_NO,PRE_LIST_NO,I_E_FLAG,I_E_PORT,I_E_DATE,D_DATE,MANUAL_NO,TRADE_CO,TRADE_NAME,OWNER_CODE,OWNER_NAME,TRAF_MODE,TRAF_NAME,VOYAGE_NO,BILL_NO,TRADE_MODE,LICENSE_NO,TRADE_COUNTRY,DESTINATION_PORT,PACK_NO,WRAP_TYPE,GROSS_WT,NET_WT,NOTE_S,INPUT_NO,INPUT_CO,INPUT_NAME,AGENT_CODE,AGENT_NAME,DECL_PORT,INPUT_DATE,CTR_NOTES,STATUS_RESULT,IS_DECL,MODI_NO,EDI_REMARK,HASH_SIGN,EXCHANGE_RATE,RTX_DATE from CDL_HEAD_INC_EXT where CMD_TYPE='I';

delete from CDL_HEAD_GPTMP;

\timing
