\echo ------------------CDL_STATUS_DETAIL----------------
select now();
\timing
insert into CDL_STATUS_DETAIL_GPTMP (CMD_TYPE,LIST_NO, DETAIL_COUNT) select CMD_TYPE,LIST_NO, DETAIL_COUNT from CDL_STATUS_DETAIL_INC_EXT;

delete from CDL_STATUS_DETAIL using CDL_STATUS_DETAIL_GPTMP where CDL_STATUS_DETAIL_GPTMP.LIST_NO=CDL_STATUS_DETAIL.LIST_NO AND CDL_STATUS_DETAIL_GPTMP.DETAIL_COUNT=CDL_STATUS_DETAIL.DETAIL_COUNT ;

insert into CDL_STATUS_DETAIL(LIST_NO,DETAIL_COUNT,STATUS_NUMBER,STATUS_RESULT,STATUS_DETAIL) select LIST_NO,DETAIL_COUNT,STATUS_NUMBER,STATUS_RESULT,STATUS_DETAIL from CDL_STATUS_DETAIL_INC_EXT where CMD_TYPE='I';

delete from CDL_STATUS_DETAIL_GPTMP;

\timing
