\echo ------------------CDL_COMP_COMM_MODIFY_LOG----------------
select now();
\timing
insert into CDL_COMP_COMM_MODIFY_LOG_GPTMP (CMD_TYPE,TRADE_CO, OP_TIME, MODI_TYPE, ITEM_NAME) select CMD_TYPE,TRADE_CO, OP_TIME, MODI_TYPE, ITEM_NAME from CDL_COMP_COMM_MODIFY_LOG_INC_EXT;

delete from CDL_COMP_COMM_MODIFY_LOG using CDL_COMP_COMM_MODIFY_LOG_GPTMP where CDL_COMP_COMM_MODIFY_LOG_GPTMP.TRADE_CO=CDL_COMP_COMM_MODIFY_LOG.TRADE_CO AND CDL_COMP_COMM_MODIFY_LOG_GPTMP.OP_TIME=CDL_COMP_COMM_MODIFY_LOG.OP_TIME AND CDL_COMP_COMM_MODIFY_LOG_GPTMP.MODI_TYPE=CDL_COMP_COMM_MODIFY_LOG.MODI_TYPE AND CDL_COMP_COMM_MODIFY_LOG_GPTMP.ITEM_NAME=CDL_COMP_COMM_MODIFY_LOG.ITEM_NAME ;

insert into CDL_COMP_COMM_MODIFY_LOG(TRADE_CO,RECORDS_NO,OP_TIME,MODI_TYPE,ITEM_NAME,ITEM_SOURCE,ITEM_CURRENT,NOTES,CUSTOMS_CODE) select TRADE_CO,RECORDS_NO,OP_TIME,MODI_TYPE,ITEM_NAME,ITEM_SOURCE,ITEM_CURRENT,NOTES,CUSTOMS_CODE from CDL_COMP_COMM_MODIFY_LOG_INC_EXT where CMD_TYPE='I';

delete from CDL_COMP_COMM_MODIFY_LOG_GPTMP;

\timing
