\echo ------------------CHK_COP_RATIO----------------
select now();
\timing
insert into CHK_COP_RATIO_GPTMP (CMD_TYPE,CORP_CODE) select CMD_TYPE,CORP_CODE from CHK_COP_RATIO_INC_EXT;

delete from CHK_COP_RATIO using CHK_COP_RATIO_GPTMP where CHK_COP_RATIO_GPTMP.CORP_CODE=CHK_COP_RATIO.CORP_CODE ;

insert into CHK_COP_RATIO(CORP_CODE,CORP_NAME,CUSTOMS_CODE,RATIO_NUM) select CORP_CODE,CORP_NAME,CUSTOMS_CODE,RATIO_NUM from CHK_COP_RATIO_INC_EXT where CMD_TYPE='I';

delete from CHK_COP_RATIO_GPTMP;

\timing
