\echo ------------------CIC_SEND_REL----------------
select now();
\timing
insert into CIC_SEND_REL_GPTMP (CMD_TYPE,CPT_NO, SEND_TIMES) select CMD_TYPE,CPT_NO, SEND_TIMES from CIC_SEND_REL_INC_EXT;

delete from CIC_SEND_REL using CIC_SEND_REL_GPTMP where CIC_SEND_REL_GPTMP.CPT_NO=CIC_SEND_REL.CPT_NO AND CIC_SEND_REL_GPTMP.SEND_TIMES=CIC_SEND_REL.SEND_TIMES ;

insert into CIC_SEND_REL(CPT_NO,CIC_NO,SEND_TIMES,SEND_ER,SEND_TYPE,SEND_DATE,RECV_DATE,RECV_FLAG,NOTE) select CPT_NO,CIC_NO,SEND_TIMES,SEND_ER,SEND_TYPE,SEND_DATE,RECV_DATE,RECV_FLAG,NOTE from CIC_SEND_REL_INC_EXT where CMD_TYPE='I';

delete from CIC_SEND_REL_GPTMP;

\timing
