\echo ------------------CLC_GPR_RATIO_BAK----------------
select now();
\timing
insert into CLC_GPR_RATIO_BAK_GPTMP (CMD_TYPE,CUSTOMS_CODE, I_E_FLAG, OP_TIME) select CMD_TYPE,CUSTOMS_CODE, I_E_FLAG, OP_TIME from CLC_GPR_RATIO_BAK_INC_EXT;

delete from CLC_GPR_RATIO_BAK using CLC_GPR_RATIO_BAK_GPTMP where CLC_GPR_RATIO_BAK_GPTMP.CUSTOMS_CODE=CLC_GPR_RATIO_BAK.CUSTOMS_CODE AND CLC_GPR_RATIO_BAK_GPTMP.I_E_FLAG=CLC_GPR_RATIO_BAK.I_E_FLAG AND CLC_GPR_RATIO_BAK_GPTMP.OP_TIME=CLC_GPR_RATIO_BAK.OP_TIME ;

insert into CLC_GPR_RATIO_BAK(CUSTOMS_CODE,I_E_FLAG,RATIO_NUM,OP_TIME,OP_ER,OP_CUSTOMS) select CUSTOMS_CODE,I_E_FLAG,RATIO_NUM,OP_TIME,OP_ER,OP_CUSTOMS from CLC_GPR_RATIO_BAK_INC_EXT where CMD_TYPE='I';

delete from CLC_GPR_RATIO_BAK_GPTMP;

\timing
