\echo ------------------CO_CLASS_REL----------------
select now();
\timing
insert into CO_CLASS_REL_GPTMP (CMD_TYPE,TRADE_CO, CLASS_NO) select CMD_TYPE,TRADE_CO, CLASS_NO from CO_CLASS_REL_INC_EXT;

delete from CO_CLASS_REL using CO_CLASS_REL_GPTMP where CO_CLASS_REL_GPTMP.TRADE_CO=CO_CLASS_REL.TRADE_CO AND CO_CLASS_REL_GPTMP.CLASS_NO=CO_CLASS_REL.CLASS_NO ;

insert into CO_CLASS_REL(TRADE_CO,CLASS_NO,CLASS_SOURCE,CLASS_DEST,CLASS_OPER_CODE,CLASS_OPER_DATE,CLASS_DPT_CODE,CLASS_DPT_DATE,CLASS_NOTE) select TRADE_CO,CLASS_NO,CLASS_SOURCE,CLASS_DEST,CLASS_OPER_CODE,CLASS_OPER_DATE,CLASS_DPT_CODE,CLASS_DPT_DATE,CLASS_NOTE from CO_CLASS_REL_INC_EXT where CMD_TYPE='I';

delete from CO_CLASS_REL_GPTMP;

\timing
