\echo ------------------CONSUME_DB----------------
select now();
\timing
insert into CONSUME_DB_GPTMP (CMD_TYPE,EX_CODE_TS, EX_NO, IM_CODE_TS, IM_NO) select CMD_TYPE,EX_CODE_TS, EX_NO, IM_CODE_TS, IM_NO from CONSUME_DB_INC_EXT;

delete from CONSUME_DB using CONSUME_DB_GPTMP where CONSUME_DB_GPTMP.EX_CODE_TS=CONSUME_DB.EX_CODE_TS AND CONSUME_DB_GPTMP.EX_NO=CONSUME_DB.EX_NO AND CONSUME_DB_GPTMP.IM_CODE_TS=CONSUME_DB.IM_CODE_TS AND CONSUME_DB_GPTMP.IM_NO=CONSUME_DB.IM_NO ;

insert into CONSUME_DB(EX_CODE_TS,EX_NO,IM_CODE_TS,IM_NO,CONSUME_RATIO,DAMAGE_RATIO,CONSUME_RANGE,CONSUME_NOTE,G_CLASS,INPUT_DATE,LIMIT_DATE) select EX_CODE_TS,EX_NO,IM_CODE_TS,IM_NO,CONSUME_RATIO,DAMAGE_RATIO,CONSUME_RANGE,CONSUME_NOTE,G_CLASS,INPUT_DATE,LIMIT_DATE from CONSUME_DB_INC_EXT where CMD_TYPE='I';

delete from CONSUME_DB_GPTMP;

\timing
