\echo ------------------CONSUME----------------
select now();
\timing
insert into CONSUME_GPTMP (CMD_TYPE,MANUAL_NO, CONTR_ITEM, EX_NO) select CMD_TYPE,MANUAL_NO, CONTR_ITEM, EX_NO from CONSUME_INC_EXT;

delete from CONSUME using CONSUME_GPTMP where CONSUME_GPTMP.MANUAL_NO=CONSUME.MANUAL_NO AND CONSUME_GPTMP.CONTR_ITEM=CONSUME.CONTR_ITEM AND CONSUME_GPTMP.EX_NO=CONSUME.EX_NO ;

insert into CONSUME(MANUAL_NO,CONTR_ITEM,EX_NO,APPR_CONSUME,APPR_DAMAGE,DECL_CONSUME,DECL_DAMAGE) select MANUAL_NO,CONTR_ITEM,EX_NO,APPR_CONSUME,APPR_DAMAGE,DECL_CONSUME,DECL_DAMAGE from CONSUME_INC_EXT where CMD_TYPE='I';

delete from CONSUME_GPTMP;

\timing
