\echo ------------------CONVEYANCE----------------
select now();
\timing
insert into CONVEYANCE_GPTMP (CMD_TYPE,SHIP_ID, TRAF_MODE) select CMD_TYPE,SHIP_ID, TRAF_MODE from CONVEYANCE_INC_EXT;

delete from CONVEYANCE using CONVEYANCE_GPTMP where CONVEYANCE_GPTMP.SHIP_ID=CONVEYANCE.SHIP_ID AND CONVEYANCE_GPTMP.TRAF_MODE=CONVEYANCE.TRAF_MODE ;

insert into CONVEYANCE(SHIP_ID,TRAF_MODE,SHIP_NAME_EN,SHIP_NAME_CN,SHIP_NAME_ORI,COUNTRY_CODE,SHIP_TYPE,SHIP_ATTR,SHIP_USE_CODE,TONNAGE,CREATE_DATE,CREATE_ER,CUSTOMS_CODE) select SHIP_ID,TRAF_MODE,SHIP_NAME_EN,SHIP_NAME_CN,SHIP_NAME_ORI,COUNTRY_CODE,SHIP_TYPE,SHIP_ATTR,SHIP_USE_CODE,TONNAGE,CREATE_DATE,CREATE_ER,CUSTOMS_CODE from CONVEYANCE_INC_EXT where CMD_TYPE='I';

delete from CONVEYANCE_GPTMP;

\timing
