\echo ------------------CONVEYANCE_SEGMENT----------------
select now();
\timing
insert into CONVEYANCE_SEGMENT_GPTMP (CMD_TYPE,SHIP_ID, TRAF_MODE, VOYAGE_NO, I_E_FLAG, LOAD_PORT, DESTINATION_PORT, CUSTOMS_CODE, I_E_DATE) select CMD_TYPE,SHIP_ID, TRAF_MODE, VOYAGE_NO, I_E_FLAG, LOAD_PORT, DESTINATION_PORT, CUSTOMS_CODE, I_E_DATE from CONVEYANCE_SEGMENT_INC_EXT;

delete from CONVEYANCE_SEGMENT using CONVEYANCE_SEGMENT_GPTMP where CONVEYANCE_SEGMENT_GPTMP.SHIP_ID=CONVEYANCE_SEGMENT.SHIP_ID AND CONVEYANCE_SEGMENT_GPTMP.TRAF_MODE=CONVEYANCE_SEGMENT.TRAF_MODE AND CONVEYANCE_SEGMENT_GPTMP.VOYAGE_NO=CONVEYANCE_SEGMENT.VOYAGE_NO AND CONVEYANCE_SEGMENT_GPTMP.I_E_FLAG=CONVEYANCE_SEGMENT.I_E_FLAG AND CONVEYANCE_SEGMENT_GPTMP.LOAD_PORT=CONVEYANCE_SEGMENT.LOAD_PORT AND CONVEYANCE_SEGMENT_GPTMP.DESTINATION_PORT=CONVEYANCE_SEGMENT.DESTINATION_PORT AND CONVEYANCE_SEGMENT_GPTMP.CUSTOMS_CODE=CONVEYANCE_SEGMENT.CUSTOMS_CODE AND CONVEYANCE_SEGMENT_GPTMP.I_E_DATE=CONVEYANCE_SEGMENT.I_E_DATE ;

insert into CONVEYANCE_SEGMENT(SHIP_ID,TRAF_MODE,VOYAGE_NO,I_E_FLAG,LOAD_PORT,DESTINATION_PORT,CUSTOMS_CODE,I_E_DATE) select SHIP_ID,TRAF_MODE,VOYAGE_NO,I_E_FLAG,LOAD_PORT,DESTINATION_PORT,CUSTOMS_CODE,I_E_DATE from CONVEYANCE_SEGMENT_INC_EXT where CMD_TYPE='I';

delete from CONVEYANCE_SEGMENT_GPTMP;

\timing
