\echo ------------------COP_SPEC_REL----------------
select now();
\timing
insert into COP_SPEC_REL_GPTMP (CMD_TYPE,ENTRY_ID, AUTH_ID) select CMD_TYPE,ENTRY_ID, AUTH_ID from COP_SPEC_REL_INC_EXT;

delete from COP_SPEC_REL using COP_SPEC_REL_GPTMP where COP_SPEC_REL_GPTMP.ENTRY_ID=COP_SPEC_REL.ENTRY_ID AND COP_SPEC_REL_GPTMP.AUTH_ID=COP_SPEC_REL.AUTH_ID ;

insert into COP_SPEC_REL(ENTRY_ID,STEP_STATUS,PASS_CODE,AUTH_ID,AUTH_DATETIME,AUTH_PORT,AUTH_NOTE,PASS_ID,PASS_DATETIME,PASS_PORT) select ENTRY_ID,STEP_STATUS,PASS_CODE,AUTH_ID,AUTH_DATETIME,AUTH_PORT,AUTH_NOTE,PASS_ID,PASS_DATETIME,PASS_PORT from COP_SPEC_REL_INC_EXT where CMD_TYPE='I';

delete from COP_SPEC_REL_GPTMP;

\timing
