\echo ------------------COPLOG_DELETE_REL----------------
select now();
\timing
insert into COPLOG_DELETE_REL_GPTMP (CMD_TYPE,LOG_ID) select CMD_TYPE,LOG_ID from COPLOG_DELETE_REL_INC_EXT;

delete from COPLOG_DELETE_REL using COPLOG_DELETE_REL_GPTMP where COPLOG_DELETE_REL_GPTMP.LOG_ID=COPLOG_DELETE_REL.LOG_ID ;

insert into COPLOG_DELETE_REL(LOG_ID,LOG_DATE,LOG_OPER_ID,LOG_CUSTOMS_CODE,LOG_COMPUTER_NAME,LOG_MODE,TRADE_CO,REG_CO,FULL_NAME,CUSTOMS_CODE,CO_CLASS,CREDIT_MAR,EXAM_SCORE,VALID_DATE,ACCO_BANK,ACCO_NO,MAIL_CO,BROKER_TYPE,RG_DATE,LICENSE_ID,EN_FULL_CO,EN_ADDR_CO,ADDR_CO,BUSI_TYPE,CONTAC_CO,TEL_CO,APPR_DEP,APPR_ID,LAW_MAN,LAW_MAN_TEL,INV_FUND_T,ID_NUMBER,RG_FUND,CURR_CODE,TAXY_RG_NO,CHK_DATE,CO_TYPE,BREAK_LAW_TIME1,BREAK_LAW_TIME2,IN_RATIO,INSPECT_TIME,SPE_CO,TRADE_AREA,MAIN_PRO,ACT_FUND,DUTY_FREE_AMT,COP_FLAG,COP_NOTE,PRE_TRADE_CO,CHK_OPER_CODE,CHK_OPER_FLAG,CHK_OPER_DATE,CHK_DPT_CODE,CHK_DPT_FLAG,CHK_DPT_DATE,CHK_MASTER_CODE,CHK_MASTER_FLAG,CHK_MASTER_DATE,CHK_EARNEST_MON,CHK_CODE,COP_GB_CODE,COP_IO_CODE,COP_PASS_CODE,COP_END_DATE,COP_MODIFY_DATE,COP_RANGE) select LOG_ID,LOG_DATE,LOG_OPER_ID,LOG_CUSTOMS_CODE,LOG_COMPUTER_NAME,LOG_MODE,TRADE_CO,REG_CO,FULL_NAME,CUSTOMS_CODE,CO_CLASS,CREDIT_MAR,EXAM_SCORE,VALID_DATE,ACCO_BANK,ACCO_NO,MAIL_CO,BROKER_TYPE,RG_DATE,LICENSE_ID,EN_FULL_CO,EN_ADDR_CO,ADDR_CO,BUSI_TYPE,CONTAC_CO,TEL_CO,APPR_DEP,APPR_ID,LAW_MAN,LAW_MAN_TEL,INV_FUND_T,ID_NUMBER,RG_FUND,CURR_CODE,TAXY_RG_NO,CHK_DATE,CO_TYPE,BREAK_LAW_TIME1,BREAK_LAW_TIME2,IN_RATIO,INSPECT_TIME,SPE_CO,TRADE_AREA,MAIN_PRO,ACT_FUND,DUTY_FREE_AMT,COP_FLAG,COP_NOTE,PRE_TRADE_CO,CHK_OPER_CODE,CHK_OPER_FLAG,CHK_OPER_DATE,CHK_DPT_CODE,CHK_DPT_FLAG,CHK_DPT_DATE,CHK_MASTER_CODE,CHK_MASTER_FLAG,CHK_MASTER_DATE,CHK_EARNEST_MON,CHK_CODE,COP_GB_CODE,COP_IO_CODE,COP_PASS_CODE,COP_END_DATE,COP_MODIFY_DATE,COP_RANGE from COPLOG_DELETE_REL_INC_EXT where CMD_TYPE='I';

delete from COPLOG_DELETE_REL_GPTMP;

\timing
