\echo ------------------CORP_TABLE----------------
select now();
\timing
insert into CORP_TABLE_GPTMP (CMD_TYPE,FIELD_ID, TABLE_ID) select CMD_TYPE,FIELD_ID, TABLE_ID from CORP_TABLE_INC_EXT;

delete from CORP_TABLE using CORP_TABLE_GPTMP where CORP_TABLE_GPTMP.FIELD_ID=CORP_TABLE.FIELD_ID AND CORP_TABLE_GPTMP.TABLE_ID=CORP_TABLE.TABLE_ID ;

insert into CORP_TABLE(FIELD_ID,TABLE_ID,TABLE_NAME,FIELD_NAME) select FIELD_ID,TABLE_ID,TABLE_NAME,FIELD_NAME from CORP_TABLE_INC_EXT where CMD_TYPE='I';

delete from CORP_TABLE_GPTMP;

\timing
