\echo ------------------COUNTER_TABLE----------------
select now();
\timing
insert into COUNTER_TABLE_GPTMP (CMD_TYPE,COUNTER_TYPE, CUSTOMS_CODE, I_E_FLAG, C_DATE) select CMD_TYPE,COUNTER_TYPE, CUSTOMS_CODE, I_E_FLAG, C_DATE from COUNTER_TABLE_INC_EXT;

delete from COUNTER_TABLE using COUNTER_TABLE_GPTMP where COUNTER_TABLE_GPTMP.COUNTER_TYPE=COUNTER_TABLE.COUNTER_TYPE AND COUNTER_TABLE_GPTMP.CUSTOMS_CODE=COUNTER_TABLE.CUSTOMS_CODE AND COUNTER_TABLE_GPTMP.I_E_FLAG=COUNTER_TABLE.I_E_FLAG AND COUNTER_TABLE_GPTMP.C_DATE=COUNTER_TABLE.C_DATE ;

insert into COUNTER_TABLE(COUNTER_TYPE,CUSTOMS_CODE,I_E_FLAG,C_DATE,COUNTER) select COUNTER_TYPE,CUSTOMS_CODE,I_E_FLAG,C_DATE,COUNTER from COUNTER_TABLE_INC_EXT where CMD_TYPE='I';

delete from COUNTER_TABLE_GPTMP;

\timing
