\echo ------------------CREDIT_INFO----------------
select now();
\timing
insert into CREDIT_INFO_GPTMP (CMD_TYPE,RPTNO) select CMD_TYPE,RPTNO from CREDIT_INFO_INC_EXT;

delete from CREDIT_INFO using CREDIT_INFO_GPTMP where CREDIT_INFO_GPTMP.RPTNO=CREDIT_INFO.RPTNO ;

insert into CREDIT_INFO(RPTNO,RPTUSER,TRADE_CO,RCVNAME,ACTUCCY,ACTUAMT,CSTSETCODE,COUNTRYCODE,CSTCNTRCTNO,INVOICENO,LCBGNO,RECV_DATE) select RPTNO,RPTUSER,TRADE_CO,RCVNAME,ACTUCCY,ACTUAMT,CSTSETCODE,COUNTRYCODE,CSTCNTRCTNO,INVOICENO,LCBGNO,RECV_DATE from CREDIT_INFO_INC_EXT where CMD_TYPE='I';

delete from CREDIT_INFO_GPTMP;

\timing
