\echo ------------------CUSTOMS_ESEAL_CONFIG----------------
select now();
\timing
insert into CUSTOMS_ESEAL_CONFIG_GPTMP (CMD_TYPE,CUSTOMS_CODE, FLAG_TYPE, I_E_FLAG) select CMD_TYPE,CUSTOMS_CODE, FLAG_TYPE, I_E_FLAG from CUSTOMS_ESEAL_CONFIG_INC_EXT;

delete from CUSTOMS_ESEAL_CONFIG using CUSTOMS_ESEAL_CONFIG_GPTMP where CUSTOMS_ESEAL_CONFIG_GPTMP.CUSTOMS_CODE=CUSTOMS_ESEAL_CONFIG.CUSTOMS_CODE AND CUSTOMS_ESEAL_CONFIG_GPTMP.FLAG_TYPE=CUSTOMS_ESEAL_CONFIG.FLAG_TYPE AND CUSTOMS_ESEAL_CONFIG_GPTMP.I_E_FLAG=CUSTOMS_ESEAL_CONFIG.I_E_FLAG ;

insert into CUSTOMS_ESEAL_CONFIG(CUSTOMS_CODE,FLAG_TYPE,I_E_FLAG,ESEAL_FLAG,ESEAL_MODE,OP_ID,OP_DATE) select CUSTOMS_CODE,FLAG_TYPE,I_E_FLAG,ESEAL_FLAG,ESEAL_MODE,OP_ID,OP_DATE from CUSTOMS_ESEAL_CONFIG_INC_EXT where CMD_TYPE='I';

delete from CUSTOMS_ESEAL_CONFIG_GPTMP;

\timing
