\echo ------------------DCG_BILL_LIST----------------
select now();
\timing
insert into DCG_BILL_LIST_GPTMP (CMD_TYPE,BILL_NO, G_TYPE, G_NO) select CMD_TYPE,BILL_NO, G_TYPE, G_NO from DCG_BILL_LIST_INC_EXT;

delete from DCG_BILL_LIST using DCG_BILL_LIST_GPTMP where DCG_BILL_LIST_GPTMP.BILL_NO=DCG_BILL_LIST.BILL_NO AND DCG_BILL_LIST_GPTMP.G_TYPE=DCG_BILL_LIST.G_TYPE AND DCG_BILL_LIST_GPTMP.G_NO=DCG_BILL_LIST.G_NO ;

insert into DCG_BILL_LIST(BILL_NO,G_TYPE,G_NO,DCG_G_NO,QTY,CHECK_DATE,COP_QTY,COP_UNIT,G_MARK) select BILL_NO,G_TYPE,G_NO,DCG_G_NO,QTY,CHECK_DATE,COP_QTY,COP_UNIT,G_MARK from DCG_BILL_LIST_INC_EXT where CMD_TYPE='I';

delete from DCG_BILL_LIST_GPTMP;

\timing
