\echo ------------------DCG_COPR_INFO----------------
select now();
\timing
insert into DCG_COPR_INFO_GPTMP (CMD_TYPE,CORP_NO) select CMD_TYPE,CORP_NO from DCG_COPR_INFO_INC_EXT;

delete from DCG_COPR_INFO using DCG_COPR_INFO_GPTMP where DCG_COPR_INFO_GPTMP.CORP_NO=DCG_COPR_INFO.CORP_NO ;

insert into DCG_COPR_INFO(CORP_NO,EXE_MARK,BEGIN_DATE,END_DATE,PROC_ER,PROC_DATE,CUSTOMS_CODE,NOTE,REMARK) select CORP_NO,EXE_MARK,BEGIN_DATE,END_DATE,PROC_ER,PROC_DATE,CUSTOMS_CODE,NOTE,REMARK from DCG_COPR_INFO_INC_EXT where CMD_TYPE='I';

delete from DCG_COPR_INFO_GPTMP;

\timing
