\echo ------------------DCG_WORKFLOW----------------
select now();
\timing
insert into DCG_WORKFLOW_GPTMP (CMD_TYPE,DCG_NO, STEP_ID, CREATE_DATE) select CMD_TYPE,DCG_NO, STEP_ID, CREATE_DATE from DCG_WORKFLOW_INC_EXT;

delete from DCG_WORKFLOW using DCG_WORKFLOW_GPTMP where DCG_WORKFLOW_GPTMP.DCG_NO=DCG_WORKFLOW.DCG_NO AND DCG_WORKFLOW_GPTMP.STEP_ID=DCG_WORKFLOW.STEP_ID AND DCG_WORKFLOW_GPTMP.CREATE_DATE=DCG_WORKFLOW.CREATE_DATE ;

insert into DCG_WORKFLOW(DCG_NO,STEP_ID,CREATE_DATE,PROC_ER,PROC_ID,PROC_POS,PROC_RESULT) select DCG_NO,STEP_ID,CREATE_DATE,PROC_ER,PROC_ID,PROC_POS,PROC_RESULT from DCG_WORKFLOW_INC_EXT where CMD_TYPE='I';

delete from DCG_WORKFLOW_GPTMP;

\timing
