\echo ------------------DECLOG_SCORE_LIST----------------
select now();
\timing
insert into DECLOG_SCORE_LIST_GPTMP (CMD_TYPE,DECL_CO, FORM_ID, SCORE_TIME, ITEM_NO) select CMD_TYPE,DECL_CO, FORM_ID, SCORE_TIME, ITEM_NO from DECLOG_SCORE_LIST_INC_EXT;

delete from DECLOG_SCORE_LIST using DECLOG_SCORE_LIST_GPTMP where DECLOG_SCORE_LIST_GPTMP.DECL_CO=DECLOG_SCORE_LIST.DECL_CO AND DECLOG_SCORE_LIST_GPTMP.FORM_ID=DECLOG_SCORE_LIST.FORM_ID AND DECLOG_SCORE_LIST_GPTMP.SCORE_TIME=DECLOG_SCORE_LIST.SCORE_TIME AND DECLOG_SCORE_LIST_GPTMP.ITEM_NO=DECLOG_SCORE_LIST.ITEM_NO ;

insert into DECLOG_SCORE_LIST(DECL_CO,FORM_ID,SCORE_TIME,ITEM_NO,ERROR_TYPE,SEQ_NO,SCORE_DESC) select DECL_CO,FORM_ID,SCORE_TIME,ITEM_NO,ERROR_TYPE,SEQ_NO,SCORE_DESC from DECLOG_SCORE_LIST_INC_EXT where CMD_TYPE='I';

delete from DECLOG_SCORE_LIST_GPTMP;

\timing
