\echo ------------------DECLARER_REL----------------
select now();
\timing
insert into DECLARER_REL_GPTMP (CMD_TYPE,DECL_CO) select CMD_TYPE,DECL_CO from DECLARER_REL_INC_EXT;

delete from DECLARER_REL using DECLARER_REL_GPTMP where DECLARER_REL_GPTMP.DECL_CO=DECLARER_REL.DECL_CO ;

insert into DECLARER_REL(TRADE_CO,DECL_CO,PRE_DECL_CO,TRADE_NAME,BROKER_TYPE,CUSTOMS_CODE,DECL_ZG_CODE,DECL_NAME,DECL_SEX,DECL_DEGREE,DECL_ID_CODE,DECL_BIRTHDAY,DECL_TEL_CODE,DECL_MOBILE_CODE,DECL_FAX_CODE,DECL_EMAIL_ADDR,DECL_CLASS,DECL_YD_FLAG,INP_DATE,IC_CODE,CTRL_MARK,CTRL_DATE,RG_DATE,APPL_CODE,CHK_DATE,CHK_CODE,VALID_DATE,SCORE,SCORE_DATE,CLEAR_DATE,YSCORE,FAULT_TIME,ENTRY_DECL_NUM,ENTRY_END_NUM,FAULT_ENTRY_NUM,LAST_YSCORE,LAST_FAULT_TIME,LAST_ENTRY_DECL_NUM,LAST_ENTRY_END_NUM,LAST_FAULT_ENTRY_NUM,CHANGE_TIME,NOTE) select TRADE_CO,DECL_CO,PRE_DECL_CO,TRADE_NAME,BROKER_TYPE,CUSTOMS_CODE,DECL_ZG_CODE,DECL_NAME,DECL_SEX,DECL_DEGREE,DECL_ID_CODE,DECL_BIRTHDAY,DECL_TEL_CODE,DECL_MOBILE_CODE,DECL_FAX_CODE,DECL_EMAIL_ADDR,DECL_CLASS,DECL_YD_FLAG,INP_DATE,IC_CODE,CTRL_MARK,CTRL_DATE,RG_DATE,APPL_CODE,CHK_DATE,CHK_CODE,VALID_DATE,SCORE,SCORE_DATE,CLEAR_DATE,YSCORE,FAULT_TIME,ENTRY_DECL_NUM,ENTRY_END_NUM,FAULT_ENTRY_NUM,LAST_YSCORE,LAST_FAULT_TIME,LAST_ENTRY_DECL_NUM,LAST_ENTRY_END_NUM,LAST_FAULT_ENTRY_NUM,CHANGE_TIME,NOTE from DECLARER_REL_INC_EXT where CMD_TYPE='I';

delete from DECLARER_REL_GPTMP;

\timing
