\echo ------------------DECLAR_COUNTER_REL----------------
select now();
\timing
insert into DECLAR_COUNTER_REL_GPTMP (CMD_TYPE,DECL_KEY) select CMD_TYPE,DECL_KEY from DECLAR_COUNTER_REL_INC_EXT;

delete from DECLAR_COUNTER_REL using DECLAR_COUNTER_REL_GPTMP where DECLAR_COUNTER_REL_GPTMP.DECL_KEY=DECLAR_COUNTER_REL.DECL_KEY ;

insert into DECLAR_COUNTER_REL(DECL_KEY,COUNTER) select DECL_KEY,COUNTER from DECLAR_COUNTER_REL_INC_EXT where CMD_TYPE='I';

delete from DECLAR_COUNTER_REL_GPTMP;

\timing
