\echo ------------------DEL_EGS_ARC_AGENT_LIST----------------
select now();
\timing
insert into DEL_EGS_ARC_AGENT_LIST_GPTMP (CMD_TYPE,EGS_NO, AGENT_NO) select CMD_TYPE,EGS_NO, AGENT_NO from DEL_EGS_ARC_AGENT_LIST_INC_EXT;

delete from DEL_EGS_ARC_AGENT_LIST using DEL_EGS_ARC_AGENT_LIST_GPTMP where DEL_EGS_ARC_AGENT_LIST_GPTMP.EGS_NO=DEL_EGS_ARC_AGENT_LIST.EGS_NO AND DEL_EGS_ARC_AGENT_LIST_GPTMP.AGENT_NO=DEL_EGS_ARC_AGENT_LIST.AGENT_NO ;

insert into DEL_EGS_ARC_AGENT_LIST(EGS_NO,AGENT_NO,AGENT_CODE,AGENT_NAME) select EGS_NO,AGENT_NO,AGENT_CODE,AGENT_NAME from DEL_EGS_ARC_AGENT_LIST_INC_EXT where CMD_TYPE='I';

delete from DEL_EGS_ARC_AGENT_LIST_GPTMP;

\timing
