\echo ------------------DEL_EGS_CLEAR_CERT----------------
select now();
\timing
insert into DEL_EGS_CLEAR_CERT_GPTMP (CMD_TYPE,CLR_NO, CERT_CODE, CERT_NO) select CMD_TYPE,CLR_NO, CERT_CODE, CERT_NO from DEL_EGS_CLEAR_CERT_INC_EXT;

delete from DEL_EGS_CLEAR_CERT using DEL_EGS_CLEAR_CERT_GPTMP where DEL_EGS_CLEAR_CERT_GPTMP.CLR_NO=DEL_EGS_CLEAR_CERT.CLR_NO AND DEL_EGS_CLEAR_CERT_GPTMP.CERT_CODE=DEL_EGS_CLEAR_CERT.CERT_CODE AND DEL_EGS_CLEAR_CERT_GPTMP.CERT_NO=DEL_EGS_CLEAR_CERT.CERT_NO ;

insert into DEL_EGS_CLEAR_CERT(CLR_NO,CERT_CODE,CERT_NO) select CLR_NO,CERT_CODE,CERT_NO from DEL_EGS_CLEAR_CERT_INC_EXT where CMD_TYPE='I';

delete from DEL_EGS_CLEAR_CERT_GPTMP;

\timing
