\echo ------------------DEL_MOD_APPLY----------------
select now();
\timing
insert into DEL_MOD_APPLY_GPTMP (CMD_TYPE,ENTRY_ID, APPLY_TIME) select CMD_TYPE,ENTRY_ID, APPLY_TIME from DEL_MOD_APPLY_INC_EXT;

delete from DEL_MOD_APPLY using DEL_MOD_APPLY_GPTMP where DEL_MOD_APPLY_GPTMP.ENTRY_ID=DEL_MOD_APPLY.ENTRY_ID AND DEL_MOD_APPLY_GPTMP.APPLY_TIME=DEL_MOD_APPLY.APPLY_TIME ;

insert into DEL_MOD_APPLY(ENTRY_ID,APPLY_TIME,APPLY_FLAG,APPLY_ER,APPLY_MARK,APPLY_COMM,RSK_CLASS,OP_FLAG,OP_TIME,OP_ER,OP_MARK,OP_COMM) select ENTRY_ID,APPLY_TIME,APPLY_FLAG,APPLY_ER,APPLY_MARK,APPLY_COMM,RSK_CLASS,OP_FLAG,OP_TIME,OP_ER,OP_MARK,OP_COMM from DEL_MOD_APPLY_INC_EXT where CMD_TYPE='I';

delete from DEL_MOD_APPLY_GPTMP;

\timing
