\echo ------------------DEL_EGS_DECLARE_HEAD----------------
select now();
\timing
insert into DEL_EGS_DECLARE_HEAD_GPTMP (CMD_TYPE,DECL_NO) select CMD_TYPE,DECL_NO from DEL_EGS_DECLARE_HEAD_INC_EXT;

delete from DEL_EGS_DECLARE_HEAD using DEL_EGS_DECLARE_HEAD_GPTMP where DEL_EGS_DECLARE_HEAD_GPTMP.DECL_NO=DEL_EGS_DECLARE_HEAD.DECL_NO ;

insert into DEL_EGS_DECLARE_HEAD(EGS_NO,EGS_NAME,ADM_NO,DECL_NO,PRE_DECL_NO,DECL_TYPE,MASTER_CUSTOMS,I_E_PORT,I_E_DATE,I_E_FLAG,DECLARE_DATE,AGENT_CODE,AGENT_NAME,DECLARE_NO,DECLARE_PHONE,LICENSE_NO,TRAF_MODE,BILL_NO,BILL_SUB_NO,TRADE_COUNTRY,GROSS_WT,NET_WT,WRAP_TYPE,PACK_NO,TRANS_MODE,NOTES,DEPOSIT_MARK,REL_DATE,TRANS_DATE,POSTPONE_TIMES,ZS_APPR_NO,TURN_NO,ENTRY_ID,ENTRY_TYPE,DECLARE_SOURCE,CHK_MARK,EX_CUSTOMS_CODE,EX_EGS_NO,EX_EGS_NAME,EX_AGENT_CODE,EX_AGENT_NAME,AUDIT_ER,AUDIT_DATE,AUDIT_NOTE,VERIFY_DATE,VERIFY_ER,CLEAR_DATE,CLEAR_ER,EXE_MARK) select EGS_NO,EGS_NAME,ADM_NO,DECL_NO,PRE_DECL_NO,DECL_TYPE,MASTER_CUSTOMS,I_E_PORT,I_E_DATE,I_E_FLAG,DECLARE_DATE,AGENT_CODE,AGENT_NAME,DECLARE_NO,DECLARE_PHONE,LICENSE_NO,TRAF_MODE,BILL_NO,BILL_SUB_NO,TRADE_COUNTRY,GROSS_WT,NET_WT,WRAP_TYPE,PACK_NO,TRANS_MODE,NOTES,DEPOSIT_MARK,REL_DATE,TRANS_DATE,POSTPONE_TIMES,ZS_APPR_NO,TURN_NO,ENTRY_ID,ENTRY_TYPE,DECLARE_SOURCE,CHK_MARK,EX_CUSTOMS_CODE,EX_EGS_NO,EX_EGS_NAME,EX_AGENT_CODE,EX_AGENT_NAME,AUDIT_ER,AUDIT_DATE,AUDIT_NOTE,VERIFY_DATE,VERIFY_ER,CLEAR_DATE,CLEAR_ER,EXE_MARK from DEL_EGS_DECLARE_HEAD_INC_EXT where CMD_TYPE='I';

delete from DEL_EGS_DECLARE_HEAD_GPTMP;

\timing
