\echo ------------------DST_COUNTER_TABLE----------------
select now();
\timing
insert into DST_COUNTER_TABLE_GPTMP (CMD_TYPE,EMS_NO, COUNTER, SUB_COUNTER) select CMD_TYPE,EMS_NO, COUNTER, SUB_COUNTER from DST_COUNTER_TABLE_INC_EXT;

delete from DST_COUNTER_TABLE using DST_COUNTER_TABLE_GPTMP where DST_COUNTER_TABLE_GPTMP.EMS_NO=DST_COUNTER_TABLE.EMS_NO AND DST_COUNTER_TABLE_GPTMP.COUNTER=DST_COUNTER_TABLE.COUNTER AND DST_COUNTER_TABLE_GPTMP.SUB_COUNTER=DST_COUNTER_TABLE.SUB_COUNTER ;

insert into DST_COUNTER_TABLE(EMS_NO,COUNTER,SUB_COUNTER) select EMS_NO,COUNTER,SUB_COUNTER from DST_COUNTER_TABLE_INC_EXT where CMD_TYPE='I';

delete from DST_COUNTER_TABLE_GPTMP;

\timing
