\echo ------------------DST_EXG----------------
select now();
\timing
insert into DST_EXG_GPTMP (CMD_TYPE,PRE_NO, G_NO, ORIGIN_COUNTRY) select CMD_TYPE,PRE_NO, G_NO, ORIGIN_COUNTRY from DST_EXG_INC_EXT;

delete from DST_EXG using DST_EXG_GPTMP where DST_EXG_GPTMP.PRE_NO=DST_EXG.PRE_NO AND DST_EXG_GPTMP.G_NO=DST_EXG.G_NO AND DST_EXG_GPTMP.ORIGIN_COUNTRY=DST_EXG.ORIGIN_COUNTRY ;

insert into DST_EXG(DST_SEQ_NO,PRE_NO,REL_NO,G_NO,CODE_TS,G_NAME,G_MODEL,G_QTY,G_UNIT,UNIT_1,QTY_1,DECL_PRICE,PRICE_1,TRADE_TOTAL,TRADE_CURR,ORIGIN_COUNTRY,VERSION,MODIFY_MARK,DECL_DUTY,DECL_TAX,DECL_OTHER,DECL_TOTAL,CHK_DUTY,CHK_TAX,CHK_INTEREST,CHK_OTHER,CHK_TOTAL,IMG_PRICE,CONTRACT_PRICE,NORMAL_PRICE,PARAM_PRICE,NOTE,FACT_QTY) select DST_SEQ_NO,PRE_NO,REL_NO,G_NO,CODE_TS,G_NAME,G_MODEL,G_QTY,G_UNIT,UNIT_1,QTY_1,DECL_PRICE,PRICE_1,TRADE_TOTAL,TRADE_CURR,ORIGIN_COUNTRY,VERSION,MODIFY_MARK,DECL_DUTY,DECL_TAX,DECL_OTHER,DECL_TOTAL,CHK_DUTY,CHK_TAX,CHK_INTEREST,CHK_OTHER,CHK_TOTAL,IMG_PRICE,CONTRACT_PRICE,NORMAL_PRICE,PARAM_PRICE,NOTE,FACT_QTY from DST_EXG_INC_EXT where CMD_TYPE='I';

delete from DST_EXG_GPTMP;

\timing
