\echo ------------------DST_DEDUCT----------------
select now();
\timing
insert into DST_DEDUCT_GPTMP (CMD_TYPE,PRE_NO, G_NO, ORIGIN_COUNTRY, ENTRY_ID, ENTRY_G_NO) select CMD_TYPE,PRE_NO, G_NO, ORIGIN_COUNTRY, ENTRY_ID, ENTRY_G_NO from DST_DEDUCT_INC_EXT;

delete from DST_DEDUCT using DST_DEDUCT_GPTMP where DST_DEDUCT_GPTMP.PRE_NO=DST_DEDUCT.PRE_NO AND DST_DEDUCT_GPTMP.G_NO=DST_DEDUCT.G_NO AND DST_DEDUCT_GPTMP.ORIGIN_COUNTRY=DST_DEDUCT.ORIGIN_COUNTRY AND DST_DEDUCT_GPTMP.ENTRY_ID=DST_DEDUCT.ENTRY_ID AND DST_DEDUCT_GPTMP.ENTRY_G_NO=DST_DEDUCT.ENTRY_G_NO ;

insert into DST_DEDUCT(PRE_NO,REL_NO,G_NO,ENTRY_ID,ENTRY_G_NO,I_E_FLAG,G_QTY,VERIFY_DATE,VERIFY_ER,ORIGIN_COUNTRY) select PRE_NO,REL_NO,G_NO,ENTRY_ID,ENTRY_G_NO,I_E_FLAG,G_QTY,VERIFY_DATE,VERIFY_ER,ORIGIN_COUNTRY from DST_DEDUCT_INC_EXT where CMD_TYPE='I';

delete from DST_DEDUCT_GPTMP;

\timing
