\echo ------------------DTT_COP_PARAM----------------
select now();
\timing
insert into DTT_COP_PARAM_GPTMP (CMD_TYPE,CORP_CODE, CUSTOMS_CODE) select CMD_TYPE,CORP_CODE, CUSTOMS_CODE from DTT_COP_PARAM_INC_EXT;

delete from DTT_COP_PARAM using DTT_COP_PARAM_GPTMP where DTT_COP_PARAM_GPTMP.CORP_CODE=DTT_COP_PARAM.CORP_CODE AND DTT_COP_PARAM_GPTMP.CUSTOMS_CODE=DTT_COP_PARAM.CUSTOMS_CODE ;

insert into DTT_COP_PARAM(CORP_CODE,CUSTOMS_CODE,CORP_NAME,PROC_ER,PROC_DATE) select CORP_CODE,CUSTOMS_CODE,CORP_NAME,PROC_ER,PROC_DATE from DTT_COP_PARAM_INC_EXT where CMD_TYPE='I';

delete from DTT_COP_PARAM_GPTMP;

\timing
