\echo ------------------DUTYFORM_HEAD----------------
select now();
\timing
insert into DUTYFORM_HEAD_GPTMP (CMD_TYPE,ENTRY_ID) select CMD_TYPE,ENTRY_ID from DUTYFORM_HEAD_INC_EXT;

delete from DUTYFORM_HEAD using DUTYFORM_HEAD_GPTMP where DUTYFORM_HEAD_GPTMP.ENTRY_ID=DUTYFORM_HEAD.ENTRY_ID ;

insert into DUTYFORM_HEAD(ENTRY_ID,ID_CHK,DUTYFORM_FLAG,I_E_PORT,DECL_PORT,PAYER_CODE,PAYER_NAME,OWNER_CODE,OWNER_NAME,TRADE_CODE,TRADE_NAME,AGENT_CODE,AGENT_NAME,CONTR_NO,D_DATE,DUTY_ER,G_NAME,D_ITEMS_NO,A_ITEMS_NO,R_ITEMS_NO,TRADE_MODE,CUT_MODE,TAXY_RG_NO,MANUAL_NO,INTEREST_DAYS,INTEREST_RATE,SERVICE_RATE) select ENTRY_ID,ID_CHK,DUTYFORM_FLAG,I_E_PORT,DECL_PORT,PAYER_CODE,PAYER_NAME,OWNER_CODE,OWNER_NAME,TRADE_CODE,TRADE_NAME,AGENT_CODE,AGENT_NAME,CONTR_NO,D_DATE,DUTY_ER,G_NAME,D_ITEMS_NO,A_ITEMS_NO,R_ITEMS_NO,TRADE_MODE,CUT_MODE,TAXY_RG_NO,MANUAL_NO,INTEREST_DAYS,INTEREST_RATE,SERVICE_RATE from DUTYFORM_HEAD_INC_EXT where CMD_TYPE='I';

delete from DUTYFORM_HEAD_GPTMP;

\timing
