\echo ------------------DUTYFORM_LIST----------------
select now();
\timing
insert into DUTYFORM_LIST_GPTMP (CMD_TYPE,ENTRY_ID, TAX_ID) select CMD_TYPE,ENTRY_ID, TAX_ID from DUTYFORM_LIST_INC_EXT;

delete from DUTYFORM_LIST using DUTYFORM_LIST_GPTMP where DUTYFORM_LIST_GPTMP.ENTRY_ID=DUTYFORM_LIST.ENTRY_ID AND DUTYFORM_LIST_GPTMP.TAX_ID=DUTYFORM_LIST.TAX_ID ;

insert into DUTYFORM_LIST(ENTRY_ID,TAX_ID,DELAY_MARK,DUTY_FLAG,DUTY_FLAG_NOTE,TAX_TYPE,PAY_MODE,EPORT_ID,ID_CHK,INCOME_SYS,INCOME_NAME,BANK_NAME,BANK_ACCOUNT,SUBJECT_CODE,SUBJECT_NAME,SUBJECT_LEVEL,EXQ_NAME,DUTY_VALUE,REAL_TAX,DELAY_DAYS,TAX_CUT,CUT_NOTE,P_DATE,P_LIMIT,PAY_DATE,C_DATE,CANCEL_ER,RECHK_ER,EXQ_DATE,SYS_DATE,BOOK_NO,ORIGINAL_TAXID,DUTYFOR_NO,NOTE_1,NOTE_2,NOTE_3,NOTE_4,OP_C_DATE,GEN_DATE,BANK_CODE,BANK_ACCOUNT_NAME,PAYER_ACCOUNT_NO,PAYER_ACCOUNT_NAME,PAYER_BANK_NAME,PAYER_BANK_CODE,TREASURY_CODE) select ENTRY_ID,TAX_ID,DELAY_MARK,DUTY_FLAG,DUTY_FLAG_NOTE,TAX_TYPE,PAY_MODE,EPORT_ID,ID_CHK,INCOME_SYS,INCOME_NAME,BANK_NAME,BANK_ACCOUNT,SUBJECT_CODE,SUBJECT_NAME,SUBJECT_LEVEL,EXQ_NAME,DUTY_VALUE,REAL_TAX,DELAY_DAYS,TAX_CUT,CUT_NOTE,P_DATE,P_LIMIT,PAY_DATE,C_DATE,CANCEL_ER,RECHK_ER,EXQ_DATE,SYS_DATE,BOOK_NO,ORIGINAL_TAXID,DUTYFOR_NO,NOTE_1,NOTE_2,NOTE_3,NOTE_4,OP_C_DATE,GEN_DATE,BANK_CODE,BANK_ACCOUNT_NAME,PAYER_ACCOUNT_NO,PAYER_ACCOUNT_NAME,PAYER_BANK_NAME,PAYER_BANK_CODE,TREASURY_CODE from DUTYFORM_LIST_INC_EXT where CMD_TYPE='I';

delete from DUTYFORM_LIST_GPTMP;

\timing
