\echo ------------------ECO_WORKFLOW----------------
select now();
\timing
insert into ECO_WORKFLOW_GPTMP (CMD_TYPE,CERTIFICATE_NO, TRANSFER_NUM, PROCESS_STATUS, PROCESS_DATE) select CMD_TYPE,CERTIFICATE_NO, TRANSFER_NUM, PROCESS_STATUS, PROCESS_DATE from ECO_WORKFLOW_INC_EXT;

delete from ECO_WORKFLOW using ECO_WORKFLOW_GPTMP where ECO_WORKFLOW_GPTMP.CERTIFICATE_NO=ECO_WORKFLOW.CERTIFICATE_NO AND ECO_WORKFLOW_GPTMP.TRANSFER_NUM=ECO_WORKFLOW.TRANSFER_NUM AND ECO_WORKFLOW_GPTMP.PROCESS_STATUS=ECO_WORKFLOW.PROCESS_STATUS AND ECO_WORKFLOW_GPTMP.PROCESS_DATE=ECO_WORKFLOW.PROCESS_DATE ;

insert into ECO_WORKFLOW(CERTIFICATE_NO,TRANSFER_NUM,PROCESS_STATUS,PROCESS_DATE,ENTRY_ID,NOTE) select CERTIFICATE_NO,TRANSFER_NUM,PROCESS_STATUS,PROCESS_DATE,ENTRY_ID,NOTE from ECO_WORKFLOW_INC_EXT where CMD_TYPE='I';

delete from ECO_WORKFLOW_GPTMP;

\timing
