\echo ------------------ECO_PARTS----------------
select now();
\timing
insert into ECO_PARTS_GPTMP (CMD_TYPE,CERTIFICATE_NO, G_NO, PART_SEQ) select CMD_TYPE,CERTIFICATE_NO, G_NO, PART_SEQ from ECO_PARTS_INC_EXT;

delete from ECO_PARTS using ECO_PARTS_GPTMP where ECO_PARTS_GPTMP.CERTIFICATE_NO=ECO_PARTS.CERTIFICATE_NO AND ECO_PARTS_GPTMP.G_NO=ECO_PARTS.G_NO AND ECO_PARTS_GPTMP.PART_SEQ=ECO_PARTS.PART_SEQ ;

insert into ECO_PARTS(CERTIFICATE_NO,G_NO,PART_SEQ,PART_HSCODE,PART_NAME,UNIT_PRICE,ORIGIN_COUNTRY,AMT_PERCENT) select CERTIFICATE_NO,G_NO,PART_SEQ,PART_HSCODE,PART_NAME,UNIT_PRICE,ORIGIN_COUNTRY,AMT_PERCENT from ECO_PARTS_INC_EXT where CMD_TYPE='I';

delete from ECO_PARTS_GPTMP;

\timing
