\echo ------------------EGS_CHECK_LOG----------------
select now();
\timing
insert into EGS_CHECK_LOG_GPTMP (CMD_TYPE,EGS_NO, CHK_TIMES, FORM_TYPE, G_NO) select CMD_TYPE,EGS_NO, CHK_TIMES, FORM_TYPE, G_NO from EGS_CHECK_LOG_INC_EXT;

delete from EGS_CHECK_LOG using EGS_CHECK_LOG_GPTMP where EGS_CHECK_LOG_GPTMP.EGS_NO=EGS_CHECK_LOG.EGS_NO AND EGS_CHECK_LOG_GPTMP.CHK_TIMES=EGS_CHECK_LOG.CHK_TIMES AND EGS_CHECK_LOG_GPTMP.FORM_TYPE=EGS_CHECK_LOG.FORM_TYPE AND EGS_CHECK_LOG_GPTMP.G_NO=EGS_CHECK_LOG.G_NO ;

insert into EGS_CHECK_LOG(EGS_NO,EPORT_NO,CHK_TIMES,FORM_TYPE,G_NO,EGS_TYPE,CHK_MARK,CHK_ER,CHK_DATE,CHK_RESULT,MESSAGE,NOTE) select EGS_NO,EPORT_NO,CHK_TIMES,FORM_TYPE,G_NO,EGS_TYPE,CHK_MARK,CHK_ER,CHK_DATE,CHK_RESULT,MESSAGE,NOTE from EGS_CHECK_LOG_INC_EXT where CMD_TYPE='I';

delete from EGS_CHECK_LOG_GPTMP;

\timing
