\echo ------------------EGS_ARC_MERCHANT_LIST----------------
select now();
\timing
insert into EGS_ARC_MERCHANT_LIST_GPTMP (CMD_TYPE,EGS_NO, AGENT_CODE, MERCHANT_NO) select CMD_TYPE,EGS_NO, AGENT_CODE, MERCHANT_NO from EGS_ARC_MERCHANT_LIST_INC_EXT;

delete from EGS_ARC_MERCHANT_LIST using EGS_ARC_MERCHANT_LIST_GPTMP where EGS_ARC_MERCHANT_LIST_GPTMP.EGS_NO=EGS_ARC_MERCHANT_LIST.EGS_NO AND EGS_ARC_MERCHANT_LIST_GPTMP.AGENT_CODE=EGS_ARC_MERCHANT_LIST.AGENT_CODE AND EGS_ARC_MERCHANT_LIST_GPTMP.MERCHANT_NO=EGS_ARC_MERCHANT_LIST.MERCHANT_NO ;

insert into EGS_ARC_MERCHANT_LIST(EGS_NO,MERCHANT_NO,MERCHANT_NAME,MERCHANT_COUNTRY,EXHIBITION_NO,EXHIBITION_SITE_NO,AGENT_CODE) select EGS_NO,MERCHANT_NO,MERCHANT_NAME,MERCHANT_COUNTRY,EXHIBITION_NO,EXHIBITION_SITE_NO,AGENT_CODE from EGS_ARC_MERCHANT_LIST_INC_EXT where CMD_TYPE='I';

delete from EGS_ARC_MERCHANT_LIST_GPTMP;

\timing
