\echo ------------------EGS_ADMIT_HEAD----------------
select now();
\timing
insert into EGS_ADMIT_HEAD_GPTMP (CMD_TYPE,ADM_NO) select CMD_TYPE,ADM_NO from EGS_ADMIT_HEAD_INC_EXT;

delete from EGS_ADMIT_HEAD using EGS_ADMIT_HEAD_GPTMP where EGS_ADMIT_HEAD_GPTMP.ADM_NO=EGS_ADMIT_HEAD.ADM_NO ;

insert into EGS_ADMIT_HEAD(PRE_ADM_NO,ADM_NO,MODIFY_TIMES,ADM_TYPE,EGS_NO,EGS_NAME,APPLY_NO,REG_CUSTOMS,MASTER_CUSTOMS,I_E_FLAG,DECL_DATE,AGENT_CODE,AGENT_NAME,DECLARE_NO,DECLARE_PHONE,SPONSOR_NAME,PERIOD,AUDITOR,AUDIT_DATE,AUDIT_NOTE,PRINT_DATE,AUDIT_RESULT,AUDIT_FILENO,DECLARE_SOURCE,CHK_MARK,NOTES) select PRE_ADM_NO,ADM_NO,MODIFY_TIMES,ADM_TYPE,EGS_NO,EGS_NAME,APPLY_NO,REG_CUSTOMS,MASTER_CUSTOMS,I_E_FLAG,DECL_DATE,AGENT_CODE,AGENT_NAME,DECLARE_NO,DECLARE_PHONE,SPONSOR_NAME,PERIOD,AUDITOR,AUDIT_DATE,AUDIT_NOTE,PRINT_DATE,AUDIT_RESULT,AUDIT_FILENO,DECLARE_SOURCE,CHK_MARK,NOTES from EGS_ADMIT_HEAD_INC_EXT where CMD_TYPE='I';

delete from EGS_ADMIT_HEAD_GPTMP;

\timing
