\echo ------------------EGS_CLEAR_CERT----------------
select now();
\timing
insert into EGS_CLEAR_CERT_GPTMP (CMD_TYPE,CLR_NO, CERT_CODE, CERT_NO) select CMD_TYPE,CLR_NO, CERT_CODE, CERT_NO from EGS_CLEAR_CERT_INC_EXT;

delete from EGS_CLEAR_CERT using EGS_CLEAR_CERT_GPTMP where EGS_CLEAR_CERT_GPTMP.CLR_NO=EGS_CLEAR_CERT.CLR_NO AND EGS_CLEAR_CERT_GPTMP.CERT_CODE=EGS_CLEAR_CERT.CERT_CODE AND EGS_CLEAR_CERT_GPTMP.CERT_NO=EGS_CLEAR_CERT.CERT_NO ;

insert into EGS_CLEAR_CERT(CLR_NO,CERT_CODE,CERT_NO) select CLR_NO,CERT_CODE,CERT_NO from EGS_CLEAR_CERT_INC_EXT where CMD_TYPE='I';

delete from EGS_CLEAR_CERT_GPTMP;

\timing
