\echo ------------------EGS_DECLARE_CERT----------------
select now();
\timing
insert into EGS_DECLARE_CERT_GPTMP (CMD_TYPE,DECL_NO, CERT_CODE, CERT_NO) select CMD_TYPE,DECL_NO, CERT_CODE, CERT_NO from EGS_DECLARE_CERT_INC_EXT;

delete from EGS_DECLARE_CERT using EGS_DECLARE_CERT_GPTMP where EGS_DECLARE_CERT_GPTMP.DECL_NO=EGS_DECLARE_CERT.DECL_NO AND EGS_DECLARE_CERT_GPTMP.CERT_CODE=EGS_DECLARE_CERT.CERT_CODE AND EGS_DECLARE_CERT_GPTMP.CERT_NO=EGS_DECLARE_CERT.CERT_NO ;

insert into EGS_DECLARE_CERT(DECL_NO,CERT_CODE,CERT_NO) select DECL_NO,CERT_CODE,CERT_NO from EGS_DECLARE_CERT_INC_EXT where CMD_TYPE='I';

delete from EGS_DECLARE_CERT_GPTMP;

\timing
