\echo ------------------EMS_CLR_LIST----------------
select now();
\timing
insert into EMS_CLR_LIST_GPTMP (CMD_TYPE,EMS_NO, DCR_TIMES, G_TYPE, G_NO, DU_CODE) select CMD_TYPE,EMS_NO, DCR_TIMES, G_TYPE, G_NO, DU_CODE from EMS_CLR_LIST_INC_EXT;

delete from EMS_CLR_LIST using EMS_CLR_LIST_GPTMP where EMS_CLR_LIST_GPTMP.EMS_NO=EMS_CLR_LIST.EMS_NO AND EMS_CLR_LIST_GPTMP.DCR_TIMES=EMS_CLR_LIST.DCR_TIMES AND EMS_CLR_LIST_GPTMP.G_TYPE=EMS_CLR_LIST.G_TYPE AND EMS_CLR_LIST_GPTMP.G_NO=EMS_CLR_LIST.G_NO AND EMS_CLR_LIST_GPTMP.DU_CODE=EMS_CLR_LIST.DU_CODE ;

insert into EMS_CLR_LIST(EMS_NO,DCR_TIMES,G_TYPE,G_NO,DU_CODE,ITEMS_NO,QTY,AMOUNT,WEIGHT,DU_MARK,NOTE_1,NOTE,I_E_FLAG,TRADE_MODE,PARENT_DU_CODE,DISPSUB) select EMS_NO,DCR_TIMES,G_TYPE,G_NO,DU_CODE,ITEMS_NO,QTY,AMOUNT,WEIGHT,DU_MARK,NOTE_1,NOTE,I_E_FLAG,TRADE_MODE,PARENT_DU_CODE,DISPSUB from EMS_CLR_LIST_INC_EXT where CMD_TYPE='I';

delete from EMS_CLR_LIST_GPTMP;

\timing
