\echo ------------------EMS_CONSUME----------------
select now();
\timing
insert into EMS_CONSUME_GPTMP (CMD_TYPE,EMS_NO, EXG_NO, EXG_VERSION, IMG_NO) select CMD_TYPE,EMS_NO, EXG_NO, EXG_VERSION, IMG_NO from EMS_CONSUME_INC_EXT;

delete from EMS_CONSUME using EMS_CONSUME_GPTMP where EMS_CONSUME_GPTMP.EMS_NO=EMS_CONSUME.EMS_NO AND EMS_CONSUME_GPTMP.EXG_NO=EMS_CONSUME.EXG_NO AND EMS_CONSUME_GPTMP.EXG_VERSION=EMS_CONSUME.EXG_VERSION AND EMS_CONSUME_GPTMP.IMG_NO=EMS_CONSUME.IMG_NO ;

insert into EMS_CONSUME(EMS_NO,EXG_NO,EXG_VERSION,IMG_NO,MODIFY_TIMES,DEC_CM,DEC_DM,OTHER_CM,OTHER_DM,CM_MARK,PRODUCT_MARK,PRODUCT_TYPE,MODIFY_MARK,CONTROL_MARK,NOTE,ETL_MARK) select EMS_NO,EXG_NO,EXG_VERSION,IMG_NO,MODIFY_TIMES,DEC_CM,DEC_DM,OTHER_CM,OTHER_DM,CM_MARK,PRODUCT_MARK,PRODUCT_TYPE,MODIFY_MARK,CONTROL_MARK,NOTE,ETL_MARK from EMS_CONSUME_INC_EXT where CMD_TYPE='I';

delete from EMS_CONSUME_GPTMP;

\timing
