\echo ------------------EMS_CONSUME_CLR----------------
select now();
\timing
insert into EMS_CONSUME_CLR_GPTMP (CMD_TYPE,EMS_NO, IMG_NO) select CMD_TYPE,EMS_NO, IMG_NO from EMS_CONSUME_CLR_INC_EXT;

delete from EMS_CONSUME_CLR using EMS_CONSUME_CLR_GPTMP where EMS_CONSUME_CLR_GPTMP.EMS_NO=EMS_CONSUME_CLR.EMS_NO AND EMS_CONSUME_CLR_GPTMP.IMG_NO=EMS_CONSUME_CLR.IMG_NO ;

insert into EMS_CONSUME_CLR(EMS_NO,IMG_NO,G_NAME,QTY,EX_QTY,REM_QTY,UNIT,REM_RATIO,MODIFY_MARK,ETL_MARK) select EMS_NO,IMG_NO,G_NAME,QTY,EX_QTY,REM_QTY,UNIT,REM_RATIO,MODIFY_MARK,ETL_MARK from EMS_CONSUME_CLR_INC_EXT where CMD_TYPE='I';

delete from EMS_CONSUME_CLR_GPTMP;

\timing
