\echo ------------------EMS_VERIFY----------------
select now();
\timing
insert into EMS_VERIFY_GPTMP (CMD_TYPE,EMS_NO, G_TYPE, G_NO) select CMD_TYPE,EMS_NO, G_TYPE, G_NO from EMS_VERIFY_INC_EXT;

delete from EMS_VERIFY using EMS_VERIFY_GPTMP where EMS_VERIFY_GPTMP.EMS_NO=EMS_VERIFY.EMS_NO AND EMS_VERIFY_GPTMP.G_TYPE=EMS_VERIFY.G_TYPE AND EMS_VERIFY_GPTMP.G_NO=EMS_VERIFY.G_NO ;

insert into EMS_VERIFY(EMS_NO,G_TYPE,G_NO,CODE_TS,G_NAME,UNIT,QTY,MAX_QTY,FIRST_QTY,INC_QTY,INC_QTY_DEDUCT,INC_QTY_ENTRY,CUT_QTY,CUT_QTY_DEDUCT,CUT_QTY_ENTRY,CLR_INC_QTY,CLR_CUT_QTY,RESULT,RESULT2) select EMS_NO,G_TYPE,G_NO,CODE_TS,G_NAME,UNIT,QTY,MAX_QTY,FIRST_QTY,INC_QTY,INC_QTY_DEDUCT,INC_QTY_ENTRY,CUT_QTY,CUT_QTY_DEDUCT,CUT_QTY_ENTRY,CLR_INC_QTY,CLR_CUT_QTY,RESULT,RESULT2 from EMS_VERIFY_INC_EXT where CMD_TYPE='I';

delete from EMS_VERIFY_GPTMP;

\timing
