\echo ------------------EMS_WORKFLOW----------------
select now();
\timing
insert into EMS_WORKFLOW_GPTMP (CMD_TYPE,EMS_NO, STEP_ID, CREATE_DATE) select CMD_TYPE,EMS_NO, STEP_ID, CREATE_DATE from EMS_WORKFLOW_INC_EXT;

delete from EMS_WORKFLOW using EMS_WORKFLOW_GPTMP where EMS_WORKFLOW_GPTMP.EMS_NO=EMS_WORKFLOW.EMS_NO AND EMS_WORKFLOW_GPTMP.STEP_ID=EMS_WORKFLOW.STEP_ID AND EMS_WORKFLOW_GPTMP.CREATE_DATE=EMS_WORKFLOW.CREATE_DATE ;

insert into EMS_WORKFLOW(EMS_NO,STEP_ID,CREATE_DATE,PROC_ER,PROC_ID,PROC_POS,PROC_RESULT) select EMS_NO,STEP_ID,CREATE_DATE,PROC_ER,PROC_ID,PROC_POS,PROC_RESULT from EMS_WORKFLOW_INC_EXT where CMD_TYPE='I';

delete from EMS_WORKFLOW_GPTMP;

\timing
