\echo ------------------EMS_MESSAGE_LOG----------------
select now();
\timing
insert into EMS_MESSAGE_LOG_GPTMP (CMD_TYPE,EMS_NO, SEND_CUSTOMS, CUSTOMS_CODE, H2000_RECEIVE_DATE) select CMD_TYPE,EMS_NO, SEND_CUSTOMS, CUSTOMS_CODE, H2000_RECEIVE_DATE from EMS_MESSAGE_LOG_INC_EXT;

delete from EMS_MESSAGE_LOG using EMS_MESSAGE_LOG_GPTMP where EMS_MESSAGE_LOG_GPTMP.EMS_NO=EMS_MESSAGE_LOG.EMS_NO AND EMS_MESSAGE_LOG_GPTMP.SEND_CUSTOMS=EMS_MESSAGE_LOG.SEND_CUSTOMS AND EMS_MESSAGE_LOG_GPTMP.CUSTOMS_CODE=EMS_MESSAGE_LOG.CUSTOMS_CODE AND EMS_MESSAGE_LOG_GPTMP.H2000_RECEIVE_DATE=EMS_MESSAGE_LOG.H2000_RECEIVE_DATE ;

insert into EMS_MESSAGE_LOG(EMS_NO,SEND_CUSTOMS,CUSTOMS_CODE,H2000_RECEIVE_DATE,MESSAGE_ID,MESSAGE_FLAG,MESSAGE_TYPE,RECEIVE_DATE,TYPE,SEND_TIMES,APPL_NO,STATUS,FLAG,NOTE) select EMS_NO,SEND_CUSTOMS,CUSTOMS_CODE,H2000_RECEIVE_DATE,MESSAGE_ID,MESSAGE_FLAG,MESSAGE_TYPE,RECEIVE_DATE,TYPE,SEND_TIMES,APPL_NO,STATUS,FLAG,NOTE from EMS_MESSAGE_LOG_INC_EXT where CMD_TYPE='I';

delete from EMS_MESSAGE_LOG_GPTMP;

\timing
