\echo ------------------EMS_DCR_LIST----------------
select now();
\timing
insert into EMS_DCR_LIST_GPTMP (CMD_TYPE,EMS_NO, DCR_TIMES, G_TYPE, G_NO) select CMD_TYPE,EMS_NO, DCR_TIMES, G_TYPE, G_NO from EMS_DCR_LIST_INC_EXT;

delete from EMS_DCR_LIST using EMS_DCR_LIST_GPTMP where EMS_DCR_LIST_GPTMP.EMS_NO=EMS_DCR_LIST.EMS_NO AND EMS_DCR_LIST_GPTMP.DCR_TIMES=EMS_DCR_LIST.DCR_TIMES AND EMS_DCR_LIST_GPTMP.G_TYPE=EMS_DCR_LIST.G_TYPE AND EMS_DCR_LIST_GPTMP.G_NO=EMS_DCR_LIST.G_NO ;

insert into EMS_DCR_LIST(EMS_NO,DCR_TIMES,G_TYPE,G_NO,GR_QTY,GR_AMOUNT,GR_WEIGHT,REMAIN_QTY,REMAIN_AMOUNT,REMAIN_WEIGHT,CM_QTY,CM_AMOUNT,CM_WEIGHT,FACT_REMAIN_QTY,FACT_REMAIN_AMOUNT,FACT_REMAIN_WEIGHT,NOTE_1,NOTE_2,NOTE,MODIFY_MARK,FACT_QTY,T_QTY,IN_QTY,REX_QTY,DISCLAIM_QTY,REMAIN_T_QTY,EXCHANGE_EX_QTY,EXCHANGE_IM_QTY) select EMS_NO,DCR_TIMES,G_TYPE,G_NO,GR_QTY,GR_AMOUNT,GR_WEIGHT,REMAIN_QTY,REMAIN_AMOUNT,REMAIN_WEIGHT,CM_QTY,CM_AMOUNT,CM_WEIGHT,FACT_REMAIN_QTY,FACT_REMAIN_AMOUNT,FACT_REMAIN_WEIGHT,NOTE_1,NOTE_2,NOTE,MODIFY_MARK,FACT_QTY,T_QTY,IN_QTY,REX_QTY,DISCLAIM_QTY,REMAIN_T_QTY,EXCHANGE_EX_QTY,EXCHANGE_IM_QTY from EMS_DCR_LIST_INC_EXT where CMD_TYPE='I';

delete from EMS_DCR_LIST_GPTMP;

\timing
