\echo ------------------EMS_PRESS_CLEAR----------------
select now();
\timing
insert into EMS_PRESS_CLEAR_GPTMP (CMD_TYPE,EMS_NO, PR_NO) select CMD_TYPE,EMS_NO, PR_NO from EMS_PRESS_CLEAR_INC_EXT;

delete from EMS_PRESS_CLEAR using EMS_PRESS_CLEAR_GPTMP where EMS_PRESS_CLEAR_GPTMP.EMS_NO=EMS_PRESS_CLEAR.EMS_NO AND EMS_PRESS_CLEAR_GPTMP.PR_NO=EMS_PRESS_CLEAR.PR_NO ;

insert into EMS_PRESS_CLEAR(EMS_NO,PR_NO,PR_COUNT,PR_CUSTOMS,PR_DEPARTMENT,PR_DATE) select EMS_NO,PR_NO,PR_COUNT,PR_CUSTOMS,PR_DEPARTMENT,PR_DATE from EMS_PRESS_CLEAR_INC_EXT where CMD_TYPE='I';

delete from EMS_PRESS_CLEAR_GPTMP;

\timing
