\echo ------------------EMS_DCR_CONSUME----------------
select now();
\timing
insert into EMS_DCR_CONSUME_GPTMP (CMD_TYPE,EMS_NO, EXG_NO, EXG_VERSION, IMG_NO, MODIFY_TIMES) select CMD_TYPE,EMS_NO, EXG_NO, EXG_VERSION, IMG_NO, MODIFY_TIMES from EMS_DCR_CONSUME_INC_EXT;

delete from EMS_DCR_CONSUME using EMS_DCR_CONSUME_GPTMP where EMS_DCR_CONSUME_GPTMP.EMS_NO=EMS_DCR_CONSUME.EMS_NO AND EMS_DCR_CONSUME_GPTMP.EXG_NO=EMS_DCR_CONSUME.EXG_NO AND EMS_DCR_CONSUME_GPTMP.EXG_VERSION=EMS_DCR_CONSUME.EXG_VERSION AND EMS_DCR_CONSUME_GPTMP.IMG_NO=EMS_DCR_CONSUME.IMG_NO AND EMS_DCR_CONSUME_GPTMP.MODIFY_TIMES=EMS_DCR_CONSUME.MODIFY_TIMES ;

insert into EMS_DCR_CONSUME(EMS_NO,EXG_NO,EXG_VERSION,IMG_NO,MODIFY_TIMES,DEC_CM,DEC_DM,OTHER_CM,OTHER_DM,CM_MARK,PRODUCT_MARK,PRODUCT_TYPE,MODIFY_MARK,CONTROL_MARK,NOTE,ETL_MARK) select EMS_NO,EXG_NO,EXG_VERSION,IMG_NO,MODIFY_TIMES,DEC_CM,DEC_DM,OTHER_CM,OTHER_DM,CM_MARK,PRODUCT_MARK,PRODUCT_TYPE,MODIFY_MARK,CONTROL_MARK,NOTE,ETL_MARK from EMS_DCR_CONSUME_INC_EXT where CMD_TYPE='I';

delete from EMS_DCR_CONSUME_GPTMP;

\timing
