\echo ------------------EMS_PRESS----------------
select now();
\timing
insert into EMS_PRESS_GPTMP (CMD_TYPE,PARA_TYPE, PARA_NAME) select CMD_TYPE,PARA_TYPE, PARA_NAME from EMS_PRESS_INC_EXT;

delete from EMS_PRESS using EMS_PRESS_GPTMP where EMS_PRESS_GPTMP.PARA_TYPE=EMS_PRESS.PARA_TYPE AND EMS_PRESS_GPTMP.PARA_NAME=EMS_PRESS.PARA_NAME ;

insert into EMS_PRESS(PARA_TYPE,PARA_ID,PARA_NAME,PARA_EXP,PARA_FLAG,PARA_VALUE,PARA_MARK) select PARA_TYPE,PARA_ID,PARA_NAME,PARA_EXP,PARA_FLAG,PARA_VALUE,PARA_MARK from EMS_PRESS_INC_EXT where CMD_TYPE='I';

delete from EMS_PRESS_GPTMP;

\timing
