\echo ------------------ENTRY_WORKFLOW----------------
select now();
\timing
insert into ENTRY_WORKFLOW_GPTMP (CMD_TYPE,ENTRY_ID, STEP_ID, CREATE_DATE) select CMD_TYPE,ENTRY_ID, STEP_ID, CREATE_DATE from ENTRY_WORKFLOW_INC_EXT;

delete from ENTRY_WORKFLOW using ENTRY_WORKFLOW_GPTMP where ENTRY_WORKFLOW_GPTMP.ENTRY_ID=ENTRY_WORKFLOW.ENTRY_ID AND ENTRY_WORKFLOW_GPTMP.STEP_ID=ENTRY_WORKFLOW.STEP_ID AND ENTRY_WORKFLOW_GPTMP.CREATE_DATE=ENTRY_WORKFLOW.CREATE_DATE ;

insert into ENTRY_WORKFLOW(ENTRY_ID,STEP_ID,CREATE_DATE,PROC_POS,STATUS_CODE,PROC_ER,PROC_RESULT,PREV_POS,PREV_ER,RECHK_MARK,RECHK_COMM) select ENTRY_ID,STEP_ID,CREATE_DATE,PROC_POS,STATUS_CODE,PROC_ER,PROC_RESULT,PREV_POS,PREV_ER,RECHK_MARK,RECHK_COMM from ENTRY_WORKFLOW_INC_EXT where CMD_TYPE='I';

delete from ENTRY_WORKFLOW_GPTMP;

\timing
