\echo ------------------ENTRY_PROC_LOG----------------
select now();
\timing
insert into ENTRY_PROC_LOG_GPTMP (CMD_TYPE,ENTRY_ID, OP_TIME, OP_STEP) select CMD_TYPE,ENTRY_ID, OP_TIME, OP_STEP from ENTRY_PROC_LOG_INC_EXT;

delete from ENTRY_PROC_LOG using ENTRY_PROC_LOG_GPTMP where ENTRY_PROC_LOG_GPTMP.ENTRY_ID=ENTRY_PROC_LOG.ENTRY_ID AND ENTRY_PROC_LOG_GPTMP.OP_TIME=ENTRY_PROC_LOG.OP_TIME AND ENTRY_PROC_LOG_GPTMP.OP_STEP=ENTRY_PROC_LOG.OP_STEP ;

insert into ENTRY_PROC_LOG(ENTRY_ID,OP_TIME,OP_STEP,OP_TYPE,OP_SOURCE,OP_DESCRIPTION) select ENTRY_ID,OP_TIME,OP_STEP,OP_TYPE,OP_SOURCE,OP_DESCRIPTION from ENTRY_PROC_LOG_INC_EXT where CMD_TYPE='I';

delete from ENTRY_PROC_LOG_GPTMP;

\timing
