\echo ------------------ENTRY_CENTRY_SELECT_DEL----------------
select now();
\timing
insert into ENTRY_CENTRY_SELECT_DEL_GPTMP (CMD_TYPE,ENTRY_ID, OP_TIME) select CMD_TYPE,ENTRY_ID, OP_TIME from ENTRY_CENTRY_SELECT_DEL_INC_EXT;

delete from ENTRY_CENTRY_SELECT_DEL using ENTRY_CENTRY_SELECT_DEL_GPTMP where ENTRY_CENTRY_SELECT_DEL_GPTMP.ENTRY_ID=ENTRY_CENTRY_SELECT_DEL.ENTRY_ID AND ENTRY_CENTRY_SELECT_DEL_GPTMP.OP_TIME=ENTRY_CENTRY_SELECT_DEL.OP_TIME ;

insert into ENTRY_CENTRY_SELECT_DEL(ENTRY_ID,OP_TIME,CREATE_DATE,DECL_PORT,I_E_FLAG,TRADE_CO,AGENT_CODE,TRADE_NAME,AGENT_NAME,OP_ID,SEL_RESULT,RSK_TYPE,RSK_CREATE_DATE,RSK_TYPE_DESC,MANUAL_ARV,OP_ER) select ENTRY_ID,OP_TIME,CREATE_DATE,DECL_PORT,I_E_FLAG,TRADE_CO,AGENT_CODE,TRADE_NAME,AGENT_NAME,OP_ID,SEL_RESULT,RSK_TYPE,RSK_CREATE_DATE,RSK_TYPE_DESC,MANUAL_ARV,OP_ER from ENTRY_CENTRY_SELECT_DEL_INC_EXT where CMD_TYPE='I';

delete from ENTRY_CENTRY_SELECT_DEL_GPTMP;

\timing
