\echo ------------------ENTRY_CERTIFICATE_LOG----------------
select now();
\timing
insert into ENTRY_CERTIFICATE_LOG_GPTMP (CMD_TYPE,ENTRY_ID, DOCU_CODE, CERT_CODE, OP_TIME) select CMD_TYPE,ENTRY_ID, DOCU_CODE, CERT_CODE, OP_TIME from ENTRY_CERTIFICATE_LOG_INC_EXT;

delete from ENTRY_CERTIFICATE_LOG using ENTRY_CERTIFICATE_LOG_GPTMP where ENTRY_CERTIFICATE_LOG_GPTMP.ENTRY_ID=ENTRY_CERTIFICATE_LOG.ENTRY_ID AND ENTRY_CERTIFICATE_LOG_GPTMP.DOCU_CODE=ENTRY_CERTIFICATE_LOG.DOCU_CODE AND ENTRY_CERTIFICATE_LOG_GPTMP.CERT_CODE=ENTRY_CERTIFICATE_LOG.CERT_CODE AND ENTRY_CERTIFICATE_LOG_GPTMP.OP_TIME=ENTRY_CERTIFICATE_LOG.OP_TIME ;

insert into ENTRY_CERTIFICATE_LOG(ENTRY_ID,DOCU_CODE,CERT_CODE,OP_TIME) select ENTRY_ID,DOCU_CODE,CERT_CODE,OP_TIME from ENTRY_CERTIFICATE_LOG_INC_EXT where CMD_TYPE='I';

delete from ENTRY_CERTIFICATE_LOG_GPTMP;

\timing
