\echo ------------------ENTRY_OP_LOG----------------
select now();
\timing
insert into ENTRY_OP_LOG_GPTMP (CMD_TYPE,ENTRY_ID, OP_TIME) select CMD_TYPE,ENTRY_ID, OP_TIME from ENTRY_OP_LOG_INC_EXT;

delete from ENTRY_OP_LOG using ENTRY_OP_LOG_GPTMP where ENTRY_OP_LOG_GPTMP.ENTRY_ID=ENTRY_OP_LOG.ENTRY_ID AND ENTRY_OP_LOG_GPTMP.OP_TIME=ENTRY_OP_LOG.OP_TIME ;

insert into ENTRY_OP_LOG(ENTRY_ID,OP_TIME,OP_TYPE,OP_ER,SRV_PORT) select ENTRY_ID,OP_TIME,OP_TYPE,OP_ER,SRV_PORT from ENTRY_OP_LOG_INC_EXT where CMD_TYPE='I';

delete from ENTRY_OP_LOG_GPTMP;

\timing
