\echo ------------------ENTRY_GPM_RTX_SENDLOG----------------
select now();
\timing
insert into ENTRY_GPM_RTX_SENDLOG_GPTMP (CMD_TYPE,ENTRY_ID, SIGN_TYPE, PROC_MODE, SEND_DATE) select CMD_TYPE,ENTRY_ID, SIGN_TYPE, PROC_MODE, SEND_DATE from ENTRY_GPM_RTX_SENDLOG_INC_EXT;

delete from ENTRY_GPM_RTX_SENDLOG using ENTRY_GPM_RTX_SENDLOG_GPTMP where ENTRY_GPM_RTX_SENDLOG_GPTMP.ENTRY_ID=ENTRY_GPM_RTX_SENDLOG.ENTRY_ID AND ENTRY_GPM_RTX_SENDLOG_GPTMP.SIGN_TYPE=ENTRY_GPM_RTX_SENDLOG.SIGN_TYPE AND ENTRY_GPM_RTX_SENDLOG_GPTMP.PROC_MODE=ENTRY_GPM_RTX_SENDLOG.PROC_MODE AND ENTRY_GPM_RTX_SENDLOG_GPTMP.SEND_DATE=ENTRY_GPM_RTX_SENDLOG.SEND_DATE ;

insert into ENTRY_GPM_RTX_SENDLOG(ENTRY_ID,SIGN_TYPE,PROC_MODE,SEND_DATE,SEND_FILE_NAME,SEND_ER) select ENTRY_ID,SIGN_TYPE,PROC_MODE,SEND_DATE,SEND_FILE_NAME,SEND_ER from ENTRY_GPM_RTX_SENDLOG_INC_EXT where CMD_TYPE='I';

delete from ENTRY_GPM_RTX_SENDLOG_GPTMP;

\timing
