\echo ------------------ENTRY_AUTOREL_ERR_LIST----------------
select now();
\timing
insert into ENTRY_AUTOREL_ERR_LIST_GPTMP (CMD_TYPE,ENTRY_ID) select CMD_TYPE,ENTRY_ID from ENTRY_AUTOREL_ERR_LIST_INC_EXT;

delete from ENTRY_AUTOREL_ERR_LIST using ENTRY_AUTOREL_ERR_LIST_GPTMP where ENTRY_AUTOREL_ERR_LIST_GPTMP.ENTRY_ID=ENTRY_AUTOREL_ERR_LIST.ENTRY_ID ;

insert into ENTRY_AUTOREL_ERR_LIST(ENTRY_ID,I_E_FLAG,DECL_PORT,TRADE_CO,TRADE_NAME,AGENT_CODE,AGENT_NAME,CREATE_DATE,DESCRIPTION) select ENTRY_ID,I_E_FLAG,DECL_PORT,TRADE_CO,TRADE_NAME,AGENT_CODE,AGENT_NAME,CREATE_DATE,DESCRIPTION from ENTRY_AUTOREL_ERR_LIST_INC_EXT where CMD_TYPE='I';

delete from ENTRY_AUTOREL_ERR_LIST_GPTMP;

\timing
