\echo ------------------ENTRY_CONTAINER_LOG----------------
select now();
\timing
insert into ENTRY_CONTAINER_LOG_GPTMP (CMD_TYPE,ENTRY_ID, CONTAINER_ID, OP_TIME) select CMD_TYPE,ENTRY_ID, CONTAINER_ID, OP_TIME from ENTRY_CONTAINER_LOG_INC_EXT;

delete from ENTRY_CONTAINER_LOG using ENTRY_CONTAINER_LOG_GPTMP where ENTRY_CONTAINER_LOG_GPTMP.ENTRY_ID=ENTRY_CONTAINER_LOG.ENTRY_ID AND ENTRY_CONTAINER_LOG_GPTMP.CONTAINER_ID=ENTRY_CONTAINER_LOG.CONTAINER_ID AND ENTRY_CONTAINER_LOG_GPTMP.OP_TIME=ENTRY_CONTAINER_LOG.OP_TIME ;

insert into ENTRY_CONTAINER_LOG(ENTRY_ID,CONTAINER_ID,CONTAINER_WT,OP_TIME) select ENTRY_ID,CONTAINER_ID,CONTAINER_WT,OP_TIME from ENTRY_CONTAINER_LOG_INC_EXT where CMD_TYPE='I';

delete from ENTRY_CONTAINER_LOG_GPTMP;

\timing
