\echo ------------------ENTRY_GPM_RTX----------------
select now();
\timing
insert into ENTRY_GPM_RTX_GPTMP (CMD_TYPE,SIGN_TYPE, ENTRY_ID, PROC_MODE) select CMD_TYPE,SIGN_TYPE, ENTRY_ID, PROC_MODE from ENTRY_GPM_RTX_INC_EXT;

delete from ENTRY_GPM_RTX using ENTRY_GPM_RTX_GPTMP where ENTRY_GPM_RTX_GPTMP.SIGN_TYPE=ENTRY_GPM_RTX.SIGN_TYPE AND ENTRY_GPM_RTX_GPTMP.ENTRY_ID=ENTRY_GPM_RTX.ENTRY_ID AND ENTRY_GPM_RTX_GPTMP.PROC_MODE=ENTRY_GPM_RTX.PROC_MODE ;

insert into ENTRY_GPM_RTX(SIGN_TYPE,ENTRY_ID,PROC_MODE,PROC_DATE) select SIGN_TYPE,ENTRY_ID,PROC_MODE,PROC_DATE from ENTRY_GPM_RTX_INC_EXT where CMD_TYPE='I';

delete from ENTRY_GPM_RTX_GPTMP;

\timing
