\echo ------------------ENTRY_MODI_LOG----------------
select now();
\timing
insert into ENTRY_MODI_LOG_GPTMP (CMD_TYPE,ENTRY_ID, OP_TIME, MODI_TYPE, ITEM_NAME) select CMD_TYPE,ENTRY_ID, OP_TIME, MODI_TYPE, ITEM_NAME from ENTRY_MODI_LOG_INC_EXT;

delete from ENTRY_MODI_LOG using ENTRY_MODI_LOG_GPTMP where ENTRY_MODI_LOG_GPTMP.ENTRY_ID=ENTRY_MODI_LOG.ENTRY_ID AND ENTRY_MODI_LOG_GPTMP.OP_TIME=ENTRY_MODI_LOG.OP_TIME AND ENTRY_MODI_LOG_GPTMP.MODI_TYPE=ENTRY_MODI_LOG.MODI_TYPE AND ENTRY_MODI_LOG_GPTMP.ITEM_NAME=ENTRY_MODI_LOG.ITEM_NAME ;

insert into ENTRY_MODI_LOG(ENTRY_ID,OP_TIME,MODI_TYPE,ITEM_NAME,ITEM_SOURCE,NOTES,ITEM_CURRENT) select ENTRY_ID,OP_TIME,MODI_TYPE,ITEM_NAME,ITEM_SOURCE,NOTES,ITEM_CURRENT from ENTRY_MODI_LOG_INC_EXT where CMD_TYPE='I';

delete from ENTRY_MODI_LOG_GPTMP;

\timing
