\echo ------------------ENTRY_CENTRY_SELECT----------------
select now();
\timing
insert into ENTRY_CENTRY_SELECT_GPTMP (CMD_TYPE,ENTRY_ID) select CMD_TYPE,ENTRY_ID from ENTRY_CENTRY_SELECT_INC_EXT;

delete from ENTRY_CENTRY_SELECT using ENTRY_CENTRY_SELECT_GPTMP where ENTRY_CENTRY_SELECT_GPTMP.ENTRY_ID=ENTRY_CENTRY_SELECT.ENTRY_ID ;

insert into ENTRY_CENTRY_SELECT(ENTRY_ID,CREATE_DATE,DECL_PORT,I_E_FLAG,TRADE_CO,AGENT_CODE,TRADE_NAME,AGENT_NAME,OP_ID,SEL_RESULT,RSK_TYPE,RSK_CREATE_DATE,RSK_TYPE_DESC,MANUAL_ARV) select ENTRY_ID,CREATE_DATE,DECL_PORT,I_E_FLAG,TRADE_CO,AGENT_CODE,TRADE_NAME,AGENT_NAME,OP_ID,SEL_RESULT,RSK_TYPE,RSK_CREATE_DATE,RSK_TYPE_DESC,MANUAL_ARV from ENTRY_CENTRY_SELECT_INC_EXT where CMD_TYPE='I';

delete from ENTRY_CENTRY_SELECT_GPTMP;

\timing
