\echo ------------------EPA_SCARP_CERT----------------
select now();
\timing
insert into EPA_SCARP_CERT_GPTMP (CMD_TYPE,CERTIFICATE_NO) select CMD_TYPE,CERTIFICATE_NO from EPA_SCARP_CERT_INC_EXT;

delete from EPA_SCARP_CERT using EPA_SCARP_CERT_GPTMP where EPA_SCARP_CERT_GPTMP.CERTIFICATE_NO=EPA_SCARP_CERT.CERTIFICATE_NO ;

insert into EPA_SCARP_CERT(CERTIFICATE_NO,TRANSFER_NUM,ISSUE_ORGANIZATION,ISSUE_DATE,BEGIN_DATE,END_DATE,OWNER_REG_NO,OWNER_CODE,OWNER_NAME,TRADE_REG_NO,TRADE_CO,TRADE_NAME,CODE_TS,G_NAME,G_QTY,G_UNIT,ORIGIN_COUNTRY,TRADE_MODE,I_E_PORT1,I_E_PORT2,I_E_PORT3,NOTE,OP_MODE,RECV_DATE) select CERTIFICATE_NO,TRANSFER_NUM,ISSUE_ORGANIZATION,ISSUE_DATE,BEGIN_DATE,END_DATE,OWNER_REG_NO,OWNER_CODE,OWNER_NAME,TRADE_REG_NO,TRADE_CO,TRADE_NAME,CODE_TS,G_NAME,G_QTY,G_UNIT,ORIGIN_COUNTRY,TRADE_MODE,I_E_PORT1,I_E_PORT2,I_E_PORT3,NOTE,OP_MODE,RECV_DATE from EPA_SCARP_CERT_INC_EXT where CMD_TYPE='I';

delete from EPA_SCARP_CERT_GPTMP;

\timing
