\echo ------------------ERR_LOG----------------
select now();
\timing
insert into ERR_LOG_GPTMP (CMD_TYPE,ENTRY_ID, CREATE_DATE) select CMD_TYPE,ENTRY_ID, CREATE_DATE from ERR_LOG_INC_EXT;

delete from ERR_LOG using ERR_LOG_GPTMP where ERR_LOG_GPTMP.ENTRY_ID=ERR_LOG.ENTRY_ID AND ERR_LOG_GPTMP.CREATE_DATE=ERR_LOG.CREATE_DATE ;

insert into ERR_LOG(ENTRY_ID,CREATE_DATE,SOURCE,DESCRIPTION) select ENTRY_ID,CREATE_DATE,SOURCE,DESCRIPTION from ERR_LOG_INC_EXT where CMD_TYPE='I';

delete from ERR_LOG_GPTMP;

\timing
