\echo ------------------EX_CDL_MNL_DEDUCT----------------
select now();
\timing
insert into EX_CDL_MNL_DEDUCT_GPTMP (CMD_TYPE,MANUAL_NO, ENTRY_ID, G_NO) select CMD_TYPE,MANUAL_NO, ENTRY_ID, G_NO from EX_CDL_MNL_DEDUCT_INC_EXT;

delete from EX_CDL_MNL_DEDUCT using EX_CDL_MNL_DEDUCT_GPTMP where EX_CDL_MNL_DEDUCT_GPTMP.MANUAL_NO=EX_CDL_MNL_DEDUCT.MANUAL_NO AND EX_CDL_MNL_DEDUCT_GPTMP.ENTRY_ID=EX_CDL_MNL_DEDUCT.ENTRY_ID AND EX_CDL_MNL_DEDUCT_GPTMP.G_NO=EX_CDL_MNL_DEDUCT.G_NO ;

insert into EX_CDL_MNL_DEDUCT(MANUAL_NO,CONTR_ITEM,ENTRY_ID,ENTRY_ITEM,I_E_PORT,I_E_DATE,G_NO,IN_QTY,I_ACCOUNT,I_CURR,DUTY_MODE,VERIFY_MODE,VERIFY_DATE,VERIFY_ER) select MANUAL_NO,CONTR_ITEM,ENTRY_ID,ENTRY_ITEM,I_E_PORT,I_E_DATE,G_NO,IN_QTY,I_ACCOUNT,I_CURR,DUTY_MODE,VERIFY_MODE,VERIFY_DATE,VERIFY_ER from EX_CDL_MNL_DEDUCT_INC_EXT where CMD_TYPE='I';

delete from EX_CDL_MNL_DEDUCT_GPTMP;

\timing
