\echo ------------------EX_CONTA_ENTRY_CHK----------------
select now();
\timing
insert into EX_CONTA_ENTRY_CHK_GPTMP (CMD_TYPE,CONTA_ID, BILL_NO, REC_NO, ENTRY_ID) select CMD_TYPE,CONTA_ID, BILL_NO, REC_NO, ENTRY_ID from EX_CONTA_ENTRY_CHK_INC_EXT;

delete from EX_CONTA_ENTRY_CHK using EX_CONTA_ENTRY_CHK_GPTMP where EX_CONTA_ENTRY_CHK_GPTMP.CONTA_ID=EX_CONTA_ENTRY_CHK.CONTA_ID AND EX_CONTA_ENTRY_CHK_GPTMP.BILL_NO=EX_CONTA_ENTRY_CHK.BILL_NO AND EX_CONTA_ENTRY_CHK_GPTMP.REC_NO=EX_CONTA_ENTRY_CHK.REC_NO AND EX_CONTA_ENTRY_CHK_GPTMP.ENTRY_ID=EX_CONTA_ENTRY_CHK.ENTRY_ID ;

insert into EX_CONTA_ENTRY_CHK(CONTA_ID,BILL_NO,REC_NO,ENTRY_ID,CHK_DATE,CHK_ER) select CONTA_ID,BILL_NO,REC_NO,ENTRY_ID,CHK_DATE,CHK_ER from EX_CONTA_ENTRY_CHK_INC_EXT where CMD_TYPE='I';

delete from EX_CONTA_ENTRY_CHK_GPTMP;

\timing
