\echo ------------------EX_ELE_LIST----------------
select now();
\timing
insert into EX_ELE_LIST_GPTMP (CMD_TYPE,LICENSE_NO, L_G_NO) select CMD_TYPE,LICENSE_NO, L_G_NO from EX_ELE_LIST_INC_EXT;

delete from EX_ELE_LIST using EX_ELE_LIST_GPTMP where EX_ELE_LIST_GPTMP.LICENSE_NO=EX_ELE_LIST.LICENSE_NO AND EX_ELE_LIST_GPTMP.L_G_NO=EX_ELE_LIST.L_G_NO ;

insert into EX_ELE_LIST(LICENSE_NO,L_G_NO,G_MODEL,LIC_QTY,LIC_USD_PRICE) select LICENSE_NO,L_G_NO,G_MODEL,LIC_QTY,LIC_USD_PRICE from EX_ELE_LIST_INC_EXT where CMD_TYPE='I';

delete from EX_ELE_LIST_GPTMP;

\timing
