\echo ------------------EX_FASCICLE_LIST----------------
select now();
\timing
insert into EX_FASCICLE_LIST_GPTMP (CMD_TYPE,FASCICLE_NO, CONTR_ITEM) select CMD_TYPE,FASCICLE_NO, CONTR_ITEM from EX_FASCICLE_LIST_INC_EXT;

delete from EX_FASCICLE_LIST using EX_FASCICLE_LIST_GPTMP where EX_FASCICLE_LIST_GPTMP.FASCICLE_NO=EX_FASCICLE_LIST.FASCICLE_NO AND EX_FASCICLE_LIST_GPTMP.CONTR_ITEM=EX_FASCICLE_LIST.CONTR_ITEM ;

insert into EX_FASCICLE_LIST(MANUAL_NO,FASCICLE_NO,CONTR_ITEM,APPR_QTY,FACT_QTY) select MANUAL_NO,FASCICLE_NO,CONTR_ITEM,APPR_QTY,FACT_QTY from EX_FASCICLE_LIST_INC_EXT where CMD_TYPE='I';

delete from EX_FASCICLE_LIST_GPTMP;

\timing
