\echo ------------------EX_TRANS_GOODS_CONTA_REL----------------
select now();
\timing
insert into EX_TRANS_GOODS_CONTA_REL_GPTMP (CMD_TYPE,PRE_NO, RECORD_NUMBER, G_NO, CONTA_NO) select CMD_TYPE,PRE_NO, RECORD_NUMBER, G_NO, CONTA_NO from EX_TRANS_GOODS_CONTA_REL_INC_EXT;

delete from EX_TRANS_GOODS_CONTA_REL using EX_TRANS_GOODS_CONTA_REL_GPTMP where EX_TRANS_GOODS_CONTA_REL_GPTMP.PRE_NO=EX_TRANS_GOODS_CONTA_REL.PRE_NO AND EX_TRANS_GOODS_CONTA_REL_GPTMP.RECORD_NUMBER=EX_TRANS_GOODS_CONTA_REL.RECORD_NUMBER AND EX_TRANS_GOODS_CONTA_REL_GPTMP.G_NO=EX_TRANS_GOODS_CONTA_REL.G_NO AND EX_TRANS_GOODS_CONTA_REL_GPTMP.CONTA_NO=EX_TRANS_GOODS_CONTA_REL.CONTA_NO ;

insert into EX_TRANS_GOODS_CONTA_REL(PRE_NO,RECORD_NUMBER,G_NO,CONTA_NO,CONTA_GOODS_COUNT,CONTA_GOODS_WEIGHT,SEND_PORT,RECV_PORT) select PRE_NO,RECORD_NUMBER,G_NO,CONTA_NO,CONTA_GOODS_COUNT,CONTA_GOODS_WEIGHT,SEND_PORT,RECV_PORT from EX_TRANS_GOODS_CONTA_REL_INC_EXT where CMD_TYPE='I';

delete from EX_TRANS_GOODS_CONTA_REL_GPTMP;

\timing
