\echo ------------------EX_TRN_CONTA_ENTRY_ARV----------------
select now();
\timing
insert into EX_TRN_CONTA_ENTRY_ARV_GPTMP (CMD_TYPE,ENTRY_ID, CONTA_ID) select CMD_TYPE,ENTRY_ID, CONTA_ID from EX_TRN_CONTA_ENTRY_ARV_INC_EXT;

delete from EX_TRN_CONTA_ENTRY_ARV using EX_TRN_CONTA_ENTRY_ARV_GPTMP where EX_TRN_CONTA_ENTRY_ARV_GPTMP.ENTRY_ID=EX_TRN_CONTA_ENTRY_ARV.ENTRY_ID AND EX_TRN_CONTA_ENTRY_ARV_GPTMP.CONTA_ID=EX_TRN_CONTA_ENTRY_ARV.CONTA_ID ;

insert into EX_TRN_CONTA_ENTRY_ARV(ENTRY_ID,CONTA_ID,CUSTOMS_CODE,TRAF_MODE,TRAF_NAME,VOYAGE_NO,BILL_NO,PACK_NO,GROSS_WT,ARV_FLAG,TRN_MODE) select ENTRY_ID,CONTA_ID,CUSTOMS_CODE,TRAF_MODE,TRAF_NAME,VOYAGE_NO,BILL_NO,PACK_NO,GROSS_WT,ARV_FLAG,TRN_MODE from EX_TRN_CONTA_ENTRY_ARV_INC_EXT where CMD_TYPE='I';

delete from EX_TRN_CONTA_ENTRY_ARV_GPTMP;

\timing
