\echo ------------------EX_TRAN_JOU----------------
select now();
\timing
insert into EX_TRAN_JOU_GPTMP (CMD_TYPE,ENTRY_ID, G_NO) select CMD_TYPE,ENTRY_ID, G_NO from EX_TRAN_JOU_INC_EXT;

delete from EX_TRAN_JOU using EX_TRAN_JOU_GPTMP where EX_TRAN_JOU_GPTMP.ENTRY_ID=EX_TRAN_JOU.ENTRY_ID AND EX_TRAN_JOU_GPTMP.G_NO=EX_TRAN_JOU.G_NO ;

insert into EX_TRAN_JOU(I_E_PORT,ENTRY_ID,G_NO,ENTRY_LIC_NO,CODE_TS,G_NAME,G_MODEL,QTY_1,UNIT_NAME,USD_PRICE,REL_DATE,REL_TIME,REL_ER,AFTER_MARK,SEND_GEN_DATE,NOTE_S,SECURITY_ID) select I_E_PORT,ENTRY_ID,G_NO,ENTRY_LIC_NO,CODE_TS,G_NAME,G_MODEL,QTY_1,UNIT_NAME,USD_PRICE,REL_DATE,REL_TIME,REL_ER,AFTER_MARK,SEND_GEN_DATE,NOTE_S,SECURITY_ID from EX_TRAN_JOU_INC_EXT where CMD_TYPE='I';

delete from EX_TRAN_JOU_GPTMP;

\timing
