\echo ------------------EXAM_CONTA_END_LOG----------------
select now();
\timing
insert into EXAM_CONTA_END_LOG_GPTMP (CMD_TYPE,EXAM_REC_ID, END_TIME) select CMD_TYPE,EXAM_REC_ID, END_TIME from EXAM_CONTA_END_LOG_INC_EXT;

delete from EXAM_CONTA_END_LOG using EXAM_CONTA_END_LOG_GPTMP where EXAM_CONTA_END_LOG_GPTMP.EXAM_REC_ID=EXAM_CONTA_END_LOG.EXAM_REC_ID AND EXAM_CONTA_END_LOG_GPTMP.END_TIME=EXAM_CONTA_END_LOG.END_TIME ;

insert into EXAM_CONTA_END_LOG(EXAM_REC_ID,RSK_NO,END_ER,END_TIME,END_REASON) select EXAM_REC_ID,RSK_NO,END_ER,END_TIME,END_REASON from EXAM_CONTA_END_LOG_INC_EXT where CMD_TYPE='I';

delete from EXAM_CONTA_END_LOG_GPTMP;

\timing
