\echo ------------------EXC_EXAM----------------
select now();
\timing
insert into EXC_EXAM_GPTMP (CMD_TYPE,HXD_NO) select CMD_TYPE,HXD_NO from EXC_EXAM_INC_EXT;

delete from EXC_EXAM using EXC_EXAM_GPTMP where EXC_EXAM_GPTMP.HXD_NO=EXC_EXAM.HXD_NO ;

insert into EXC_EXAM(SEQ_NO,HXD_NO,ENTRY_ID,CUS_CODE,DECL_DATE,IMPLE_DATE,IMPLE_ER,RET_DATE,EXC_MARK,DELE_DATE,DELE_ER,DATA_SIGN) select SEQ_NO,HXD_NO,ENTRY_ID,CUS_CODE,DECL_DATE,IMPLE_DATE,IMPLE_ER,RET_DATE,EXC_MARK,DELE_DATE,DELE_ER,DATA_SIGN from EXC_EXAM_INC_EXT where CMD_TYPE='I';

delete from EXC_EXAM_GPTMP;

\timing
