\echo ------------------EXTERNAL_JOU----------------
select now();
\timing
insert into EXTERNAL_JOU_GPTMP (CMD_TYPE,MANUAL_NO, CUSTOMS_CODE, APPL_NO) select CMD_TYPE,MANUAL_NO, CUSTOMS_CODE, APPL_NO from EXTERNAL_JOU_INC_EXT;

delete from EXTERNAL_JOU using EXTERNAL_JOU_GPTMP where EXTERNAL_JOU_GPTMP.MANUAL_NO=EXTERNAL_JOU.MANUAL_NO AND EXTERNAL_JOU_GPTMP.CUSTOMS_CODE=EXTERNAL_JOU.CUSTOMS_CODE AND EXTERNAL_JOU_GPTMP.APPL_NO=EXTERNAL_JOU.APPL_NO ;

insert into EXTERNAL_JOU(MANUAL_NO,CUSTOMS_CODE,APPL_NO,FASCICLE_NO,E_DATE,APPL_ER,APPL_DATE,RETURN_DATE,RETURN_FLAG,PASSWORD,NOTE_S) select MANUAL_NO,CUSTOMS_CODE,APPL_NO,FASCICLE_NO,E_DATE,APPL_ER,APPL_DATE,RETURN_DATE,RETURN_FLAG,PASSWORD,NOTE_S from EXTERNAL_JOU_INC_EXT where CMD_TYPE='I';

delete from EXTERNAL_JOU_GPTMP;

\timing
