\echo ------------------FASCICLE_HEAD----------------
select now();
\timing
insert into FASCICLE_HEAD_GPTMP (CMD_TYPE,FASCICLE_NO) select CMD_TYPE,FASCICLE_NO from FASCICLE_HEAD_INC_EXT;

delete from FASCICLE_HEAD using FASCICLE_HEAD_GPTMP where FASCICLE_HEAD_GPTMP.FASCICLE_NO=FASCICLE_HEAD.FASCICLE_NO ;

insert into FASCICLE_HEAD(MANUAL_NO,FASCICLE_NO,PRE_FASCICLE_NO,I_E_PORT,TYPE_ER,TYPE_DATE,LIMIT_DATE,TRADE_CO,CHK_ER,RECHK_ER,PR_DATE,FASCICLE_TYPE,EXE_MARK,CONTR_IN,CONTR_OUT,IN_PNT,EX_PNT,SUPV_MARK,NOTE_S) select MANUAL_NO,FASCICLE_NO,PRE_FASCICLE_NO,I_E_PORT,TYPE_ER,TYPE_DATE,LIMIT_DATE,TRADE_CO,CHK_ER,RECHK_ER,PR_DATE,FASCICLE_TYPE,EXE_MARK,CONTR_IN,CONTR_OUT,IN_PNT,EX_PNT,SUPV_MARK,NOTE_S from FASCICLE_HEAD_INC_EXT where CMD_TYPE='I';

delete from FASCICLE_HEAD_GPTMP;

\timing
