\echo ------------------FCB_LIST----------------
select now();
\timing
insert into FCB_LIST_GPTMP (CMD_TYPE,FCB_ID, G_NO) select CMD_TYPE,FCB_ID, G_NO from FCB_LIST_INC_EXT;

delete from FCB_LIST using FCB_LIST_GPTMP where FCB_LIST_GPTMP.FCB_ID=FCB_LIST.FCB_ID AND FCB_LIST_GPTMP.G_NO=FCB_LIST.G_NO ;

insert into FCB_LIST(FCB_ID,G_NO,CODE_TS,G_NAME,WRAP_TYPE,PACK_NO,GROSS_WT,PRICE,CURR,MARK,CONSIGNOR,CONSIGNEE,UCR,UNDG,FREE_TEXT,PORT_CUS,MAIN_CUS,BILL_NO) select FCB_ID,G_NO,CODE_TS,G_NAME,WRAP_TYPE,PACK_NO,GROSS_WT,PRICE,CURR,MARK,CONSIGNOR,CONSIGNEE,UCR,UNDG,FREE_TEXT,PORT_CUS,MAIN_CUS,BILL_NO from FCB_LIST_INC_EXT where CMD_TYPE='I';

delete from FCB_LIST_GPTMP;

\timing
