\echo ------------------FCB_CHK----------------
select now();
\timing
insert into FCB_CHK_GPTMP (CMD_TYPE,FCB_ID, FORM_FLAG, ENTRY_ID) select CMD_TYPE,FCB_ID, FORM_FLAG, ENTRY_ID from FCB_CHK_INC_EXT;

delete from FCB_CHK using FCB_CHK_GPTMP where FCB_CHK_GPTMP.FCB_ID=FCB_CHK.FCB_ID AND FCB_CHK_GPTMP.FORM_FLAG=FCB_CHK.FORM_FLAG AND FCB_CHK_GPTMP.ENTRY_ID=FCB_CHK.ENTRY_ID ;

insert into FCB_CHK(FCB_ID,FORM_FLAG,ENTRY_ID,CUSTOMS_CODE,PACK_NO,GROSS_WT,CHK_ER,CHK_DATE,REL_ER,REL_DATE,RTX_ER,RTX_DATE,NOTE) select FCB_ID,FORM_FLAG,ENTRY_ID,CUSTOMS_CODE,PACK_NO,GROSS_WT,CHK_ER,CHK_DATE,REL_ER,REL_DATE,RTX_ER,RTX_DATE,NOTE from FCB_CHK_INC_EXT where CMD_TYPE='I';

delete from FCB_CHK_GPTMP;

\timing
