\echo ------------------FCB_HEAD----------------
select now();
\timing
insert into FCB_HEAD_GPTMP (CMD_TYPE,FCB_ID) select CMD_TYPE,FCB_ID from FCB_HEAD_INC_EXT;

delete from FCB_HEAD using FCB_HEAD_GPTMP where FCB_HEAD_GPTMP.FCB_ID=FCB_HEAD.FCB_ID ;

insert into FCB_HEAD(FCB_ID,I_E_FLAG,I_E_DATE,FCB_MODE,GOODS_CHK_FLAG,PORT_CUS,MAIN_CUS,APPL_CODE,APPL_NAME,VE_CUSTOMS_NO,VE_NAME,VE_NO1,VE_WT,VE_TYPE,CONSIGNER,CO_REG_NO,CONTRACTOR,CONTRACTOR_OUTER,CONTRACTOR_ADD,DR_CUSTOMS_NO,DR_NAME,PHONE_NO,TRADE_MODE,VE_FRAME_NO,PACK_NO,GROSS_WT,LOAD_PLACE,DISCHARGE_PLACE,ORIGIN_COUNTRY,DESTINATION,CONTR_NO,TRANSSHIPMENT_MARK,LICENSE_NO,BILL_NO,PERMISSIVE_TIME,INPUT_TIME,SUR_TIME,REAL_I_E_TIME,REL_TIME,ARRIVE_TIME,LEAVE_TIME,CANCEL_TIME,MODIFY_APPLY_MARK,TIME_STAMP,RISK_INFO,SYS_INFO,PORT_WT,MAIN_WT,EX_TRAF_MODE,CONTA_COUNT,CONTA_STD_COUNT,CONTA_EMPTY_COUNT,PRE_MARK,PRE_ID,ESEAL_KEY,HASH_SIGN,PRE_NO,VE_FRAME_WT,NOTE) select FCB_ID,I_E_FLAG,I_E_DATE,FCB_MODE,GOODS_CHK_FLAG,PORT_CUS,MAIN_CUS,APPL_CODE,APPL_NAME,VE_CUSTOMS_NO,VE_NAME,VE_NO1,VE_WT,VE_TYPE,CONSIGNER,CO_REG_NO,CONTRACTOR,CONTRACTOR_OUTER,CONTRACTOR_ADD,DR_CUSTOMS_NO,DR_NAME,PHONE_NO,TRADE_MODE,VE_FRAME_NO,PACK_NO,GROSS_WT,LOAD_PLACE,DISCHARGE_PLACE,ORIGIN_COUNTRY,DESTINATION,CONTR_NO,TRANSSHIPMENT_MARK,LICENSE_NO,BILL_NO,PERMISSIVE_TIME,INPUT_TIME,SUR_TIME,REAL_I_E_TIME,REL_TIME,ARRIVE_TIME,LEAVE_TIME,CANCEL_TIME,MODIFY_APPLY_MARK,TIME_STAMP,RISK_INFO,SYS_INFO,PORT_WT,MAIN_WT,EX_TRAF_MODE,CONTA_COUNT,CONTA_STD_COUNT,CONTA_EMPTY_COUNT,PRE_MARK,PRE_ID,ESEAL_KEY,HASH_SIGN,PRE_NO,VE_FRAME_WT,NOTE from FCB_HEAD_INC_EXT where CMD_TYPE='I';

delete from FCB_HEAD_GPTMP;

\timing
