\echo ------------------FCB_LIST_MODI----------------
select now();
\timing
insert into FCB_LIST_MODI_GPTMP (CMD_TYPE,FCB_ID, G_NO) select CMD_TYPE,FCB_ID, G_NO from FCB_LIST_MODI_INC_EXT;

delete from FCB_LIST_MODI using FCB_LIST_MODI_GPTMP where FCB_LIST_MODI_GPTMP.FCB_ID=FCB_LIST_MODI.FCB_ID AND FCB_LIST_MODI_GPTMP.G_NO=FCB_LIST_MODI.G_NO ;

insert into FCB_LIST_MODI(FCB_ID,G_NO,CODE_TS,G_NAME,WRAP_TYPE,PACK_NO,GROSS_WT,PRICE,CURR,MARK,CONSIGNOR,CONSIGNEE,UCR,UNDG,FREE_TEXT,BILL_NO) select FCB_ID,G_NO,CODE_TS,G_NAME,WRAP_TYPE,PACK_NO,GROSS_WT,PRICE,CURR,MARK,CONSIGNOR,CONSIGNEE,UCR,UNDG,FREE_TEXT,BILL_NO from FCB_LIST_MODI_INC_EXT where CMD_TYPE='I';

delete from FCB_LIST_MODI_GPTMP;

\timing
