\echo ------------------FCB_WORKFLOW----------------
select now();
\timing
insert into FCB_WORKFLOW_GPTMP (CMD_TYPE,FCB_ID, STEP_ID, CREATE_DATE) select CMD_TYPE,FCB_ID, STEP_ID, CREATE_DATE from FCB_WORKFLOW_INC_EXT;

delete from FCB_WORKFLOW using FCB_WORKFLOW_GPTMP where FCB_WORKFLOW_GPTMP.FCB_ID=FCB_WORKFLOW.FCB_ID AND FCB_WORKFLOW_GPTMP.STEP_ID=FCB_WORKFLOW.STEP_ID AND FCB_WORKFLOW_GPTMP.CREATE_DATE=FCB_WORKFLOW.CREATE_DATE ;

insert into FCB_WORKFLOW(FCB_ID,STEP_ID,CREATE_DATE,PROC_ER,PROC_RESULT,RECHK_COMM,PORT_CUS,MAIN_CUS) select FCB_ID,STEP_ID,CREATE_DATE,PROC_ER,PROC_RESULT,RECHK_COMM,PORT_CUS,MAIN_CUS from FCB_WORKFLOW_INC_EXT where CMD_TYPE='I';

delete from FCB_WORKFLOW_GPTMP;

\timing
