\echo ------------------FCB_HEAD_MODI----------------
select now();
\timing
insert into FCB_HEAD_MODI_GPTMP (CMD_TYPE,FCB_ID) select CMD_TYPE,FCB_ID from FCB_HEAD_MODI_INC_EXT;

delete from FCB_HEAD_MODI using FCB_HEAD_MODI_GPTMP where FCB_HEAD_MODI_GPTMP.FCB_ID=FCB_HEAD_MODI.FCB_ID ;

insert into FCB_HEAD_MODI(FCB_ID,PROCESS_STATUS,I_E_FLAG,I_E_DATE,FCB_MODE,GOODS_CHK_FLAG,PORT_CUS,MAIN_CUS,APPL_CODE,APPL_NAME,VE_CUSTOMS_NO,VE_NAME,VE_NO1,VE_WT,VE_TYPE,CONSIGNER,CO_REG_NO,CONTRACTOR,CONTRACTOR_OUTER,CONTRACTOR_ADD,DR_CUSTOMS_NO,DR_NAME,PHONE_NO,TRADE_MODE,VE_FRAME_NO,PACK_NO,GROSS_WT,LOAD_PLACE,DISCHARGE_PLACE,ORIGIN_COUNTRY,DESTINATION,CONTR_NO,TRANSSHIPMENT_MARK,LICENSE_NO,BILL_NO,INPUT_TIME,EX_TRAF_MODE,CONTA_COUNT,CONTA_STD_COUNT,CONTA_EMPTY_COUNT,PRE_MARK,PRE_ID,PRE_NO,VE_FRAME_WT,NOTE) select FCB_ID,PROCESS_STATUS,I_E_FLAG,I_E_DATE,FCB_MODE,GOODS_CHK_FLAG,PORT_CUS,MAIN_CUS,APPL_CODE,APPL_NAME,VE_CUSTOMS_NO,VE_NAME,VE_NO1,VE_WT,VE_TYPE,CONSIGNER,CO_REG_NO,CONTRACTOR,CONTRACTOR_OUTER,CONTRACTOR_ADD,DR_CUSTOMS_NO,DR_NAME,PHONE_NO,TRADE_MODE,VE_FRAME_NO,PACK_NO,GROSS_WT,LOAD_PLACE,DISCHARGE_PLACE,ORIGIN_COUNTRY,DESTINATION,CONTR_NO,TRANSSHIPMENT_MARK,LICENSE_NO,BILL_NO,INPUT_TIME,EX_TRAF_MODE,CONTA_COUNT,CONTA_STD_COUNT,CONTA_EMPTY_COUNT,PRE_MARK,PRE_ID,PRE_NO,VE_FRAME_WT,NOTE from FCB_HEAD_MODI_INC_EXT where CMD_TYPE='I';

delete from FCB_HEAD_MODI_GPTMP;

\timing
