\echo ------------------FEE_INVOICE----------------
select now();
\timing
insert into FEE_INVOICE_GPTMP (CMD_TYPE,MANUAL_NO, F_NO) select CMD_TYPE,MANUAL_NO, F_NO from FEE_INVOICE_INC_EXT;

delete from FEE_INVOICE using FEE_INVOICE_GPTMP where FEE_INVOICE_GPTMP.MANUAL_NO=FEE_INVOICE.MANUAL_NO AND FEE_INVOICE_GPTMP.F_NO=FEE_INVOICE.F_NO ;

insert into FEE_INVOICE(MANUAL_NO,F_NO,FEE_ID,CREATE_DATE,CHK_ER,TYPE_ER,TYPE_DATE,FINANCIAL_FLAG,FINANCIAL_DATE,BOOK_NO,FEE_AMT,NOTE_S) select MANUAL_NO,F_NO,FEE_ID,CREATE_DATE,CHK_ER,TYPE_ER,TYPE_DATE,FINANCIAL_FLAG,FINANCIAL_DATE,BOOK_NO,FEE_AMT,NOTE_S from FEE_INVOICE_INC_EXT where CMD_TYPE='I';

delete from FEE_INVOICE_GPTMP;

\timing
