\echo ------------------FORFEIT_FORM----------------
select now();
\timing
insert into FORFEIT_FORM_GPTMP (CMD_TYPE,FMS_ID) select CMD_TYPE,FMS_ID from FORFEIT_FORM_INC_EXT;

delete from FORFEIT_FORM using FORFEIT_FORM_GPTMP where FORFEIT_FORM_GPTMP.FMS_ID=FORFEIT_FORM.FMS_ID ;

insert into FORFEIT_FORM(FMS_ID,DEPARTMENT,DEPARTMENT_NOTE,DISTRICT_CODE,PAYER_NAME,FMS_CLASS,FMS_AMOUNT,OPER_CODE,LAW_ID,TAX_FLAG,LIMIT_DAY,FMS_MODE,CREATE_DATE,CUSTOMS_CODE,SECTION_ID,GROUP_ID) select FMS_ID,DEPARTMENT,DEPARTMENT_NOTE,DISTRICT_CODE,PAYER_NAME,FMS_CLASS,FMS_AMOUNT,OPER_CODE,LAW_ID,TAX_FLAG,LIMIT_DAY,FMS_MODE,CREATE_DATE,CUSTOMS_CODE,SECTION_ID,GROUP_ID from FORFEIT_FORM_INC_EXT where CMD_TYPE='I';

delete from FORFEIT_FORM_GPTMP;

\timing
