\echo ------------------H2000_SMS_SENDLOG----------------
select now();
\timing
insert into H2000_SMS_SENDLOG_GPTMP (CMD_TYPE,SEQUENCE_NO, FORM_ID, SYSTEM_ID, POS_ID, OP_TIME, PHONE_NO) select CMD_TYPE,SEQUENCE_NO, FORM_ID, SYSTEM_ID, POS_ID, OP_TIME, PHONE_NO from H2000_SMS_SENDLOG_INC_EXT;

delete from H2000_SMS_SENDLOG using H2000_SMS_SENDLOG_GPTMP where H2000_SMS_SENDLOG_GPTMP.SEQUENCE_NO=H2000_SMS_SENDLOG.SEQUENCE_NO AND H2000_SMS_SENDLOG_GPTMP.FORM_ID=H2000_SMS_SENDLOG.FORM_ID AND H2000_SMS_SENDLOG_GPTMP.SYSTEM_ID=H2000_SMS_SENDLOG.SYSTEM_ID AND H2000_SMS_SENDLOG_GPTMP.POS_ID=H2000_SMS_SENDLOG.POS_ID AND H2000_SMS_SENDLOG_GPTMP.OP_TIME=H2000_SMS_SENDLOG.OP_TIME AND H2000_SMS_SENDLOG_GPTMP.PHONE_NO=H2000_SMS_SENDLOG.PHONE_NO ;

insert into H2000_SMS_SENDLOG(SEQUENCE_NO,FORM_ID,CUSTOMS_CODE,SYSTEM_ID,POS_ID,OP_TIME,PHONE_NO,MSG_TEXT,NOTES,LOG_TIME) select SEQUENCE_NO,FORM_ID,CUSTOMS_CODE,SYSTEM_ID,POS_ID,OP_TIME,PHONE_NO,MSG_TEXT,NOTES,LOG_TIME from H2000_SMS_SENDLOG_INC_EXT where CMD_TYPE='I';

delete from H2000_SMS_SENDLOG_GPTMP;

\timing
