\echo ------------------HIS_TRN_DR_REL----------------
select now();
\timing
insert into HIS_TRN_DR_REL_GPTMP (CMD_TYPE,DR_CUSTOMS_NO, MODI_COUNT) select CMD_TYPE,DR_CUSTOMS_NO, MODI_COUNT from HIS_TRN_DR_REL_INC_EXT;

delete from HIS_TRN_DR_REL using HIS_TRN_DR_REL_GPTMP where HIS_TRN_DR_REL_GPTMP.DR_CUSTOMS_NO=HIS_TRN_DR_REL.DR_CUSTOMS_NO AND HIS_TRN_DR_REL_GPTMP.MODI_COUNT=HIS_TRN_DR_REL.MODI_COUNT ;

insert into HIS_TRN_DR_REL(DR_REG_TYPE,DR_CUSTOMS_NO,DR_IC_NO,DR_NAME,DR_IDCARD_NO,DR_GENDER,DR_NATIVE,DR_BIRTH_DATE,CO_REG_NO,CO_NAME,MAIN_PORT,DR_LIC_CUS,DR_IE_CERF_NO,DR_PERMIT_VE,VALID_FLAG,CK_FLAG,VALID_DATE,TRAIN_VALID_DATE,INPUT_DATE,INPUT_OP_ID,RESERV_FIELD,NOTE_FIELD,MODI_OP_ID,MODI_TIME,MODI_COUNT,DR_IC_NO2) select DR_REG_TYPE,DR_CUSTOMS_NO,DR_IC_NO,DR_NAME,DR_IDCARD_NO,DR_GENDER,DR_NATIVE,DR_BIRTH_DATE,CO_REG_NO,CO_NAME,MAIN_PORT,DR_LIC_CUS,DR_IE_CERF_NO,DR_PERMIT_VE,VALID_FLAG,CK_FLAG,VALID_DATE,TRAIN_VALID_DATE,INPUT_DATE,INPUT_OP_ID,RESERV_FIELD,NOTE_FIELD,MODI_OP_ID,MODI_TIME,MODI_COUNT,DR_IC_NO2 from HIS_TRN_DR_REL_INC_EXT where CMD_TYPE='I';

delete from HIS_TRN_DR_REL_GPTMP;

\timing
