\echo ------------------IM_CDL_MNL_DEDUCT----------------
select now();
\timing
insert into IM_CDL_MNL_DEDUCT_GPTMP (CMD_TYPE,MANUAL_NO, ENTRY_ID, G_NO) select CMD_TYPE,MANUAL_NO, ENTRY_ID, G_NO from IM_CDL_MNL_DEDUCT_INC_EXT;

delete from IM_CDL_MNL_DEDUCT using IM_CDL_MNL_DEDUCT_GPTMP where IM_CDL_MNL_DEDUCT_GPTMP.MANUAL_NO=IM_CDL_MNL_DEDUCT.MANUAL_NO AND IM_CDL_MNL_DEDUCT_GPTMP.ENTRY_ID=IM_CDL_MNL_DEDUCT.ENTRY_ID AND IM_CDL_MNL_DEDUCT_GPTMP.G_NO=IM_CDL_MNL_DEDUCT.G_NO ;

insert into IM_CDL_MNL_DEDUCT(MANUAL_NO,CONTR_ITEM,ENTRY_ID,ENTRY_ITEM,I_E_PORT,I_E_DATE,G_NO,IN_QTY,I_ACCOUNT,I_CURR,DUTY_MODE,VERIFY_MODE,VERIFY_DATE,VERIFY_ER,DUTY_PRINT) select MANUAL_NO,CONTR_ITEM,ENTRY_ID,ENTRY_ITEM,I_E_PORT,I_E_DATE,G_NO,IN_QTY,I_ACCOUNT,I_CURR,DUTY_MODE,VERIFY_MODE,VERIFY_DATE,VERIFY_ER,DUTY_PRINT from IM_CDL_MNL_DEDUCT_INC_EXT where CMD_TYPE='I';

delete from IM_CDL_MNL_DEDUCT_GPTMP;

\timing
