\echo ------------------IM_COP_RATE----------------
select now();
\timing
insert into IM_COP_RATE_GPTMP (CMD_TYPE,TRADE_CO, CHKSTDATE, CHKENDDATE) select CMD_TYPE,TRADE_CO, CHKSTDATE, CHKENDDATE from IM_COP_RATE_INC_EXT;

delete from IM_COP_RATE using IM_COP_RATE_GPTMP where IM_COP_RATE_GPTMP.TRADE_CO=IM_COP_RATE.TRADE_CO AND IM_COP_RATE_GPTMP.CHKSTDATE=IM_COP_RATE.CHKSTDATE AND IM_COP_RATE_GPTMP.CHKENDDATE=IM_COP_RATE.CHKENDDATE ;

insert into IM_COP_RATE(TRADE_CO,CHKSTDATE,CHKENDDATE,CORCORPNAME,CHKRATE,RECV_DATE) select TRADE_CO,CHKSTDATE,CHKENDDATE,CORCORPNAME,CHKRATE,RECV_DATE from IM_COP_RATE_INC_EXT where CMD_TYPE='I';

delete from IM_COP_RATE_GPTMP;

\timing
