\echo ------------------IM_EXAM_MANA_LIST----------------
select now();
\timing
insert into IM_EXAM_MANA_LIST_GPTMP (CMD_TYPE,LICENSE_NO, L_G_NO) select CMD_TYPE,LICENSE_NO, L_G_NO from IM_EXAM_MANA_LIST_INC_EXT;

delete from IM_EXAM_MANA_LIST using IM_EXAM_MANA_LIST_GPTMP where IM_EXAM_MANA_LIST_GPTMP.LICENSE_NO=IM_EXAM_MANA_LIST.LICENSE_NO AND IM_EXAM_MANA_LIST_GPTMP.L_G_NO=IM_EXAM_MANA_LIST.L_G_NO ;

insert into IM_EXAM_MANA_LIST(LICENSE_NO,L_G_NO,L_FACT_AQTY,L_FACT_AUSED,L_REUSE1,L_REUSE2) select LICENSE_NO,L_G_NO,L_FACT_AQTY,L_FACT_AUSED,L_REUSE1,L_REUSE2 from IM_EXAM_MANA_LIST_INC_EXT where CMD_TYPE='I';

delete from IM_EXAM_MANA_LIST_GPTMP;

\timing
