\echo ------------------IM_TRANS_LIST_REL----------------
select now();
\timing
insert into IM_TRANS_LIST_REL_GPTMP (CMD_TYPE,PRE_NO, RECORD_NUMBER) select CMD_TYPE,PRE_NO, RECORD_NUMBER from IM_TRANS_LIST_REL_INC_EXT;

delete from IM_TRANS_LIST_REL using IM_TRANS_LIST_REL_GPTMP where IM_TRANS_LIST_REL_GPTMP.PRE_NO=IM_TRANS_LIST_REL.PRE_NO AND IM_TRANS_LIST_REL_GPTMP.RECORD_NUMBER=IM_TRANS_LIST_REL.RECORD_NUMBER ;

insert into IM_TRANS_LIST_REL(PRE_NO,RECORD_NUMBER,TRAF_MODE,SHIP_ID,SHIP_NAME_EN,VOYAGE_NO,BILL_NO,I_E_DATE,ENTRY_NO,BIND_FLAG,REC_FLAG,PACK_NO,GROSS_WT,GOODS_COUNT,CONTA_C,OWNER_NAME,EX_CHECK_FLAG,EX_CHECK_TIME,REAL_PACK_NO,REAL_GROSS_WT,NOTE,SEND_PORT,RECV_PORT,EX_CHECK_OP_ID) select PRE_NO,RECORD_NUMBER,TRAF_MODE,SHIP_ID,SHIP_NAME_EN,VOYAGE_NO,BILL_NO,I_E_DATE,ENTRY_NO,BIND_FLAG,REC_FLAG,PACK_NO,GROSS_WT,GOODS_COUNT,CONTA_C,OWNER_NAME,EX_CHECK_FLAG,EX_CHECK_TIME,REAL_PACK_NO,REAL_GROSS_WT,NOTE,SEND_PORT,RECV_PORT,EX_CHECK_OP_ID from IM_TRANS_LIST_REL_INC_EXT where CMD_TYPE='I';

delete from IM_TRANS_LIST_REL_GPTMP;

\timing
