\echo ------------------JOB_PARAMETER----------------
select now();
\timing
insert into JOB_PARAMETER_GPTMP (CMD_TYPE,JOB_NAME, PARAMETER_NAME, PARAMETER_VALUE) select CMD_TYPE,JOB_NAME, PARAMETER_NAME, PARAMETER_VALUE from JOB_PARAMETER_INC_EXT;

delete from JOB_PARAMETER using JOB_PARAMETER_GPTMP where JOB_PARAMETER_GPTMP.JOB_NAME=JOB_PARAMETER.JOB_NAME AND JOB_PARAMETER_GPTMP.PARAMETER_NAME=JOB_PARAMETER.PARAMETER_NAME AND JOB_PARAMETER_GPTMP.PARAMETER_VALUE=JOB_PARAMETER.PARAMETER_VALUE ;

insert into JOB_PARAMETER(JOB_NAME,PARAMETER_NAME,PARAMETER_VALUE,UPDATE_TIME,NOTES) select JOB_NAME,PARAMETER_NAME,PARAMETER_VALUE,UPDATE_TIME,NOTES from JOB_PARAMETER_INC_EXT where CMD_TYPE='I';

delete from JOB_PARAMETER_GPTMP;

\timing
