\echo ------------------LSP_CHK----------------
select now();
\timing
insert into LSP_CHK_GPTMP (CMD_TYPE,LSP_ID, LSP_TYPE, I_E_FLAG, ENTRY_ID, G_NO) select CMD_TYPE,LSP_ID, LSP_TYPE, I_E_FLAG, ENTRY_ID, G_NO from LSP_CHK_INC_EXT;

delete from LSP_CHK using LSP_CHK_GPTMP where LSP_CHK_GPTMP.LSP_ID=LSP_CHK.LSP_ID AND LSP_CHK_GPTMP.LSP_TYPE=LSP_CHK.LSP_TYPE AND LSP_CHK_GPTMP.I_E_FLAG=LSP_CHK.I_E_FLAG AND LSP_CHK_GPTMP.ENTRY_ID=LSP_CHK.ENTRY_ID AND LSP_CHK_GPTMP.G_NO=LSP_CHK.G_NO ;

insert into LSP_CHK(LSP_ID,LSP_TYPE,I_E_FLAG,ENTRY_ID,G_NO,CREATE_DATE,RMB_PRICE,USD_PRICE,G_QTY,G_UNIT,QTY_1,UNIT_1,CHK_MARK) select LSP_ID,LSP_TYPE,I_E_FLAG,ENTRY_ID,G_NO,CREATE_DATE,RMB_PRICE,USD_PRICE,G_QTY,G_UNIT,QTY_1,UNIT_1,CHK_MARK from LSP_CHK_INC_EXT where CMD_TYPE='I';

delete from LSP_CHK_GPTMP;

\timing
