\echo ------------------MANIFEST_EXCH_LOG_BAK----------------
select now();
\timing
insert into MANIFEST_EXCH_LOG_BAK_GPTMP (CMD_TYPE,CUSTOMS_CODE, SHIP_ID, VOYAGE_NO, BILL_NO, I_E_DATE, CREATE_DATE) select CMD_TYPE,CUSTOMS_CODE, SHIP_ID, VOYAGE_NO, BILL_NO, I_E_DATE, CREATE_DATE from MANIFEST_EXCH_LOG_BAK_INC_EXT;

delete from MANIFEST_EXCH_LOG_BAK using MANIFEST_EXCH_LOG_BAK_GPTMP where MANIFEST_EXCH_LOG_BAK_GPTMP.CUSTOMS_CODE=MANIFEST_EXCH_LOG_BAK.CUSTOMS_CODE AND MANIFEST_EXCH_LOG_BAK_GPTMP.SHIP_ID=MANIFEST_EXCH_LOG_BAK.SHIP_ID AND MANIFEST_EXCH_LOG_BAK_GPTMP.VOYAGE_NO=MANIFEST_EXCH_LOG_BAK.VOYAGE_NO AND MANIFEST_EXCH_LOG_BAK_GPTMP.BILL_NO=MANIFEST_EXCH_LOG_BAK.BILL_NO AND MANIFEST_EXCH_LOG_BAK_GPTMP.I_E_DATE=MANIFEST_EXCH_LOG_BAK.I_E_DATE AND MANIFEST_EXCH_LOG_BAK_GPTMP.CREATE_DATE=MANIFEST_EXCH_LOG_BAK.CREATE_DATE ;

insert into MANIFEST_EXCH_LOG_BAK(CUSTOMS_CODE,VOYAGE_NO,SHIP_ID,BILL_NO,I_E_DATE,CREATE_DATE,I_E_FLAG,TRAF_MODE,SHIP_NAME_EN,NOTICE_DATE,FILE_NAME,MANTFEST_NO,OP_MODE,MODIFY_TIMES,INSE_NOTICE_DATE,INSE_FILE_NAME,INSE_CHANNEL,NOTES) select CUSTOMS_CODE,VOYAGE_NO,SHIP_ID,BILL_NO,I_E_DATE,CREATE_DATE,I_E_FLAG,TRAF_MODE,SHIP_NAME_EN,NOTICE_DATE,FILE_NAME,MANTFEST_NO,OP_MODE,MODIFY_TIMES,INSE_NOTICE_DATE,INSE_FILE_NAME,INSE_CHANNEL,NOTES from MANIFEST_EXCH_LOG_BAK_INC_EXT where CMD_TYPE='I';

delete from MANIFEST_EXCH_LOG_BAK_GPTMP;

\timing
