\echo ------------------MANIFEST_LIST----------------
select now();
\timing
insert into MANIFEST_LIST_GPTMP (CMD_TYPE,BILL_NO, VOYAGE_NO, CUSTOMS_CODE, SHIP_ID, I_E_DATE, TRAF_MODE, I_E_FLAG) select CMD_TYPE,BILL_NO, VOYAGE_NO, CUSTOMS_CODE, SHIP_ID, I_E_DATE, TRAF_MODE, I_E_FLAG from MANIFEST_LIST_INC_EXT;

delete from MANIFEST_LIST using MANIFEST_LIST_GPTMP where MANIFEST_LIST_GPTMP.BILL_NO=MANIFEST_LIST.BILL_NO AND MANIFEST_LIST_GPTMP.VOYAGE_NO=MANIFEST_LIST.VOYAGE_NO AND MANIFEST_LIST_GPTMP.CUSTOMS_CODE=MANIFEST_LIST.CUSTOMS_CODE AND MANIFEST_LIST_GPTMP.SHIP_ID=MANIFEST_LIST.SHIP_ID AND MANIFEST_LIST_GPTMP.I_E_DATE=MANIFEST_LIST.I_E_DATE AND MANIFEST_LIST_GPTMP.TRAF_MODE=MANIFEST_LIST.TRAF_MODE AND MANIFEST_LIST_GPTMP.I_E_FLAG=MANIFEST_LIST.I_E_FLAG ;

insert into MANIFEST_LIST(I_E_FLAG,CUSTOMS_CODE,TRAF_MODE,VOYAGE_NO,BILL_NO,SHIP_ID,I_E_DATE,BILL_FLAG,SHIP_NAME_EN,CONSIGNOR,CONSIGNEE,LOADING_PORT,DESTINATION_PORT,DISTRICT_CODE,DISCHARGE_PLACE,MAIN_G_NAME,PACK_NO,WRAP_TYPE,VOLUME,MARK_CONTR,CONTA_NUM,GROSS_WT,BILL_PACK_NO,BILL_GROSS_WT,TAL_FLAG,TAL_DATE,TAL_ER,SUR_DATE,SUR_ER,EXAM_FLAG,URG_DATE,URG_ER,SEL_DATE,SEL_ER,ITEMS_NO,TOTAL_VALUE,CURR_CODE,I_E_PORT,DISTRIBUTE_FLAG,DISTRIBUTE_DATE,TRANS_NO,ARRIVE_DATE,BILL_NO_ORI,RSK_ER,RSK_DATE,RSK_CODE,RSK_LEVEL,RELEASE_ER,RELEASE_DATE,DISCHARGE_PLACE_ORI,CN_SHIP_ID,CN_SHIP_ER,CN_SHIP_DATE,D_DATE,RSK_PHONE,RSK_RESULT,RSKAPPLY_ER,NOTES,CREATE_DATE) select I_E_FLAG,CUSTOMS_CODE,TRAF_MODE,VOYAGE_NO,BILL_NO,SHIP_ID,I_E_DATE,BILL_FLAG,SHIP_NAME_EN,CONSIGNOR,CONSIGNEE,LOADING_PORT,DESTINATION_PORT,DISTRICT_CODE,DISCHARGE_PLACE,MAIN_G_NAME,PACK_NO,WRAP_TYPE,VOLUME,MARK_CONTR,CONTA_NUM,GROSS_WT,BILL_PACK_NO,BILL_GROSS_WT,TAL_FLAG,TAL_DATE,TAL_ER,SUR_DATE,SUR_ER,EXAM_FLAG,URG_DATE,URG_ER,SEL_DATE,SEL_ER,ITEMS_NO,TOTAL_VALUE,CURR_CODE,I_E_PORT,DISTRIBUTE_FLAG,DISTRIBUTE_DATE,TRANS_NO,ARRIVE_DATE,BILL_NO_ORI,RSK_ER,RSK_DATE,RSK_CODE,RSK_LEVEL,RELEASE_ER,RELEASE_DATE,DISCHARGE_PLACE_ORI,CN_SHIP_ID,CN_SHIP_ER,CN_SHIP_DATE,D_DATE,RSK_PHONE,RSK_RESULT,RSKAPPLY_ER,NOTES,CREATE_DATE from MANIFEST_LIST_INC_EXT where CMD_TYPE='I';

delete from MANIFEST_LIST_GPTMP;

\timing
