\echo ------------------MANIFEST_CONTA----------------
select now();
\timing
insert into MANIFEST_CONTA_GPTMP (CMD_TYPE,VOYAGE_NO, TRAF_MODE, I_E_FLAG, BILL_NO, CONTA_ID, SHIP_ID) select CMD_TYPE,VOYAGE_NO, TRAF_MODE, I_E_FLAG, BILL_NO, CONTA_ID, SHIP_ID from MANIFEST_CONTA_INC_EXT;

delete from MANIFEST_CONTA using MANIFEST_CONTA_GPTMP where MANIFEST_CONTA_GPTMP.VOYAGE_NO=MANIFEST_CONTA.VOYAGE_NO AND MANIFEST_CONTA_GPTMP.TRAF_MODE=MANIFEST_CONTA.TRAF_MODE AND MANIFEST_CONTA_GPTMP.I_E_FLAG=MANIFEST_CONTA.I_E_FLAG AND MANIFEST_CONTA_GPTMP.BILL_NO=MANIFEST_CONTA.BILL_NO AND MANIFEST_CONTA_GPTMP.CONTA_ID=MANIFEST_CONTA.CONTA_ID AND MANIFEST_CONTA_GPTMP.SHIP_ID=MANIFEST_CONTA.SHIP_ID ;

insert into MANIFEST_CONTA(I_E_FLAG,TRAF_MODE,VOYAGE_NO,BILL_NO,CONTA_ID,SHIP_ID,CONTA_MODEL,SEAL_NO,CONTA_WT,CONTA_FLAG,PACK_NO,MAIN_G_NAME,NOTES,CUSTOMS_CODE) select I_E_FLAG,TRAF_MODE,VOYAGE_NO,BILL_NO,CONTA_ID,SHIP_ID,CONTA_MODEL,SEAL_NO,CONTA_WT,CONTA_FLAG,PACK_NO,MAIN_G_NAME,NOTES,CUSTOMS_CODE from MANIFEST_CONTA_INC_EXT where CMD_TYPE='I';

delete from MANIFEST_CONTA_GPTMP;

\timing
