\echo ------------------MNL_PRESS----------------
select now();
\timing
insert into MNL_PRESS_GPTMP (CMD_TYPE,PARA_TYPE, PARA_NAME) select CMD_TYPE,PARA_TYPE, PARA_NAME from MNL_PRESS_INC_EXT;

delete from MNL_PRESS using MNL_PRESS_GPTMP where MNL_PRESS_GPTMP.PARA_TYPE=MNL_PRESS.PARA_TYPE AND MNL_PRESS_GPTMP.PARA_NAME=MNL_PRESS.PARA_NAME ;

insert into MNL_PRESS(PARA_TYPE,PARA_ID,PARA_NAME,PARA_EXP,PARA_FLAG,PARA_VALUE,PARA_MARK) select PARA_TYPE,PARA_ID,PARA_NAME,PARA_EXP,PARA_FLAG,PARA_VALUE,PARA_MARK from MNL_PRESS_INC_EXT where CMD_TYPE='I';

delete from MNL_PRESS_GPTMP;

\timing
