\echo ------------------MNLBAK_SERVICE_LIST----------------
select now();
\timing
insert into MNLBAK_SERVICE_LIST_GPTMP (CMD_TYPE,MANUAL_NO, F_NO) select CMD_TYPE,MANUAL_NO, F_NO from MNLBAK_SERVICE_LIST_INC_EXT;

delete from MNLBAK_SERVICE_LIST using MNLBAK_SERVICE_LIST_GPTMP where MNLBAK_SERVICE_LIST_GPTMP.MANUAL_NO=MNLBAK_SERVICE_LIST.MANUAL_NO AND MNLBAK_SERVICE_LIST_GPTMP.F_NO=MNLBAK_SERVICE_LIST.F_NO ;

insert into MNLBAK_SERVICE_LIST(MANUAL_NO,F_NO,FEE_TYPE,FEE_RATE,G_NO,G_NAME,FEE_AMT,FEE_CURR,FEE_RMB,SERVICE_FEE) select MANUAL_NO,F_NO,FEE_TYPE,FEE_RATE,G_NO,G_NAME,FEE_AMT,FEE_CURR,FEE_RMB,SERVICE_FEE from MNLBAK_SERVICE_LIST_INC_EXT where CMD_TYPE='I';

delete from MNLBAK_SERVICE_LIST_GPTMP;

\timing
