\echo ------------------MNLBAK_FEE_INVOICE----------------
select now();
\timing
insert into MNLBAK_FEE_INVOICE_GPTMP (CMD_TYPE,MANUAL_NO, F_NO) select CMD_TYPE,MANUAL_NO, F_NO from MNLBAK_FEE_INVOICE_INC_EXT;

delete from MNLBAK_FEE_INVOICE using MNLBAK_FEE_INVOICE_GPTMP where MNLBAK_FEE_INVOICE_GPTMP.MANUAL_NO=MNLBAK_FEE_INVOICE.MANUAL_NO AND MNLBAK_FEE_INVOICE_GPTMP.F_NO=MNLBAK_FEE_INVOICE.F_NO ;

insert into MNLBAK_FEE_INVOICE(MANUAL_NO,F_NO,FEE_ID,CREATE_DATE,CHK_ER,TYPE_ER,TYPE_DATE,FINANCIAL_FLAG,FINANCIAL_DATE,BOOK_NO,FEE_AMT,NOTE_S) select MANUAL_NO,F_NO,FEE_ID,CREATE_DATE,CHK_ER,TYPE_ER,TYPE_DATE,FINANCIAL_FLAG,FINANCIAL_DATE,BOOK_NO,FEE_AMT,NOTE_S from MNLBAK_FEE_INVOICE_INC_EXT where CMD_TYPE='I';

delete from MNLBAK_FEE_INVOICE_GPTMP;

\timing
