\echo ------------------MNLBAK_CONSUME----------------
select now();
\timing
insert into MNLBAK_CONSUME_GPTMP (CMD_TYPE,MANUAL_NO, CONTR_ITEM, EX_NO) select CMD_TYPE,MANUAL_NO, CONTR_ITEM, EX_NO from MNLBAK_CONSUME_INC_EXT;

delete from MNLBAK_CONSUME using MNLBAK_CONSUME_GPTMP where MNLBAK_CONSUME_GPTMP.MANUAL_NO=MNLBAK_CONSUME.MANUAL_NO AND MNLBAK_CONSUME_GPTMP.CONTR_ITEM=MNLBAK_CONSUME.CONTR_ITEM AND MNLBAK_CONSUME_GPTMP.EX_NO=MNLBAK_CONSUME.EX_NO ;

insert into MNLBAK_CONSUME(MANUAL_NO,CONTR_ITEM,EX_NO,APPR_CONSUME,APPR_DAMAGE,DECL_CONSUME,DECL_DAMAGE) select MANUAL_NO,CONTR_ITEM,EX_NO,APPR_CONSUME,APPR_DAMAGE,DECL_CONSUME,DECL_DAMAGE from MNLBAK_CONSUME_INC_EXT where CMD_TYPE='I';

delete from MNLBAK_CONSUME_GPTMP;

\timing
