\echo ------------------MNLBAK_EX_FASCICLE_LIST----------------
select now();
\timing
insert into MNLBAK_EX_FASCICLE_LIST_GPTMP (CMD_TYPE,FASCICLE_NO, CONTR_ITEM) select CMD_TYPE,FASCICLE_NO, CONTR_ITEM from MNLBAK_EX_FASCICLE_LIST_INC_EXT;

delete from MNLBAK_EX_FASCICLE_LIST using MNLBAK_EX_FASCICLE_LIST_GPTMP where MNLBAK_EX_FASCICLE_LIST_GPTMP.FASCICLE_NO=MNLBAK_EX_FASCICLE_LIST.FASCICLE_NO AND MNLBAK_EX_FASCICLE_LIST_GPTMP.CONTR_ITEM=MNLBAK_EX_FASCICLE_LIST.CONTR_ITEM ;

insert into MNLBAK_EX_FASCICLE_LIST(MANUAL_NO,FASCICLE_NO,CONTR_ITEM,APPR_QTY,FACT_QTY) select MANUAL_NO,FASCICLE_NO,CONTR_ITEM,APPR_QTY,FACT_QTY from MNLBAK_EX_FASCICLE_LIST_INC_EXT where CMD_TYPE='I';

delete from MNLBAK_EX_FASCICLE_LIST_GPTMP;

\timing
