\echo ------------------NORSK_CONDITION_BAK----------------
select now();
\timing
insert into NORSK_CONDITION_BAK_GPTMP (CMD_TYPE,CCTS_CODE, OP_BAK_TIME) select CMD_TYPE,CCTS_CODE, OP_BAK_TIME from NORSK_CONDITION_BAK_INC_EXT;

delete from NORSK_CONDITION_BAK using NORSK_CONDITION_BAK_GPTMP where NORSK_CONDITION_BAK_GPTMP.CCTS_CODE=NORSK_CONDITION_BAK.CCTS_CODE AND NORSK_CONDITION_BAK_GPTMP.OP_BAK_TIME=NORSK_CONDITION_BAK.OP_BAK_TIME ;

insert into NORSK_CONDITION_BAK(CCTS_CODE,RSK_COND,RSK_COND_MID,RSK_COND_TXT,NOTE,BEGIN_DATE,END_DATE,CUSTOMS_CODE,INPUT_ID,AUTHORIZE_ID,OP_TIME,OP_BAK_TYPE,OP_BAK_CUSTOMS,OP_BAK_MAN,OP_BAK_TIME) select CCTS_CODE,RSK_COND,RSK_COND_MID,RSK_COND_TXT,NOTE,BEGIN_DATE,END_DATE,CUSTOMS_CODE,INPUT_ID,AUTHORIZE_ID,OP_TIME,OP_BAK_TYPE,OP_BAK_CUSTOMS,OP_BAK_MAN,OP_BAK_TIME from NORSK_CONDITION_BAK_INC_EXT where CMD_TYPE='I';

delete from NORSK_CONDITION_BAK_GPTMP;

\timing
