\echo ------------------NORSK_TRADE_MODE----------------
select now();
\timing
insert into NORSK_TRADE_MODE_GPTMP (CMD_TYPE,CCTS_CODE) select CMD_TYPE,CCTS_CODE from NORSK_TRADE_MODE_INC_EXT;

delete from NORSK_TRADE_MODE using NORSK_TRADE_MODE_GPTMP where NORSK_TRADE_MODE_GPTMP.CCTS_CODE=NORSK_TRADE_MODE.CCTS_CODE ;

insert into NORSK_TRADE_MODE(CCTS_CODE,TRADE_MODE,TRADE_NAME,BEGIN_DATE,END_DATE,CUSTOMS_CODE,INPUT_ID,AUTHORIZE_ID,OP_TIME,I_E_FLAG) select CCTS_CODE,TRADE_MODE,TRADE_NAME,BEGIN_DATE,END_DATE,CUSTOMS_CODE,INPUT_ID,AUTHORIZE_ID,OP_TIME,I_E_FLAG from NORSK_TRADE_MODE_INC_EXT where CMD_TYPE='I';

delete from NORSK_TRADE_MODE_GPTMP;

\timing
