\echo ------------------NORSK_COMPANY----------------
select now();
\timing
insert into NORSK_COMPANY_GPTMP (CMD_TYPE,CCTS_CODE) select CMD_TYPE,CCTS_CODE from NORSK_COMPANY_INC_EXT;

delete from NORSK_COMPANY using NORSK_COMPANY_GPTMP where NORSK_COMPANY_GPTMP.CCTS_CODE=NORSK_COMPANY.CCTS_CODE ;

insert into NORSK_COMPANY(CCTS_CODE,TRADE_CO,TRADE_NAME,BEGIN_DATE,END_DATE,CUSTOMS_CODE,INPUT_ID,AUTHORIZE_ID,OP_TIME,I_E_FLAG) select CCTS_CODE,TRADE_CO,TRADE_NAME,BEGIN_DATE,END_DATE,CUSTOMS_CODE,INPUT_ID,AUTHORIZE_ID,OP_TIME,I_E_FLAG from NORSK_COMPANY_INC_EXT where CMD_TYPE='I';

delete from NORSK_COMPANY_GPTMP;

\timing
