\echo ------------------NORSK_COMPANY_BAK----------------
select now();
\timing
insert into NORSK_COMPANY_BAK_GPTMP (CMD_TYPE,CCTS_CODE, OP_BAK_TIME) select CMD_TYPE,CCTS_CODE, OP_BAK_TIME from NORSK_COMPANY_BAK_INC_EXT;

delete from NORSK_COMPANY_BAK using NORSK_COMPANY_BAK_GPTMP where NORSK_COMPANY_BAK_GPTMP.CCTS_CODE=NORSK_COMPANY_BAK.CCTS_CODE AND NORSK_COMPANY_BAK_GPTMP.OP_BAK_TIME=NORSK_COMPANY_BAK.OP_BAK_TIME ;

insert into NORSK_COMPANY_BAK(CCTS_CODE,TRADE_CO,TRADE_NAME,BEGIN_DATE,END_DATE,CUSTOMS_CODE,INPUT_ID,AUTHORIZE_ID,OP_TIME,I_E_FLAG,OP_BAK_TYPE,OP_BAK_CUSTOMS,OP_BAK_MAN,OP_BAK_TIME) select CCTS_CODE,TRADE_CO,TRADE_NAME,BEGIN_DATE,END_DATE,CUSTOMS_CODE,INPUT_ID,AUTHORIZE_ID,OP_TIME,I_E_FLAG,OP_BAK_TYPE,OP_BAK_CUSTOMS,OP_BAK_MAN,OP_BAK_TIME from NORSK_COMPANY_BAK_INC_EXT where CMD_TYPE='I';

delete from NORSK_COMPANY_BAK_GPTMP;

\timing
