\echo ------------------OCC_EXAM----------------
select now();
\timing
insert into OCC_EXAM_GPTMP (CMD_TYPE,CERTIFICATE_NO, AGREEMENT_ID, ISSUE_PLACE, G_NO, ENTRY_G_NO) select CMD_TYPE,CERTIFICATE_NO, AGREEMENT_ID, ISSUE_PLACE, G_NO, ENTRY_G_NO from OCC_EXAM_INC_EXT;

delete from OCC_EXAM using OCC_EXAM_GPTMP where OCC_EXAM_GPTMP.CERTIFICATE_NO=OCC_EXAM.CERTIFICATE_NO AND OCC_EXAM_GPTMP.AGREEMENT_ID=OCC_EXAM.AGREEMENT_ID AND OCC_EXAM_GPTMP.ISSUE_PLACE=OCC_EXAM.ISSUE_PLACE AND OCC_EXAM_GPTMP.G_NO=OCC_EXAM.G_NO AND OCC_EXAM_GPTMP.ENTRY_G_NO=OCC_EXAM.ENTRY_G_NO ;

insert into OCC_EXAM(CERTIFICATE_NO,AGREEMENT_ID,ISSUE_PLACE,ENTRY_ID,BASE_ID,G_NO,ENTRY_G_NO,FACT_AQTY,FACT_TOTAL,FACT_CURR,CHK_DATE,CHK_ER,VERIFY_DATE,VERIFY_ER,RETURN_DATE,REUSE1,REUSE2,HASH_SIGN) select CERTIFICATE_NO,AGREEMENT_ID,ISSUE_PLACE,ENTRY_ID,BASE_ID,G_NO,ENTRY_G_NO,FACT_AQTY,FACT_TOTAL,FACT_CURR,CHK_DATE,CHK_ER,VERIFY_DATE,VERIFY_ER,RETURN_DATE,REUSE1,REUSE2,HASH_SIGN from OCC_EXAM_INC_EXT where CMD_TYPE='I';

delete from OCC_EXAM_GPTMP;

\timing
