\echo ------------------PAYOUT_REMIT_HEAD----------------
select now();
\timing
insert into PAYOUT_REMIT_HEAD_GPTMP (CMD_TYPE,RPTNO) select CMD_TYPE,RPTNO from PAYOUT_REMIT_HEAD_INC_EXT;

delete from PAYOUT_REMIT_HEAD using PAYOUT_REMIT_HEAD_GPTMP where PAYOUT_REMIT_HEAD_GPTMP.RPTNO=PAYOUT_REMIT_HEAD.RPTNO ;

insert into PAYOUT_REMIT_HEAD(RPTNO,RPTUSER,TRADE_CO,RCVNAME,ACTUCCY,ACTUAMT,CSTSETCODE,COUNTRYCODE,CSTCNTRCTNO,INVOICENO,LCBGNO,CUS_TRADE_CO,RECV_DATE) select RPTNO,RPTUSER,TRADE_CO,RCVNAME,ACTUCCY,ACTUAMT,CSTSETCODE,COUNTRYCODE,CSTCNTRCTNO,INVOICENO,LCBGNO,CUS_TRADE_CO,RECV_DATE from PAYOUT_REMIT_HEAD_INC_EXT where CMD_TYPE='I';

delete from PAYOUT_REMIT_HEAD_GPTMP;

\timing
