\echo ------------------PAYOUT_REMIT_LIST----------------
select now();
\timing
insert into PAYOUT_REMIT_LIST_GPTMP (CMD_TYPE,RPTNO, ENTRY_ID) select CMD_TYPE,RPTNO, ENTRY_ID from PAYOUT_REMIT_LIST_INC_EXT;

delete from PAYOUT_REMIT_LIST using PAYOUT_REMIT_LIST_GPTMP where PAYOUT_REMIT_LIST_GPTMP.RPTNO=PAYOUT_REMIT_LIST.RPTNO AND PAYOUT_REMIT_LIST_GPTMP.ENTRY_ID=PAYOUT_REMIT_LIST.ENTRY_ID ;

insert into PAYOUT_REMIT_LIST(RPTNO,ENTRY_ID,CUSTOMCCY,CUSTOMAMT,WRITEOFFAMT,RECV_DATE) select RPTNO,ENTRY_ID,CUSTOMCCY,CUSTOMAMT,WRITEOFFAMT,RECV_DATE from PAYOUT_REMIT_LIST_INC_EXT where CMD_TYPE='I';

delete from PAYOUT_REMIT_LIST_GPTMP;

\timing
