\echo ------------------PES_WORKFLOW----------------
select now();
\timing
insert into PES_WORKFLOW_GPTMP (CMD_TYPE,NOTE_NO, NOTE_TYPE, PROCESS_DATE, STEP_ID) select CMD_TYPE,NOTE_NO, NOTE_TYPE, PROCESS_DATE, STEP_ID from PES_WORKFLOW_INC_EXT;

delete from PES_WORKFLOW using PES_WORKFLOW_GPTMP where PES_WORKFLOW_GPTMP.NOTE_NO=PES_WORKFLOW.NOTE_NO AND PES_WORKFLOW_GPTMP.NOTE_TYPE=PES_WORKFLOW.NOTE_TYPE AND PES_WORKFLOW_GPTMP.PROCESS_DATE=PES_WORKFLOW.PROCESS_DATE AND PES_WORKFLOW_GPTMP.STEP_ID=PES_WORKFLOW.STEP_ID ;

insert into PES_WORKFLOW(NOTE_NO,NOTE_TYPE,PROCESS_DATE,STEP_ID,PROCESS_STATUS,STAT,ENTRY_ID,NOTE,PROCESS_ER) select NOTE_NO,NOTE_TYPE,PROCESS_DATE,STEP_ID,PROCESS_STATUS,STAT,ENTRY_ID,NOTE,PROCESS_ER from PES_WORKFLOW_INC_EXT where CMD_TYPE='I';

delete from PES_WORKFLOW_GPTMP;

\timing
