\echo ------------------PRE_CDL_COMMODITY----------------
select now();
\timing
insert into PRE_CDL_COMMODITY_GPTMP (CMD_TYPE,PRE_RECORDS_NO, RECORDS_DATE, G_NO) select CMD_TYPE,PRE_RECORDS_NO, RECORDS_DATE, G_NO from PRE_CDL_COMMODITY_INC_EXT;

delete from PRE_CDL_COMMODITY using PRE_CDL_COMMODITY_GPTMP where PRE_CDL_COMMODITY_GPTMP.PRE_RECORDS_NO=PRE_CDL_COMMODITY.PRE_RECORDS_NO AND PRE_CDL_COMMODITY_GPTMP.RECORDS_DATE=PRE_CDL_COMMODITY.RECORDS_DATE AND PRE_CDL_COMMODITY_GPTMP.G_NO=PRE_CDL_COMMODITY.G_NO ;

insert into PRE_CDL_COMMODITY(RECORDS_NO,PRE_RECORDS_NO,RECORDS_DATE,PROC_FLAG,TRADE_CO,G_NO,CODE_TS,G_NAME,G_MODEL,G_UNIT,DECL_PRICE,TRADE_CURR,I_E_FLAG,ORIGIN_COUNTRY,DISTRICT_CODE,LICENSE_NO,LICENSE_COUNT,LICENSE_DATE,MOD_TYPE,CUSTOMS_CODE) select RECORDS_NO,PRE_RECORDS_NO,RECORDS_DATE,PROC_FLAG,TRADE_CO,G_NO,CODE_TS,G_NAME,G_MODEL,G_UNIT,DECL_PRICE,TRADE_CURR,I_E_FLAG,ORIGIN_COUNTRY,DISTRICT_CODE,LICENSE_NO,LICENSE_COUNT,LICENSE_DATE,MOD_TYPE,CUSTOMS_CODE from PRE_CDL_COMMODITY_INC_EXT where CMD_TYPE='I';

delete from PRE_CDL_COMMODITY_GPTMP;

\timing
