\echo ------------------PRE_MANA_REL----------------
select now();
\timing
insert into PRE_MANA_REL_GPTMP (CMD_TYPE,PRE_TRADE_CO, MANAG_NO) select CMD_TYPE,PRE_TRADE_CO, MANAG_NO from PRE_MANA_REL_INC_EXT;

delete from PRE_MANA_REL using PRE_MANA_REL_GPTMP where PRE_MANA_REL_GPTMP.PRE_TRADE_CO=PRE_MANA_REL.PRE_TRADE_CO AND PRE_MANA_REL_GPTMP.MANAG_NO=PRE_MANA_REL.MANAG_NO ;

insert into PRE_MANA_REL(PRE_TRADE_CO,MANAG_NO,MANAG_NAME,MANAG_TITLE,MANAG_NAT,MANAG_ID,MANAG_BIR,MANAG_SEX,MANAG_ADDR,MANAG_TEL_BP,MANAG_NOTE,MANAG_DEGREE) select PRE_TRADE_CO,MANAG_NO,MANAG_NAME,MANAG_TITLE,MANAG_NAT,MANAG_ID,MANAG_BIR,MANAG_SEX,MANAG_ADDR,MANAG_TEL_BP,MANAG_NOTE,MANAG_DEGREE from PRE_MANA_REL_INC_EXT where CMD_TYPE='I';

delete from PRE_MANA_REL_GPTMP;

\timing
