\echo ------------------PRE_CONSUME----------------
select now();
\timing
insert into PRE_CONSUME_GPTMP (CMD_TYPE,MANUAL_NO, CONTR_ITEM, EX_NO) select CMD_TYPE,MANUAL_NO, CONTR_ITEM, EX_NO from PRE_CONSUME_INC_EXT;

delete from PRE_CONSUME using PRE_CONSUME_GPTMP where PRE_CONSUME_GPTMP.MANUAL_NO=PRE_CONSUME.MANUAL_NO AND PRE_CONSUME_GPTMP.CONTR_ITEM=PRE_CONSUME.CONTR_ITEM AND PRE_CONSUME_GPTMP.EX_NO=PRE_CONSUME.EX_NO ;

insert into PRE_CONSUME(MANUAL_NO,CONTR_ITEM,EX_NO,APPR_CONSUME,APPR_DAMAGE,DECL_CONSUME,DECL_DAMAGE) select MANUAL_NO,CONTR_ITEM,EX_NO,APPR_CONSUME,APPR_DAMAGE,DECL_CONSUME,DECL_DAMAGE from PRE_CONSUME_INC_EXT where CMD_TYPE='I';

delete from PRE_CONSUME_GPTMP;

\timing
