\echo ------------------PRE_PROJECT_LIST----------------
select now();
\timing
insert into PRE_PROJECT_LIST_GPTMP (CMD_TYPE,PROJECT_ID, MODIFY_TIMES, G_NO) select CMD_TYPE,PROJECT_ID, MODIFY_TIMES, G_NO from PRE_PROJECT_LIST_INC_EXT;

delete from PRE_PROJECT_LIST using PRE_PROJECT_LIST_GPTMP where PRE_PROJECT_LIST_GPTMP.PROJECT_ID=PRE_PROJECT_LIST.PROJECT_ID AND PRE_PROJECT_LIST_GPTMP.MODIFY_TIMES=PRE_PROJECT_LIST.MODIFY_TIMES AND PRE_PROJECT_LIST_GPTMP.G_NO=PRE_PROJECT_LIST.G_NO ;

insert into PRE_PROJECT_LIST(PROJECT_ID,MODIFY_TIMES,G_NO,CODE_TS,CLASS_MARK,G_NAME,G_MODEL,ORIGIN_COUNTRY,G_UNIT,G_QTY,UNIT_1,QTY_1,UNIT_2,QTY_2,DECL_TOTAL,TRADE_CURR,USED_QTY,USED_AMT,FACT_QTY,FACT_AMT,DUTY_MODE,D_RATE,T_RATE,O_RATE,DUTY_RATE,TAX_RATE,OTHER_RATE,CHECK_MARK,RESERVE1,NOTE) select PROJECT_ID,MODIFY_TIMES,G_NO,CODE_TS,CLASS_MARK,G_NAME,G_MODEL,ORIGIN_COUNTRY,G_UNIT,G_QTY,UNIT_1,QTY_1,UNIT_2,QTY_2,DECL_TOTAL,TRADE_CURR,USED_QTY,USED_AMT,FACT_QTY,FACT_AMT,DUTY_MODE,D_RATE,T_RATE,O_RATE,DUTY_RATE,TAX_RATE,OTHER_RATE,CHECK_MARK,RESERVE1,NOTE from PRE_PROJECT_LIST_INC_EXT where CMD_TYPE='I';

delete from PRE_PROJECT_LIST_GPTMP;

\timing
