\echo ------------------PROJECT_MAX_NO----------------
select now();
\timing
insert into PROJECT_MAX_NO_GPTMP (CMD_TYPE,MASTER_CUSTOMS, YEAR_2, CUT_MODE) select CMD_TYPE,MASTER_CUSTOMS, YEAR_2, CUT_MODE from PROJECT_MAX_NO_INC_EXT;

delete from PROJECT_MAX_NO using PROJECT_MAX_NO_GPTMP where PROJECT_MAX_NO_GPTMP.MASTER_CUSTOMS=PROJECT_MAX_NO.MASTER_CUSTOMS AND PROJECT_MAX_NO_GPTMP.YEAR_2=PROJECT_MAX_NO.YEAR_2 AND PROJECT_MAX_NO_GPTMP.CUT_MODE=PROJECT_MAX_NO.CUT_MODE ;

insert into PROJECT_MAX_NO(MASTER_CUSTOMS,YEAR_2,CUT_MODE,MAX_NO) select MASTER_CUSTOMS,YEAR_2,CUT_MODE,MAX_NO from PROJECT_MAX_NO_INC_EXT where CMD_TYPE='I';

delete from PROJECT_MAX_NO_GPTMP;

\timing
