\echo ------------------RAM_STATUS_MODI_LOG----------------
select now();
\timing
insert into RAM_STATUS_MODI_LOG_GPTMP (CMD_TYPE,CUT_ID, G_NO, MODIFY_DATE, FIELD_NAME) select CMD_TYPE,CUT_ID, G_NO, MODIFY_DATE, FIELD_NAME from RAM_STATUS_MODI_LOG_INC_EXT;

delete from RAM_STATUS_MODI_LOG using RAM_STATUS_MODI_LOG_GPTMP where RAM_STATUS_MODI_LOG_GPTMP.CUT_ID=RAM_STATUS_MODI_LOG.CUT_ID AND RAM_STATUS_MODI_LOG_GPTMP.G_NO=RAM_STATUS_MODI_LOG.G_NO AND RAM_STATUS_MODI_LOG_GPTMP.MODIFY_DATE=RAM_STATUS_MODI_LOG.MODIFY_DATE AND RAM_STATUS_MODI_LOG_GPTMP.FIELD_NAME=RAM_STATUS_MODI_LOG.FIELD_NAME ;

insert into RAM_STATUS_MODI_LOG(CUT_ID,G_NO,MODIFY_DATE,MODIFY_ER,FIELD_NAME,ORIGIN_VALUE,NEW_VALUE,REASON) select CUT_ID,G_NO,MODIFY_DATE,MODIFY_ER,FIELD_NAME,ORIGIN_VALUE,NEW_VALUE,REASON from RAM_STATUS_MODI_LOG_INC_EXT where CMD_TYPE='I';

delete from RAM_STATUS_MODI_LOG_GPTMP;

\timing
