\echo ------------------RAM_PRINT_LOG----------------
select now();
\timing
insert into RAM_PRINT_LOG_GPTMP (CMD_TYPE,RAM_ID, PRINT_DATE) select CMD_TYPE,RAM_ID, PRINT_DATE from RAM_PRINT_LOG_INC_EXT;

delete from RAM_PRINT_LOG using RAM_PRINT_LOG_GPTMP where RAM_PRINT_LOG_GPTMP.RAM_ID=RAM_PRINT_LOG.RAM_ID AND RAM_PRINT_LOG_GPTMP.PRINT_DATE=RAM_PRINT_LOG.PRINT_DATE ;

insert into RAM_PRINT_LOG(RAM_ID,PRINT_DATE,PRINT_ER) select RAM_ID,PRINT_DATE,PRINT_ER from RAM_PRINT_LOG_INC_EXT where CMD_TYPE='I';

delete from RAM_PRINT_LOG_GPTMP;

\timing
