\echo ------------------RAM_RG_COP_PROJECT----------------
select now();
\timing
insert into RAM_RG_COP_PROJECT_GPTMP (CMD_TYPE,RAM_ID, TYPE, COP_NO, PROJECT_NO) select CMD_TYPE,RAM_ID, TYPE, COP_NO, PROJECT_NO from RAM_RG_COP_PROJECT_INC_EXT;

delete from RAM_RG_COP_PROJECT using RAM_RG_COP_PROJECT_GPTMP where RAM_RG_COP_PROJECT_GPTMP.RAM_ID=RAM_RG_COP_PROJECT.RAM_ID AND RAM_RG_COP_PROJECT_GPTMP.TYPE=RAM_RG_COP_PROJECT.TYPE AND RAM_RG_COP_PROJECT_GPTMP.COP_NO=RAM_RG_COP_PROJECT.COP_NO AND RAM_RG_COP_PROJECT_GPTMP.PROJECT_NO=RAM_RG_COP_PROJECT.PROJECT_NO ;

insert into RAM_RG_COP_PROJECT(RAM_ID,TYPE,COP_NO,PROJECT_NO,PROJECT_ID,PROJECT_NAME,PROJECT_FUND,PROJECT_TYPE,INVEST_AMT,INVEST_CURR,QUOTA_AMT,QUOTA_FREE) select RAM_ID,TYPE,COP_NO,PROJECT_NO,PROJECT_ID,PROJECT_NAME,PROJECT_FUND,PROJECT_TYPE,INVEST_AMT,INVEST_CURR,QUOTA_AMT,QUOTA_FREE from RAM_RG_COP_PROJECT_INC_EXT where CMD_TYPE='I';

delete from RAM_RG_COP_PROJECT_GPTMP;

\timing
