\echo ------------------RAM_RG_COP_OWNER----------------
select now();
\timing
insert into RAM_RG_COP_OWNER_GPTMP (CMD_TYPE,RAM_ID, TYPE, COP_NO, OWNER_NO) select CMD_TYPE,RAM_ID, TYPE, COP_NO, OWNER_NO from RAM_RG_COP_OWNER_INC_EXT;

delete from RAM_RG_COP_OWNER using RAM_RG_COP_OWNER_GPTMP where RAM_RG_COP_OWNER_GPTMP.RAM_ID=RAM_RG_COP_OWNER.RAM_ID AND RAM_RG_COP_OWNER_GPTMP.TYPE=RAM_RG_COP_OWNER.TYPE AND RAM_RG_COP_OWNER_GPTMP.COP_NO=RAM_RG_COP_OWNER.COP_NO AND RAM_RG_COP_OWNER_GPTMP.OWNER_NO=RAM_RG_COP_OWNER.OWNER_NO ;

insert into RAM_RG_COP_OWNER(RAM_ID,TYPE,COP_NO,OWNER_NO,OWNER_NAME,COUNTRY,INVEST_RATE) select RAM_ID,TYPE,COP_NO,OWNER_NO,OWNER_NAME,COUNTRY,INVEST_RATE from RAM_RG_COP_OWNER_INC_EXT where CMD_TYPE='I';

delete from RAM_RG_COP_OWNER_GPTMP;

\timing
