\echo ------------------RCP_INCOME_HEAD_BAK----------------
select now();
\timing
insert into RCP_INCOME_HEAD_BAK_GPTMP (CMD_TYPE,LEVYNO) select CMD_TYPE,LEVYNO from RCP_INCOME_HEAD_BAK_INC_EXT;

delete from RCP_INCOME_HEAD_BAK using RCP_INCOME_HEAD_BAK_GPTMP where RCP_INCOME_HEAD_BAK_GPTMP.LEVYNO=RCP_INCOME_HEAD_BAK.LEVYNO ;

insert into RCP_INCOME_HEAD_BAK(LEVYNO,BANKORGCODE,PAYEENAME,PAYEEORGCODE,PAYEECGACCODE,PAYEEACCT,PAYERNAME,PAYERCOUNTRYCODE,SWIFTBIC,PAYEEDATE,PAYEECNY,PAYEEAMT,CUSTOMSAMT,PREPAYEEAMT,REFUNDMENTAMT,BALANCEMODE,ACCOUNTPERIOD,BANKTRANO,ADDWORD) select LEVYNO,BANKORGCODE,PAYEENAME,PAYEEORGCODE,PAYEECGACCODE,PAYEEACCT,PAYERNAME,PAYERCOUNTRYCODE,SWIFTBIC,PAYEEDATE,PAYEECNY,PAYEEAMT,CUSTOMSAMT,PREPAYEEAMT,REFUNDMENTAMT,BALANCEMODE,ACCOUNTPERIOD,BANKTRANO,ADDWORD from RCP_INCOME_HEAD_BAK_INC_EXT where CMD_TYPE='I';

delete from RCP_INCOME_HEAD_BAK_GPTMP;

\timing
