\echo ------------------RCP_RECORD_LIST----------------
select now();
\timing
insert into RCP_RECORD_LIST_GPTMP (CMD_TYPE,LEVYNO, LISTNO) select CMD_TYPE,LEVYNO, LISTNO from RCP_RECORD_LIST_INC_EXT;

delete from RCP_RECORD_LIST using RCP_RECORD_LIST_GPTMP where RCP_RECORD_LIST_GPTMP.LEVYNO=RCP_RECORD_LIST.LEVYNO AND RCP_RECORD_LIST_GPTMP.LISTNO=RCP_RECORD_LIST.LISTNO ;

insert into RCP_RECORD_LIST(LEVYNO,LISTNO,COUNTRYAREA,BANKNAMEOUT,BANKACCTOUT,BANKAMTOUT,RECDATEOUT,REMARK) select LEVYNO,LISTNO,COUNTRYAREA,BANKNAMEOUT,BANKACCTOUT,BANKAMTOUT,RECDATEOUT,REMARK from RCP_RECORD_LIST_INC_EXT where CMD_TYPE='I';

delete from RCP_RECORD_LIST_GPTMP;

\timing
