\echo ------------------RCP_RECORD_HEAD_BAK----------------
select now();
\timing
insert into RCP_RECORD_HEAD_BAK_GPTMP (CMD_TYPE,LEVYNO) select CMD_TYPE,LEVYNO from RCP_RECORD_HEAD_BAK_INC_EXT;

delete from RCP_RECORD_HEAD_BAK using RCP_RECORD_HEAD_BAK_GPTMP where RCP_RECORD_HEAD_BAK_GPTMP.LEVYNO=RCP_RECORD_HEAD_BAK.LEVYNO ;

insert into RCP_RECORD_HEAD_BAK(LEVYNO,ORGCODE,CGACCODE,ORGNAME,ENTRYID,TRADEDATE,TOTALAMT,BALANCEMODE,PACTNO,PRERECDATE,PRERECAMT) select LEVYNO,ORGCODE,CGACCODE,ORGNAME,ENTRYID,TRADEDATE,TOTALAMT,BALANCEMODE,PACTNO,PRERECDATE,PRERECAMT from RCP_RECORD_HEAD_BAK_INC_EXT where CMD_TYPE='I';

delete from RCP_RECORD_HEAD_BAK_GPTMP;

\timing
