\echo ------------------RCP_RECORD_LIST_BAK----------------
select now();
\timing
insert into RCP_RECORD_LIST_BAK_GPTMP (CMD_TYPE,LEVYNO, LISTNO) select CMD_TYPE,LEVYNO, LISTNO from RCP_RECORD_LIST_BAK_INC_EXT;

delete from RCP_RECORD_LIST_BAK using RCP_RECORD_LIST_BAK_GPTMP where RCP_RECORD_LIST_BAK_GPTMP.LEVYNO=RCP_RECORD_LIST_BAK.LEVYNO AND RCP_RECORD_LIST_BAK_GPTMP.LISTNO=RCP_RECORD_LIST_BAK.LISTNO ;

insert into RCP_RECORD_LIST_BAK(LEVYNO,LISTNO,COUNTRYAREA,BANKNAMEOUT,BANKACCTOUT,BANKAMTOUT,RECDATEOUT,REMARK) select LEVYNO,LISTNO,COUNTRYAREA,BANKNAMEOUT,BANKACCTOUT,BANKAMTOUT,RECDATEOUT,REMARK from RCP_RECORD_LIST_BAK_INC_EXT where CMD_TYPE='I';

delete from RCP_RECORD_LIST_BAK_GPTMP;

\timing
