\echo ------------------RCP_INCOME_HEAD----------------
select now();
\timing
insert into RCP_INCOME_HEAD_GPTMP (CMD_TYPE,LEVYNO) select CMD_TYPE,LEVYNO from RCP_INCOME_HEAD_INC_EXT;

delete from RCP_INCOME_HEAD using RCP_INCOME_HEAD_GPTMP where RCP_INCOME_HEAD_GPTMP.LEVYNO=RCP_INCOME_HEAD.LEVYNO ;

insert into RCP_INCOME_HEAD(LEVYNO,BANKORGCODE,PAYEENAME,PAYEEORGCODE,PAYEECGACCODE,PAYEEACCT,PAYERNAME,PAYERCOUNTRYCODE,SWIFTBIC,PAYEEDATE,PAYEECNY,PAYEEAMT,CUSTOMSAMT,PREPAYEEAMT,REFUNDMENTAMT,BALANCEMODE,ACCOUNTPERIOD,BANKTRANO,ADDWORD) select LEVYNO,BANKORGCODE,PAYEENAME,PAYEEORGCODE,PAYEECGACCODE,PAYEEACCT,PAYERNAME,PAYERCOUNTRYCODE,SWIFTBIC,PAYEEDATE,PAYEECNY,PAYEEAMT,CUSTOMSAMT,PREPAYEEAMT,REFUNDMENTAMT,BALANCEMODE,ACCOUNTPERIOD,BANKTRANO,ADDWORD from RCP_INCOME_HEAD_INC_EXT where CMD_TYPE='I';

delete from RCP_INCOME_HEAD_GPTMP;

\timing
