\echo ------------------RCP_INCOME_LIST----------------
select now();
\timing
insert into RCP_INCOME_LIST_GPTMP (CMD_TYPE,LEVYNO, LISTNO) select CMD_TYPE,LEVYNO, LISTNO from RCP_INCOME_LIST_INC_EXT;

delete from RCP_INCOME_LIST using RCP_INCOME_LIST_GPTMP where RCP_INCOME_LIST_GPTMP.LEVYNO=RCP_INCOME_LIST.LEVYNO AND RCP_INCOME_LIST_GPTMP.LISTNO=RCP_INCOME_LIST.LISTNO ;

insert into RCP_INCOME_LIST(LEVYNO,LISTNO,CUSTOMSDATE) select LEVYNO,LISTNO,CUSTOMSDATE from RCP_INCOME_LIST_INC_EXT where CMD_TYPE='I';

delete from RCP_INCOME_LIST_GPTMP;

\timing
