\echo ------------------RCP_RECORD_HEAD----------------
select now();
\timing
insert into RCP_RECORD_HEAD_GPTMP (CMD_TYPE,LEVYNO) select CMD_TYPE,LEVYNO from RCP_RECORD_HEAD_INC_EXT;

delete from RCP_RECORD_HEAD using RCP_RECORD_HEAD_GPTMP where RCP_RECORD_HEAD_GPTMP.LEVYNO=RCP_RECORD_HEAD.LEVYNO ;

insert into RCP_RECORD_HEAD(LEVYNO,ORGCODE,CGACCODE,ORGNAME,ENTRYID,TRADEDATE,TOTALAMT,BALANCEMODE,PACTNO,PRERECDATE,PRERECAMT) select LEVYNO,ORGCODE,CGACCODE,ORGNAME,ENTRYID,TRADEDATE,TOTALAMT,BALANCEMODE,PACTNO,PRERECDATE,PRERECAMT from RCP_RECORD_HEAD_INC_EXT where CMD_TYPE='I';

delete from RCP_RECORD_HEAD_GPTMP;

\timing
