\echo ------------------RCP_INCOME_LIST_BAK----------------
select now();
\timing
insert into RCP_INCOME_LIST_BAK_GPTMP (CMD_TYPE,LEVYNO, LISTNO) select CMD_TYPE,LEVYNO, LISTNO from RCP_INCOME_LIST_BAK_INC_EXT;

delete from RCP_INCOME_LIST_BAK using RCP_INCOME_LIST_BAK_GPTMP where RCP_INCOME_LIST_BAK_GPTMP.LEVYNO=RCP_INCOME_LIST_BAK.LEVYNO AND RCP_INCOME_LIST_BAK_GPTMP.LISTNO=RCP_INCOME_LIST_BAK.LISTNO ;

insert into RCP_INCOME_LIST_BAK(LEVYNO,LISTNO,CUSTOMSDATE) select LEVYNO,LISTNO,CUSTOMSDATE from RCP_INCOME_LIST_BAK_INC_EXT where CMD_TYPE='I';

delete from RCP_INCOME_LIST_BAK_GPTMP;

\timing
