\echo ------------------RED_MAX_NO_2007----------------
select now();
\timing
insert into RED_MAX_NO_2007_GPTMP (CMD_TYPE,MASTER_CUSTOMS, YEAR_2) select CMD_TYPE,MASTER_CUSTOMS, YEAR_2 from RED_MAX_NO_2007_INC_EXT;

delete from RED_MAX_NO_2007 using RED_MAX_NO_2007_GPTMP where RED_MAX_NO_2007_GPTMP.MASTER_CUSTOMS=RED_MAX_NO_2007.MASTER_CUSTOMS AND RED_MAX_NO_2007_GPTMP.YEAR_2=RED_MAX_NO_2007.YEAR_2 ;

insert into RED_MAX_NO_2007(MASTER_CUSTOMS,YEAR_2,MAX_NO) select MASTER_CUSTOMS,YEAR_2,MAX_NO from RED_MAX_NO_2007_INC_EXT where CMD_TYPE='I';

delete from RED_MAX_NO_2007_GPTMP;

\timing
