\echo ------------------RED_ENTRY_LIST----------------
select now();
\timing
insert into RED_ENTRY_LIST_GPTMP (CMD_TYPE,ENTRY_ID, G_NO) select CMD_TYPE,ENTRY_ID, G_NO from RED_ENTRY_LIST_INC_EXT;

delete from RED_ENTRY_LIST using RED_ENTRY_LIST_GPTMP where RED_ENTRY_LIST_GPTMP.ENTRY_ID=RED_ENTRY_LIST.ENTRY_ID AND RED_ENTRY_LIST_GPTMP.G_NO=RED_ENTRY_LIST.G_NO ;

insert into RED_ENTRY_LIST(ENTRY_ID,G_NO,CODE_TS,G_NAME,G_MODEL,ORIGIN_COUNTRY,CONTR_ITEM,TRADE_CURR,EXCHANGE_RATE,DECL_PRICE,DECL_TOTAL,USE_TO,DUTY_MODE,G_QTY,G_UNIT,QTY_1,UNIT_1,QTY_2,UNIT_2,TRADE_TOTAL,RMB_PRICE,USD_PRICE,DUTY_VALUE,G_PROCESS_MARK,WORK_USD,CLASS_MARK,G_CERT_FLAG,TARIFF_MARK,DUTY_TYPE,REAL_DUTY,DUTY_CUT,DUTY_RATE,D_RATE,QTY_DUTY_RATE,QTY_D_RATE,TAX_TYPE,REAL_TAX,TAX_CUT,TAX_RATE,T_RATE,QTY_TAX_RATE,QTY_T_RATE,REG_TYPE,REAL_REG,REG_CUT,REG_RATE,R_RATE,QTY_REG_RATE,QTY_R_RATE,OIL_TYPE,REAL_OIL,OIL_CUT,OIL_RATE,O_RATE,QTY_OIL_RATE,QTY_O_RATE,ANTI_TYPE,REAL_ANTI,ANTI_CUT,ANTI_RATE,A_RATE,QTY_ANTI_RATE,QTY_A_RATE,PRDT_NO,GOODS_ID,DECL_CODE_TS) select ENTRY_ID,G_NO,CODE_TS,G_NAME,G_MODEL,ORIGIN_COUNTRY,CONTR_ITEM,TRADE_CURR,EXCHANGE_RATE,DECL_PRICE,DECL_TOTAL,USE_TO,DUTY_MODE,G_QTY,G_UNIT,QTY_1,UNIT_1,QTY_2,UNIT_2,TRADE_TOTAL,RMB_PRICE,USD_PRICE,DUTY_VALUE,G_PROCESS_MARK,WORK_USD,CLASS_MARK,G_CERT_FLAG,TARIFF_MARK,DUTY_TYPE,REAL_DUTY,DUTY_CUT,DUTY_RATE,D_RATE,QTY_DUTY_RATE,QTY_D_RATE,TAX_TYPE,REAL_TAX,TAX_CUT,TAX_RATE,T_RATE,QTY_TAX_RATE,QTY_T_RATE,REG_TYPE,REAL_REG,REG_CUT,REG_RATE,R_RATE,QTY_REG_RATE,QTY_R_RATE,OIL_TYPE,REAL_OIL,OIL_CUT,OIL_RATE,O_RATE,QTY_OIL_RATE,QTY_O_RATE,ANTI_TYPE,REAL_ANTI,ANTI_CUT,ANTI_RATE,A_RATE,QTY_ANTI_RATE,QTY_A_RATE,PRDT_NO,GOODS_ID,DECL_CODE_TS from RED_ENTRY_LIST_INC_EXT where CMD_TYPE='I';

delete from RED_ENTRY_LIST_GPTMP;

\timing
