\echo ------------------RED_MAX_NO----------------
select now();
\timing
insert into RED_MAX_NO_GPTMP (CMD_TYPE,MASTER_CUSTOMS, YEAR_1, CLASS) select CMD_TYPE,MASTER_CUSTOMS, YEAR_1, CLASS from RED_MAX_NO_INC_EXT;

delete from RED_MAX_NO using RED_MAX_NO_GPTMP where RED_MAX_NO_GPTMP.MASTER_CUSTOMS=RED_MAX_NO.MASTER_CUSTOMS AND RED_MAX_NO_GPTMP.YEAR_1=RED_MAX_NO.YEAR_1 AND RED_MAX_NO_GPTMP.CLASS=RED_MAX_NO.CLASS ;

insert into RED_MAX_NO(MASTER_CUSTOMS,YEAR_1,CLASS,MAX_NO) select MASTER_CUSTOMS,YEAR_1,CLASS,MAX_NO from RED_MAX_NO_INC_EXT where CMD_TYPE='I';

delete from RED_MAX_NO_GPTMP;

\timing
