\echo ------------------RETURN_REL----------------
select now();
\timing
insert into RETURN_REL_GPTMP (CMD_TYPE,RET_TRANS_NO, RET_TYPE, RET_TIME) select CMD_TYPE,RET_TRANS_NO, RET_TYPE, RET_TIME from RETURN_REL_INC_EXT;

delete from RETURN_REL using RETURN_REL_GPTMP where RETURN_REL_GPTMP.RET_TRANS_NO=RETURN_REL.RET_TRANS_NO AND RETURN_REL_GPTMP.RET_TYPE=RETURN_REL.RET_TYPE AND RETURN_REL_GPTMP.RET_TIME=RETURN_REL.RET_TIME ;

insert into RETURN_REL(RET_TRANS_NO,RET_TYPE,RET_TIME,RET_CODE,RET_MESS) select RET_TRANS_NO,RET_TYPE,RET_TIME,RET_CODE,RET_MESS from RETURN_REL_INC_EXT where CMD_TYPE='I';

delete from RETURN_REL_GPTMP;

\timing
