\echo ------------------RSK_REPLICATION_LOG----------------
select now();
\timing
insert into RSK_REPLICATION_LOG_GPTMP (CMD_TYPE,CUSTOMS_CODE, TABLE_NAME, REPLI_DATE) select CMD_TYPE,CUSTOMS_CODE, TABLE_NAME, REPLI_DATE from RSK_REPLICATION_LOG_INC_EXT;

delete from RSK_REPLICATION_LOG using RSK_REPLICATION_LOG_GPTMP where RSK_REPLICATION_LOG_GPTMP.CUSTOMS_CODE=RSK_REPLICATION_LOG.CUSTOMS_CODE AND RSK_REPLICATION_LOG_GPTMP.TABLE_NAME=RSK_REPLICATION_LOG.TABLE_NAME AND RSK_REPLICATION_LOG_GPTMP.REPLI_DATE=RSK_REPLICATION_LOG.REPLI_DATE ;

insert into RSK_REPLICATION_LOG(CUSTOMS_CODE,TABLE_NAME,TABLE_C_NAME,REPLI_DATE,REPLI_ER) select CUSTOMS_CODE,TABLE_NAME,TABLE_C_NAME,REPLI_DATE,REPLI_ER from RSK_REPLICATION_LOG_INC_EXT where CMD_TYPE='I';

delete from RSK_REPLICATION_LOG_GPTMP;

\timing
