\echo ------------------RSK_CASE_FEEDBACK_LIST----------------
select now();
\timing
insert into RSK_CASE_FEEDBACK_LIST_GPTMP (CMD_TYPE,ENTRY_ID, CASE_ID, PROC_NO) select CMD_TYPE,ENTRY_ID, CASE_ID, PROC_NO from RSK_CASE_FEEDBACK_LIST_INC_EXT;

delete from RSK_CASE_FEEDBACK_LIST using RSK_CASE_FEEDBACK_LIST_GPTMP where RSK_CASE_FEEDBACK_LIST_GPTMP.ENTRY_ID=RSK_CASE_FEEDBACK_LIST.ENTRY_ID AND RSK_CASE_FEEDBACK_LIST_GPTMP.CASE_ID=RSK_CASE_FEEDBACK_LIST.CASE_ID AND RSK_CASE_FEEDBACK_LIST_GPTMP.PROC_NO=RSK_CASE_FEEDBACK_LIST.PROC_NO ;

insert into RSK_CASE_FEEDBACK_LIST(ENTRY_ID,CASE_ID,PROC_NO,PROC_RESULT) select ENTRY_ID,CASE_ID,PROC_NO,PROC_RESULT from RSK_CASE_FEEDBACK_LIST_INC_EXT where CMD_TYPE='I';

delete from RSK_CASE_FEEDBACK_LIST_GPTMP;

\timing
