\echo ------------------RSK_INSTR_ATTR_REL----------------
select now();
\timing
insert into RSK_INSTR_ATTR_REL_GPTMP (CMD_TYPE,RSK_NO) select CMD_TYPE,RSK_NO from RSK_INSTR_ATTR_REL_INC_EXT;

delete from RSK_INSTR_ATTR_REL using RSK_INSTR_ATTR_REL_GPTMP where RSK_INSTR_ATTR_REL_GPTMP.RSK_NO=RSK_INSTR_ATTR_REL.RSK_NO ;

insert into RSK_INSTR_ATTR_REL(RSK_NO,RSK_CUSTOMS,RSK_DEP,IN_OP_ID,INPUT_DATE,RSK_SRC,RSK_REASON,EXE_AREA,RSK_CONF_CUSTOMS,RSK_CONF_DEP,CONF_OP_ID,CONF_DATE,REFUSE_FLAG,REFUSE_REASON,DISPATCH_DATE,B_DATE,E_DATE,FORCE_E_CUSTOMS,FORCE_E_DEP,FORCE_E_OP_ID,FORCE_E_DATE,I_E_FLAG,BP1,BP2,TEL1,TEL2,EMAIL,RSK_INSTR_STAT,RSK_COND,RSK_COND_MID,RSK_COND_TXT,NOTE_S,MEM1,MEM2,INFO_UNLOCK_OP_ID,CONTACTER,CONTACTER_TEL,INFO_UNLOCK_DATE,FIT_COUNT,LAST_FIT_TIME,MAX_FIT_COUNT,RND_RATE,FORM_TYPE,RSK_NOTES,TOTAL_FIT_COUNT) select RSK_NO,RSK_CUSTOMS,RSK_DEP,IN_OP_ID,INPUT_DATE,RSK_SRC,RSK_REASON,EXE_AREA,RSK_CONF_CUSTOMS,RSK_CONF_DEP,CONF_OP_ID,CONF_DATE,REFUSE_FLAG,REFUSE_REASON,DISPATCH_DATE,B_DATE,E_DATE,FORCE_E_CUSTOMS,FORCE_E_DEP,FORCE_E_OP_ID,FORCE_E_DATE,I_E_FLAG,BP1,BP2,TEL1,TEL2,EMAIL,RSK_INSTR_STAT,RSK_COND,RSK_COND_MID,RSK_COND_TXT,NOTE_S,MEM1,MEM2,INFO_UNLOCK_OP_ID,CONTACTER,CONTACTER_TEL,INFO_UNLOCK_DATE,FIT_COUNT,LAST_FIT_TIME,MAX_FIT_COUNT,RND_RATE,FORM_TYPE,RSK_NOTES,TOTAL_FIT_COUNT from RSK_INSTR_ATTR_REL_INC_EXT where CMD_TYPE='I';

delete from RSK_INSTR_ATTR_REL_GPTMP;

\timing
