\echo ------------------RSK_VS_EXAM----------------
select now();
\timing
insert into RSK_VS_EXAM_GPTMP (CMD_TYPE,FORM_ID, FORM_TYPE, RSK_NO, D_DATE, EXAM_REC_ID) select CMD_TYPE,FORM_ID, FORM_TYPE, RSK_NO, D_DATE, EXAM_REC_ID from RSK_VS_EXAM_INC_EXT;

delete from RSK_VS_EXAM using RSK_VS_EXAM_GPTMP where RSK_VS_EXAM_GPTMP.FORM_ID=RSK_VS_EXAM.FORM_ID AND RSK_VS_EXAM_GPTMP.FORM_TYPE=RSK_VS_EXAM.FORM_TYPE AND RSK_VS_EXAM_GPTMP.RSK_NO=RSK_VS_EXAM.RSK_NO AND RSK_VS_EXAM_GPTMP.D_DATE=RSK_VS_EXAM.D_DATE AND RSK_VS_EXAM_GPTMP.EXAM_REC_ID=RSK_VS_EXAM.EXAM_REC_ID ;

insert into RSK_VS_EXAM(FORM_ID,FORM_TYPE,RSK_NO,D_DATE,EXAM_REC_ID) select FORM_ID,FORM_TYPE,RSK_NO,D_DATE,EXAM_REC_ID from RSK_VS_EXAM_INC_EXT where CMD_TYPE='I';

delete from RSK_VS_EXAM_GPTMP;

\timing
