\echo ------------------RSK_CONDITION----------------
select now();
\timing
insert into RSK_CONDITION_GPTMP (CMD_TYPE,CCTS_CODE) select CMD_TYPE,CCTS_CODE from RSK_CONDITION_INC_EXT;

delete from RSK_CONDITION using RSK_CONDITION_GPTMP where RSK_CONDITION_GPTMP.CCTS_CODE=RSK_CONDITION.CCTS_CODE ;

insert into RSK_CONDITION(CCTS_CODE,TRADE_CO,TRADE_NAME,CORP_TYPE,RSK_COND,RSK_COND_MID,RSK_COND_TXT,BEGIN_DATE,END_DATE,CUSTOMS_CODE,SMUGGLE_MODE,INPUT_ID,AUTHORIZE_ID,OP_TIME) select CCTS_CODE,TRADE_CO,TRADE_NAME,CORP_TYPE,RSK_COND,RSK_COND_MID,RSK_COND_TXT,BEGIN_DATE,END_DATE,CUSTOMS_CODE,SMUGGLE_MODE,INPUT_ID,AUTHORIZE_ID,OP_TIME from RSK_CONDITION_INC_EXT where CMD_TYPE='I';

delete from RSK_CONDITION_GPTMP;

\timing
