\echo ------------------RSK_CONTA_CAPACITY----------------
select now();
\timing
insert into RSK_CONTA_CAPACITY_GPTMP (CMD_TYPE,CCTS_CODE) select CMD_TYPE,CCTS_CODE from RSK_CONTA_CAPACITY_INC_EXT;

delete from RSK_CONTA_CAPACITY using RSK_CONTA_CAPACITY_GPTMP where RSK_CONTA_CAPACITY_GPTMP.CCTS_CODE=RSK_CONTA_CAPACITY.CCTS_CODE ;

insert into RSK_CONTA_CAPACITY(CCTS_CODE,CONTA_MODEL,CONTA_BULK,CONTA_WEIGHT_LOW,CONTA_WEIGHT_HIGH,CUSTOMS_CODE,INPUT_ID,BEGIN_DATE,END_DATE) select CCTS_CODE,CONTA_MODEL,CONTA_BULK,CONTA_WEIGHT_LOW,CONTA_WEIGHT_HIGH,CUSTOMS_CODE,INPUT_ID,BEGIN_DATE,END_DATE from RSK_CONTA_CAPACITY_INC_EXT where CMD_TYPE='I';

delete from RSK_CONTA_CAPACITY_GPTMP;

\timing
