\echo ------------------RSK_EXAM_OP_LOG----------------
select now();
\timing
insert into RSK_EXAM_OP_LOG_GPTMP (CMD_TYPE,EXAM_REC_ID, OP_TIME, MODI_TYPE, TABLE_NAME, ITEM_NAME) select CMD_TYPE,EXAM_REC_ID, OP_TIME, MODI_TYPE, TABLE_NAME, ITEM_NAME from RSK_EXAM_OP_LOG_INC_EXT;

delete from RSK_EXAM_OP_LOG using RSK_EXAM_OP_LOG_GPTMP where RSK_EXAM_OP_LOG_GPTMP.EXAM_REC_ID=RSK_EXAM_OP_LOG.EXAM_REC_ID AND RSK_EXAM_OP_LOG_GPTMP.OP_TIME=RSK_EXAM_OP_LOG.OP_TIME AND RSK_EXAM_OP_LOG_GPTMP.MODI_TYPE=RSK_EXAM_OP_LOG.MODI_TYPE AND RSK_EXAM_OP_LOG_GPTMP.TABLE_NAME=RSK_EXAM_OP_LOG.TABLE_NAME AND RSK_EXAM_OP_LOG_GPTMP.ITEM_NAME=RSK_EXAM_OP_LOG.ITEM_NAME ;

insert into RSK_EXAM_OP_LOG(EXAM_REC_ID,OP_TIME,OP_ER,MODI_TYPE,FORM_ID,TABLE_NAME,ITEM_NAME,ITEM_SOURCE,ITEM_CURRENT,NOTE) select EXAM_REC_ID,OP_TIME,OP_ER,MODI_TYPE,FORM_ID,TABLE_NAME,ITEM_NAME,ITEM_SOURCE,ITEM_CURRENT,NOTE from RSK_EXAM_OP_LOG_INC_EXT where CMD_TYPE='I';

delete from RSK_EXAM_OP_LOG_GPTMP;

\timing
