\echo ------------------RSK_UNLOCK_OP_LOG----------------
select now();
\timing
insert into RSK_UNLOCK_OP_LOG_GPTMP (CMD_TYPE,FORM_ID, RSK_NO, UNLOCK_TIME) select CMD_TYPE,FORM_ID, RSK_NO, UNLOCK_TIME from RSK_UNLOCK_OP_LOG_INC_EXT;

delete from RSK_UNLOCK_OP_LOG using RSK_UNLOCK_OP_LOG_GPTMP where RSK_UNLOCK_OP_LOG_GPTMP.FORM_ID=RSK_UNLOCK_OP_LOG.FORM_ID AND RSK_UNLOCK_OP_LOG_GPTMP.RSK_NO=RSK_UNLOCK_OP_LOG.RSK_NO AND RSK_UNLOCK_OP_LOG_GPTMP.UNLOCK_TIME=RSK_UNLOCK_OP_LOG.UNLOCK_TIME ;

insert into RSK_UNLOCK_OP_LOG(FORM_ID,RSK_NO,FORM_TYPE,CUSTOMS_CODE,UNLOCK_ER,UNLOCK_TIME,UNLOCK_REASON) select FORM_ID,RSK_NO,FORM_TYPE,CUSTOMS_CODE,UNLOCK_ER,UNLOCK_TIME,UNLOCK_REASON from RSK_UNLOCK_OP_LOG_INC_EXT where CMD_TYPE='I';

delete from RSK_UNLOCK_OP_LOG_GPTMP;

\timing
