\echo ------------------RSK_CASE_FEEDBACK_HEAD----------------
select now();
\timing
insert into RSK_CASE_FEEDBACK_HEAD_GPTMP (CMD_TYPE,ENTRY_ID, CASE_ID) select CMD_TYPE,ENTRY_ID, CASE_ID from RSK_CASE_FEEDBACK_HEAD_INC_EXT;

delete from RSK_CASE_FEEDBACK_HEAD using RSK_CASE_FEEDBACK_HEAD_GPTMP where RSK_CASE_FEEDBACK_HEAD_GPTMP.ENTRY_ID=RSK_CASE_FEEDBACK_HEAD.ENTRY_ID AND RSK_CASE_FEEDBACK_HEAD_GPTMP.CASE_ID=RSK_CASE_FEEDBACK_HEAD.CASE_ID ;

insert into RSK_CASE_FEEDBACK_HEAD(ENTRY_ID,CASE_ID,TRADE_NAME,AGENT_NAME,BILL_NO,D_DATE,I_E_DATE,EXAM_ER1,EXAM_PROC_TIME,CASE_PROPERTY,ADMIN_PUNISH_CERT_NO,NOTE_S,OP_ER,CASE_VALUE,TRANSFER_DEPARTMENT,RECEIVE_DEPARTMENT) select ENTRY_ID,CASE_ID,TRADE_NAME,AGENT_NAME,BILL_NO,D_DATE,I_E_DATE,EXAM_ER1,EXAM_PROC_TIME,CASE_PROPERTY,ADMIN_PUNISH_CERT_NO,NOTE_S,OP_ER,CASE_VALUE,TRANSFER_DEPARTMENT,RECEIVE_DEPARTMENT from RSK_CASE_FEEDBACK_HEAD_INC_EXT where CMD_TYPE='I';

delete from RSK_CASE_FEEDBACK_HEAD_GPTMP;

\timing
