\echo ------------------RSK_CASE_TRANSFER_G_NO----------------
select now();
\timing
insert into RSK_CASE_TRANSFER_G_NO_GPTMP (CMD_TYPE,ENTRY_ID, CASE_ID, G_NO) select CMD_TYPE,ENTRY_ID, CASE_ID, G_NO from RSK_CASE_TRANSFER_G_NO_INC_EXT;

delete from RSK_CASE_TRANSFER_G_NO using RSK_CASE_TRANSFER_G_NO_GPTMP where RSK_CASE_TRANSFER_G_NO_GPTMP.ENTRY_ID=RSK_CASE_TRANSFER_G_NO.ENTRY_ID AND RSK_CASE_TRANSFER_G_NO_GPTMP.CASE_ID=RSK_CASE_TRANSFER_G_NO.CASE_ID AND RSK_CASE_TRANSFER_G_NO_GPTMP.G_NO=RSK_CASE_TRANSFER_G_NO.G_NO ;

insert into RSK_CASE_TRANSFER_G_NO(ENTRY_ID,CASE_ID,G_NO,G_NAME) select ENTRY_ID,CASE_ID,G_NO,G_NAME from RSK_CASE_TRANSFER_G_NO_INC_EXT where CMD_TYPE='I';

delete from RSK_CASE_TRANSFER_G_NO_GPTMP;

\timing
