\echo ------------------RSK_FIT_LOG_REL----------------
select now();
\timing
insert into RSK_FIT_LOG_REL_GPTMP (CMD_TYPE,RSK_NO, FORM_ID, D_DATE) select CMD_TYPE,RSK_NO, FORM_ID, D_DATE from RSK_FIT_LOG_REL_INC_EXT;

delete from RSK_FIT_LOG_REL using RSK_FIT_LOG_REL_GPTMP where RSK_FIT_LOG_REL_GPTMP.RSK_NO=RSK_FIT_LOG_REL.RSK_NO AND RSK_FIT_LOG_REL_GPTMP.FORM_ID=RSK_FIT_LOG_REL.FORM_ID AND RSK_FIT_LOG_REL_GPTMP.D_DATE=RSK_FIT_LOG_REL.D_DATE ;

insert into RSK_FIT_LOG_REL(RSK_NO,FORM_ID,FORM_TYPE,I_E_FLAG,D_DATE,R_DATE,FIT_FLAG,INFO_LOCK_FLAG,RSK_REQUEST_DETAIL,EXAM_CONTA_FLAG,RSK_BEFORE) select RSK_NO,FORM_ID,FORM_TYPE,I_E_FLAG,D_DATE,R_DATE,FIT_FLAG,INFO_LOCK_FLAG,RSK_REQUEST_DETAIL,EXAM_CONTA_FLAG,RSK_BEFORE from RSK_FIT_LOG_REL_INC_EXT where CMD_TYPE='I';

delete from RSK_FIT_LOG_REL_GPTMP;

\timing
