\echo ------------------SERVICE_LIST----------------
select now();
\timing
insert into SERVICE_LIST_GPTMP (CMD_TYPE,MANUAL_NO, F_NO) select CMD_TYPE,MANUAL_NO, F_NO from SERVICE_LIST_INC_EXT;

delete from SERVICE_LIST using SERVICE_LIST_GPTMP where SERVICE_LIST_GPTMP.MANUAL_NO=SERVICE_LIST.MANUAL_NO AND SERVICE_LIST_GPTMP.F_NO=SERVICE_LIST.F_NO ;

insert into SERVICE_LIST(MANUAL_NO,F_NO,FEE_TYPE,FEE_RATE,G_NO,G_NAME,FEE_AMT,FEE_CURR,FEE_RMB,SERVICE_FEE) select MANUAL_NO,F_NO,FEE_TYPE,FEE_RATE,G_NO,G_NAME,FEE_AMT,FEE_CURR,FEE_RMB,SERVICE_FEE from SERVICE_LIST_INC_EXT where CMD_TYPE='I';

delete from SERVICE_LIST_GPTMP;

\timing
