\echo ------------------SERVICE_FEE----------------
select now();
\timing
insert into SERVICE_FEE_GPTMP (CMD_TYPE,MANUAL_NO) select CMD_TYPE,MANUAL_NO from SERVICE_FEE_INC_EXT;

delete from SERVICE_FEE using SERVICE_FEE_GPTMP where SERVICE_FEE_GPTMP.MANUAL_NO=SERVICE_FEE.MANUAL_NO ;

insert into SERVICE_FEE(MANUAL_NO,DUE_FEE_AMT,PAY_FEE_AMT,CREATE_DATE,RETURN_ID,RETURN_FLAG,REMAIN_AMT) select MANUAL_NO,DUE_FEE_AMT,PAY_FEE_AMT,CREATE_DATE,RETURN_ID,RETURN_FLAG,REMAIN_AMT from SERVICE_FEE_INC_EXT where CMD_TYPE='I';

delete from SERVICE_FEE_GPTMP;

\timing
