\echo ------------------SPECIAL_ENTRY----------------
select now();
\timing
insert into SPECIAL_ENTRY_GPTMP (CMD_TYPE,ENTRY_ID, OP_TIME) select CMD_TYPE,ENTRY_ID, OP_TIME from SPECIAL_ENTRY_INC_EXT;

delete from SPECIAL_ENTRY using SPECIAL_ENTRY_GPTMP where SPECIAL_ENTRY_GPTMP.ENTRY_ID=SPECIAL_ENTRY.ENTRY_ID AND SPECIAL_ENTRY_GPTMP.OP_TIME=SPECIAL_ENTRY.OP_TIME ;

insert into SPECIAL_ENTRY(ENTRY_ID,OP_TIME,OP_ER,OP_NOTE,OP_FLAG,REV_ER,REV_TIME,END_ER,END_TIME,END_NOTE) select ENTRY_ID,OP_TIME,OP_ER,OP_NOTE,OP_FLAG,REV_ER,REV_TIME,END_ER,END_TIME,END_NOTE from SPECIAL_ENTRY_INC_EXT where CMD_TYPE='I';

delete from SPECIAL_ENTRY_GPTMP;

\timing
