\echo ------------------STATUS_DETAIL----------------
select now();
\timing
insert into STATUS_DETAIL_GPTMP (CMD_TYPE,ENTRY_ID, DETAIL_COUNT) select CMD_TYPE,ENTRY_ID, DETAIL_COUNT from STATUS_DETAIL_INC_EXT;

delete from STATUS_DETAIL using STATUS_DETAIL_GPTMP where STATUS_DETAIL_GPTMP.ENTRY_ID=STATUS_DETAIL.ENTRY_ID AND STATUS_DETAIL_GPTMP.DETAIL_COUNT=STATUS_DETAIL.DETAIL_COUNT ;

insert into STATUS_DETAIL(ENTRY_ID,DETAIL_COUNT,STATUS_NUMBER,STATUS_RESULT,STATUS_DETAIL) select ENTRY_ID,DETAIL_COUNT,STATUS_NUMBER,STATUS_RESULT,STATUS_DETAIL from STATUS_DETAIL_INC_EXT where CMD_TYPE='I';

delete from STATUS_DETAIL_GPTMP;

\timing
