\echo ------------------STL_DATA_TS_LIST----------------
select now();
\timing
insert into STL_DATA_TS_LIST_GPTMP (CMD_TYPE,UCR_CODE, G_NO) select CMD_TYPE,UCR_CODE, G_NO from STL_DATA_TS_LIST_INC_EXT;

delete from STL_DATA_TS_LIST using STL_DATA_TS_LIST_GPTMP where STL_DATA_TS_LIST_GPTMP.UCR_CODE=STL_DATA_TS_LIST.UCR_CODE AND STL_DATA_TS_LIST_GPTMP.G_NO=STL_DATA_TS_LIST.G_NO ;

insert into STL_DATA_TS_LIST(UCR_CODE,G_NO,CODE_TS,G_NAME,PACK_NO) select UCR_CODE,G_NO,CODE_TS,G_NAME,PACK_NO from STL_DATA_TS_LIST_INC_EXT where CMD_TYPE='I';

delete from STL_DATA_TS_LIST_GPTMP;

\timing
