\echo ------------------STL_DATA_CONTA_LIST----------------
select now();
\timing
insert into STL_DATA_CONTA_LIST_GPTMP (CMD_TYPE,UCR_CODE, CONTAINER_ID) select CMD_TYPE,UCR_CODE, CONTAINER_ID from STL_DATA_CONTA_LIST_INC_EXT;

delete from STL_DATA_CONTA_LIST using STL_DATA_CONTA_LIST_GPTMP where STL_DATA_CONTA_LIST_GPTMP.UCR_CODE=STL_DATA_CONTA_LIST.UCR_CODE AND STL_DATA_CONTA_LIST_GPTMP.CONTAINER_ID=STL_DATA_CONTA_LIST.CONTAINER_ID ;

insert into STL_DATA_CONTA_LIST(UCR_CODE,CONTAINER_ID,SEAL_NO) select UCR_CODE,CONTAINER_ID,SEAL_NO from STL_DATA_CONTA_LIST_INC_EXT where CMD_TYPE='I';

delete from STL_DATA_CONTA_LIST_GPTMP;

\timing
