\echo ------------------TCS_SEND_LOG----------------
select now();
\timing
insert into TCS_SEND_LOG_GPTMP (CMD_TYPE,TRANS_NO) select CMD_TYPE,TRANS_NO from TCS_SEND_LOG_INC_EXT;

delete from TCS_SEND_LOG using TCS_SEND_LOG_GPTMP where TCS_SEND_LOG_GPTMP.TRANS_NO=TCS_SEND_LOG.TRANS_NO ;

insert into TCS_SEND_LOG(TRANS_NO,ENTRY_ID,TAX_ID,SEND_DATE,ACCOUNT_ORG_CODE,ORIGINAL_SOURCE,GEN_DATE,TAX_TYPE,DELAY_MARK,DUTY_FLAG,P_DATE,BUDGET_SUBJECT_CODE,TREASURY_CODE,BUDGET_LEVEL_CODE,REAL_TAX,C_DATE,PAY_MODE,PAYER_BANK_NAME,PAYER_ACCOUNT_NO,REMARK1,REMARK2,REMARK3,TREASURY_RESPONSE_DATE,RESPONSE_OP_DATE,TREASURY_RESULT,TREASURY_ADD_WORD) select TRANS_NO,ENTRY_ID,TAX_ID,SEND_DATE,ACCOUNT_ORG_CODE,ORIGINAL_SOURCE,GEN_DATE,TAX_TYPE,DELAY_MARK,DUTY_FLAG,P_DATE,BUDGET_SUBJECT_CODE,TREASURY_CODE,BUDGET_LEVEL_CODE,REAL_TAX,C_DATE,PAY_MODE,PAYER_BANK_NAME,PAYER_ACCOUNT_NO,REMARK1,REMARK2,REMARK3,TREASURY_RESPONSE_DATE,RESPONSE_OP_DATE,TREASURY_RESULT,TREASURY_ADD_WORD from TCS_SEND_LOG_INC_EXT where CMD_TYPE='I';

delete from TCS_SEND_LOG_GPTMP;

\timing
