\echo ------------------TEMP_PAGE_RANGE----------------
select now();
\timing
insert into TEMP_PAGE_RANGE_GPTMP (CMD_TYPE,PR_KEY, PR_DETAIL) select CMD_TYPE,PR_KEY, PR_DETAIL from TEMP_PAGE_RANGE_INC_EXT;

delete from TEMP_PAGE_RANGE using TEMP_PAGE_RANGE_GPTMP where TEMP_PAGE_RANGE_GPTMP.PR_KEY=TEMP_PAGE_RANGE.PR_KEY AND TEMP_PAGE_RANGE_GPTMP.PR_DETAIL=TEMP_PAGE_RANGE.PR_DETAIL ;

insert into TEMP_PAGE_RANGE(PR_KEY,PR_DETAIL) select PR_KEY,PR_DETAIL from TEMP_PAGE_RANGE_INC_EXT where CMD_TYPE='I';

delete from TEMP_PAGE_RANGE_GPTMP;

\timing
