\echo ------------------TEP_PAY_REC_REQUEST----------------
select now();
\timing
insert into TEP_PAY_REC_REQUEST_GPTMP (CMD_TYPE,REQUEST_DATE, TRANS_NO) select CMD_TYPE,REQUEST_DATE, TRANS_NO from TEP_PAY_REC_REQUEST_INC_EXT;

delete from TEP_PAY_REC_REQUEST using TEP_PAY_REC_REQUEST_GPTMP where TEP_PAY_REC_REQUEST_GPTMP.REQUEST_DATE=TEP_PAY_REC_REQUEST.REQUEST_DATE AND TEP_PAY_REC_REQUEST_GPTMP.TRANS_NO=TEP_PAY_REC_REQUEST.TRANS_NO ;

insert into TEP_PAY_REC_REQUEST(REQUEST_DATE,TRANS_NO,REQUEST_TIME,PAY_STATUS,ENTRY_ID,DUTY_FLAG,TAX_TYPE,TAX_ID,GUA_ID,AMOUNT,MEMO) select REQUEST_DATE,TRANS_NO,REQUEST_TIME,PAY_STATUS,ENTRY_ID,DUTY_FLAG,TAX_TYPE,TAX_ID,GUA_ID,AMOUNT,MEMO from TEP_PAY_REC_REQUEST_INC_EXT where CMD_TYPE='I';

delete from TEP_PAY_REC_REQUEST_GPTMP;

\timing
