\echo ------------------TEP_VOUCHER_REC_PAGE_LIST----------------
select now();
\timing
insert into TEP_VOUCHER_REC_PAGE_LIST_GPTMP (CMD_TYPE,VOUCHER_RECEIVABLE_SEQ_NO, PAYEE_CODE, BANK_CODE, PAYEE_BANK_ACCOUNT, PAGE_NAME, PAGE_NO) select CMD_TYPE,VOUCHER_RECEIVABLE_SEQ_NO, PAYEE_CODE, BANK_CODE, PAYEE_BANK_ACCOUNT, PAGE_NAME, PAGE_NO from TEP_VOUCHER_REC_PAGE_LIST_INC_EXT;

delete from TEP_VOUCHER_REC_PAGE_LIST using TEP_VOUCHER_REC_PAGE_LIST_GPTMP where TEP_VOUCHER_REC_PAGE_LIST_GPTMP.VOUCHER_RECEIVABLE_SEQ_NO=TEP_VOUCHER_REC_PAGE_LIST.VOUCHER_RECEIVABLE_SEQ_NO AND TEP_VOUCHER_REC_PAGE_LIST_GPTMP.PAYEE_CODE=TEP_VOUCHER_REC_PAGE_LIST.PAYEE_CODE AND TEP_VOUCHER_REC_PAGE_LIST_GPTMP.BANK_CODE=TEP_VOUCHER_REC_PAGE_LIST.BANK_CODE AND TEP_VOUCHER_REC_PAGE_LIST_GPTMP.PAYEE_BANK_ACCOUNT=TEP_VOUCHER_REC_PAGE_LIST.PAYEE_BANK_ACCOUNT AND TEP_VOUCHER_REC_PAGE_LIST_GPTMP.PAGE_NAME=TEP_VOUCHER_REC_PAGE_LIST.PAGE_NAME AND TEP_VOUCHER_REC_PAGE_LIST_GPTMP.PAGE_NO=TEP_VOUCHER_REC_PAGE_LIST.PAGE_NO ;

insert into TEP_VOUCHER_REC_PAGE_LIST(VOUCHER_RECEIVABLE_SEQ_NO,BANK_CODE,PAYEE_BANK_ACCOUNT,PAYER_CONGREG_BK_ID,PAYER_CONGREG_BK_NAME,PAGE_NO,PAGE_NAME,PAGE_OBJECT,PAYEE_CODE) select VOUCHER_RECEIVABLE_SEQ_NO,BANK_CODE,PAYEE_BANK_ACCOUNT,PAYER_CONGREG_BK_ID,PAYER_CONGREG_BK_NAME,PAGE_NO,PAGE_NAME,PAGE_OBJECT,PAYEE_CODE from TEP_VOUCHER_REC_PAGE_LIST_INC_EXT where CMD_TYPE='I';

delete from TEP_VOUCHER_REC_PAGE_LIST_GPTMP;

\timing
