\echo ------------------TEP_DEBIT_REC_RESPONSE----------------
select now();
\timing
insert into TEP_DEBIT_REC_RESPONSE_GPTMP (CMD_TYPE,TRANS_NO, RESPONSE_DATE) select CMD_TYPE,TRANS_NO, RESPONSE_DATE from TEP_DEBIT_REC_RESPONSE_INC_EXT;

delete from TEP_DEBIT_REC_RESPONSE using TEP_DEBIT_REC_RESPONSE_GPTMP where TEP_DEBIT_REC_RESPONSE_GPTMP.TRANS_NO=TEP_DEBIT_REC_RESPONSE.TRANS_NO AND TEP_DEBIT_REC_RESPONSE_GPTMP.RESPONSE_DATE=TEP_DEBIT_REC_RESPONSE.RESPONSE_DATE ;

insert into TEP_DEBIT_REC_RESPONSE(TRANS_NO,RESPONSE_DATE,RESPONSE_TIME,REC_CODE,MEMO) select TRANS_NO,RESPONSE_DATE,RESPONSE_TIME,REC_CODE,MEMO from TEP_DEBIT_REC_RESPONSE_INC_EXT where CMD_TYPE='I';

delete from TEP_DEBIT_REC_RESPONSE_GPTMP;

\timing
