\echo ------------------TEP_VOUCHER_REC_LIST_DETAIL----------------
select now();
\timing
insert into TEP_VOUCHER_REC_LIST_DETAIL_GPTMP (CMD_TYPE,VOUCHER_RECEIVABLE_SEQ_NO, PAYEE_CODE, BANK_CODE, PAYEE_BANK_ACCOUNT) select CMD_TYPE,VOUCHER_RECEIVABLE_SEQ_NO, PAYEE_CODE, BANK_CODE, PAYEE_BANK_ACCOUNT from TEP_VOUCHER_REC_LIST_DETAIL_INC_EXT;

delete from TEP_VOUCHER_REC_LIST_DETAIL using TEP_VOUCHER_REC_LIST_DETAIL_GPTMP where TEP_VOUCHER_REC_LIST_DETAIL_GPTMP.VOUCHER_RECEIVABLE_SEQ_NO=TEP_VOUCHER_REC_LIST_DETAIL.VOUCHER_RECEIVABLE_SEQ_NO AND TEP_VOUCHER_REC_LIST_DETAIL_GPTMP.PAYEE_CODE=TEP_VOUCHER_REC_LIST_DETAIL.PAYEE_CODE AND TEP_VOUCHER_REC_LIST_DETAIL_GPTMP.BANK_CODE=TEP_VOUCHER_REC_LIST_DETAIL.BANK_CODE AND TEP_VOUCHER_REC_LIST_DETAIL_GPTMP.PAYEE_BANK_ACCOUNT=TEP_VOUCHER_REC_LIST_DETAIL.PAYEE_BANK_ACCOUNT ;

insert into TEP_VOUCHER_REC_LIST_DETAIL(VOUCHER_RECEIVABLE_SEQ_NO,BANK_CODE,PAYEE_BANK_ACCOUNT,PAYEE_CODE,PAYEE_BANK_NAME,PAYEE_BRANCH_CODE,PAYEE_BANK_ACCOUNT_NAME) select VOUCHER_RECEIVABLE_SEQ_NO,BANK_CODE,PAYEE_BANK_ACCOUNT,PAYEE_CODE,PAYEE_BANK_NAME,PAYEE_BRANCH_CODE,PAYEE_BANK_ACCOUNT_NAME from TEP_VOUCHER_REC_LIST_DETAIL_INC_EXT where CMD_TYPE='I';

delete from TEP_VOUCHER_REC_LIST_DETAIL_GPTMP;

\timing
