\echo ------------------TMP_EMS_DCR_ENT----------------
select now();
\timing
insert into TMP_EMS_DCR_ENT_GPTMP (CMD_TYPE,EMS_NO, DCR_TIMES, ENTRY_ID) select CMD_TYPE,EMS_NO, DCR_TIMES, ENTRY_ID from TMP_EMS_DCR_ENT_INC_EXT;

delete from TMP_EMS_DCR_ENT using TMP_EMS_DCR_ENT_GPTMP where TMP_EMS_DCR_ENT_GPTMP.EMS_NO=TMP_EMS_DCR_ENT.EMS_NO AND TMP_EMS_DCR_ENT_GPTMP.DCR_TIMES=TMP_EMS_DCR_ENT.DCR_TIMES AND TMP_EMS_DCR_ENT_GPTMP.ENTRY_ID=TMP_EMS_DCR_ENT.ENTRY_ID ;

insert into TMP_EMS_DCR_ENT(EMS_NO,DCR_TIMES,ENTRY_ID,MASTER_CUSTOMS,I_E_FLAG,ITEMS_NUM,DECLARE_DATE,I_E_DATE,DU_CODE,ENT_MARK,NOTE,MODIFY_MARK) select EMS_NO,DCR_TIMES,ENTRY_ID,MASTER_CUSTOMS,I_E_FLAG,ITEMS_NUM,DECLARE_DATE,I_E_DATE,DU_CODE,ENT_MARK,NOTE,MODIFY_MARK from TMP_EMS_DCR_ENT_INC_EXT where CMD_TYPE='I';

delete from TMP_EMS_DCR_ENT_GPTMP;

\timing
