\echo ------------------TRADE_GPM_RTX----------------
select now();
\timing
insert into TRADE_GPM_RTX_GPTMP (CMD_TYPE,TRADE_MODE, SIGN_TYPE, SIGN_MODE) select CMD_TYPE,TRADE_MODE, SIGN_TYPE, SIGN_MODE from TRADE_GPM_RTX_INC_EXT;

delete from TRADE_GPM_RTX using TRADE_GPM_RTX_GPTMP where TRADE_GPM_RTX_GPTMP.TRADE_MODE=TRADE_GPM_RTX.TRADE_MODE AND TRADE_GPM_RTX_GPTMP.SIGN_TYPE=TRADE_GPM_RTX.SIGN_TYPE AND TRADE_GPM_RTX_GPTMP.SIGN_MODE=TRADE_GPM_RTX.SIGN_MODE ;

insert into TRADE_GPM_RTX(TRADE_MODE,SIGN_TYPE,SIGN_MODE) select TRADE_MODE,SIGN_TYPE,SIGN_MODE from TRADE_GPM_RTX_INC_EXT where CMD_TYPE='I';

delete from TRADE_GPM_RTX_GPTMP;

\timing
