\echo ------------------TRANSFER_FEE_LOG----------------
select now();
\timing
insert into TRANSFER_FEE_LOG_GPTMP (CMD_TYPE,MANUAL_NO, RTN_MANUAL_NO, CREATE_DATE) select CMD_TYPE,MANUAL_NO, RTN_MANUAL_NO, CREATE_DATE from TRANSFER_FEE_LOG_INC_EXT;

delete from TRANSFER_FEE_LOG using TRANSFER_FEE_LOG_GPTMP where TRANSFER_FEE_LOG_GPTMP.MANUAL_NO=TRANSFER_FEE_LOG.MANUAL_NO AND TRANSFER_FEE_LOG_GPTMP.RTN_MANUAL_NO=TRANSFER_FEE_LOG.RTN_MANUAL_NO AND TRANSFER_FEE_LOG_GPTMP.CREATE_DATE=TRANSFER_FEE_LOG.CREATE_DATE ;

insert into TRANSFER_FEE_LOG(MANUAL_NO,RTN_MANUAL_NO,CREATE_DATE,TRANSFER_FEE) select MANUAL_NO,RTN_MANUAL_NO,CREATE_DATE,TRANSFER_FEE from TRANSFER_FEE_LOG_INC_EXT where CMD_TYPE='I';

delete from TRANSFER_FEE_LOG_GPTMP;

\timing
