\echo ------------------TRN_EXAM_MAX_SEQ----------------
select now();
\timing
insert into TRN_EXAM_MAX_SEQ_GPTMP (CMD_TYPE,TYPE, YEARAREA) select CMD_TYPE,TYPE, YEARAREA from TRN_EXAM_MAX_SEQ_INC_EXT;

delete from TRN_EXAM_MAX_SEQ using TRN_EXAM_MAX_SEQ_GPTMP where TRN_EXAM_MAX_SEQ_GPTMP.TYPE=TRN_EXAM_MAX_SEQ.TYPE AND TRN_EXAM_MAX_SEQ_GPTMP.YEARAREA=TRN_EXAM_MAX_SEQ.YEARAREA ;

insert into TRN_EXAM_MAX_SEQ(TYPE,YEARAREA,MAX_SEQ) select TYPE,YEARAREA,MAX_SEQ from TRN_EXAM_MAX_SEQ_INC_EXT where CMD_TYPE='I';

delete from TRN_EXAM_MAX_SEQ_GPTMP;

\timing
