\echo ------------------TRN_CHECK----------------
select now();
\timing
insert into TRN_CHECK_GPTMP (CMD_TYPE,NO) select CMD_TYPE,NO from TRN_CHECK_INC_EXT;

delete from TRN_CHECK using TRN_CHECK_GPTMP where TRN_CHECK_GPTMP.NO=TRN_CHECK.NO ;

insert into TRN_CHECK(NO,I_E_FLAG,CODE_S,CODE_E,GOODS_NAME,AGENT_NAME,TRANS_NAME,TRAF_NAME,PORT_CO,RESULT_MARK,RESULT_STATUS,EFFECT_D_S,EFFECT_D_E,ISSUE_PORT,ISSUE_OP_ID,ISSUE_TIME,MODI_TIME) select NO,I_E_FLAG,CODE_S,CODE_E,GOODS_NAME,AGENT_NAME,TRANS_NAME,TRAF_NAME,PORT_CO,RESULT_MARK,RESULT_STATUS,EFFECT_D_S,EFFECT_D_E,ISSUE_PORT,ISSUE_OP_ID,ISSUE_TIME,MODI_TIME from TRN_CHECK_INC_EXT where CMD_TYPE='I';

delete from TRN_CHECK_GPTMP;

\timing
