\echo ------------------TRN_DELAY_FORM----------------
select now();
\timing
insert into TRN_DELAY_FORM_GPTMP (CMD_TYPE,TURN_NO) select CMD_TYPE,TURN_NO from TRN_DELAY_FORM_INC_EXT;

delete from TRN_DELAY_FORM using TRN_DELAY_FORM_GPTMP where TRN_DELAY_FORM_GPTMP.TURN_NO=TRN_DELAY_FORM.TURN_NO ;

insert into TRN_DELAY_FORM(TURN_NO,ID_CHK,DUTY_FLAG,TAX_TYPE,TAX_ID,DELAY_MARK,BOOK_NO,DELAY_ACCOUNT,DELAY_DAY,P_DATE,DUTY_PRINT,C_DATE,CANCEL_ER,SYS_DATE,TAX_TYPES,CUT_NOTE) select TURN_NO,ID_CHK,DUTY_FLAG,TAX_TYPE,TAX_ID,DELAY_MARK,BOOK_NO,DELAY_ACCOUNT,DELAY_DAY,P_DATE,DUTY_PRINT,C_DATE,CANCEL_ER,SYS_DATE,TAX_TYPES,CUT_NOTE from TRN_DELAY_FORM_INC_EXT where CMD_TYPE='I';

delete from TRN_DELAY_FORM_GPTMP;

\timing
