\echo ------------------TRN_POP_LIST----------------
select now();
\timing
insert into TRN_POP_LIST_GPTMP (CMD_TYPE,APPLY_NO, RECORD_NUMBER) select CMD_TYPE,APPLY_NO, RECORD_NUMBER from TRN_POP_LIST_INC_EXT;

delete from TRN_POP_LIST using TRN_POP_LIST_GPTMP where TRN_POP_LIST_GPTMP.APPLY_NO=TRN_POP_LIST.APPLY_NO AND TRN_POP_LIST_GPTMP.RECORD_NUMBER=TRN_POP_LIST.RECORD_NUMBER ;

insert into TRN_POP_LIST(APPLY_NO,RECORD_NUMBER,ENTRY_ID,PRE_NO,PROCESS_FLAG,SELECT_FLAG,BILL_REJECT_REASON,TRAF_MODE,SHIP_ID,SHIP_NAME_EN,VOYAGE_NO,BILL_NO,PACK_NO,GROSS_WT,GOODS_COUNT,CONTA_C,OWNER_NAME,CONTA_NO,TRANS_NAME,TRANS_WEIGHT,CONTA_MODEL,SEAL_NO,SEAL_NUM,ESEAL_ID) select APPLY_NO,RECORD_NUMBER,ENTRY_ID,PRE_NO,PROCESS_FLAG,SELECT_FLAG,BILL_REJECT_REASON,TRAF_MODE,SHIP_ID,SHIP_NAME_EN,VOYAGE_NO,BILL_NO,PACK_NO,GROSS_WT,GOODS_COUNT,CONTA_C,OWNER_NAME,CONTA_NO,TRANS_NAME,TRANS_WEIGHT,CONTA_MODEL,SEAL_NO,SEAL_NUM,ESEAL_ID from TRN_POP_LIST_INC_EXT where CMD_TYPE='I';

delete from TRN_POP_LIST_GPTMP;

\timing
