\echo ------------------TRN_POP_COP_REL----------------
select now();
\timing
insert into TRN_POP_COP_REL_GPTMP (CMD_TYPE,AGENT_CODE, CUSTOMS_CODE) select CMD_TYPE,AGENT_CODE, CUSTOMS_CODE from TRN_POP_COP_REL_INC_EXT;

delete from TRN_POP_COP_REL using TRN_POP_COP_REL_GPTMP where TRN_POP_COP_REL_GPTMP.AGENT_CODE=TRN_POP_COP_REL.AGENT_CODE AND TRN_POP_COP_REL_GPTMP.CUSTOMS_CODE=TRN_POP_COP_REL.CUSTOMS_CODE ;

insert into TRN_POP_COP_REL(AGENT_CODE,AGENT_NAME,CUSTOMS_CODE,OTHER_COP,OTHER_RECV_PORT,VALID_FLAG,OP_ER,OP_DATE) select AGENT_CODE,AGENT_NAME,CUSTOMS_CODE,OTHER_COP,OTHER_RECV_PORT,VALID_FLAG,OP_ER,OP_DATE from TRN_POP_COP_REL_INC_EXT where CMD_TYPE='I';

delete from TRN_POP_COP_REL_GPTMP;

\timing
