\echo ------------------YD_DECLARE_REL----------------
select now();
\timing
insert into YD_DECLARE_REL_GPTMP (CMD_TYPE,TRADE_CO, CUSTOMS_CODE) select CMD_TYPE,TRADE_CO, CUSTOMS_CODE from YD_DECLARE_REL_INC_EXT;

delete from YD_DECLARE_REL using YD_DECLARE_REL_GPTMP where YD_DECLARE_REL_GPTMP.TRADE_CO=YD_DECLARE_REL.TRADE_CO AND YD_DECLARE_REL_GPTMP.CUSTOMS_CODE=YD_DECLARE_REL.CUSTOMS_CODE ;

insert into YD_DECLARE_REL(TRADE_CO,CUSTOMS_CODE) select TRADE_CO,CUSTOMS_CODE from YD_DECLARE_REL_INC_EXT where CMD_TYPE='I';

delete from YD_DECLARE_REL_GPTMP;

\timing
