\echo ---------------ACCOUNT----------------
VACUUM ACCOUNT_GPTMP_TODAY;
\echo ---------------AGREEMENT_GOODS_LIST----------------
VACUUM AGREEMENT_GOODS_LIST_GPTMP_TODAY;
\echo ---------------AMS_MODI_LOG----------------
VACUUM AMS_MODI_LOG_GPTMP_TODAY;
\echo ---------------AMSLIST_BODY----------------
VACUUM AMSLIST_BODY_GPTMP_TODAY;
\echo ---------------AMSLIST_HEAD----------------
VACUUM AMSLIST_HEAD_GPTMP_TODAY;
\echo ---------------APPL_CLOSE----------------
VACUUM APPL_CLOSE_GPTMP_TODAY;
\echo ---------------APPL_CLOSE_CONSUME----------------
VACUUM APPL_CLOSE_CONSUME_GPTMP_TODAY;
\echo ---------------APPLY_HEAD----------------
VACUUM APPLY_HEAD_GPTMP_TODAY;
\echo ---------------APPLY_LIST----------------
VACUUM APPLY_LIST_GPTMP_TODAY;
\echo ---------------ARRIVAL_INFO_HEAD----------------
VACUUM ARRIVAL_INFO_HEAD_GPTMP_TODAY;
\echo ---------------ARRIVAL_INFO_LIST----------------
VACUUM ARRIVAL_INFO_LIST_GPTMP_TODAY;
\echo ---------------BAK_BWS_EXAM_CERT_LIST----------------
VACUUM BAK_BWS_EXAM_CERT_LIST_GPTMP_TODAY;
\echo ---------------BAK_BWS_EXAM_GOOD_LIST----------------
VACUUM BAK_BWS_EXAM_GOOD_LIST_GPTMP_TODAY;
\echo ---------------BAK_BWS_EXAM_HEAD----------------
VACUUM BAK_BWS_EXAM_HEAD_GPTMP_TODAY;
\echo ---------------BAK_CONSUME----------------
VACUUM BAK_CONSUME_GPTMP_TODAY;
\echo ---------------BAK_CONTRACT_HEAD----------------
VACUUM BAK_CONTRACT_HEAD_GPTMP_TODAY;
\echo ---------------BAK_DCG_BILL_HEAD----------------
VACUUM BAK_DCG_BILL_HEAD_GPTMP_TODAY;
\echo ---------------BAK_DCG_BILL_LIST----------------
VACUUM BAK_DCG_BILL_LIST_GPTMP_TODAY;
\echo ---------------BAK_DCG_DEDUCT----------------
VACUUM BAK_DCG_DEDUCT_GPTMP_TODAY;
\echo ---------------BAK_DCG_DEDUCT_LOG----------------
VACUUM BAK_DCG_DEDUCT_LOG_GPTMP_TODAY;
\echo ---------------BAK_DCG_HEAD----------------
VACUUM BAK_DCG_HEAD_GPTMP_TODAY;
\echo ---------------BAK_DCG_LIST----------------
VACUUM BAK_DCG_LIST_GPTMP_TODAY;
\echo ---------------BAK_EMS_APPR_HEAD----------------
VACUUM BAK_EMS_APPR_HEAD_GPTMP_TODAY;
\echo ---------------BAK_EMS_APPR_LIST----------------
VACUUM BAK_EMS_APPR_LIST_GPTMP_TODAY;
\echo ---------------BAK_EMS_CONSUME----------------
VACUUM BAK_EMS_CONSUME_GPTMP_TODAY;
\echo ---------------BAK_EMS_DEDUCT_CLR----------------
VACUUM BAK_EMS_DEDUCT_CLR_GPTMP_TODAY;
\echo ---------------BAK_EMS_HEAD----------------
VACUUM BAK_EMS_HEAD_GPTMP_TODAY;
\echo ---------------BAK_EMS_LIST----------------
VACUUM BAK_EMS_LIST_GPTMP_TODAY;
\echo ---------------BAK_EX_CONTRACT_LIST----------------
VACUUM BAK_EX_CONTRACT_LIST_GPTMP_TODAY;
\echo ---------------BAK_EX_FASCICLE_LIST----------------
VACUUM BAK_EX_FASCICLE_LIST_GPTMP_TODAY;
\echo ---------------BAK_FASCICLE_HEAD----------------
VACUUM BAK_FASCICLE_HEAD_GPTMP_TODAY;
\echo ---------------BAK_IM_CONTRACT_LIST----------------
VACUUM BAK_IM_CONTRACT_LIST_GPTMP_TODAY;
\echo ---------------BAK_IM_FASCICLE_LIST----------------
VACUUM BAK_IM_FASCICLE_LIST_GPTMP_TODAY;
\echo ---------------BANK_ACCOUNT----------------
VACUUM BANK_ACCOUNT_GPTMP_TODAY;
\echo ---------------BCK_COP_HEAD----------------
VACUUM BCK_COP_HEAD_GPTMP_TODAY;
\echo ---------------BCK_COP_LIST----------------
VACUUM BCK_COP_LIST_GPTMP_TODAY;
\echo ---------------BCK_COP_LIST_TEMP----------------
VACUUM BCK_COP_LIST_TEMP_GPTMP_TODAY;
\echo ---------------BCK_COP_PARA_HEAD----------------
VACUUM BCK_COP_PARA_HEAD_GPTMP_TODAY;
\echo ---------------BCK_COP_PARA_LIST----------------
VACUUM BCK_COP_PARA_LIST_GPTMP_TODAY;
\echo ---------------BCK_EXECUTOR----------------
VACUUM BCK_EXECUTOR_GPTMP_TODAY;
\echo ---------------BCK_HANDOVER----------------
VACUUM BCK_HANDOVER_GPTMP_TODAY;
\echo ---------------BCK_HANDOVER_TYPE----------------
VACUUM BCK_HANDOVER_TYPE_GPTMP_TODAY;
\echo ---------------BCK_HEAD----------------
VACUUM BCK_HEAD_GPTMP_TODAY;
\echo ---------------BCK_SEQ----------------
VACUUM BCK_SEQ_GPTMP_TODAY;
\echo ---------------BCK_STOCK_HEAD----------------
VACUUM BCK_STOCK_HEAD_GPTMP_TODAY;
\echo ---------------BCK_STOCK_LIST----------------
VACUUM BCK_STOCK_LIST_GPTMP_TODAY;
\echo ---------------BCK_WORKFLOW----------------
VACUUM BCK_WORKFLOW_GPTMP_TODAY;
\echo ---------------BTI_DATA_CONTA_LIST----------------
VACUUM BTI_DATA_CONTA_LIST_GPTMP_TODAY;
\echo ---------------BTI_DATA_HEAD----------------
VACUUM BTI_DATA_HEAD_GPTMP_TODAY;
\echo ---------------BTI_DATA_TS_LIST----------------
VACUUM BTI_DATA_TS_LIST_GPTMP_TODAY;
\echo ---------------BWS_AUDIT_HEAD----------------
VACUUM BWS_AUDIT_HEAD_GPTMP_TODAY;
\echo ---------------BWS_AUDIT_LIST----------------
VACUUM BWS_AUDIT_LIST_GPTMP_TODAY;
\echo ---------------BWS_DCR_BILL_LIST----------------
VACUUM BWS_DCR_BILL_LIST_GPTMP_TODAY;
\echo ---------------BWS_DCR_HEAD----------------
VACUUM BWS_DCR_HEAD_GPTMP_TODAY;
\echo ---------------BWS_DCR_LIST----------------
VACUUM BWS_DCR_LIST_GPTMP_TODAY;
\echo ---------------BWS_DEDUCT----------------
VACUUM BWS_DEDUCT_GPTMP_TODAY;
\echo ---------------BWS_DEDUCT_LOG----------------
VACUUM BWS_DEDUCT_LOG_GPTMP_TODAY;
\echo ---------------BWS_EXAM_CERT_LIST----------------
VACUUM BWS_EXAM_CERT_LIST_GPTMP_TODAY;
\echo ---------------BWS_EXAM_GOOD_LIST----------------
VACUUM BWS_EXAM_GOOD_LIST_GPTMP_TODAY;
\echo ---------------BWS_EXAM_HEAD----------------
VACUUM BWS_EXAM_HEAD_GPTMP_TODAY;
\echo ---------------BWS_EXAM_PASSCERT----------------
VACUUM BWS_EXAM_PASSCERT_GPTMP_TODAY;
\echo ---------------BWS_FORM_HEAD----------------
VACUUM BWS_FORM_HEAD_GPTMP_TODAY;
\echo ---------------BWS_FORM_LIST----------------
VACUUM BWS_FORM_LIST_GPTMP_TODAY;
\echo ---------------BWS_GB_LIST----------------
VACUUM BWS_GB_LIST_GPTMP_TODAY;
\echo ---------------BWS_HEAD----------------
VACUUM BWS_HEAD_GPTMP_TODAY;
\echo ---------------BWS_LIST----------------
VACUUM BWS_LIST_GPTMP_TODAY;
\echo ---------------BWS_MANIFEST_HEAD----------------
VACUUM BWS_MANIFEST_HEAD_GPTMP_TODAY;
\echo ---------------BWS_MANIFEST_LIST----------------
VACUUM BWS_MANIFEST_LIST_GPTMP_TODAY;
\echo ---------------BWS_SEQ----------------
VACUUM BWS_SEQ_GPTMP_TODAY;
\echo ---------------BWS_VAR----------------
VACUUM BWS_VAR_GPTMP_TODAY;
\echo ---------------BWS_WORKFLOW----------------
VACUUM BWS_WORKFLOW_GPTMP_TODAY;
\echo ---------------CCTS_ERROR_LOG----------------
VACUUM CCTS_ERROR_LOG_GPTMP_TODAY;
\echo ---------------CCTS_ONLINE_RESULT----------------
VACUUM CCTS_ONLINE_RESULT_GPTMP_TODAY;
\echo ---------------CCTS_ONLINE_RESULT_BAK----------------
VACUUM CCTS_ONLINE_RESULT_BAK_GPTMP_TODAY;
\echo ---------------CCTS_PERFORMANCE----------------
VACUUM CCTS_PERFORMANCE_GPTMP_TODAY;
\echo ---------------CCTS_RSK_RESULT----------------
VACUUM CCTS_RSK_RESULT_GPTMP_TODAY;
\echo ---------------CCTS_RSK_RESULT_BAK----------------
VACUUM CCTS_RSK_RESULT_BAK_GPTMP_TODAY;
\echo ---------------CDL_CERTIFICATE----------------
VACUUM CDL_CERTIFICATE_GPTMP_TODAY;
\echo ---------------CDL_CHK----------------
VACUUM CDL_CHK_GPTMP_TODAY;
\echo ---------------CDL_COMMODITY----------------
VACUUM CDL_COMMODITY_GPTMP_TODAY;
\echo ---------------CDL_COMP_COMM_MODIFY_LOG----------------
VACUUM CDL_COMP_COMM_MODIFY_LOG_GPTMP_TODAY;
\echo ---------------CDL_COMP_COMM_OP_LOG----------------
VACUUM CDL_COMP_COMM_OP_LOG_GPTMP_TODAY;
\echo ---------------CDL_COMPANY----------------
VACUUM CDL_COMPANY_GPTMP_TODAY;
\echo ---------------CDL_CONTAINER----------------
VACUUM CDL_CONTAINER_GPTMP_TODAY;
\echo ---------------CDL_DEL_CERTIFICATE_LOG----------------
VACUUM CDL_DEL_CERTIFICATE_LOG_GPTMP_TODAY;
\echo ---------------CDL_DEL_CONTAINER_LOG----------------
VACUUM CDL_DEL_CONTAINER_LOG_GPTMP_TODAY;
\echo ---------------CDL_DEL_HEAD_LOG----------------
VACUUM CDL_DEL_HEAD_LOG_GPTMP_TODAY;
\echo ---------------CDL_DEL_LIST_LOG----------------
VACUUM CDL_DEL_LIST_LOG_GPTMP_TODAY;
\echo ---------------CDL_EDI_MESS----------------
VACUUM CDL_EDI_MESS_GPTMP_TODAY;
\echo ---------------CDL_EMS_DEDUCT----------------
VACUUM CDL_EMS_DEDUCT_GPTMP_TODAY;
\echo ---------------CDL_EMS_DEDUCT_LOG----------------
VACUUM CDL_EMS_DEDUCT_LOG_GPTMP_TODAY;
\echo ---------------CDL_ENTRY_HEAD----------------
VACUUM CDL_ENTRY_HEAD_GPTMP_TODAY;
\echo ---------------CDL_ENTRY_LIST----------------
VACUUM CDL_ENTRY_LIST_GPTMP_TODAY;
\echo ---------------CDL_HEAD----------------
VACUUM CDL_HEAD_GPTMP_TODAY;
\echo ---------------CDL_LICENSE_DEDUCT----------------
VACUUM CDL_LICENSE_DEDUCT_GPTMP_TODAY;
\echo ---------------CDL_LIST----------------
VACUUM CDL_LIST_GPTMP_TODAY;
\echo ---------------CDL_LOCK_COMMODITY----------------
VACUUM CDL_LOCK_COMMODITY_GPTMP_TODAY;
\echo ---------------CDL_MODI_LOG----------------
VACUUM CDL_MODI_LOG_GPTMP_TODAY;
\echo ---------------CDL_OP_LOG----------------
VACUUM CDL_OP_LOG_GPTMP_TODAY;
\echo ---------------CDL_OVERDUE_LIST----------------
VACUUM CDL_OVERDUE_LIST_GPTMP_TODAY;
\echo ---------------CDL_STATUS_DETAIL----------------
VACUUM CDL_STATUS_DETAIL_GPTMP_TODAY;
\echo ---------------CDL_WORKFLOW----------------
VACUUM CDL_WORKFLOW_GPTMP_TODAY;
\echo ---------------CHK_COP_RATIO----------------
VACUUM CHK_COP_RATIO_GPTMP_TODAY;
\echo ---------------CHK_COUNTER----------------
VACUUM CHK_COUNTER_GPTMP_TODAY;
\echo ---------------CHK_RATE_LIMIT----------------
VACUUM CHK_RATE_LIMIT_GPTMP_TODAY;
\echo ---------------CHKHS_MNLPROC----------------
VACUUM CHKHS_MNLPROC_GPTMP_TODAY;
\echo ---------------CIC_CODE----------------
VACUUM CIC_CODE_GPTMP_TODAY;
\echo ---------------CIC_HEAD----------------
VACUUM CIC_HEAD_GPTMP_TODAY;
\echo ---------------CIC_LIST----------------
VACUUM CIC_LIST_GPTMP_TODAY;
\echo ---------------CIC_MAXID----------------
VACUUM CIC_MAXID_GPTMP_TODAY;
\echo ---------------CIC_SEND_REL----------------
VACUUM CIC_SEND_REL_GPTMP_TODAY;
\echo ---------------CLAIM----------------
VACUUM CLAIM_GPTMP_TODAY;
\echo ---------------CLC_CHKRATE_LIMIT----------------
VACUUM CLC_CHKRATE_LIMIT_GPTMP_TODAY;
\echo ---------------CLC_GPR_RATIO----------------
VACUUM CLC_GPR_RATIO_GPTMP_TODAY;
\echo ---------------CLC_GPR_RATIO_BAK----------------
VACUUM CLC_GPR_RATIO_BAK_GPTMP_TODAY;
\echo ---------------CNS_COUNTER_TABLE----------------
VACUUM CNS_COUNTER_TABLE_GPTMP_TODAY;
\echo ---------------CO_CLASS_REL----------------
VACUUM CO_CLASS_REL_GPTMP_TODAY;
\echo ---------------COMPANY_REL----------------
VACUUM COMPANY_REL_GPTMP_TODAY;
\echo ---------------CONSUME----------------
VACUUM CONSUME_GPTMP_TODAY;
\echo ---------------CONSUME_DB----------------
VACUUM CONSUME_DB_GPTMP_TODAY;
\echo ---------------CONSUME_GOODS----------------
VACUUM CONSUME_GOODS_GPTMP_TODAY;
\echo ---------------CONTA----------------
VACUUM CONTA_GPTMP_TODAY;
\echo ---------------CONTA_MONITOR----------------
VACUUM CONTA_MONITOR_GPTMP_TODAY;
\echo ---------------CONTRACT_HEAD----------------
VACUUM CONTRACT_HEAD_GPTMP_TODAY;
\echo ---------------CONTRACT_WORKFLOW----------------
VACUUM CONTRACT_WORKFLOW_GPTMP_TODAY;
\echo ---------------CONVEYANCE----------------
VACUUM CONVEYANCE_GPTMP_TODAY;
\echo ---------------CONVEYANCE_SEGMENT----------------
VACUUM CONVEYANCE_SEGMENT_GPTMP_TODAY;
\echo ---------------COP_CONSUME----------------
VACUUM COP_CONSUME_GPTMP_TODAY;
\echo ---------------COP_SPEC_REL----------------
VACUUM COP_SPEC_REL_GPTMP_TODAY;
\echo ---------------COPLOG_DELETE_REL----------------
VACUUM COPLOG_DELETE_REL_GPTMP_TODAY;
\echo ---------------COPLOG_MODIFY_REL----------------
VACUUM COPLOG_MODIFY_REL_GPTMP_TODAY;
\echo ---------------CORP_HEAD----------------
VACUUM CORP_HEAD_GPTMP_TODAY;
\echo ---------------CORP_LIST----------------
VACUUM CORP_LIST_GPTMP_TODAY;
\echo ---------------CORP_TABLE----------------
VACUUM CORP_TABLE_GPTMP_TODAY;
\echo ---------------CORP_TYPE----------------
VACUUM CORP_TYPE_GPTMP_TODAY;
\echo ---------------COUNTER_TABLE----------------
VACUUM COUNTER_TABLE_GPTMP_TODAY;
\echo ---------------CREDIT_INFO----------------
VACUUM CREDIT_INFO_GPTMP_TODAY;
\echo ---------------CTS_CHKRATE_LIMIT----------------
VACUUM CTS_CHKRATE_LIMIT_GPTMP_TODAY;
\echo ---------------CTS_CHKRATE_LIMIT_BAK----------------
VACUUM CTS_CHKRATE_LIMIT_BAK_GPTMP_TODAY;
\echo ---------------CTS_PERIOD----------------
VACUUM CTS_PERIOD_GPTMP_TODAY;
\echo ---------------CUS_GOOD_CONSUME----------------
VACUUM CUS_GOOD_CONSUME_GPTMP_TODAY;
\echo ---------------CUSTOMS_DEFAULT----------------
VACUUM CUSTOMS_DEFAULT_GPTMP_TODAY;
\echo ---------------CUSTOMS_ESEAL_CONFIG----------------
VACUUM CUSTOMS_ESEAL_CONFIG_GPTMP_TODAY;
\echo ---------------DCG_BAK_LIST----------------
VACUUM DCG_BAK_LIST_GPTMP_TODAY;
\echo ---------------DCG_BILL_HEAD----------------
VACUUM DCG_BILL_HEAD_GPTMP_TODAY;
\echo ---------------DCG_BILL_LIST----------------
VACUUM DCG_BILL_LIST_GPTMP_TODAY;
\echo ---------------DCG_COPR_INFO----------------
VACUUM DCG_COPR_INFO_GPTMP_TODAY;
\echo ---------------DCG_DEDUCT----------------
VACUUM DCG_DEDUCT_GPTMP_TODAY;
\echo ---------------DCG_DEDUCT_LOG----------------
VACUUM DCG_DEDUCT_LOG_GPTMP_TODAY;
\echo ---------------DCG_HEAD----------------
VACUUM DCG_HEAD_GPTMP_TODAY;
\echo ---------------DCG_LIST----------------
VACUUM DCG_LIST_GPTMP_TODAY;
\echo ---------------DCG_SEQ----------------
VACUUM DCG_SEQ_GPTMP_TODAY;
\echo ---------------DCG_WORKFLOW----------------
VACUUM DCG_WORKFLOW_GPTMP_TODAY;
\echo ---------------DECL_CO_ENTRY_COUNT----------------
VACUUM DECL_CO_ENTRY_COUNT_GPTMP_TODAY;
\echo ---------------DECL_CO_ENTRY_COUNT_TEMP----------------
VACUUM DECL_CO_ENTRY_COUNT_TEMP_GPTMP_TODAY;
\echo ---------------DECLAR_COUNTER_REL----------------
VACUUM DECLAR_COUNTER_REL_GPTMP_TODAY;
\echo ---------------DECLAR_REL----------------
VACUUM DECLAR_REL_GPTMP_TODAY;
\echo ---------------DECLARER_REL----------------
VACUUM DECLARER_REL_GPTMP_TODAY;
\echo ---------------DECLOG_FULL_REL----------------
VACUUM DECLOG_FULL_REL_GPTMP_TODAY;
\echo ---------------DECLOG_MOD_REL----------------
VACUUM DECLOG_MOD_REL_GPTMP_TODAY;
\echo ---------------DECLOG_MODIFY_REL----------------
VACUUM DECLOG_MODIFY_REL_GPTMP_TODAY;
\echo ---------------DECLOG_SCORE_HEAD----------------
VACUUM DECLOG_SCORE_HEAD_GPTMP_TODAY;
\echo ---------------DECLOG_SCORE_LIST----------------
VACUUM DECLOG_SCORE_LIST_GPTMP_TODAY;
\echo ---------------DEL_EGS_ARC_AGENT_LIST----------------
VACUUM DEL_EGS_ARC_AGENT_LIST_GPTMP_TODAY;
\echo ---------------DEL_EGS_ARC_HEAD----------------
VACUUM DEL_EGS_ARC_HEAD_GPTMP_TODAY;
\echo ---------------DEL_EGS_ARC_LIST----------------
VACUUM DEL_EGS_ARC_LIST_GPTMP_TODAY;
\echo ---------------DEL_EGS_ARC_MERCHANT_LIST----------------
VACUUM DEL_EGS_ARC_MERCHANT_LIST_GPTMP_TODAY;
\echo ---------------DEL_EGS_CLEAR_CERT----------------
VACUUM DEL_EGS_CLEAR_CERT_GPTMP_TODAY;
\echo ---------------DEL_EGS_CLEAR_HEAD----------------
VACUUM DEL_EGS_CLEAR_HEAD_GPTMP_TODAY;
\echo ---------------DEL_EGS_CLEAR_LIST----------------
VACUUM DEL_EGS_CLEAR_LIST_GPTMP_TODAY;
\echo ---------------DEL_EGS_DECLARE_CERT----------------
VACUUM DEL_EGS_DECLARE_CERT_GPTMP_TODAY;
\echo ---------------DEL_EGS_DECLARE_HEAD----------------
VACUUM DEL_EGS_DECLARE_HEAD_GPTMP_TODAY;
\echo ---------------DEL_EGS_DECLARE_LIST----------------
VACUUM DEL_EGS_DECLARE_LIST_GPTMP_TODAY;
\echo ---------------DEL_MOD_APPLY----------------
VACUUM DEL_MOD_APPLY_GPTMP_TODAY;
\echo ---------------DISTRIBUTIVE_BILL_DECLARE----------------
VACUUM DISTRIBUTIVE_BILL_DECLARE_GPTMP_TODAY;
\echo ---------------DISTRIBUTIVE_DECLARE----------------
VACUUM DISTRIBUTIVE_DECLARE_GPTMP_TODAY;
\echo ---------------DISTRIBUTIVE_TRANSIT_WAY----------------
VACUUM DISTRIBUTIVE_TRANSIT_WAY_GPTMP_TODAY;
\echo ---------------DST_COUNTER_TABLE----------------
VACUUM DST_COUNTER_TABLE_GPTMP_TODAY;
\echo ---------------DST_DEDUCT----------------
VACUUM DST_DEDUCT_GPTMP_TODAY;
\echo ---------------DST_EXG----------------
VACUUM DST_EXG_GPTMP_TODAY;
\echo ---------------DST_EXG_ORI_ENTRY----------------
VACUUM DST_EXG_ORI_ENTRY_GPTMP_TODAY;
\echo ---------------DST_HEAD----------------
VACUUM DST_HEAD_GPTMP_TODAY;
\echo ---------------DST_IMG----------------
VACUUM DST_IMG_GPTMP_TODAY;
\echo ---------------DST_IMG_ORI_ENTRY----------------
VACUUM DST_IMG_ORI_ENTRY_GPTMP_TODAY;
\echo ---------------DTT_COP_PARAM----------------
VACUUM DTT_COP_PARAM_GPTMP_TODAY;
\echo ---------------DUTY_CHECK_LOG----------------
VACUUM DUTY_CHECK_LOG_GPTMP_TODAY;
\echo ---------------DUTYFORM_HEAD----------------
VACUUM DUTYFORM_HEAD_GPTMP_TODAY;
\echo ---------------DUTYFORM_LIST----------------
VACUUM DUTYFORM_LIST_GPTMP_TODAY;
\echo ---------------ECO_HEAD----------------
VACUUM ECO_HEAD_GPTMP_TODAY;
\echo ---------------ECO_LIST----------------
VACUUM ECO_LIST_GPTMP_TODAY;
\echo ---------------ECO_PARTS----------------
VACUUM ECO_PARTS_GPTMP_TODAY;
\echo ---------------ECO_WORKFLOW----------------
VACUUM ECO_WORKFLOW_GPTMP_TODAY;
\echo ---------------EGS_ADMIT_HEAD----------------
VACUUM EGS_ADMIT_HEAD_GPTMP_TODAY;
\echo ---------------EGS_ADMIT_HS----------------
VACUUM EGS_ADMIT_HS_GPTMP_TODAY;
\echo ---------------EGS_ADMIT_LIST----------------
VACUUM EGS_ADMIT_LIST_GPTMP_TODAY;
\echo ---------------EGS_ARC_AGENT_LIST----------------
VACUUM EGS_ARC_AGENT_LIST_GPTMP_TODAY;
\echo ---------------EGS_ARC_HEAD----------------
VACUUM EGS_ARC_HEAD_GPTMP_TODAY;
\echo ---------------EGS_ARC_LIST----------------
VACUUM EGS_ARC_LIST_GPTMP_TODAY;
\echo ---------------EGS_ARC_MERCHANT_LIST----------------
VACUUM EGS_ARC_MERCHANT_LIST_GPTMP_TODAY;
\echo ---------------EGS_CHECK_LOG----------------
VACUUM EGS_CHECK_LOG_GPTMP_TODAY;
\echo ---------------EGS_CLEAR_CERT----------------
VACUUM EGS_CLEAR_CERT_GPTMP_TODAY;
\echo ---------------EGS_CLEAR_HEAD----------------
VACUUM EGS_CLEAR_HEAD_GPTMP_TODAY;
\echo ---------------EGS_CLEAR_LIST----------------
VACUUM EGS_CLEAR_LIST_GPTMP_TODAY;
\echo ---------------EGS_DECLARE_CERT----------------
VACUUM EGS_DECLARE_CERT_GPTMP_TODAY;
\echo ---------------EGS_DECLARE_HEAD----------------
VACUUM EGS_DECLARE_HEAD_GPTMP_TODAY;
\echo ---------------EGS_DECLARE_LIST----------------
VACUUM EGS_DECLARE_LIST_GPTMP_TODAY;
\echo ---------------EGS_DEDUCT----------------
VACUUM EGS_DEDUCT_GPTMP_TODAY;
\echo ---------------EGS_LEND_HEAD----------------
VACUUM EGS_LEND_HEAD_GPTMP_TODAY;
\echo ---------------EGS_LEND_LIST----------------
VACUUM EGS_LEND_LIST_GPTMP_TODAY;
\echo ---------------EGS_PATROL_HEAD----------------
VACUUM EGS_PATROL_HEAD_GPTMP_TODAY;
\echo ---------------EGS_PATROL_LIST----------------
VACUUM EGS_PATROL_LIST_GPTMP_TODAY;
\echo ---------------EGS_SEQ----------------
VACUUM EGS_SEQ_GPTMP_TODAY;
\echo ---------------EGS_WORKFLOW----------------
VACUUM EGS_WORKFLOW_GPTMP_TODAY;
\echo ---------------EMS_ACCOUNT----------------
VACUUM EMS_ACCOUNT_GPTMP_TODAY;
\echo ---------------EMS_APPR_HEAD----------------
VACUUM EMS_APPR_HEAD_GPTMP_TODAY;
\echo ---------------EMS_APPR_LIST----------------
VACUUM EMS_APPR_LIST_GPTMP_TODAY;
\echo ---------------EMS_CLAIM----------------
VACUUM EMS_CLAIM_GPTMP_TODAY;
\echo ---------------EMS_CLR_LIST----------------
VACUUM EMS_CLR_LIST_GPTMP_TODAY;
\echo ---------------EMS_CLR_TMP----------------
VACUUM EMS_CLR_TMP_GPTMP_TODAY;
\echo ---------------EMS_COMPLEX----------------
VACUUM EMS_COMPLEX_GPTMP_TODAY;
\echo ---------------EMS_COMPLEX2----------------
VACUUM EMS_COMPLEX2_GPTMP_TODAY;
\echo ---------------EMS_CONSUME----------------
VACUUM EMS_CONSUME_GPTMP_TODAY;
\echo ---------------EMS_CONSUME_CLR----------------
VACUUM EMS_CONSUME_CLR_GPTMP_TODAY;
\echo ---------------EMS_CONSUME_CLR_D----------------
VACUUM EMS_CONSUME_CLR_D_GPTMP_TODAY;
\echo ---------------EMS_DCR_CONSUME----------------
VACUUM EMS_DCR_CONSUME_GPTMP_TODAY;
\echo ---------------EMS_DCR_ENT----------------
VACUUM EMS_DCR_ENT_GPTMP_TODAY;
\echo ---------------EMS_DCR_HEAD----------------
VACUUM EMS_DCR_HEAD_GPTMP_TODAY;
\echo ---------------EMS_DCR_LIST----------------
VACUUM EMS_DCR_LIST_GPTMP_TODAY;
\echo ---------------EMS_DCR_RUB_LIST----------------
VACUUM EMS_DCR_RUB_LIST_GPTMP_TODAY;
\echo ---------------EMS_DEDUCT----------------
VACUUM EMS_DEDUCT_GPTMP_TODAY;
\echo ---------------EMS_DEDUCT_CLR----------------
VACUUM EMS_DEDUCT_CLR_GPTMP_TODAY;
\echo ---------------EMS_DEDUCT_LOG----------------
VACUUM EMS_DEDUCT_LOG_GPTMP_TODAY;
\echo ---------------EMS_ENP----------------
VACUUM EMS_ENP_GPTMP_TODAY;
\echo ---------------EMS_ENP_JOU----------------
VACUUM EMS_ENP_JOU_GPTMP_TODAY;
\echo ---------------EMS_HEAD----------------
VACUUM EMS_HEAD_GPTMP_TODAY;
\echo ---------------EMS_LIST----------------
VACUUM EMS_LIST_GPTMP_TODAY;
\echo ---------------EMS_MESSAGE_LOG----------------
VACUUM EMS_MESSAGE_LOG_GPTMP_TODAY;
\echo ---------------EMS_PRESS----------------
VACUUM EMS_PRESS_GPTMP_TODAY;
\echo ---------------EMS_PRESS_CLEAR----------------
VACUUM EMS_PRESS_CLEAR_GPTMP_TODAY;
\echo ---------------EMS_SEQ----------------
VACUUM EMS_SEQ_GPTMP_TODAY;
\echo ---------------EMS_TMP_CLR----------------
VACUUM EMS_TMP_CLR_GPTMP_TODAY;
\echo ---------------EMS_VAR----------------
VACUUM EMS_VAR_GPTMP_TODAY;
\echo ---------------EMS_VERIFY----------------
VACUUM EMS_VERIFY_GPTMP_TODAY;
\echo ---------------EMS_VERIFY_DETAIL----------------
VACUUM EMS_VERIFY_DETAIL_GPTMP_TODAY;
\echo ---------------EMS_WORKFLOW----------------
VACUUM EMS_WORKFLOW_GPTMP_TODAY;
\echo ---------------ENTRY_AUTOREL_ERR_LIST----------------
VACUUM ENTRY_AUTOREL_ERR_LIST_GPTMP_TODAY;
\echo ---------------ENTRY_AUTOREL_ERR_LOG----------------
VACUUM ENTRY_AUTOREL_ERR_LOG_GPTMP_TODAY;
\echo ---------------ENTRY_CENTRY_SELECT----------------
VACUUM ENTRY_CENTRY_SELECT_GPTMP_TODAY;
\echo ---------------ENTRY_CENTRY_SELECT_DEL----------------
VACUUM ENTRY_CENTRY_SELECT_DEL_GPTMP_TODAY;
\echo ---------------ENTRY_CERTIFICATE----------------
VACUUM ENTRY_CERTIFICATE_GPTMP_TODAY;
\echo ---------------ENTRY_CERTIFICATE_LOG----------------
VACUUM ENTRY_CERTIFICATE_LOG_GPTMP_TODAY;
\echo ---------------ENTRY_CONTAINER----------------
VACUUM ENTRY_CONTAINER_GPTMP_TODAY;
\echo ---------------ENTRY_CONTAINER_LOG----------------
VACUUM ENTRY_CONTAINER_LOG_GPTMP_TODAY;
\echo ---------------ENTRY_DEL_HEAD_LOG----------------
VACUUM ENTRY_DEL_HEAD_LOG_GPTMP_TODAY;
\echo ---------------ENTRY_DEL_LIST_LOG----------------
VACUUM ENTRY_DEL_LIST_LOG_GPTMP_TODAY;
\echo ---------------ENTRY_EVALUATION----------------
VACUUM ENTRY_EVALUATION_GPTMP_TODAY;
\echo ---------------ENTRY_GPM_RTX----------------
VACUUM ENTRY_GPM_RTX_GPTMP_TODAY;
\echo ---------------ENTRY_GPM_RTX_PRINTLOG----------------
VACUUM ENTRY_GPM_RTX_PRINTLOG_GPTMP_TODAY;
\echo ---------------ENTRY_GPM_RTX_SENDLOG----------------
VACUUM ENTRY_GPM_RTX_SENDLOG_GPTMP_TODAY;
\echo ---------------ENTRY_HEAD----------------
VACUUM ENTRY_HEAD_GPTMP_TODAY;
\echo ---------------ENTRY_LIST----------------
VACUUM ENTRY_LIST_GPTMP_TODAY;
\echo ---------------ENTRY_MODI_LOG----------------
VACUUM ENTRY_MODI_LOG_GPTMP_TODAY;
\echo ---------------ENTRY_OP_LOG----------------
VACUUM ENTRY_OP_LOG_GPTMP_TODAY;
\echo ---------------ENTRY_PROC----------------
VACUUM ENTRY_PROC_GPTMP_TODAY;
\echo ---------------ENTRY_PROC_LOG----------------
VACUUM ENTRY_PROC_LOG_GPTMP_TODAY;
\echo ---------------ENTRY_QUERY----------------
VACUUM ENTRY_QUERY_GPTMP_TODAY;
\echo ---------------ENTRY_WORKFLOW----------------
VACUUM ENTRY_WORKFLOW_GPTMP_TODAY;
\echo ---------------EPA_CHEM_CERT----------------
VACUUM EPA_CHEM_CERT_GPTMP_TODAY;
\echo ---------------EPA_CHK----------------
VACUUM EPA_CHK_GPTMP_TODAY;
\echo ---------------EPA_SCARP_CERT----------------
VACUUM EPA_SCARP_CERT_GPTMP_TODAY;
\echo ---------------ERR_LOG----------------
VACUUM ERR_LOG_GPTMP_TODAY;
\echo ---------------EX_APPL_CLOSE----------------
VACUUM EX_APPL_CLOSE_GPTMP_TODAY;
\echo ---------------EX_ARRIVAL_CONTA----------------
VACUUM EX_ARRIVAL_CONTA_GPTMP_TODAY;
\echo ---------------EX_ARRIVAL_ERR_CHK----------------
VACUUM EX_ARRIVAL_ERR_CHK_GPTMP_TODAY;
\echo ---------------EX_ARRIVAL_SHIP----------------
VACUUM EX_ARRIVAL_SHIP_GPTMP_TODAY;
\echo ---------------EX_CDL_MNL_DEDUCT----------------
VACUUM EX_CDL_MNL_DEDUCT_GPTMP_TODAY;
\echo ---------------EX_CONTA_ENTRY_CHK----------------
VACUUM EX_CONTA_ENTRY_CHK_GPTMP_TODAY;
\echo ---------------EX_CONTRACT_CLEAR----------------
VACUUM EX_CONTRACT_CLEAR_GPTMP_TODAY;
\echo ---------------EX_CONTRACT_DEDUC----------------
VACUUM EX_CONTRACT_DEDUC_GPTMP_TODAY;
\echo ---------------EX_CONTRACT_LIST----------------
VACUUM EX_CONTRACT_LIST_GPTMP_TODAY;
\echo ---------------EX_COP_RATE----------------
VACUUM EX_COP_RATE_GPTMP_TODAY;
\echo ---------------EX_DECL_ALARM_HEAD----------------
VACUUM EX_DECL_ALARM_HEAD_GPTMP_TODAY;
\echo ---------------EX_DECL_ALARM_LIST----------------
VACUUM EX_DECL_ALARM_LIST_GPTMP_TODAY;
\echo ---------------EX_DECL_CUR_HEAD----------------
VACUUM EX_DECL_CUR_HEAD_GPTMP_TODAY;
\echo ---------------EX_DECL_CUR_LIST----------------
VACUUM EX_DECL_CUR_LIST_GPTMP_TODAY;
\echo ---------------EX_DECL_HIS_HEAD----------------
VACUUM EX_DECL_HIS_HEAD_GPTMP_TODAY;
\echo ---------------EX_DECL_HIS_LIST----------------
VACUUM EX_DECL_HIS_LIST_GPTMP_TODAY;
\echo ---------------EX_ELE_HEAD----------------
VACUUM EX_ELE_HEAD_GPTMP_TODAY;
\echo ---------------EX_ELE_LIST----------------
VACUUM EX_ELE_LIST_GPTMP_TODAY;
\echo ---------------EX_EXAM_JOU----------------
VACUUM EX_EXAM_JOU_GPTMP_TODAY;
\echo ---------------EX_EXAM_MANA_HEAD----------------
VACUUM EX_EXAM_MANA_HEAD_GPTMP_TODAY;
\echo ---------------EX_EXAM_MANA_LIST----------------
VACUUM EX_EXAM_MANA_LIST_GPTMP_TODAY;
\echo ---------------EX_FASCICLE_LIST----------------
VACUUM EX_FASCICLE_LIST_GPTMP_TODAY;
\echo ---------------EX_LIC_CODE_TS----------------
VACUUM EX_LIC_CODE_TS_GPTMP_TODAY;
\echo ---------------EX_TRAN_JOU----------------
VACUUM EX_TRAN_JOU_GPTMP_TODAY;
\echo ---------------EX_TRANS_ALARM_CONTA_REL----------------
VACUUM EX_TRANS_ALARM_CONTA_REL_GPTMP_TODAY;
\echo ---------------EX_TRANS_ALARM_GOODS_CONTA_REL----------------
VACUUM EX_TRANS_ALARM_GOODS_CONTA_REL_GPTMP_TODAY;
\echo ---------------EX_TRANS_ALARM_LIST_REL----------------
VACUUM EX_TRANS_ALARM_LIST_REL_GPTMP_TODAY;
\echo ---------------EX_TRANS_CONTA_REL----------------
VACUUM EX_TRANS_CONTA_REL_GPTMP_TODAY;
\echo ---------------EX_TRANS_GOODS_CONTA_REL----------------
VACUUM EX_TRANS_GOODS_CONTA_REL_GPTMP_TODAY;
\echo ---------------EX_TRANS_HIS_CONTA_REL----------------
VACUUM EX_TRANS_HIS_CONTA_REL_GPTMP_TODAY;
\echo ---------------EX_TRANS_HIS_GOODS_CONTA_REL----------------
VACUUM EX_TRANS_HIS_GOODS_CONTA_REL_GPTMP_TODAY;
\echo ---------------EX_TRANS_HIS_LIST_REL----------------
VACUUM EX_TRANS_HIS_LIST_REL_GPTMP_TODAY;
\echo ---------------EX_TRANS_LIST_REL----------------
VACUUM EX_TRANS_LIST_REL_GPTMP_TODAY;
\echo ---------------EX_TRN_ARRIVAL_CONTA----------------
VACUUM EX_TRN_ARRIVAL_CONTA_GPTMP_TODAY;
\echo ---------------EX_TRN_CONTA_ENTRY_ARV----------------
VACUUM EX_TRN_CONTA_ENTRY_ARV_GPTMP_TODAY;
\echo ---------------EX_TRN_CONTA_ENTRY_CHK----------------
VACUUM EX_TRN_CONTA_ENTRY_CHK_GPTMP_TODAY;
\echo ---------------EXA_APPL_CLOSE----------------
VACUUM EXA_APPL_CLOSE_GPTMP_TODAY;
\echo ---------------EXAM_CONTA_END_LOG----------------
VACUUM EXAM_CONTA_END_LOG_GPTMP_TODAY;
\echo ---------------EXAM_CONTA_HEAD----------------
VACUUM EXAM_CONTA_HEAD_GPTMP_TODAY;
\echo ---------------EXAM_CONTA_LIST----------------
VACUUM EXAM_CONTA_LIST_GPTMP_TODAY;
\echo ---------------EXC_ELE----------------
VACUUM EXC_ELE_GPTMP_TODAY;
\echo ---------------EXC_EX_CHK----------------
VACUUM EXC_EX_CHK_GPTMP_TODAY;
\echo ---------------EXC_EXAM----------------
VACUUM EXC_EXAM_GPTMP_TODAY;
\echo ---------------EXP_MFT_CHK_RESULT----------------
VACUUM EXP_MFT_CHK_RESULT_GPTMP_TODAY;
\echo ---------------EXTERNAL_JOU----------------
VACUUM EXTERNAL_JOU_GPTMP_TODAY;
\echo ---------------FASCICLE_HEAD----------------
VACUUM FASCICLE_HEAD_GPTMP_TODAY;
\echo ---------------FCB_CHK----------------
VACUUM FCB_CHK_GPTMP_TODAY;
\echo ---------------FCB_CONTA----------------
VACUUM FCB_CONTA_GPTMP_TODAY;
\echo ---------------FCB_CONTA_MODI----------------
VACUUM FCB_CONTA_MODI_GPTMP_TODAY;
\echo ---------------FCB_HEAD----------------
VACUUM FCB_HEAD_GPTMP_TODAY;
\echo ---------------FCB_HEAD_MODI----------------
VACUUM FCB_HEAD_MODI_GPTMP_TODAY;
\echo ---------------FCB_LIST----------------
VACUUM FCB_LIST_GPTMP_TODAY;
\echo ---------------FCB_LIST_MODI----------------
VACUUM FCB_LIST_MODI_GPTMP_TODAY;
\echo ---------------FCB_RSK----------------
VACUUM FCB_RSK_GPTMP_TODAY;
\echo ---------------FCB_WORKFLOW----------------
VACUUM FCB_WORKFLOW_GPTMP_TODAY;
\echo ---------------FEE_INVOICE----------------
VACUUM FEE_INVOICE_GPTMP_TODAY;
\echo ---------------FORFEIT_FORM----------------
VACUUM FORFEIT_FORM_GPTMP_TODAY;
\echo ---------------FORM_CHK----------------
VACUUM FORM_CHK_GPTMP_TODAY;
\echo ---------------GUARANTEE_DEL_LOG----------------
VACUUM GUARANTEE_DEL_LOG_GPTMP_TODAY;
\echo ---------------GUARANTEE_LIST----------------
VACUUM GUARANTEE_LIST_GPTMP_TODAY;
\echo ---------------GUARANTEE_R----------------
VACUUM GUARANTEE_R_GPTMP_TODAY;
\echo ---------------H2000_SMS_SEND----------------
VACUUM H2000_SMS_SEND_GPTMP_TODAY;
\echo ---------------H2000_SMS_SENDLOG----------------
VACUUM H2000_SMS_SENDLOG_GPTMP_TODAY;
\echo ---------------HIS_TRN_COP_REL----------------
VACUUM HIS_TRN_COP_REL_GPTMP_TODAY;
\echo ---------------HIS_TRN_DR_REL----------------
VACUUM HIS_TRN_DR_REL_GPTMP_TODAY;
\echo ---------------HIS_TRN_ESEAL_REL----------------
VACUUM HIS_TRN_ESEAL_REL_GPTMP_TODAY;
\echo ---------------HIS_TRN_VE_REL----------------
VACUUM HIS_TRN_VE_REL_GPTMP_TODAY;
\echo ---------------IM_APPL_CLOSE----------------
VACUUM IM_APPL_CLOSE_GPTMP_TODAY;
\echo ---------------IM_CDL_MNL_DEDUCT----------------
VACUUM IM_CDL_MNL_DEDUCT_GPTMP_TODAY;
\echo ---------------IM_CONTRACT_CLEAR----------------
VACUUM IM_CONTRACT_CLEAR_GPTMP_TODAY;
\echo ---------------IM_CONTRACT_DEDUC----------------
VACUUM IM_CONTRACT_DEDUC_GPTMP_TODAY;
\echo ---------------IM_CONTRACT_LIST----------------
VACUUM IM_CONTRACT_LIST_GPTMP_TODAY;
\echo ---------------IM_COP_RATE----------------
VACUUM IM_COP_RATE_GPTMP_TODAY;
\echo ---------------IM_DECL_ALARM_HEAD----------------
VACUUM IM_DECL_ALARM_HEAD_GPTMP_TODAY;
\echo ---------------IM_DECL_ALARM_LIST----------------
VACUUM IM_DECL_ALARM_LIST_GPTMP_TODAY;
\echo ---------------IM_DECL_CUR_HEAD----------------
VACUUM IM_DECL_CUR_HEAD_GPTMP_TODAY;
\echo ---------------IM_DECL_CUR_LIST----------------
VACUUM IM_DECL_CUR_LIST_GPTMP_TODAY;
\echo ---------------IM_DECL_HIS_HEAD----------------
VACUUM IM_DECL_HIS_HEAD_GPTMP_TODAY;
\echo ---------------IM_DECL_HIS_LIST----------------
VACUUM IM_DECL_HIS_LIST_GPTMP_TODAY;
\echo ---------------IM_ELE_HEAD----------------
VACUUM IM_ELE_HEAD_GPTMP_TODAY;
\echo ---------------IM_ELE_LIST----------------
VACUUM IM_ELE_LIST_GPTMP_TODAY;
\echo ---------------IM_EXAM_JOU----------------
VACUUM IM_EXAM_JOU_GPTMP_TODAY;
\echo ---------------IM_EXAM_MANA_HEAD----------------
VACUUM IM_EXAM_MANA_HEAD_GPTMP_TODAY;
\echo ---------------IM_EXAM_MANA_LIST----------------
VACUUM IM_EXAM_MANA_LIST_GPTMP_TODAY;
\echo ---------------IM_FASCICLE_LIST----------------
VACUUM IM_FASCICLE_LIST_GPTMP_TODAY;
\echo ---------------IM_LIC_CODE_TS----------------
VACUUM IM_LIC_CODE_TS_GPTMP_TODAY;
\echo ---------------IM_TRAN_JOU----------------
VACUUM IM_TRAN_JOU_GPTMP_TODAY;
\echo ---------------IM_TRANS_ALARM_CONTA_REL----------------
VACUUM IM_TRANS_ALARM_CONTA_REL_GPTMP_TODAY;
\echo ---------------IM_TRANS_ALARM_GOODS_CONTA_REL----------------
VACUUM IM_TRANS_ALARM_GOODS_CONTA_REL_GPTMP_TODAY;
\echo ---------------IM_TRANS_ALARM_LIST_REL----------------
VACUUM IM_TRANS_ALARM_LIST_REL_GPTMP_TODAY;
\echo ---------------IM_TRANS_CONTA_REL----------------
VACUUM IM_TRANS_CONTA_REL_GPTMP_TODAY;
\echo ---------------IM_TRANS_GOODS_CONTA_REL----------------
VACUUM IM_TRANS_GOODS_CONTA_REL_GPTMP_TODAY;
\echo ---------------IM_TRANS_HIS_CONTA_REL----------------
VACUUM IM_TRANS_HIS_CONTA_REL_GPTMP_TODAY;
\echo ---------------IM_TRANS_HIS_GOODS_CONTA_REL----------------
VACUUM IM_TRANS_HIS_GOODS_CONTA_REL_GPTMP_TODAY;
\echo ---------------IM_TRANS_HIS_LIST_REL----------------
VACUUM IM_TRANS_HIS_LIST_REL_GPTMP_TODAY;
\echo ---------------IM_TRANS_LIST_REL----------------
VACUUM IM_TRANS_LIST_REL_GPTMP_TODAY;
\echo ---------------IMA_APPL_CLOSE----------------
VACUUM IMA_APPL_CLOSE_GPTMP_TODAY;
\echo ---------------INCOME_INFO----------------
VACUUM INCOME_INFO_GPTMP_TODAY;
\echo ---------------INVESTER_REL----------------
VACUUM INVESTER_REL_GPTMP_TODAY;
\echo ---------------INVLOG_REL----------------
VACUUM INVLOG_REL_GPTMP_TODAY;
\echo ---------------JOB_PARAMETER----------------
VACUUM JOB_PARAMETER_GPTMP_TODAY;
\echo ---------------LSP_CHK----------------
VACUUM LSP_CHK_GPTMP_TODAY;
\echo ---------------LSP_HEAD----------------
VACUUM LSP_HEAD_GPTMP_TODAY;
\echo ---------------LSP_LIST----------------
VACUUM LSP_LIST_GPTMP_TODAY;
\echo ---------------MAIL_FILE----------------
VACUUM MAIL_FILE_GPTMP_TODAY;
\echo ---------------MANA_REL----------------
VACUUM MANA_REL_GPTMP_TODAY;
\echo ---------------MANIFEST_CHK----------------
VACUUM MANIFEST_CHK_GPTMP_TODAY;
\echo ---------------MANIFEST_CHK_LOG----------------
VACUUM MANIFEST_CHK_LOG_GPTMP_TODAY;
\echo ---------------MANIFEST_CONTA----------------
VACUUM MANIFEST_CONTA_GPTMP_TODAY;
\echo ---------------MANIFEST_EXCH_LOG----------------
VACUUM MANIFEST_EXCH_LOG_GPTMP_TODAY;
\echo ---------------MANIFEST_EXCH_LOG_BAK----------------
VACUUM MANIFEST_EXCH_LOG_BAK_GPTMP_TODAY;
\echo ---------------MANIFEST_HEAD----------------
VACUUM MANIFEST_HEAD_GPTMP_TODAY;
\echo ---------------MANIFEST_HEAD_XMS_LOG----------------
VACUUM MANIFEST_HEAD_XMS_LOG_GPTMP_TODAY;
\echo ---------------MANIFEST_LIST----------------
VACUUM MANIFEST_LIST_GPTMP_TODAY;
\echo ---------------MANIFEST_LIST_CONTA----------------
VACUUM MANIFEST_LIST_CONTA_GPTMP_TODAY;
\echo ---------------MANIFEST_LIST_LOG----------------
VACUUM MANIFEST_LIST_LOG_GPTMP_TODAY;
\echo ---------------MANIFEST_LIST_RSKINFO_LOG----------------
VACUUM MANIFEST_LIST_RSKINFO_LOG_GPTMP_TODAY;
\echo ---------------MNL_PARA----------------
VACUUM MNL_PARA_GPTMP_TODAY;
\echo ---------------MNL_PRESS----------------
VACUUM MNL_PRESS_GPTMP_TODAY;
\echo ---------------MNL_RECEIVE_RECEIPT----------------
VACUUM MNL_RECEIVE_RECEIPT_GPTMP_TODAY;
\echo ---------------MNL_SEQ----------------
VACUUM MNL_SEQ_GPTMP_TODAY;
\echo ---------------MNLBAK_ACCOUNT----------------
VACUUM MNLBAK_ACCOUNT_GPTMP_TODAY;
\echo ---------------MNLBAK_APPL_CLOSE----------------
VACUUM MNLBAK_APPL_CLOSE_GPTMP_TODAY;
\echo ---------------MNLBAK_CLAIM----------------
VACUUM MNLBAK_CLAIM_GPTMP_TODAY;
\echo ---------------MNLBAK_CONSUME----------------
VACUUM MNLBAK_CONSUME_GPTMP_TODAY;
\echo ---------------MNLBAK_CONTRACT_HEAD----------------
VACUUM MNLBAK_CONTRACT_HEAD_GPTMP_TODAY;
\echo ---------------MNLBAK_CONTRACT_WORKFLOW----------------
VACUUM MNLBAK_CONTRACT_WORKFLOW_GPTMP_TODAY;
\echo ---------------MNLBAK_EX_CONTRACT_CLEAR----------------
VACUUM MNLBAK_EX_CONTRACT_CLEAR_GPTMP_TODAY;
\echo ---------------MNLBAK_EX_CONTRACT_DEDUC----------------
VACUUM MNLBAK_EX_CONTRACT_DEDUC_GPTMP_TODAY;
\echo ---------------MNLBAK_EX_CONTRACT_LIST----------------
VACUUM MNLBAK_EX_CONTRACT_LIST_GPTMP_TODAY;
\echo ---------------MNLBAK_EX_FASCICLE_LIST----------------
VACUUM MNLBAK_EX_FASCICLE_LIST_GPTMP_TODAY;
\echo ---------------MNLBAK_FASCICLE_HEAD----------------
VACUUM MNLBAK_FASCICLE_HEAD_GPTMP_TODAY;
\echo ---------------MNLBAK_FEE_INVOICE----------------
VACUUM MNLBAK_FEE_INVOICE_GPTMP_TODAY;
\echo ---------------MNLBAK_IM_CONTRACT_CLEAR----------------
VACUUM MNLBAK_IM_CONTRACT_CLEAR_GPTMP_TODAY;
\echo ---------------MNLBAK_IM_CONTRACT_DEDUC----------------
VACUUM MNLBAK_IM_CONTRACT_DEDUC_GPTMP_TODAY;
\echo ---------------MNLBAK_IM_CONTRACT_LIST----------------
VACUUM MNLBAK_IM_CONTRACT_LIST_GPTMP_TODAY;
\echo ---------------MNLBAK_IM_FASCICLE_LIST----------------
VACUUM MNLBAK_IM_FASCICLE_LIST_GPTMP_TODAY;
\echo ---------------MNLBAK_PRESS_CLEAR----------------
VACUUM MNLBAK_PRESS_CLEAR_GPTMP_TODAY;
\echo ---------------MNLBAK_SERVICE_FEE----------------
VACUUM MNLBAK_SERVICE_FEE_GPTMP_TODAY;
\echo ---------------MNLBAK_SERVICE_LIST----------------
VACUUM MNLBAK_SERVICE_LIST_GPTMP_TODAY;
\echo ---------------MOD_PROJECT_HEAD----------------
VACUUM MOD_PROJECT_HEAD_GPTMP_TODAY;
\echo ---------------MOD_PROJECT_LIST----------------
VACUUM MOD_PROJECT_LIST_GPTMP_TODAY;
\echo ---------------MOD_RED_HEAD----------------
VACUUM MOD_RED_HEAD_GPTMP_TODAY;
\echo ---------------MOD_RED_LIST----------------
VACUUM MOD_RED_LIST_GPTMP_TODAY;
\echo ---------------NONENTRY_CHK_RESULT----------------
VACUUM NONENTRY_CHK_RESULT_GPTMP_TODAY;
\echo ---------------NORSK_COMPANY----------------
VACUUM NORSK_COMPANY_GPTMP_TODAY;
\echo ---------------NORSK_COMPANY_BAK----------------
VACUUM NORSK_COMPANY_BAK_GPTMP_TODAY;
\echo ---------------NORSK_CONDITION----------------
VACUUM NORSK_CONDITION_GPTMP_TODAY;
\echo ---------------NORSK_CONDITION_BAK----------------
VACUUM NORSK_CONDITION_BAK_GPTMP_TODAY;
\echo ---------------NORSK_TRADE_MODE----------------
VACUUM NORSK_TRADE_MODE_GPTMP_TODAY;
\echo ---------------NORSK_TRADE_MODE_BAK----------------
VACUUM NORSK_TRADE_MODE_BAK_GPTMP_TODAY;
\echo ---------------OCC_ELE_HEAD----------------
VACUUM OCC_ELE_HEAD_GPTMP_TODAY;
\echo ---------------OCC_ELE_LIST----------------
VACUUM OCC_ELE_LIST_GPTMP_TODAY;
\echo ---------------OCC_EXAM----------------
VACUUM OCC_EXAM_GPTMP_TODAY;
\echo ---------------OCC_RECEIPT----------------
VACUUM OCC_RECEIPT_GPTMP_TODAY;
\echo ---------------OTHER_STF_RECORD----------------
VACUUM OTHER_STF_RECORD_GPTMP_TODAY;
\echo ---------------PAPERLESS_SELFSAVE_CERT----------------
VACUUM PAPERLESS_SELFSAVE_CERT_GPTMP_TODAY;
\echo ---------------PAYOUT_REMIT_HEAD----------------
VACUUM PAYOUT_REMIT_HEAD_GPTMP_TODAY;
\echo ---------------PAYOUT_REMIT_LIST----------------
VACUUM PAYOUT_REMIT_LIST_GPTMP_TODAY;
\echo ---------------PES_CANCEL----------------
VACUUM PES_CANCEL_GPTMP_TODAY;
\echo ---------------PES_NOTE----------------
VACUUM PES_NOTE_GPTMP_TODAY;
\echo ---------------PES_WORKFLOW----------------
VACUUM PES_WORKFLOW_GPTMP_TODAY;
\echo ---------------PORT_BIND_REL----------------
VACUUM PORT_BIND_REL_GPTMP_TODAY;
\echo ---------------PRE_APPL_CLOSE----------------
VACUUM PRE_APPL_CLOSE_GPTMP_TODAY;
\echo ---------------PRE_APPL_CLOSE_CONSUME----------------
VACUUM PRE_APPL_CLOSE_CONSUME_GPTMP_TODAY;
\echo ---------------PRE_CDL_COMMODITY----------------
VACUUM PRE_CDL_COMMODITY_GPTMP_TODAY;
\echo ---------------PRE_CDL_COMPANY----------------
VACUUM PRE_CDL_COMPANY_GPTMP_TODAY;
\echo ---------------PRE_COMPANY_REL----------------
VACUUM PRE_COMPANY_REL_GPTMP_TODAY;
\echo ---------------PRE_CONSUME----------------
VACUUM PRE_CONSUME_GPTMP_TODAY;
\echo ---------------PRE_CONTRACT_HEAD----------------
VACUUM PRE_CONTRACT_HEAD_GPTMP_TODAY;
\echo ---------------PRE_DECL_REL----------------
VACUUM PRE_DECL_REL_GPTMP_TODAY;
\echo ---------------PRE_EX_APPL_CLOSE----------------
VACUUM PRE_EX_APPL_CLOSE_GPTMP_TODAY;
\echo ---------------PRE_EX_CONTRACT_LIST----------------
VACUUM PRE_EX_CONTRACT_LIST_GPTMP_TODAY;
\echo ---------------PRE_EX_FASCICLE_LIST----------------
VACUUM PRE_EX_FASCICLE_LIST_GPTMP_TODAY;
\echo ---------------PRE_EXA_APPL_CLOSE----------------
VACUUM PRE_EXA_APPL_CLOSE_GPTMP_TODAY;
\echo ---------------PRE_FASCICLE_HEAD----------------
VACUUM PRE_FASCICLE_HEAD_GPTMP_TODAY;
\echo ---------------PRE_IM_APPL_CLOSE----------------
VACUUM PRE_IM_APPL_CLOSE_GPTMP_TODAY;
\echo ---------------PRE_IM_CONTRACT_LIST----------------
VACUUM PRE_IM_CONTRACT_LIST_GPTMP_TODAY;
\echo ---------------PRE_IM_FASCICLE_LIST----------------
VACUUM PRE_IM_FASCICLE_LIST_GPTMP_TODAY;
\echo ---------------PRE_IMA_APPL_CLOSE----------------
VACUUM PRE_IMA_APPL_CLOSE_GPTMP_TODAY;
\echo ---------------PRE_INVESTER_REL----------------
VACUUM PRE_INVESTER_REL_GPTMP_TODAY;
\echo ---------------PRE_MANA_REL----------------
VACUUM PRE_MANA_REL_GPTMP_TODAY;
\echo ---------------PRE_PROJECT_HEAD----------------
VACUUM PRE_PROJECT_HEAD_GPTMP_TODAY;
\echo ---------------PRE_PROJECT_LIST----------------
VACUUM PRE_PROJECT_LIST_GPTMP_TODAY;
\echo ---------------PRE_RED_HEAD----------------
VACUUM PRE_RED_HEAD_GPTMP_TODAY;
\echo ---------------PRE_RED_LIST----------------
VACUUM PRE_RED_LIST_GPTMP_TODAY;
\echo ---------------PRE_REL_ALC_WORK----------------
VACUUM PRE_REL_ALC_WORK_GPTMP_TODAY;
\echo ---------------PRESS_CLEAR----------------
VACUUM PRESS_CLEAR_GPTMP_TODAY;
\echo ---------------PRICE_LIBRARY----------------
VACUUM PRICE_LIBRARY_GPTMP_TODAY;
\echo ---------------PRICE_LIBRARY_ENTRY----------------
VACUUM PRICE_LIBRARY_ENTRY_GPTMP_TODAY;
\echo ---------------PRICE_LIBRARY_MAN----------------
VACUUM PRICE_LIBRARY_MAN_GPTMP_TODAY;
\echo ---------------PRICE_LIBRARY_RISK----------------
VACUUM PRICE_LIBRARY_RISK_GPTMP_TODAY;
\echo ---------------PROJECT_HEAD----------------
VACUUM PROJECT_HEAD_GPTMP_TODAY;
\echo ---------------PROJECT_LIST----------------
VACUUM PROJECT_LIST_GPTMP_TODAY;
\echo ---------------PROJECT_MAX_NO----------------
VACUUM PROJECT_MAX_NO_GPTMP_TODAY;
\echo ---------------PROJECT_MAX_NO_2007----------------
VACUUM PROJECT_MAX_NO_2007_GPTMP_TODAY;
\echo ---------------RAM_HEAD----------------
VACUUM RAM_HEAD_GPTMP_TODAY;
\echo ---------------RAM_LIST----------------
VACUUM RAM_LIST_GPTMP_TODAY;
\echo ---------------RAM_PRINT_LOG----------------
VACUUM RAM_PRINT_LOG_GPTMP_TODAY;
\echo ---------------RAM_RG_COP_OWNER----------------
VACUUM RAM_RG_COP_OWNER_GPTMP_TODAY;
\echo ---------------RAM_RG_COP_PROJECT----------------
VACUUM RAM_RG_COP_PROJECT_GPTMP_TODAY;
\echo ---------------RAM_RG_COPINFO----------------
VACUUM RAM_RG_COPINFO_GPTMP_TODAY;
\echo ---------------RAM_RG_HEAD----------------
VACUUM RAM_RG_HEAD_GPTMP_TODAY;
\echo ---------------RAM_RN_INFO----------------
VACUUM RAM_RN_INFO_GPTMP_TODAY;
\echo ---------------RAM_RY_COMMUNICATION----------------
VACUUM RAM_RY_COMMUNICATION_GPTMP_TODAY;
\echo ---------------RAM_STATUS----------------
VACUUM RAM_STATUS_GPTMP_TODAY;
\echo ---------------RAM_STATUS_LIST----------------
VACUUM RAM_STATUS_LIST_GPTMP_TODAY;
\echo ---------------RAM_STATUS_MODI_LOG----------------
VACUUM RAM_STATUS_MODI_LOG_GPTMP_TODAY;
\echo ---------------RCP_INCOME_HEAD----------------
VACUUM RCP_INCOME_HEAD_GPTMP_TODAY;
\echo ---------------RCP_INCOME_HEAD_BAK----------------
VACUUM RCP_INCOME_HEAD_BAK_GPTMP_TODAY;
\echo ---------------RCP_INCOME_LIST----------------
VACUUM RCP_INCOME_LIST_GPTMP_TODAY;
\echo ---------------RCP_INCOME_LIST_BAK----------------
VACUUM RCP_INCOME_LIST_BAK_GPTMP_TODAY;
\echo ---------------RCP_PAYMENT_HEAD----------------
VACUUM RCP_PAYMENT_HEAD_GPTMP_TODAY;
\echo ---------------RCP_PAYMENT_HEAD_BAK----------------
VACUUM RCP_PAYMENT_HEAD_BAK_GPTMP_TODAY;
\echo ---------------RCP_PAYMENT_LIST----------------
VACUUM RCP_PAYMENT_LIST_GPTMP_TODAY;
\echo ---------------RCP_PAYMENT_LIST_BAK----------------
VACUUM RCP_PAYMENT_LIST_BAK_GPTMP_TODAY;
\echo ---------------RCP_RECORD_HEAD----------------
VACUUM RCP_RECORD_HEAD_GPTMP_TODAY;
\echo ---------------RCP_RECORD_HEAD_BAK----------------
VACUUM RCP_RECORD_HEAD_BAK_GPTMP_TODAY;
\echo ---------------RCP_RECORD_LIST----------------
VACUUM RCP_RECORD_LIST_GPTMP_TODAY;
\echo ---------------RCP_RECORD_LIST_BAK----------------
VACUUM RCP_RECORD_LIST_BAK_GPTMP_TODAY;
\echo ---------------RCP_WORKFLOW----------------
VACUUM RCP_WORKFLOW_GPTMP_TODAY;
\echo ---------------RED_ENTRY_HEAD----------------
VACUUM RED_ENTRY_HEAD_GPTMP_TODAY;
\echo ---------------RED_ENTRY_LIST----------------
VACUUM RED_ENTRY_LIST_GPTMP_TODAY;
\echo ---------------RED_FEE_INVOICE----------------
VACUUM RED_FEE_INVOICE_GPTMP_TODAY;
\echo ---------------RED_HEAD----------------
VACUUM RED_HEAD_GPTMP_TODAY;
\echo ---------------RED_LIST----------------
VACUUM RED_LIST_GPTMP_TODAY;
\echo ---------------RED_MAX_NO----------------
VACUUM RED_MAX_NO_GPTMP_TODAY;
\echo ---------------RED_MAX_NO_2007----------------
VACUUM RED_MAX_NO_2007_GPTMP_TODAY;
\echo ---------------RED_RECEIVE_RECEIPT----------------
VACUUM RED_RECEIVE_RECEIPT_GPTMP_TODAY;
\echo ---------------RED_SERVICE_FEE----------------
VACUUM RED_SERVICE_FEE_GPTMP_TODAY;
\echo ---------------REL_ALC_WORK----------------
VACUUM REL_ALC_WORK_GPTMP_TODAY;
\echo ---------------RETURN_REL----------------
VACUUM RETURN_REL_GPTMP_TODAY;
\echo ---------------RISK_CONTROL----------------
VACUUM RISK_CONTROL_GPTMP_TODAY;
\echo ---------------RSK_ASSAY_APPLICATION----------------
VACUUM RSK_ASSAY_APPLICATION_GPTMP_TODAY;
\echo ---------------RSK_CASE_FEEDBACK_HEAD----------------
VACUUM RSK_CASE_FEEDBACK_HEAD_GPTMP_TODAY;
\echo ---------------RSK_CASE_FEEDBACK_LIST----------------
VACUUM RSK_CASE_FEEDBACK_LIST_GPTMP_TODAY;
\echo ---------------RSK_CASE_FEEDBACK_LIST_CERT----------------
VACUUM RSK_CASE_FEEDBACK_LIST_CERT_GPTMP_TODAY;
\echo ---------------RSK_CASE_TRANSFER_G_NO----------------
VACUUM RSK_CASE_TRANSFER_G_NO_GPTMP_TODAY;
\echo ---------------RSK_CASE_TRANSFER_HEAD----------------
VACUUM RSK_CASE_TRANSFER_HEAD_GPTMP_TODAY;
\echo ---------------RSK_CASE_TRANSFER_LIST----------------
VACUUM RSK_CASE_TRANSFER_LIST_GPTMP_TODAY;
\echo ---------------RSK_CODE_TS----------------
VACUUM RSK_CODE_TS_GPTMP_TODAY;
\echo ---------------RSK_CODE_TS_BAK----------------
VACUUM RSK_CODE_TS_BAK_GPTMP_TODAY;
\echo ---------------RSK_CONDITION----------------
VACUUM RSK_CONDITION_GPTMP_TODAY;
\echo ---------------RSK_CONDITION_BAK----------------
VACUUM RSK_CONDITION_BAK_GPTMP_TODAY;
\echo ---------------RSK_CONTA_CAPACITY----------------
VACUUM RSK_CONTA_CAPACITY_GPTMP_TODAY;
\echo ---------------RSK_CONTA_CAPACITY_BAK----------------
VACUUM RSK_CONTA_CAPACITY_BAK_GPTMP_TODAY;
\echo ---------------RSK_EXAM_HEAD_REL----------------
VACUUM RSK_EXAM_HEAD_REL_GPTMP_TODAY;
\echo ---------------RSK_EXAM_LIST_CONTAINER----------------
VACUUM RSK_EXAM_LIST_CONTAINER_GPTMP_TODAY;
\echo ---------------RSK_EXAM_LIST_REL----------------
VACUUM RSK_EXAM_LIST_REL_GPTMP_TODAY;
\echo ---------------RSK_EXAM_OP_LOG----------------
VACUUM RSK_EXAM_OP_LOG_GPTMP_TODAY;
\echo ---------------RSK_FAKE_CODE_TS----------------
VACUUM RSK_FAKE_CODE_TS_GPTMP_TODAY;
\echo ---------------RSK_FAKE_CODE_TS_BAK----------------
VACUUM RSK_FAKE_CODE_TS_BAK_GPTMP_TODAY;
\echo ---------------RSK_FIT_LOG_REL----------------
VACUUM RSK_FIT_LOG_REL_GPTMP_TODAY;
\echo ---------------RSK_FIT_RESULT_LOG----------------
VACUUM RSK_FIT_RESULT_LOG_GPTMP_TODAY;
\echo ---------------RSK_INSTR_ATTR_REL----------------
VACUUM RSK_INSTR_ATTR_REL_GPTMP_TODAY;
\echo ---------------RSK_INSTR_PROC_REL----------------
VACUUM RSK_INSTR_PROC_REL_GPTMP_TODAY;
\echo ---------------RSK_OP_LOG----------------
VACUUM RSK_OP_LOG_GPTMP_TODAY;
\echo ---------------RSK_RECHECK_REL----------------
VACUUM RSK_RECHECK_REL_GPTMP_TODAY;
\echo ---------------RSK_REPLICATION_LOG----------------
VACUUM RSK_REPLICATION_LOG_GPTMP_TODAY;
\echo ---------------RSK_RESULT_REL----------------
VACUUM RSK_RESULT_REL_GPTMP_TODAY;
\echo ---------------RSK_TRADE_CO----------------
VACUUM RSK_TRADE_CO_GPTMP_TODAY;
\echo ---------------RSK_TRADE_CO_BAK----------------
VACUUM RSK_TRADE_CO_BAK_GPTMP_TODAY;
\echo ---------------RSK_UNLOCK_OP_LOG----------------
VACUUM RSK_UNLOCK_OP_LOG_GPTMP_TODAY;
\echo ---------------RSK_VS_EXAM----------------
VACUUM RSK_VS_EXAM_GPTMP_TODAY;
\echo ---------------RSK_WORKFLOW----------------
VACUUM RSK_WORKFLOW_GPTMP_TODAY;
\echo ---------------SERVICE_FEE----------------
VACUUM SERVICE_FEE_GPTMP_TODAY;
\echo ---------------SERVICE_LIST----------------
VACUUM SERVICE_LIST_GPTMP_TODAY;
\echo ---------------SHIP_TONNAGE----------------
VACUUM SHIP_TONNAGE_GPTMP_TODAY;
\echo ---------------SPECIAL_ENTRY----------------
VACUUM SPECIAL_ENTRY_GPTMP_TODAY;
\echo ---------------STATUS_DETAIL----------------
VACUUM STATUS_DETAIL_GPTMP_TODAY;
\echo ---------------STATUS_DETAIL----------------
VACUUM STATUS_DETAIL_GPTMP_TODAY;
\echo ---------------STF_RECORD----------------
VACUUM STF_RECORD_GPTMP_TODAY;
\echo ---------------STL_DATA_CONTA_LIST----------------
VACUUM STL_DATA_CONTA_LIST_GPTMP_TODAY;
\echo ---------------STL_DATA_HEAD----------------
VACUUM STL_DATA_HEAD_GPTMP_TODAY;
\echo ---------------STL_DATA_TS_LIST----------------
VACUUM STL_DATA_TS_LIST_GPTMP_TODAY;
\echo ---------------STL_REQUEST_CHK----------------
VACUUM STL_REQUEST_CHK_GPTMP_TODAY;
\echo ---------------TAR_DEL_LOG----------------
VACUUM TAR_DEL_LOG_GPTMP_TODAY;
\echo ---------------TCS_COUNTER----------------
VACUUM TCS_COUNTER_GPTMP_TODAY;
\echo ---------------TCS_DETAIL_HEAD----------------
VACUUM TCS_DETAIL_HEAD_GPTMP_TODAY;
\echo ---------------TCS_DETAIL_LIST----------------
VACUUM TCS_DETAIL_LIST_GPTMP_TODAY;
\echo ---------------TCS_ERROR_LOG----------------
VACUUM TCS_ERROR_LOG_GPTMP_TODAY;
\echo ---------------TCS_SEND_LOG----------------
VACUUM TCS_SEND_LOG_GPTMP_TODAY;
\echo ---------------TCS_STATISTIC_REPORT----------------
VACUUM TCS_STATISTIC_REPORT_GPTMP_TODAY;
\echo ---------------TEMP_DB----------------
VACUUM TEMP_DB_GPTMP_TODAY;
\echo ---------------TEMP_DEL_EMS_CONSUME----------------
VACUUM TEMP_DEL_EMS_CONSUME_GPTMP_TODAY;
\echo ---------------TEMP_DEL_EMS_HEAD----------------
VACUUM TEMP_DEL_EMS_HEAD_GPTMP_TODAY;
\echo ---------------TEMP_PAGE_RANGE----------------
VACUUM TEMP_PAGE_RANGE_GPTMP_TODAY;
\echo ---------------TEP_COMPANY----------------
VACUUM TEP_COMPANY_GPTMP_TODAY;
\echo ---------------TEP_DEBIT_REC_REQUEST----------------
VACUUM TEP_DEBIT_REC_REQUEST_GPTMP_TODAY;
\echo ---------------TEP_DEBIT_REC_RESPONSE----------------
VACUUM TEP_DEBIT_REC_RESPONSE_GPTMP_TODAY;
\echo ---------------TEP_EPLAT_RESPONSE----------------
VACUUM TEP_EPLAT_RESPONSE_GPTMP_TODAY;
\echo ---------------TEP_ERR_LOG----------------
VACUUM TEP_ERR_LOG_GPTMP_TODAY;
\echo ---------------TEP_LOG----------------
VACUUM TEP_LOG_GPTMP_TODAY;
\echo ---------------TEP_PAY_LOG----------------
VACUUM TEP_PAY_LOG_GPTMP_TODAY;
\echo ---------------TEP_PAY_REC_REQUEST----------------
VACUUM TEP_PAY_REC_REQUEST_GPTMP_TODAY;
\echo ---------------TEP_PAY_REC_RESPONSE----------------
VACUUM TEP_PAY_REC_RESPONSE_GPTMP_TODAY;
\echo ---------------TEP_REC_LOG----------------
VACUUM TEP_REC_LOG_GPTMP_TODAY;
\echo ---------------TEP_SEQ----------------
VACUUM TEP_SEQ_GPTMP_TODAY;
\echo ---------------TEP_STATUS_QUERY----------------
VACUUM TEP_STATUS_QUERY_GPTMP_TODAY;
\echo ---------------TEP_VOUCHER_REC_LIST----------------
VACUUM TEP_VOUCHER_REC_LIST_GPTMP_TODAY;
\echo ---------------TEP_VOUCHER_REC_LIST_DETAIL----------------
VACUUM TEP_VOUCHER_REC_LIST_DETAIL_GPTMP_TODAY;
\echo ---------------TEP_VOUCHER_REC_PAGE_LIST----------------
VACUUM TEP_VOUCHER_REC_PAGE_LIST_GPTMP_TODAY;
\echo ---------------TMP_EMS_CONSUME----------------
VACUUM TMP_EMS_CONSUME_GPTMP_TODAY;
\echo ---------------TMP_EMS_DCR_ENT----------------
VACUUM TMP_EMS_DCR_ENT_GPTMP_TODAY;
\echo ---------------TMP_EMS_HEAD----------------
VACUUM TMP_EMS_HEAD_GPTMP_TODAY;
\echo ---------------TMP_EMS_LIST----------------
VACUUM TMP_EMS_LIST_GPTMP_TODAY;
\echo ---------------TRADE_ERR----------------
VACUUM TRADE_ERR_GPTMP_TODAY;
\echo ---------------TRADE_GPM_RTX----------------
VACUUM TRADE_GPM_RTX_GPTMP_TODAY;
\echo ---------------TRANSFER_FEE----------------
VACUUM TRANSFER_FEE_GPTMP_TODAY;
\echo ---------------TRANSFER_FEE_LOG----------------
VACUUM TRANSFER_FEE_LOG_GPTMP_TODAY;
\echo ---------------TRN_ALC_REL----------------
VACUUM TRN_ALC_REL_GPTMP_TODAY;
\echo ---------------TRN_CHECK----------------
VACUUM TRN_CHECK_GPTMP_TODAY;
\echo ---------------TRN_CHK_GOODS----------------
VACUUM TRN_CHK_GOODS_GPTMP_TODAY;
\echo ---------------TRN_COP_REL----------------
VACUUM TRN_COP_REL_GPTMP_TODAY;
\echo ---------------TRN_DELAY_FORM----------------
VACUUM TRN_DELAY_FORM_GPTMP_TODAY;
\echo ---------------TRN_DR_REL----------------
VACUUM TRN_DR_REL_GPTMP_TODAY;
\echo ---------------TRN_ESEAL_REL----------------
VACUUM TRN_ESEAL_REL_GPTMP_TODAY;
\echo ---------------TRN_EXAM_MAX_SEQ----------------
VACUUM TRN_EXAM_MAX_SEQ_GPTMP_TODAY;
\echo ---------------TRN_I_E_PORT----------------
VACUUM TRN_I_E_PORT_GPTMP_TODAY;
\echo ---------------TRN_PARAMETER----------------
VACUUM TRN_PARAMETER_GPTMP_TODAY;
\echo ---------------TRN_POP_COP_REL----------------
VACUUM TRN_POP_COP_REL_GPTMP_TODAY;
\echo ---------------TRN_POP_HEAD----------------
VACUUM TRN_POP_HEAD_GPTMP_TODAY;
\echo ---------------TRN_POP_LIST----------------
VACUUM TRN_POP_LIST_GPTMP_TODAY;
\echo ---------------TRN_PRE_MAX_SEQ----------------
VACUUM TRN_PRE_MAX_SEQ_GPTMP_TODAY;
\echo ---------------TRN_SHIP----------------
VACUUM TRN_SHIP_GPTMP_TODAY;
\echo ---------------TRN_VE_REL----------------
VACUUM TRN_VE_REL_GPTMP_TODAY;
\echo ---------------TRN_VEHICLE----------------
VACUUM TRN_VEHICLE_GPTMP_TODAY;
\echo ---------------YD_DECLARE_REL----------------
VACUUM YD_DECLARE_REL_GPTMP_TODAY;
