ACCOUNT:MANUAL_NO, ID_STAT
AGREEMENT_GOODS_LIST:ENTRY_ID, G_NO
AMS_MODI_LOG:EMS_NO, OP_TIME, MODI_TYPE, ITEM_NAME
AMSLIST_BODY:LIST_ID, G_NO
AMSLIST_HEAD:LIST_ID
APPL_CLOSE:MANUAL_NO
APPL_CLOSE_CONSUME:MANUAL_NO, CONTR_ITEM, EX_NO
APPLY_HEAD:APPL_NO
APPLY_LIST:APPL_NO, G_NO
ARRIVAL_INFO_HEAD:VOYAGE_NO, SHIP_ID, I_E_DATE, CUSTOMS_CODE, TRAF_MODE
ARRIVAL_INFO_LIST:BILL_NO, VOYAGE_NO, SHIP_ID, I_E_DATE, CUSTOMS_CODE, TRAF_MODE
BAK_BWS_EXAM_CERT_LIST:BWS_EXAM_NO, G_NO
BAK_BWS_EXAM_GOOD_LIST:BWS_EXAM_NO, G_NO
BAK_BWS_EXAM_HEAD:BWS_EXAM_NO
BAK_CONSUME:MANUAL_NO, CONTR_ITEM, EX_NO
BAK_CONTRACT_HEAD:MANUAL_NO
BAK_DCG_BILL_HEAD:BILL_NO
BAK_DCG_BILL_LIST:BILL_NO, G_TYPE, G_NO
BAK_DCG_DEDUCT:ENTRY_ID, DCG_NO, G_TYPE, ENTRY_G_NO
BAK_DCG_DEDUCT_LOG:ENTRY_ID, DCG_NO, CREATE_DATE, JOU_MARK
BAK_DCG_HEAD:DCG_NO
BAK_DCG_LIST:DCG_NO, G_TYPE, G_NO
BAK_EMS_APPR_HEAD:APPR_NO, RECEIVE_TIMES
BAK_EMS_APPR_LIST:APPR_NO, G_TYPE, G_NO, RECEIVE_TIMES
BAK_EMS_CONSUME:EMS_NO, EXG_NO, EXG_VERSION, IMG_NO, MODIFY_TIMES
BAK_EMS_DEDUCT_CLR:EMS_NO, IMG_NO, ENTRY_ID, ENTRY_G_NO
BAK_EMS_HEAD:EMS_NO, MODIFY_TIMES
BAK_EMS_LIST:EMS_NO, G_TYPE, G_NO, MODIFY_TIMES
BAK_EX_CONTRACT_LIST:MANUAL_NO, CONTR_ITEM
BAK_EX_FASCICLE_LIST:FASCICLE_NO, CONTR_ITEM
BAK_FASCICLE_HEAD:FASCICLE_NO
BAK_IM_CONTRACT_LIST:MANUAL_NO, CONTR_ITEM
BAK_IM_FASCICLE_LIST:FASCICLE_NO, CONTR_ITEM
BANK_ACCOUNT:MANUAL_NO, ID_STAT, RECEIVE_DATE
BCK_COP_HEAD:TRADE_CODE
BCK_COP_LIST:TRADE_CODE, RISK_NO, CUSTOMS_CODE
BCK_COP_LIST_TEMP:TRADE_CO, RISK_NO, CUSTOMS_CODE
BCK_COP_PARA_HEAD:RISK_NO, CUSTOMS_CODE
BCK_COP_PARA_LIST:RISK_NO, RISK_VALUE, CUSTOMS_CODE
BCK_EXECUTOR:BCK_NO, EXECUTOR
BCK_HANDOVER:HANDOVER_NO
BCK_HANDOVER_TYPE:HANDOVER_TYPE, ID
BCK_HEAD:BCK_NO
BCK_SEQ:BCK_KEY
BCK_STOCK_HEAD:SEQ_NO
BCK_STOCK_LIST:SEQ_NO, LIST_NO
BCK_WORKFLOW:BCK_NO, STEP_ID, OPER_ID, CREATE_DATE
BTI_DATA_CONTA_LIST:UCR_CODE, CONTAINER_ID
BTI_DATA_HEAD:UCR_CODE, CREATE_DATE
BTI_DATA_TS_LIST:UCR_CODE, G_NO
BWS_AUDIT_HEAD:AUDIT_NO
BWS_AUDIT_LIST:AUDIT_NO, G_NO
BWS_DCR_BILL_LIST:BWS_NO, DCR_TIMES, G_TYPE, G_NO
BWS_DCR_HEAD:BWS_NO, DCR_TIMES, DCR_TYPE
BWS_DCR_LIST:BWS_NO, DCR_TIMES, G_NO
BWS_DEDUCT:BWS_ID, ENTRY_G_NO
BWS_DEDUCT_LOG:BWS_ID, BWS_NO, CREATE_DATE, JOU_MARK
BWS_EXAM_CERT_LIST:BWS_EXAM_NO, G_NO
BWS_EXAM_GOOD_LIST:BWS_EXAM_NO, G_NO
BWS_EXAM_HEAD:BWS_EXAM_NO
BWS_EXAM_PASSCERT:CERT_NO
BWS_FORM_HEAD:FORM_ID
BWS_FORM_LIST:FORM_ID, G_NO
BWS_GB_LIST:BWS_NO, G_NO
BWS_HEAD:BWS_NO
BWS_LIST:BWS_NO, G_NO
BWS_MANIFEST_HEAD:BWS_MANIFEST_NO
BWS_MANIFEST_LIST:BWS_MANIFEST_NO, G_NO
BWS_SEQ:BWS_KEY
BWS_VAR:VAR_TYPE, VAR_ID, VAR_SUB_ID, CUSTOMS_CODE
BWS_WORKFLOW:BWS_ID, STEP_ID, CREATE_DATE
CCTS_ERROR_LOG:SEQUENCE_NO
CCTS_ONLINE_RESULT:SEQUENCE_NO
CCTS_ONLINE_RESULT_BAK:SEQUENCE_NO
CCTS_PERFORMANCE:SEQUENCE_NO
CCTS_RSK_RESULT:CCTS_CODE, CUSTOMS_CODE
CCTS_RSK_RESULT_BAK:CCTS_CODE, CUSTOMS_CODE, OP_BAK_TIME
CDL_CERTIFICATE:LIST_NO, DOCU_CODE, CERT_CODE
CDL_CHK:LIST_NO
CDL_COMMODITY:RECORDS_NO, G_NO
CDL_COMP_COMM_MODIFY_LOG:TRADE_CO, OP_TIME, MODI_TYPE, ITEM_NAME
CDL_COMP_COMM_OP_LOG:TRADE_CO, PROC_DATE, PROC_TYPE
CDL_COMPANY:TRADE_CO, CUSTOMS_CODE, TRADE_BONDED_FLAG
CDL_CONTAINER:LIST_NO, CONTAINER_ID
CDL_DEL_CERTIFICATE_LOG:LIST_NO, DOCU_CODE, CERT_CODE
CDL_DEL_CONTAINER_LOG:LIST_NO, CONTAINER_ID, CONTAINER_WT
CDL_DEL_HEAD_LOG:LIST_NO
CDL_DEL_LIST_LOG:LIST_NO, G_NO
CDL_EDI_MESS:MESS_CODE
CDL_EMS_DEDUCT:ENTRY_ID, EMS_NO, G_TYPE, ENTRY_G_NO
CDL_EMS_DEDUCT_LOG:ENTRY_ID, EMS_NO, CREATE_DATE, JOU_MARK
CDL_ENTRY_HEAD:PRE_ENTRY_ID
CDL_ENTRY_LIST:PRE_ENTRY_ID, ENTRY_G_NO, LIST_NO, LIST_G_NO
CDL_HEAD:LIST_NO
CDL_LICENSE_DEDUCT:LIST_NO, G_NO, TRADE_CO, OP_TIME
CDL_LIST:LIST_NO, G_NO
CDL_LOCK_COMMODITY:CODE_TS, CONTROL_COUNTRY, CUSTOMS_CODE, I_E_FLAG, TRADE_MODE
CDL_MODI_LOG:LIST_NO, OP_TIME, MODI_TYPE, ITEM_NAME
CDL_OP_LOG:LIST_NO, OP_TIME
CDL_OVERDUE_LIST:TRADE_CO, ENTRY_ID
CDL_STATUS_DETAIL:LIST_NO, DETAIL_COUNT
CDL_WORKFLOW:LIST_NO, STEP_ID, CREATE_DATE
CHK_COP_RATIO:CORP_CODE
CHK_COUNTER:CUSTOMS_CODE, I_E_FLAG, COUNTER_TYPE, COUNT_DATE
CHK_RATE_LIMIT:CUSTOMS_CODE, I_E_FLAG
CHKHS_MNLPROC:ORDER_NO, MANUAL_SCH
CIC_CODE:FIRST_NO
CIC_HEAD:CPT_NO
CIC_LIST:CPT_NO, ITEM_NO
CIC_MAXID:CUS_ID
CIC_SEND_REL:CPT_NO, SEND_TIMES
CLAIM:GUARANTEE_NO
CLC_CHKRATE_LIMIT:CUSTOMS_CODE, I_E_FLAG
CLC_GPR_RATIO:CUSTOMS_CODE, I_E_FLAG
CLC_GPR_RATIO_BAK:CUSTOMS_CODE, I_E_FLAG, OP_TIME
CNS_COUNTER_TABLE:CUSTOMS_CODE
CO_CLASS_REL:TRADE_CO, CLASS_NO
COMPANY_REL:TRADE_CO
CONSUME:MANUAL_NO, CONTR_ITEM, EX_NO
CONSUME_DB:EX_CODE_TS, EX_NO, IM_CODE_TS, IM_NO
CONSUME_GOODS:CODE_TS, G_NO, G_FLAG
CONTA:FORM_ID, CONTA_ID
CONTA_MONITOR:I_E_FLAG, CONTA_ID, DISTRIBUTIVE_NO, IN_OUT_FLAG
CONTRACT_HEAD:MANUAL_NO
CONTRACT_WORKFLOW:MANUAL_NO, STEP_ID, PROC_DATE
CONVEYANCE:SHIP_ID, TRAF_MODE
CONVEYANCE_SEGMENT:SHIP_ID, TRAF_MODE, VOYAGE_NO, I_E_FLAG, LOAD_PORT, DESTINATION_PORT, CUSTOMS_CODE, I_E_DATE
COP_CONSUME:REC_NUM
COP_SPEC_REL:ENTRY_ID, AUTH_ID
COPLOG_DELETE_REL:LOG_ID
COPLOG_MODIFY_REL:LOG_ID
CORP_HEAD:FORM_ID
CORP_LIST:FORM_ID, FIELD_ID
CORP_TABLE:FIELD_ID, TABLE_ID
CORP_TYPE:CORP_TYPE
COUNTER_TABLE:COUNTER_TYPE, CUSTOMS_CODE, I_E_FLAG, C_DATE
CREDIT_INFO:RPTNO
CTS_CHKRATE_LIMIT:ID
CTS_CHKRATE_LIMIT_BAK:ID, OP_BAK_TIME
CTS_PERIOD:CUSTOMS_CODE
CUS_GOOD_CONSUME:REC_NUM
CUSTOMS_DEFAULT:MASTER_CUSTOMS
CUSTOMS_ESEAL_CONFIG:CUSTOMS_CODE, FLAG_TYPE, I_E_FLAG
DCG_BAK_LIST:DCG_NO
DCG_BILL_HEAD:BILL_NO
DCG_BILL_LIST:BILL_NO, G_TYPE, G_NO
DCG_COPR_INFO:CORP_NO
DCG_DEDUCT:ENTRY_ID, DCG_NO, G_TYPE, ENTRY_G_NO
DCG_DEDUCT_LOG:ENTRY_ID, DCG_NO, CREATE_DATE, JOU_MARK
DCG_HEAD:DCG_NO
DCG_LIST:DCG_NO, G_TYPE, G_NO
DCG_SEQ:DCG_KEY
DCG_WORKFLOW:DCG_NO, STEP_ID, CREATE_DATE
DECL_CO_ENTRY_COUNT:DECL_CO, RANDOM
DECL_CO_ENTRY_COUNT_TEMP:GEN_DATE, DECL_CO, RANDOM
DECLAR_COUNTER_REL:DECL_KEY
DECLAR_REL:DECL_CO, CUSTOMS_CODE
DECLARER_REL:DECL_CO
DECLOG_FULL_REL:LOG_ID
DECLOG_MOD_REL:DECL_CO, MOD_TIMES
DECLOG_MODIFY_REL:LOG_ID
DECLOG_SCORE_HEAD:DECL_CO, FORM_ID, SCORE_TIME
DECLOG_SCORE_LIST:DECL_CO, FORM_ID, SCORE_TIME, ITEM_NO
DEL_EGS_ARC_AGENT_LIST:EGS_NO, AGENT_NO
DEL_EGS_ARC_HEAD:EGS_NO
DEL_EGS_ARC_LIST:EGS_NO, G_NO
DEL_EGS_ARC_MERCHANT_LIST:EGS_NO, AGENT_CODE, MERCHANT_NO
DEL_EGS_CLEAR_CERT:CLR_NO, CERT_CODE, CERT_NO
DEL_EGS_CLEAR_HEAD:CLR_NO
DEL_EGS_CLEAR_LIST:CLR_NO, G_NO
DEL_EGS_DECLARE_CERT:DECL_NO, CERT_CODE, CERT_NO
DEL_EGS_DECLARE_HEAD:DECL_NO
DEL_EGS_DECLARE_LIST:DECL_NO, G_NO
DEL_MOD_APPLY:ENTRY_ID, APPLY_TIME
DISTRIBUTIVE_BILL_DECLARE:DISTRIBUTIVE_NO, I_E_FLAG, CUSTOMS_CODE, TRAF_MODE, VOYAGE_NO, BILL_NO, SHIP_ID, I_E_DATE
DISTRIBUTIVE_DECLARE:DISTRIBUTIVE_NO
DISTRIBUTIVE_TRANSIT_WAY:DISTRIBUTIVE_NO, CONTA_ID
DST_COUNTER_TABLE:EMS_NO, COUNTER, SUB_COUNTER
DST_DEDUCT:PRE_NO, G_NO, ORIGIN_COUNTRY, ENTRY_ID, ENTRY_G_NO
DST_EXG:PRE_NO, G_NO, ORIGIN_COUNTRY
DST_EXG_ORI_ENTRY:PRE_NO, G_NO, ORIGIN_COUNTRY, ENTRY_ID, ENTRY_G_NO
DST_HEAD:PRE_NO
DST_IMG:PRE_NO, G_NO, ORIGIN_COUNTRY
DST_IMG_ORI_ENTRY:PRE_NO, G_NO, ORIGIN_COUNTRY, ENTRY_ID, ENTRY_G_NO
DTT_COP_PARAM:CORP_CODE, CUSTOMS_CODE
DUTY_CHECK_LOG:ENTRY_ID, TAX_ID, PROC_TIME
DUTYFORM_HEAD:ENTRY_ID
DUTYFORM_LIST:ENTRY_ID, TAX_ID
ECO_HEAD:CERTIFICATE_NO
ECO_LIST:CERTIFICATE_NO, G_NO
ECO_PARTS:CERTIFICATE_NO, G_NO, PART_SEQ
ECO_WORKFLOW:CERTIFICATE_NO, TRANSFER_NUM, PROCESS_STATUS, PROCESS_DATE
EGS_ADMIT_HEAD:ADM_NO
EGS_ADMIT_HS:ADM_NO, CODE_TS
EGS_ADMIT_LIST:ADM_NO, G_NO
EGS_ARC_AGENT_LIST:EGS_NO, AGENT_NO
EGS_ARC_HEAD:EGS_NO
EGS_ARC_LIST:EGS_NO, G_NO
EGS_ARC_MERCHANT_LIST:EGS_NO, AGENT_CODE, MERCHANT_NO
EGS_CHECK_LOG:EGS_NO, CHK_TIMES, FORM_TYPE, G_NO
EGS_CLEAR_CERT:CLR_NO, CERT_CODE, CERT_NO
EGS_CLEAR_HEAD:CLR_NO
EGS_CLEAR_LIST:CLR_NO, G_NO
EGS_DECLARE_CERT:DECL_NO, CERT_CODE, CERT_NO
EGS_DECLARE_HEAD:DECL_NO
EGS_DECLARE_LIST:DECL_NO, G_NO
EGS_DEDUCT:DECL_NO, DECL_G_NO, CLR_NO, CLR_G_NO
EGS_LEND_HEAD:LEND_NO
EGS_LEND_LIST:LEND_NO, G_NO
EGS_PATROL_HEAD:PAT_NO
EGS_PATROL_LIST:PAT_NO, G_NO
EGS_SEQ:EGS_KEY
EGS_WORKFLOW:EGS_NO, STEP_ID, CREATE_DATE
EMS_ACCOUNT:EMS_NO, ID_STAT
EMS_APPR_HEAD:APPR_NO, RECEIVE_TIMES
EMS_APPR_LIST:APPR_NO, G_TYPE, G_NO, RECEIVE_TIMES
EMS_CLAIM:GUARANTEE_NO
EMS_CLR_LIST:EMS_NO, DCR_TIMES, G_TYPE, G_NO, DU_CODE
EMS_CLR_TMP:EMS_NO, G_TYPE, G_NO
EMS_COMPLEX:GOODS_TYPE, G_TYPE, CODE_TS, CLASSIFY
EMS_COMPLEX2:ICODE_TS, ECODE_TS
EMS_CONSUME:EMS_NO, EXG_NO, EXG_VERSION, IMG_NO
EMS_CONSUME_CLR:EMS_NO, IMG_NO
EMS_CONSUME_CLR_D:EMS_NO, IMG_NO, EXG_NO, EXG_VERSION
EMS_DCR_CONSUME:EMS_NO, EXG_NO, EXG_VERSION, IMG_NO, MODIFY_TIMES
EMS_DCR_ENT:EMS_NO, DCR_TIMES, ENTRY_ID
EMS_DCR_HEAD:EMS_NO, DCR_TIMES
EMS_DCR_LIST:EMS_NO, DCR_TIMES, G_TYPE, G_NO
EMS_DCR_RUB_LIST:EMS_NO, DCR_TIMES, G_TYPE, G_NO
EMS_DEDUCT:ENTRY_ID, EMS_NO, G_TYPE, ENTRY_G_NO
EMS_DEDUCT_CLR:EMS_NO, IMG_NO, ENTRY_ID, ENTRY_G_NO
EMS_DEDUCT_LOG:ENTRY_ID, EMS_NO, CREATE_DATE, JOU_MARK
EMS_ENP:ENP_ID
EMS_ENP_JOU:ENP_ID, ENP_SEQ, ENP_NO
EMS_HEAD:EMS_NO
EMS_LIST:EMS_NO, G_TYPE, G_NO
EMS_MESSAGE_LOG:EMS_NO, SEND_CUSTOMS, CUSTOMS_CODE, H2000_RECEIVE_DATE
EMS_PRESS:PARA_TYPE, PARA_NAME
EMS_PRESS_CLEAR:EMS_NO, PR_NO
EMS_SEQ:EMS_KEY
EMS_TMP_CLR:EMS_NO, G_TYPE, G_NO
EMS_VAR:VAR_TYPE, VAR_ID, VAR_SUB_ID, CUSTOMS_CODE
EMS_VERIFY:EMS_NO, G_TYPE, G_NO
EMS_VERIFY_DETAIL:EMS_NO, G_TYPE, G_NO, D_TYPE, E_TYPE
EMS_WORKFLOW:EMS_NO, STEP_ID, CREATE_DATE
ENTRY_AUTOREL_ERR_LIST:ENTRY_ID
ENTRY_AUTOREL_ERR_LOG:ENTRY_ID, DEL_TIME
ENTRY_CENTRY_SELECT:ENTRY_ID
ENTRY_CENTRY_SELECT_DEL:ENTRY_ID, OP_TIME
ENTRY_CERTIFICATE:ENTRY_ID, DOCU_CODE, CERT_CODE
ENTRY_CERTIFICATE_LOG:ENTRY_ID, DOCU_CODE, CERT_CODE, OP_TIME
ENTRY_CONTAINER:ENTRY_ID, CONTAINER_ID
ENTRY_CONTAINER_LOG:ENTRY_ID, CONTAINER_ID, OP_TIME
ENTRY_DEL_HEAD_LOG:ENTRY_ID, OP_TIME
ENTRY_DEL_LIST_LOG:ENTRY_ID, G_NO, OP_TIME
ENTRY_EVALUATION:ENTRY_ID, G_NO
ENTRY_GPM_RTX:SIGN_TYPE, ENTRY_ID, PROC_MODE
ENTRY_GPM_RTX_PRINTLOG:ENTRY_ID, PRINT_TYPE, PRINT_DATE
ENTRY_GPM_RTX_SENDLOG:ENTRY_ID, SIGN_TYPE, PROC_MODE, SEND_DATE
ENTRY_HEAD:ENTRY_ID, DECL_PORT
ENTRY_LIST:ENTRY_ID, G_NO
ENTRY_MODI_LOG:ENTRY_ID, OP_TIME, MODI_TYPE, ITEM_NAME
ENTRY_OP_LOG:ENTRY_ID, OP_TIME
ENTRY_PROC:ENTRY_ID, DECL_PORT
ENTRY_PROC_LOG:ENTRY_ID, OP_TIME, OP_STEP
ENTRY_QUERY:ENTRY_ID, G_NO
ENTRY_WORKFLOW:ENTRY_ID, STEP_ID, CREATE_DATE
EPA_CHEM_CERT:CERTIFICATE_NO
EPA_CHK:ENTRY_ID, CERTIFICATE_NO, CERT_TYPE
EPA_SCARP_CERT:CERTIFICATE_NO
ERR_LOG:ENTRY_ID, CREATE_DATE
EX_APPL_CLOSE:MANUAL_NO, CONTR_ITEM
EX_ARRIVAL_CONTA:CONTA_ID, BILL_NO, REC_NO
EX_ARRIVAL_ERR_CHK:ENTRY_ID, CHK_DATE
EX_ARRIVAL_SHIP:VOYAGE_NO, SHIP_NAME_EN, CUSTOMS_CODE, SHIP_ID
EX_CDL_MNL_DEDUCT:MANUAL_NO, ENTRY_ID, G_NO
EX_CONTA_ENTRY_CHK:CONTA_ID, BILL_NO, REC_NO, ENTRY_ID
EX_CONTRACT_CLEAR:MANUAL_NO, CONTR_ITEM
EX_CONTRACT_DEDUC:MANUAL_NO, ENTRY_ID, G_NO
EX_CONTRACT_LIST:MANUAL_NO, CONTR_ITEM
EX_COP_RATE:TRADE_CO, CHKSTDATE, CHKENDDATE
EX_DECL_ALARM_HEAD:PRE_NO
EX_DECL_ALARM_LIST:PRE_NO, RECORD_NUMBER, G_NO
EX_DECL_CUR_HEAD:PRE_NO
EX_DECL_CUR_LIST:PRE_NO, RECORD_NUMBER, G_NO
EX_DECL_HIS_HEAD:PRE_NO
EX_DECL_HIS_LIST:PRE_NO, RECORD_NUMBER, G_NO
EX_ELE_HEAD:LICENSE_NO
EX_ELE_LIST:LICENSE_NO, L_G_NO
EX_EXAM_JOU:ENTRY_ID, G_NO
EX_EXAM_MANA_HEAD:LICENSE_NO
EX_EXAM_MANA_LIST:LICENSE_NO, L_G_NO
EX_FASCICLE_LIST:FASCICLE_NO, CONTR_ITEM
EX_LIC_CODE_TS:LICENSE_NO
EX_TRAN_JOU:ENTRY_ID, G_NO
EX_TRANS_ALARM_CONTA_REL:PRE_NO, RECORD_NUMBER, CONTA_NO
EX_TRANS_ALARM_GOODS_CONTA_REL:PRE_NO, RECORD_NUMBER, G_NO, CONTA_NO
EX_TRANS_ALARM_LIST_REL:PRE_NO, RECORD_NUMBER
EX_TRANS_CONTA_REL:PRE_NO, RECORD_NUMBER, CONTA_NO
EX_TRANS_GOODS_CONTA_REL:PRE_NO, RECORD_NUMBER, G_NO, CONTA_NO
EX_TRANS_HIS_CONTA_REL:PRE_NO, RECORD_NUMBER, CONTA_NO
EX_TRANS_HIS_GOODS_CONTA_REL:PRE_NO, RECORD_NUMBER, G_NO, CONTA_NO
EX_TRANS_HIS_LIST_REL:PRE_NO, RECORD_NUMBER
EX_TRANS_LIST_REL:PRE_NO, RECORD_NUMBER
EX_TRN_ARRIVAL_CONTA:ARRIVE_NO, CONTA_ID
EX_TRN_CONTA_ENTRY_ARV:ENTRY_ID, CONTA_ID
EX_TRN_CONTA_ENTRY_CHK:ENTRY_ID, ARRIVE_NO, CONTA_ID
EXA_APPL_CLOSE:MANUAL_NO, CONTR_ITEM
EXAM_CONTA_END_LOG:EXAM_REC_ID, END_TIME
EXAM_CONTA_HEAD:EXAM_REC_ID
EXAM_CONTA_LIST:EXAM_REC_ID, CONTA_ID
EXC_ELE:HXD_NO
EXC_EX_CHK:HXD_NO
EXC_EXAM:HXD_NO
EXP_MFT_CHK_RESULT:VOYAGE_NO, CUSTOMS_CODE
EXTERNAL_JOU:MANUAL_NO, CUSTOMS_CODE, APPL_NO
FASCICLE_HEAD:FASCICLE_NO
FCB_CHK:FCB_ID, FORM_FLAG, ENTRY_ID
FCB_CONTA:FCB_ID, CONTA_ID
FCB_CONTA_MODI:FCB_ID, CONTA_ID
FCB_HEAD:FCB_ID
FCB_HEAD_MODI:FCB_ID
FCB_LIST:FCB_ID, G_NO
FCB_LIST_MODI:FCB_ID, G_NO
FCB_RSK:FCB_ID, CUSTOMS_CODE
FCB_WORKFLOW:FCB_ID, STEP_ID, CREATE_DATE
FEE_INVOICE:MANUAL_NO, F_NO
FORFEIT_FORM:FMS_ID
FORM_CHK:FORM_ID
GUARANTEE_DEL_LOG:GUA_ID, DEL_DATETIME
GUARANTEE_LIST:ENTRY_ID, G_NO, TAX_TYPE
GUARANTEE_R:GUA_ID
H2000_SMS_SEND:SEQUENCE_NO, FORM_ID, SYSTEM_ID, POS_ID, OP_TIME, PHONE_NO
H2000_SMS_SENDLOG:SEQUENCE_NO, FORM_ID, SYSTEM_ID, POS_ID, OP_TIME, PHONE_NO
HIS_TRN_COP_REL:CO_REG_NO, MODI_COUNT
HIS_TRN_DR_REL:DR_CUSTOMS_NO, MODI_COUNT
HIS_TRN_ESEAL_REL:ESEAL_ID, MODI_TIME
HIS_TRN_VE_REL:VE_CUSTOMS_NO, MODI_COUNT
IM_APPL_CLOSE:MANUAL_NO, CONTR_ITEM
IM_CDL_MNL_DEDUCT:MANUAL_NO, ENTRY_ID, G_NO
IM_CONTRACT_CLEAR:MANUAL_NO, CONTR_ITEM
IM_CONTRACT_DEDUC:MANUAL_NO, ENTRY_ID, G_NO
IM_CONTRACT_LIST:MANUAL_NO, CONTR_ITEM
IM_COP_RATE:TRADE_CO, CHKSTDATE, CHKENDDATE
IM_DECL_ALARM_HEAD:PRE_NO
IM_DECL_ALARM_LIST:PRE_NO, RECORD_NUMBER, G_NO
IM_DECL_CUR_HEAD:PRE_NO
IM_DECL_CUR_LIST:PRE_NO, RECORD_NUMBER, G_NO
IM_DECL_HIS_HEAD:PRE_NO
IM_DECL_HIS_LIST:PRE_NO, RECORD_NUMBER, G_NO
IM_ELE_HEAD:LICENSE_NO
IM_ELE_LIST:LICENSE_NO, L_G_NO
IM_EXAM_JOU:ENTRY_ID, G_NO
IM_EXAM_MANA_HEAD:LICENSE_NO
IM_EXAM_MANA_LIST:LICENSE_NO, L_G_NO
IM_FASCICLE_LIST:FASCICLE_NO, CONTR_ITEM
IM_LIC_CODE_TS:LICENSE_NO
IM_TRAN_JOU:ENTRY_ID, G_NO
IM_TRANS_ALARM_CONTA_REL:PRE_NO, RECORD_NUMBER, CONTA_NO
IM_TRANS_ALARM_GOODS_CONTA_REL:PRE_NO, RECORD_NUMBER, G_NO, CONTA_NO
IM_TRANS_ALARM_LIST_REL:PRE_NO, RECORD_NUMBER
IM_TRANS_CONTA_REL:PRE_NO, RECORD_NUMBER, CONTA_NO
IM_TRANS_GOODS_CONTA_REL:PRE_NO, RECORD_NUMBER, G_NO, CONTA_NO
IM_TRANS_HIS_CONTA_REL:PRE_NO, RECORD_NUMBER, CONTA_NO
IM_TRANS_HIS_GOODS_CONTA_REL:PRE_NO, RECORD_NUMBER, G_NO, CONTA_NO
IM_TRANS_HIS_LIST_REL:PRE_NO, RECORD_NUMBER
IM_TRANS_LIST_REL:PRE_NO, RECORD_NUMBER
IMA_APPL_CLOSE:MANUAL_NO, CONTR_ITEM
INCOME_INFO:RPTNO
INVESTER_REL:TRADE_CO, INV_NO
INVLOG_REL:LOG_ID
JOB_PARAMETER:JOB_NAME, PARAMETER_NAME, PARAMETER_VALUE
LSP_CHK:LSP_ID, LSP_TYPE, I_E_FLAG, ENTRY_ID, G_NO
LSP_HEAD:LSP_ID, LSP_TYPE, I_E_FLAG
LSP_LIST:LSP_ID, LSP_TYPE, I_E_FLAG, G_NO
MAIL_FILE:NO
MANA_REL:TRADE_CO, MANAG_NO
MANIFEST_CHK:BILL_NO, SHIP_ID, VOYAGE_NO, CUSTOMS_CODE, TRAF_MODE, I_E_FLAG, FORM_ID
MANIFEST_CHK_LOG:FORM_ID, CREATE_DATE, BILL_NO
MANIFEST_CONTA:VOYAGE_NO, TRAF_MODE, I_E_FLAG, BILL_NO, CONTA_ID, SHIP_ID
MANIFEST_EXCH_LOG:CUSTOMS_CODE, SHIP_ID, VOYAGE_NO, BILL_NO, I_E_DATE
MANIFEST_EXCH_LOG_BAK:CUSTOMS_CODE, SHIP_ID, VOYAGE_NO, BILL_NO, I_E_DATE, CREATE_DATE
MANIFEST_HEAD:I_E_FLAG, CUSTOMS_CODE, TRAF_MODE, VOYAGE_NO, SHIP_ID, I_E_DATE
MANIFEST_HEAD_XMS_LOG:VOYAGE_NO, SHIP_ID, CUSTOMS_CODE, I_E_DATE, TRAF_MODE, I_E_FLAG
MANIFEST_LIST:BILL_NO, VOYAGE_NO, CUSTOMS_CODE, SHIP_ID, I_E_DATE, TRAF_MODE, I_E_FLAG
MANIFEST_LIST_CONTA:VOYAGE_NO, CUSTOMS_CODE, TRAF_MODE, I_E_FLAG, BILL_NO, CONTA_ID, SHIP_ID
MANIFEST_LIST_LOG:I_E_FLAG, CUSTOMS_CODE, TRAF_MODE, VOYAGE_NO, BILL_NO, SHIP_ID, CREATE_DATE, I_E_DATE
MANIFEST_LIST_RSKINFO_LOG:BILL_NO, CUSTOMS_CODE, VOYAGE_NO, SHIP_ID, I_E_DATE, TRAF_MODE, I_E_FLAG, RSK_DATE
MNL_PARA:PARA_TYPE, PARA_ID
MNL_PRESS:PARA_TYPE, PARA_NAME
MNL_RECEIVE_RECEIPT:MANUAL_NO, SEND_CUSTOMS, CUSTOMS_CODE, H2000_RECEIVE_DATE
MNL_SEQ:MNL_KEY
MNLBAK_ACCOUNT:MANUAL_NO, ID_STAT
MNLBAK_APPL_CLOSE:MANUAL_NO
MNLBAK_CLAIM:GUARANTEE_NO
MNLBAK_CONSUME:MANUAL_NO, CONTR_ITEM, EX_NO
MNLBAK_CONTRACT_HEAD:MANUAL_NO
MNLBAK_CONTRACT_WORKFLOW:MANUAL_NO, STEP_ID, PROC_DATE
MNLBAK_EX_CONTRACT_CLEAR:MANUAL_NO, CONTR_ITEM
MNLBAK_EX_CONTRACT_DEDUC:MANUAL_NO, ENTRY_ID, G_NO
MNLBAK_EX_CONTRACT_LIST:MANUAL_NO, CONTR_ITEM
MNLBAK_EX_FASCICLE_LIST:FASCICLE_NO, CONTR_ITEM
MNLBAK_FASCICLE_HEAD:FASCICLE_NO
MNLBAK_FEE_INVOICE:MANUAL_NO, F_NO
MNLBAK_IM_CONTRACT_CLEAR:MANUAL_NO, CONTR_ITEM
MNLBAK_IM_CONTRACT_DEDUC:MANUAL_NO, ENTRY_ID, G_NO
MNLBAK_IM_CONTRACT_LIST:MANUAL_NO, CONTR_ITEM
MNLBAK_IM_FASCICLE_LIST:FASCICLE_NO, CONTR_ITEM
MNLBAK_PRESS_CLEAR:MANUAL_NO, PR_NO
MNLBAK_SERVICE_FEE:MANUAL_NO
MNLBAK_SERVICE_LIST:MANUAL_NO, F_NO
MOD_PROJECT_HEAD:PROJECT_ID, MODIFY_TIMES
MOD_PROJECT_LIST:PROJECT_ID, MODIFY_TIMES, G_NO
MOD_RED_HEAD:CUT_ID, MODIFY_TIMES
MOD_RED_LIST:CUT_ID, MODIFY_TIMES, G_NO
NONENTRY_CHK_RESULT:RSK_NO
NORSK_COMPANY:CCTS_CODE
NORSK_COMPANY_BAK:CCTS_CODE, OP_BAK_TIME
NORSK_CONDITION:CCTS_CODE
NORSK_CONDITION_BAK:CCTS_CODE, OP_BAK_TIME
NORSK_TRADE_MODE:CCTS_CODE
NORSK_TRADE_MODE_BAK:CCTS_CODE, OP_BAK_TIME
OCC_ELE_HEAD:CERTIFICATE_NO, AGREEMENT_ID, ISSUE_PLACE
OCC_ELE_LIST:CERTIFICATE_NO, AGREEMENT_ID, ISSUE_PLACE, G_NO
OCC_EXAM:CERTIFICATE_NO, AGREEMENT_ID, ISSUE_PLACE, G_NO, ENTRY_G_NO
OCC_RECEIPT:CERTIFICATE_NO, AGREEMENT_ID, ISSUE_PLACE
OTHER_STF_RECORD:OTHER_ID, ID_TYPE
PAPERLESS_SELFSAVE_CERT:ENTRY_ID
PAYOUT_REMIT_HEAD:RPTNO
PAYOUT_REMIT_LIST:RPTNO, ENTRY_ID
PES_CANCEL:ENTRY_ID
PES_NOTE:NOTE_NO
PES_WORKFLOW:NOTE_NO, NOTE_TYPE, PROCESS_DATE, STEP_ID
PORT_BIND_REL:BIND_NO, PRE_NO
PRE_APPL_CLOSE:MANUAL_NO
PRE_APPL_CLOSE_CONSUME:MANUAL_NO, CONTR_ITEM, EX_NO
PRE_CDL_COMMODITY:PRE_RECORDS_NO, RECORDS_DATE, G_NO
PRE_CDL_COMPANY:TRADE_CO, RECORDS_DATE, TRADE_BONDED_FLAG
PRE_COMPANY_REL:PRE_TRADE_CO
PRE_CONSUME:MANUAL_NO, CONTR_ITEM, EX_NO
PRE_CONTRACT_HEAD:MANUAL_NO
PRE_DECL_REL:DECL_TRAIN_CO
PRE_EX_APPL_CLOSE:MANUAL_NO, CONTR_ITEM
PRE_EX_CONTRACT_LIST:MANUAL_NO, CONTR_ITEM
PRE_EX_FASCICLE_LIST:FASCICLE_NO, CONTR_ITEM
PRE_EXA_APPL_CLOSE:MANUAL_NO, CONTR_ITEM
PRE_FASCICLE_HEAD:FASCICLE_NO
PRE_IM_APPL_CLOSE:MANUAL_NO, CONTR_ITEM
PRE_IM_CONTRACT_LIST:MANUAL_NO, CONTR_ITEM
PRE_IM_FASCICLE_LIST:FASCICLE_NO, CONTR_ITEM
PRE_IMA_APPL_CLOSE:MANUAL_NO, CONTR_ITEM
PRE_INVESTER_REL:PRE_TRADE_CO, INV_NO
PRE_MANA_REL:PRE_TRADE_CO, MANAG_NO
PRE_PROJECT_HEAD:PROJECT_ID, MODIFY_TIMES
PRE_PROJECT_LIST:PROJECT_ID, MODIFY_TIMES, G_NO
PRE_RED_HEAD:CUT_ID, MODIFY_TIMES
PRE_RED_LIST:CUT_ID, MODIFY_TIMES, G_NO
PRE_REL_ALC_WORK:ENTRY_ID
PRESS_CLEAR:MANUAL_NO, PR_NO
PRICE_LIBRARY:REC_NO, I_E_FLAG, REC_TYPE, CREATE_DATE, POST_MARK
PRICE_LIBRARY_ENTRY:REC_NO, I_E_FLAG, REC_TYPE, CREATE_DATE
PRICE_LIBRARY_MAN:REC_NO, I_E_FLAG, REC_TYPE, CREATE_DATE
PRICE_LIBRARY_RISK:REC_NO, I_E_FLAG, REC_TYPE, CREATE_DATE
PROJECT_HEAD:PROJECT_ID, MODIFY_TIMES
PROJECT_LIST:PROJECT_ID, MODIFY_TIMES, G_NO
PROJECT_MAX_NO:MASTER_CUSTOMS, YEAR_2, CUT_MODE
PROJECT_MAX_NO_2007:MASTER_CUSTOMS, YEAR_4, CUT_MODE
RAM_HEAD:RAM_ID
RAM_LIST:RAM_ID, NUM
RAM_PRINT_LOG:RAM_ID, PRINT_DATE
RAM_RG_COP_OWNER:RAM_ID, TYPE, COP_NO, OWNER_NO
RAM_RG_COP_PROJECT:RAM_ID, TYPE, COP_NO, PROJECT_NO
RAM_RG_COPINFO:RAM_ID, TYPE, COP_NO
RAM_RG_HEAD:RAM_ID
RAM_RN_INFO:RAM_ID
RAM_RY_COMMUNICATION:RAM_ID, SEQ_NO
RAM_STATUS:CUT_ID, G_NO
RAM_STATUS_LIST:CUT_ID, G_NO
RAM_STATUS_MODI_LOG:CUT_ID, G_NO, MODIFY_DATE, FIELD_NAME
RCP_INCOME_HEAD:LEVYNO
RCP_INCOME_HEAD_BAK:LEVYNO
RCP_INCOME_LIST:LEVYNO, LISTNO
RCP_INCOME_LIST_BAK:LEVYNO, LISTNO
RCP_PAYMENT_HEAD:LEVYNO
RCP_PAYMENT_HEAD_BAK:LEVYNO
RCP_PAYMENT_LIST:LEVYNO, LISTNO
RCP_PAYMENT_LIST_BAK:LEVYNO, LISTNO
RCP_RECORD_HEAD:LEVYNO
RCP_RECORD_HEAD_BAK:LEVYNO
RCP_RECORD_LIST:LEVYNO, LISTNO
RCP_RECORD_LIST_BAK:LEVYNO, LISTNO
RCP_WORKFLOW:LEVYNO, TRANSFER_NUM, PROCESS_STATUS, PROCESS_DATE
RED_ENTRY_HEAD:ENTRY_ID
RED_ENTRY_LIST:ENTRY_ID, G_NO
RED_FEE_INVOICE:MANUAL_NO, FEE_ID
RED_HEAD:CUT_ID, MODIFY_TIMES
RED_LIST:CUT_ID, MODIFY_TIMES, G_NO
RED_MAX_NO:MASTER_CUSTOMS, YEAR_1, CLASS
RED_MAX_NO_2007:MASTER_CUSTOMS, YEAR_2
RED_RECEIVE_RECEIPT:CUT_ID, SEND_TIMES
RED_SERVICE_FEE:MANUAL_NO
REL_ALC_WORK:ENTRY_ID
RETURN_REL:RET_TRANS_NO, RET_TYPE, RET_TIME
RISK_CONTROL:RISK_CONTROL_CODE, RISK_TYPE, RISK_SCHEDULE
RSK_ASSAY_APPLICATION:ENTRY_ID, G_NO
RSK_CASE_FEEDBACK_HEAD:ENTRY_ID, CASE_ID
RSK_CASE_FEEDBACK_LIST:ENTRY_ID, CASE_ID, PROC_NO
RSK_CASE_FEEDBACK_LIST_CERT:ENTRY_ID, CASE_ID, CERT_NO
RSK_CASE_TRANSFER_G_NO:ENTRY_ID, CASE_ID, G_NO
RSK_CASE_TRANSFER_HEAD:ENTRY_ID, CASE_ID
RSK_CASE_TRANSFER_LIST:ENTRY_ID, CASE_ID, CERT_NO
RSK_CODE_TS:CCTS_CODE
RSK_CODE_TS_BAK:CCTS_CODE, OP_BAK_TIME
RSK_CONDITION:CCTS_CODE
RSK_CONDITION_BAK:CCTS_CODE, OP_BAK_TIME
RSK_CONTA_CAPACITY:CCTS_CODE
RSK_CONTA_CAPACITY_BAK:CCTS_CODE, OP_BAK_TIME
RSK_EXAM_HEAD_REL:EXAM_REC_ID
RSK_EXAM_LIST_CONTAINER:EXAM_REC_ID, CONTAINER_ID
RSK_EXAM_LIST_REL:EXAM_REC_ID, G_NO
RSK_EXAM_OP_LOG:EXAM_REC_ID, OP_TIME, MODI_TYPE, TABLE_NAME, ITEM_NAME
RSK_FAKE_CODE_TS:CCTS_CODE
RSK_FAKE_CODE_TS_BAK:CCTS_CODE, OP_BAK_TIME
RSK_FIT_LOG_REL:RSK_NO, FORM_ID, D_DATE
RSK_FIT_RESULT_LOG:RSK_NO, FORM_ID, D_DATE, RSK_POS
RSK_INSTR_ATTR_REL:RSK_NO
RSK_INSTR_PROC_REL:RSK_NO, RSK_POS
RSK_OP_LOG:FORM_ID, OP_TIME
RSK_RECHECK_REL:FORM_ID
RSK_REPLICATION_LOG:CUSTOMS_CODE, TABLE_NAME, REPLI_DATE
RSK_RESULT_REL:RSK_NO, FORM_ID, RSK_POS
RSK_TRADE_CO:CCTS_CODE
RSK_TRADE_CO_BAK:CCTS_CODE, OP_BAK_TIME
RSK_UNLOCK_OP_LOG:FORM_ID, RSK_NO, UNLOCK_TIME
RSK_VS_EXAM:FORM_ID, FORM_TYPE, RSK_NO, D_DATE, EXAM_REC_ID
RSK_WORKFLOW:ENTRY_ID, EXAM_REC_ID
SERVICE_FEE:MANUAL_NO
SERVICE_LIST:MANUAL_NO, F_NO
SHIP_TONNAGE:LICENSE_NO
SPECIAL_ENTRY:ENTRY_ID, OP_TIME
STATUS_DETAIL:ENTRY_ID, DETAIL_COUNT
STATUS_DETAIL:ENTRY_ID, DETAIL_COUNT
STF_RECORD:ENTRY_ID
STL_DATA_CONTA_LIST:UCR_CODE, CONTAINER_ID
STL_DATA_HEAD:UCR_CODE
STL_DATA_TS_LIST:UCR_CODE, G_NO
STL_REQUEST_CHK:UCR_CODE
TAR_DEL_LOG:ENTRY_ID, TAX_ID, OP_TIME
TCS_COUNTER:TCS_KEY
TCS_DETAIL_HEAD:ACCOUNT_ORG_CODE, IN_TREASURY_DATE, PACK_NO, CURRENT_PACK_NO
TCS_DETAIL_LIST:ACCOUNT_ORG_CODE, IN_TREASURY_DATE, PACK_NO, ITEM_NO
TCS_ERROR_LOG:GUID
TCS_SEND_LOG:TRANS_NO
TCS_STATISTIC_REPORT:ACCOUNT_ORG_CODE, REPORT_DATE, SPECIAL_PERIOD_FLAG, TREASURY_CODE, BUDGET_LEVEL_CODE, BUDGET_SUBJECT_CODE
TEMP_DB:PRE_NO, PROCESS_STEP
TEMP_DEL_EMS_CONSUME:RID
TEMP_DEL_EMS_HEAD:EMS_NO
TEMP_PAGE_RANGE:PR_KEY, PR_DETAIL
TEP_COMPANY:TEP_NO
TEP_DEBIT_REC_REQUEST:REQUEST_DATE, TRANS_NO
TEP_DEBIT_REC_RESPONSE:TRANS_NO, RESPONSE_DATE
TEP_EPLAT_RESPONSE:MSG_TYPE, CREATE_DATE
TEP_ERR_LOG:ERR_NO, CREATE_DATE
TEP_LOG:STEP_ID, BIZ_ID, CREATE_DATE
TEP_PAY_LOG:TRANS_NO, EPLAT_CODE
TEP_PAY_REC_REQUEST:REQUEST_DATE, TRANS_NO
TEP_PAY_REC_RESPONSE:RESPONSE_DATE, TRANS_NO
TEP_REC_LOG:REC_DATE, REC_TYPE, TRANS_NO
TEP_SEQ:TEP_KEY
TEP_STATUS_QUERY:TRANS_NO, SENDER_ID, DEAL_TIME
TEP_VOUCHER_REC_LIST:VOUCHER_RECEIVABLE_SEQ_NO
TEP_VOUCHER_REC_LIST_DETAIL:VOUCHER_RECEIVABLE_SEQ_NO, PAYEE_CODE, BANK_CODE, PAYEE_BANK_ACCOUNT
TEP_VOUCHER_REC_PAGE_LIST:VOUCHER_RECEIVABLE_SEQ_NO, PAYEE_CODE, BANK_CODE, PAYEE_BANK_ACCOUNT, PAGE_NAME, PAGE_NO
TMP_EMS_CONSUME:EMS_NO, EXG_NO, EXG_VERSION, IMG_NO
TMP_EMS_DCR_ENT:EMS_NO, DCR_TIMES, ENTRY_ID
TMP_EMS_HEAD:EMS_NO
TMP_EMS_LIST:EMS_NO, G_TYPE, G_NO
TRADE_ERR:HG_CODE
TRADE_GPM_RTX:TRADE_MODE, SIGN_TYPE, SIGN_MODE
TRANSFER_FEE:MANUAL_NO, RTN_MANUAL_NO
TRANSFER_FEE_LOG:MANUAL_NO, RTN_MANUAL_NO, CREATE_DATE
TRN_ALC_REL:CUSTOMS_CODE, TRN_MODE, TRAF_MODE
TRN_CHECK:NO
TRN_CHK_GOODS:CHK_CODE_TS
TRN_COP_REL:CO_REG_NO
TRN_DELAY_FORM:TURN_NO
TRN_DR_REL:DR_CUSTOMS_NO
TRN_ESEAL_REL:ESEAL_ID
TRN_EXAM_MAX_SEQ:TYPE, YEARAREA
TRN_I_E_PORT:VE_CUSTOMS_NO, I_E_PORT
TRN_PARAMETER:CUSTOMS_CODE, P_NAME
TRN_POP_COP_REL:AGENT_CODE, CUSTOMS_CODE
TRN_POP_HEAD:APPLY_NO
TRN_POP_LIST:APPLY_NO, RECORD_NUMBER
TRN_PRE_MAX_SEQ:TYPE, YEARAREA
TRN_SHIP:CUSTOM_NO
TRN_VE_REL:VE_CUSTOMS_NO
TRN_VEHICLE:CUSTOM_NO
YD_DECLARE_REL:TRADE_CO, CUSTOMS_CODE
