\timing
select now();
\echo "PK_ACCOUNT on ACCOUNT (MANUAL_NO, ID_STAT)"
create index PK_ACCOUNT on ACCOUNT (MANUAL_NO, ID_STAT) ;
select now();
\echo "PK_AGREEMENT_GOODS_LIST on AGREEMENT_GOODS_LIST (ENTRY_ID, G_NO)"
create index PK_AGREEMENT_GOODS_LIST on AGREEMENT_GOODS_LIST (ENTRY_ID, G_NO) ;
select now();
\echo "PK_AMSLIST_BODY on AMSLIST_BODY (LIST_ID, G_NO)"
create index PK_AMSLIST_BODY on AMSLIST_BODY (LIST_ID, G_NO) ;
select now();
\echo "PK_AMSLIST_HEAD on AMSLIST_HEAD (LIST_ID)"
create index PK_AMSLIST_HEAD on AMSLIST_HEAD (LIST_ID) ;
select now();
\echo "PK_AMS_MODI_LOG on AMS_MODI_LOG (EMS_NO, OP_TIME, MODI_TYPE, ITEM_NAME)"
create index PK_AMS_MODI_LOG on AMS_MODI_LOG (EMS_NO, OP_TIME, MODI_TYPE, ITEM_NAME) ;
select now();
\echo "PK_APPLY_HEAD on APPLY_HEAD (APPL_NO)"
create index PK_APPLY_HEAD on APPLY_HEAD (APPL_NO) ;
select now();
\echo "PK_APPLY_LIST on APPLY_LIST (APPL_NO, G_NO)"
create index PK_APPLY_LIST on APPLY_LIST (APPL_NO, G_NO) ;
select now();
\echo "PK_APPL_CLOSE on APPL_CLOSE (MANUAL_NO)"
create index PK_APPL_CLOSE on APPL_CLOSE (MANUAL_NO) ;
select now();
\echo "PK_APPL_CLOSE_CONSUME on APPL_CLOSE_CONSUME (MANUAL_NO, CONTR_ITEM, EX_NO)"
create index PK_APPL_CLOSE_CONSUME on APPL_CLOSE_CONSUME (MANUAL_NO, CONTR_ITEM, EX_NO) ;
select now();
\echo "PK_ARRIVAL_INFO_HEAD on ARRIVAL_INFO_HEAD (VOYAGE_NO, SHIP_ID, I_E_DATE, CUSTOMS_CODE, TRAF_MODE)"
create index PK_ARRIVAL_INFO_HEAD on ARRIVAL_INFO_HEAD (VOYAGE_NO, SHIP_ID, I_E_DATE, CUSTOMS_CODE, TRAF_MODE) ;
select now();
\echo "PK_ARRIVAL_INFO_LIST on ARRIVAL_INFO_LIST (BILL_NO, VOYAGE_NO, SHIP_ID, I_E_DATE, CUSTOMS_CODE, TRAF_MODE)"
create index PK_ARRIVAL_INFO_LIST on ARRIVAL_INFO_LIST (BILL_NO, VOYAGE_NO, SHIP_ID, I_E_DATE, CUSTOMS_CODE, TRAF_MODE) ;
select now();
\echo "PK_BAK_BWS_EXAM_CERT_LIST on BAK_BWS_EXAM_CERT_LIST (BWS_EXAM_NO, G_NO)"
create index PK_BAK_BWS_EXAM_CERT_LIST on BAK_BWS_EXAM_CERT_LIST (BWS_EXAM_NO, G_NO) ;
select now();
\echo "PK_BAK_BWS_EXAM_GOOD_LIST on BAK_BWS_EXAM_GOOD_LIST (BWS_EXAM_NO, G_NO)"
create index PK_BAK_BWS_EXAM_GOOD_LIST on BAK_BWS_EXAM_GOOD_LIST (BWS_EXAM_NO, G_NO) ;
select now();
\echo "PK_BAK_BWS_EXAM_HEAD on BAK_BWS_EXAM_HEAD (BWS_EXAM_NO)"
create index PK_BAK_BWS_EXAM_HEAD on BAK_BWS_EXAM_HEAD (BWS_EXAM_NO) ;
select now();
\echo "PK_BAK_CONSUME on BAK_CONSUME (MANUAL_NO, CONTR_ITEM, EX_NO)"
create index PK_BAK_CONSUME on BAK_CONSUME (MANUAL_NO, CONTR_ITEM, EX_NO) ;
select now();
\echo "PK_BAK_CONTRACT_HEAD on BAK_CONTRACT_HEAD (MANUAL_NO)"
create index PK_BAK_CONTRACT_HEAD on BAK_CONTRACT_HEAD (MANUAL_NO) ;
select now();
\echo "PK_BAK_DCG_BILL_HEAD on BAK_DCG_BILL_HEAD (BILL_NO)"
create index PK_BAK_DCG_BILL_HEAD on BAK_DCG_BILL_HEAD (BILL_NO) ;
select now();
\echo "PK_BAK_DCG_BILL_LIST on BAK_DCG_BILL_LIST (BILL_NO, G_TYPE, G_NO)"
create index PK_BAK_DCG_BILL_LIST on BAK_DCG_BILL_LIST (BILL_NO, G_TYPE, G_NO) ;
select now();
\echo "PK_BAK_DCG_DEDUCT on BAK_DCG_DEDUCT (ENTRY_ID, DCG_NO, G_TYPE, ENTRY_G_NO)"
create index PK_BAK_DCG_DEDUCT on BAK_DCG_DEDUCT (ENTRY_ID, DCG_NO, G_TYPE, ENTRY_G_NO) ;
select now();
\echo "PK_BAK_DCG_DEDUCT_LOG on BAK_DCG_DEDUCT_LOG (ENTRY_ID, DCG_NO, CREATE_DATE, JOU_MARK)"
create index PK_BAK_DCG_DEDUCT_LOG on BAK_DCG_DEDUCT_LOG (ENTRY_ID, DCG_NO, CREATE_DATE, JOU_MARK) ;
select now();
\echo "PK_BAK_DCG_HEAD on BAK_DCG_HEAD (DCG_NO)"
create index PK_BAK_DCG_HEAD on BAK_DCG_HEAD (DCG_NO) ;
select now();
\echo "PK_BAK_DCG_LIST on BAK_DCG_LIST (DCG_NO, G_TYPE, G_NO)"
create index PK_BAK_DCG_LIST on BAK_DCG_LIST (DCG_NO, G_TYPE, G_NO) ;
select now();
\echo "PK_BAK_EMS_APPR_HEAD on BAK_EMS_APPR_HEAD (APPR_NO, RECEIVE_TIMES)"
create index PK_BAK_EMS_APPR_HEAD on BAK_EMS_APPR_HEAD (APPR_NO, RECEIVE_TIMES) ;
select now();
\echo "PK_BAK_EMS_APPR_LIST on BAK_EMS_APPR_LIST (APPR_NO, G_TYPE, G_NO, RECEIVE_TIMES)"
create index PK_BAK_EMS_APPR_LIST on BAK_EMS_APPR_LIST (APPR_NO, G_TYPE, G_NO, RECEIVE_TIMES) ;
select now();
\echo "PK_BAK_EMS_CONSUME on BAK_EMS_CONSUME (EMS_NO, EXG_NO, EXG_VERSION, IMG_NO, MODIFY_TIMES)"
create index PK_BAK_EMS_CONSUME on BAK_EMS_CONSUME (EMS_NO, EXG_NO, EXG_VERSION, IMG_NO, MODIFY_TIMES) ;
select now();
\echo "PK_BAK_EMS_DEDUCT_CLR on BAK_EMS_DEDUCT_CLR (EMS_NO, IMG_NO, ENTRY_ID, ENTRY_G_NO)"
create index PK_BAK_EMS_DEDUCT_CLR on BAK_EMS_DEDUCT_CLR (EMS_NO, IMG_NO, ENTRY_ID, ENTRY_G_NO) ;
select now();
\echo "PK_BAK_EMS_HEAD on BAK_EMS_HEAD (EMS_NO, MODIFY_TIMES)"
create index PK_BAK_EMS_HEAD on BAK_EMS_HEAD (EMS_NO, MODIFY_TIMES) ;
select now();
\echo "PK_BAK_EMS_LIST on BAK_EMS_LIST (EMS_NO, G_TYPE, G_NO, MODIFY_TIMES)"
create index PK_BAK_EMS_LIST on BAK_EMS_LIST (EMS_NO, G_TYPE, G_NO, MODIFY_TIMES) ;
select now();
\echo "PK_BAK_EX_CONTRACT_LIST on BAK_EX_CONTRACT_LIST (MANUAL_NO, CONTR_ITEM)"
create index PK_BAK_EX_CONTRACT_LIST on BAK_EX_CONTRACT_LIST (MANUAL_NO, CONTR_ITEM) ;
select now();
\echo "PK_BAK_EX_FASCICLE_LIST on BAK_EX_FASCICLE_LIST (FASCICLE_NO, CONTR_ITEM)"
create index PK_BAK_EX_FASCICLE_LIST on BAK_EX_FASCICLE_LIST (FASCICLE_NO, CONTR_ITEM) ;
select now();
\echo "PK_BAK_FASCICLE_HEAD on BAK_FASCICLE_HEAD (FASCICLE_NO)"
create index PK_BAK_FASCICLE_HEAD on BAK_FASCICLE_HEAD (FASCICLE_NO) ;
select now();
\echo "PK_BAK_IM_CONTRACT_LIST on BAK_IM_CONTRACT_LIST (MANUAL_NO, CONTR_ITEM)"
create index PK_BAK_IM_CONTRACT_LIST on BAK_IM_CONTRACT_LIST (MANUAL_NO, CONTR_ITEM) ;
select now();
\echo "PK_BAK_IM_FASCICLE_LIST on BAK_IM_FASCICLE_LIST (FASCICLE_NO, CONTR_ITEM)"
create index PK_BAK_IM_FASCICLE_LIST on BAK_IM_FASCICLE_LIST (FASCICLE_NO, CONTR_ITEM) ;
select now();
\echo "PK_BANK_ACCOUNT on BANK_ACCOUNT (MANUAL_NO, ID_STAT, RECEIVE_DATE)"
create index PK_BANK_ACCOUNT on BANK_ACCOUNT (MANUAL_NO, ID_STAT, RECEIVE_DATE) ;
select now();
\echo "PK_BCK_COP_HEAD on BCK_COP_HEAD (TRADE_CODE)"
create index PK_BCK_COP_HEAD on BCK_COP_HEAD (TRADE_CODE) ;
select now();
\echo "PK_BCK_COP_LIST on BCK_COP_LIST (TRADE_CODE, RISK_NO, CUSTOMS_CODE)"
create index PK_BCK_COP_LIST on BCK_COP_LIST (TRADE_CODE, RISK_NO, CUSTOMS_CODE) ;
select now();
\echo "PK_BCK_COP_LIST_TEMP on BCK_COP_LIST_TEMP (TRADE_CO, RISK_NO, CUSTOMS_CODE)"
create index PK_BCK_COP_LIST_TEMP on BCK_COP_LIST_TEMP (TRADE_CO, RISK_NO, CUSTOMS_CODE) ;
select now();
\echo "PK_BCK_COP_PARA_HEAD on BCK_COP_PARA_HEAD (RISK_NO, CUSTOMS_CODE)"
create index PK_BCK_COP_PARA_HEAD on BCK_COP_PARA_HEAD (RISK_NO, CUSTOMS_CODE) ;
select now();
\echo "PK_BCK_COP_PARA_LIST on BCK_COP_PARA_LIST (RISK_NO, RISK_VALUE, CUSTOMS_CODE)"
create index PK_BCK_COP_PARA_LIST on BCK_COP_PARA_LIST (RISK_NO, RISK_VALUE, CUSTOMS_CODE) ;
select now();
\echo "PK_BCK_EXECUTOR on BCK_EXECUTOR (BCK_NO, EXECUTOR)"
create index PK_BCK_EXECUTOR on BCK_EXECUTOR (BCK_NO, EXECUTOR) ;
select now();
\echo "PK_BCK_HANDOVER on BCK_HANDOVER (HANDOVER_NO)"
create index PK_BCK_HANDOVER on BCK_HANDOVER (HANDOVER_NO) ;
select now();
\echo "PK_BCK_HANDOVER_TYPE on BCK_HANDOVER_TYPE (HANDOVER_TYPE, ID)"
create index PK_BCK_HANDOVER_TYPE on BCK_HANDOVER_TYPE (HANDOVER_TYPE, ID) ;
select now();
\echo "PK_BCK_HEAD on BCK_HEAD (BCK_NO)"
create index PK_BCK_HEAD on BCK_HEAD (BCK_NO) ;
select now();
\echo "PK_BCK_SEQ on BCK_SEQ (BCK_KEY)"
create index PK_BCK_SEQ on BCK_SEQ (BCK_KEY) ;
select now();
\echo "PK_BCK_STOCK_HEAD on BCK_STOCK_HEAD (SEQ_NO)"
create index PK_BCK_STOCK_HEAD on BCK_STOCK_HEAD (SEQ_NO) ;
select now();
\echo "PK_BCK_STOCK_LIST on BCK_STOCK_LIST (SEQ_NO, LIST_NO)"
create index PK_BCK_STOCK_LIST on BCK_STOCK_LIST (SEQ_NO, LIST_NO) ;
select now();
\echo "PK_BCK_WORKFLOW on BCK_WORKFLOW (BCK_NO, STEP_ID, OPER_ID, CREATE_DATE)"
create index PK_BCK_WORKFLOW on BCK_WORKFLOW (BCK_NO, STEP_ID, OPER_ID, CREATE_DATE) ;
select now();
\echo "PK_BTI_DATA_CONTA_LIST on BTI_DATA_CONTA_LIST (UCR_CODE, CONTAINER_ID)"
create index PK_BTI_DATA_CONTA_LIST on BTI_DATA_CONTA_LIST (UCR_CODE, CONTAINER_ID) ;
select now();
\echo "PK_BTI_DATA_HEAD on BTI_DATA_HEAD (UCR_CODE, CREATE_DATE)"
create index PK_BTI_DATA_HEAD on BTI_DATA_HEAD (UCR_CODE, CREATE_DATE) ;
select now();
\echo "PK_BTI_DATA_TS_LIST on BTI_DATA_TS_LIST (UCR_CODE, G_NO)"
create index PK_BTI_DATA_TS_LIST on BTI_DATA_TS_LIST (UCR_CODE, G_NO) ;
select now();
\echo "PK_BWS_AUDIT_HEAD on BWS_AUDIT_HEAD (AUDIT_NO)"
create index PK_BWS_AUDIT_HEAD on BWS_AUDIT_HEAD (AUDIT_NO) ;
select now();
\echo "PK_BWS_AUDIT_LIST on BWS_AUDIT_LIST (AUDIT_NO, G_NO)"
create index PK_BWS_AUDIT_LIST on BWS_AUDIT_LIST (AUDIT_NO, G_NO) ;
select now();
\echo "PK_BWS_DCR_BILL_LIST on BWS_DCR_BILL_LIST (BWS_NO, DCR_TIMES, G_TYPE, G_NO)"
create index PK_BWS_DCR_BILL_LIST on BWS_DCR_BILL_LIST (BWS_NO, DCR_TIMES, G_TYPE, G_NO) ;
select now();
\echo "PK_BWS_DCR_HEAD on BWS_DCR_HEAD (BWS_NO, DCR_TIMES, DCR_TYPE)"
create index PK_BWS_DCR_HEAD on BWS_DCR_HEAD (BWS_NO, DCR_TIMES, DCR_TYPE) ;
select now();
\echo "PK_BWS_DCR_LIST on BWS_DCR_LIST (BWS_NO, DCR_TIMES, G_NO)"
create index PK_BWS_DCR_LIST on BWS_DCR_LIST (BWS_NO, DCR_TIMES, G_NO) ;
select now();
\echo "PK_BWS_DEDUCT on BWS_DEDUCT (BWS_ID, ENTRY_G_NO)"
create index PK_BWS_DEDUCT on BWS_DEDUCT (BWS_ID, ENTRY_G_NO) ;
select now();
\echo "PK_BWS_DEDUCT_LOG on BWS_DEDUCT_LOG (BWS_ID, BWS_NO, CREATE_DATE, JOU_MARK)"
create index PK_BWS_DEDUCT_LOG on BWS_DEDUCT_LOG (BWS_ID, BWS_NO, CREATE_DATE, JOU_MARK) ;
select now();
\echo "PK_BWS_EXAM_CERT_LIST on BWS_EXAM_CERT_LIST (BWS_EXAM_NO, G_NO)"
create index PK_BWS_EXAM_CERT_LIST on BWS_EXAM_CERT_LIST (BWS_EXAM_NO, G_NO) ;
select now();
\echo "PK_BWS_EXAM_GOOD_LIST on BWS_EXAM_GOOD_LIST (BWS_EXAM_NO, G_NO)"
create index PK_BWS_EXAM_GOOD_LIST on BWS_EXAM_GOOD_LIST (BWS_EXAM_NO, G_NO) ;
select now();
\echo "PK_BWS_EXAM_HEAD on BWS_EXAM_HEAD (BWS_EXAM_NO)"
create index PK_BWS_EXAM_HEAD on BWS_EXAM_HEAD (BWS_EXAM_NO) ;
select now();
\echo "PK_BWS_EXAM_PASSCERT on BWS_EXAM_PASSCERT (CERT_NO)"
create index PK_BWS_EXAM_PASSCERT on BWS_EXAM_PASSCERT (CERT_NO) ;
select now();
\echo "PK_BWS_EXAM_TEMP on BWS_EXAM_TEMP (BWS_EXAM_NO) ;
create index PK_BWS_EXAM_TEMP on BWS_EXAM_TEMP (BWS_EXAM_NO) ;
select now();
\echo "PK_BWS_FORM_HEAD on BWS_FORM_HEAD (FORM_ID)"
create index PK_BWS_FORM_HEAD on BWS_FORM_HEAD (FORM_ID) ;
select now();
\echo "PK_BWS_FORM_LIST on BWS_FORM_LIST (FORM_ID, G_NO)"
create index PK_BWS_FORM_LIST on BWS_FORM_LIST (FORM_ID, G_NO) ;
select now();
\echo "PK_BWS_GB_LIST on BWS_GB_LIST (BWS_NO, G_NO)"
create index PK_BWS_GB_LIST on BWS_GB_LIST (BWS_NO, G_NO) ;
select now();
\echo "PK_BWS_HEAD on BWS_HEAD (BWS_NO)"
create index PK_BWS_HEAD on BWS_HEAD (BWS_NO) ;
select now();
\echo "PK_BWS_LIST on BWS_LIST (BWS_NO, G_NO)"
create index PK_BWS_LIST on BWS_LIST (BWS_NO, G_NO) ;
select now();
\echo "PK_BWS_MANIFEST_HEAD on BWS_MANIFEST_HEAD (BWS_MANIFEST_NO)"
create index PK_BWS_MANIFEST_HEAD on BWS_MANIFEST_HEAD (BWS_MANIFEST_NO) ;
select now();
\echo "PK_BWS_MANIFEST_LIST on BWS_MANIFEST_LIST (BWS_MANIFEST_NO, G_NO)"
create index PK_BWS_MANIFEST_LIST on BWS_MANIFEST_LIST (BWS_MANIFEST_NO, G_NO) ;
select now();
\echo "PK_BWS_SEQ on BWS_SEQ (BWS_KEY)"
create index PK_BWS_SEQ on BWS_SEQ (BWS_KEY) ;
select now();
\echo "PK_BWS_VAR on BWS_VAR (VAR_TYPE, VAR_ID, VAR_SUB_ID, CUSTOMS_CODE)"
create index PK_BWS_VAR on BWS_VAR (VAR_TYPE, VAR_ID, VAR_SUB_ID, CUSTOMS_CODE) ;
select now();
\echo "PK_BWS_WORKFLOW on BWS_WORKFLOW (BWS_ID, STEP_ID, CREATE_DATE)"
create index PK_BWS_WORKFLOW on BWS_WORKFLOW (BWS_ID, STEP_ID, CREATE_DATE) ;
select now();
\echo "PK_CCTS_ERROR_LOG on CCTS_ERROR_LOG (SEQUENCE_NO)"
create index PK_CCTS_ERROR_LOG on CCTS_ERROR_LOG (SEQUENCE_NO) ;
select now();
\echo "PK_CCTS_ONLINE_RESULT on CCTS_ONLINE_RESULT (SEQUENCE_NO)"
create index PK_CCTS_ONLINE_RESULT on CCTS_ONLINE_RESULT (SEQUENCE_NO) ;
select now();
\echo "PK_CCTS_ONLINE_RESULT_BAK on CCTS_ONLINE_RESULT_BAK (SEQUENCE_NO)"
create index PK_CCTS_ONLINE_RESULT_BAK on CCTS_ONLINE_RESULT_BAK (SEQUENCE_NO) ;
select now();
\echo "PK_CCTS_PERFORMANCE on CCTS_PERFORMANCE (SEQUENCE_NO)"
create index PK_CCTS_PERFORMANCE on CCTS_PERFORMANCE (SEQUENCE_NO) ;
select now();
\echo "PK_CCTS_RSK_RESULT on CCTS_RSK_RESULT (CCTS_CODE, CUSTOMS_CODE)"
create index PK_CCTS_RSK_RESULT on CCTS_RSK_RESULT (CCTS_CODE, CUSTOMS_CODE) ;
select now();
\echo "PK_CCTS_RSK_RESULT_BAK on CCTS_RSK_RESULT_BAK (CCTS_CODE, CUSTOMS_CODE, OP_BAK_TIME)"
create index PK_CCTS_RSK_RESULT_BAK on CCTS_RSK_RESULT_BAK (CCTS_CODE, CUSTOMS_CODE, OP_BAK_TIME) ;
select now();
\echo "PK_CDL_CERTIFICATE on CDL_CERTIFICATE (LIST_NO, DOCU_CODE, CERT_CODE)"
create index PK_CDL_CERTIFICATE on CDL_CERTIFICATE (LIST_NO, DOCU_CODE, CERT_CODE) ;
select now();
\echo "PK_CDL_CHK on CDL_CHK (LIST_NO)"
create index PK_CDL_CHK on CDL_CHK (LIST_NO) ;
select now();
\echo "PK_CDL_COMMODITY on CDL_COMMODITY (RECORDS_NO, G_NO)"
create index PK_CDL_COMMODITY on CDL_COMMODITY (RECORDS_NO, G_NO) ;
select now();
\echo "PK_CDL_COMPANY on CDL_COMPANY (TRADE_CO, CUSTOMS_CODE, TRADE_BONDED_FLAG)"
create index PK_CDL_COMPANY on CDL_COMPANY (TRADE_CO, CUSTOMS_CODE, TRADE_BONDED_FLAG) ;
select now();
\echo "PK_CDL_COMP_COMM_MODIFY_LOG on CDL_COMP_COMM_MODIFY_LOG (TRADE_CO, OP_TIME, MODI_TYPE, ITEM_NAME)"
create index PK_CDL_COMP_COMM_MODIFY_LOG on CDL_COMP_COMM_MODIFY_LOG (TRADE_CO, OP_TIME, MODI_TYPE, ITEM_NAME) ;
select now();
\echo "PK_CDL_COMP_COMM_OP_LOG on CDL_COMP_COMM_OP_LOG (TRADE_CO, PROC_DATE, PROC_TYPE)"
create index PK_CDL_COMP_COMM_OP_LOG on CDL_COMP_COMM_OP_LOG (TRADE_CO, PROC_DATE, PROC_TYPE) ;
select now();
\echo "PK_CDL_CONTAINER on CDL_CONTAINER (LIST_NO, CONTAINER_ID)"
create index PK_CDL_CONTAINER on CDL_CONTAINER (LIST_NO, CONTAINER_ID) ;
select now();
\echo "PK_CDL_DEL_CERTIFICATE_LOG on CDL_DEL_CERTIFICATE_LOG (LIST_NO, DOCU_CODE, CERT_CODE)"
create index PK_CDL_DEL_CERTIFICATE_LOG on CDL_DEL_CERTIFICATE_LOG (LIST_NO, DOCU_CODE, CERT_CODE) ;
select now();
\echo "PK_CDL_DEL_CONTAINER_LOG on CDL_DEL_CONTAINER_LOG (LIST_NO, CONTAINER_ID, CONTAINER_WT)"
create index PK_CDL_DEL_CONTAINER_LOG on CDL_DEL_CONTAINER_LOG (LIST_NO, CONTAINER_ID, CONTAINER_WT) ;
select now();
\echo "PK_CDL_DEL_HEAD_LOG on CDL_DEL_HEAD_LOG (LIST_NO)"
create index PK_CDL_DEL_HEAD_LOG on CDL_DEL_HEAD_LOG (LIST_NO) ;
select now();
\echo "PK_CDL_DEL_LIST_LOG on CDL_DEL_LIST_LOG (LIST_NO, G_NO)"
create index PK_CDL_DEL_LIST_LOG on CDL_DEL_LIST_LOG (LIST_NO, G_NO) ;
select now();
\echo "PK_CDL_EDI_MESS on CDL_EDI_MESS (MESS_CODE)"
create index PK_CDL_EDI_MESS on CDL_EDI_MESS (MESS_CODE) ;
select now();
\echo "PK_CDL_EMS_DEDUCT on CDL_EMS_DEDUCT (ENTRY_ID, EMS_NO, G_TYPE, ENTRY_G_NO)"
create index PK_CDL_EMS_DEDUCT on CDL_EMS_DEDUCT (ENTRY_ID, EMS_NO, G_TYPE, ENTRY_G_NO) ;
select now();
\echo "PK_CDL_EMS_DEDUCT_LOG on CDL_EMS_DEDUCT_LOG (ENTRY_ID, EMS_NO, CREATE_DATE, JOU_MARK)"
create index PK_CDL_EMS_DEDUCT_LOG on CDL_EMS_DEDUCT_LOG (ENTRY_ID, EMS_NO, CREATE_DATE, JOU_MARK) ;
select now();
\echo "PK_CDL_ENTRY_HEAD on CDL_ENTRY_HEAD (PRE_ENTRY_ID)"
create index PK_CDL_ENTRY_HEAD on CDL_ENTRY_HEAD (PRE_ENTRY_ID) ;
select now();
\echo "PK_CDL_ENTRY_LIST on CDL_ENTRY_LIST (PRE_ENTRY_ID, ENTRY_G_NO, LIST_NO, LIST_G_NO)"
create index PK_CDL_ENTRY_LIST on CDL_ENTRY_LIST (PRE_ENTRY_ID, ENTRY_G_NO, LIST_NO, LIST_G_NO) ;
select now();
\echo "PK_CDL_HEAD on CDL_HEAD (LIST_NO)"
create index PK_CDL_HEAD on CDL_HEAD (LIST_NO) ;
select now();
\echo "PK_CDL_LICENSE_DEDUCT on CDL_LICENSE_DEDUCT (LIST_NO, G_NO, TRADE_CO, OP_TIME)"
create index PK_CDL_LICENSE_DEDUCT on CDL_LICENSE_DEDUCT (LIST_NO, G_NO, TRADE_CO, OP_TIME) ;
select now();
\echo "PK_CDL_LIST on CDL_LIST (LIST_NO, G_NO)"
create index PK_CDL_LIST on CDL_LIST (LIST_NO, G_NO) ;
select now();
\echo "PK_CDL_LOCK_COMMODITY on CDL_LOCK_COMMODITY (CODE_TS, CONTROL_COUNTRY, CUSTOMS_CODE, I_E_FLAG, TRADE_MODE)"
create index PK_CDL_LOCK_COMMODITY on CDL_LOCK_COMMODITY (CODE_TS, CONTROL_COUNTRY, CUSTOMS_CODE, I_E_FLAG, TRADE_MODE) ;
select now();
\echo "PK_CDL_MODI_LOG on CDL_MODI_LOG (LIST_NO, OP_TIME, MODI_TYPE, ITEM_NAME)"
create index PK_CDL_MODI_LOG on CDL_MODI_LOG (LIST_NO, OP_TIME, MODI_TYPE, ITEM_NAME) ;
select now();
\echo "PK_CDL_OP_LOG on CDL_OP_LOG (LIST_NO, OP_TIME)"
create index PK_CDL_OP_LOG on CDL_OP_LOG (LIST_NO, OP_TIME) ;
select now();
\echo "PK_CDL_OVERDUE_LIST on CDL_OVERDUE_LIST (TRADE_CO, ENTRY_ID)"
create index PK_CDL_OVERDUE_LIST on CDL_OVERDUE_LIST (TRADE_CO, ENTRY_ID) ;
select now();
\echo "PK_CDL_STATUS_DETAIL on CDL_STATUS_DETAIL (LIST_NO, DETAIL_COUNT)"
create index PK_CDL_STATUS_DETAIL on CDL_STATUS_DETAIL (LIST_NO, DETAIL_COUNT) ;
select now();
\echo "PK_CDL_WORKFLOW on CDL_WORKFLOW (LIST_NO, STEP_ID, CREATE_DATE)"
create index PK_CDL_WORKFLOW on CDL_WORKFLOW (LIST_NO, STEP_ID, CREATE_DATE) ;
select now();
\echo "PK_CHKHS_MNLPROC on CHKHS_MNLPROC (ORDER_NO, MANUAL_SCH)"
create index PK_CHKHS_MNLPROC on CHKHS_MNLPROC (ORDER_NO, MANUAL_SCH) ;
select now();
\echo "PK_CHK_COP_RATIO on CHK_COP_RATIO (CORP_CODE)"
create index PK_CHK_COP_RATIO on CHK_COP_RATIO (CORP_CODE) ;
select now();
\echo "PK_CHK_COUNTER on CHK_COUNTER (CUSTOMS_CODE, I_E_FLAG, COUNTER_TYPE, COUNT_DATE)"
create index PK_CHK_COUNTER on CHK_COUNTER (CUSTOMS_CODE, I_E_FLAG, COUNTER_TYPE, COUNT_DATE) ;
select now();
\echo "PK_CHK_RATE_LIMIT on CHK_RATE_LIMIT (CUSTOMS_CODE, I_E_FLAG)"
create index PK_CHK_RATE_LIMIT on CHK_RATE_LIMIT (CUSTOMS_CODE, I_E_FLAG) ;
select now();
\echo "PK_CIC_CODE on CIC_CODE (FIRST_NO)"
create index PK_CIC_CODE on CIC_CODE (FIRST_NO) ;
select now();
\echo "PK_CIC_HEAD on CIC_HEAD (CPT_NO)"
create index PK_CIC_HEAD on CIC_HEAD (CPT_NO) ;
select now();
\echo "PK_CIC_LIST on CIC_LIST (CPT_NO, ITEM_NO)"
create index PK_CIC_LIST on CIC_LIST (CPT_NO, ITEM_NO) ;
select now();
\echo "PK_CIC_MAXID on CIC_MAXID (CUS_ID)"
create index PK_CIC_MAXID on CIC_MAXID (CUS_ID) ;
select now();
\echo "PK_CIC_SEND_REL on CIC_SEND_REL (CPT_NO, SEND_TIMES)"
create index PK_CIC_SEND_REL on CIC_SEND_REL (CPT_NO, SEND_TIMES) ;
select now();
\echo "PK_CLAIM on CLAIM (GUARANTEE_NO)"
create index PK_CLAIM on CLAIM (GUARANTEE_NO) ;
select now();
\echo "PK_CLC_CHKRATE_LIMIT on CLC_CHKRATE_LIMIT (CUSTOMS_CODE, I_E_FLAG)"
create index PK_CLC_CHKRATE_LIMIT on CLC_CHKRATE_LIMIT (CUSTOMS_CODE, I_E_FLAG) ;
select now();
\echo "PK_CLC_GPR_RATIO on CLC_GPR_RATIO (CUSTOMS_CODE, I_E_FLAG)"
create index PK_CLC_GPR_RATIO on CLC_GPR_RATIO (CUSTOMS_CODE, I_E_FLAG) ;
select now();
\echo "PK_CLC_GPR_RATIO_BAK on CLC_GPR_RATIO_BAK (CUSTOMS_CODE, I_E_FLAG, OP_TIME)"
create index PK_CLC_GPR_RATIO_BAK on CLC_GPR_RATIO_BAK (CUSTOMS_CODE, I_E_FLAG, OP_TIME) ;
select now();
\echo "  add on CNSMATCH (EX_CODE_TS, IM_CODE_TS)"
create index PK_CNSMATCH add on CNSMATCH (EX_CODE_TS, IM_CODE_TS) ;
select now();
\echo "PK_CNS_COUNTER_TABLE on CNS_COUNTER_TABLE (CUSTOMS_CODE)"
create index PK_CNS_COUNTER_TABLE on CNS_COUNTER_TABLE (CUSTOMS_CODE) ;
select now();
\echo "PK_COMPANY_REL on COMPANY_REL (TRADE_CO)"
create index PK_COMPANY_REL on COMPANY_REL (TRADE_CO) ;
select now();
\echo "PK_CONSUME on CONSUME (MANUAL_NO, CONTR_ITEM, EX_NO)"
create index PK_CONSUME on CONSUME (MANUAL_NO, CONTR_ITEM, EX_NO) ;
select now();
\echo "PK_CONSUME_DB on CONSUME_DB (EX_CODE_TS, EX_NO, IM_CODE_TS, IM_NO)"
create index PK_CONSUME_DB on CONSUME_DB (EX_CODE_TS, EX_NO, IM_CODE_TS, IM_NO) ;
select now();
\echo "PK_CONSUME_GOODS on CONSUME_GOODS (CODE_TS, G_NO, G_FLAG)"
create index PK_CONSUME_GOODS on CONSUME_GOODS (CODE_TS, G_NO, G_FLAG) ;
select now();
\echo "PK_CONTA on CONTA (FORM_ID, CONTA_ID)"
create index PK_CONTA on CONTA (FORM_ID, CONTA_ID) ;
select now();
\echo "PK_CONTA_MONITOR on CONTA_MONITOR (I_E_FLAG, CONTA_ID, DISTRIBUTIVE_NO, IN_OUT_FLAG)"
create index PK_CONTA_MONITOR on CONTA_MONITOR (I_E_FLAG, CONTA_ID, DISTRIBUTIVE_NO, IN_OUT_FLAG) ;
select now();
\echo "PK_CONTRACT_HEAD on CONTRACT_HEAD (MANUAL_NO)"
create index PK_CONTRACT_HEAD on CONTRACT_HEAD (MANUAL_NO) ;
select now();
\echo "PK_CONTRACT_WORKFLOW on CONTRACT_WORKFLOW (MANUAL_NO, STEP_ID, PROC_DATE)"
create index PK_CONTRACT_WORKFLOW on CONTRACT_WORKFLOW (MANUAL_NO, STEP_ID, PROC_DATE) ;
select now();
\echo "PK_CONVEYANCE on CONVEYANCE (SHIP_ID, TRAF_MODE)"
create index PK_CONVEYANCE on CONVEYANCE (SHIP_ID, TRAF_MODE) ;
select now();
\echo "PK_CONVEYANCE_SEGMENT on CONVEYANCE_SEGMENT (SHIP_ID, TRAF_MODE, VOYAGE_NO, I_E_FLAG, LOAD_PORT, DESTINATION_PORT, CUSTOMS_CODE, I_E_DATE)"
create index PK_CONVEYANCE_SEGMENT on CONVEYANCE_SEGMENT (SHIP_ID, TRAF_MODE, VOYAGE_NO, I_E_FLAG, LOAD_PORT, DESTINATION_PORT, CUSTOMS_CODE, I_E_DATE) ;
select now();
\echo "PK_COPLOG_DELETE_REL on COPLOG_DELETE_REL (LOG_ID)"
create index PK_COPLOG_DELETE_REL on COPLOG_DELETE_REL (LOG_ID) ;
select now();
\echo "PK_COPLOG_MODIFY_REL on COPLOG_MODIFY_REL (LOG_ID)"
create index PK_COPLOG_MODIFY_REL on COPLOG_MODIFY_REL (LOG_ID) ;
select now();
\echo "PK_COP_CONSUME on COP_CONSUME (REC_NUM)"
create index PK_COP_CONSUME on COP_CONSUME (REC_NUM) ;
select now();
\echo "PK_COP_SPEC_REL on COP_SPEC_REL (ENTRY_ID, AUTH_ID)"
create index PK_COP_SPEC_REL on COP_SPEC_REL (ENTRY_ID, AUTH_ID) ;
select now();
\echo "PK_CORP_HEAD on CORP_HEAD (FORM_ID)"
create index PK_CORP_HEAD on CORP_HEAD (FORM_ID) ;
select now();
\echo "PK_CORP_LIST on CORP_LIST (FORM_ID, FIELD_ID)"
create index PK_CORP_LIST on CORP_LIST (FORM_ID, FIELD_ID) ;
select now();
\echo "PK_CORP_TABLE on CORP_TABLE (FIELD_ID, TABLE_ID)"
create index PK_CORP_TABLE on CORP_TABLE (FIELD_ID, TABLE_ID) ;
select now();
\echo "PK_CORP_TYPE on CORP_TYPE (CORP_TYPE)"
create index PK_CORP_TYPE on CORP_TYPE (CORP_TYPE) ;
select now();
\echo "PK_COUNTER_TABLE on COUNTER_TABLE (COUNTER_TYPE, CUSTOMS_CODE, I_E_FLAG, C_DATE)"
create index PK_COUNTER_TABLE on COUNTER_TABLE (COUNTER_TYPE, CUSTOMS_CODE, I_E_FLAG, C_DATE) ;
select now();
\echo "PK_CO_CLASS_REL on CO_CLASS_REL (TRADE_CO, CLASS_NO)"
create index PK_CO_CLASS_REL on CO_CLASS_REL (TRADE_CO, CLASS_NO) ;
select now();
\echo "PK_CREDIT_INFO on CREDIT_INFO (RPTNO)"
create index PK_CREDIT_INFO on CREDIT_INFO (RPTNO) ;
select now();
\echo "PK_CTS_CHKRATE_LIMIT on CTS_CHKRATE_LIMIT (ID)"
create index PK_CTS_CHKRATE_LIMIT on CTS_CHKRATE_LIMIT (ID) ;
select now();
\echo "PK_CTS_CHKRATE_LIMIT_BAK on CTS_CHKRATE_LIMIT_BAK (ID, OP_BAK_TIME)"
create index PK_CTS_CHKRATE_LIMIT_BAK on CTS_CHKRATE_LIMIT_BAK (ID, OP_BAK_TIME) ;
select now();
\echo "PK_CTS_PERIOD on CTS_PERIOD (CUSTOMS_CODE)"
create index PK_CTS_PERIOD on CTS_PERIOD (CUSTOMS_CODE) ;
select now();
\echo "PK_CUSTOMS_DEFAULT on CUSTOMS_DEFAULT (MASTER_CUSTOMS)"
create index PK_CUSTOMS_DEFAULT on CUSTOMS_DEFAULT (MASTER_CUSTOMS) ;
select now();
\echo "PK_CUSTOMS_ESEAL_CONFIG on CUSTOMS_ESEAL_CONFIG (CUSTOMS_CODE, FLAG_TYPE, I_E_FLAG)"
create index PK_CUSTOMS_ESEAL_CONFIG on CUSTOMS_ESEAL_CONFIG (CUSTOMS_CODE, FLAG_TYPE, I_E_FLAG) ;
select now();
\echo "PK_CUS_GOOD_CONSUME on CUS_GOOD_CONSUME (REC_NUM)"
create index PK_CUS_GOOD_CONSUME on CUS_GOOD_CONSUME (REC_NUM) ;
select now();
\echo "PK_DCG_BAK_LIST on DCG_BAK_LIST (DCG_NO)"
create index PK_DCG_BAK_LIST on DCG_BAK_LIST (DCG_NO) ;
select now();
\echo "PK_DCG_BILL_HEAD on DCG_BILL_HEAD (BILL_NO)"
create index PK_DCG_BILL_HEAD on DCG_BILL_HEAD (BILL_NO) ;
select now();
\echo "PK_DCG_BILL_LIST on DCG_BILL_LIST (BILL_NO, G_TYPE, G_NO)"
create index PK_DCG_BILL_LIST on DCG_BILL_LIST (BILL_NO, G_TYPE, G_NO) ;
select now();
\echo "PK_DCG_COPR_INFO on DCG_COPR_INFO (CORP_NO)"
create index PK_DCG_COPR_INFO on DCG_COPR_INFO (CORP_NO) ;
select now();
\echo "PK_DCG_DEDUCT on DCG_DEDUCT (ENTRY_ID, DCG_NO, G_TYPE, ENTRY_G_NO)"
create index PK_DCG_DEDUCT on DCG_DEDUCT (ENTRY_ID, DCG_NO, G_TYPE, ENTRY_G_NO) ;
select now();
\echo "PK_DCG_DEDUCT_LOG on DCG_DEDUCT_LOG (ENTRY_ID, DCG_NO, CREATE_DATE, JOU_MARK)"
create index PK_DCG_DEDUCT_LOG on DCG_DEDUCT_LOG (ENTRY_ID, DCG_NO, CREATE_DATE, JOU_MARK) ;
select now();
\echo "PK_DCG_HEAD on DCG_HEAD (DCG_NO)"
create index PK_DCG_HEAD on DCG_HEAD (DCG_NO) ;
select now();
\echo "PK_DCG_LIST on DCG_LIST (DCG_NO, G_TYPE, G_NO)"
create index PK_DCG_LIST on DCG_LIST (DCG_NO, G_TYPE, G_NO) ;
select now();
\echo "PK_DCG_SEQ on DCG_SEQ (DCG_KEY)"
create index PK_DCG_SEQ on DCG_SEQ (DCG_KEY) ;
select now();
\echo "PK_DCG_WORKFLOW on DCG_WORKFLOW (DCG_NO, STEP_ID, CREATE_DATE)"
create index PK_DCG_WORKFLOW on DCG_WORKFLOW (DCG_NO, STEP_ID, CREATE_DATE) ;
select now();
\echo "PK_DECLARER_REL on DECLARER_REL (DECL_CO)"
create index PK_DECLARER_REL on DECLARER_REL (DECL_CO) ;
select now();
\echo "PK_DECLAR_COUNTER_REL on DECLAR_COUNTER_REL (DECL_KEY)"
create index PK_DECLAR_COUNTER_REL on DECLAR_COUNTER_REL (DECL_KEY) ;
select now();
\echo "PK_DECLAR_REL on DECLAR_REL (DECL_CO, CUSTOMS_CODE)"
create index PK_DECLAR_REL on DECLAR_REL (DECL_CO, CUSTOMS_CODE) ;
select now();
\echo "PK_DECLOG_FULL_REL on DECLOG_FULL_REL (LOG_ID)"
create index PK_DECLOG_FULL_REL on DECLOG_FULL_REL (LOG_ID) ;
select now();
\echo "PK_DECLOG_MODIFY_REL on DECLOG_MODIFY_REL (LOG_ID)"
create index PK_DECLOG_MODIFY_REL on DECLOG_MODIFY_REL (LOG_ID) ;
select now();
\echo "PK_DECLOG_MOD_REL on DECLOG_MOD_REL (DECL_CO, MOD_TIMES)"
create index PK_DECLOG_MOD_REL on DECLOG_MOD_REL (DECL_CO, MOD_TIMES) ;
select now();
\echo "PK_DECLOG_SCORE_HEAD on DECLOG_SCORE_HEAD (DECL_CO, FORM_ID, SCORE_TIME)"
create index PK_DECLOG_SCORE_HEAD on DECLOG_SCORE_HEAD (DECL_CO, FORM_ID, SCORE_TIME) ;
select now();
\echo "PK_DECLOG_SCORE_LIST on DECLOG_SCORE_LIST (DECL_CO, FORM_ID, SCORE_TIME, ITEM_NO)"
create index PK_DECLOG_SCORE_LIST on DECLOG_SCORE_LIST (DECL_CO, FORM_ID, SCORE_TIME, ITEM_NO) ;
select now();
\echo "PK_DECL_CO_ENTRY_COUNT on DECL_CO_ENTRY_COUNT (DECL_CO, RANDOM)"
create index PK_DECL_CO_ENTRY_COUNT on DECL_CO_ENTRY_COUNT (DECL_CO, RANDOM) ;
select now();
\echo "PK_DECL_CO_ENTRY_COUNT_TEMP on DECL_CO_ENTRY_COUNT_TEMP (GEN_DATE, DECL_CO, RANDOM)"
create index PK_DECL_CO_ENTRY_COUNT_TEMP on DECL_CO_ENTRY_COUNT_TEMP (GEN_DATE, DECL_CO, RANDOM) ;
select now();
\echo "PK_DEL_EGS_ARC_AGENT_LIST on DEL_EGS_ARC_AGENT_LIST (EGS_NO, AGENT_NO)"
create index PK_DEL_EGS_ARC_AGENT_LIST on DEL_EGS_ARC_AGENT_LIST (EGS_NO, AGENT_NO) ;
select now();
\echo "PK_DEL_EGS_ARC_HEAD on DEL_EGS_ARC_HEAD (EGS_NO)"
create index PK_DEL_EGS_ARC_HEAD on DEL_EGS_ARC_HEAD (EGS_NO) ;
select now();
\echo "PK_DEL_EGS_ARC_LIST on DEL_EGS_ARC_LIST (EGS_NO, G_NO)"
create index PK_DEL_EGS_ARC_LIST on DEL_EGS_ARC_LIST (EGS_NO, G_NO) ;
select now();
\echo "PK_DEL_EGS_ARC_MERCHANT_LIST on DEL_EGS_ARC_MERCHANT_LIST (EGS_NO, AGENT_CODE, MERCHANT_NO)"
create index PK_DEL_EGS_ARC_MERCHANT_LIST on DEL_EGS_ARC_MERCHANT_LIST (EGS_NO, AGENT_CODE, MERCHANT_NO) ;
select now();
\echo "PK_DEL_EGS_CLEAR_CERT on DEL_EGS_CLEAR_CERT (CLR_NO, CERT_CODE, CERT_NO)"
create index PK_DEL_EGS_CLEAR_CERT on DEL_EGS_CLEAR_CERT (CLR_NO, CERT_CODE, CERT_NO) ;
select now();
\echo "PK_DEL_EGS_CLEAR_HEAD on DEL_EGS_CLEAR_HEAD (CLR_NO)"
create index PK_DEL_EGS_CLEAR_HEAD on DEL_EGS_CLEAR_HEAD (CLR_NO) ;
select now();
\echo "PK_DEL_EGS_CLEAR_LIST on DEL_EGS_CLEAR_LIST (CLR_NO, G_NO)"
create index PK_DEL_EGS_CLEAR_LIST on DEL_EGS_CLEAR_LIST (CLR_NO, G_NO) ;
select now();
\echo "PK_DEL_EGS_DECLARE_CERT on DEL_EGS_DECLARE_CERT (DECL_NO, CERT_CODE, CERT_NO)"
create index PK_DEL_EGS_DECLARE_CERT on DEL_EGS_DECLARE_CERT (DECL_NO, CERT_CODE, CERT_NO) ;
select now();
\echo "PK_DEL_EGS_DECLARE_HEAD on DEL_EGS_DECLARE_HEAD (DECL_NO)"
create index PK_DEL_EGS_DECLARE_HEAD on DEL_EGS_DECLARE_HEAD (DECL_NO) ;
select now();
\echo "PK_DEL_EGS_DECLARE_LIST on DEL_EGS_DECLARE_LIST (DECL_NO, G_NO)"
create index PK_DEL_EGS_DECLARE_LIST on DEL_EGS_DECLARE_LIST (DECL_NO, G_NO) ;
select now();
\echo "PK_DEL_MOD_APPLY on DEL_MOD_APPLY (ENTRY_ID, APPLY_TIME)"
create index PK_DEL_MOD_APPLY on DEL_MOD_APPLY (ENTRY_ID, APPLY_TIME) ;
select now();
\echo "PK_DISTRIBUTIVE_BILL_DECLARE on DISTRIBUTIVE_BILL_DECLARE (DISTRIBUTIVE_NO, I_E_FLAG, CUSTOMS_CODE, TRAF_MODE, VOYAGE_NO, BILL_NO, SHIP_ID, I_E_DATE)"
create index PK_DISTRIBUTIVE_BILL_DECLARE on DISTRIBUTIVE_BILL_DECLARE (DISTRIBUTIVE_NO, I_E_FLAG, CUSTOMS_CODE, TRAF_MODE, VOYAGE_NO, BILL_NO, SHIP_ID, I_E_DATE) ;
select now();
\echo "PK_DISTRIBUTIVE_DECLARE on DISTRIBUTIVE_DECLARE (DISTRIBUTIVE_NO)"
create index PK_DISTRIBUTIVE_DECLARE on DISTRIBUTIVE_DECLARE (DISTRIBUTIVE_NO) ;
select now();
\echo "PK_DISTRIBUTIVE_TRANSIT_WAY on DISTRIBUTIVE_TRANSIT_WAY (DISTRIBUTIVE_NO, CONTA_ID)"
create index PK_DISTRIBUTIVE_TRANSIT_WAY on DISTRIBUTIVE_TRANSIT_WAY (DISTRIBUTIVE_NO, CONTA_ID) ;
select now();
\echo "PK_DST_COUNTER_TABLE on DST_COUNTER_TABLE (EMS_NO, COUNTER, SUB_COUNTER)"
create index PK_DST_COUNTER_TABLE on DST_COUNTER_TABLE (EMS_NO, COUNTER, SUB_COUNTER) ;
select now();
\echo "PK_DST_DEDUCT on DST_DEDUCT (PRE_NO, G_NO, ORIGIN_COUNTRY, ENTRY_ID, ENTRY_G_NO)"
create index PK_DST_DEDUCT on DST_DEDUCT (PRE_NO, G_NO, ORIGIN_COUNTRY, ENTRY_ID, ENTRY_G_NO) ;
select now();
\echo "PK_DST_EXG on DST_EXG (PRE_NO, G_NO, ORIGIN_COUNTRY)"
create index PK_DST_EXG on DST_EXG (PRE_NO, G_NO, ORIGIN_COUNTRY) ;
select now();
\echo "PK_DST_EXG_ORI_ENTRY on DST_EXG_ORI_ENTRY (PRE_NO, G_NO, ORIGIN_COUNTRY, ENTRY_ID, ENTRY_G_NO)"
create index PK_DST_EXG_ORI_ENTRY on DST_EXG_ORI_ENTRY (PRE_NO, G_NO, ORIGIN_COUNTRY, ENTRY_ID, ENTRY_G_NO) ;
select now();
\echo "PK_DST_HEAD on DST_HEAD (PRE_NO)"
create index PK_DST_HEAD on DST_HEAD (PRE_NO) ;
select now();
\echo "PK_DST_IMG on DST_IMG (PRE_NO, G_NO, ORIGIN_COUNTRY)"
create index PK_DST_IMG on DST_IMG (PRE_NO, G_NO, ORIGIN_COUNTRY) ;
select now();
\echo "PK_DST_IMG_ORI_ENTRY on DST_IMG_ORI_ENTRY (PRE_NO, G_NO, ORIGIN_COUNTRY, ENTRY_ID, ENTRY_G_NO)"
create index PK_DST_IMG_ORI_ENTRY on DST_IMG_ORI_ENTRY (PRE_NO, G_NO, ORIGIN_COUNTRY, ENTRY_ID, ENTRY_G_NO) ;
select now();
\echo "PK_DTT_COP_PARAM on DTT_COP_PARAM (CORP_CODE, CUSTOMS_CODE)"
create index PK_DTT_COP_PARAM on DTT_COP_PARAM (CORP_CODE, CUSTOMS_CODE) ;
select now();
\echo "PK_DUTYFORM_HEAD on DUTYFORM_HEAD (ENTRY_ID)"
create index PK_DUTYFORM_HEAD on DUTYFORM_HEAD (ENTRY_ID) ;
select now();
\echo "PK_DUTYFORM_LIST on DUTYFORM_LIST (ENTRY_ID, TAX_ID)"
create index PK_DUTYFORM_LIST on DUTYFORM_LIST (ENTRY_ID, TAX_ID) ;
select now();
\echo "PK_DUTY_CHECK_LOG on DUTY_CHECK_LOG (ENTRY_ID, TAX_ID, PROC_TIME)"
create index PK_DUTY_CHECK_LOG on DUTY_CHECK_LOG (ENTRY_ID, TAX_ID, PROC_TIME) ;
select now();
\echo "PK_ECO_HEAD on ECO_HEAD (CERTIFICATE_NO)"
create index PK_ECO_HEAD on ECO_HEAD (CERTIFICATE_NO) ;
select now();
\echo "PK_ECO_LIST on ECO_LIST (CERTIFICATE_NO, G_NO)"
create index PK_ECO_LIST on ECO_LIST (CERTIFICATE_NO, G_NO) ;
select now();
\echo "PK_ECO_PARTS on ECO_PARTS (CERTIFICATE_NO, G_NO, PART_SEQ)"
create index PK_ECO_PARTS on ECO_PARTS (CERTIFICATE_NO, G_NO, PART_SEQ) ;
select now();
\echo "PK_ECO_WORKFLOW on ECO_WORKFLOW (CERTIFICATE_NO, TRANSFER_NUM, PROCESS_STATUS, PROCESS_DATE)"
create index PK_ECO_WORKFLOW on ECO_WORKFLOW (CERTIFICATE_NO, TRANSFER_NUM, PROCESS_STATUS, PROCESS_DATE) ;
select now();
\echo "PK_EGS_ADMIT_HEAD on EGS_ADMIT_HEAD (ADM_NO)"
create index PK_EGS_ADMIT_HEAD on EGS_ADMIT_HEAD (ADM_NO) ;
select now();
\echo "PK_EGS_ADMIT_HS on EGS_ADMIT_HS (ADM_NO, CODE_TS)"
create index PK_EGS_ADMIT_HS on EGS_ADMIT_HS (ADM_NO, CODE_TS) ;
select now();
\echo "PK_EGS_ADMIT_LIST on EGS_ADMIT_LIST (ADM_NO, G_NO)"
create index PK_EGS_ADMIT_LIST on EGS_ADMIT_LIST (ADM_NO, G_NO) ;
select now();
\echo "PK_EGS_ARC_AGENT_LIST on EGS_ARC_AGENT_LIST (EGS_NO, AGENT_NO)"
create index PK_EGS_ARC_AGENT_LIST on EGS_ARC_AGENT_LIST (EGS_NO, AGENT_NO) ;
select now();
\echo "PK_EGS_ARC_HEAD on EGS_ARC_HEAD (EGS_NO)"
create index PK_EGS_ARC_HEAD on EGS_ARC_HEAD (EGS_NO) ;
select now();
\echo "PK_EGS_ARC_LIST on EGS_ARC_LIST (EGS_NO, G_NO)"
create index PK_EGS_ARC_LIST on EGS_ARC_LIST (EGS_NO, G_NO) ;
select now();
\echo "PK_EGS_ARC_MERCHANT_LIST on EGS_ARC_MERCHANT_LIST (EGS_NO, AGENT_CODE, MERCHANT_NO)"
create index PK_EGS_ARC_MERCHANT_LIST on EGS_ARC_MERCHANT_LIST (EGS_NO, AGENT_CODE, MERCHANT_NO) ;
select now();
\echo "PK_EGS_CHECK_LOG on EGS_CHECK_LOG (EGS_NO, CHK_TIMES, FORM_TYPE, G_NO)"
create index PK_EGS_CHECK_LOG on EGS_CHECK_LOG (EGS_NO, CHK_TIMES, FORM_TYPE, G_NO) ;
select now();
\echo "PK_EGS_CLEAR_CERT on EGS_CLEAR_CERT (CLR_NO, CERT_CODE, CERT_NO)"
create index PK_EGS_CLEAR_CERT on EGS_CLEAR_CERT (CLR_NO, CERT_CODE, CERT_NO) ;
select now();
\echo "PK_EGS_CLEAR_HEAD on EGS_CLEAR_HEAD (CLR_NO)"
create index PK_EGS_CLEAR_HEAD on EGS_CLEAR_HEAD (CLR_NO) ;
select now();
\echo "PK_EGS_CLEAR_LIST on EGS_CLEAR_LIST (CLR_NO, G_NO)"
create index PK_EGS_CLEAR_LIST on EGS_CLEAR_LIST (CLR_NO, G_NO) ;
select now();
\echo "PK_EGS_DECLARE_CERT on EGS_DECLARE_CERT (DECL_NO, CERT_CODE, CERT_NO)"
create index PK_EGS_DECLARE_CERT on EGS_DECLARE_CERT (DECL_NO, CERT_CODE, CERT_NO) ;
select now();
\echo "PK_EGS_DECLARE_HEAD on EGS_DECLARE_HEAD (DECL_NO)"
create index PK_EGS_DECLARE_HEAD on EGS_DECLARE_HEAD (DECL_NO) ;
select now();
\echo "PK_EGS_DECLARE_LIST on EGS_DECLARE_LIST (DECL_NO, G_NO)"
create index PK_EGS_DECLARE_LIST on EGS_DECLARE_LIST (DECL_NO, G_NO) ;
select now();
\echo "PK_EGS_DEDUCT on EGS_DEDUCT (DECL_NO, DECL_G_NO, CLR_NO, CLR_G_NO)"
create index PK_EGS_DEDUCT on EGS_DEDUCT (DECL_NO, DECL_G_NO, CLR_NO, CLR_G_NO) ;
select now();
\echo "PK_EGS_LEND_HEAD on EGS_LEND_HEAD (LEND_NO)"
create index PK_EGS_LEND_HEAD on EGS_LEND_HEAD (LEND_NO) ;
select now();
\echo "PK_EGS_LEND_LIST on EGS_LEND_LIST (LEND_NO, G_NO)"
create index PK_EGS_LEND_LIST on EGS_LEND_LIST (LEND_NO, G_NO) ;
select now();
\echo "PK_EGS_PATROL_HEAD on EGS_PATROL_HEAD (PAT_NO)"
create index PK_EGS_PATROL_HEAD on EGS_PATROL_HEAD (PAT_NO) ;
select now();
\echo "PK_EGS_PATROL_LIST on EGS_PATROL_LIST (PAT_NO, G_NO)"
create index PK_EGS_PATROL_LIST on EGS_PATROL_LIST (PAT_NO, G_NO) ;
select now();
\echo "PK_EGS_SEQ on EGS_SEQ (EGS_KEY)"
create index PK_EGS_SEQ on EGS_SEQ (EGS_KEY) ;
select now();
\echo "PK_EGS_WORKFLOW on EGS_WORKFLOW (EGS_NO, STEP_ID, CREATE_DATE)"
create index PK_EGS_WORKFLOW on EGS_WORKFLOW (EGS_NO, STEP_ID, CREATE_DATE) ;
select now();
\echo "PK_EMS_ACCOUNT on EMS_ACCOUNT (EMS_NO, ID_STAT)"
create index PK_EMS_ACCOUNT on EMS_ACCOUNT (EMS_NO, ID_STAT) ;
select now();
\echo "PK_EMS_APPR_HEAD on EMS_APPR_HEAD (APPR_NO, RECEIVE_TIMES)"
create index PK_EMS_APPR_HEAD on EMS_APPR_HEAD (APPR_NO, RECEIVE_TIMES) ;
select now();
\echo "PK_EMS_APPR_LIST on EMS_APPR_LIST (APPR_NO, G_TYPE, G_NO, RECEIVE_TIMES)"
create index PK_EMS_APPR_LIST on EMS_APPR_LIST (APPR_NO, G_TYPE, G_NO, RECEIVE_TIMES) ;
select now();
\echo "PK_EMS_CLAIM on EMS_CLAIM (GUARANTEE_NO)"
create index PK_EMS_CLAIM on EMS_CLAIM (GUARANTEE_NO) ;
select now();
\echo "PK_EMS_CLR_LIST on EMS_CLR_LIST (EMS_NO, DCR_TIMES, G_TYPE, G_NO, DU_CODE)"
create index PK_EMS_CLR_LIST on EMS_CLR_LIST (EMS_NO, DCR_TIMES, G_TYPE, G_NO, DU_CODE) ;
select now();
\echo "PK_EMS_CLR_TMP on EMS_CLR_TMP (EMS_NO, G_TYPE, G_NO)"
create index PK_EMS_CLR_TMP on EMS_CLR_TMP (EMS_NO, G_TYPE, G_NO) ;
select now();
\echo "PK_EMS_COMPLEX on EMS_COMPLEX (GOODS_TYPE, G_TYPE, CODE_TS, CLASSIFY)"
create index PK_EMS_COMPLEX on EMS_COMPLEX (GOODS_TYPE, G_TYPE, CODE_TS, CLASSIFY) ;
select now();
\echo "PK_EMS_COMPLEX2 on EMS_COMPLEX2 (ICODE_TS, ECODE_TS)"
create index PK_EMS_COMPLEX2 on EMS_COMPLEX2 (ICODE_TS, ECODE_TS) ;
select now();
\echo "PK_EMS_CONSUME on EMS_CONSUME (EMS_NO, EXG_NO, EXG_VERSION, IMG_NO)"
create index PK_EMS_CONSUME on EMS_CONSUME (EMS_NO, EXG_NO, EXG_VERSION, IMG_NO) ;
select now();
\echo "PK_EMS_CONSUME_CLR on EMS_CONSUME_CLR (EMS_NO, IMG_NO)"
create index PK_EMS_CONSUME_CLR on EMS_CONSUME_CLR (EMS_NO, IMG_NO) ;
select now();
\echo "PK_EMS_CONSUME_CLR_D on EMS_CONSUME_CLR_D (EMS_NO, IMG_NO, EXG_NO, EXG_VERSION)"
create index PK_EMS_CONSUME_CLR_D on EMS_CONSUME_CLR_D (EMS_NO, IMG_NO, EXG_NO, EXG_VERSION) ;
select now();
\echo "PK_EMS_DCR_CONSUME on EMS_DCR_CONSUME (EMS_NO, EXG_NO, EXG_VERSION, IMG_NO, MODIFY_TIMES)"
create index PK_EMS_DCR_CONSUME on EMS_DCR_CONSUME (EMS_NO, EXG_NO, EXG_VERSION, IMG_NO, MODIFY_TIMES) ;
select now();
\echo "PK_EMS_DCR_ENT on EMS_DCR_ENT (EMS_NO, DCR_TIMES, ENTRY_ID)"
create index PK_EMS_DCR_ENT on EMS_DCR_ENT (EMS_NO, DCR_TIMES, ENTRY_ID) ;
select now();
\echo "PK_EMS_DCR_HEAD on EMS_DCR_HEAD (EMS_NO, DCR_TIMES)"
create index PK_EMS_DCR_HEAD on EMS_DCR_HEAD (EMS_NO, DCR_TIMES) ;
select now();
\echo "PK_EMS_DCR_LIST on EMS_DCR_LIST (EMS_NO, DCR_TIMES, G_TYPE, G_NO)"
create index PK_EMS_DCR_LIST on EMS_DCR_LIST (EMS_NO, DCR_TIMES, G_TYPE, G_NO) ;
select now();
\echo "PK_EMS_DCR_RUB_LIST on EMS_DCR_RUB_LIST (EMS_NO, DCR_TIMES, G_TYPE, G_NO)"
create index PK_EMS_DCR_RUB_LIST on EMS_DCR_RUB_LIST (EMS_NO, DCR_TIMES, G_TYPE, G_NO) ;
select now();
\echo "PK_EMS_DEDUCT on EMS_DEDUCT (ENTRY_ID, EMS_NO, G_TYPE, ENTRY_G_NO)"
create index PK_EMS_DEDUCT on EMS_DEDUCT (ENTRY_ID, EMS_NO, G_TYPE, ENTRY_G_NO) ;
select now();
\echo "PK_EMS_DEDUCT_CLR on EMS_DEDUCT_CLR (EMS_NO, IMG_NO, ENTRY_ID, ENTRY_G_NO)"
create index PK_EMS_DEDUCT_CLR on EMS_DEDUCT_CLR (EMS_NO, IMG_NO, ENTRY_ID, ENTRY_G_NO) ;
select now();
\echo "PK_EMS_DEDUCT_LOG on EMS_DEDUCT_LOG (ENTRY_ID, EMS_NO, CREATE_DATE, JOU_MARK)"
create index PK_EMS_DEDUCT_LOG on EMS_DEDUCT_LOG (ENTRY_ID, EMS_NO, CREATE_DATE, JOU_MARK) ;
select now();
\echo "PK_EMS_ENP on EMS_ENP (ENP_ID)"
create index PK_EMS_ENP on EMS_ENP (ENP_ID) ;
select now();
\echo "PK_EMS_ENP_JOU on EMS_ENP_JOU (ENP_ID, ENP_SEQ, ENP_NO)"
create index PK_EMS_ENP_JOU on EMS_ENP_JOU (ENP_ID, ENP_SEQ, ENP_NO) ;
select now();
\echo "PK_EMS_HEAD on EMS_HEAD (EMS_NO)"
create index PK_EMS_HEAD on EMS_HEAD (EMS_NO) ;
select now();
\echo "PK_EMS_LIST on EMS_LIST (EMS_NO, G_TYPE, G_NO)"
create index PK_EMS_LIST on EMS_LIST (EMS_NO, G_TYPE, G_NO) ;
select now();
\echo "PK_EMS_MESSAGE_LOG on EMS_MESSAGE_LOG (EMS_NO, SEND_CUSTOMS, CUSTOMS_CODE, H2000_RECEIVE_DATE)"
create index PK_EMS_MESSAGE_LOG on EMS_MESSAGE_LOG (EMS_NO, SEND_CUSTOMS, CUSTOMS_CODE, H2000_RECEIVE_DATE) ;
select now();
\echo "PK_EMS_PRESS on EMS_PRESS (PARA_TYPE, PARA_NAME)"
create index PK_EMS_PRESS on EMS_PRESS (PARA_TYPE, PARA_NAME) ;
select now();
\echo "PK_EMS_PRESS_CLEAR on EMS_PRESS_CLEAR (EMS_NO, PR_NO)"
create index PK_EMS_PRESS_CLEAR on EMS_PRESS_CLEAR (EMS_NO, PR_NO) ;
select now();
\echo "PK_EMS_SEQ on EMS_SEQ (EMS_KEY)"
create index PK_EMS_SEQ on EMS_SEQ (EMS_KEY) ;
select now();
\echo "PK_EMS_TMP_CLR on EMS_TMP_CLR (EMS_NO, G_TYPE, G_NO)"
create index PK_EMS_TMP_CLR on EMS_TMP_CLR (EMS_NO, G_TYPE, G_NO) ;
select now();
\echo "PK_EMS_VAR on EMS_VAR (VAR_TYPE, VAR_ID, VAR_SUB_ID, CUSTOMS_CODE)"
create index PK_EMS_VAR on EMS_VAR (VAR_TYPE, VAR_ID, VAR_SUB_ID, CUSTOMS_CODE) ;
select now();
\echo "PK_EMS_VERIFY on EMS_VERIFY (EMS_NO, G_TYPE, G_NO)"
create index PK_EMS_VERIFY on EMS_VERIFY (EMS_NO, G_TYPE, G_NO) ;
select now();
\echo "PK_EMS_VERIFY_DETAIL on EMS_VERIFY_DETAIL (EMS_NO, G_TYPE, G_NO, D_TYPE, E_TYPE)"
create index PK_EMS_VERIFY_DETAIL on EMS_VERIFY_DETAIL (EMS_NO, G_TYPE, G_NO, D_TYPE, E_TYPE) ;
select now();
\echo "PK_EMS_WORKFLOW on EMS_WORKFLOW (EMS_NO, STEP_ID, CREATE_DATE)"
create index PK_EMS_WORKFLOW on EMS_WORKFLOW (EMS_NO, STEP_ID, CREATE_DATE) ;
select now();
\echo "PK_ENTRY_AUTOREL_ERR_LIST on ENTRY_AUTOREL_ERR_LIST (ENTRY_ID)"
create index PK_ENTRY_AUTOREL_ERR_LIST on ENTRY_AUTOREL_ERR_LIST (ENTRY_ID) ;
select now();
\echo "PK_ENTRY_AUTOREL_ERR_LOG on ENTRY_AUTOREL_ERR_LOG (ENTRY_ID, DEL_TIME)"
create index PK_ENTRY_AUTOREL_ERR_LOG on ENTRY_AUTOREL_ERR_LOG (ENTRY_ID, DEL_TIME) ;
select now();
\echo "PK_ENTRY_CENTRY_SELECT on ENTRY_CENTRY_SELECT (ENTRY_ID)"
create index PK_ENTRY_CENTRY_SELECT on ENTRY_CENTRY_SELECT (ENTRY_ID) ;
select now();
\echo "PK_ENTRY_CENTRY_SELECT_DEL on ENTRY_CENTRY_SELECT_DEL (ENTRY_ID, OP_TIME)"
create index PK_ENTRY_CENTRY_SELECT_DEL on ENTRY_CENTRY_SELECT_DEL (ENTRY_ID, OP_TIME) ;
select now();
\echo "PK_ENTRY_CERTIFICATE on ENTRY_CERTIFICATE (ENTRY_ID, DOCU_CODE, CERT_CODE)"
create index PK_ENTRY_CERTIFICATE on ENTRY_CERTIFICATE (ENTRY_ID, DOCU_CODE, CERT_CODE) ;
select now();
\echo "PK_ENTRY_CERTIFICATE_LOG on ENTRY_CERTIFICATE_LOG (ENTRY_ID, DOCU_CODE, CERT_CODE, OP_TIME)"
create index PK_ENTRY_CERTIFICATE_LOG on ENTRY_CERTIFICATE_LOG (ENTRY_ID, DOCU_CODE, CERT_CODE, OP_TIME) ;
select now();
\echo "PK_ENTRY_CONTAINER on ENTRY_CONTAINER (ENTRY_ID, CONTAINER_ID)"
create index PK_ENTRY_CONTAINER on ENTRY_CONTAINER (ENTRY_ID, CONTAINER_ID) ;
select now();
\echo "PK_ENTRY_CONTAINER_LOG on ENTRY_CONTAINER_LOG (ENTRY_ID, CONTAINER_ID, OP_TIME)"
create index PK_ENTRY_CONTAINER_LOG on ENTRY_CONTAINER_LOG (ENTRY_ID, CONTAINER_ID, OP_TIME) ;
select now();
\echo "PK_ENTRY_DEL_HEAD_LOG on ENTRY_DEL_HEAD_LOG (ENTRY_ID, OP_TIME)"
create index PK_ENTRY_DEL_HEAD_LOG on ENTRY_DEL_HEAD_LOG (ENTRY_ID, OP_TIME) ;
select now();
\echo "PK_ENTRY_DEL_LIST_LOG on ENTRY_DEL_LIST_LOG (ENTRY_ID, G_NO, OP_TIME)"
create index PK_ENTRY_DEL_LIST_LOG on ENTRY_DEL_LIST_LOG (ENTRY_ID, G_NO, OP_TIME) ;
select now();
\echo "PK_ENTRY_EVALUATION on ENTRY_EVALUATION (ENTRY_ID, G_NO)"
create index PK_ENTRY_EVALUATION on ENTRY_EVALUATION (ENTRY_ID, G_NO) ;
select now();
\echo "PK_ENTRY_GPM_RTX on ENTRY_GPM_RTX (SIGN_TYPE, ENTRY_ID, PROC_MODE)"
create index PK_ENTRY_GPM_RTX on ENTRY_GPM_RTX (SIGN_TYPE, ENTRY_ID, PROC_MODE) ;
select now();
\echo "PK_ENTRY_GPM_RTX_PRINTLOG on ENTRY_GPM_RTX_PRINTLOG (ENTRY_ID, PRINT_TYPE, PRINT_DATE)"
create index PK_ENTRY_GPM_RTX_PRINTLOG on ENTRY_GPM_RTX_PRINTLOG (ENTRY_ID, PRINT_TYPE, PRINT_DATE) ;
select now();
\echo "PK_ENTRY_GPM_RTX_SENDLOG on ENTRY_GPM_RTX_SENDLOG (ENTRY_ID, SIGN_TYPE, PROC_MODE, SEND_DATE)"
create index PK_ENTRY_GPM_RTX_SENDLOG on ENTRY_GPM_RTX_SENDLOG (ENTRY_ID, SIGN_TYPE, PROC_MODE, SEND_DATE) ;
select now();
\echo "PK_ENTRY_HEAD on ENTRY_HEAD (ENTRY_ID, DECL_PORT)"
create index PK_ENTRY_HEAD on ENTRY_HEAD (ENTRY_ID, DECL_PORT) ;
select now();
\echo "PK_ENTRY_LIST on ENTRY_LIST (ENTRY_ID, G_NO)"
create index PK_ENTRY_LIST on ENTRY_LIST (ENTRY_ID, G_NO) ;
select now();
\echo "PK_ENTRY_MODI_LOG on ENTRY_MODI_LOG (ENTRY_ID, OP_TIME, MODI_TYPE, ITEM_NAME)"
create index PK_ENTRY_MODI_LOG on ENTRY_MODI_LOG (ENTRY_ID, OP_TIME, MODI_TYPE, ITEM_NAME) ;
select now();
\echo "PK_ENTRY_OP_LOG on ENTRY_OP_LOG (ENTRY_ID, OP_TIME)"
create index PK_ENTRY_OP_LOG on ENTRY_OP_LOG (ENTRY_ID, OP_TIME) ;
select now();
\echo "PK_ENTRY_PROC on ENTRY_PROC (ENTRY_ID, DECL_PORT)"
create index PK_ENTRY_PROC on ENTRY_PROC (ENTRY_ID, DECL_PORT) ;
select now();
\echo "PK_ENTRY_PROC_LOG on ENTRY_PROC_LOG (ENTRY_ID, OP_TIME, OP_STEP)"
create index PK_ENTRY_PROC_LOG on ENTRY_PROC_LOG (ENTRY_ID, OP_TIME, OP_STEP) ;
select now();
\echo "PK_ENTRY_QUERY on ENTRY_QUERY (ENTRY_ID, G_NO)"
create index PK_ENTRY_QUERY on ENTRY_QUERY (ENTRY_ID, G_NO) ;
select now();
\echo "PK_ENTRY_WORKFLOW on ENTRY_WORKFLOW (ENTRY_ID, STEP_ID, CREATE_DATE)"
create index PK_ENTRY_WORKFLOW on ENTRY_WORKFLOW (ENTRY_ID, STEP_ID, CREATE_DATE) ;
select now();
\echo "PK_EPA_CHEM_CERT on EPA_CHEM_CERT (CERTIFICATE_NO)"
create index PK_EPA_CHEM_CERT on EPA_CHEM_CERT (CERTIFICATE_NO) ;
select now();
\echo "PK_EPA_CHK on EPA_CHK (ENTRY_ID, CERTIFICATE_NO, CERT_TYPE)"
create index PK_EPA_CHK on EPA_CHK (ENTRY_ID, CERTIFICATE_NO, CERT_TYPE) ;
select now();
\echo "PK_EPA_SCARP_CERT on EPA_SCARP_CERT (CERTIFICATE_NO)"
create index PK_EPA_SCARP_CERT on EPA_SCARP_CERT (CERTIFICATE_NO) ;
select now();
\echo "PK_ERR_LOG on ERR_LOG (ENTRY_ID, CREATE_DATE)"
create index PK_ERR_LOG on ERR_LOG (ENTRY_ID, CREATE_DATE) ;
select now();
\echo "PK_EXAM_CONTA_END_LOG on EXAM_CONTA_END_LOG (EXAM_REC_ID, END_TIME)"
create index PK_EXAM_CONTA_END_LOG on EXAM_CONTA_END_LOG (EXAM_REC_ID, END_TIME) ;
select now();
\echo "PK_EXAM_CONTA_HEAD on EXAM_CONTA_HEAD (EXAM_REC_ID)"
create index PK_EXAM_CONTA_HEAD on EXAM_CONTA_HEAD (EXAM_REC_ID) ;
select now();
\echo "PK_EXAM_CONTA_LIST on EXAM_CONTA_LIST (EXAM_REC_ID, CONTA_ID)"
create index PK_EXAM_CONTA_LIST on EXAM_CONTA_LIST (EXAM_REC_ID, CONTA_ID) ;
select now();
\echo "PK_EXA_APPL_CLOSE on EXA_APPL_CLOSE (MANUAL_NO, CONTR_ITEM)"
create index PK_EXA_APPL_CLOSE on EXA_APPL_CLOSE (MANUAL_NO, CONTR_ITEM) ;
select now();
\echo "PK_EXC_ELE on EXC_ELE (HXD_NO)"
create index PK_EXC_ELE on EXC_ELE (HXD_NO) ;
select now();
\echo "PK_EXC_EXAM on EXC_EXAM (HXD_NO)"
create index PK_EXC_EXAM on EXC_EXAM (HXD_NO) ;
select now();
\echo "PK_EXC_EX_CHK on EXC_EX_CHK (HXD_NO)"
create index PK_EXC_EX_CHK on EXC_EX_CHK (HXD_NO) ;
select now();
\echo "PK_EXP_MFT_CHK_RESULT on EXP_MFT_CHK_RESULT (VOYAGE_NO, CUSTOMS_CODE)"
create index PK_EXP_MFT_CHK_RESULT on EXP_MFT_CHK_RESULT (VOYAGE_NO, CUSTOMS_CODE) ;
select now();
\echo "PK_EXTERNAL_JOU on EXTERNAL_JOU (MANUAL_NO, CUSTOMS_CODE, APPL_NO)"
create index PK_EXTERNAL_JOU on EXTERNAL_JOU (MANUAL_NO, CUSTOMS_CODE, APPL_NO) ;
select now();
\echo "PK_EX_APPL_CLOSE on EX_APPL_CLOSE (MANUAL_NO, CONTR_ITEM)"
create index PK_EX_APPL_CLOSE on EX_APPL_CLOSE (MANUAL_NO, CONTR_ITEM) ;
select now();
\echo "PK_EX_ARRIVAL_CONTA on EX_ARRIVAL_CONTA (CONTA_ID, BILL_NO, REC_NO)"
create index PK_EX_ARRIVAL_CONTA on EX_ARRIVAL_CONTA (CONTA_ID, BILL_NO, REC_NO) ;
select now();
\echo "PK_EX_ARRIVAL_ERR_CHK on EX_ARRIVAL_ERR_CHK (ENTRY_ID, CHK_DATE)"
create index PK_EX_ARRIVAL_ERR_CHK on EX_ARRIVAL_ERR_CHK (ENTRY_ID, CHK_DATE) ;
select now();
\echo "PK_EX_ARRIVAL_SHIP on EX_ARRIVAL_SHIP (VOYAGE_NO, SHIP_NAME_EN, CUSTOMS_CODE, SHIP_ID)"
create index PK_EX_ARRIVAL_SHIP on EX_ARRIVAL_SHIP (VOYAGE_NO, SHIP_NAME_EN, CUSTOMS_CODE, SHIP_ID) ;
select now();
\echo "PK_EX_CDL_MNL_DEDUCT on EX_CDL_MNL_DEDUCT (MANUAL_NO, ENTRY_ID, G_NO)"
create index PK_EX_CDL_MNL_DEDUCT on EX_CDL_MNL_DEDUCT (MANUAL_NO, ENTRY_ID, G_NO) ;
select now();
\echo "PK_EX_CONTA_ENTRY_CHK on EX_CONTA_ENTRY_CHK (CONTA_ID, BILL_NO, REC_NO, ENTRY_ID)"
create index PK_EX_CONTA_ENTRY_CHK on EX_CONTA_ENTRY_CHK (CONTA_ID, BILL_NO, REC_NO, ENTRY_ID) ;
select now();
\echo "PK_EX_CONTRACT_CLEAR on EX_CONTRACT_CLEAR (MANUAL_NO, CONTR_ITEM)"
create index PK_EX_CONTRACT_CLEAR on EX_CONTRACT_CLEAR (MANUAL_NO, CONTR_ITEM) ;
select now();
\echo "PK_EX_CONTRACT_DEDUC on EX_CONTRACT_DEDUC (MANUAL_NO, ENTRY_ID, G_NO)"
create index PK_EX_CONTRACT_DEDUC on EX_CONTRACT_DEDUC (MANUAL_NO, ENTRY_ID, G_NO) ;
select now();
\echo "PK_EX_CONTRACT_LIST on EX_CONTRACT_LIST (MANUAL_NO, CONTR_ITEM)"
create index PK_EX_CONTRACT_LIST on EX_CONTRACT_LIST (MANUAL_NO, CONTR_ITEM) ;
select now();
\echo "PK_EX_COP_RATE on EX_COP_RATE (TRADE_CO, CHKSTDATE, CHKENDDATE)"
create index PK_EX_COP_RATE on EX_COP_RATE (TRADE_CO, CHKSTDATE, CHKENDDATE) ;
select now();
\echo "PK_EX_DECL_ALARM_HEAD on EX_DECL_ALARM_HEAD (PRE_NO)"
create index PK_EX_DECL_ALARM_HEAD on EX_DECL_ALARM_HEAD (PRE_NO) ;
select now();
\echo "PK_EX_DECL_ALARM_LIST on EX_DECL_ALARM_LIST (PRE_NO, RECORD_NUMBER, G_NO)"
create index PK_EX_DECL_ALARM_LIST on EX_DECL_ALARM_LIST (PRE_NO, RECORD_NUMBER, G_NO) ;
select now();
\echo "PK_EX_DECL_CUR_HEAD on EX_DECL_CUR_HEAD (PRE_NO)"
create index PK_EX_DECL_CUR_HEAD on EX_DECL_CUR_HEAD (PRE_NO) ;
select now();
\echo "PK_EX_DECL_CUR_LIST on EX_DECL_CUR_LIST (PRE_NO, RECORD_NUMBER, G_NO)"
create index PK_EX_DECL_CUR_LIST on EX_DECL_CUR_LIST (PRE_NO, RECORD_NUMBER, G_NO) ;
select now();
\echo "PK_EX_DECL_HIS_HEAD on EX_DECL_HIS_HEAD (PRE_NO)"
create index PK_EX_DECL_HIS_HEAD on EX_DECL_HIS_HEAD (PRE_NO) ;
select now();
\echo "PK_EX_DECL_HIS_LIST on EX_DECL_HIS_LIST (PRE_NO, RECORD_NUMBER, G_NO)"
create index PK_EX_DECL_HIS_LIST on EX_DECL_HIS_LIST (PRE_NO, RECORD_NUMBER, G_NO) ;
select now();
\echo "PK_EX_ELE_HEAD on EX_ELE_HEAD (LICENSE_NO)"
create index PK_EX_ELE_HEAD on EX_ELE_HEAD (LICENSE_NO) ;
select now();
\echo "PK_EX_ELE_LIST on EX_ELE_LIST (LICENSE_NO, L_G_NO)"
create index PK_EX_ELE_LIST on EX_ELE_LIST (LICENSE_NO, L_G_NO) ;
select now();
\echo "PK_EX_EXAM_JOU on EX_EXAM_JOU (ENTRY_ID, G_NO)"
create index PK_EX_EXAM_JOU on EX_EXAM_JOU (ENTRY_ID, G_NO) ;
select now();
\echo "PK_EX_EXAM_MANA_HEAD on EX_EXAM_MANA_HEAD (LICENSE_NO)"
create index PK_EX_EXAM_MANA_HEAD on EX_EXAM_MANA_HEAD (LICENSE_NO) ;
select now();
\echo "PK_EX_EXAM_MANA_LIST on EX_EXAM_MANA_LIST (LICENSE_NO, L_G_NO)"
create index PK_EX_EXAM_MANA_LIST on EX_EXAM_MANA_LIST (LICENSE_NO, L_G_NO) ;
select now();
\echo "PK_EX_FASCICLE_LIST on EX_FASCICLE_LIST (FASCICLE_NO, CONTR_ITEM)"
create index PK_EX_FASCICLE_LIST on EX_FASCICLE_LIST (FASCICLE_NO, CONTR_ITEM) ;
select now();
\echo "PK_EX_LIC_CODE_TS on EX_LIC_CODE_TS (LICENSE_NO)"
create index PK_EX_LIC_CODE_TS on EX_LIC_CODE_TS (LICENSE_NO) ;
select now();
\echo "PK_EX_TRANS_ALARM_CONTA_REL on EX_TRANS_ALARM_CONTA_REL (PRE_NO, RECORD_NUMBER, CONTA_NO)"
create index PK_EX_TRANS_ALARM_CONTA_REL on EX_TRANS_ALARM_CONTA_REL (PRE_NO, RECORD_NUMBER, CONTA_NO) ;
select now();
\echo "PK_EX_TRANS_ALARM_GOODS_CONTA_REL on EX_TRANS_ALARM_GOODS_CONTA_REL (PRE_NO, RECORD_NUMBER, G_NO, CONTA_NO)"
create index PK_EX_TRANS_ALARM_GOODS_CONTA_REL on EX_TRANS_ALARM_GOODS_CONTA_REL (PRE_NO, RECORD_NUMBER, G_NO, CONTA_NO) ;
select now();
\echo "PK_EX_TRANS_ALARM_LIST_REL on EX_TRANS_ALARM_LIST_REL (PRE_NO, RECORD_NUMBER)"
create index PK_EX_TRANS_ALARM_LIST_REL on EX_TRANS_ALARM_LIST_REL (PRE_NO, RECORD_NUMBER) ;
select now();
\echo "PK_EX_TRANS_CONTA_REL on EX_TRANS_CONTA_REL (PRE_NO, RECORD_NUMBER, CONTA_NO)"
create index PK_EX_TRANS_CONTA_REL on EX_TRANS_CONTA_REL (PRE_NO, RECORD_NUMBER, CONTA_NO) ;
select now();
\echo "PK_EX_TRANS_GOODS_CONTA_REL on EX_TRANS_GOODS_CONTA_REL (PRE_NO, RECORD_NUMBER, G_NO, CONTA_NO)"
create index PK_EX_TRANS_GOODS_CONTA_REL on EX_TRANS_GOODS_CONTA_REL (PRE_NO, RECORD_NUMBER, G_NO, CONTA_NO) ;
select now();
\echo "PK_EX_TRANS_HIS_CONTA_REL on EX_TRANS_HIS_CONTA_REL (PRE_NO, RECORD_NUMBER, CONTA_NO)"
create index PK_EX_TRANS_HIS_CONTA_REL on EX_TRANS_HIS_CONTA_REL (PRE_NO, RECORD_NUMBER, CONTA_NO) ;
select now();
\echo "PK_EX_TRANS_HIS_GOODS_CONTA_REL on EX_TRANS_HIS_GOODS_CONTA_REL (PRE_NO, RECORD_NUMBER, G_NO, CONTA_NO)"
create index PK_EX_TRANS_HIS_GOODS_CONTA_REL on EX_TRANS_HIS_GOODS_CONTA_REL (PRE_NO, RECORD_NUMBER, G_NO, CONTA_NO) ;
select now();
\echo "PK_EX_TRANS_HIS_LIST_REL on EX_TRANS_HIS_LIST_REL (PRE_NO, RECORD_NUMBER)"
create index PK_EX_TRANS_HIS_LIST_REL on EX_TRANS_HIS_LIST_REL (PRE_NO, RECORD_NUMBER) ;
select now();
\echo "PK_EX_TRANS_LIST_REL on EX_TRANS_LIST_REL (PRE_NO, RECORD_NUMBER)"
create index PK_EX_TRANS_LIST_REL on EX_TRANS_LIST_REL (PRE_NO, RECORD_NUMBER) ;
select now();
\echo "PK_EX_TRAN_JOU on EX_TRAN_JOU (ENTRY_ID, G_NO)"
create index PK_EX_TRAN_JOU on EX_TRAN_JOU (ENTRY_ID, G_NO) ;
select now();
\echo "PK_EX_TRN_ARRIVAL_CONTA on EX_TRN_ARRIVAL_CONTA (ARRIVE_NO, CONTA_ID)"
create index PK_EX_TRN_ARRIVAL_CONTA on EX_TRN_ARRIVAL_CONTA (ARRIVE_NO, CONTA_ID) ;
select now();
\echo "PK_EX_TRN_CONTA_ENTRY_ARV on EX_TRN_CONTA_ENTRY_ARV (ENTRY_ID, CONTA_ID)"
create index PK_EX_TRN_CONTA_ENTRY_ARV on EX_TRN_CONTA_ENTRY_ARV (ENTRY_ID, CONTA_ID) ;
select now();
\echo "PK_EX_TRN_CONTA_ENTRY_CHK on EX_TRN_CONTA_ENTRY_CHK (ENTRY_ID, ARRIVE_NO, CONTA_ID)"
create index PK_EX_TRN_CONTA_ENTRY_CHK on EX_TRN_CONTA_ENTRY_CHK (ENTRY_ID, ARRIVE_NO, CONTA_ID) ;
select now();
\echo "PK_FASCICLE_HEAD on FASCICLE_HEAD (FASCICLE_NO)"
create index PK_FASCICLE_HEAD on FASCICLE_HEAD (FASCICLE_NO) ;
select now();
\echo "PK_FCB_CHK on FCB_CHK (FCB_ID, FORM_FLAG, ENTRY_ID)"
create index PK_FCB_CHK on FCB_CHK (FCB_ID, FORM_FLAG, ENTRY_ID) ;
select now();
\echo "PK_FCB_CONTA on FCB_CONTA (FCB_ID, CONTA_ID)"
create index PK_FCB_CONTA on FCB_CONTA (FCB_ID, CONTA_ID) ;
select now();
\echo "PK_FCB_CONTA_MODI on FCB_CONTA_MODI (FCB_ID, CONTA_ID)"
create index PK_FCB_CONTA_MODI on FCB_CONTA_MODI (FCB_ID, CONTA_ID) ;
select now();
\echo "PK_FCB_HEAD on FCB_HEAD (FCB_ID)"
create index PK_FCB_HEAD on FCB_HEAD (FCB_ID) ;
select now();
\echo "PK_FCB_HEAD_MODI on FCB_HEAD_MODI (FCB_ID)"
create index PK_FCB_HEAD_MODI on FCB_HEAD_MODI (FCB_ID) ;
select now();
\echo "PK_FCB_LIST on FCB_LIST (FCB_ID, G_NO)"
create index PK_FCB_LIST on FCB_LIST (FCB_ID, G_NO) ;
select now();
\echo "PK_FCB_LIST_MODI on FCB_LIST_MODI (FCB_ID, G_NO)"
create index PK_FCB_LIST_MODI on FCB_LIST_MODI (FCB_ID, G_NO) ;
select now();
\echo "PK_FCB_RSK on FCB_RSK (FCB_ID, CUSTOMS_CODE)"
create index PK_FCB_RSK on FCB_RSK (FCB_ID, CUSTOMS_CODE) ;
select now();
\echo "PK_FCB_WORKFLOW on FCB_WORKFLOW (FCB_ID, STEP_ID, CREATE_DATE)"
create index PK_FCB_WORKFLOW on FCB_WORKFLOW (FCB_ID, STEP_ID, CREATE_DATE) ;
select now();
\echo "PK_FEE_INVOICE on FEE_INVOICE (MANUAL_NO, F_NO)"
create index PK_FEE_INVOICE on FEE_INVOICE (MANUAL_NO, F_NO) ;
select now();
\echo "PK_FORFEIT_FORM on FORFEIT_FORM (FMS_ID)"
create index PK_FORFEIT_FORM on FORFEIT_FORM (FMS_ID) ;
select now();
\echo "PK_FORM_CHK on FORM_CHK (FORM_ID)"
create index PK_FORM_CHK on FORM_CHK (FORM_ID) ;
select now();
\echo "PK_GUARANTEE_DEL_LOG on GUARANTEE_DEL_LOG (GUA_ID, DEL_DATETIME)"
create index PK_GUARANTEE_DEL_LOG on GUARANTEE_DEL_LOG (GUA_ID, DEL_DATETIME) ;
select now();
\echo "PK_GUARANTEE_LIST on GUARANTEE_LIST (ENTRY_ID, G_NO, TAX_TYPE)"
create index PK_GUARANTEE_LIST on GUARANTEE_LIST (ENTRY_ID, G_NO, TAX_TYPE) ;
select now();
\echo "PK_GUARANTEE_R on GUARANTEE_R (GUA_ID)"
create index PK_GUARANTEE_R on GUARANTEE_R (GUA_ID) ;
select now();
\echo "PK_H2000_SMS_SEND on H2000_SMS_SEND (SEQUENCE_NO, FORM_ID, SYSTEM_ID, POS_ID, OP_TIME, PHONE_NO)"
create index PK_H2000_SMS_SEND on H2000_SMS_SEND (SEQUENCE_NO, FORM_ID, SYSTEM_ID, POS_ID, OP_TIME, PHONE_NO) ;
select now();
\echo "PK_H2000_SMS_SENDLOG on H2000_SMS_SENDLOG (SEQUENCE_NO, FORM_ID, SYSTEM_ID, POS_ID, OP_TIME, PHONE_NO)"
create index PK_H2000_SMS_SENDLOG on H2000_SMS_SENDLOG (SEQUENCE_NO, FORM_ID, SYSTEM_ID, POS_ID, OP_TIME, PHONE_NO) ;
select now();
\echo "PK_HIS_TRN_COP_REL on HIS_TRN_COP_REL (CO_REG_NO, MODI_COUNT)"
create index PK_HIS_TRN_COP_REL on HIS_TRN_COP_REL (CO_REG_NO, MODI_COUNT) ;
select now();
\echo "PK_HIS_TRN_DR_REL on HIS_TRN_DR_REL (DR_CUSTOMS_NO, MODI_COUNT)"
create index PK_HIS_TRN_DR_REL on HIS_TRN_DR_REL (DR_CUSTOMS_NO, MODI_COUNT) ;
select now();
\echo "PK_HIS_TRN_ESEAL_REL on HIS_TRN_ESEAL_REL (ESEAL_ID, MODI_TIME)"
create index PK_HIS_TRN_ESEAL_REL on HIS_TRN_ESEAL_REL (ESEAL_ID, MODI_TIME) ;
select now();
\echo "PK_HIS_TRN_VE_REL on HIS_TRN_VE_REL (VE_CUSTOMS_NO, MODI_COUNT)"
create index PK_HIS_TRN_VE_REL on HIS_TRN_VE_REL (VE_CUSTOMS_NO, MODI_COUNT) ;
select now();
\echo "PK_IMA_APPL_CLOSE on IMA_APPL_CLOSE (MANUAL_NO, CONTR_ITEM)"
create index PK_IMA_APPL_CLOSE on IMA_APPL_CLOSE (MANUAL_NO, CONTR_ITEM) ;
select now();
\echo "PK_IM_APPL_CLOSE on IM_APPL_CLOSE (MANUAL_NO, CONTR_ITEM)"
create index PK_IM_APPL_CLOSE on IM_APPL_CLOSE (MANUAL_NO, CONTR_ITEM) ;
select now();
\echo "PK_IM_CDL_MNL_DEDUCT on IM_CDL_MNL_DEDUCT (MANUAL_NO, ENTRY_ID, G_NO)"
create index PK_IM_CDL_MNL_DEDUCT on IM_CDL_MNL_DEDUCT (MANUAL_NO, ENTRY_ID, G_NO) ;
select now();
\echo "PK_IM_CONTRACT_CLEAR on IM_CONTRACT_CLEAR (MANUAL_NO, CONTR_ITEM)"
create index PK_IM_CONTRACT_CLEAR on IM_CONTRACT_CLEAR (MANUAL_NO, CONTR_ITEM) ;
select now();
\echo "PK_IM_CONTRACT_DEDUC on IM_CONTRACT_DEDUC (MANUAL_NO, ENTRY_ID, G_NO)"
create index PK_IM_CONTRACT_DEDUC on IM_CONTRACT_DEDUC (MANUAL_NO, ENTRY_ID, G_NO) ;
select now();
\echo "PK_IM_CONTRACT_LIST on IM_CONTRACT_LIST (MANUAL_NO, CONTR_ITEM)"
create index PK_IM_CONTRACT_LIST on IM_CONTRACT_LIST (MANUAL_NO, CONTR_ITEM) ;
select now();
\echo "PK_IM_COP_RATE on IM_COP_RATE (TRADE_CO, CHKSTDATE, CHKENDDATE)"
create index PK_IM_COP_RATE on IM_COP_RATE (TRADE_CO, CHKSTDATE, CHKENDDATE) ;
select now();
\echo "PK_IM_DECL_ALARM_HEAD on IM_DECL_ALARM_HEAD (PRE_NO)"
create index PK_IM_DECL_ALARM_HEAD on IM_DECL_ALARM_HEAD (PRE_NO) ;
select now();
\echo "PK_IM_DECL_ALARM_LIST on IM_DECL_ALARM_LIST (PRE_NO, RECORD_NUMBER, G_NO)"
create index PK_IM_DECL_ALARM_LIST on IM_DECL_ALARM_LIST (PRE_NO, RECORD_NUMBER, G_NO) ;
select now();
\echo "PK_IM_DECL_CUR_HEAD on IM_DECL_CUR_HEAD (PRE_NO)"
create index PK_IM_DECL_CUR_HEAD on IM_DECL_CUR_HEAD (PRE_NO) ;
select now();
\echo "PK_IM_DECL_CUR_LIST on IM_DECL_CUR_LIST (PRE_NO, RECORD_NUMBER, G_NO)"
create index PK_IM_DECL_CUR_LIST on IM_DECL_CUR_LIST (PRE_NO, RECORD_NUMBER, G_NO) ;
select now();
\echo "PK_IM_DECL_HIS_HEAD on IM_DECL_HIS_HEAD (PRE_NO)"
create index PK_IM_DECL_HIS_HEAD on IM_DECL_HIS_HEAD (PRE_NO) ;
select now();
\echo "PK_IM_DECL_HIS_LIST on IM_DECL_HIS_LIST (PRE_NO, RECORD_NUMBER, G_NO)"
create index PK_IM_DECL_HIS_LIST on IM_DECL_HIS_LIST (PRE_NO, RECORD_NUMBER, G_NO) ;
select now();
\echo "PK_IM_ELE_HEAD on IM_ELE_HEAD (LICENSE_NO)"
create index PK_IM_ELE_HEAD on IM_ELE_HEAD (LICENSE_NO) ;
select now();
\echo "PK_IM_ELE_LIST on IM_ELE_LIST (LICENSE_NO, L_G_NO)"
create index PK_IM_ELE_LIST on IM_ELE_LIST (LICENSE_NO, L_G_NO) ;
select now();
\echo "PK_IM_EXAM_JOU on IM_EXAM_JOU (ENTRY_ID, G_NO)"
create index PK_IM_EXAM_JOU on IM_EXAM_JOU (ENTRY_ID, G_NO) ;
select now();
\echo "PK_IM_EXAM_MANA_HEAD on IM_EXAM_MANA_HEAD (LICENSE_NO)"
create index PK_IM_EXAM_MANA_HEAD on IM_EXAM_MANA_HEAD (LICENSE_NO) ;
select now();
\echo "PK_IM_EXAM_MANA_LIST on IM_EXAM_MANA_LIST (LICENSE_NO, L_G_NO)"
create index PK_IM_EXAM_MANA_LIST on IM_EXAM_MANA_LIST (LICENSE_NO, L_G_NO) ;
select now();
\echo "PK_IM_FASCICLE_LIST on IM_FASCICLE_LIST (FASCICLE_NO, CONTR_ITEM)"
create index PK_IM_FASCICLE_LIST on IM_FASCICLE_LIST (FASCICLE_NO, CONTR_ITEM) ;
select now();
\echo "PK_IM_LIC_CODE_TS on IM_LIC_CODE_TS (LICENSE_NO)"
create index PK_IM_LIC_CODE_TS on IM_LIC_CODE_TS (LICENSE_NO) ;
select now();
\echo "PK_IM_TRANS_ALARM_CONTA_REL on IM_TRANS_ALARM_CONTA_REL (PRE_NO, RECORD_NUMBER, CONTA_NO)"
create index PK_IM_TRANS_ALARM_CONTA_REL on IM_TRANS_ALARM_CONTA_REL (PRE_NO, RECORD_NUMBER, CONTA_NO) ;
select now();
\echo "PK_IM_TRANS_ALARM_GOODS_CONTA_REL on IM_TRANS_ALARM_GOODS_CONTA_REL (PRE_NO, RECORD_NUMBER, G_NO, CONTA_NO)"
create index PK_IM_TRANS_ALARM_GOODS_CONTA_REL on IM_TRANS_ALARM_GOODS_CONTA_REL (PRE_NO, RECORD_NUMBER, G_NO, CONTA_NO) ;
select now();
\echo "PK_IM_TRANS_ALARM_LIST_REL on IM_TRANS_ALARM_LIST_REL (PRE_NO, RECORD_NUMBER)"
create index PK_IM_TRANS_ALARM_LIST_REL on IM_TRANS_ALARM_LIST_REL (PRE_NO, RECORD_NUMBER) ;
select now();
\echo "PK_IM_TRANS_CONTA_REL on IM_TRANS_CONTA_REL (PRE_NO, RECORD_NUMBER, CONTA_NO)"
create index PK_IM_TRANS_CONTA_REL on IM_TRANS_CONTA_REL (PRE_NO, RECORD_NUMBER, CONTA_NO) ;
select now();
\echo "PK_IM_TRANS_GOODS_CONTA_REL on IM_TRANS_GOODS_CONTA_REL (PRE_NO, RECORD_NUMBER, G_NO, CONTA_NO)"
create index PK_IM_TRANS_GOODS_CONTA_REL on IM_TRANS_GOODS_CONTA_REL (PRE_NO, RECORD_NUMBER, G_NO, CONTA_NO) ;
select now();
\echo "PK_IM_TRANS_HIS_CONTA_REL on IM_TRANS_HIS_CONTA_REL (PRE_NO, RECORD_NUMBER, CONTA_NO)"
create index PK_IM_TRANS_HIS_CONTA_REL on IM_TRANS_HIS_CONTA_REL (PRE_NO, RECORD_NUMBER, CONTA_NO) ;
select now();
\echo "PK_IM_TRANS_HIS_GOODS_CONTA_REL on IM_TRANS_HIS_GOODS_CONTA_REL (PRE_NO, RECORD_NUMBER, G_NO, CONTA_NO)"
create index PK_IM_TRANS_HIS_GOODS_CONTA_REL on IM_TRANS_HIS_GOODS_CONTA_REL (PRE_NO, RECORD_NUMBER, G_NO, CONTA_NO) ;
select now();
\echo "PK_IM_TRANS_HIS_LIST_REL on IM_TRANS_HIS_LIST_REL (PRE_NO, RECORD_NUMBER)"
create index PK_IM_TRANS_HIS_LIST_REL on IM_TRANS_HIS_LIST_REL (PRE_NO, RECORD_NUMBER) ;
select now();
\echo "PK_IM_TRANS_LIST_REL on IM_TRANS_LIST_REL (PRE_NO, RECORD_NUMBER)"
create index PK_IM_TRANS_LIST_REL on IM_TRANS_LIST_REL (PRE_NO, RECORD_NUMBER) ;
select now();
\echo "PK_IM_TRAN_JOU on IM_TRAN_JOU (ENTRY_ID, G_NO)"
create index PK_IM_TRAN_JOU on IM_TRAN_JOU (ENTRY_ID, G_NO) ;
select now();
\echo "PK_INCOME_INFO on INCOME_INFO (RPTNO)"
create index PK_INCOME_INFO on INCOME_INFO (RPTNO) ;
select now();
\echo "PK_INVESTER_REL on INVESTER_REL (TRADE_CO, INV_NO)"
create index PK_INVESTER_REL on INVESTER_REL (TRADE_CO, INV_NO) ;
select now();
\echo "PK_INVLOG_REL on INVLOG_REL (LOG_ID)"
create index PK_INVLOG_REL on INVLOG_REL (LOG_ID) ;
select now();
\echo "PK_JOB_PARAMETER on JOB_PARAMETER (JOB_NAME, PARAMETER_NAME, PARAMETER_VALUE)"
create index PK_JOB_PARAMETER on JOB_PARAMETER (JOB_NAME, PARAMETER_NAME, PARAMETER_VALUE) ;
select now();
\echo "PK_LSP_CHK on LSP_CHK (LSP_ID, LSP_TYPE, I_E_FLAG, ENTRY_ID, G_NO)"
create index PK_LSP_CHK on LSP_CHK (LSP_ID, LSP_TYPE, I_E_FLAG, ENTRY_ID, G_NO) ;
select now();
\echo "PK_LSP_HEAD on LSP_HEAD (LSP_ID, LSP_TYPE, I_E_FLAG)"
create index PK_LSP_HEAD on LSP_HEAD (LSP_ID, LSP_TYPE, I_E_FLAG) ;
select now();
\echo "PK_LSP_LIST on LSP_LIST (LSP_ID, LSP_TYPE, I_E_FLAG, G_NO)"
create index PK_LSP_LIST on LSP_LIST (LSP_ID, LSP_TYPE, I_E_FLAG, G_NO) ;
select now();
\echo "PK_MAIL_FILE on MAIL_FILE (NO)"
create index PK_MAIL_FILE on MAIL_FILE (NO) ;
select now();
\echo "PK_MANA_REL on MANA_REL (TRADE_CO, MANAG_NO)"
create index PK_MANA_REL on MANA_REL (TRADE_CO, MANAG_NO) ;
select now();
\echo "PK_MANIFEST_CHK on MANIFEST_CHK (BILL_NO, SHIP_ID, VOYAGE_NO, CUSTOMS_CODE, TRAF_MODE, I_E_FLAG, FORM_ID)"
create index PK_MANIFEST_CHK on MANIFEST_CHK (BILL_NO, SHIP_ID, VOYAGE_NO, CUSTOMS_CODE, TRAF_MODE, I_E_FLAG, FORM_ID) ;
select now();
\echo "PK_MANIFEST_CHK_LOG on MANIFEST_CHK_LOG (FORM_ID, CREATE_DATE, BILL_NO)"
create index PK_MANIFEST_CHK_LOG on MANIFEST_CHK_LOG (FORM_ID, CREATE_DATE, BILL_NO) ;
select now();
\echo "PK_MANIFEST_CONTA on MANIFEST_CONTA (VOYAGE_NO, TRAF_MODE, I_E_FLAG, BILL_NO, CONTA_ID, SHIP_ID)"
create index PK_MANIFEST_CONTA on MANIFEST_CONTA (VOYAGE_NO, TRAF_MODE, I_E_FLAG, BILL_NO, CONTA_ID, SHIP_ID) ;
select now();
\echo "PK_MANIFEST_EXCH_LOG on MANIFEST_EXCH_LOG (CUSTOMS_CODE, SHIP_ID, VOYAGE_NO, BILL_NO, I_E_DATE)"
create index PK_MANIFEST_EXCH_LOG on MANIFEST_EXCH_LOG (CUSTOMS_CODE, SHIP_ID, VOYAGE_NO, BILL_NO, I_E_DATE) ;
select now();
\echo "PK_MANIFEST_EXCH_LOG_BAK on MANIFEST_EXCH_LOG_BAK (CUSTOMS_CODE, SHIP_ID, VOYAGE_NO, BILL_NO, I_E_DATE, CREATE_DATE)"
create index PK_MANIFEST_EXCH_LOG_BAK on MANIFEST_EXCH_LOG_BAK (CUSTOMS_CODE, SHIP_ID, VOYAGE_NO, BILL_NO, I_E_DATE, CREATE_DATE) ;
select now();
\echo "PK_MANIFEST_HEAD on MANIFEST_HEAD (I_E_FLAG, CUSTOMS_CODE, TRAF_MODE, VOYAGE_NO, SHIP_ID, I_E_DATE)"
create index PK_MANIFEST_HEAD on MANIFEST_HEAD (I_E_FLAG, CUSTOMS_CODE, TRAF_MODE, VOYAGE_NO, SHIP_ID, I_E_DATE) ;
select now();
\echo "PK_MANIFEST_HEAD_XMS_LOG on MANIFEST_HEAD_XMS_LOG (VOYAGE_NO, SHIP_ID, CUSTOMS_CODE, I_E_DATE, TRAF_MODE, I_E_FLAG)"
create index PK_MANIFEST_HEAD_XMS_LOG on MANIFEST_HEAD_XMS_LOG (VOYAGE_NO, SHIP_ID, CUSTOMS_CODE, I_E_DATE, TRAF_MODE, I_E_FLAG) ;
select now();
\echo "PK_MANIFEST_LIST on MANIFEST_LIST (BILL_NO, VOYAGE_NO, CUSTOMS_CODE, SHIP_ID, I_E_DATE, TRAF_MODE, I_E_FLAG)"
create index PK_MANIFEST_LIST on MANIFEST_LIST (BILL_NO, VOYAGE_NO, CUSTOMS_CODE, SHIP_ID, I_E_DATE, TRAF_MODE, I_E_FLAG) ;
select now();
\echo "PK_MANIFEST_LIST_CONTA on MANIFEST_LIST_CONTA (VOYAGE_NO, CUSTOMS_CODE, TRAF_MODE, I_E_FLAG, BILL_NO, CONTA_ID, SHIP_ID)"
create index PK_MANIFEST_LIST_CONTA on MANIFEST_LIST_CONTA (VOYAGE_NO, CUSTOMS_CODE, TRAF_MODE, I_E_FLAG, BILL_NO, CONTA_ID, SHIP_ID) ;
select now();
\echo "PK_MANIFEST_LIST_LOG on MANIFEST_LIST_LOG (I_E_FLAG, CUSTOMS_CODE, TRAF_MODE, VOYAGE_NO, BILL_NO, SHIP_ID, CREATE_DATE, I_E_DATE)"
create index PK_MANIFEST_LIST_LOG on MANIFEST_LIST_LOG (I_E_FLAG, CUSTOMS_CODE, TRAF_MODE, VOYAGE_NO, BILL_NO, SHIP_ID, CREATE_DATE, I_E_DATE) ;
select now();
\echo "PK_MANIFEST_LIST_RSKINFO_LOG on MANIFEST_LIST_RSKINFO_LOG (BILL_NO, CUSTOMS_CODE, VOYAGE_NO, SHIP_ID, I_E_DATE, TRAF_MODE, I_E_FLAG, RSK_DATE)"
create index PK_MANIFEST_LIST_RSKINFO_LOG on MANIFEST_LIST_RSKINFO_LOG (BILL_NO, CUSTOMS_CODE, VOYAGE_NO, SHIP_ID, I_E_DATE, TRAF_MODE, I_E_FLAG, RSK_DATE) ;
select now();
\echo "PK_MGR_SECTION_CODE on MGR_SECTION_CODE (SECTION_ID, CUSTOMS_CODE)"
create index PK_MGR_SECTION_CODE on MGR_SECTION_CODE (SECTION_ID, CUSTOMS_CODE) ;
select now();
\echo "PK_MGR_USER_INFO on MGR_USER_INFO (EMPLOYEE_ID, DOMAIN_NAME)"
create index PK_MGR_USER_INFO on MGR_USER_INFO (EMPLOYEE_ID, DOMAIN_NAME) ;
select now();
\echo "MICROSOFT_PK_DTPROPERTIES on MICROSOFTDTPROPERTIES (ID, PROPERTY)"
create index MICROSOFT_PK_DTPROPERTIES on MICROSOFTDTPROPERTIES (ID, PROPERTY) ;
select now();
\echo "PK_MNLBAK_ACCOUNT on MNLBAK_ACCOUNT (MANUAL_NO, ID_STAT)"
create index PK_MNLBAK_ACCOUNT on MNLBAK_ACCOUNT (MANUAL_NO, ID_STAT) ;
select now();
\echo "PK_MNLBAK_APPL_CLOSE on MNLBAK_APPL_CLOSE (MANUAL_NO)"
create index PK_MNLBAK_APPL_CLOSE on MNLBAK_APPL_CLOSE (MANUAL_NO) ;
select now();
\echo "PK_MNLBAK_CLAIM on MNLBAK_CLAIM (GUARANTEE_NO)"
create index PK_MNLBAK_CLAIM on MNLBAK_CLAIM (GUARANTEE_NO) ;
select now();
\echo "PK_MNLBAK_CONSUME on MNLBAK_CONSUME (MANUAL_NO, CONTR_ITEM, EX_NO)"
create index PK_MNLBAK_CONSUME on MNLBAK_CONSUME (MANUAL_NO, CONTR_ITEM, EX_NO) ;
select now();
\echo "PK_MNLBAK_CONTRACT_HEAD on MNLBAK_CONTRACT_HEAD (MANUAL_NO)"
create index PK_MNLBAK_CONTRACT_HEAD on MNLBAK_CONTRACT_HEAD (MANUAL_NO) ;
select now();
\echo "PK_MNLBAK_CONTRACT_WORKFLOW on MNLBAK_CONTRACT_WORKFLOW (MANUAL_NO, STEP_ID, PROC_DATE)"
create index PK_MNLBAK_CONTRACT_WORKFLOW on MNLBAK_CONTRACT_WORKFLOW (MANUAL_NO, STEP_ID, PROC_DATE) ;
select now();
\echo "PK_MNLBAK_EX_CONTRACT_CLEAR on MNLBAK_EX_CONTRACT_CLEAR (MANUAL_NO, CONTR_ITEM)"
create index PK_MNLBAK_EX_CONTRACT_CLEAR on MNLBAK_EX_CONTRACT_CLEAR (MANUAL_NO, CONTR_ITEM) ;
select now();
\echo "PK_MNLBAK_EX_CONTRACT_DEDUC on MNLBAK_EX_CONTRACT_DEDUC (MANUAL_NO, ENTRY_ID, G_NO)"
create index PK_MNLBAK_EX_CONTRACT_DEDUC on MNLBAK_EX_CONTRACT_DEDUC (MANUAL_NO, ENTRY_ID, G_NO) ;
select now();
\echo "PK_MNLBAK_EX_CONTRACT_LIST on MNLBAK_EX_CONTRACT_LIST (MANUAL_NO, CONTR_ITEM)"
create index PK_MNLBAK_EX_CONTRACT_LIST on MNLBAK_EX_CONTRACT_LIST (MANUAL_NO, CONTR_ITEM) ;
select now();
\echo "PK_MNLBAK_EX_FASCICLE_LIST on MNLBAK_EX_FASCICLE_LIST (FASCICLE_NO, CONTR_ITEM)"
create index PK_MNLBAK_EX_FASCICLE_LIST on MNLBAK_EX_FASCICLE_LIST (FASCICLE_NO, CONTR_ITEM) ;
select now();
\echo "PK_MNLBAK_FASCICLE_HEAD on MNLBAK_FASCICLE_HEAD (FASCICLE_NO)"
create index PK_MNLBAK_FASCICLE_HEAD on MNLBAK_FASCICLE_HEAD (FASCICLE_NO) ;
select now();
\echo "PK_MNLBAK_FEE_INVOICE on MNLBAK_FEE_INVOICE (MANUAL_NO, F_NO)"
create index PK_MNLBAK_FEE_INVOICE on MNLBAK_FEE_INVOICE (MANUAL_NO, F_NO) ;
select now();
\echo "PK_MNLBAK_IM_CONTRACT_CLEAR on MNLBAK_IM_CONTRACT_CLEAR (MANUAL_NO, CONTR_ITEM)"
create index PK_MNLBAK_IM_CONTRACT_CLEAR on MNLBAK_IM_CONTRACT_CLEAR (MANUAL_NO, CONTR_ITEM) ;
select now();
\echo "PK_MNLBAK_IM_CONTRACT_DEDUC on MNLBAK_IM_CONTRACT_DEDUC (MANUAL_NO, ENTRY_ID, G_NO)"
create index PK_MNLBAK_IM_CONTRACT_DEDUC on MNLBAK_IM_CONTRACT_DEDUC (MANUAL_NO, ENTRY_ID, G_NO) ;
select now();
\echo "PK_MNLBAK_IM_CONTRACT_LIST on MNLBAK_IM_CONTRACT_LIST (MANUAL_NO, CONTR_ITEM)"
create index PK_MNLBAK_IM_CONTRACT_LIST on MNLBAK_IM_CONTRACT_LIST (MANUAL_NO, CONTR_ITEM) ;
select now();
\echo "PK_MNLBAK_IM_FASCICLE_LIST on MNLBAK_IM_FASCICLE_LIST (FASCICLE_NO, CONTR_ITEM)"
create index PK_MNLBAK_IM_FASCICLE_LIST on MNLBAK_IM_FASCICLE_LIST (FASCICLE_NO, CONTR_ITEM) ;
select now();
\echo "PK_MNLBAK_PRESS_CLEAR on MNLBAK_PRESS_CLEAR (MANUAL_NO, PR_NO)"
create index PK_MNLBAK_PRESS_CLEAR on MNLBAK_PRESS_CLEAR (MANUAL_NO, PR_NO) ;
select now();
\echo "PK_MNLBAK_SERVICE_FEE on MNLBAK_SERVICE_FEE (MANUAL_NO)"
create index PK_MNLBAK_SERVICE_FEE on MNLBAK_SERVICE_FEE (MANUAL_NO) ;
select now();
\echo "PK_MNLBAK_SERVICE_LIST on MNLBAK_SERVICE_LIST (MANUAL_NO, F_NO)"
create index PK_MNLBAK_SERVICE_LIST on MNLBAK_SERVICE_LIST (MANUAL_NO, F_NO) ;
select now();
\echo "PK_MNL_PARA on MNL_PARA (PARA_TYPE, PARA_ID)"
create index PK_MNL_PARA on MNL_PARA (PARA_TYPE, PARA_ID) ;
select now();
\echo "PK_MNL_PRESS on MNL_PRESS (PARA_TYPE, PARA_NAME)"
create index PK_MNL_PRESS on MNL_PRESS (PARA_TYPE, PARA_NAME) ;
select now();
\echo "PK_MNL_RECEIVE_RECEIPT on MNL_RECEIVE_RECEIPT (MANUAL_NO, SEND_CUSTOMS, CUSTOMS_CODE, H2000_RECEIVE_DATE)"
create index PK_MNL_RECEIVE_RECEIPT on MNL_RECEIVE_RECEIPT (MANUAL_NO, SEND_CUSTOMS, CUSTOMS_CODE, H2000_RECEIVE_DATE) ;
select now();
\echo "PK_MNL_SEQ on MNL_SEQ (MNL_KEY)"
create index PK_MNL_SEQ on MNL_SEQ (MNL_KEY) ;
select now();
\echo "PK_MOD_PROJECT_HEAD on MOD_PROJECT_HEAD (PROJECT_ID, MODIFY_TIMES)"
create index PK_MOD_PROJECT_HEAD on MOD_PROJECT_HEAD (PROJECT_ID, MODIFY_TIMES) ;
select now();
\echo "PK_MOD_PROJECT_LIST on MOD_PROJECT_LIST (PROJECT_ID, MODIFY_TIMES, G_NO)"
create index PK_MOD_PROJECT_LIST on MOD_PROJECT_LIST (PROJECT_ID, MODIFY_TIMES, G_NO) ;
select now();
\echo "PK_MOD_RED_HEAD on MOD_RED_HEAD (CUT_ID, MODIFY_TIMES)"
create index PK_MOD_RED_HEAD on MOD_RED_HEAD (CUT_ID, MODIFY_TIMES) ;
select now();
\echo "PK_MOD_RED_LIST on MOD_RED_LIST (CUT_ID, MODIFY_TIMES, G_NO)"
create index PK_MOD_RED_LIST on MOD_RED_LIST (CUT_ID, MODIFY_TIMES, G_NO) ;
select now();
\echo "PK_NONENTRY_CHK_RESULT on NONENTRY_CHK_RESULT (RSK_NO)"
create index PK_NONENTRY_CHK_RESULT on NONENTRY_CHK_RESULT (RSK_NO) ;
select now();
\echo "PK_NORSK_COMPANY on NORSK_COMPANY (CCTS_CODE)"
create index PK_NORSK_COMPANY on NORSK_COMPANY (CCTS_CODE) ;
select now();
\echo "PK_NORSK_COMPANY_BAK on NORSK_COMPANY_BAK (CCTS_CODE, OP_BAK_TIME)"
create index PK_NORSK_COMPANY_BAK on NORSK_COMPANY_BAK (CCTS_CODE, OP_BAK_TIME) ;
select now();
\echo "PK_NORSK_CONDITION on NORSK_CONDITION (CCTS_CODE)"
create index PK_NORSK_CONDITION on NORSK_CONDITION (CCTS_CODE) ;
select now();
\echo "PK_NORSK_CONDITION_BAK on NORSK_CONDITION_BAK (CCTS_CODE, OP_BAK_TIME)"
create index PK_NORSK_CONDITION_BAK on NORSK_CONDITION_BAK (CCTS_CODE, OP_BAK_TIME) ;
select now();
\echo "PK_NORSK_TRADE_MODE on NORSK_TRADE_MODE (CCTS_CODE)"
create index PK_NORSK_TRADE_MODE on NORSK_TRADE_MODE (CCTS_CODE) ;
select now();
\echo "PK_NORSK_TRADE_MODE_BAK on NORSK_TRADE_MODE_BAK (CCTS_CODE, OP_BAK_TIME)"
create index PK_NORSK_TRADE_MODE_BAK on NORSK_TRADE_MODE_BAK (CCTS_CODE, OP_BAK_TIME) ;
select now();
\echo "PK_OCC_ELE_HEAD on OCC_ELE_HEAD (CERTIFICATE_NO, AGREEMENT_ID, ISSUE_PLACE)"
create index PK_OCC_ELE_HEAD on OCC_ELE_HEAD (CERTIFICATE_NO, AGREEMENT_ID, ISSUE_PLACE) ;
select now();
\echo "PK_OCC_ELE_LIST on OCC_ELE_LIST (CERTIFICATE_NO, AGREEMENT_ID, ISSUE_PLACE, G_NO)"
create index PK_OCC_ELE_LIST on OCC_ELE_LIST (CERTIFICATE_NO, AGREEMENT_ID, ISSUE_PLACE, G_NO) ;
select now();
\echo "PK_OCC_EXAM on OCC_EXAM (CERTIFICATE_NO, AGREEMENT_ID, ISSUE_PLACE, G_NO, ENTRY_G_NO)"
create index PK_OCC_EXAM on OCC_EXAM (CERTIFICATE_NO, AGREEMENT_ID, ISSUE_PLACE, G_NO, ENTRY_G_NO) ;
select now();
\echo "PK_OCC_RECEIPT on OCC_RECEIPT (CERTIFICATE_NO, AGREEMENT_ID, ISSUE_PLACE)"
create index PK_OCC_RECEIPT on OCC_RECEIPT (CERTIFICATE_NO, AGREEMENT_ID, ISSUE_PLACE) ;
select now();
\echo "  add on ODIOGGCKPT (GROUP_NAME, GROUP_KEY)"
create index  PK_ODIOGGCKPT add on ODIOGGCKPT (GROUP_NAME, GROUP_KEY) ;
select now();
\echo "PK_OTHER_STF_RECORD on OTHER_STF_RECORD (OTHER_ID, ID_TYPE)"
create index PK_OTHER_STF_RECORD on OTHER_STF_RECORD (OTHER_ID, ID_TYPE) ;
select now();
\echo "PK_PAPERLESS_SELFSAVE_CERT on PAPERLESS_SELFSAVE_CERT (ENTRY_ID)"
create index PK_PAPERLESS_SELFSAVE_CERT on PAPERLESS_SELFSAVE_CERT (ENTRY_ID) ;
select now();
\echo "PK_PAYOUT_REMIT_HEAD on PAYOUT_REMIT_HEAD (RPTNO)"
create index PK_PAYOUT_REMIT_HEAD on PAYOUT_REMIT_HEAD (RPTNO) ;
select now();
\echo "PK_PAYOUT_REMIT_LIST on PAYOUT_REMIT_LIST (RPTNO, ENTRY_ID)"
create index PK_PAYOUT_REMIT_LIST on PAYOUT_REMIT_LIST (RPTNO, ENTRY_ID) ;
select now();
\echo "PK_PES_CANCEL on PES_CANCEL (ENTRY_ID)"
create index PK_PES_CANCEL on PES_CANCEL (ENTRY_ID) ;
select now();
\echo "PK_PES_NOTE on PES_NOTE (NOTE_NO)"
create index PK_PES_NOTE on PES_NOTE (NOTE_NO) ;
select now();
\echo "PK_PES_WORKFLOW on PES_WORKFLOW (NOTE_NO, NOTE_TYPE, PROCESS_DATE, STEP_ID)"
create index PK_PES_WORKFLOW on PES_WORKFLOW (NOTE_NO, NOTE_TYPE, PROCESS_DATE, STEP_ID) ;
select now();
\echo "PK_PORT_BIND_REL on PORT_BIND_REL (BIND_NO, PRE_NO)"
create index PK_PORT_BIND_REL on PORT_BIND_REL (BIND_NO, PRE_NO) ;
select now();
\echo "PK_PRESS_CLEAR on PRESS_CLEAR (MANUAL_NO, PR_NO)"
create index PK_PRESS_CLEAR on PRESS_CLEAR (MANUAL_NO, PR_NO) ;
select now();
\echo "PK_PRE_APPL_CLOSE on PRE_APPL_CLOSE (MANUAL_NO)"
create index PK_PRE_APPL_CLOSE on PRE_APPL_CLOSE (MANUAL_NO) ;
select now();
\echo "PK_PRE_APPL_CLOSE_CONSUME on PRE_APPL_CLOSE_CONSUME (MANUAL_NO, CONTR_ITEM, EX_NO)"
create index PK_PRE_APPL_CLOSE_CONSUME on PRE_APPL_CLOSE_CONSUME (MANUAL_NO, CONTR_ITEM, EX_NO) ;
select now();
\echo "PK_PRE_CDL_COMMODITY on PRE_CDL_COMMODITY (PRE_RECORDS_NO, RECORDS_DATE, G_NO)"
create index PK_PRE_CDL_COMMODITY on PRE_CDL_COMMODITY (PRE_RECORDS_NO, RECORDS_DATE, G_NO) ;
select now();
\echo "PK_PRE_CDL_COMPANY on PRE_CDL_COMPANY (TRADE_CO, RECORDS_DATE, TRADE_BONDED_FLAG)"
create index PK_PRE_CDL_COMPANY on PRE_CDL_COMPANY (TRADE_CO, RECORDS_DATE, TRADE_BONDED_FLAG) ;
select now();
\echo "PK_PRE_COMPANY_REL on PRE_COMPANY_REL (PRE_TRADE_CO)"
create index PK_PRE_COMPANY_REL on PRE_COMPANY_REL (PRE_TRADE_CO) ;
select now();
\echo "PK_PRE_CONSUME on PRE_CONSUME (MANUAL_NO, CONTR_ITEM, EX_NO)"
create index PK_PRE_CONSUME on PRE_CONSUME (MANUAL_NO, CONTR_ITEM, EX_NO) ;
select now();
\echo "PK_PRE_CONTRACT_HEAD on PRE_CONTRACT_HEAD (MANUAL_NO)"
create index PK_PRE_CONTRACT_HEAD on PRE_CONTRACT_HEAD (MANUAL_NO) ;
select now();
\echo "PK_PRE_DECL_REL on PRE_DECL_REL (DECL_TRAIN_CO)"
create index PK_PRE_DECL_REL on PRE_DECL_REL (DECL_TRAIN_CO) ;
select now();
\echo "PK_PRE_EXA_APPL_CLOSE on PRE_EXA_APPL_CLOSE (MANUAL_NO, CONTR_ITEM)"
create index PK_PRE_EXA_APPL_CLOSE on PRE_EXA_APPL_CLOSE (MANUAL_NO, CONTR_ITEM) ;
select now();
\echo "PK_PRE_EX_APPL_CLOSE on PRE_EX_APPL_CLOSE (MANUAL_NO, CONTR_ITEM)"
create index PK_PRE_EX_APPL_CLOSE on PRE_EX_APPL_CLOSE (MANUAL_NO, CONTR_ITEM) ;
select now();
\echo "PK_PRE_EX_CONTRACT_LIST on PRE_EX_CONTRACT_LIST (MANUAL_NO, CONTR_ITEM)"
create index PK_PRE_EX_CONTRACT_LIST on PRE_EX_CONTRACT_LIST (MANUAL_NO, CONTR_ITEM) ;
select now();
\echo "PK_PRE_EX_FASCICLE_LIST on PRE_EX_FASCICLE_LIST (FASCICLE_NO, CONTR_ITEM)"
create index PK_PRE_EX_FASCICLE_LIST on PRE_EX_FASCICLE_LIST (FASCICLE_NO, CONTR_ITEM) ;
select now();
\echo "PK_PRE_FASCICLE_HEAD on PRE_FASCICLE_HEAD (FASCICLE_NO)"
create index PK_PRE_FASCICLE_HEAD on PRE_FASCICLE_HEAD (FASCICLE_NO) ;
select now();
\echo "PK_PRE_IMA_APPL_CLOSE on PRE_IMA_APPL_CLOSE (MANUAL_NO, CONTR_ITEM)"
create index PK_PRE_IMA_APPL_CLOSE on PRE_IMA_APPL_CLOSE (MANUAL_NO, CONTR_ITEM) ;
select now();
\echo "PK_PRE_IM_APPL_CLOSE on PRE_IM_APPL_CLOSE (MANUAL_NO, CONTR_ITEM)"
create index PK_PRE_IM_APPL_CLOSE on PRE_IM_APPL_CLOSE (MANUAL_NO, CONTR_ITEM) ;
select now();
\echo "PK_PRE_IM_CONTRACT_LIST on PRE_IM_CONTRACT_LIST (MANUAL_NO, CONTR_ITEM)"
create index PK_PRE_IM_CONTRACT_LIST on PRE_IM_CONTRACT_LIST (MANUAL_NO, CONTR_ITEM) ;
select now();
\echo "PK_PRE_IM_FASCICLE_LIST on PRE_IM_FASCICLE_LIST (FASCICLE_NO, CONTR_ITEM)"
create index PK_PRE_IM_FASCICLE_LIST on PRE_IM_FASCICLE_LIST (FASCICLE_NO, CONTR_ITEM) ;
select now();
\echo "PK_PRE_INVESTER_REL on PRE_INVESTER_REL (PRE_TRADE_CO, INV_NO)"
create index PK_PRE_INVESTER_REL on PRE_INVESTER_REL (PRE_TRADE_CO, INV_NO) ;
select now();
\echo "PK_PRE_MANA_REL on PRE_MANA_REL (PRE_TRADE_CO, MANAG_NO)"
create index PK_PRE_MANA_REL on PRE_MANA_REL (PRE_TRADE_CO, MANAG_NO) ;
select now();
\echo "PK_PRE_PROJECT_HEAD on PRE_PROJECT_HEAD (PROJECT_ID, MODIFY_TIMES)"
create index PK_PRE_PROJECT_HEAD on PRE_PROJECT_HEAD (PROJECT_ID, MODIFY_TIMES) ;
select now();
\echo "PK_PRE_PROJECT_LIST on PRE_PROJECT_LIST (PROJECT_ID, MODIFY_TIMES, G_NO)"
create index PK_PRE_PROJECT_LIST on PRE_PROJECT_LIST (PROJECT_ID, MODIFY_TIMES, G_NO) ;
select now();
\echo "PK_PRE_RED_HEAD on PRE_RED_HEAD (CUT_ID, MODIFY_TIMES)"
create index PK_PRE_RED_HEAD on PRE_RED_HEAD (CUT_ID, MODIFY_TIMES) ;
select now();
\echo "PK_PRE_RED_LIST on PRE_RED_LIST (CUT_ID, MODIFY_TIMES, G_NO)"
create index PK_PRE_RED_LIST on PRE_RED_LIST (CUT_ID, MODIFY_TIMES, G_NO) ;
select now();
\echo "PK_PRE_REL_ALC_WORK on PRE_REL_ALC_WORK (ENTRY_ID)"
create index PK_PRE_REL_ALC_WORK on PRE_REL_ALC_WORK (ENTRY_ID) ;
select now();
\echo "PK_PRICE_LIBRARY on PRICE_LIBRARY (REC_NO, I_E_FLAG, REC_TYPE, CREATE_DATE, POST_MARK)"
create index PK_PRICE_LIBRARY on PRICE_LIBRARY (REC_NO, I_E_FLAG, REC_TYPE, CREATE_DATE, POST_MARK) ;
select now();
\echo "PK_PRICE_LIBRARY_ENTRY on PRICE_LIBRARY_ENTRY (REC_NO, I_E_FLAG, REC_TYPE, CREATE_DATE)"
create index PK_PRICE_LIBRARY_ENTRY on PRICE_LIBRARY_ENTRY (REC_NO, I_E_FLAG, REC_TYPE, CREATE_DATE) ;
select now();
\echo "PK_PRICE_LIBRARY_MAN on PRICE_LIBRARY_MAN (REC_NO, I_E_FLAG, REC_TYPE, CREATE_DATE)"
create index PK_PRICE_LIBRARY_MAN on PRICE_LIBRARY_MAN (REC_NO, I_E_FLAG, REC_TYPE, CREATE_DATE) ;
select now();
\echo "PK_PRICE_LIBRARY_RISK on PRICE_LIBRARY_RISK (REC_NO, I_E_FLAG, REC_TYPE, CREATE_DATE)"
create index PK_PRICE_LIBRARY_RISK on PRICE_LIBRARY_RISK (REC_NO, I_E_FLAG, REC_TYPE, CREATE_DATE) ;
select now();
\echo "PK_PROJECT_HEAD on PROJECT_HEAD (PROJECT_ID, MODIFY_TIMES)"
create index PK_PROJECT_HEAD on PROJECT_HEAD (PROJECT_ID, MODIFY_TIMES) ;
select now();
\echo "PK_PROJECT_LIST on PROJECT_LIST (PROJECT_ID, MODIFY_TIMES, G_NO)"
create index PK_PROJECT_LIST on PROJECT_LIST (PROJECT_ID, MODIFY_TIMES, G_NO) ;
select now();
\echo "PK_PROJECT_MAX_NO on PROJECT_MAX_NO (MASTER_CUSTOMS, YEAR_2, CUT_MODE)"
create index PK_PROJECT_MAX_NO on PROJECT_MAX_NO (MASTER_CUSTOMS, YEAR_2, CUT_MODE) ;
select now();
\echo "PK_PROJECT_MAX_NO_2007 on PROJECT_MAX_NO_2007 (MASTER_CUSTOMS, YEAR_4, CUT_MODE)"
create index PK_PROJECT_MAX_NO_2007 on PROJECT_MAX_NO_2007 (MASTER_CUSTOMS, YEAR_4, CUT_MODE) ;
select now();
\echo "PK_RAM_HEAD on RAM_HEAD (RAM_ID)"
create index PK_RAM_HEAD on RAM_HEAD (RAM_ID) ;
select now();
\echo "PK_RAM_LIST on RAM_LIST (RAM_ID, NUM)"
create index PK_RAM_LIST on RAM_LIST (RAM_ID, NUM) ;
select now();
\echo "PK_RAM_PRINT_LOG on RAM_PRINT_LOG (RAM_ID, PRINT_DATE)"
create index PK_RAM_PRINT_LOG on RAM_PRINT_LOG (RAM_ID, PRINT_DATE) ;
select now();
\echo "PK_RAM_RG_COPINFO on RAM_RG_COPINFO (RAM_ID, TYPE, COP_NO)"
create index PK_RAM_RG_COPINFO on RAM_RG_COPINFO (RAM_ID, TYPE, COP_NO) ;
select now();
\echo "PK_RAM_RG_COP_OWNER on RAM_RG_COP_OWNER (RAM_ID, TYPE, COP_NO, OWNER_NO)"
create index PK_RAM_RG_COP_OWNER on RAM_RG_COP_OWNER (RAM_ID, TYPE, COP_NO, OWNER_NO) ;
select now();
\echo "PK_RAM_RG_COP_PROJECT on RAM_RG_COP_PROJECT (RAM_ID, TYPE, COP_NO, PROJECT_NO)"
create index PK_RAM_RG_COP_PROJECT on RAM_RG_COP_PROJECT (RAM_ID, TYPE, COP_NO, PROJECT_NO) ;
select now();
\echo "PK_RAM_RG_HEAD on RAM_RG_HEAD (RAM_ID)"
create index PK_RAM_RG_HEAD on RAM_RG_HEAD (RAM_ID) ;
select now();
\echo "PK_RAM_RN_INFO on RAM_RN_INFO (RAM_ID)"
create index PK_RAM_RN_INFO on RAM_RN_INFO (RAM_ID) ;
select now();
\echo "PK_RAM_RY_COMMUNICATION on RAM_RY_COMMUNICATION (RAM_ID, SEQ_NO)"
create index PK_RAM_RY_COMMUNICATION on RAM_RY_COMMUNICATION (RAM_ID, SEQ_NO) ;
select now();
\echo "PK_RAM_STATUS on RAM_STATUS (CUT_ID, G_NO)"
create index PK_RAM_STATUS on RAM_STATUS (CUT_ID, G_NO) ;
select now();
\echo "PK_RAM_STATUS_LIST on RAM_STATUS_LIST (CUT_ID, G_NO)"
create index PK_RAM_STATUS_LIST on RAM_STATUS_LIST (CUT_ID, G_NO) ;
select now();
\echo "PK_RAM_STATUS_MODI_LOG on RAM_STATUS_MODI_LOG (CUT_ID, G_NO, MODIFY_DATE, FIELD_NAME)"
create index PK_RAM_STATUS_MODI_LOG on RAM_STATUS_MODI_LOG (CUT_ID, G_NO, MODIFY_DATE, FIELD_NAME) ;
select now();
\echo "PK_RCP_INCOME_HEAD on RCP_INCOME_HEAD (LEVYNO)"
create index PK_RCP_INCOME_HEAD on RCP_INCOME_HEAD (LEVYNO) ;
select now();
\echo "PK_RCP_INCOME_HEAD_BAK on RCP_INCOME_HEAD_BAK (LEVYNO)"
create index PK_RCP_INCOME_HEAD_BAK on RCP_INCOME_HEAD_BAK (LEVYNO) ;
select now();
\echo "PK_RCP_INCOME_LIST on RCP_INCOME_LIST (LEVYNO, LISTNO)"
create index PK_RCP_INCOME_LIST on RCP_INCOME_LIST (LEVYNO, LISTNO) ;
select now();
\echo "PK_RCP_INCOME_LIST_BAK on RCP_INCOME_LIST_BAK (LEVYNO, LISTNO)"
create index PK_RCP_INCOME_LIST_BAK on RCP_INCOME_LIST_BAK (LEVYNO, LISTNO) ;
select now();
\echo "PK_RCP_PAYMENT_HEAD on RCP_PAYMENT_HEAD (LEVYNO)"
create index PK_RCP_PAYMENT_HEAD on RCP_PAYMENT_HEAD (LEVYNO) ;
select now();
\echo "PK_RCP_PAYMENT_HEAD_BAK on RCP_PAYMENT_HEAD_BAK (LEVYNO)"
create index PK_RCP_PAYMENT_HEAD_BAK on RCP_PAYMENT_HEAD_BAK (LEVYNO) ;
select now();
\echo "PK_RCP_PAYMENT_LIST on RCP_PAYMENT_LIST (LEVYNO, LISTNO)"
create index PK_RCP_PAYMENT_LIST on RCP_PAYMENT_LIST (LEVYNO, LISTNO) ;
select now();
\echo "PK_RCP_PAYMENT_LIST_BAK on RCP_PAYMENT_LIST_BAK (LEVYNO, LISTNO)"
create index PK_RCP_PAYMENT_LIST_BAK on RCP_PAYMENT_LIST_BAK (LEVYNO, LISTNO) ;
select now();
\echo "PK_RCP_RECORD_HEAD on RCP_RECORD_HEAD (LEVYNO)"
create index PK_RCP_RECORD_HEAD on RCP_RECORD_HEAD (LEVYNO) ;
select now();
\echo "PK_RCP_RECORD_HEAD_BAK on RCP_RECORD_HEAD_BAK (LEVYNO)"
create index PK_RCP_RECORD_HEAD_BAK on RCP_RECORD_HEAD_BAK (LEVYNO) ;
select now();
\echo "PK_RCP_RECORD_LIST on RCP_RECORD_LIST (LEVYNO, LISTNO)"
create index PK_RCP_RECORD_LIST on RCP_RECORD_LIST (LEVYNO, LISTNO) ;
select now();
\echo "PK_RCP_RECORD_LIST_BAK on RCP_RECORD_LIST_BAK (LEVYNO, LISTNO)"
create index PK_RCP_RECORD_LIST_BAK on RCP_RECORD_LIST_BAK (LEVYNO, LISTNO) ;
select now();
\echo "PK_RCP_WORKFLOW on RCP_WORKFLOW (LEVYNO, TRANSFER_NUM, PROCESS_STATUS, PROCESS_DATE)"
create index PK_RCP_WORKFLOW on RCP_WORKFLOW (LEVYNO, TRANSFER_NUM, PROCESS_STATUS, PROCESS_DATE) ;
select now();
\echo "PK_RED_ENTRY_HEAD on RED_ENTRY_HEAD (ENTRY_ID)"
create index PK_RED_ENTRY_HEAD on RED_ENTRY_HEAD (ENTRY_ID) ;
select now();
\echo "PK_RED_ENTRY_LIST on RED_ENTRY_LIST (ENTRY_ID, G_NO)"
create index PK_RED_ENTRY_LIST on RED_ENTRY_LIST (ENTRY_ID, G_NO) ;
select now();
\echo "PK_RED_FEE_INVOICE on RED_FEE_INVOICE (MANUAL_NO, FEE_ID)"
create index PK_RED_FEE_INVOICE on RED_FEE_INVOICE (MANUAL_NO, FEE_ID) ;
select now();
\echo "PK_RED_HEAD on RED_HEAD (CUT_ID, MODIFY_TIMES)"
create index PK_RED_HEAD on RED_HEAD (CUT_ID, MODIFY_TIMES) ;
select now();
\echo "PK_RED_LIST on RED_LIST (CUT_ID, MODIFY_TIMES, G_NO)"
create index PK_RED_LIST on RED_LIST (CUT_ID, MODIFY_TIMES, G_NO) ;
select now();
\echo "PK_RED_MAX_NO on RED_MAX_NO (MASTER_CUSTOMS, YEAR_1, CLASS)"
create index PK_RED_MAX_NO on RED_MAX_NO (MASTER_CUSTOMS, YEAR_1, CLASS) ;
select now();
\echo "PK_RED_MAX_NO_2007 on RED_MAX_NO_2007 (MASTER_CUSTOMS, YEAR_2)"
create index PK_RED_MAX_NO_2007 on RED_MAX_NO_2007 (MASTER_CUSTOMS, YEAR_2) ;
select now();
\echo "PK_RED_RECEIVE_RECEIPT on RED_RECEIVE_RECEIPT (CUT_ID, SEND_TIMES)"
create index PK_RED_RECEIVE_RECEIPT on RED_RECEIVE_RECEIPT (CUT_ID, SEND_TIMES) ;
select now();
\echo "PK_RED_SERVICE_FEE on RED_SERVICE_FEE (MANUAL_NO)"
create index PK_RED_SERVICE_FEE on RED_SERVICE_FEE (MANUAL_NO) ;
select now();
\echo "PK_REL_ALC_WORK on REL_ALC_WORK (ENTRY_ID)"
create index PK_REL_ALC_WORK on REL_ALC_WORK (ENTRY_ID) ;
select now();
\echo "PK_RETURN_REL on RETURN_REL (RET_TRANS_NO, RET_TYPE, RET_TIME)"
create index PK_RETURN_REL on RETURN_REL (RET_TRANS_NO, RET_TYPE, RET_TIME) ;
select now();
\echo "PK_RISK_CONTROL on RISK_CONTROL (RISK_CONTROL_CODE, RISK_TYPE, RISK_SCHEDULE)"
create index PK_RISK_CONTROL on RISK_CONTROL (RISK_CONTROL_CODE, RISK_TYPE, RISK_SCHEDULE) ;
select now();
\echo "PK_RSK_ASSAY_APPLICATION on RSK_ASSAY_APPLICATION (ENTRY_ID, G_NO)"
create index PK_RSK_ASSAY_APPLICATION on RSK_ASSAY_APPLICATION (ENTRY_ID, G_NO) ;
select now();
\echo "PK_RSK_CASE_FEEDBACK_HEAD on RSK_CASE_FEEDBACK_HEAD (ENTRY_ID, CASE_ID)"
create index PK_RSK_CASE_FEEDBACK_HEAD on RSK_CASE_FEEDBACK_HEAD (ENTRY_ID, CASE_ID) ;
select now();
\echo "PK_RSK_CASE_FEEDBACK_LIST on RSK_CASE_FEEDBACK_LIST (ENTRY_ID, CASE_ID, PROC_NO)"
create index PK_RSK_CASE_FEEDBACK_LIST on RSK_CASE_FEEDBACK_LIST (ENTRY_ID, CASE_ID, PROC_NO) ;
select now();
\echo "PK_RSK_CASE_FEEDBACK_LIST_CERT on RSK_CASE_FEEDBACK_LIST_CERT (ENTRY_ID, CASE_ID, CERT_NO)"
create index PK_RSK_CASE_FEEDBACK_LIST_CERT on RSK_CASE_FEEDBACK_LIST_CERT (ENTRY_ID, CASE_ID, CERT_NO) ;
select now();
\echo "PK_RSK_CASE_TRANSFER_G_NO on RSK_CASE_TRANSFER_G_NO (ENTRY_ID, CASE_ID, G_NO)"
create index PK_RSK_CASE_TRANSFER_G_NO on RSK_CASE_TRANSFER_G_NO (ENTRY_ID, CASE_ID, G_NO) ;
select now();
\echo "PK_RSK_CASE_TRANSFER_HEAD on RSK_CASE_TRANSFER_HEAD (ENTRY_ID, CASE_ID)"
create index PK_RSK_CASE_TRANSFER_HEAD on RSK_CASE_TRANSFER_HEAD (ENTRY_ID, CASE_ID) ;
select now();
\echo "PK_RSK_CASE_TRANSFER_LIST on RSK_CASE_TRANSFER_LIST (ENTRY_ID, CASE_ID, CERT_NO)"
create index PK_RSK_CASE_TRANSFER_LIST on RSK_CASE_TRANSFER_LIST (ENTRY_ID, CASE_ID, CERT_NO) ;
select now();
\echo "PK_RSK_CODE_TS on RSK_CODE_TS (CCTS_CODE)"
create index PK_RSK_CODE_TS on RSK_CODE_TS (CCTS_CODE) ;
select now();
\echo "PK_RSK_CODE_TS_BAK on RSK_CODE_TS_BAK (CCTS_CODE, OP_BAK_TIME)"
create index PK_RSK_CODE_TS_BAK on RSK_CODE_TS_BAK (CCTS_CODE, OP_BAK_TIME) ;
select now();
\echo "PK_RSK_CONDITION on RSK_CONDITION (CCTS_CODE)"
create index PK_RSK_CONDITION on RSK_CONDITION (CCTS_CODE) ;
select now();
\echo "PK_RSK_CONDITION_BAK on RSK_CONDITION_BAK (CCTS_CODE, OP_BAK_TIME)"
create index PK_RSK_CONDITION_BAK on RSK_CONDITION_BAK (CCTS_CODE, OP_BAK_TIME) ;
select now();
\echo "PK_RSK_CONTA_CAPACITY on RSK_CONTA_CAPACITY (CCTS_CODE)"
create index PK_RSK_CONTA_CAPACITY on RSK_CONTA_CAPACITY (CCTS_CODE) ;
select now();
\echo "PK_RSK_CONTA_CAPACITY_BAK on RSK_CONTA_CAPACITY_BAK (CCTS_CODE, OP_BAK_TIME)"
create index PK_RSK_CONTA_CAPACITY_BAK on RSK_CONTA_CAPACITY_BAK (CCTS_CODE, OP_BAK_TIME) ;
select now();
\echo "PK_RSK_EXAM_HEAD_REL on RSK_EXAM_HEAD_REL (EXAM_REC_ID)"
create index PK_RSK_EXAM_HEAD_REL on RSK_EXAM_HEAD_REL (EXAM_REC_ID) ;
select now();
\echo "PK_RSK_EXAM_LIST_CONTAINER on RSK_EXAM_LIST_CONTAINER (EXAM_REC_ID, CONTAINER_ID)"
create index PK_RSK_EXAM_LIST_CONTAINER on RSK_EXAM_LIST_CONTAINER (EXAM_REC_ID, CONTAINER_ID) ;
select now();
\echo "PK_RSK_EXAM_LIST_REL on RSK_EXAM_LIST_REL (EXAM_REC_ID, G_NO)"
create index PK_RSK_EXAM_LIST_REL on RSK_EXAM_LIST_REL (EXAM_REC_ID, G_NO) ;
select now();
\echo "PK_RSK_EXAM_OP_LOG on RSK_EXAM_OP_LOG (EXAM_REC_ID, OP_TIME, MODI_TYPE, TABLE_NAME, ITEM_NAME)"
create index PK_RSK_EXAM_OP_LOG on RSK_EXAM_OP_LOG (EXAM_REC_ID, OP_TIME, MODI_TYPE, TABLE_NAME, ITEM_NAME) ;
select now();
\echo "PK_RSK_FAKE_CODE_TS on RSK_FAKE_CODE_TS (CCTS_CODE)"
create index PK_RSK_FAKE_CODE_TS on RSK_FAKE_CODE_TS (CCTS_CODE) ;
select now();
\echo "PK_RSK_FAKE_CODE_TS_BAK on RSK_FAKE_CODE_TS_BAK (CCTS_CODE, OP_BAK_TIME)"
create index PK_RSK_FAKE_CODE_TS_BAK on RSK_FAKE_CODE_TS_BAK (CCTS_CODE, OP_BAK_TIME) ;
select now();
\echo "PK_RSK_FIT_LOG_REL on RSK_FIT_LOG_REL (RSK_NO, FORM_ID, D_DATE)"
create index PK_RSK_FIT_LOG_REL on RSK_FIT_LOG_REL (RSK_NO, FORM_ID, D_DATE) ;
select now();
\echo "PK_RSK_FIT_RESULT_LOG on RSK_FIT_RESULT_LOG (RSK_NO, FORM_ID, D_DATE, RSK_POS)"
create index PK_RSK_FIT_RESULT_LOG on RSK_FIT_RESULT_LOG (RSK_NO, FORM_ID, D_DATE, RSK_POS) ;
select now();
\echo "PK_RSK_INSTR_ATTR_REL on RSK_INSTR_ATTR_REL (RSK_NO)"
create index PK_RSK_INSTR_ATTR_REL on RSK_INSTR_ATTR_REL (RSK_NO) ;
select now();
\echo "PK_RSK_INSTR_PROC_REL on RSK_INSTR_PROC_REL (RSK_NO, RSK_POS)"
create index PK_RSK_INSTR_PROC_REL on RSK_INSTR_PROC_REL (RSK_NO, RSK_POS) ;
select now();
\echo "PK_RSK_OP_LOG on RSK_OP_LOG (FORM_ID, OP_TIME)"
create index PK_RSK_OP_LOG on RSK_OP_LOG (FORM_ID, OP_TIME) ;
select now();
\echo "PK_RSK_RECHECK_REL on RSK_RECHECK_REL (FORM_ID)"
create index PK_RSK_RECHECK_REL on RSK_RECHECK_REL (FORM_ID) ;
select now();
\echo "PK_RSK_REPLICATION_LOG on RSK_REPLICATION_LOG (CUSTOMS_CODE, TABLE_NAME, REPLI_DATE)"
create index PK_RSK_REPLICATION_LOG on RSK_REPLICATION_LOG (CUSTOMS_CODE, TABLE_NAME, REPLI_DATE) ;
select now();
\echo "PK_RSK_RESULT_REL on RSK_RESULT_REL (RSK_NO, FORM_ID, RSK_POS)"
create index PK_RSK_RESULT_REL on RSK_RESULT_REL (RSK_NO, FORM_ID, RSK_POS) ;
select now();
\echo "PK_RSK_TRADE_CO on RSK_TRADE_CO (CCTS_CODE)"
create index PK_RSK_TRADE_CO on RSK_TRADE_CO (CCTS_CODE) ;
select now();
\echo "PK_RSK_TRADE_CO_BAK on RSK_TRADE_CO_BAK (CCTS_CODE, OP_BAK_TIME)"
create index PK_RSK_TRADE_CO_BAK on RSK_TRADE_CO_BAK (CCTS_CODE, OP_BAK_TIME) ;
select now();
\echo "PK_RSK_UNLOCK_OP_LOG on RSK_UNLOCK_OP_LOG (FORM_ID, RSK_NO, UNLOCK_TIME)"
create index PK_RSK_UNLOCK_OP_LOG on RSK_UNLOCK_OP_LOG (FORM_ID, RSK_NO, UNLOCK_TIME) ;
select now();
\echo "PK_RSK_VS_EXAM on RSK_VS_EXAM (FORM_ID, FORM_TYPE, RSK_NO, D_DATE, EXAM_REC_ID)"
create index PK_RSK_VS_EXAM on RSK_VS_EXAM (FORM_ID, FORM_TYPE, RSK_NO, D_DATE, EXAM_REC_ID) ;
select now();
\echo "PK_RSK_WORKFLOW on RSK_WORKFLOW (ENTRY_ID, EXAM_REC_ID)"
create index PK_RSK_WORKFLOW on RSK_WORKFLOW (ENTRY_ID, EXAM_REC_ID) ;
select now();
\echo "PK_SERVICE_FEE on SERVICE_FEE (MANUAL_NO)"
create index PK_SERVICE_FEE on SERVICE_FEE (MANUAL_NO) ;
select now();
\echo "PK_SERVICE_LIST on SERVICE_LIST (MANUAL_NO, F_NO)"
create index PK_SERVICE_LIST on SERVICE_LIST (MANUAL_NO, F_NO) ;
select now();
\echo "PK_SHIP_TONNAGE on SHIP_TONNAGE (LICENSE_NO)"
create index PK_SHIP_TONNAGE on SHIP_TONNAGE (LICENSE_NO) ;
select now();
\echo "PK_SPECIAL_ENTRY on SPECIAL_ENTRY (ENTRY_ID, OP_TIME)"
create index PK_SPECIAL_ENTRY on SPECIAL_ENTRY (ENTRY_ID, OP_TIME) ;
select now();
\echo "PK_STATUS_DETAIL on STATUS_DETAIL (ENTRY_ID, DETAIL_COUNT)"
create index PK_STATUS_DETAIL on STATUS_DETAIL (ENTRY_ID, DETAIL_COUNT) ;
select now();
\echo "PK_STF_CORP_RECORD on STF_CORP_RECORD (ENTRY_ID)"
create index PK_STF_CORP_RECORD on STF_CORP_RECORD (ENTRY_ID) ;
select now();
\echo "PK_STF_RECORD on STF_RECORD (ENTRY_ID)"
create index PK_STF_RECORD on STF_RECORD (ENTRY_ID) ;
select now();
\echo "PK_STL_DATA_CONTA_LIST on STL_DATA_CONTA_LIST (UCR_CODE, CONTAINER_ID)"
create index PK_STL_DATA_CONTA_LIST on STL_DATA_CONTA_LIST (UCR_CODE, CONTAINER_ID) ;
select now();
\echo "PK_STL_DATA_HEAD on STL_DATA_HEAD (UCR_CODE)"
create index PK_STL_DATA_HEAD on STL_DATA_HEAD (UCR_CODE) ;
select now();
\echo "PK_STL_DATA_TS_LIST on STL_DATA_TS_LIST (UCR_CODE, G_NO)"
create index PK_STL_DATA_TS_LIST on STL_DATA_TS_LIST (UCR_CODE, G_NO) ;
select now();
\echo "PK_STL_REQUEST_CHK on STL_REQUEST_CHK (UCR_CODE)"
create index PK_STL_REQUEST_CHK on STL_REQUEST_CHK (UCR_CODE) ;
select now();
\echo "PK_TAR_DEL_LOG on TAR_DEL_LOG (ENTRY_ID, TAX_ID, OP_TIME)"
create index PK_TAR_DEL_LOG on TAR_DEL_LOG (ENTRY_ID, TAX_ID, OP_TIME) ;
select now();
\echo "PK_TB_PCS on TB_PCS (PCS_NO_S)"
create index PK_TB_PCS on TB_PCS (PCS_NO_S) ;
select now();
\echo "PK_TB_PCS_HIS on TB_PCS_HIS (PCS_NO_S)"
create index PK_TB_PCS_HIS on TB_PCS_HIS (PCS_NO_S) ;
select now();
\echo "PK_TCS_COUNTER on TCS_COUNTER (TCS_KEY)"
create index PK_TCS_COUNTER on TCS_COUNTER (TCS_KEY) ;
select now();
\echo "PK_TCS_DETAIL_HEAD on TCS_DETAIL_HEAD (ACCOUNT_ORG_CODE, IN_TREASURY_DATE, PACK_NO, CURRENT_PACK_NO)"
create index PK_TCS_DETAIL_HEAD on TCS_DETAIL_HEAD (ACCOUNT_ORG_CODE, IN_TREASURY_DATE, PACK_NO, CURRENT_PACK_NO) ;
select now();
\echo "PK_TCS_DETAIL_LIST on TCS_DETAIL_LIST (ACCOUNT_ORG_CODE, IN_TREASURY_DATE, PACK_NO, ITEM_NO)"
create index PK_TCS_DETAIL_LIST on TCS_DETAIL_LIST (ACCOUNT_ORG_CODE, IN_TREASURY_DATE, PACK_NO, ITEM_NO) ;
select now();
\echo "PK_TCS_ERROR_LOG on TCS_ERROR_LOG (GUID)"
create index PK_TCS_ERROR_LOG on TCS_ERROR_LOG (GUID) ;
select now();
\echo "PK_TCS_SEND_LOG on TCS_SEND_LOG (TRANS_NO)"
create index PK_TCS_SEND_LOG on TCS_SEND_LOG (TRANS_NO) ;
select now();
\echo "PK_TCS_STATISTIC_REPORT on TCS_STATISTIC_REPORT (ACCOUNT_ORG_CODE, REPORT_DATE, SPECIAL_PERIOD_FLAG, TREASURY_CODE, BUDGET_LEVEL_CODE, BUDGET_SUBJECT_CODE)"
create index PK_TCS_STATISTIC_REPORT on TCS_STATISTIC_REPORT (ACCOUNT_ORG_CODE, REPORT_DATE, SPECIAL_PERIOD_FLAG, TREASURY_CODE, BUDGET_LEVEL_CODE, BUDGET_SUBJECT_CODE) ;
select now();
\echo "PK_TEMP_DB on TEMP_DB (PRE_NO, PROCESS_STEP)"
create index PK_TEMP_DB on TEMP_DB (PRE_NO, PROCESS_STEP) ;
select now();
\echo "PK_TEMP_DEL_EMS_CONSUME on TEMP_DEL_EMS_CONSUME (RID)"
create index PK_TEMP_DEL_EMS_CONSUME on TEMP_DEL_EMS_CONSUME (RID) ;
select now();
\echo "PK_TEMP_DEL_EMS_HEAD on TEMP_DEL_EMS_HEAD (EMS_NO)"
create index PK_TEMP_DEL_EMS_HEAD on TEMP_DEL_EMS_HEAD (EMS_NO) ;
select now();
\echo "PK_TEMP_PAGE_RANGE on TEMP_PAGE_RANGE (PR_KEY, PR_DETAIL)"
create index PK_TEMP_PAGE_RANGE on TEMP_PAGE_RANGE (PR_KEY, PR_DETAIL) ;
select now();
\echo "PK_TEP_COMPANY on TEP_COMPANY (TEP_NO)"
create index PK_TEP_COMPANY on TEP_COMPANY (TEP_NO) ;
select now();
\echo "PK_TEP_DEBIT_REC_REQUEST on TEP_DEBIT_REC_REQUEST (REQUEST_DATE, TRANS_NO)"
create index PK_TEP_DEBIT_REC_REQUEST on TEP_DEBIT_REC_REQUEST (REQUEST_DATE, TRANS_NO) ;
select now();
\echo "PK_TEP_DEBIT_REC_RESPONSE on TEP_DEBIT_REC_RESPONSE (TRANS_NO, RESPONSE_DATE)"
create index PK_TEP_DEBIT_REC_RESPONSE on TEP_DEBIT_REC_RESPONSE (TRANS_NO, RESPONSE_DATE) ;
select now();
\echo "PK_TEP_EPLAT_RESPONSE on TEP_EPLAT_RESPONSE (MSG_TYPE, CREATE_DATE)"
create index PK_TEP_EPLAT_RESPONSE on TEP_EPLAT_RESPONSE (MSG_TYPE, CREATE_DATE) ;
select now();
\echo "PK_TEP_ERR_LOG on TEP_ERR_LOG (ERR_NO, CREATE_DATE)"
create index PK_TEP_ERR_LOG on TEP_ERR_LOG (ERR_NO, CREATE_DATE) ;
select now();
\echo "PK_TEP_LOG on TEP_LOG (STEP_ID, BIZ_ID, CREATE_DATE)"
create index PK_TEP_LOG on TEP_LOG (STEP_ID, BIZ_ID, CREATE_DATE) ;
select now();
\echo "PK_TEP_PAY_LOG on TEP_PAY_LOG (TRANS_NO, EPLAT_CODE)"
create index PK_TEP_PAY_LOG on TEP_PAY_LOG (TRANS_NO, EPLAT_CODE) ;
select now();
\echo "PK_TEP_PAY_REC_REQUEST on TEP_PAY_REC_REQUEST (REQUEST_DATE, TRANS_NO)"
create index PK_TEP_PAY_REC_REQUEST on TEP_PAY_REC_REQUEST (REQUEST_DATE, TRANS_NO) ;
select now();
\echo "PK_TEP_PAY_REC_RESPONSE on TEP_PAY_REC_RESPONSE (RESPONSE_DATE, TRANS_NO)"
create index PK_TEP_PAY_REC_RESPONSE on TEP_PAY_REC_RESPONSE (RESPONSE_DATE, TRANS_NO) ;
select now();
\echo "PK_TEP_REC_LOG on TEP_REC_LOG (REC_DATE, REC_TYPE, TRANS_NO)"
create index PK_TEP_REC_LOG on TEP_REC_LOG (REC_DATE, REC_TYPE, TRANS_NO) ;
select now();
\echo "PK_TEP_SEQ on TEP_SEQ (TEP_KEY)"
create index PK_TEP_SEQ on TEP_SEQ (TEP_KEY) ;
select now();
\echo "PK_TEP_STATUS_QUERY on TEP_STATUS_QUERY (TRANS_NO, SENDER_ID, DEAL_TIME)"
create index PK_TEP_STATUS_QUERY on TEP_STATUS_QUERY (TRANS_NO, SENDER_ID, DEAL_TIME) ;
select now();
\echo "PK_TEP_VOUCHER_REC_LIST on TEP_VOUCHER_REC_LIST (VOUCHER_RECEIVABLE_SEQ_NO)"
create index PK_TEP_VOUCHER_REC_LIST on TEP_VOUCHER_REC_LIST (VOUCHER_RECEIVABLE_SEQ_NO) ;
select now();
\echo "PK_TEP_VOUCHER_REC_LIST_DETAIL on TEP_VOUCHER_REC_LIST_DETAIL (VOUCHER_RECEIVABLE_SEQ_NO, PAYEE_CODE, BANK_CODE, PAYEE_BANK_ACCOUNT)"
create index PK_TEP_VOUCHER_REC_LIST_DETAIL on TEP_VOUCHER_REC_LIST_DETAIL (VOUCHER_RECEIVABLE_SEQ_NO, PAYEE_CODE, BANK_CODE, PAYEE_BANK_ACCOUNT) ;
select now();
\echo "PK_TEP_VOUCHER_REC_PAGE_LIST on TEP_VOUCHER_REC_PAGE_LIST (VOUCHER_RECEIVABLE_SEQ_NO, PAYEE_CODE, BANK_CODE, PAYEE_BANK_ACCOUNT, PAGE_NAME, PAGE_NO)"
create index PK_TEP_VOUCHER_REC_PAGE_LIST on TEP_VOUCHER_REC_PAGE_LIST (VOUCHER_RECEIVABLE_SEQ_NO, PAYEE_CODE, BANK_CODE, PAYEE_BANK_ACCOUNT, PAGE_NAME, PAGE_NO) ;
select now();
\echo "PK_TMP_EMS_CONSUME on TMP_EMS_CONSUME (EMS_NO, EXG_NO, EXG_VERSION, IMG_NO)"
create index PK_TMP_EMS_CONSUME on TMP_EMS_CONSUME (EMS_NO, EXG_NO, EXG_VERSION, IMG_NO) ;
select now();
\echo "PK_TMP_EMS_DCR_ENT on TMP_EMS_DCR_ENT (EMS_NO, DCR_TIMES, ENTRY_ID)"
create index PK_TMP_EMS_DCR_ENT on TMP_EMS_DCR_ENT (EMS_NO, DCR_TIMES, ENTRY_ID) ;
select now();
\echo "PK_TMP_EMS_HEAD on TMP_EMS_HEAD (EMS_NO)"
create index PK_TMP_EMS_HEAD on TMP_EMS_HEAD (EMS_NO) ;
select now();
\echo "PK_TMP_EMS_LIST on TMP_EMS_LIST (EMS_NO, G_TYPE, G_NO)"
create index PK_TMP_EMS_LIST on TMP_EMS_LIST (EMS_NO, G_TYPE, G_NO) ;
select now();
\echo "PK_TRADE_ERR on TRADE_ERR (HG_CODE)"
create index PK_TRADE_ERR on TRADE_ERR (HG_CODE) ;
select now();
\echo "PK_TRADE_GPM_RTX on TRADE_GPM_RTX (TRADE_MODE, SIGN_TYPE, SIGN_MODE)"
create index PK_TRADE_GPM_RTX on TRADE_GPM_RTX (TRADE_MODE, SIGN_TYPE, SIGN_MODE) ;
select now();
\echo "PK_TRANSFER_FEE on TRANSFER_FEE (MANUAL_NO, RTN_MANUAL_NO)"
create index PK_TRANSFER_FEE on TRANSFER_FEE (MANUAL_NO, RTN_MANUAL_NO) ;
select now();
\echo "PK_TRANSFER_FEE_LOG on TRANSFER_FEE_LOG (MANUAL_NO, RTN_MANUAL_NO, CREATE_DATE)"
create index PK_TRANSFER_FEE_LOG on TRANSFER_FEE_LOG (MANUAL_NO, RTN_MANUAL_NO, CREATE_DATE) ;
select now();
\echo "PK_TRN_ALC_REL on TRN_ALC_REL (CUSTOMS_CODE, TRN_MODE, TRAF_MODE)"
create index PK_TRN_ALC_REL on TRN_ALC_REL (CUSTOMS_CODE, TRN_MODE, TRAF_MODE) ;
select now();
\echo "PK_TRN_CHECK on TRN_CHECK (NO)"
create index PK_TRN_CHECK on TRN_CHECK (NO) ;
select now();
\echo "PK_TRN_CHK_GOODS on TRN_CHK_GOODS (CHK_CODE_TS)"
create index PK_TRN_CHK_GOODS on TRN_CHK_GOODS (CHK_CODE_TS) ;
select now();
\echo "PK_TRN_COP_REL on TRN_COP_REL (CO_REG_NO)"
create index PK_TRN_COP_REL on TRN_COP_REL (CO_REG_NO) ;
select now();
\echo "PK_TRN_DELAY_FORM on TRN_DELAY_FORM (TURN_NO)"
create index PK_TRN_DELAY_FORM on TRN_DELAY_FORM (TURN_NO) ;
select now();
\echo "PK_TRN_DR_REL on TRN_DR_REL (DR_CUSTOMS_NO)"
create index PK_TRN_DR_REL on TRN_DR_REL (DR_CUSTOMS_NO) ;
select now();
\echo "PK_TRN_ESEAL_REL on TRN_ESEAL_REL (ESEAL_ID)"
create index PK_TRN_ESEAL_REL on TRN_ESEAL_REL (ESEAL_ID) ;
select now();
\echo "PK_TRN_EXAM_MAX_SEQ on TRN_EXAM_MAX_SEQ (TYPE, YEARAREA)"
create index PK_TRN_EXAM_MAX_SEQ on TRN_EXAM_MAX_SEQ (TYPE, YEARAREA) ;
select now();
\echo "PK_TRN_I_E_PORT on TRN_I_E_PORT (VE_CUSTOMS_NO, I_E_PORT)"
create index PK_TRN_I_E_PORT on TRN_I_E_PORT (VE_CUSTOMS_NO, I_E_PORT) ;
select now();
\echo "PK_TRN_PARAMETER on TRN_PARAMETER (CUSTOMS_CODE, P_NAME)"
create index PK_TRN_PARAMETER on TRN_PARAMETER (CUSTOMS_CODE, P_NAME) ;
select now();
\echo "PK_TRN_POP_COP_REL on TRN_POP_COP_REL (AGENT_CODE, CUSTOMS_CODE)"
create index PK_TRN_POP_COP_REL on TRN_POP_COP_REL (AGENT_CODE, CUSTOMS_CODE) ;
select now();
\echo "PK_TRN_POP_HEAD on TRN_POP_HEAD (APPLY_NO)"
create index PK_TRN_POP_HEAD on TRN_POP_HEAD (APPLY_NO) ;
select now();
\echo "PK_TRN_POP_LIST on TRN_POP_LIST (APPLY_NO, RECORD_NUMBER)"
create index PK_TRN_POP_LIST on TRN_POP_LIST (APPLY_NO, RECORD_NUMBER) ;
select now();
\echo "PK_TRN_PRE_MAX_SEQ on TRN_PRE_MAX_SEQ (TYPE, YEARAREA)"
create index PK_TRN_PRE_MAX_SEQ on TRN_PRE_MAX_SEQ (TYPE, YEARAREA) ;
select now();
\echo "PK_TRN_SHIP on TRN_SHIP (CUSTOM_NO)"
create index PK_TRN_SHIP on TRN_SHIP (CUSTOM_NO) ;
select now();
\echo "PK_TRN_VEHICLE on TRN_VEHICLE (CUSTOM_NO)"
create index PK_TRN_VEHICLE on TRN_VEHICLE (CUSTOM_NO) ;
select now();
\echo "PK_TRN_VE_REL on TRN_VE_REL (VE_CUSTOMS_NO)"
create index PK_TRN_VE_REL on TRN_VE_REL (VE_CUSTOMS_NO) ;
select now();
\echo "PK_YD_DECLARE_REL on YD_DECLARE_REL (TRADE_CO, CUSTOMS_CODE)"
create index PK_YD_DECLARE_REL on YD_DECLARE_REL (TRADE_CO, CUSTOMS_CODE) ;
\timing

