select now();
\timing
\echo ---------------ACCOUNT----------------
truncate ACCOUNT_GPTMP_TODAY;
\echo ---------------AGREEMENT_GOODS_LIST----------------
truncate AGREEMENT_GOODS_LIST_GPTMP_TODAY;
\echo ---------------AMS_MODI_LOG----------------
truncate AMS_MODI_LOG_GPTMP_TODAY;
\echo ---------------AMSLIST_BODY----------------
truncate AMSLIST_BODY_GPTMP_TODAY;
\echo ---------------AMSLIST_HEAD----------------
truncate AMSLIST_HEAD_GPTMP_TODAY;
\echo ---------------APPL_CLOSE----------------
truncate APPL_CLOSE_GPTMP_TODAY;
\echo ---------------APPL_CLOSE_CONSUME----------------
truncate APPL_CLOSE_CONSUME_GPTMP_TODAY;
\echo ---------------APPLY_HEAD----------------
truncate APPLY_HEAD_GPTMP_TODAY;
\echo ---------------APPLY_LIST----------------
truncate APPLY_LIST_GPTMP_TODAY;
\echo ---------------ARRIVAL_INFO_HEAD----------------
truncate ARRIVAL_INFO_HEAD_GPTMP_TODAY;
\echo ---------------ARRIVAL_INFO_LIST----------------
truncate ARRIVAL_INFO_LIST_GPTMP_TODAY;
\echo ---------------BAK_BWS_EXAM_CERT_LIST----------------
truncate BAK_BWS_EXAM_CERT_LIST_GPTMP_TODAY;
\echo ---------------BAK_BWS_EXAM_GOOD_LIST----------------
truncate BAK_BWS_EXAM_GOOD_LIST_GPTMP_TODAY;
\echo ---------------BAK_BWS_EXAM_HEAD----------------
truncate BAK_BWS_EXAM_HEAD_GPTMP_TODAY;
\echo ---------------BAK_CONSUME----------------
truncate BAK_CONSUME_GPTMP_TODAY;
\echo ---------------BAK_CONTRACT_HEAD----------------
truncate BAK_CONTRACT_HEAD_GPTMP_TODAY;
\echo ---------------BAK_DCG_BILL_HEAD----------------
truncate BAK_DCG_BILL_HEAD_GPTMP_TODAY;
\echo ---------------BAK_DCG_BILL_LIST----------------
truncate BAK_DCG_BILL_LIST_GPTMP_TODAY;
\echo ---------------BAK_DCG_DEDUCT----------------
truncate BAK_DCG_DEDUCT_GPTMP_TODAY;
\echo ---------------BAK_DCG_DEDUCT_LOG----------------
truncate BAK_DCG_DEDUCT_LOG_GPTMP_TODAY;
\echo ---------------BAK_DCG_HEAD----------------
truncate BAK_DCG_HEAD_GPTMP_TODAY;
\echo ---------------BAK_DCG_LIST----------------
truncate BAK_DCG_LIST_GPTMP_TODAY;
\echo ---------------BAK_EMS_APPR_HEAD----------------
truncate BAK_EMS_APPR_HEAD_GPTMP_TODAY;
\echo ---------------BAK_EMS_APPR_LIST----------------
truncate BAK_EMS_APPR_LIST_GPTMP_TODAY;
\echo ---------------BAK_EMS_CONSUME----------------
truncate BAK_EMS_CONSUME_GPTMP_TODAY;
\echo ---------------BAK_EMS_DEDUCT_CLR----------------
truncate BAK_EMS_DEDUCT_CLR_GPTMP_TODAY;
\echo ---------------BAK_EMS_HEAD----------------
truncate BAK_EMS_HEAD_GPTMP_TODAY;
\echo ---------------BAK_EMS_LIST----------------
truncate BAK_EMS_LIST_GPTMP_TODAY;
\echo ---------------BAK_EX_CONTRACT_LIST----------------
truncate BAK_EX_CONTRACT_LIST_GPTMP_TODAY;
\echo ---------------BAK_EX_FASCICLE_LIST----------------
truncate BAK_EX_FASCICLE_LIST_GPTMP_TODAY;
\echo ---------------BAK_FASCICLE_HEAD----------------
truncate BAK_FASCICLE_HEAD_GPTMP_TODAY;
\echo ---------------BAK_IM_CONTRACT_LIST----------------
truncate BAK_IM_CONTRACT_LIST_GPTMP_TODAY;
\echo ---------------BAK_IM_FASCICLE_LIST----------------
truncate BAK_IM_FASCICLE_LIST_GPTMP_TODAY;
\echo ---------------BANK_ACCOUNT----------------
truncate BANK_ACCOUNT_GPTMP_TODAY;
\echo ---------------BCK_COP_HEAD----------------
truncate BCK_COP_HEAD_GPTMP_TODAY;
\echo ---------------BCK_COP_LIST----------------
truncate BCK_COP_LIST_GPTMP_TODAY;
\echo ---------------BCK_COP_LIST_TEMP----------------
truncate BCK_COP_LIST_TEMP_GPTMP_TODAY;
\echo ---------------BCK_COP_PARA_HEAD----------------
truncate BCK_COP_PARA_HEAD_GPTMP_TODAY;
\echo ---------------BCK_COP_PARA_LIST----------------
truncate BCK_COP_PARA_LIST_GPTMP_TODAY;
\echo ---------------BCK_EXECUTOR----------------
truncate BCK_EXECUTOR_GPTMP_TODAY;
\echo ---------------BCK_HANDOVER----------------
truncate BCK_HANDOVER_GPTMP_TODAY;
\echo ---------------BCK_HANDOVER_TYPE----------------
truncate BCK_HANDOVER_TYPE_GPTMP_TODAY;
\echo ---------------BCK_HEAD----------------
truncate BCK_HEAD_GPTMP_TODAY;
\echo ---------------BCK_SEQ----------------
truncate BCK_SEQ_GPTMP_TODAY;
\echo ---------------BCK_STOCK_HEAD----------------
truncate BCK_STOCK_HEAD_GPTMP_TODAY;
\echo ---------------BCK_STOCK_LIST----------------
truncate BCK_STOCK_LIST_GPTMP_TODAY;
\echo ---------------BCK_WORKFLOW----------------
truncate BCK_WORKFLOW_GPTMP_TODAY;
\echo ---------------BTI_DATA_CONTA_LIST----------------
truncate BTI_DATA_CONTA_LIST_GPTMP_TODAY;
\echo ---------------BTI_DATA_HEAD----------------
truncate BTI_DATA_HEAD_GPTMP_TODAY;
\echo ---------------BTI_DATA_TS_LIST----------------
truncate BTI_DATA_TS_LIST_GPTMP_TODAY;
\echo ---------------BWS_AUDIT_HEAD----------------
truncate BWS_AUDIT_HEAD_GPTMP_TODAY;
\echo ---------------BWS_AUDIT_LIST----------------
truncate BWS_AUDIT_LIST_GPTMP_TODAY;
\echo ---------------BWS_DCR_BILL_LIST----------------
truncate BWS_DCR_BILL_LIST_GPTMP_TODAY;
\echo ---------------BWS_DCR_HEAD----------------
truncate BWS_DCR_HEAD_GPTMP_TODAY;
\echo ---------------BWS_DCR_LIST----------------
truncate BWS_DCR_LIST_GPTMP_TODAY;
\echo ---------------BWS_DEDUCT----------------
truncate BWS_DEDUCT_GPTMP_TODAY;
\echo ---------------BWS_DEDUCT_LOG----------------
truncate BWS_DEDUCT_LOG_GPTMP_TODAY;
\echo ---------------BWS_EXAM_CERT_LIST----------------
truncate BWS_EXAM_CERT_LIST_GPTMP_TODAY;
\echo ---------------BWS_EXAM_GOOD_LIST----------------
truncate BWS_EXAM_GOOD_LIST_GPTMP_TODAY;
\echo ---------------BWS_EXAM_HEAD----------------
truncate BWS_EXAM_HEAD_GPTMP_TODAY;
\echo ---------------BWS_EXAM_PASSCERT----------------
truncate BWS_EXAM_PASSCERT_GPTMP_TODAY;
\echo ---------------BWS_FORM_HEAD----------------
truncate BWS_FORM_HEAD_GPTMP_TODAY;
\echo ---------------BWS_FORM_LIST----------------
truncate BWS_FORM_LIST_GPTMP_TODAY;
\echo ---------------BWS_GB_LIST----------------
truncate BWS_GB_LIST_GPTMP_TODAY;
\echo ---------------BWS_HEAD----------------
truncate BWS_HEAD_GPTMP_TODAY;
\echo ---------------BWS_LIST----------------
truncate BWS_LIST_GPTMP_TODAY;
\echo ---------------BWS_MANIFEST_HEAD----------------
truncate BWS_MANIFEST_HEAD_GPTMP_TODAY;
\echo ---------------BWS_MANIFEST_LIST----------------
truncate BWS_MANIFEST_LIST_GPTMP_TODAY;
\echo ---------------BWS_SEQ----------------
truncate BWS_SEQ_GPTMP_TODAY;
\echo ---------------BWS_VAR----------------
truncate BWS_VAR_GPTMP_TODAY;
\echo ---------------BWS_WORKFLOW----------------
truncate BWS_WORKFLOW_GPTMP_TODAY;
\echo ---------------CCTS_ERROR_LOG----------------
truncate CCTS_ERROR_LOG_GPTMP_TODAY;
\echo ---------------CCTS_ONLINE_RESULT----------------
truncate CCTS_ONLINE_RESULT_GPTMP_TODAY;
\echo ---------------CCTS_ONLINE_RESULT_BAK----------------
truncate CCTS_ONLINE_RESULT_BAK_GPTMP_TODAY;
\echo ---------------CCTS_PERFORMANCE----------------
truncate CCTS_PERFORMANCE_GPTMP_TODAY;
\echo ---------------CCTS_RSK_RESULT----------------
truncate CCTS_RSK_RESULT_GPTMP_TODAY;
\echo ---------------CCTS_RSK_RESULT_BAK----------------
truncate CCTS_RSK_RESULT_BAK_GPTMP_TODAY;
\echo ---------------CDL_CERTIFICATE----------------
truncate CDL_CERTIFICATE_GPTMP_TODAY;
\echo ---------------CDL_CHK----------------
truncate CDL_CHK_GPTMP_TODAY;
\echo ---------------CDL_COMMODITY----------------
truncate CDL_COMMODITY_GPTMP_TODAY;
\echo ---------------CDL_COMP_COMM_MODIFY_LOG----------------
truncate CDL_COMP_COMM_MODIFY_LOG_GPTMP_TODAY;
\echo ---------------CDL_COMP_COMM_OP_LOG----------------
truncate CDL_COMP_COMM_OP_LOG_GPTMP_TODAY;
\echo ---------------CDL_COMPANY----------------
truncate CDL_COMPANY_GPTMP_TODAY;
\echo ---------------CDL_CONTAINER----------------
truncate CDL_CONTAINER_GPTMP_TODAY;
\echo ---------------CDL_DEL_CERTIFICATE_LOG----------------
truncate CDL_DEL_CERTIFICATE_LOG_GPTMP_TODAY;
\echo ---------------CDL_DEL_CONTAINER_LOG----------------
truncate CDL_DEL_CONTAINER_LOG_GPTMP_TODAY;
\echo ---------------CDL_DEL_HEAD_LOG----------------
truncate CDL_DEL_HEAD_LOG_GPTMP_TODAY;
\echo ---------------CDL_DEL_LIST_LOG----------------
truncate CDL_DEL_LIST_LOG_GPTMP_TODAY;
\echo ---------------CDL_EDI_MESS----------------
truncate CDL_EDI_MESS_GPTMP_TODAY;
\echo ---------------CDL_EMS_DEDUCT----------------
truncate CDL_EMS_DEDUCT_GPTMP_TODAY;
\echo ---------------CDL_EMS_DEDUCT_LOG----------------
truncate CDL_EMS_DEDUCT_LOG_GPTMP_TODAY;
\echo ---------------CDL_ENTRY_HEAD----------------
truncate CDL_ENTRY_HEAD_GPTMP_TODAY;
\echo ---------------CDL_ENTRY_LIST----------------
truncate CDL_ENTRY_LIST_GPTMP_TODAY;
\echo ---------------CDL_HEAD----------------
truncate CDL_HEAD_GPTMP_TODAY;
\echo ---------------CDL_LICENSE_DEDUCT----------------
truncate CDL_LICENSE_DEDUCT_GPTMP_TODAY;
\echo ---------------CDL_LIST----------------
truncate CDL_LIST_GPTMP_TODAY;
\echo ---------------CDL_LOCK_COMMODITY----------------
truncate CDL_LOCK_COMMODITY_GPTMP_TODAY;
\echo ---------------CDL_MODI_LOG----------------
truncate CDL_MODI_LOG_GPTMP_TODAY;
\echo ---------------CDL_OP_LOG----------------
truncate CDL_OP_LOG_GPTMP_TODAY;
\echo ---------------CDL_OVERDUE_LIST----------------
truncate CDL_OVERDUE_LIST_GPTMP_TODAY;
\echo ---------------CDL_STATUS_DETAIL----------------
truncate CDL_STATUS_DETAIL_GPTMP_TODAY;
\echo ---------------CDL_WORKFLOW----------------
truncate CDL_WORKFLOW_GPTMP_TODAY;
\echo ---------------CHK_COP_RATIO----------------
truncate CHK_COP_RATIO_GPTMP_TODAY;
\echo ---------------CHK_COUNTER----------------
truncate CHK_COUNTER_GPTMP_TODAY;
\echo ---------------CHK_RATE_LIMIT----------------
truncate CHK_RATE_LIMIT_GPTMP_TODAY;
\echo ---------------CHKHS_MNLPROC----------------
truncate CHKHS_MNLPROC_GPTMP_TODAY;
\echo ---------------CIC_CODE----------------
truncate CIC_CODE_GPTMP_TODAY;
\echo ---------------CIC_HEAD----------------
truncate CIC_HEAD_GPTMP_TODAY;
\echo ---------------CIC_LIST----------------
truncate CIC_LIST_GPTMP_TODAY;
\echo ---------------CIC_MAXID----------------
truncate CIC_MAXID_GPTMP_TODAY;
\echo ---------------CIC_SEND_REL----------------
truncate CIC_SEND_REL_GPTMP_TODAY;
\echo ---------------CLAIM----------------
truncate CLAIM_GPTMP_TODAY;
\echo ---------------CLC_CHKRATE_LIMIT----------------
truncate CLC_CHKRATE_LIMIT_GPTMP_TODAY;
\echo ---------------CLC_GPR_RATIO----------------
truncate CLC_GPR_RATIO_GPTMP_TODAY;
\echo ---------------CLC_GPR_RATIO_BAK----------------
truncate CLC_GPR_RATIO_BAK_GPTMP_TODAY;
\echo ---------------CNS_COUNTER_TABLE----------------
truncate CNS_COUNTER_TABLE_GPTMP_TODAY;
\echo ---------------CO_CLASS_REL----------------
truncate CO_CLASS_REL_GPTMP_TODAY;
\echo ---------------COMPANY_REL----------------
truncate COMPANY_REL_GPTMP_TODAY;
\echo ---------------CONSUME----------------
truncate CONSUME_GPTMP_TODAY;
\echo ---------------CONSUME_DB----------------
truncate CONSUME_DB_GPTMP_TODAY;
\echo ---------------CONSUME_GOODS----------------
truncate CONSUME_GOODS_GPTMP_TODAY;
\echo ---------------CONTA----------------
truncate CONTA_GPTMP_TODAY;
\echo ---------------CONTA_MONITOR----------------
truncate CONTA_MONITOR_GPTMP_TODAY;
\echo ---------------CONTRACT_HEAD----------------
truncate CONTRACT_HEAD_GPTMP_TODAY;
\echo ---------------CONTRACT_WORKFLOW----------------
truncate CONTRACT_WORKFLOW_GPTMP_TODAY;
\echo ---------------CONVEYANCE----------------
truncate CONVEYANCE_GPTMP_TODAY;
\echo ---------------CONVEYANCE_SEGMENT----------------
truncate CONVEYANCE_SEGMENT_GPTMP_TODAY;
\echo ---------------COP_CONSUME----------------
truncate COP_CONSUME_GPTMP_TODAY;
\echo ---------------COP_SPEC_REL----------------
truncate COP_SPEC_REL_GPTMP_TODAY;
\echo ---------------COPLOG_DELETE_REL----------------
truncate COPLOG_DELETE_REL_GPTMP_TODAY;
\echo ---------------COPLOG_MODIFY_REL----------------
truncate COPLOG_MODIFY_REL_GPTMP_TODAY;
\echo ---------------CORP_HEAD----------------
truncate CORP_HEAD_GPTMP_TODAY;
\echo ---------------CORP_LIST----------------
truncate CORP_LIST_GPTMP_TODAY;
\echo ---------------CORP_TABLE----------------
truncate CORP_TABLE_GPTMP_TODAY;
\echo ---------------CORP_TYPE----------------
truncate CORP_TYPE_GPTMP_TODAY;
\echo ---------------COUNTER_TABLE----------------
truncate COUNTER_TABLE_GPTMP_TODAY;
\echo ---------------CREDIT_INFO----------------
truncate CREDIT_INFO_GPTMP_TODAY;
\echo ---------------CTS_CHKRATE_LIMIT----------------
truncate CTS_CHKRATE_LIMIT_GPTMP_TODAY;
\echo ---------------CTS_CHKRATE_LIMIT_BAK----------------
truncate CTS_CHKRATE_LIMIT_BAK_GPTMP_TODAY;
\echo ---------------CTS_PERIOD----------------
truncate CTS_PERIOD_GPTMP_TODAY;
\echo ---------------CUS_GOOD_CONSUME----------------
truncate CUS_GOOD_CONSUME_GPTMP_TODAY;
\echo ---------------CUSTOMS_DEFAULT----------------
truncate CUSTOMS_DEFAULT_GPTMP_TODAY;
\echo ---------------CUSTOMS_ESEAL_CONFIG----------------
truncate CUSTOMS_ESEAL_CONFIG_GPTMP_TODAY;
\echo ---------------DCG_BAK_LIST----------------
truncate DCG_BAK_LIST_GPTMP_TODAY;
\echo ---------------DCG_BILL_HEAD----------------
truncate DCG_BILL_HEAD_GPTMP_TODAY;
\echo ---------------DCG_BILL_LIST----------------
truncate DCG_BILL_LIST_GPTMP_TODAY;
\echo ---------------DCG_COPR_INFO----------------
truncate DCG_COPR_INFO_GPTMP_TODAY;
\echo ---------------DCG_DEDUCT----------------
truncate DCG_DEDUCT_GPTMP_TODAY;
\echo ---------------DCG_DEDUCT_LOG----------------
truncate DCG_DEDUCT_LOG_GPTMP_TODAY;
\echo ---------------DCG_HEAD----------------
truncate DCG_HEAD_GPTMP_TODAY;
\echo ---------------DCG_LIST----------------
truncate DCG_LIST_GPTMP_TODAY;
\echo ---------------DCG_SEQ----------------
truncate DCG_SEQ_GPTMP_TODAY;
\echo ---------------DCG_WORKFLOW----------------
truncate DCG_WORKFLOW_GPTMP_TODAY;
\echo ---------------DECL_CO_ENTRY_COUNT----------------
truncate DECL_CO_ENTRY_COUNT_GPTMP_TODAY;
\echo ---------------DECL_CO_ENTRY_COUNT_TEMP----------------
truncate DECL_CO_ENTRY_COUNT_TEMP_GPTMP_TODAY;
\echo ---------------DECLAR_COUNTER_REL----------------
truncate DECLAR_COUNTER_REL_GPTMP_TODAY;
\echo ---------------DECLAR_REL----------------
truncate DECLAR_REL_GPTMP_TODAY;
\echo ---------------DECLARER_REL----------------
truncate DECLARER_REL_GPTMP_TODAY;
\echo ---------------DECLOG_FULL_REL----------------
truncate DECLOG_FULL_REL_GPTMP_TODAY;
\echo ---------------DECLOG_MOD_REL----------------
truncate DECLOG_MOD_REL_GPTMP_TODAY;
\echo ---------------DECLOG_MODIFY_REL----------------
truncate DECLOG_MODIFY_REL_GPTMP_TODAY;
\echo ---------------DECLOG_SCORE_HEAD----------------
truncate DECLOG_SCORE_HEAD_GPTMP_TODAY;
\echo ---------------DECLOG_SCORE_LIST----------------
truncate DECLOG_SCORE_LIST_GPTMP_TODAY;
\echo ---------------DEL_EGS_ARC_AGENT_LIST----------------
truncate DEL_EGS_ARC_AGENT_LIST_GPTMP_TODAY;
\echo ---------------DEL_EGS_ARC_HEAD----------------
truncate DEL_EGS_ARC_HEAD_GPTMP_TODAY;
\echo ---------------DEL_EGS_ARC_LIST----------------
truncate DEL_EGS_ARC_LIST_GPTMP_TODAY;
\echo ---------------DEL_EGS_ARC_MERCHANT_LIST----------------
truncate DEL_EGS_ARC_MERCHANT_LIST_GPTMP_TODAY;
\echo ---------------DEL_EGS_CLEAR_CERT----------------
truncate DEL_EGS_CLEAR_CERT_GPTMP_TODAY;
\echo ---------------DEL_EGS_CLEAR_HEAD----------------
truncate DEL_EGS_CLEAR_HEAD_GPTMP_TODAY;
\echo ---------------DEL_EGS_CLEAR_LIST----------------
truncate DEL_EGS_CLEAR_LIST_GPTMP_TODAY;
\echo ---------------DEL_EGS_DECLARE_CERT----------------
truncate DEL_EGS_DECLARE_CERT_GPTMP_TODAY;
\echo ---------------DEL_EGS_DECLARE_HEAD----------------
truncate DEL_EGS_DECLARE_HEAD_GPTMP_TODAY;
\echo ---------------DEL_EGS_DECLARE_LIST----------------
truncate DEL_EGS_DECLARE_LIST_GPTMP_TODAY;
\echo ---------------DEL_MOD_APPLY----------------
truncate DEL_MOD_APPLY_GPTMP_TODAY;
\echo ---------------DISTRIBUTIVE_BILL_DECLARE----------------
truncate DISTRIBUTIVE_BILL_DECLARE_GPTMP_TODAY;
\echo ---------------DISTRIBUTIVE_DECLARE----------------
truncate DISTRIBUTIVE_DECLARE_GPTMP_TODAY;
\echo ---------------DISTRIBUTIVE_TRANSIT_WAY----------------
truncate DISTRIBUTIVE_TRANSIT_WAY_GPTMP_TODAY;
\echo ---------------DST_COUNTER_TABLE----------------
truncate DST_COUNTER_TABLE_GPTMP_TODAY;
\echo ---------------DST_DEDUCT----------------
truncate DST_DEDUCT_GPTMP_TODAY;
\echo ---------------DST_EXG----------------
truncate DST_EXG_GPTMP_TODAY;
\echo ---------------DST_EXG_ORI_ENTRY----------------
truncate DST_EXG_ORI_ENTRY_GPTMP_TODAY;
\echo ---------------DST_HEAD----------------
truncate DST_HEAD_GPTMP_TODAY;
\echo ---------------DST_IMG----------------
truncate DST_IMG_GPTMP_TODAY;
\echo ---------------DST_IMG_ORI_ENTRY----------------
truncate DST_IMG_ORI_ENTRY_GPTMP_TODAY;
\echo ---------------DTT_COP_PARAM----------------
truncate DTT_COP_PARAM_GPTMP_TODAY;
\echo ---------------DUTY_CHECK_LOG----------------
truncate DUTY_CHECK_LOG_GPTMP_TODAY;
\echo ---------------DUTYFORM_HEAD----------------
truncate DUTYFORM_HEAD_GPTMP_TODAY;
\echo ---------------DUTYFORM_LIST----------------
truncate DUTYFORM_LIST_GPTMP_TODAY;
\echo ---------------ECO_HEAD----------------
truncate ECO_HEAD_GPTMP_TODAY;
\echo ---------------ECO_LIST----------------
truncate ECO_LIST_GPTMP_TODAY;
\echo ---------------ECO_PARTS----------------
truncate ECO_PARTS_GPTMP_TODAY;
\echo ---------------ECO_WORKFLOW----------------
truncate ECO_WORKFLOW_GPTMP_TODAY;
\echo ---------------EGS_ADMIT_HEAD----------------
truncate EGS_ADMIT_HEAD_GPTMP_TODAY;
\echo ---------------EGS_ADMIT_HS----------------
truncate EGS_ADMIT_HS_GPTMP_TODAY;
\echo ---------------EGS_ADMIT_LIST----------------
truncate EGS_ADMIT_LIST_GPTMP_TODAY;
\echo ---------------EGS_ARC_AGENT_LIST----------------
truncate EGS_ARC_AGENT_LIST_GPTMP_TODAY;
\echo ---------------EGS_ARC_HEAD----------------
truncate EGS_ARC_HEAD_GPTMP_TODAY;
\echo ---------------EGS_ARC_LIST----------------
truncate EGS_ARC_LIST_GPTMP_TODAY;
\echo ---------------EGS_ARC_MERCHANT_LIST----------------
truncate EGS_ARC_MERCHANT_LIST_GPTMP_TODAY;
\echo ---------------EGS_CHECK_LOG----------------
truncate EGS_CHECK_LOG_GPTMP_TODAY;
\echo ---------------EGS_CLEAR_CERT----------------
truncate EGS_CLEAR_CERT_GPTMP_TODAY;
\echo ---------------EGS_CLEAR_HEAD----------------
truncate EGS_CLEAR_HEAD_GPTMP_TODAY;
\echo ---------------EGS_CLEAR_LIST----------------
truncate EGS_CLEAR_LIST_GPTMP_TODAY;
\echo ---------------EGS_DECLARE_CERT----------------
truncate EGS_DECLARE_CERT_GPTMP_TODAY;
\echo ---------------EGS_DECLARE_HEAD----------------
truncate EGS_DECLARE_HEAD_GPTMP_TODAY;
\echo ---------------EGS_DECLARE_LIST----------------
truncate EGS_DECLARE_LIST_GPTMP_TODAY;
\echo ---------------EGS_DEDUCT----------------
truncate EGS_DEDUCT_GPTMP_TODAY;
\echo ---------------EGS_LEND_HEAD----------------
truncate EGS_LEND_HEAD_GPTMP_TODAY;
\echo ---------------EGS_LEND_LIST----------------
truncate EGS_LEND_LIST_GPTMP_TODAY;
\echo ---------------EGS_PATROL_HEAD----------------
truncate EGS_PATROL_HEAD_GPTMP_TODAY;
\echo ---------------EGS_PATROL_LIST----------------
truncate EGS_PATROL_LIST_GPTMP_TODAY;
\echo ---------------EGS_SEQ----------------
truncate EGS_SEQ_GPTMP_TODAY;
\echo ---------------EGS_WORKFLOW----------------
truncate EGS_WORKFLOW_GPTMP_TODAY;
\echo ---------------EMS_ACCOUNT----------------
truncate EMS_ACCOUNT_GPTMP_TODAY;
\echo ---------------EMS_APPR_HEAD----------------
truncate EMS_APPR_HEAD_GPTMP_TODAY;
\echo ---------------EMS_APPR_LIST----------------
truncate EMS_APPR_LIST_GPTMP_TODAY;
\echo ---------------EMS_CLAIM----------------
truncate EMS_CLAIM_GPTMP_TODAY;
\echo ---------------EMS_CLR_LIST----------------
truncate EMS_CLR_LIST_GPTMP_TODAY;
\echo ---------------EMS_CLR_TMP----------------
truncate EMS_CLR_TMP_GPTMP_TODAY;
\echo ---------------EMS_COMPLEX----------------
truncate EMS_COMPLEX_GPTMP_TODAY;
\echo ---------------EMS_COMPLEX2----------------
truncate EMS_COMPLEX2_GPTMP_TODAY;
\echo ---------------EMS_CONSUME----------------
truncate EMS_CONSUME_GPTMP_TODAY;
\echo ---------------EMS_CONSUME_CLR----------------
truncate EMS_CONSUME_CLR_GPTMP_TODAY;
\echo ---------------EMS_CONSUME_CLR_D----------------
truncate EMS_CONSUME_CLR_D_GPTMP_TODAY;
\echo ---------------EMS_DCR_CONSUME----------------
truncate EMS_DCR_CONSUME_GPTMP_TODAY;
\echo ---------------EMS_DCR_ENT----------------
truncate EMS_DCR_ENT_GPTMP_TODAY;
\echo ---------------EMS_DCR_HEAD----------------
truncate EMS_DCR_HEAD_GPTMP_TODAY;
\echo ---------------EMS_DCR_LIST----------------
truncate EMS_DCR_LIST_GPTMP_TODAY;
\echo ---------------EMS_DCR_RUB_LIST----------------
truncate EMS_DCR_RUB_LIST_GPTMP_TODAY;
\echo ---------------EMS_DEDUCT----------------
truncate EMS_DEDUCT_GPTMP_TODAY;
\echo ---------------EMS_DEDUCT_CLR----------------
truncate EMS_DEDUCT_CLR_GPTMP_TODAY;
\echo ---------------EMS_DEDUCT_LOG----------------
truncate EMS_DEDUCT_LOG_GPTMP_TODAY;
\echo ---------------EMS_ENP----------------
truncate EMS_ENP_GPTMP_TODAY;
\echo ---------------EMS_ENP_JOU----------------
truncate EMS_ENP_JOU_GPTMP_TODAY;
\echo ---------------EMS_HEAD----------------
truncate EMS_HEAD_GPTMP_TODAY;
\echo ---------------EMS_LIST----------------
truncate EMS_LIST_GPTMP_TODAY;
\echo ---------------EMS_MESSAGE_LOG----------------
truncate EMS_MESSAGE_LOG_GPTMP_TODAY;
\echo ---------------EMS_PRESS----------------
truncate EMS_PRESS_GPTMP_TODAY;
\echo ---------------EMS_PRESS_CLEAR----------------
truncate EMS_PRESS_CLEAR_GPTMP_TODAY;
\echo ---------------EMS_SEQ----------------
truncate EMS_SEQ_GPTMP_TODAY;
\echo ---------------EMS_TMP_CLR----------------
truncate EMS_TMP_CLR_GPTMP_TODAY;
\echo ---------------EMS_VAR----------------
truncate EMS_VAR_GPTMP_TODAY;
\echo ---------------EMS_VERIFY----------------
truncate EMS_VERIFY_GPTMP_TODAY;
\echo ---------------EMS_VERIFY_DETAIL----------------
truncate EMS_VERIFY_DETAIL_GPTMP_TODAY;
\echo ---------------EMS_WORKFLOW----------------
truncate EMS_WORKFLOW_GPTMP_TODAY;
\echo ---------------ENTRY_AUTOREL_ERR_LIST----------------
truncate ENTRY_AUTOREL_ERR_LIST_GPTMP_TODAY;
\echo ---------------ENTRY_AUTOREL_ERR_LOG----------------
truncate ENTRY_AUTOREL_ERR_LOG_GPTMP_TODAY;
\echo ---------------ENTRY_CENTRY_SELECT----------------
truncate ENTRY_CENTRY_SELECT_GPTMP_TODAY;
\echo ---------------ENTRY_CENTRY_SELECT_DEL----------------
truncate ENTRY_CENTRY_SELECT_DEL_GPTMP_TODAY;
\echo ---------------ENTRY_CERTIFICATE----------------
truncate ENTRY_CERTIFICATE_GPTMP_TODAY;
\echo ---------------ENTRY_CERTIFICATE_LOG----------------
truncate ENTRY_CERTIFICATE_LOG_GPTMP_TODAY;
\echo ---------------ENTRY_CONTAINER----------------
truncate ENTRY_CONTAINER_GPTMP_TODAY;
\echo ---------------ENTRY_CONTAINER_LOG----------------
truncate ENTRY_CONTAINER_LOG_GPTMP_TODAY;
\echo ---------------ENTRY_DEL_HEAD_LOG----------------
truncate ENTRY_DEL_HEAD_LOG_GPTMP_TODAY;
\echo ---------------ENTRY_DEL_LIST_LOG----------------
truncate ENTRY_DEL_LIST_LOG_GPTMP_TODAY;
\echo ---------------ENTRY_EVALUATION----------------
truncate ENTRY_EVALUATION_GPTMP_TODAY;
\echo ---------------ENTRY_GPM_RTX----------------
truncate ENTRY_GPM_RTX_GPTMP_TODAY;
\echo ---------------ENTRY_GPM_RTX_PRINTLOG----------------
truncate ENTRY_GPM_RTX_PRINTLOG_GPTMP_TODAY;
\echo ---------------ENTRY_GPM_RTX_SENDLOG----------------
truncate ENTRY_GPM_RTX_SENDLOG_GPTMP_TODAY;
\echo ---------------ENTRY_HEAD----------------
truncate ENTRY_HEAD_GPTMP_TODAY;
\echo ---------------ENTRY_LIST----------------
truncate ENTRY_LIST_GPTMP_TODAY;
\echo ---------------ENTRY_MODI_LOG----------------
truncate ENTRY_MODI_LOG_GPTMP_TODAY;
\echo ---------------ENTRY_OP_LOG----------------
truncate ENTRY_OP_LOG_GPTMP_TODAY;
\echo ---------------ENTRY_PROC----------------
truncate ENTRY_PROC_GPTMP_TODAY;
\echo ---------------ENTRY_PROC_LOG----------------
truncate ENTRY_PROC_LOG_GPTMP_TODAY;
\echo ---------------ENTRY_QUERY----------------
truncate ENTRY_QUERY_GPTMP_TODAY;
\echo ---------------ENTRY_WORKFLOW----------------
truncate ENTRY_WORKFLOW_GPTMP_TODAY;
\echo ---------------EPA_CHEM_CERT----------------
truncate EPA_CHEM_CERT_GPTMP_TODAY;
\echo ---------------EPA_CHK----------------
truncate EPA_CHK_GPTMP_TODAY;
\echo ---------------EPA_SCARP_CERT----------------
truncate EPA_SCARP_CERT_GPTMP_TODAY;
\echo ---------------ERR_LOG----------------
truncate ERR_LOG_GPTMP_TODAY;
\echo ---------------EX_APPL_CLOSE----------------
truncate EX_APPL_CLOSE_GPTMP_TODAY;
\echo ---------------EX_ARRIVAL_CONTA----------------
truncate EX_ARRIVAL_CONTA_GPTMP_TODAY;
\echo ---------------EX_ARRIVAL_ERR_CHK----------------
truncate EX_ARRIVAL_ERR_CHK_GPTMP_TODAY;
\echo ---------------EX_ARRIVAL_SHIP----------------
truncate EX_ARRIVAL_SHIP_GPTMP_TODAY;
\echo ---------------EX_CDL_MNL_DEDUCT----------------
truncate EX_CDL_MNL_DEDUCT_GPTMP_TODAY;
\echo ---------------EX_CONTA_ENTRY_CHK----------------
truncate EX_CONTA_ENTRY_CHK_GPTMP_TODAY;
\echo ---------------EX_CONTRACT_CLEAR----------------
truncate EX_CONTRACT_CLEAR_GPTMP_TODAY;
\echo ---------------EX_CONTRACT_DEDUC----------------
truncate EX_CONTRACT_DEDUC_GPTMP_TODAY;
\echo ---------------EX_CONTRACT_LIST----------------
truncate EX_CONTRACT_LIST_GPTMP_TODAY;
\echo ---------------EX_COP_RATE----------------
truncate EX_COP_RATE_GPTMP_TODAY;
\echo ---------------EX_DECL_ALARM_HEAD----------------
truncate EX_DECL_ALARM_HEAD_GPTMP_TODAY;
\echo ---------------EX_DECL_ALARM_LIST----------------
truncate EX_DECL_ALARM_LIST_GPTMP_TODAY;
\echo ---------------EX_DECL_CUR_HEAD----------------
truncate EX_DECL_CUR_HEAD_GPTMP_TODAY;
\echo ---------------EX_DECL_CUR_LIST----------------
truncate EX_DECL_CUR_LIST_GPTMP_TODAY;
\echo ---------------EX_DECL_HIS_HEAD----------------
truncate EX_DECL_HIS_HEAD_GPTMP_TODAY;
\echo ---------------EX_DECL_HIS_LIST----------------
truncate EX_DECL_HIS_LIST_GPTMP_TODAY;
\echo ---------------EX_ELE_HEAD----------------
truncate EX_ELE_HEAD_GPTMP_TODAY;
\echo ---------------EX_ELE_LIST----------------
truncate EX_ELE_LIST_GPTMP_TODAY;
\echo ---------------EX_EXAM_JOU----------------
truncate EX_EXAM_JOU_GPTMP_TODAY;
\echo ---------------EX_EXAM_MANA_HEAD----------------
truncate EX_EXAM_MANA_HEAD_GPTMP_TODAY;
\echo ---------------EX_EXAM_MANA_LIST----------------
truncate EX_EXAM_MANA_LIST_GPTMP_TODAY;
\echo ---------------EX_FASCICLE_LIST----------------
truncate EX_FASCICLE_LIST_GPTMP_TODAY;
\echo ---------------EX_LIC_CODE_TS----------------
truncate EX_LIC_CODE_TS_GPTMP_TODAY;
\echo ---------------EX_TRAN_JOU----------------
truncate EX_TRAN_JOU_GPTMP_TODAY;
\echo ---------------EX_TRANS_ALARM_CONTA_REL----------------
truncate EX_TRANS_ALARM_CONTA_REL_GPTMP_TODAY;
\echo ---------------EX_TRANS_ALARM_GOODS_CONTA_REL----------------
truncate EX_TRANS_ALARM_GOODS_CONTA_REL_GPTMP_TODAY;
\echo ---------------EX_TRANS_ALARM_LIST_REL----------------
truncate EX_TRANS_ALARM_LIST_REL_GPTMP_TODAY;
\echo ---------------EX_TRANS_CONTA_REL----------------
truncate EX_TRANS_CONTA_REL_GPTMP_TODAY;
\echo ---------------EX_TRANS_GOODS_CONTA_REL----------------
truncate EX_TRANS_GOODS_CONTA_REL_GPTMP_TODAY;
\echo ---------------EX_TRANS_HIS_CONTA_REL----------------
truncate EX_TRANS_HIS_CONTA_REL_GPTMP_TODAY;
\echo ---------------EX_TRANS_HIS_GOODS_CONTA_REL----------------
truncate EX_TRANS_HIS_GOODS_CONTA_REL_GPTMP_TODAY;
\echo ---------------EX_TRANS_HIS_LIST_REL----------------
truncate EX_TRANS_HIS_LIST_REL_GPTMP_TODAY;
\echo ---------------EX_TRANS_LIST_REL----------------
truncate EX_TRANS_LIST_REL_GPTMP_TODAY;
\echo ---------------EX_TRN_ARRIVAL_CONTA----------------
truncate EX_TRN_ARRIVAL_CONTA_GPTMP_TODAY;
\echo ---------------EX_TRN_CONTA_ENTRY_ARV----------------
truncate EX_TRN_CONTA_ENTRY_ARV_GPTMP_TODAY;
\echo ---------------EX_TRN_CONTA_ENTRY_CHK----------------
truncate EX_TRN_CONTA_ENTRY_CHK_GPTMP_TODAY;
\echo ---------------EXA_APPL_CLOSE----------------
truncate EXA_APPL_CLOSE_GPTMP_TODAY;
\echo ---------------EXAM_CONTA_END_LOG----------------
truncate EXAM_CONTA_END_LOG_GPTMP_TODAY;
\echo ---------------EXAM_CONTA_HEAD----------------
truncate EXAM_CONTA_HEAD_GPTMP_TODAY;
\echo ---------------EXAM_CONTA_LIST----------------
truncate EXAM_CONTA_LIST_GPTMP_TODAY;
\echo ---------------EXC_ELE----------------
truncate EXC_ELE_GPTMP_TODAY;
\echo ---------------EXC_EX_CHK----------------
truncate EXC_EX_CHK_GPTMP_TODAY;
\echo ---------------EXC_EXAM----------------
truncate EXC_EXAM_GPTMP_TODAY;
\echo ---------------EXP_MFT_CHK_RESULT----------------
truncate EXP_MFT_CHK_RESULT_GPTMP_TODAY;
\echo ---------------EXTERNAL_JOU----------------
truncate EXTERNAL_JOU_GPTMP_TODAY;
\echo ---------------FASCICLE_HEAD----------------
truncate FASCICLE_HEAD_GPTMP_TODAY;
\echo ---------------FCB_CHK----------------
truncate FCB_CHK_GPTMP_TODAY;
\echo ---------------FCB_CONTA----------------
truncate FCB_CONTA_GPTMP_TODAY;
\echo ---------------FCB_CONTA_MODI----------------
truncate FCB_CONTA_MODI_GPTMP_TODAY;
\echo ---------------FCB_HEAD----------------
truncate FCB_HEAD_GPTMP_TODAY;
\echo ---------------FCB_HEAD_MODI----------------
truncate FCB_HEAD_MODI_GPTMP_TODAY;
\echo ---------------FCB_LIST----------------
truncate FCB_LIST_GPTMP_TODAY;
\echo ---------------FCB_LIST_MODI----------------
truncate FCB_LIST_MODI_GPTMP_TODAY;
\echo ---------------FCB_RSK----------------
truncate FCB_RSK_GPTMP_TODAY;
\echo ---------------FCB_WORKFLOW----------------
truncate FCB_WORKFLOW_GPTMP_TODAY;
\echo ---------------FEE_INVOICE----------------
truncate FEE_INVOICE_GPTMP_TODAY;
\echo ---------------FORFEIT_FORM----------------
truncate FORFEIT_FORM_GPTMP_TODAY;
\echo ---------------FORM_CHK----------------
truncate FORM_CHK_GPTMP_TODAY;
\echo ---------------GUARANTEE_DEL_LOG----------------
truncate GUARANTEE_DEL_LOG_GPTMP_TODAY;
\echo ---------------GUARANTEE_LIST----------------
truncate GUARANTEE_LIST_GPTMP_TODAY;
\echo ---------------GUARANTEE_R----------------
truncate GUARANTEE_R_GPTMP_TODAY;
\echo ---------------H2000_SMS_SEND----------------
truncate H2000_SMS_SEND_GPTMP_TODAY;
\echo ---------------H2000_SMS_SENDLOG----------------
truncate H2000_SMS_SENDLOG_GPTMP_TODAY;
\echo ---------------HIS_TRN_COP_REL----------------
truncate HIS_TRN_COP_REL_GPTMP_TODAY;
\echo ---------------HIS_TRN_DR_REL----------------
truncate HIS_TRN_DR_REL_GPTMP_TODAY;
\echo ---------------HIS_TRN_ESEAL_REL----------------
truncate HIS_TRN_ESEAL_REL_GPTMP_TODAY;
\echo ---------------HIS_TRN_VE_REL----------------
truncate HIS_TRN_VE_REL_GPTMP_TODAY;
\echo ---------------IM_APPL_CLOSE----------------
truncate IM_APPL_CLOSE_GPTMP_TODAY;
\echo ---------------IM_CDL_MNL_DEDUCT----------------
truncate IM_CDL_MNL_DEDUCT_GPTMP_TODAY;
\echo ---------------IM_CONTRACT_CLEAR----------------
truncate IM_CONTRACT_CLEAR_GPTMP_TODAY;
\echo ---------------IM_CONTRACT_DEDUC----------------
truncate IM_CONTRACT_DEDUC_GPTMP_TODAY;
\echo ---------------IM_CONTRACT_LIST----------------
truncate IM_CONTRACT_LIST_GPTMP_TODAY;
\echo ---------------IM_COP_RATE----------------
truncate IM_COP_RATE_GPTMP_TODAY;
\echo ---------------IM_DECL_ALARM_HEAD----------------
truncate IM_DECL_ALARM_HEAD_GPTMP_TODAY;
\echo ---------------IM_DECL_ALARM_LIST----------------
truncate IM_DECL_ALARM_LIST_GPTMP_TODAY;
\echo ---------------IM_DECL_CUR_HEAD----------------
truncate IM_DECL_CUR_HEAD_GPTMP_TODAY;
\echo ---------------IM_DECL_CUR_LIST----------------
truncate IM_DECL_CUR_LIST_GPTMP_TODAY;
\echo ---------------IM_DECL_HIS_HEAD----------------
truncate IM_DECL_HIS_HEAD_GPTMP_TODAY;
\echo ---------------IM_DECL_HIS_LIST----------------
truncate IM_DECL_HIS_LIST_GPTMP_TODAY;
\echo ---------------IM_ELE_HEAD----------------
truncate IM_ELE_HEAD_GPTMP_TODAY;
\echo ---------------IM_ELE_LIST----------------
truncate IM_ELE_LIST_GPTMP_TODAY;
\echo ---------------IM_EXAM_JOU----------------
truncate IM_EXAM_JOU_GPTMP_TODAY;
\echo ---------------IM_EXAM_MANA_HEAD----------------
truncate IM_EXAM_MANA_HEAD_GPTMP_TODAY;
\echo ---------------IM_EXAM_MANA_LIST----------------
truncate IM_EXAM_MANA_LIST_GPTMP_TODAY;
\echo ---------------IM_FASCICLE_LIST----------------
truncate IM_FASCICLE_LIST_GPTMP_TODAY;
\echo ---------------IM_LIC_CODE_TS----------------
truncate IM_LIC_CODE_TS_GPTMP_TODAY;
\echo ---------------IM_TRAN_JOU----------------
truncate IM_TRAN_JOU_GPTMP_TODAY;
\echo ---------------IM_TRANS_ALARM_CONTA_REL----------------
truncate IM_TRANS_ALARM_CONTA_REL_GPTMP_TODAY;
\echo ---------------IM_TRANS_ALARM_GOODS_CONTA_REL----------------
truncate IM_TRANS_ALARM_GOODS_CONTA_REL_GPTMP_TODAY;
\echo ---------------IM_TRANS_ALARM_LIST_REL----------------
truncate IM_TRANS_ALARM_LIST_REL_GPTMP_TODAY;
\echo ---------------IM_TRANS_CONTA_REL----------------
truncate IM_TRANS_CONTA_REL_GPTMP_TODAY;
\echo ---------------IM_TRANS_GOODS_CONTA_REL----------------
truncate IM_TRANS_GOODS_CONTA_REL_GPTMP_TODAY;
\echo ---------------IM_TRANS_HIS_CONTA_REL----------------
truncate IM_TRANS_HIS_CONTA_REL_GPTMP_TODAY;
\echo ---------------IM_TRANS_HIS_GOODS_CONTA_REL----------------
truncate IM_TRANS_HIS_GOODS_CONTA_REL_GPTMP_TODAY;
\echo ---------------IM_TRANS_HIS_LIST_REL----------------
truncate IM_TRANS_HIS_LIST_REL_GPTMP_TODAY;
\echo ---------------IM_TRANS_LIST_REL----------------
truncate IM_TRANS_LIST_REL_GPTMP_TODAY;
\echo ---------------IMA_APPL_CLOSE----------------
truncate IMA_APPL_CLOSE_GPTMP_TODAY;
\echo ---------------INCOME_INFO----------------
truncate INCOME_INFO_GPTMP_TODAY;
\echo ---------------INVESTER_REL----------------
truncate INVESTER_REL_GPTMP_TODAY;
\echo ---------------INVLOG_REL----------------
truncate INVLOG_REL_GPTMP_TODAY;
\echo ---------------JOB_PARAMETER----------------
truncate JOB_PARAMETER_GPTMP_TODAY;
\echo ---------------LSP_CHK----------------
truncate LSP_CHK_GPTMP_TODAY;
\echo ---------------LSP_HEAD----------------
truncate LSP_HEAD_GPTMP_TODAY;
\echo ---------------LSP_LIST----------------
truncate LSP_LIST_GPTMP_TODAY;
\echo ---------------MAIL_FILE----------------
truncate MAIL_FILE_GPTMP_TODAY;
\echo ---------------MANA_REL----------------
truncate MANA_REL_GPTMP_TODAY;
\echo ---------------MANIFEST_CHK----------------
truncate MANIFEST_CHK_GPTMP_TODAY;
\echo ---------------MANIFEST_CHK_LOG----------------
truncate MANIFEST_CHK_LOG_GPTMP_TODAY;
\echo ---------------MANIFEST_CONTA----------------
truncate MANIFEST_CONTA_GPTMP_TODAY;
\echo ---------------MANIFEST_EXCH_LOG----------------
truncate MANIFEST_EXCH_LOG_GPTMP_TODAY;
\echo ---------------MANIFEST_EXCH_LOG_BAK----------------
truncate MANIFEST_EXCH_LOG_BAK_GPTMP_TODAY;
\echo ---------------MANIFEST_HEAD----------------
truncate MANIFEST_HEAD_GPTMP_TODAY;
\echo ---------------MANIFEST_HEAD_XMS_LOG----------------
truncate MANIFEST_HEAD_XMS_LOG_GPTMP_TODAY;
\echo ---------------MANIFEST_LIST----------------
truncate MANIFEST_LIST_GPTMP_TODAY;
\echo ---------------MANIFEST_LIST_CONTA----------------
truncate MANIFEST_LIST_CONTA_GPTMP_TODAY;
\echo ---------------MANIFEST_LIST_LOG----------------
truncate MANIFEST_LIST_LOG_GPTMP_TODAY;
\echo ---------------MANIFEST_LIST_RSKINFO_LOG----------------
truncate MANIFEST_LIST_RSKINFO_LOG_GPTMP_TODAY;
\echo ---------------MNL_PARA----------------
truncate MNL_PARA_GPTMP_TODAY;
\echo ---------------MNL_PRESS----------------
truncate MNL_PRESS_GPTMP_TODAY;
\echo ---------------MNL_RECEIVE_RECEIPT----------------
truncate MNL_RECEIVE_RECEIPT_GPTMP_TODAY;
\echo ---------------MNL_SEQ----------------
truncate MNL_SEQ_GPTMP_TODAY;
\echo ---------------MNLBAK_ACCOUNT----------------
truncate MNLBAK_ACCOUNT_GPTMP_TODAY;
\echo ---------------MNLBAK_APPL_CLOSE----------------
truncate MNLBAK_APPL_CLOSE_GPTMP_TODAY;
\echo ---------------MNLBAK_CLAIM----------------
truncate MNLBAK_CLAIM_GPTMP_TODAY;
\echo ---------------MNLBAK_CONSUME----------------
truncate MNLBAK_CONSUME_GPTMP_TODAY;
\echo ---------------MNLBAK_CONTRACT_HEAD----------------
truncate MNLBAK_CONTRACT_HEAD_GPTMP_TODAY;
\echo ---------------MNLBAK_CONTRACT_WORKFLOW----------------
truncate MNLBAK_CONTRACT_WORKFLOW_GPTMP_TODAY;
\echo ---------------MNLBAK_EX_CONTRACT_CLEAR----------------
truncate MNLBAK_EX_CONTRACT_CLEAR_GPTMP_TODAY;
\echo ---------------MNLBAK_EX_CONTRACT_DEDUC----------------
truncate MNLBAK_EX_CONTRACT_DEDUC_GPTMP_TODAY;
\echo ---------------MNLBAK_EX_CONTRACT_LIST----------------
truncate MNLBAK_EX_CONTRACT_LIST_GPTMP_TODAY;
\echo ---------------MNLBAK_EX_FASCICLE_LIST----------------
truncate MNLBAK_EX_FASCICLE_LIST_GPTMP_TODAY;
\echo ---------------MNLBAK_FASCICLE_HEAD----------------
truncate MNLBAK_FASCICLE_HEAD_GPTMP_TODAY;
\echo ---------------MNLBAK_FEE_INVOICE----------------
truncate MNLBAK_FEE_INVOICE_GPTMP_TODAY;
\echo ---------------MNLBAK_IM_CONTRACT_CLEAR----------------
truncate MNLBAK_IM_CONTRACT_CLEAR_GPTMP_TODAY;
\echo ---------------MNLBAK_IM_CONTRACT_DEDUC----------------
truncate MNLBAK_IM_CONTRACT_DEDUC_GPTMP_TODAY;
\echo ---------------MNLBAK_IM_CONTRACT_LIST----------------
truncate MNLBAK_IM_CONTRACT_LIST_GPTMP_TODAY;
\echo ---------------MNLBAK_IM_FASCICLE_LIST----------------
truncate MNLBAK_IM_FASCICLE_LIST_GPTMP_TODAY;
\echo ---------------MNLBAK_PRESS_CLEAR----------------
truncate MNLBAK_PRESS_CLEAR_GPTMP_TODAY;
\echo ---------------MNLBAK_SERVICE_FEE----------------
truncate MNLBAK_SERVICE_FEE_GPTMP_TODAY;
\echo ---------------MNLBAK_SERVICE_LIST----------------
truncate MNLBAK_SERVICE_LIST_GPTMP_TODAY;
\echo ---------------MOD_PROJECT_HEAD----------------
truncate MOD_PROJECT_HEAD_GPTMP_TODAY;
\echo ---------------MOD_PROJECT_LIST----------------
truncate MOD_PROJECT_LIST_GPTMP_TODAY;
\echo ---------------MOD_RED_HEAD----------------
truncate MOD_RED_HEAD_GPTMP_TODAY;
\echo ---------------MOD_RED_LIST----------------
truncate MOD_RED_LIST_GPTMP_TODAY;
\echo ---------------NONENTRY_CHK_RESULT----------------
truncate NONENTRY_CHK_RESULT_GPTMP_TODAY;
\echo ---------------NORSK_COMPANY----------------
truncate NORSK_COMPANY_GPTMP_TODAY;
\echo ---------------NORSK_COMPANY_BAK----------------
truncate NORSK_COMPANY_BAK_GPTMP_TODAY;
\echo ---------------NORSK_CONDITION----------------
truncate NORSK_CONDITION_GPTMP_TODAY;
\echo ---------------NORSK_CONDITION_BAK----------------
truncate NORSK_CONDITION_BAK_GPTMP_TODAY;
\echo ---------------NORSK_TRADE_MODE----------------
truncate NORSK_TRADE_MODE_GPTMP_TODAY;
\echo ---------------NORSK_TRADE_MODE_BAK----------------
truncate NORSK_TRADE_MODE_BAK_GPTMP_TODAY;
\echo ---------------OCC_ELE_HEAD----------------
truncate OCC_ELE_HEAD_GPTMP_TODAY;
\echo ---------------OCC_ELE_LIST----------------
truncate OCC_ELE_LIST_GPTMP_TODAY;
\echo ---------------OCC_EXAM----------------
truncate OCC_EXAM_GPTMP_TODAY;
\echo ---------------OCC_RECEIPT----------------
truncate OCC_RECEIPT_GPTMP_TODAY;
\echo ---------------OTHER_STF_RECORD----------------
truncate OTHER_STF_RECORD_GPTMP_TODAY;
\echo ---------------PAPERLESS_SELFSAVE_CERT----------------
truncate PAPERLESS_SELFSAVE_CERT_GPTMP_TODAY;
\echo ---------------PAYOUT_REMIT_HEAD----------------
truncate PAYOUT_REMIT_HEAD_GPTMP_TODAY;
\echo ---------------PAYOUT_REMIT_LIST----------------
truncate PAYOUT_REMIT_LIST_GPTMP_TODAY;
\echo ---------------PES_CANCEL----------------
truncate PES_CANCEL_GPTMP_TODAY;
\echo ---------------PES_NOTE----------------
truncate PES_NOTE_GPTMP_TODAY;
\echo ---------------PES_WORKFLOW----------------
truncate PES_WORKFLOW_GPTMP_TODAY;
\echo ---------------PORT_BIND_REL----------------
truncate PORT_BIND_REL_GPTMP_TODAY;
\echo ---------------PRE_APPL_CLOSE----------------
truncate PRE_APPL_CLOSE_GPTMP_TODAY;
\echo ---------------PRE_APPL_CLOSE_CONSUME----------------
truncate PRE_APPL_CLOSE_CONSUME_GPTMP_TODAY;
\echo ---------------PRE_CDL_COMMODITY----------------
truncate PRE_CDL_COMMODITY_GPTMP_TODAY;
\echo ---------------PRE_CDL_COMPANY----------------
truncate PRE_CDL_COMPANY_GPTMP_TODAY;
\echo ---------------PRE_COMPANY_REL----------------
truncate PRE_COMPANY_REL_GPTMP_TODAY;
\echo ---------------PRE_CONSUME----------------
truncate PRE_CONSUME_GPTMP_TODAY;
\echo ---------------PRE_CONTRACT_HEAD----------------
truncate PRE_CONTRACT_HEAD_GPTMP_TODAY;
\echo ---------------PRE_DECL_REL----------------
truncate PRE_DECL_REL_GPTMP_TODAY;
\echo ---------------PRE_EX_APPL_CLOSE----------------
truncate PRE_EX_APPL_CLOSE_GPTMP_TODAY;
\echo ---------------PRE_EX_CONTRACT_LIST----------------
truncate PRE_EX_CONTRACT_LIST_GPTMP_TODAY;
\echo ---------------PRE_EX_FASCICLE_LIST----------------
truncate PRE_EX_FASCICLE_LIST_GPTMP_TODAY;
\echo ---------------PRE_EXA_APPL_CLOSE----------------
truncate PRE_EXA_APPL_CLOSE_GPTMP_TODAY;
\echo ---------------PRE_FASCICLE_HEAD----------------
truncate PRE_FASCICLE_HEAD_GPTMP_TODAY;
\echo ---------------PRE_IM_APPL_CLOSE----------------
truncate PRE_IM_APPL_CLOSE_GPTMP_TODAY;
\echo ---------------PRE_IM_CONTRACT_LIST----------------
truncate PRE_IM_CONTRACT_LIST_GPTMP_TODAY;
\echo ---------------PRE_IM_FASCICLE_LIST----------------
truncate PRE_IM_FASCICLE_LIST_GPTMP_TODAY;
\echo ---------------PRE_IMA_APPL_CLOSE----------------
truncate PRE_IMA_APPL_CLOSE_GPTMP_TODAY;
\echo ---------------PRE_INVESTER_REL----------------
truncate PRE_INVESTER_REL_GPTMP_TODAY;
\echo ---------------PRE_MANA_REL----------------
truncate PRE_MANA_REL_GPTMP_TODAY;
\echo ---------------PRE_PROJECT_HEAD----------------
truncate PRE_PROJECT_HEAD_GPTMP_TODAY;
\echo ---------------PRE_PROJECT_LIST----------------
truncate PRE_PROJECT_LIST_GPTMP_TODAY;
\echo ---------------PRE_RED_HEAD----------------
truncate PRE_RED_HEAD_GPTMP_TODAY;
\echo ---------------PRE_RED_LIST----------------
truncate PRE_RED_LIST_GPTMP_TODAY;
\echo ---------------PRE_REL_ALC_WORK----------------
truncate PRE_REL_ALC_WORK_GPTMP_TODAY;
\echo ---------------PRESS_CLEAR----------------
truncate PRESS_CLEAR_GPTMP_TODAY;
\echo ---------------PRICE_LIBRARY----------------
truncate PRICE_LIBRARY_GPTMP_TODAY;
\echo ---------------PRICE_LIBRARY_ENTRY----------------
truncate PRICE_LIBRARY_ENTRY_GPTMP_TODAY;
\echo ---------------PRICE_LIBRARY_MAN----------------
truncate PRICE_LIBRARY_MAN_GPTMP_TODAY;
\echo ---------------PRICE_LIBRARY_RISK----------------
truncate PRICE_LIBRARY_RISK_GPTMP_TODAY;
\echo ---------------PROJECT_HEAD----------------
truncate PROJECT_HEAD_GPTMP_TODAY;
\echo ---------------PROJECT_LIST----------------
truncate PROJECT_LIST_GPTMP_TODAY;
\echo ---------------PROJECT_MAX_NO----------------
truncate PROJECT_MAX_NO_GPTMP_TODAY;
\echo ---------------PROJECT_MAX_NO_2007----------------
truncate PROJECT_MAX_NO_2007_GPTMP_TODAY;
\echo ---------------RAM_HEAD----------------
truncate RAM_HEAD_GPTMP_TODAY;
\echo ---------------RAM_LIST----------------
truncate RAM_LIST_GPTMP_TODAY;
\echo ---------------RAM_PRINT_LOG----------------
truncate RAM_PRINT_LOG_GPTMP_TODAY;
\echo ---------------RAM_RG_COP_OWNER----------------
truncate RAM_RG_COP_OWNER_GPTMP_TODAY;
\echo ---------------RAM_RG_COP_PROJECT----------------
truncate RAM_RG_COP_PROJECT_GPTMP_TODAY;
\echo ---------------RAM_RG_COPINFO----------------
truncate RAM_RG_COPINFO_GPTMP_TODAY;
\echo ---------------RAM_RG_HEAD----------------
truncate RAM_RG_HEAD_GPTMP_TODAY;
\echo ---------------RAM_RN_INFO----------------
truncate RAM_RN_INFO_GPTMP_TODAY;
\echo ---------------RAM_RY_COMMUNICATION----------------
truncate RAM_RY_COMMUNICATION_GPTMP_TODAY;
\echo ---------------RAM_STATUS----------------
truncate RAM_STATUS_GPTMP_TODAY;
\echo ---------------RAM_STATUS_LIST----------------
truncate RAM_STATUS_LIST_GPTMP_TODAY;
\echo ---------------RAM_STATUS_MODI_LOG----------------
truncate RAM_STATUS_MODI_LOG_GPTMP_TODAY;
\echo ---------------RCP_INCOME_HEAD----------------
truncate RCP_INCOME_HEAD_GPTMP_TODAY;
\echo ---------------RCP_INCOME_HEAD_BAK----------------
truncate RCP_INCOME_HEAD_BAK_GPTMP_TODAY;
\echo ---------------RCP_INCOME_LIST----------------
truncate RCP_INCOME_LIST_GPTMP_TODAY;
\echo ---------------RCP_INCOME_LIST_BAK----------------
truncate RCP_INCOME_LIST_BAK_GPTMP_TODAY;
\echo ---------------RCP_PAYMENT_HEAD----------------
truncate RCP_PAYMENT_HEAD_GPTMP_TODAY;
\echo ---------------RCP_PAYMENT_HEAD_BAK----------------
truncate RCP_PAYMENT_HEAD_BAK_GPTMP_TODAY;
\echo ---------------RCP_PAYMENT_LIST----------------
truncate RCP_PAYMENT_LIST_GPTMP_TODAY;
\echo ---------------RCP_PAYMENT_LIST_BAK----------------
truncate RCP_PAYMENT_LIST_BAK_GPTMP_TODAY;
\echo ---------------RCP_RECORD_HEAD----------------
truncate RCP_RECORD_HEAD_GPTMP_TODAY;
\echo ---------------RCP_RECORD_HEAD_BAK----------------
truncate RCP_RECORD_HEAD_BAK_GPTMP_TODAY;
\echo ---------------RCP_RECORD_LIST----------------
truncate RCP_RECORD_LIST_GPTMP_TODAY;
\echo ---------------RCP_RECORD_LIST_BAK----------------
truncate RCP_RECORD_LIST_BAK_GPTMP_TODAY;
\echo ---------------RCP_WORKFLOW----------------
truncate RCP_WORKFLOW_GPTMP_TODAY;
\echo ---------------RED_ENTRY_HEAD----------------
truncate RED_ENTRY_HEAD_GPTMP_TODAY;
\echo ---------------RED_ENTRY_LIST----------------
truncate RED_ENTRY_LIST_GPTMP_TODAY;
\echo ---------------RED_FEE_INVOICE----------------
truncate RED_FEE_INVOICE_GPTMP_TODAY;
\echo ---------------RED_HEAD----------------
truncate RED_HEAD_GPTMP_TODAY;
\echo ---------------RED_LIST----------------
truncate RED_LIST_GPTMP_TODAY;
\echo ---------------RED_MAX_NO----------------
truncate RED_MAX_NO_GPTMP_TODAY;
\echo ---------------RED_MAX_NO_2007----------------
truncate RED_MAX_NO_2007_GPTMP_TODAY;
\echo ---------------RED_RECEIVE_RECEIPT----------------
truncate RED_RECEIVE_RECEIPT_GPTMP_TODAY;
\echo ---------------RED_SERVICE_FEE----------------
truncate RED_SERVICE_FEE_GPTMP_TODAY;
\echo ---------------REL_ALC_WORK----------------
truncate REL_ALC_WORK_GPTMP_TODAY;
\echo ---------------RETURN_REL----------------
truncate RETURN_REL_GPTMP_TODAY;
\echo ---------------RISK_CONTROL----------------
truncate RISK_CONTROL_GPTMP_TODAY;
\echo ---------------RSK_ASSAY_APPLICATION----------------
truncate RSK_ASSAY_APPLICATION_GPTMP_TODAY;
\echo ---------------RSK_CASE_FEEDBACK_HEAD----------------
truncate RSK_CASE_FEEDBACK_HEAD_GPTMP_TODAY;
\echo ---------------RSK_CASE_FEEDBACK_LIST----------------
truncate RSK_CASE_FEEDBACK_LIST_GPTMP_TODAY;
\echo ---------------RSK_CASE_FEEDBACK_LIST_CERT----------------
truncate RSK_CASE_FEEDBACK_LIST_CERT_GPTMP_TODAY;
\echo ---------------RSK_CASE_TRANSFER_G_NO----------------
truncate RSK_CASE_TRANSFER_G_NO_GPTMP_TODAY;
\echo ---------------RSK_CASE_TRANSFER_HEAD----------------
truncate RSK_CASE_TRANSFER_HEAD_GPTMP_TODAY;
\echo ---------------RSK_CASE_TRANSFER_LIST----------------
truncate RSK_CASE_TRANSFER_LIST_GPTMP_TODAY;
\echo ---------------RSK_CODE_TS----------------
truncate RSK_CODE_TS_GPTMP_TODAY;
\echo ---------------RSK_CODE_TS_BAK----------------
truncate RSK_CODE_TS_BAK_GPTMP_TODAY;
\echo ---------------RSK_CONDITION----------------
truncate RSK_CONDITION_GPTMP_TODAY;
\echo ---------------RSK_CONDITION_BAK----------------
truncate RSK_CONDITION_BAK_GPTMP_TODAY;
\echo ---------------RSK_CONTA_CAPACITY----------------
truncate RSK_CONTA_CAPACITY_GPTMP_TODAY;
\echo ---------------RSK_CONTA_CAPACITY_BAK----------------
truncate RSK_CONTA_CAPACITY_BAK_GPTMP_TODAY;
\echo ---------------RSK_EXAM_HEAD_REL----------------
truncate RSK_EXAM_HEAD_REL_GPTMP_TODAY;
\echo ---------------RSK_EXAM_LIST_CONTAINER----------------
truncate RSK_EXAM_LIST_CONTAINER_GPTMP_TODAY;
\echo ---------------RSK_EXAM_LIST_REL----------------
truncate RSK_EXAM_LIST_REL_GPTMP_TODAY;
\echo ---------------RSK_EXAM_OP_LOG----------------
truncate RSK_EXAM_OP_LOG_GPTMP_TODAY;
\echo ---------------RSK_FAKE_CODE_TS----------------
truncate RSK_FAKE_CODE_TS_GPTMP_TODAY;
\echo ---------------RSK_FAKE_CODE_TS_BAK----------------
truncate RSK_FAKE_CODE_TS_BAK_GPTMP_TODAY;
\echo ---------------RSK_FIT_LOG_REL----------------
truncate RSK_FIT_LOG_REL_GPTMP_TODAY;
\echo ---------------RSK_FIT_RESULT_LOG----------------
truncate RSK_FIT_RESULT_LOG_GPTMP_TODAY;
\echo ---------------RSK_INSTR_ATTR_REL----------------
truncate RSK_INSTR_ATTR_REL_GPTMP_TODAY;
\echo ---------------RSK_INSTR_PROC_REL----------------
truncate RSK_INSTR_PROC_REL_GPTMP_TODAY;
\echo ---------------RSK_OP_LOG----------------
truncate RSK_OP_LOG_GPTMP_TODAY;
\echo ---------------RSK_RECHECK_REL----------------
truncate RSK_RECHECK_REL_GPTMP_TODAY;
\echo ---------------RSK_REPLICATION_LOG----------------
truncate RSK_REPLICATION_LOG_GPTMP_TODAY;
\echo ---------------RSK_RESULT_REL----------------
truncate RSK_RESULT_REL_GPTMP_TODAY;
\echo ---------------RSK_TRADE_CO----------------
truncate RSK_TRADE_CO_GPTMP_TODAY;
\echo ---------------RSK_TRADE_CO_BAK----------------
truncate RSK_TRADE_CO_BAK_GPTMP_TODAY;
\echo ---------------RSK_UNLOCK_OP_LOG----------------
truncate RSK_UNLOCK_OP_LOG_GPTMP_TODAY;
\echo ---------------RSK_VS_EXAM----------------
truncate RSK_VS_EXAM_GPTMP_TODAY;
\echo ---------------RSK_WORKFLOW----------------
truncate RSK_WORKFLOW_GPTMP_TODAY;
\echo ---------------SERVICE_FEE----------------
truncate SERVICE_FEE_GPTMP_TODAY;
\echo ---------------SERVICE_LIST----------------
truncate SERVICE_LIST_GPTMP_TODAY;
\echo ---------------SHIP_TONNAGE----------------
truncate SHIP_TONNAGE_GPTMP_TODAY;
\echo ---------------SPECIAL_ENTRY----------------
truncate SPECIAL_ENTRY_GPTMP_TODAY;
\echo ---------------STATUS_DETAIL----------------
truncate STATUS_DETAIL_GPTMP_TODAY;
\echo ---------------STATUS_DETAIL----------------
truncate STATUS_DETAIL_GPTMP_TODAY;
\echo ---------------STF_RECORD----------------
truncate STF_RECORD_GPTMP_TODAY;
\echo ---------------STL_DATA_CONTA_LIST----------------
truncate STL_DATA_CONTA_LIST_GPTMP_TODAY;
\echo ---------------STL_DATA_HEAD----------------
truncate STL_DATA_HEAD_GPTMP_TODAY;
\echo ---------------STL_DATA_TS_LIST----------------
truncate STL_DATA_TS_LIST_GPTMP_TODAY;
\echo ---------------STL_REQUEST_CHK----------------
truncate STL_REQUEST_CHK_GPTMP_TODAY;
\echo ---------------TAR_DEL_LOG----------------
truncate TAR_DEL_LOG_GPTMP_TODAY;
\echo ---------------TCS_COUNTER----------------
truncate TCS_COUNTER_GPTMP_TODAY;
\echo ---------------TCS_DETAIL_HEAD----------------
truncate TCS_DETAIL_HEAD_GPTMP_TODAY;
\echo ---------------TCS_DETAIL_LIST----------------
truncate TCS_DETAIL_LIST_GPTMP_TODAY;
\echo ---------------TCS_ERROR_LOG----------------
truncate TCS_ERROR_LOG_GPTMP_TODAY;
\echo ---------------TCS_SEND_LOG----------------
truncate TCS_SEND_LOG_GPTMP_TODAY;
\echo ---------------TCS_STATISTIC_REPORT----------------
truncate TCS_STATISTIC_REPORT_GPTMP_TODAY;
\echo ---------------TEMP_DB----------------
truncate TEMP_DB_GPTMP_TODAY;
\echo ---------------TEMP_DEL_EMS_CONSUME----------------
truncate TEMP_DEL_EMS_CONSUME_GPTMP_TODAY;
\echo ---------------TEMP_DEL_EMS_HEAD----------------
truncate TEMP_DEL_EMS_HEAD_GPTMP_TODAY;
\echo ---------------TEMP_PAGE_RANGE----------------
truncate TEMP_PAGE_RANGE_GPTMP_TODAY;
\echo ---------------TEP_COMPANY----------------
truncate TEP_COMPANY_GPTMP_TODAY;
\echo ---------------TEP_DEBIT_REC_REQUEST----------------
truncate TEP_DEBIT_REC_REQUEST_GPTMP_TODAY;
\echo ---------------TEP_DEBIT_REC_RESPONSE----------------
truncate TEP_DEBIT_REC_RESPONSE_GPTMP_TODAY;
\echo ---------------TEP_EPLAT_RESPONSE----------------
truncate TEP_EPLAT_RESPONSE_GPTMP_TODAY;
\echo ---------------TEP_ERR_LOG----------------
truncate TEP_ERR_LOG_GPTMP_TODAY;
\echo ---------------TEP_LOG----------------
truncate TEP_LOG_GPTMP_TODAY;
\echo ---------------TEP_PAY_LOG----------------
truncate TEP_PAY_LOG_GPTMP_TODAY;
\echo ---------------TEP_PAY_REC_REQUEST----------------
truncate TEP_PAY_REC_REQUEST_GPTMP_TODAY;
\echo ---------------TEP_PAY_REC_RESPONSE----------------
truncate TEP_PAY_REC_RESPONSE_GPTMP_TODAY;
\echo ---------------TEP_REC_LOG----------------
truncate TEP_REC_LOG_GPTMP_TODAY;
\echo ---------------TEP_SEQ----------------
truncate TEP_SEQ_GPTMP_TODAY;
\echo ---------------TEP_STATUS_QUERY----------------
truncate TEP_STATUS_QUERY_GPTMP_TODAY;
\echo ---------------TEP_VOUCHER_REC_LIST----------------
truncate TEP_VOUCHER_REC_LIST_GPTMP_TODAY;
\echo ---------------TEP_VOUCHER_REC_LIST_DETAIL----------------
truncate TEP_VOUCHER_REC_LIST_DETAIL_GPTMP_TODAY;
\echo ---------------TEP_VOUCHER_REC_PAGE_LIST----------------
truncate TEP_VOUCHER_REC_PAGE_LIST_GPTMP_TODAY;
\echo ---------------TMP_EMS_CONSUME----------------
truncate TMP_EMS_CONSUME_GPTMP_TODAY;
\echo ---------------TMP_EMS_DCR_ENT----------------
truncate TMP_EMS_DCR_ENT_GPTMP_TODAY;
\echo ---------------TMP_EMS_HEAD----------------
truncate TMP_EMS_HEAD_GPTMP_TODAY;
\echo ---------------TMP_EMS_LIST----------------
truncate TMP_EMS_LIST_GPTMP_TODAY;
\echo ---------------TRADE_ERR----------------
truncate TRADE_ERR_GPTMP_TODAY;
\echo ---------------TRADE_GPM_RTX----------------
truncate TRADE_GPM_RTX_GPTMP_TODAY;
\echo ---------------TRANSFER_FEE----------------
truncate TRANSFER_FEE_GPTMP_TODAY;
\echo ---------------TRANSFER_FEE_LOG----------------
truncate TRANSFER_FEE_LOG_GPTMP_TODAY;
\echo ---------------TRN_ALC_REL----------------
truncate TRN_ALC_REL_GPTMP_TODAY;
\echo ---------------TRN_CHECK----------------
truncate TRN_CHECK_GPTMP_TODAY;
\echo ---------------TRN_CHK_GOODS----------------
truncate TRN_CHK_GOODS_GPTMP_TODAY;
\echo ---------------TRN_COP_REL----------------
truncate TRN_COP_REL_GPTMP_TODAY;
\echo ---------------TRN_DELAY_FORM----------------
truncate TRN_DELAY_FORM_GPTMP_TODAY;
\echo ---------------TRN_DR_REL----------------
truncate TRN_DR_REL_GPTMP_TODAY;
\echo ---------------TRN_ESEAL_REL----------------
truncate TRN_ESEAL_REL_GPTMP_TODAY;
\echo ---------------TRN_EXAM_MAX_SEQ----------------
truncate TRN_EXAM_MAX_SEQ_GPTMP_TODAY;
\echo ---------------TRN_I_E_PORT----------------
truncate TRN_I_E_PORT_GPTMP_TODAY;
\echo ---------------TRN_PARAMETER----------------
truncate TRN_PARAMETER_GPTMP_TODAY;
\echo ---------------TRN_POP_COP_REL----------------
truncate TRN_POP_COP_REL_GPTMP_TODAY;
\echo ---------------TRN_POP_HEAD----------------
truncate TRN_POP_HEAD_GPTMP_TODAY;
\echo ---------------TRN_POP_LIST----------------
truncate TRN_POP_LIST_GPTMP_TODAY;
\echo ---------------TRN_PRE_MAX_SEQ----------------
truncate TRN_PRE_MAX_SEQ_GPTMP_TODAY;
\echo ---------------TRN_SHIP----------------
truncate TRN_SHIP_GPTMP_TODAY;
\echo ---------------TRN_VE_REL----------------
truncate TRN_VE_REL_GPTMP_TODAY;
\echo ---------------TRN_VEHICLE----------------
truncate TRN_VEHICLE_GPTMP_TODAY;
\echo ---------------YD_DECLARE_REL----------------
truncate YD_DECLARE_REL_GPTMP_TODAY;
select now();
