
\echo --------------MANIFEST_CHK_LOG------------

create table MANIFEST_CHK_LOG_GPTMP_TODAY
(
  CMD_TYPE  VARCHAR(1),
  FORM_ID      VARCHAR(18)  ,
  CREATE_DATE  TIMESTAMP ,
  OPER_FLAG    VARCHAR(1),
  OPER_ER      VARCHAR(8),
  FORM_FLAG    VARCHAR(1),
  SHIP_ID      VARCHAR(32),
  VOYAGE_NO    VARCHAR(32),
  SHIP_NAME_EN VARCHAR(255),
  BILL_NO      VARCHAR(32)  ,
  TRAF_MODE    VARCHAR(1),
  CUSTOMS_CODE VARCHAR(4),
  I_E_FLAG     VARCHAR(1),
  PACK_NO      NUMERIC(19,5),
  GROSS_WT     NUMERIC(19,5),
  CHK_MARK     VARCHAR(1),
  CHK_ER       VARCHAR(8),
  CHK_DATE     TIMESTAMP,
  REL_ER       VARCHAR(8),
  REL_DATE     TIMESTAMP,
  COUNTRY_CODE VARCHAR(3),
  NOTES        VARCHAR(255)
)
DISTRIBUTED BY (FORM_ID, CREATE_DATE, BILL_NO);

\echo --------------MANIFEST_CHK_LOG------------

create table MANIFEST_CHK_LOG_GPTMP
(
  CMD_TYPE  VARCHAR(1),
  FORM_ID      VARCHAR(18)  ,
  CREATE_DATE  TIMESTAMP ,
  OPER_FLAG    VARCHAR(1),
  OPER_ER      VARCHAR(8),
  FORM_FLAG    VARCHAR(1),
  SHIP_ID      VARCHAR(32),
  VOYAGE_NO    VARCHAR(32),
  SHIP_NAME_EN VARCHAR(255),
  BILL_NO      VARCHAR(32)  ,
  TRAF_MODE    VARCHAR(1),
  CUSTOMS_CODE VARCHAR(4),
  I_E_FLAG     VARCHAR(1),
  PACK_NO      NUMERIC(19,5),
  GROSS_WT     NUMERIC(19,5),
  CHK_MARK     VARCHAR(1),
  CHK_ER       VARCHAR(8),
  CHK_DATE     TIMESTAMP,
  REL_ER       VARCHAR(8),
  REL_DATE     TIMESTAMP,
  COUNTRY_CODE VARCHAR(3),
  NOTES        VARCHAR(255)
)
DISTRIBUTED BY (FORM_ID, CREATE_DATE, BILL_NO);


