\echo ------------------AMS_MODI_LOG----------------
select now();
\timing
delete from AMS_MODI_LOG_GPTMP;
insert into AMS_MODI_LOG_GPTMP (CMD_TYPE,EMS_NO, OP_TIME, MODI_TYPE, ITEM_NAME) select CMD_TYPE,EMS_NO, OP_TIME, MODI_TYPE, ITEM_NAME from AMS_MODI_LOG_INC_EXT;
delete from AMS_MODI_LOG_GPTMP_TODAY using AMS_MODI_LOG_GPTMP where AMS_MODI_LOG_GPTMP.EMS_NO=AMS_MODI_LOG_GPTMP_TODAY.EMS_NO AND AMS_MODI_LOG_GPTMP.OP_TIME=AMS_MODI_LOG_GPTMP_TODAY.OP_TIME AND AMS_MODI_LOG_GPTMP.MODI_TYPE=AMS_MODI_LOG_GPTMP_TODAY.MODI_TYPE AND AMS_MODI_LOG_GPTMP.ITEM_NAME=AMS_MODI_LOG_GPTMP_TODAY.ITEM_NAME ;
insert into AMS_MODI_LOG_GPTMP_TODAY (CMD_TYPE,EMS_NO,OP_TIME,MODI_TYPE,ITEM_NAME,ITEM_SOURCE,ITEM_CURRENT,OP_ER,NOTE) select CMD_TYPE,EMS_NO,OP_TIME,MODI_TYPE,ITEM_NAME,ITEM_SOURCE,ITEM_CURRENT,OP_ER,NOTE from AMS_MODI_LOG_INC_EXT;
delete from AMS_MODI_LOG_GPTMP;
\timing
