\echo ------------------APPL_CLOSE_CONSUME----------------
select now();
\timing
delete from APPL_CLOSE_CONSUME_GPTMP;
insert into APPL_CLOSE_CONSUME_GPTMP (CMD_TYPE,MANUAL_NO, CONTR_ITEM, EX_NO) select CMD_TYPE,MANUAL_NO, CONTR_ITEM, EX_NO from APPL_CLOSE_CONSUME_INC_EXT;
delete from APPL_CLOSE_CONSUME_GPTMP_TODAY using APPL_CLOSE_CONSUME_GPTMP where APPL_CLOSE_CONSUME_GPTMP.MANUAL_NO=APPL_CLOSE_CONSUME_GPTMP_TODAY.MANUAL_NO AND APPL_CLOSE_CONSUME_GPTMP.CONTR_ITEM=APPL_CLOSE_CONSUME_GPTMP_TODAY.CONTR_ITEM AND APPL_CLOSE_CONSUME_GPTMP.EX_NO=APPL_CLOSE_CONSUME_GPTMP_TODAY.EX_NO ;
insert into APPL_CLOSE_CONSUME_GPTMP_TODAY (CMD_TYPE,MANUAL_NO,CONTR_ITEM,CODE_TS,G_NAME,G_MODEL,EX_NO,DECL_CONSUME,DECL_DAMAGE) select CMD_TYPE,MANUAL_NO,CONTR_ITEM,CODE_TS,G_NAME,G_MODEL,EX_NO,DECL_CONSUME,DECL_DAMAGE from APPL_CLOSE_CONSUME_INC_EXT;
delete from APPL_CLOSE_CONSUME_GPTMP;
\timing
