\echo ------------------APPLY_HEAD----------------
select now();
\timing
delete from APPLY_HEAD_GPTMP;
insert into APPLY_HEAD_GPTMP (CMD_TYPE,APPL_NO) select CMD_TYPE,APPL_NO from APPLY_HEAD_INC_EXT;
delete from APPLY_HEAD_GPTMP_TODAY using APPLY_HEAD_GPTMP where APPLY_HEAD_GPTMP.APPL_NO=APPLY_HEAD_GPTMP_TODAY.APPL_NO ;
insert into APPLY_HEAD_GPTMP_TODAY (CMD_TYPE,APPL_NO,CONTACT_NO,INPUT_DATE,CONTR_NO,LICENSE_NO,MANUAL_NO,TRADE_MODE,OWNER_NAME,OWNER_TELE,OWNER_CONT,VALID_TIME,PRE_TIMES,IMPORT_TIMES,REC_MARK,INPUT_OP_ID,EXAM_OP_ID,EXAM_TIME,DEL_OP_ID,DEL_TIME,DEL_REASON,CHECK_OP_ID,CHECK_TIME,CHECK_MARK,GOODS_NOTE,DELI_MARK,DELI_TIME,PRE_FIEL,SEND_PORT,RECV_PORT,TRANS_PRE_NO,CA_KEY,HASH_SIGN) select CMD_TYPE,APPL_NO,CONTACT_NO,INPUT_DATE,CONTR_NO,LICENSE_NO,MANUAL_NO,TRADE_MODE,OWNER_NAME,OWNER_TELE,OWNER_CONT,VALID_TIME,PRE_TIMES,IMPORT_TIMES,REC_MARK,INPUT_OP_ID,EXAM_OP_ID,EXAM_TIME,DEL_OP_ID,DEL_TIME,DEL_REASON,CHECK_OP_ID,CHECK_TIME,CHECK_MARK,GOODS_NOTE,DELI_MARK,DELI_TIME,PRE_FIEL,SEND_PORT,RECV_PORT,TRANS_PRE_NO,CA_KEY,HASH_SIGN from APPLY_HEAD_INC_EXT;
delete from APPLY_HEAD_GPTMP;
\timing
