\echo ------------------ARRIVAL_INFO_HEAD----------------
select now();
\timing
delete from ARRIVAL_INFO_HEAD_GPTMP;
insert into ARRIVAL_INFO_HEAD_GPTMP (CMD_TYPE,VOYAGE_NO, SHIP_ID, I_E_DATE, CUSTOMS_CODE, TRAF_MODE) select CMD_TYPE,VOYAGE_NO, SHIP_ID, I_E_DATE, CUSTOMS_CODE, TRAF_MODE from ARRIVAL_INFO_HEAD_INC_EXT;
delete from ARRIVAL_INFO_HEAD_GPTMP_TODAY using ARRIVAL_INFO_HEAD_GPTMP where ARRIVAL_INFO_HEAD_GPTMP.VOYAGE_NO=ARRIVAL_INFO_HEAD_GPTMP_TODAY.VOYAGE_NO AND ARRIVAL_INFO_HEAD_GPTMP.SHIP_ID=ARRIVAL_INFO_HEAD_GPTMP_TODAY.SHIP_ID AND ARRIVAL_INFO_HEAD_GPTMP.I_E_DATE=ARRIVAL_INFO_HEAD_GPTMP_TODAY.I_E_DATE AND ARRIVAL_INFO_HEAD_GPTMP.CUSTOMS_CODE=ARRIVAL_INFO_HEAD_GPTMP_TODAY.CUSTOMS_CODE AND ARRIVAL_INFO_HEAD_GPTMP.TRAF_MODE=ARRIVAL_INFO_HEAD_GPTMP_TODAY.TRAF_MODE ;
insert into ARRIVAL_INFO_HEAD_GPTMP_TODAY (CMD_TYPE,VOYAGE_NO,SHIP_ID,I_E_DATE,CUSTOMS_CODE,TRAF_MODE,I_E_FLAG,VOYAGE_NO_MOD,ARRIVE_DATE,RECV_DATE,SEQ_NO) select CMD_TYPE,VOYAGE_NO,SHIP_ID,I_E_DATE,CUSTOMS_CODE,TRAF_MODE,I_E_FLAG,VOYAGE_NO_MOD,ARRIVE_DATE,RECV_DATE,SEQ_NO from ARRIVAL_INFO_HEAD_INC_EXT;
delete from ARRIVAL_INFO_HEAD_GPTMP;
\timing
