\echo ------------------BAK_DCG_DEDUCT_LOG----------------
select now();
\timing
delete from BAK_DCG_DEDUCT_LOG_GPTMP;
insert into BAK_DCG_DEDUCT_LOG_GPTMP (CMD_TYPE,ENTRY_ID, DCG_NO, CREATE_DATE, JOU_MARK) select CMD_TYPE,ENTRY_ID, DCG_NO, CREATE_DATE, JOU_MARK from BAK_DCG_DEDUCT_LOG_INC_EXT;
delete from BAK_DCG_DEDUCT_LOG_GPTMP_TODAY using BAK_DCG_DEDUCT_LOG_GPTMP where BAK_DCG_DEDUCT_LOG_GPTMP.ENTRY_ID=BAK_DCG_DEDUCT_LOG_GPTMP_TODAY.ENTRY_ID AND BAK_DCG_DEDUCT_LOG_GPTMP.DCG_NO=BAK_DCG_DEDUCT_LOG_GPTMP_TODAY.DCG_NO AND BAK_DCG_DEDUCT_LOG_GPTMP.CREATE_DATE=BAK_DCG_DEDUCT_LOG_GPTMP_TODAY.CREATE_DATE AND BAK_DCG_DEDUCT_LOG_GPTMP.JOU_MARK=BAK_DCG_DEDUCT_LOG_GPTMP_TODAY.JOU_MARK ;
insert into BAK_DCG_DEDUCT_LOG_GPTMP_TODAY (CMD_TYPE,ENTRY_ID,DCG_NO,CREATE_DATE,JOU_MARK,NOTE,VERIFY_ER) select CMD_TYPE,ENTRY_ID,DCG_NO,CREATE_DATE,JOU_MARK,NOTE,VERIFY_ER from BAK_DCG_DEDUCT_LOG_INC_EXT;
delete from BAK_DCG_DEDUCT_LOG_GPTMP;
\timing
