\echo ------------------BAK_DCG_HEAD----------------
select now();
\timing
delete from BAK_DCG_HEAD_GPTMP;
insert into BAK_DCG_HEAD_GPTMP (CMD_TYPE,DCG_NO) select CMD_TYPE,DCG_NO from BAK_DCG_HEAD_INC_EXT;
delete from BAK_DCG_HEAD_GPTMP_TODAY using BAK_DCG_HEAD_GPTMP where BAK_DCG_HEAD_GPTMP.DCG_NO=BAK_DCG_HEAD_GPTMP_TODAY.DCG_NO ;
insert into BAK_DCG_HEAD_GPTMP_TODAY (CMD_TYPE,DCG_NO,DCG_TYPE,EPORT_NO,EX_EMS_NO,EX_COP_EMS_NO,EX_CUSTOMS_CODE,EX_TRADE_CODE,EX_TRADE_NAME,EX_DECLARE_CODE,EX_DECLARE_NAME,EX_CORP_ER,EX_DECLARE_ER,EX_DISTRICT_CODE,EX_CONTR_NO,EX_APPR_NO,EX_NOTE,EX_DECLARE_DATE,EX_CHK_ER,EX_CHK_DATE,EX_CHK_NOTE,IM_COP_EMS_NO,IM_CUSTOMS_CODE,IM_TRADE_CODE,IM_TRADE_NAME,IM_DECLARE_CODE,IM_DECLARE_NAME,IM_CORP_ER,IM_DECLARE_ER,IM_DISTRICT_CODE,IM_CONTR_NO,IM_APPR_NO,IM_NOTE,IM_DECLARE_DATE,IM_CHK_ER,IM_CHK_DATE,IM_CHK_NOTE,INTEND_COST_TIME,DISTANCE,CHK_MARK,EXE_MARK,PAUSE_MARK,END_DATE,FIRST_DATE,LATE_DATE,NOTE_1,NOTE_2,DECLARE_TYPE,LW_MARK) select CMD_TYPE,DCG_NO,DCG_TYPE,EPORT_NO,EX_EMS_NO,EX_COP_EMS_NO,EX_CUSTOMS_CODE,EX_TRADE_CODE,EX_TRADE_NAME,EX_DECLARE_CODE,EX_DECLARE_NAME,EX_CORP_ER,EX_DECLARE_ER,EX_DISTRICT_CODE,EX_CONTR_NO,EX_APPR_NO,EX_NOTE,EX_DECLARE_DATE,EX_CHK_ER,EX_CHK_DATE,EX_CHK_NOTE,IM_COP_EMS_NO,IM_CUSTOMS_CODE,IM_TRADE_CODE,IM_TRADE_NAME,IM_DECLARE_CODE,IM_DECLARE_NAME,IM_CORP_ER,IM_DECLARE_ER,IM_DISTRICT_CODE,IM_CONTR_NO,IM_APPR_NO,IM_NOTE,IM_DECLARE_DATE,IM_CHK_ER,IM_CHK_DATE,IM_CHK_NOTE,INTEND_COST_TIME,DISTANCE,CHK_MARK,EXE_MARK,PAUSE_MARK,END_DATE,FIRST_DATE,LATE_DATE,NOTE_1,NOTE_2,DECLARE_TYPE,LW_MARK from BAK_DCG_HEAD_INC_EXT;
delete from BAK_DCG_HEAD_GPTMP;
\timing
