\echo ------------------BAK_CONSUME----------------
select now();
\timing
delete from BAK_CONSUME_GPTMP;
insert into BAK_CONSUME_GPTMP (CMD_TYPE,MANUAL_NO, CONTR_ITEM, EX_NO) select CMD_TYPE,MANUAL_NO, CONTR_ITEM, EX_NO from BAK_CONSUME_INC_EXT;
delete from BAK_CONSUME_GPTMP_TODAY using BAK_CONSUME_GPTMP where BAK_CONSUME_GPTMP.MANUAL_NO=BAK_CONSUME_GPTMP_TODAY.MANUAL_NO AND BAK_CONSUME_GPTMP.CONTR_ITEM=BAK_CONSUME_GPTMP_TODAY.CONTR_ITEM AND BAK_CONSUME_GPTMP.EX_NO=BAK_CONSUME_GPTMP_TODAY.EX_NO ;
insert into BAK_CONSUME_GPTMP_TODAY (CMD_TYPE,MANUAL_NO,CONTR_ITEM,EX_NO,APPR_CONSUME,APPR_DAMAGE,DECL_CONSUME,DECL_DAMAGE) select CMD_TYPE,MANUAL_NO,CONTR_ITEM,EX_NO,APPR_CONSUME,APPR_DAMAGE,DECL_CONSUME,DECL_DAMAGE from BAK_CONSUME_INC_EXT;
delete from BAK_CONSUME_GPTMP;
\timing
