\echo ------------------BCK_COP_PARA_HEAD----------------
select now();
\timing
delete from BCK_COP_PARA_HEAD_GPTMP;
insert into BCK_COP_PARA_HEAD_GPTMP (CMD_TYPE,RISK_NO, CUSTOMS_CODE) select CMD_TYPE,RISK_NO, CUSTOMS_CODE from BCK_COP_PARA_HEAD_INC_EXT;
delete from BCK_COP_PARA_HEAD_GPTMP_TODAY using BCK_COP_PARA_HEAD_GPTMP where BCK_COP_PARA_HEAD_GPTMP.RISK_NO=BCK_COP_PARA_HEAD_GPTMP_TODAY.RISK_NO AND BCK_COP_PARA_HEAD_GPTMP.CUSTOMS_CODE=BCK_COP_PARA_HEAD_GPTMP_TODAY.CUSTOMS_CODE ;
insert into BCK_COP_PARA_HEAD_GPTMP_TODAY (CMD_TYPE,RISK_NO,CUSTOMS_CODE,RISK_NAME,RISK_DESC,WEIGHT_VALUE,WEIGHT_TYPE,DEGREE,SOURCE,SWITCH,NOTE) select CMD_TYPE,RISK_NO,CUSTOMS_CODE,RISK_NAME,RISK_DESC,WEIGHT_VALUE,WEIGHT_TYPE,DEGREE,SOURCE,SWITCH,NOTE from BCK_COP_PARA_HEAD_INC_EXT;
delete from BCK_COP_PARA_HEAD_GPTMP;
\timing
