\echo ------------------BCK_WORKFLOW----------------
select now();
\timing
delete from BCK_WORKFLOW_GPTMP;
insert into BCK_WORKFLOW_GPTMP (CMD_TYPE,BCK_NO, STEP_ID, OPER_ID, CREATE_DATE) select CMD_TYPE,BCK_NO, STEP_ID, OPER_ID, CREATE_DATE from BCK_WORKFLOW_INC_EXT;
delete from BCK_WORKFLOW_GPTMP_TODAY using BCK_WORKFLOW_GPTMP where BCK_WORKFLOW_GPTMP.BCK_NO=BCK_WORKFLOW_GPTMP_TODAY.BCK_NO AND BCK_WORKFLOW_GPTMP.STEP_ID=BCK_WORKFLOW_GPTMP_TODAY.STEP_ID AND BCK_WORKFLOW_GPTMP.OPER_ID=BCK_WORKFLOW_GPTMP_TODAY.OPER_ID AND BCK_WORKFLOW_GPTMP.CREATE_DATE=BCK_WORKFLOW_GPTMP_TODAY.CREATE_DATE ;
insert into BCK_WORKFLOW_GPTMP_TODAY (CMD_TYPE,BCK_NO,CREATE_DATE,STEP_ID,OPER_ID,NOTE,OPER_ER,REALTIVE_NO) select CMD_TYPE,BCK_NO,CREATE_DATE,STEP_ID,OPER_ID,NOTE,OPER_ER,REALTIVE_NO from BCK_WORKFLOW_INC_EXT;
delete from BCK_WORKFLOW_GPTMP;
\timing
