\echo ------------------BCK_COP_LIST----------------
select now();
\timing
delete from BCK_COP_LIST_GPTMP;
insert into BCK_COP_LIST_GPTMP (CMD_TYPE,TRADE_CODE, RISK_NO, CUSTOMS_CODE) select CMD_TYPE,TRADE_CODE, RISK_NO, CUSTOMS_CODE from BCK_COP_LIST_INC_EXT;
delete from BCK_COP_LIST_GPTMP_TODAY using BCK_COP_LIST_GPTMP where BCK_COP_LIST_GPTMP.TRADE_CODE=BCK_COP_LIST_GPTMP_TODAY.TRADE_CODE AND BCK_COP_LIST_GPTMP.RISK_NO=BCK_COP_LIST_GPTMP_TODAY.RISK_NO AND BCK_COP_LIST_GPTMP.CUSTOMS_CODE=BCK_COP_LIST_GPTMP_TODAY.CUSTOMS_CODE ;
insert into BCK_COP_LIST_GPTMP_TODAY (CMD_TYPE,TRADE_CODE,RISK_NO,CUSTOMS_CODE,RISK_VALUE) select CMD_TYPE,TRADE_CODE,RISK_NO,CUSTOMS_CODE,RISK_VALUE from BCK_COP_LIST_INC_EXT;
delete from BCK_COP_LIST_GPTMP;
\timing
