\echo ------------------BCK_COP_LIST_TEMP----------------
select now();
\timing
delete from BCK_COP_LIST_TEMP_GPTMP;
insert into BCK_COP_LIST_TEMP_GPTMP (CMD_TYPE,TRADE_CO, RISK_NO, CUSTOMS_CODE) select CMD_TYPE,TRADE_CO, RISK_NO, CUSTOMS_CODE from BCK_COP_LIST_TEMP_INC_EXT;
delete from BCK_COP_LIST_TEMP_GPTMP_TODAY using BCK_COP_LIST_TEMP_GPTMP where BCK_COP_LIST_TEMP_GPTMP.TRADE_CO=BCK_COP_LIST_TEMP_GPTMP_TODAY.TRADE_CO AND BCK_COP_LIST_TEMP_GPTMP.RISK_NO=BCK_COP_LIST_TEMP_GPTMP_TODAY.RISK_NO AND BCK_COP_LIST_TEMP_GPTMP.CUSTOMS_CODE=BCK_COP_LIST_TEMP_GPTMP_TODAY.CUSTOMS_CODE ;
insert into BCK_COP_LIST_TEMP_GPTMP_TODAY (CMD_TYPE,TRADE_CO,RISK_NO,CUSTOMS_CODE,RISK_VALUE,VALUE) select CMD_TYPE,TRADE_CO,RISK_NO,CUSTOMS_CODE,RISK_VALUE,VALUE from BCK_COP_LIST_TEMP_INC_EXT;
delete from BCK_COP_LIST_TEMP_GPTMP;
\timing
