\echo ------------------BCK_EXECUTOR----------------
select now();
\timing
delete from BCK_EXECUTOR_GPTMP;
insert into BCK_EXECUTOR_GPTMP (CMD_TYPE,BCK_NO, EXECUTOR) select CMD_TYPE,BCK_NO, EXECUTOR from BCK_EXECUTOR_INC_EXT;
delete from BCK_EXECUTOR_GPTMP_TODAY using BCK_EXECUTOR_GPTMP where BCK_EXECUTOR_GPTMP.BCK_NO=BCK_EXECUTOR_GPTMP_TODAY.BCK_NO AND BCK_EXECUTOR_GPTMP.EXECUTOR=BCK_EXECUTOR_GPTMP_TODAY.EXECUTOR ;
insert into BCK_EXECUTOR_GPTMP_TODAY (CMD_TYPE,BCK_NO,EXECUTOR) select CMD_TYPE,BCK_NO,EXECUTOR from BCK_EXECUTOR_INC_EXT;
delete from BCK_EXECUTOR_GPTMP;
\timing
