\echo ------------------BCK_COP_PARA_LIST----------------
select now();
\timing
delete from BCK_COP_PARA_LIST_GPTMP;
insert into BCK_COP_PARA_LIST_GPTMP (CMD_TYPE,RISK_NO, RISK_VALUE, CUSTOMS_CODE) select CMD_TYPE,RISK_NO, RISK_VALUE, CUSTOMS_CODE from BCK_COP_PARA_LIST_INC_EXT;
delete from BCK_COP_PARA_LIST_GPTMP_TODAY using BCK_COP_PARA_LIST_GPTMP where BCK_COP_PARA_LIST_GPTMP.RISK_NO=BCK_COP_PARA_LIST_GPTMP_TODAY.RISK_NO AND BCK_COP_PARA_LIST_GPTMP.RISK_VALUE=BCK_COP_PARA_LIST_GPTMP_TODAY.RISK_VALUE AND BCK_COP_PARA_LIST_GPTMP.CUSTOMS_CODE=BCK_COP_PARA_LIST_GPTMP_TODAY.CUSTOMS_CODE ;
insert into BCK_COP_PARA_LIST_GPTMP_TODAY (CMD_TYPE,RISK_NO,RISK_VALUE,CUSTOMS_CODE,RISK_LIST_DESC) select CMD_TYPE,RISK_NO,RISK_VALUE,CUSTOMS_CODE,RISK_LIST_DESC from BCK_COP_PARA_LIST_INC_EXT;
delete from BCK_COP_PARA_LIST_GPTMP;
\timing
