\echo ------------------BCK_COP_HEAD----------------
select now();
\timing
delete from BCK_COP_HEAD_GPTMP;
insert into BCK_COP_HEAD_GPTMP (CMD_TYPE,TRADE_CODE) select CMD_TYPE,TRADE_CODE from BCK_COP_HEAD_INC_EXT;
delete from BCK_COP_HEAD_GPTMP_TODAY using BCK_COP_HEAD_GPTMP where BCK_COP_HEAD_GPTMP.TRADE_CODE=BCK_COP_HEAD_GPTMP_TODAY.TRADE_CODE ;
insert into BCK_COP_HEAD_GPTMP_TODAY (CMD_TYPE,TRADE_CODE,CUSTOMS_CODE,REG_CO,ADDR_CO,RISK_VALUE,RISK_TYPE,LAW_MAN,TEL_CO,CONTAC_CO,TEL_CONTAC,INV_CO,INV_COUNTRY,RG_FUND,TRADE_AREA,STAFF_NUM,EMS_TYPE,EMS_NO,LAST_CHECK_DATE,PRODUCE_TYPE,NOTE,RISK_VALUE_MARK,RISK_TYPE_MARK,RISK_CALC_DATE,RISK_AUTO_DATE,MARK_1) select CMD_TYPE,TRADE_CODE,CUSTOMS_CODE,REG_CO,ADDR_CO,RISK_VALUE,RISK_TYPE,LAW_MAN,TEL_CO,CONTAC_CO,TEL_CONTAC,INV_CO,INV_COUNTRY,RG_FUND,TRADE_AREA,STAFF_NUM,EMS_TYPE,EMS_NO,LAST_CHECK_DATE,PRODUCE_TYPE,NOTE,RISK_VALUE_MARK,RISK_TYPE_MARK,RISK_CALC_DATE,RISK_AUTO_DATE,MARK_1 from BCK_COP_HEAD_INC_EXT;
delete from BCK_COP_HEAD_GPTMP;
\timing
