\echo ------------------BTI_DATA_CONTA_LIST----------------
select now();
\timing
delete from BTI_DATA_CONTA_LIST_GPTMP;
insert into BTI_DATA_CONTA_LIST_GPTMP (CMD_TYPE,UCR_CODE, CONTAINER_ID) select CMD_TYPE,UCR_CODE, CONTAINER_ID from BTI_DATA_CONTA_LIST_INC_EXT;
delete from BTI_DATA_CONTA_LIST_GPTMP_TODAY using BTI_DATA_CONTA_LIST_GPTMP where BTI_DATA_CONTA_LIST_GPTMP.UCR_CODE=BTI_DATA_CONTA_LIST_GPTMP_TODAY.UCR_CODE AND BTI_DATA_CONTA_LIST_GPTMP.CONTAINER_ID=BTI_DATA_CONTA_LIST_GPTMP_TODAY.CONTAINER_ID ;
insert into BTI_DATA_CONTA_LIST_GPTMP_TODAY (CMD_TYPE,UCR_CODE,CONTAINER_ID,SEAL_NO) select CMD_TYPE,UCR_CODE,CONTAINER_ID,SEAL_NO from BTI_DATA_CONTA_LIST_INC_EXT;
delete from BTI_DATA_CONTA_LIST_GPTMP;
\timing
