\echo ------------------BWS_DCR_HEAD----------------
select now();
\timing
delete from BWS_DCR_HEAD_GPTMP;
insert into BWS_DCR_HEAD_GPTMP (CMD_TYPE,BWS_NO, DCR_TIMES, DCR_TYPE) select CMD_TYPE,BWS_NO, DCR_TIMES, DCR_TYPE from BWS_DCR_HEAD_INC_EXT;
delete from BWS_DCR_HEAD_GPTMP_TODAY using BWS_DCR_HEAD_GPTMP where BWS_DCR_HEAD_GPTMP.BWS_NO=BWS_DCR_HEAD_GPTMP_TODAY.BWS_NO AND BWS_DCR_HEAD_GPTMP.DCR_TIMES=BWS_DCR_HEAD_GPTMP_TODAY.DCR_TIMES AND BWS_DCR_HEAD_GPTMP.DCR_TYPE=BWS_DCR_HEAD_GPTMP_TODAY.DCR_TYPE ;
insert into BWS_DCR_HEAD_GPTMP_TODAY (CMD_TYPE,BWS_NO,DCR_TIMES,DCR_TYPE,BWS_TYPE,EPORT_NO,TRADE_CODE,TRADE_NAME,BEGIN_DATE,END_DATE,IM_NUM,EX_NUM,CUSTOMS_CODE,INPUT_DATE,INPUT_ER,DCR_DATE,NOTE,CHK_MARK,CHK_DATE,MESSAGE_TYPE) select CMD_TYPE,BWS_NO,DCR_TIMES,DCR_TYPE,BWS_TYPE,EPORT_NO,TRADE_CODE,TRADE_NAME,BEGIN_DATE,END_DATE,IM_NUM,EX_NUM,CUSTOMS_CODE,INPUT_DATE,INPUT_ER,DCR_DATE,NOTE,CHK_MARK,CHK_DATE,MESSAGE_TYPE from BWS_DCR_HEAD_INC_EXT;
delete from BWS_DCR_HEAD_GPTMP;
\timing
