\echo ------------------BWS_DEDUCT----------------
select now();
\timing
delete from BWS_DEDUCT_GPTMP;
insert into BWS_DEDUCT_GPTMP (CMD_TYPE,BWS_ID, ENTRY_G_NO) select CMD_TYPE,BWS_ID, ENTRY_G_NO from BWS_DEDUCT_INC_EXT;
delete from BWS_DEDUCT_GPTMP_TODAY using BWS_DEDUCT_GPTMP where BWS_DEDUCT_GPTMP.BWS_ID=BWS_DEDUCT_GPTMP_TODAY.BWS_ID AND BWS_DEDUCT_GPTMP.ENTRY_G_NO=BWS_DEDUCT_GPTMP_TODAY.ENTRY_G_NO ;
insert into BWS_DEDUCT_GPTMP_TODAY (CMD_TYPE,BWS_ID,ENTRY_G_NO,BWS_NO,BWS_G_NO,BWS_G_TYPE,DU_CODE,IN_QTY,I_ACCOUNT,I_E_FLAG,I_CURR,I_E_PORT,TRADE_MODE,TRAF_MODE,VERIFY_MODE,VERIFY_DATE,VERIFY_ER,I_E_DATE,USD_ACCOUNT,JOU_MARK,DECLARE_DATE,TRANS_MODE,CUSTOMS_CODE,DCR_TIMES) select CMD_TYPE,BWS_ID,ENTRY_G_NO,BWS_NO,BWS_G_NO,BWS_G_TYPE,DU_CODE,IN_QTY,I_ACCOUNT,I_E_FLAG,I_CURR,I_E_PORT,TRADE_MODE,TRAF_MODE,VERIFY_MODE,VERIFY_DATE,VERIFY_ER,I_E_DATE,USD_ACCOUNT,JOU_MARK,DECLARE_DATE,TRANS_MODE,CUSTOMS_CODE,DCR_TIMES from BWS_DEDUCT_INC_EXT;
delete from BWS_DEDUCT_GPTMP;
\timing
