\echo ------------------BWS_HEAD----------------
select now();
\timing
delete from BWS_HEAD_GPTMP;
insert into BWS_HEAD_GPTMP (CMD_TYPE,BWS_NO) select CMD_TYPE,BWS_NO from BWS_HEAD_INC_EXT;
delete from BWS_HEAD_GPTMP_TODAY using BWS_HEAD_GPTMP where BWS_HEAD_GPTMP.BWS_NO=BWS_HEAD_GPTMP_TODAY.BWS_NO ;
insert into BWS_HEAD_GPTMP_TODAY (CMD_TYPE,BWS_NO,BWS_TYPE,EPORT_NO,MASTER_CUSTOMS,REGION_NO,DECLARE_TYPE,TRADE_CODE,TRADE_NAME,OWNER_CODE,OWNER_NAME,DECLARE_CODE,DECLARE_NAME,ADDRESS,PHONE,STORE_TYPE,STORE_VOL,STORE_AREA,STORE_ADDRESS,INPUT_DATE,DECLARE_DATE,CHK_MARK,EXE_MARK,NEW_APPR_DATE,CNG_APPR_DATE,CLEAR_DATE,NEXT_CLEAR_DATE,NOTE,FIRST_QTY,FIRST_AMOUNT) select CMD_TYPE,BWS_NO,BWS_TYPE,EPORT_NO,MASTER_CUSTOMS,REGION_NO,DECLARE_TYPE,TRADE_CODE,TRADE_NAME,OWNER_CODE,OWNER_NAME,DECLARE_CODE,DECLARE_NAME,ADDRESS,PHONE,STORE_TYPE,STORE_VOL,STORE_AREA,STORE_ADDRESS,INPUT_DATE,DECLARE_DATE,CHK_MARK,EXE_MARK,NEW_APPR_DATE,CNG_APPR_DATE,CLEAR_DATE,NEXT_CLEAR_DATE,NOTE,FIRST_QTY,FIRST_AMOUNT from BWS_HEAD_INC_EXT;
delete from BWS_HEAD_GPTMP;
\timing
