\echo ------------------BWS_AUDIT_LIST----------------
select now();
\timing
delete from BWS_AUDIT_LIST_GPTMP;
insert into BWS_AUDIT_LIST_GPTMP (CMD_TYPE,AUDIT_NO, G_NO) select CMD_TYPE,AUDIT_NO, G_NO from BWS_AUDIT_LIST_INC_EXT;
delete from BWS_AUDIT_LIST_GPTMP_TODAY using BWS_AUDIT_LIST_GPTMP where BWS_AUDIT_LIST_GPTMP.AUDIT_NO=BWS_AUDIT_LIST_GPTMP_TODAY.AUDIT_NO AND BWS_AUDIT_LIST_GPTMP.G_NO=BWS_AUDIT_LIST_GPTMP_TODAY.G_NO ;
insert into BWS_AUDIT_LIST_GPTMP_TODAY (CMD_TYPE,AUDIT_NO,G_NO,G_TYPE,CODE_TS,G_NAME,G_MODEL,BWS_G_NO,QTY,UNIT,AMOUNT,CURR) select CMD_TYPE,AUDIT_NO,G_NO,G_TYPE,CODE_TS,G_NAME,G_MODEL,BWS_G_NO,QTY,UNIT,AMOUNT,CURR from BWS_AUDIT_LIST_INC_EXT;
delete from BWS_AUDIT_LIST_GPTMP;
\timing
