\echo ------------------BWS_MANIFEST_HEAD----------------
select now();
\timing
delete from BWS_MANIFEST_HEAD_GPTMP;
insert into BWS_MANIFEST_HEAD_GPTMP (CMD_TYPE,BWS_MANIFEST_NO) select CMD_TYPE,BWS_MANIFEST_NO from BWS_MANIFEST_HEAD_INC_EXT;
delete from BWS_MANIFEST_HEAD_GPTMP_TODAY using BWS_MANIFEST_HEAD_GPTMP where BWS_MANIFEST_HEAD_GPTMP.BWS_MANIFEST_NO=BWS_MANIFEST_HEAD_GPTMP_TODAY.BWS_MANIFEST_NO ;
insert into BWS_MANIFEST_HEAD_GPTMP_TODAY (CMD_TYPE,BWS_MANIFEST_NO,EPORT_NO,BWS_NO,MASTER_CUSTOMS,DECLARE_CODE,DECLARE_NAME,DECLARE_DATE,I_E_DATE,I_E_PORT,TRAF_MODE,MANIFEST_NO,SHIP_ID,VOYAGE_NO,SHIP_NAME_CN,SHIP_NAME_EN,BILL_NUM,PACK_NO,GROSS_WT,CONTA_NUM,CHK_MARK,DESTINATION_PLACE) select CMD_TYPE,BWS_MANIFEST_NO,EPORT_NO,BWS_NO,MASTER_CUSTOMS,DECLARE_CODE,DECLARE_NAME,DECLARE_DATE,I_E_DATE,I_E_PORT,TRAF_MODE,MANIFEST_NO,SHIP_ID,VOYAGE_NO,SHIP_NAME_CN,SHIP_NAME_EN,BILL_NUM,PACK_NO,GROSS_WT,CONTA_NUM,CHK_MARK,DESTINATION_PLACE from BWS_MANIFEST_HEAD_INC_EXT;
delete from BWS_MANIFEST_HEAD_GPTMP;
\timing
