\echo ------------------BWS_EXAM_PASSCERT----------------
select now();
\timing
delete from BWS_EXAM_PASSCERT_GPTMP;
insert into BWS_EXAM_PASSCERT_GPTMP (CMD_TYPE,CERT_NO) select CMD_TYPE,CERT_NO from BWS_EXAM_PASSCERT_INC_EXT;
delete from BWS_EXAM_PASSCERT_GPTMP_TODAY using BWS_EXAM_PASSCERT_GPTMP where BWS_EXAM_PASSCERT_GPTMP.CERT_NO=BWS_EXAM_PASSCERT_GPTMP_TODAY.CERT_NO ;
insert into BWS_EXAM_PASSCERT_GPTMP_TODAY (CMD_TYPE,CERT_NO,CERT_TYPE,FLAG,FLAG1,CREATE_DATE,NOTE) select CMD_TYPE,CERT_NO,CERT_TYPE,FLAG,FLAG1,CREATE_DATE,NOTE from BWS_EXAM_PASSCERT_INC_EXT;
delete from BWS_EXAM_PASSCERT_GPTMP;
\timing
