\echo ------------------BWS_DEDUCT_LOG----------------
select now();
\timing
delete from BWS_DEDUCT_LOG_GPTMP;
insert into BWS_DEDUCT_LOG_GPTMP (CMD_TYPE,BWS_ID, BWS_NO, CREATE_DATE, JOU_MARK) select CMD_TYPE,BWS_ID, BWS_NO, CREATE_DATE, JOU_MARK from BWS_DEDUCT_LOG_INC_EXT;
delete from BWS_DEDUCT_LOG_GPTMP_TODAY using BWS_DEDUCT_LOG_GPTMP where BWS_DEDUCT_LOG_GPTMP.BWS_ID=BWS_DEDUCT_LOG_GPTMP_TODAY.BWS_ID AND BWS_DEDUCT_LOG_GPTMP.BWS_NO=BWS_DEDUCT_LOG_GPTMP_TODAY.BWS_NO AND BWS_DEDUCT_LOG_GPTMP.CREATE_DATE=BWS_DEDUCT_LOG_GPTMP_TODAY.CREATE_DATE AND BWS_DEDUCT_LOG_GPTMP.JOU_MARK=BWS_DEDUCT_LOG_GPTMP_TODAY.JOU_MARK ;
insert into BWS_DEDUCT_LOG_GPTMP_TODAY (CMD_TYPE,BWS_ID,BWS_NO,CREATE_DATE,JOU_MARK,NOTE,VERIFY_ER) select CMD_TYPE,BWS_ID,BWS_NO,CREATE_DATE,JOU_MARK,NOTE,VERIFY_ER from BWS_DEDUCT_LOG_INC_EXT;
delete from BWS_DEDUCT_LOG_GPTMP;
\timing
