\echo ------------------CCTS_ERROR_LOG----------------
select now();
\timing
delete from CCTS_ERROR_LOG_GPTMP;
insert into CCTS_ERROR_LOG_GPTMP (CMD_TYPE,SEQUENCE_NO) select CMD_TYPE,SEQUENCE_NO from CCTS_ERROR_LOG_INC_EXT;
delete from CCTS_ERROR_LOG_GPTMP_TODAY using CCTS_ERROR_LOG_GPTMP where CCTS_ERROR_LOG_GPTMP.SEQUENCE_NO=CCTS_ERROR_LOG_GPTMP_TODAY.SEQUENCE_NO ;
insert into CCTS_ERROR_LOG_GPTMP_TODAY (CMD_TYPE,SEQUENCE_NO,FORM_TYPE,ENTRY_ID,G_NO,POSITION_ID,SUB_POSITION_ID,COMMENTS,CREATE_DATE) select CMD_TYPE,SEQUENCE_NO,FORM_TYPE,ENTRY_ID,G_NO,POSITION_ID,SUB_POSITION_ID,COMMENTS,CREATE_DATE from CCTS_ERROR_LOG_INC_EXT;
delete from CCTS_ERROR_LOG_GPTMP;
\timing
