\echo ------------------CDL_DEL_CONTAINER_LOG----------------
select now();
\timing
delete from CDL_DEL_CONTAINER_LOG_GPTMP;
insert into CDL_DEL_CONTAINER_LOG_GPTMP (CMD_TYPE,LIST_NO, CONTAINER_ID, CONTAINER_WT) select CMD_TYPE,LIST_NO, CONTAINER_ID, CONTAINER_WT from CDL_DEL_CONTAINER_LOG_INC_EXT;
delete from CDL_DEL_CONTAINER_LOG_GPTMP_TODAY using CDL_DEL_CONTAINER_LOG_GPTMP where CDL_DEL_CONTAINER_LOG_GPTMP.LIST_NO=CDL_DEL_CONTAINER_LOG_GPTMP_TODAY.LIST_NO AND CDL_DEL_CONTAINER_LOG_GPTMP.CONTAINER_ID=CDL_DEL_CONTAINER_LOG_GPTMP_TODAY.CONTAINER_ID AND CDL_DEL_CONTAINER_LOG_GPTMP.CONTAINER_WT=CDL_DEL_CONTAINER_LOG_GPTMP_TODAY.CONTAINER_WT ;
insert into CDL_DEL_CONTAINER_LOG_GPTMP_TODAY (CMD_TYPE,LIST_NO,CONTAINER_ID,CONTAINER_WT) select CMD_TYPE,LIST_NO,CONTAINER_ID,CONTAINER_WT from CDL_DEL_CONTAINER_LOG_INC_EXT;
delete from CDL_DEL_CONTAINER_LOG_GPTMP;
\timing
