\echo ------------------CDL_CERTIFICATE----------------
select now();
\timing
delete from CDL_CERTIFICATE_GPTMP;
insert into CDL_CERTIFICATE_GPTMP (CMD_TYPE,LIST_NO, DOCU_CODE, CERT_CODE) select CMD_TYPE,LIST_NO, DOCU_CODE, CERT_CODE from CDL_CERTIFICATE_INC_EXT;
delete from CDL_CERTIFICATE_GPTMP_TODAY using CDL_CERTIFICATE_GPTMP where CDL_CERTIFICATE_GPTMP.LIST_NO=CDL_CERTIFICATE_GPTMP_TODAY.LIST_NO AND CDL_CERTIFICATE_GPTMP.DOCU_CODE=CDL_CERTIFICATE_GPTMP_TODAY.DOCU_CODE AND CDL_CERTIFICATE_GPTMP.CERT_CODE=CDL_CERTIFICATE_GPTMP_TODAY.CERT_CODE ;
insert into CDL_CERTIFICATE_GPTMP_TODAY (CMD_TYPE,LIST_NO,DOCU_CODE,CERT_CODE) select CMD_TYPE,LIST_NO,DOCU_CODE,CERT_CODE from CDL_CERTIFICATE_INC_EXT;
delete from CDL_CERTIFICATE_GPTMP;
\timing
