\echo ------------------CDL_MODI_LOG----------------
select now();
\timing
delete from CDL_MODI_LOG_GPTMP;
insert into CDL_MODI_LOG_GPTMP (CMD_TYPE,LIST_NO, OP_TIME, MODI_TYPE, ITEM_NAME) select CMD_TYPE,LIST_NO, OP_TIME, MODI_TYPE, ITEM_NAME from CDL_MODI_LOG_INC_EXT;
delete from CDL_MODI_LOG_GPTMP_TODAY using CDL_MODI_LOG_GPTMP where CDL_MODI_LOG_GPTMP.LIST_NO=CDL_MODI_LOG_GPTMP_TODAY.LIST_NO AND CDL_MODI_LOG_GPTMP.OP_TIME=CDL_MODI_LOG_GPTMP_TODAY.OP_TIME AND CDL_MODI_LOG_GPTMP.MODI_TYPE=CDL_MODI_LOG_GPTMP_TODAY.MODI_TYPE AND CDL_MODI_LOG_GPTMP.ITEM_NAME=CDL_MODI_LOG_GPTMP_TODAY.ITEM_NAME ;
insert into CDL_MODI_LOG_GPTMP_TODAY (CMD_TYPE,LIST_NO,OP_TIME,MODI_TYPE,ITEM_NAME,ITEM_SOURCE,ITEM_CURRENT,NOTES) select CMD_TYPE,LIST_NO,OP_TIME,MODI_TYPE,ITEM_NAME,ITEM_SOURCE,ITEM_CURRENT,NOTES from CDL_MODI_LOG_INC_EXT;
delete from CDL_MODI_LOG_GPTMP;
\timing
