\echo ------------------CDL_COMMODITY----------------
select now();
\timing
delete from CDL_COMMODITY_GPTMP;
insert into CDL_COMMODITY_GPTMP (CMD_TYPE,RECORDS_NO, G_NO) select CMD_TYPE,RECORDS_NO, G_NO from CDL_COMMODITY_INC_EXT;
delete from CDL_COMMODITY_GPTMP_TODAY using CDL_COMMODITY_GPTMP where CDL_COMMODITY_GPTMP.RECORDS_NO=CDL_COMMODITY_GPTMP_TODAY.RECORDS_NO AND CDL_COMMODITY_GPTMP.G_NO=CDL_COMMODITY_GPTMP_TODAY.G_NO ;
insert into CDL_COMMODITY_GPTMP_TODAY (CMD_TYPE,RECORDS_NO,PRE_RECORDS_NO,TRADE_CO,G_NO,FIT_FLAG,CODE_TS,G_NAME,G_MODEL,G_UNIT,DECL_PRICE,TRADE_CURR,I_E_FLAG,ORIGIN_COUNTRY,DISTRICT_CODE,LICENSE_NO,LICENSE_COUNT,LICENSE_DATE,MOD_TYPE,CUSTOMS_CODE) select CMD_TYPE,RECORDS_NO,PRE_RECORDS_NO,TRADE_CO,G_NO,FIT_FLAG,CODE_TS,G_NAME,G_MODEL,G_UNIT,DECL_PRICE,TRADE_CURR,I_E_FLAG,ORIGIN_COUNTRY,DISTRICT_CODE,LICENSE_NO,LICENSE_COUNT,LICENSE_DATE,MOD_TYPE,CUSTOMS_CODE from CDL_COMMODITY_INC_EXT;
delete from CDL_COMMODITY_GPTMP;
\timing
