\echo ------------------CDL_LIST----------------
select now();
\timing
delete from CDL_LIST_GPTMP;
insert into CDL_LIST_GPTMP (CMD_TYPE,LIST_NO, G_NO) select CMD_TYPE,LIST_NO, G_NO from CDL_LIST_INC_EXT;
delete from CDL_LIST_GPTMP_TODAY using CDL_LIST_GPTMP where CDL_LIST_GPTMP.LIST_NO=CDL_LIST_GPTMP_TODAY.LIST_NO AND CDL_LIST_GPTMP.G_NO=CDL_LIST_GPTMP_TODAY.G_NO ;
insert into CDL_LIST_GPTMP_TODAY (CMD_TYPE,LIST_NO,G_NO,RECORDS_NO,D_DATE,CODE_TS,G_NAME,G_MODEL,G_QTY,G_UNIT,ORIGIN_COUNTRY,DECL_PRICE,DECL_TOTAL,TRADE_CURR,DUTY_MODE,D_RATE,DUTY_RATE,T_RATE,TAX_RATE,R_RATE,REG_RATE,TARIFF_MARK,EXCH_RATE,RMB_RATE,USD_RATE,G_CERT_FLAG,LIST_CONDITION) select CMD_TYPE,LIST_NO,G_NO,RECORDS_NO,D_DATE,CODE_TS,G_NAME,G_MODEL,G_QTY,G_UNIT,ORIGIN_COUNTRY,DECL_PRICE,DECL_TOTAL,TRADE_CURR,DUTY_MODE,D_RATE,DUTY_RATE,T_RATE,TAX_RATE,R_RATE,REG_RATE,TARIFF_MARK,EXCH_RATE,RMB_RATE,USD_RATE,G_CERT_FLAG,LIST_CONDITION from CDL_LIST_INC_EXT;
delete from CDL_LIST_GPTMP;
\timing
