\echo ------------------CDL_ENTRY_LIST----------------
select now();
\timing
delete from CDL_ENTRY_LIST_GPTMP;
insert into CDL_ENTRY_LIST_GPTMP (CMD_TYPE,PRE_ENTRY_ID, ENTRY_G_NO, LIST_NO, LIST_G_NO) select CMD_TYPE,PRE_ENTRY_ID, ENTRY_G_NO, LIST_NO, LIST_G_NO from CDL_ENTRY_LIST_INC_EXT;
delete from CDL_ENTRY_LIST_GPTMP_TODAY using CDL_ENTRY_LIST_GPTMP where CDL_ENTRY_LIST_GPTMP.PRE_ENTRY_ID=CDL_ENTRY_LIST_GPTMP_TODAY.PRE_ENTRY_ID AND CDL_ENTRY_LIST_GPTMP.ENTRY_G_NO=CDL_ENTRY_LIST_GPTMP_TODAY.ENTRY_G_NO AND CDL_ENTRY_LIST_GPTMP.LIST_NO=CDL_ENTRY_LIST_GPTMP_TODAY.LIST_NO AND CDL_ENTRY_LIST_GPTMP.LIST_G_NO=CDL_ENTRY_LIST_GPTMP_TODAY.LIST_G_NO ;
insert into CDL_ENTRY_LIST_GPTMP_TODAY (CMD_TYPE,PRE_ENTRY_ID,ENTRY_ID,ENTRY_G_NO,LIST_NO,LIST_G_NO,CODE_TS,G_NAME,G_MODEL,G_UNIT,ORIGIN_COUNTRY,DECL_PRICE,TRADE_CURR,LIST_CONDITION) select CMD_TYPE,PRE_ENTRY_ID,ENTRY_ID,ENTRY_G_NO,LIST_NO,LIST_G_NO,CODE_TS,G_NAME,G_MODEL,G_UNIT,ORIGIN_COUNTRY,DECL_PRICE,TRADE_CURR,LIST_CONDITION from CDL_ENTRY_LIST_INC_EXT;
delete from CDL_ENTRY_LIST_GPTMP;
\timing
