\echo ------------------CDL_CHK----------------
select now();
\timing
delete from CDL_CHK_GPTMP;
insert into CDL_CHK_GPTMP (CMD_TYPE,LIST_NO) select CMD_TYPE,LIST_NO from CDL_CHK_INC_EXT;
delete from CDL_CHK_GPTMP_TODAY using CDL_CHK_GPTMP where CDL_CHK_GPTMP.LIST_NO=CDL_CHK_GPTMP_TODAY.LIST_NO ;
insert into CDL_CHK_GPTMP_TODAY (CMD_TYPE,LIST_NO,PRE_LIST_NO,SHIP_ID,VOYAGE_NO,BILL_NO,TRAF_MODE,I_E_FLAG,DECL_PORT,I_E_PORT,I_E_DATE,TRADE_NAME,AGENT_NAME,OWNER_NAME,TRADE_MODE,MANUAL_NO,PACK_NO,GROSS_WT,GEN_DATE,GEN_ER,CHK_MARK,CHK_DATE,CHK_ER) select CMD_TYPE,LIST_NO,PRE_LIST_NO,SHIP_ID,VOYAGE_NO,BILL_NO,TRAF_MODE,I_E_FLAG,DECL_PORT,I_E_PORT,I_E_DATE,TRADE_NAME,AGENT_NAME,OWNER_NAME,TRADE_MODE,MANUAL_NO,PACK_NO,GROSS_WT,GEN_DATE,GEN_ER,CHK_MARK,CHK_DATE,CHK_ER from CDL_CHK_INC_EXT;
delete from CDL_CHK_GPTMP;
\timing
