\echo ------------------CDL_ENTRY_HEAD----------------
select now();
\timing
delete from CDL_ENTRY_HEAD_GPTMP;
insert into CDL_ENTRY_HEAD_GPTMP (CMD_TYPE,PRE_ENTRY_ID) select CMD_TYPE,PRE_ENTRY_ID from CDL_ENTRY_HEAD_INC_EXT;
delete from CDL_ENTRY_HEAD_GPTMP_TODAY using CDL_ENTRY_HEAD_GPTMP where CDL_ENTRY_HEAD_GPTMP.PRE_ENTRY_ID=CDL_ENTRY_HEAD_GPTMP_TODAY.PRE_ENTRY_ID ;
insert into CDL_ENTRY_HEAD_GPTMP_TODAY (CMD_TYPE,PRE_ENTRY_ID,ENTRY_ID,LIST_DATE,I_E_PORT,TRADE_CO,OWNER_CODE,TRADE_MODE,TRADE_COUNTRY,DESTINATION_PORT,TRAF_MODE,DECL_PORT,MANUAL_NO) select CMD_TYPE,PRE_ENTRY_ID,ENTRY_ID,LIST_DATE,I_E_PORT,TRADE_CO,OWNER_CODE,TRADE_MODE,TRADE_COUNTRY,DESTINATION_PORT,TRAF_MODE,DECL_PORT,MANUAL_NO from CDL_ENTRY_HEAD_INC_EXT;
delete from CDL_ENTRY_HEAD_GPTMP;
\timing
