\echo ------------------CDL_COMPANY----------------
select now();
\timing
delete from CDL_COMPANY_GPTMP;
insert into CDL_COMPANY_GPTMP (CMD_TYPE,TRADE_CO, CUSTOMS_CODE, TRADE_BONDED_FLAG) select CMD_TYPE,TRADE_CO, CUSTOMS_CODE, TRADE_BONDED_FLAG from CDL_COMPANY_INC_EXT;
delete from CDL_COMPANY_GPTMP_TODAY using CDL_COMPANY_GPTMP where CDL_COMPANY_GPTMP.TRADE_CO=CDL_COMPANY_GPTMP_TODAY.TRADE_CO AND CDL_COMPANY_GPTMP.CUSTOMS_CODE=CDL_COMPANY_GPTMP_TODAY.CUSTOMS_CODE AND CDL_COMPANY_GPTMP.TRADE_BONDED_FLAG=CDL_COMPANY_GPTMP_TODAY.TRADE_BONDED_FLAG ;
insert into CDL_COMPANY_GPTMP_TODAY (CMD_TYPE,TRADE_CO,TRADE_NAME,CUSTOMS_CODE,APP_MOD_FLAG,TRADE_BONDED_FLAG,GRT_TYPE,GRT_PRICE,GRT_DATE,APPROVE_DATE,IE_COUNT,PRE_COP_NO) select CMD_TYPE,TRADE_CO,TRADE_NAME,CUSTOMS_CODE,APP_MOD_FLAG,TRADE_BONDED_FLAG,GRT_TYPE,GRT_PRICE,GRT_DATE,APPROVE_DATE,IE_COUNT,PRE_COP_NO from CDL_COMPANY_INC_EXT;
delete from CDL_COMPANY_GPTMP;
\timing
