\echo ------------------CDL_WORKFLOW----------------
select now();
\timing
delete from CDL_WORKFLOW_GPTMP;
insert into CDL_WORKFLOW_GPTMP (CMD_TYPE,LIST_NO, STEP_ID, CREATE_DATE) select CMD_TYPE,LIST_NO, STEP_ID, CREATE_DATE from CDL_WORKFLOW_INC_EXT;
delete from CDL_WORKFLOW_GPTMP_TODAY using CDL_WORKFLOW_GPTMP where CDL_WORKFLOW_GPTMP.LIST_NO=CDL_WORKFLOW_GPTMP_TODAY.LIST_NO AND CDL_WORKFLOW_GPTMP.STEP_ID=CDL_WORKFLOW_GPTMP_TODAY.STEP_ID AND CDL_WORKFLOW_GPTMP.CREATE_DATE=CDL_WORKFLOW_GPTMP_TODAY.CREATE_DATE ;
insert into CDL_WORKFLOW_GPTMP_TODAY (CMD_TYPE,LIST_NO,STEP_ID,CREATE_DATE,PROC_POS,STATUS_CODE,PROC_ER,PROC_RESULT,PREV_POS,PREV_ER,RECHK_MARK,RECHK_COMM) select CMD_TYPE,LIST_NO,STEP_ID,CREATE_DATE,PROC_POS,STATUS_CODE,PROC_ER,PROC_RESULT,PREV_POS,PREV_ER,RECHK_MARK,RECHK_COMM from CDL_WORKFLOW_INC_EXT;
delete from CDL_WORKFLOW_GPTMP;
\timing
