\echo ------------------CDL_OVERDUE_LIST----------------
select now();
\timing
delete from CDL_OVERDUE_LIST_GPTMP;
insert into CDL_OVERDUE_LIST_GPTMP (CMD_TYPE,TRADE_CO, ENTRY_ID) select CMD_TYPE,TRADE_CO, ENTRY_ID from CDL_OVERDUE_LIST_INC_EXT;
delete from CDL_OVERDUE_LIST_GPTMP_TODAY using CDL_OVERDUE_LIST_GPTMP where CDL_OVERDUE_LIST_GPTMP.TRADE_CO=CDL_OVERDUE_LIST_GPTMP_TODAY.TRADE_CO AND CDL_OVERDUE_LIST_GPTMP.ENTRY_ID=CDL_OVERDUE_LIST_GPTMP_TODAY.ENTRY_ID ;
insert into CDL_OVERDUE_LIST_GPTMP_TODAY (CMD_TYPE,TRADE_CO,TRADE_NAME,ENTRY_ID,TRADE_BONDED_FLAG,OVERDUE_DATE,OVERDUE_DAYS,OVERDUE_NOTES,CUSTOMS_CODE) select CMD_TYPE,TRADE_CO,TRADE_NAME,ENTRY_ID,TRADE_BONDED_FLAG,OVERDUE_DATE,OVERDUE_DAYS,OVERDUE_NOTES,CUSTOMS_CODE from CDL_OVERDUE_LIST_INC_EXT;
delete from CDL_OVERDUE_LIST_GPTMP;
\timing
