\echo ------------------CHK_COP_RATIO----------------
select now();
\timing
delete from CHK_COP_RATIO_GPTMP;
insert into CHK_COP_RATIO_GPTMP (CMD_TYPE,CORP_CODE) select CMD_TYPE,CORP_CODE from CHK_COP_RATIO_INC_EXT;
delete from CHK_COP_RATIO_GPTMP_TODAY using CHK_COP_RATIO_GPTMP where CHK_COP_RATIO_GPTMP.CORP_CODE=CHK_COP_RATIO_GPTMP_TODAY.CORP_CODE ;
insert into CHK_COP_RATIO_GPTMP_TODAY (CMD_TYPE,CORP_CODE,CORP_NAME,CUSTOMS_CODE,RATIO_NUM) select CMD_TYPE,CORP_CODE,CORP_NAME,CUSTOMS_CODE,RATIO_NUM from CHK_COP_RATIO_INC_EXT;
delete from CHK_COP_RATIO_GPTMP;
\timing
