\echo ------------------CHK_RATE_LIMIT----------------
select now();
\timing
delete from CHK_RATE_LIMIT_GPTMP;
insert into CHK_RATE_LIMIT_GPTMP (CMD_TYPE,CUSTOMS_CODE, I_E_FLAG) select CMD_TYPE,CUSTOMS_CODE, I_E_FLAG from CHK_RATE_LIMIT_INC_EXT;
delete from CHK_RATE_LIMIT_GPTMP_TODAY using CHK_RATE_LIMIT_GPTMP where CHK_RATE_LIMIT_GPTMP.CUSTOMS_CODE=CHK_RATE_LIMIT_GPTMP_TODAY.CUSTOMS_CODE AND CHK_RATE_LIMIT_GPTMP.I_E_FLAG=CHK_RATE_LIMIT_GPTMP_TODAY.I_E_FLAG ;
insert into CHK_RATE_LIMIT_GPTMP_TODAY (CMD_TYPE,CUSTOMS_CODE,I_E_FLAG,MAX_CHK_RATE,MAX_OPEN_RATE,RANDOM_CHK_RATE) select CMD_TYPE,CUSTOMS_CODE,I_E_FLAG,MAX_CHK_RATE,MAX_OPEN_RATE,RANDOM_CHK_RATE from CHK_RATE_LIMIT_INC_EXT;
delete from CHK_RATE_LIMIT_GPTMP;
\timing
