\echo ------------------CHK_COUNTER----------------
select now();
\timing
delete from CHK_COUNTER_GPTMP;
insert into CHK_COUNTER_GPTMP (CMD_TYPE,CUSTOMS_CODE, I_E_FLAG, COUNTER_TYPE, COUNT_DATE) select CMD_TYPE,CUSTOMS_CODE, I_E_FLAG, COUNTER_TYPE, COUNT_DATE from CHK_COUNTER_INC_EXT;
delete from CHK_COUNTER_GPTMP_TODAY using CHK_COUNTER_GPTMP where CHK_COUNTER_GPTMP.CUSTOMS_CODE=CHK_COUNTER_GPTMP_TODAY.CUSTOMS_CODE AND CHK_COUNTER_GPTMP.I_E_FLAG=CHK_COUNTER_GPTMP_TODAY.I_E_FLAG AND CHK_COUNTER_GPTMP.COUNTER_TYPE=CHK_COUNTER_GPTMP_TODAY.COUNTER_TYPE AND CHK_COUNTER_GPTMP.COUNT_DATE=CHK_COUNTER_GPTMP_TODAY.COUNT_DATE ;
insert into CHK_COUNTER_GPTMP_TODAY (CMD_TYPE,CUSTOMS_CODE,I_E_FLAG,COUNTER_TYPE,COUNT_DATE,COUNTER) select CMD_TYPE,CUSTOMS_CODE,I_E_FLAG,COUNTER_TYPE,COUNT_DATE,COUNTER from CHK_COUNTER_INC_EXT;
delete from CHK_COUNTER_GPTMP;
\timing
