\echo ------------------CHKHS_MNLPROC----------------
select now();
\timing
delete from CHKHS_MNLPROC_GPTMP;
insert into CHKHS_MNLPROC_GPTMP (CMD_TYPE,ORDER_NO, MANUAL_SCH) select CMD_TYPE,ORDER_NO, MANUAL_SCH from CHKHS_MNLPROC_INC_EXT;
delete from CHKHS_MNLPROC_GPTMP_TODAY using CHKHS_MNLPROC_GPTMP where CHKHS_MNLPROC_GPTMP.ORDER_NO=CHKHS_MNLPROC_GPTMP_TODAY.ORDER_NO AND CHKHS_MNLPROC_GPTMP.MANUAL_SCH=CHKHS_MNLPROC_GPTMP_TODAY.MANUAL_SCH ;
insert into CHKHS_MNLPROC_GPTMP_TODAY (CMD_TYPE,MANUAL_NO,PRE_MANUAL_NO,ORDER_NO,MANUAL_SCH,M_FLAG,TRADE_NAME,OPER_ER,OPER_DATE,NOTE) select CMD_TYPE,MANUAL_NO,PRE_MANUAL_NO,ORDER_NO,MANUAL_SCH,M_FLAG,TRADE_NAME,OPER_ER,OPER_DATE,NOTE from CHKHS_MNLPROC_INC_EXT;
delete from CHKHS_MNLPROC_GPTMP;
\timing
