\echo ------------------CIC_CODE----------------
select now();
\timing
delete from CIC_CODE_GPTMP;
insert into CIC_CODE_GPTMP (CMD_TYPE,FIRST_NO) select CMD_TYPE,FIRST_NO from CIC_CODE_INC_EXT;
delete from CIC_CODE_GPTMP_TODAY using CIC_CODE_GPTMP where CIC_CODE_GPTMP.FIRST_NO=CIC_CODE_GPTMP_TODAY.FIRST_NO ;
insert into CIC_CODE_GPTMP_TODAY (CMD_TYPE,FIRST_NO,LAST_NO,CUS_CODE,LOCAL_FLAG,INPUT_ER,INPUT_DATE,PRINT_DATE) select CMD_TYPE,FIRST_NO,LAST_NO,CUS_CODE,LOCAL_FLAG,INPUT_ER,INPUT_DATE,PRINT_DATE from CIC_CODE_INC_EXT;
delete from CIC_CODE_GPTMP;
\timing
