\echo ------------------CLC_GPR_RATIO_BAK----------------
select now();
\timing
delete from CLC_GPR_RATIO_BAK_GPTMP;
insert into CLC_GPR_RATIO_BAK_GPTMP (CMD_TYPE,CUSTOMS_CODE, I_E_FLAG, OP_TIME) select CMD_TYPE,CUSTOMS_CODE, I_E_FLAG, OP_TIME from CLC_GPR_RATIO_BAK_INC_EXT;
delete from CLC_GPR_RATIO_BAK_GPTMP_TODAY using CLC_GPR_RATIO_BAK_GPTMP where CLC_GPR_RATIO_BAK_GPTMP.CUSTOMS_CODE=CLC_GPR_RATIO_BAK_GPTMP_TODAY.CUSTOMS_CODE AND CLC_GPR_RATIO_BAK_GPTMP.I_E_FLAG=CLC_GPR_RATIO_BAK_GPTMP_TODAY.I_E_FLAG AND CLC_GPR_RATIO_BAK_GPTMP.OP_TIME=CLC_GPR_RATIO_BAK_GPTMP_TODAY.OP_TIME ;
insert into CLC_GPR_RATIO_BAK_GPTMP_TODAY (CMD_TYPE,CUSTOMS_CODE,I_E_FLAG,RATIO_NUM,OP_TIME,OP_ER,OP_CUSTOMS) select CMD_TYPE,CUSTOMS_CODE,I_E_FLAG,RATIO_NUM,OP_TIME,OP_ER,OP_CUSTOMS from CLC_GPR_RATIO_BAK_INC_EXT;
delete from CLC_GPR_RATIO_BAK_GPTMP;
\timing
