\echo ------------------CNS_COUNTER_TABLE----------------
select now();
\timing
delete from CNS_COUNTER_TABLE_GPTMP;
insert into CNS_COUNTER_TABLE_GPTMP (CMD_TYPE,CUSTOMS_CODE) select CMD_TYPE,CUSTOMS_CODE from CNS_COUNTER_TABLE_INC_EXT;
delete from CNS_COUNTER_TABLE_GPTMP_TODAY using CNS_COUNTER_TABLE_GPTMP where CNS_COUNTER_TABLE_GPTMP.CUSTOMS_CODE=CNS_COUNTER_TABLE_GPTMP_TODAY.CUSTOMS_CODE ;
insert into CNS_COUNTER_TABLE_GPTMP_TODAY (CMD_TYPE,CUSTOMS_CODE,COUNTER) select CMD_TYPE,CUSTOMS_CODE,COUNTER from CNS_COUNTER_TABLE_INC_EXT;
delete from CNS_COUNTER_TABLE_GPTMP;
\timing
