\echo ------------------CO_CLASS_REL----------------
select now();
\timing
delete from CO_CLASS_REL_GPTMP;
insert into CO_CLASS_REL_GPTMP (CMD_TYPE,TRADE_CO, CLASS_NO) select CMD_TYPE,TRADE_CO, CLASS_NO from CO_CLASS_REL_INC_EXT;
delete from CO_CLASS_REL_GPTMP_TODAY using CO_CLASS_REL_GPTMP where CO_CLASS_REL_GPTMP.TRADE_CO=CO_CLASS_REL_GPTMP_TODAY.TRADE_CO AND CO_CLASS_REL_GPTMP.CLASS_NO=CO_CLASS_REL_GPTMP_TODAY.CLASS_NO ;
insert into CO_CLASS_REL_GPTMP_TODAY (CMD_TYPE,TRADE_CO,CLASS_NO,CLASS_SOURCE,CLASS_DEST,CLASS_OPER_CODE,CLASS_OPER_DATE,CLASS_DPT_CODE,CLASS_DPT_DATE,CLASS_NOTE) select CMD_TYPE,TRADE_CO,CLASS_NO,CLASS_SOURCE,CLASS_DEST,CLASS_OPER_CODE,CLASS_OPER_DATE,CLASS_DPT_CODE,CLASS_DPT_DATE,CLASS_NOTE from CO_CLASS_REL_INC_EXT;
delete from CO_CLASS_REL_GPTMP;
\timing
