\echo ------------------CONSUME_DB----------------
select now();
\timing
delete from CONSUME_DB_GPTMP;
insert into CONSUME_DB_GPTMP (CMD_TYPE,EX_CODE_TS, EX_NO, IM_CODE_TS, IM_NO) select CMD_TYPE,EX_CODE_TS, EX_NO, IM_CODE_TS, IM_NO from CONSUME_DB_INC_EXT;
delete from CONSUME_DB_GPTMP_TODAY using CONSUME_DB_GPTMP where CONSUME_DB_GPTMP.EX_CODE_TS=CONSUME_DB_GPTMP_TODAY.EX_CODE_TS AND CONSUME_DB_GPTMP.EX_NO=CONSUME_DB_GPTMP_TODAY.EX_NO AND CONSUME_DB_GPTMP.IM_CODE_TS=CONSUME_DB_GPTMP_TODAY.IM_CODE_TS AND CONSUME_DB_GPTMP.IM_NO=CONSUME_DB_GPTMP_TODAY.IM_NO ;
insert into CONSUME_DB_GPTMP_TODAY (CMD_TYPE,EX_CODE_TS,EX_NO,IM_CODE_TS,IM_NO,CONSUME_RATIO,DAMAGE_RATIO,CONSUME_RANGE,CONSUME_NOTE,G_CLASS,INPUT_DATE,LIMIT_DATE) select CMD_TYPE,EX_CODE_TS,EX_NO,IM_CODE_TS,IM_NO,CONSUME_RATIO,DAMAGE_RATIO,CONSUME_RANGE,CONSUME_NOTE,G_CLASS,INPUT_DATE,LIMIT_DATE from CONSUME_DB_INC_EXT;
delete from CONSUME_DB_GPTMP;
\timing
