\echo ------------------CONSUME_GOODS----------------
select now();
\timing
delete from CONSUME_GOODS_GPTMP;
insert into CONSUME_GOODS_GPTMP (CMD_TYPE,CODE_TS, G_NO, G_FLAG) select CMD_TYPE,CODE_TS, G_NO, G_FLAG from CONSUME_GOODS_INC_EXT;
delete from CONSUME_GOODS_GPTMP_TODAY using CONSUME_GOODS_GPTMP where CONSUME_GOODS_GPTMP.CODE_TS=CONSUME_GOODS_GPTMP_TODAY.CODE_TS AND CONSUME_GOODS_GPTMP.G_NO=CONSUME_GOODS_GPTMP_TODAY.G_NO AND CONSUME_GOODS_GPTMP.G_FLAG=CONSUME_GOODS_GPTMP_TODAY.G_FLAG ;
insert into CONSUME_GOODS_GPTMP_TODAY (CMD_TYPE,CODE_TS,G_NO,G_FLAG,G_NAME,G_MODEL,UNIT_1,TRADE_COUNTRY,INFO_SOURCE,INPUT_DATE,NOTE_S) select CMD_TYPE,CODE_TS,G_NO,G_FLAG,G_NAME,G_MODEL,UNIT_1,TRADE_COUNTRY,INFO_SOURCE,INPUT_DATE,NOTE_S from CONSUME_GOODS_INC_EXT;
delete from CONSUME_GOODS_GPTMP;
\timing
