\echo ------------------CONTA_MONITOR----------------
select now();
\timing
delete from CONTA_MONITOR_GPTMP;
insert into CONTA_MONITOR_GPTMP (CMD_TYPE,I_E_FLAG, CONTA_ID, DISTRIBUTIVE_NO, IN_OUT_FLAG) select CMD_TYPE,I_E_FLAG, CONTA_ID, DISTRIBUTIVE_NO, IN_OUT_FLAG from CONTA_MONITOR_INC_EXT;
delete from CONTA_MONITOR_GPTMP_TODAY using CONTA_MONITOR_GPTMP where CONTA_MONITOR_GPTMP.I_E_FLAG=CONTA_MONITOR_GPTMP_TODAY.I_E_FLAG AND CONTA_MONITOR_GPTMP.CONTA_ID=CONTA_MONITOR_GPTMP_TODAY.CONTA_ID AND CONTA_MONITOR_GPTMP.DISTRIBUTIVE_NO=CONTA_MONITOR_GPTMP_TODAY.DISTRIBUTIVE_NO AND CONTA_MONITOR_GPTMP.IN_OUT_FLAG=CONTA_MONITOR_GPTMP_TODAY.IN_OUT_FLAG ;
insert into CONTA_MONITOR_GPTMP_TODAY (CMD_TYPE,I_E_FLAG,CONTA_ID,DISTRIBUTIVE_NO,IN_OUT_FLAG,TRANSIT_DATE,ORIGIN_CUS_CODE,DEST_CUS_CODE,FORM_FLAG,ORIGIN_CUS_PLACE,DEST_CUS_PLACE,DRIVER_NO,TRAF_MODE,SEAL_NO,TRANSIT_NAME,CAR_NUMBER,TRANSIT_WAY) select CMD_TYPE,I_E_FLAG,CONTA_ID,DISTRIBUTIVE_NO,IN_OUT_FLAG,TRANSIT_DATE,ORIGIN_CUS_CODE,DEST_CUS_CODE,FORM_FLAG,ORIGIN_CUS_PLACE,DEST_CUS_PLACE,DRIVER_NO,TRAF_MODE,SEAL_NO,TRANSIT_NAME,CAR_NUMBER,TRANSIT_WAY from CONTA_MONITOR_INC_EXT;
delete from CONTA_MONITOR_GPTMP;
\timing
