\echo ------------------CONVEYANCE----------------
select now();
\timing
delete from CONVEYANCE_GPTMP;
insert into CONVEYANCE_GPTMP (CMD_TYPE,SHIP_ID, TRAF_MODE) select CMD_TYPE,SHIP_ID, TRAF_MODE from CONVEYANCE_INC_EXT;
delete from CONVEYANCE_GPTMP_TODAY using CONVEYANCE_GPTMP where CONVEYANCE_GPTMP.SHIP_ID=CONVEYANCE_GPTMP_TODAY.SHIP_ID AND CONVEYANCE_GPTMP.TRAF_MODE=CONVEYANCE_GPTMP_TODAY.TRAF_MODE ;
insert into CONVEYANCE_GPTMP_TODAY (CMD_TYPE,SHIP_ID,TRAF_MODE,SHIP_NAME_EN,SHIP_NAME_CN,SHIP_NAME_ORI,COUNTRY_CODE,SHIP_TYPE,SHIP_ATTR,SHIP_USE_CODE,TONNAGE,CREATE_DATE,CREATE_ER,CUSTOMS_CODE) select CMD_TYPE,SHIP_ID,TRAF_MODE,SHIP_NAME_EN,SHIP_NAME_CN,SHIP_NAME_ORI,COUNTRY_CODE,SHIP_TYPE,SHIP_ATTR,SHIP_USE_CODE,TONNAGE,CREATE_DATE,CREATE_ER,CUSTOMS_CODE from CONVEYANCE_INC_EXT;
delete from CONVEYANCE_GPTMP;
\timing
