\echo ------------------CONVEYANCE_SEGMENT----------------
select now();
\timing
delete from CONVEYANCE_SEGMENT_GPTMP;
insert into CONVEYANCE_SEGMENT_GPTMP (CMD_TYPE,SHIP_ID, TRAF_MODE, VOYAGE_NO, I_E_FLAG, LOAD_PORT, DESTINATION_PORT, CUSTOMS_CODE, I_E_DATE) select CMD_TYPE,SHIP_ID, TRAF_MODE, VOYAGE_NO, I_E_FLAG, LOAD_PORT, DESTINATION_PORT, CUSTOMS_CODE, I_E_DATE from CONVEYANCE_SEGMENT_INC_EXT;
delete from CONVEYANCE_SEGMENT_GPTMP_TODAY using CONVEYANCE_SEGMENT_GPTMP where CONVEYANCE_SEGMENT_GPTMP.SHIP_ID=CONVEYANCE_SEGMENT_GPTMP_TODAY.SHIP_ID AND CONVEYANCE_SEGMENT_GPTMP.TRAF_MODE=CONVEYANCE_SEGMENT_GPTMP_TODAY.TRAF_MODE AND CONVEYANCE_SEGMENT_GPTMP.VOYAGE_NO=CONVEYANCE_SEGMENT_GPTMP_TODAY.VOYAGE_NO AND CONVEYANCE_SEGMENT_GPTMP.I_E_FLAG=CONVEYANCE_SEGMENT_GPTMP_TODAY.I_E_FLAG AND CONVEYANCE_SEGMENT_GPTMP.LOAD_PORT=CONVEYANCE_SEGMENT_GPTMP_TODAY.LOAD_PORT AND CONVEYANCE_SEGMENT_GPTMP.DESTINATION_PORT=CONVEYANCE_SEGMENT_GPTMP_TODAY.DESTINATION_PORT AND CONVEYANCE_SEGMENT_GPTMP.CUSTOMS_CODE=CONVEYANCE_SEGMENT_GPTMP_TODAY.CUSTOMS_CODE AND CONVEYANCE_SEGMENT_GPTMP.I_E_DATE=CONVEYANCE_SEGMENT_GPTMP_TODAY.I_E_DATE ;
insert into CONVEYANCE_SEGMENT_GPTMP_TODAY (CMD_TYPE,SHIP_ID,TRAF_MODE,VOYAGE_NO,I_E_FLAG,LOAD_PORT,DESTINATION_PORT,CUSTOMS_CODE,I_E_DATE) select CMD_TYPE,SHIP_ID,TRAF_MODE,VOYAGE_NO,I_E_FLAG,LOAD_PORT,DESTINATION_PORT,CUSTOMS_CODE,I_E_DATE from CONVEYANCE_SEGMENT_INC_EXT;
delete from CONVEYANCE_SEGMENT_GPTMP;
\timing
