\echo ------------------CORP_TABLE----------------
select now();
\timing
delete from CORP_TABLE_GPTMP;
insert into CORP_TABLE_GPTMP (CMD_TYPE,FIELD_ID, TABLE_ID) select CMD_TYPE,FIELD_ID, TABLE_ID from CORP_TABLE_INC_EXT;
delete from CORP_TABLE_GPTMP_TODAY using CORP_TABLE_GPTMP where CORP_TABLE_GPTMP.FIELD_ID=CORP_TABLE_GPTMP_TODAY.FIELD_ID AND CORP_TABLE_GPTMP.TABLE_ID=CORP_TABLE_GPTMP_TODAY.TABLE_ID ;
insert into CORP_TABLE_GPTMP_TODAY (CMD_TYPE,FIELD_ID,TABLE_ID,TABLE_NAME,FIELD_NAME) select CMD_TYPE,FIELD_ID,TABLE_ID,TABLE_NAME,FIELD_NAME from CORP_TABLE_INC_EXT;
delete from CORP_TABLE_GPTMP;
\timing
