\echo ------------------CORP_LIST----------------
select now();
\timing
delete from CORP_LIST_GPTMP;
insert into CORP_LIST_GPTMP (CMD_TYPE,FORM_ID, FIELD_ID) select CMD_TYPE,FORM_ID, FIELD_ID from CORP_LIST_INC_EXT;
delete from CORP_LIST_GPTMP_TODAY using CORP_LIST_GPTMP where CORP_LIST_GPTMP.FORM_ID=CORP_LIST_GPTMP_TODAY.FORM_ID AND CORP_LIST_GPTMP.FIELD_ID=CORP_LIST_GPTMP_TODAY.FIELD_ID ;
insert into CORP_LIST_GPTMP_TODAY (CMD_TYPE,FORM_ID,FIELD_ID,TX) select CMD_TYPE,FORM_ID,FIELD_ID,TX from CORP_LIST_INC_EXT;
delete from CORP_LIST_GPTMP;
\timing
