\echo ------------------CREDIT_INFO----------------
select now();
\timing
delete from CREDIT_INFO_GPTMP;
insert into CREDIT_INFO_GPTMP (CMD_TYPE,RPTNO) select CMD_TYPE,RPTNO from CREDIT_INFO_INC_EXT;
delete from CREDIT_INFO_GPTMP_TODAY using CREDIT_INFO_GPTMP where CREDIT_INFO_GPTMP.RPTNO=CREDIT_INFO_GPTMP_TODAY.RPTNO ;
insert into CREDIT_INFO_GPTMP_TODAY (CMD_TYPE,RPTNO,RPTUSER,TRADE_CO,RCVNAME,ACTUCCY,ACTUAMT,CSTSETCODE,COUNTRYCODE,CSTCNTRCTNO,INVOICENO,LCBGNO,RECV_DATE) select CMD_TYPE,RPTNO,RPTUSER,TRADE_CO,RCVNAME,ACTUCCY,ACTUAMT,CSTSETCODE,COUNTRYCODE,CSTCNTRCTNO,INVOICENO,LCBGNO,RECV_DATE from CREDIT_INFO_INC_EXT;
delete from CREDIT_INFO_GPTMP;
\timing
