\echo ------------------CTS_PERIOD----------------
select now();
\timing
delete from CTS_PERIOD_GPTMP;
insert into CTS_PERIOD_GPTMP (CMD_TYPE,CUSTOMS_CODE) select CMD_TYPE,CUSTOMS_CODE from CTS_PERIOD_INC_EXT;
delete from CTS_PERIOD_GPTMP_TODAY using CTS_PERIOD_GPTMP where CTS_PERIOD_GPTMP.CUSTOMS_CODE=CTS_PERIOD_GPTMP_TODAY.CUSTOMS_CODE ;
insert into CTS_PERIOD_GPTMP_TODAY (CMD_TYPE,CUSTOMS_CODE,EXAM_PERIOD,CHK_PERIOD,PROC_PERIOD,OP_ER,OP_TIME) select CMD_TYPE,CUSTOMS_CODE,EXAM_PERIOD,CHK_PERIOD,PROC_PERIOD,OP_ER,OP_TIME from CTS_PERIOD_INC_EXT;
delete from CTS_PERIOD_GPTMP;
\timing
