\echo ------------------CUSTOMS_DEFAULT----------------
select now();
\timing
delete from CUSTOMS_DEFAULT_GPTMP;
insert into CUSTOMS_DEFAULT_GPTMP (CMD_TYPE,MASTER_CUSTOMS) select CMD_TYPE,MASTER_CUSTOMS from CUSTOMS_DEFAULT_INC_EXT;
delete from CUSTOMS_DEFAULT_GPTMP_TODAY using CUSTOMS_DEFAULT_GPTMP where CUSTOMS_DEFAULT_GPTMP.MASTER_CUSTOMS=CUSTOMS_DEFAULT_GPTMP_TODAY.MASTER_CUSTOMS ;
insert into CUSTOMS_DEFAULT_GPTMP_TODAY (CMD_TYPE,MASTER_CUSTOMS,ADDRESS,POST_CODE,BANK_ACCOUNT,DEPARTMENT,PHONE_NO,RED_SWITCH,MODIFY_DATE,NOTE) select CMD_TYPE,MASTER_CUSTOMS,ADDRESS,POST_CODE,BANK_ACCOUNT,DEPARTMENT,PHONE_NO,RED_SWITCH,MODIFY_DATE,NOTE from CUSTOMS_DEFAULT_INC_EXT;
delete from CUSTOMS_DEFAULT_GPTMP;
\timing
