\echo ------------------DCG_WORKFLOW----------------
select now();
\timing
delete from DCG_WORKFLOW_GPTMP;
insert into DCG_WORKFLOW_GPTMP (CMD_TYPE,DCG_NO, STEP_ID, CREATE_DATE) select CMD_TYPE,DCG_NO, STEP_ID, CREATE_DATE from DCG_WORKFLOW_INC_EXT;
delete from DCG_WORKFLOW_GPTMP_TODAY using DCG_WORKFLOW_GPTMP where DCG_WORKFLOW_GPTMP.DCG_NO=DCG_WORKFLOW_GPTMP_TODAY.DCG_NO AND DCG_WORKFLOW_GPTMP.STEP_ID=DCG_WORKFLOW_GPTMP_TODAY.STEP_ID AND DCG_WORKFLOW_GPTMP.CREATE_DATE=DCG_WORKFLOW_GPTMP_TODAY.CREATE_DATE ;
insert into DCG_WORKFLOW_GPTMP_TODAY (CMD_TYPE,DCG_NO,STEP_ID,CREATE_DATE,PROC_ER,PROC_ID,PROC_POS,PROC_RESULT) select CMD_TYPE,DCG_NO,STEP_ID,CREATE_DATE,PROC_ER,PROC_ID,PROC_POS,PROC_RESULT from DCG_WORKFLOW_INC_EXT;
delete from DCG_WORKFLOW_GPTMP;
\timing
