\echo ------------------DCG_LIST----------------
select now();
\timing
delete from DCG_LIST_GPTMP;
insert into DCG_LIST_GPTMP (CMD_TYPE,DCG_NO, G_TYPE, G_NO) select CMD_TYPE,DCG_NO, G_TYPE, G_NO from DCG_LIST_INC_EXT;
delete from DCG_LIST_GPTMP_TODAY using DCG_LIST_GPTMP where DCG_LIST_GPTMP.DCG_NO=DCG_LIST_GPTMP_TODAY.DCG_NO AND DCG_LIST_GPTMP.G_TYPE=DCG_LIST_GPTMP_TODAY.G_TYPE AND DCG_LIST_GPTMP.G_NO=DCG_LIST_GPTMP_TODAY.G_NO ;
insert into DCG_LIST_GPTMP_TODAY (CMD_TYPE,DCG_NO,G_TYPE,G_NO,EX_G_NO,EMS_NO,EMS_G_NO,CODE_TS,G_NAME,G_MODEL,UNIT,QTY,UNIT_1,QTY_1,FACT_QTY,FACT_COUNT,BACK_COUNT,DEDUCT_QTY,DEDUCT_DATE,G_MARK,PAUSE_MARK,BAK_CODE_TS,MODIFY_MARK) select CMD_TYPE,DCG_NO,G_TYPE,G_NO,EX_G_NO,EMS_NO,EMS_G_NO,CODE_TS,G_NAME,G_MODEL,UNIT,QTY,UNIT_1,QTY_1,FACT_QTY,FACT_COUNT,BACK_COUNT,DEDUCT_QTY,DEDUCT_DATE,G_MARK,PAUSE_MARK,BAK_CODE_TS,MODIFY_MARK from DCG_LIST_INC_EXT;
delete from DCG_LIST_GPTMP;
\timing
