\echo ------------------DECLOG_MOD_REL----------------
select now();
\timing
delete from DECLOG_MOD_REL_GPTMP;
insert into DECLOG_MOD_REL_GPTMP (CMD_TYPE,DECL_CO, MOD_TIMES) select CMD_TYPE,DECL_CO, MOD_TIMES from DECLOG_MOD_REL_INC_EXT;
delete from DECLOG_MOD_REL_GPTMP_TODAY using DECLOG_MOD_REL_GPTMP where DECLOG_MOD_REL_GPTMP.DECL_CO=DECLOG_MOD_REL_GPTMP_TODAY.DECL_CO AND DECLOG_MOD_REL_GPTMP.MOD_TIMES=DECLOG_MOD_REL_GPTMP_TODAY.MOD_TIMES ;
insert into DECLOG_MOD_REL_GPTMP_TODAY (CMD_TYPE,TRADE_CO,DECL_CO,PRE_DECL_CO,TRADE_NAME,BROKER_TYPE,CUSTOMS_CODE,DECL_ZG_CODE,DECL_NAME,DECL_SEX,DECL_DEGREE,DECL_ID_CODE,DECL_BIRTHDAY,DECL_TEL_CODE,DECL_MOBILE_CODE,DECL_FAX_CODE,DECL_EMAIL_ADDR,DECL_CLASS,DECL_YD_FLAG,INP_DATE,IC_CODE,CTRL_MARK,CTRL_DATE,RG_DATE,APPL_CODE,CHK_DATE,CHK_CODE,VALID_DATE,SCORE,SCORE_DATE,CLEAR_DATE,YSCORE,FAULT_TIME,ENTRY_DECL_NUM,ENTRY_END_NUM,FAULT_ENTRY_NUM,LAST_YSCORE,LAST_FAULT_TIME,LAST_ENTRY_DECL_NUM,LAST_ENTRY_END_NUM,LAST_FAULT_ENTRY_NUM,CHANGE_TIME,NOTE,MOD_TIMES,LOG_OPER_ID,LOG_CUSTOMS_CODE,LOG_DATE,LOG_MODE) select CMD_TYPE,TRADE_CO,DECL_CO,PRE_DECL_CO,TRADE_NAME,BROKER_TYPE,CUSTOMS_CODE,DECL_ZG_CODE,DECL_NAME,DECL_SEX,DECL_DEGREE,DECL_ID_CODE,DECL_BIRTHDAY,DECL_TEL_CODE,DECL_MOBILE_CODE,DECL_FAX_CODE,DECL_EMAIL_ADDR,DECL_CLASS,DECL_YD_FLAG,INP_DATE,IC_CODE,CTRL_MARK,CTRL_DATE,RG_DATE,APPL_CODE,CHK_DATE,CHK_CODE,VALID_DATE,SCORE,SCORE_DATE,CLEAR_DATE,YSCORE,FAULT_TIME,ENTRY_DECL_NUM,ENTRY_END_NUM,FAULT_ENTRY_NUM,LAST_YSCORE,LAST_FAULT_TIME,LAST_ENTRY_DECL_NUM,LAST_ENTRY_END_NUM,LAST_FAULT_ENTRY_NUM,CHANGE_TIME,NOTE,MOD_TIMES,LOG_OPER_ID,LOG_CUSTOMS_CODE,LOG_DATE,LOG_MODE from DECLOG_MOD_REL_INC_EXT;
delete from DECLOG_MOD_REL_GPTMP;
\timing
