\echo ------------------DECLAR_COUNTER_REL----------------
select now();
\timing
delete from DECLAR_COUNTER_REL_GPTMP;
insert into DECLAR_COUNTER_REL_GPTMP (CMD_TYPE,DECL_KEY) select CMD_TYPE,DECL_KEY from DECLAR_COUNTER_REL_INC_EXT;
delete from DECLAR_COUNTER_REL_GPTMP_TODAY using DECLAR_COUNTER_REL_GPTMP where DECLAR_COUNTER_REL_GPTMP.DECL_KEY=DECLAR_COUNTER_REL_GPTMP_TODAY.DECL_KEY ;
insert into DECLAR_COUNTER_REL_GPTMP_TODAY (CMD_TYPE,DECL_KEY,COUNTER) select CMD_TYPE,DECL_KEY,COUNTER from DECLAR_COUNTER_REL_INC_EXT;
delete from DECLAR_COUNTER_REL_GPTMP;
\timing
