\echo ------------------DECLAR_REL----------------
select now();
\timing
delete from DECLAR_REL_GPTMP;
insert into DECLAR_REL_GPTMP (CMD_TYPE,DECL_CO, CUSTOMS_CODE) select CMD_TYPE,DECL_CO, CUSTOMS_CODE from DECLAR_REL_INC_EXT;
delete from DECLAR_REL_GPTMP_TODAY using DECLAR_REL_GPTMP where DECLAR_REL_GPTMP.DECL_CO=DECLAR_REL_GPTMP_TODAY.DECL_CO AND DECLAR_REL_GPTMP.CUSTOMS_CODE=DECLAR_REL_GPTMP_TODAY.CUSTOMS_CODE ;
insert into DECLAR_REL_GPTMP_TODAY (CMD_TYPE,TRADE_CO,DECL_CO,CUSTOMS_CODE,DECL_NAME,DECL_TYPE,DECL_CARD_VER,DECL_CARD_DATE,DECL_CARD_OP,DECL_TOTAL_ERROR,DECL_SUB_ERROR,DECL_SEX,DECL_DEGREE,DECL_ID_CODE,DECL_TEL_BP_CODE,DECL_LICE_DATE,DECL_FAULT_TIME,DECL_LOCK_FLAG,DECL_CANCEL_DATE,DECL_CHK_DATE,DECL_CHK_CODE,DECL_CLASS,DECL_NOTE,DECL_CHANGE,DECL_VALID_DATE,DECL_ZG_CODE,DECL_TRAIN_CO) select CMD_TYPE,TRADE_CO,DECL_CO,CUSTOMS_CODE,DECL_NAME,DECL_TYPE,DECL_CARD_VER,DECL_CARD_DATE,DECL_CARD_OP,DECL_TOTAL_ERROR,DECL_SUB_ERROR,DECL_SEX,DECL_DEGREE,DECL_ID_CODE,DECL_TEL_BP_CODE,DECL_LICE_DATE,DECL_FAULT_TIME,DECL_LOCK_FLAG,DECL_CANCEL_DATE,DECL_CHK_DATE,DECL_CHK_CODE,DECL_CLASS,DECL_NOTE,DECL_CHANGE,DECL_VALID_DATE,DECL_ZG_CODE,DECL_TRAIN_CO from DECLAR_REL_INC_EXT;
delete from DECLAR_REL_GPTMP;
\timing
