\echo ------------------DECLOG_SCORE_LIST----------------
select now();
\timing
delete from DECLOG_SCORE_LIST_GPTMP;
insert into DECLOG_SCORE_LIST_GPTMP (CMD_TYPE,DECL_CO, FORM_ID, SCORE_TIME, ITEM_NO) select CMD_TYPE,DECL_CO, FORM_ID, SCORE_TIME, ITEM_NO from DECLOG_SCORE_LIST_INC_EXT;
delete from DECLOG_SCORE_LIST_GPTMP_TODAY using DECLOG_SCORE_LIST_GPTMP where DECLOG_SCORE_LIST_GPTMP.DECL_CO=DECLOG_SCORE_LIST_GPTMP_TODAY.DECL_CO AND DECLOG_SCORE_LIST_GPTMP.FORM_ID=DECLOG_SCORE_LIST_GPTMP_TODAY.FORM_ID AND DECLOG_SCORE_LIST_GPTMP.SCORE_TIME=DECLOG_SCORE_LIST_GPTMP_TODAY.SCORE_TIME AND DECLOG_SCORE_LIST_GPTMP.ITEM_NO=DECLOG_SCORE_LIST_GPTMP_TODAY.ITEM_NO ;
insert into DECLOG_SCORE_LIST_GPTMP_TODAY (CMD_TYPE,DECL_CO,FORM_ID,SCORE_TIME,ITEM_NO,ERROR_TYPE,SEQ_NO,SCORE_DESC) select CMD_TYPE,DECL_CO,FORM_ID,SCORE_TIME,ITEM_NO,ERROR_TYPE,SEQ_NO,SCORE_DESC from DECLOG_SCORE_LIST_INC_EXT;
delete from DECLOG_SCORE_LIST_GPTMP;
\timing
