\echo ------------------DECL_CO_ENTRY_COUNT----------------
select now();
\timing
delete from DECL_CO_ENTRY_COUNT_GPTMP;
insert into DECL_CO_ENTRY_COUNT_GPTMP (CMD_TYPE,DECL_CO, RANDOM) select CMD_TYPE,DECL_CO, RANDOM from DECL_CO_ENTRY_COUNT_INC_EXT;
delete from DECL_CO_ENTRY_COUNT_GPTMP_TODAY using DECL_CO_ENTRY_COUNT_GPTMP where DECL_CO_ENTRY_COUNT_GPTMP.DECL_CO=DECL_CO_ENTRY_COUNT_GPTMP_TODAY.DECL_CO AND DECL_CO_ENTRY_COUNT_GPTMP.RANDOM=DECL_CO_ENTRY_COUNT_GPTMP_TODAY.RANDOM ;
insert into DECL_CO_ENTRY_COUNT_GPTMP_TODAY (CMD_TYPE,DECL_CO,GEN_DATE,RANDOM,ENTRY_DECL,ENTRY_END,FAULT_ENTRY,SCORE_DEDUCT) select CMD_TYPE,DECL_CO,GEN_DATE,RANDOM,ENTRY_DECL,ENTRY_END,FAULT_ENTRY,SCORE_DEDUCT from DECL_CO_ENTRY_COUNT_INC_EXT;
delete from DECL_CO_ENTRY_COUNT_GPTMP;
\timing
