\echo ------------------DEL_EGS_ARC_LIST----------------
select now();
\timing
delete from DEL_EGS_ARC_LIST_GPTMP;
insert into DEL_EGS_ARC_LIST_GPTMP (CMD_TYPE,EGS_NO, G_NO) select CMD_TYPE,EGS_NO, G_NO from DEL_EGS_ARC_LIST_INC_EXT;
delete from DEL_EGS_ARC_LIST_GPTMP_TODAY using DEL_EGS_ARC_LIST_GPTMP where DEL_EGS_ARC_LIST_GPTMP.EGS_NO=DEL_EGS_ARC_LIST_GPTMP_TODAY.EGS_NO AND DEL_EGS_ARC_LIST_GPTMP.G_NO=DEL_EGS_ARC_LIST_GPTMP_TODAY.G_NO ;
insert into DEL_EGS_ARC_LIST_GPTMP_TODAY (CMD_TYPE,EGS_NO,G_NO,CODE_TS,G_NAME) select CMD_TYPE,EGS_NO,G_NO,CODE_TS,G_NAME from DEL_EGS_ARC_LIST_INC_EXT;
delete from DEL_EGS_ARC_LIST_GPTMP;
\timing
