\echo ------------------DEL_EGS_ARC_AGENT_LIST----------------
select now();
\timing
delete from DEL_EGS_ARC_AGENT_LIST_GPTMP;
insert into DEL_EGS_ARC_AGENT_LIST_GPTMP (CMD_TYPE,EGS_NO, AGENT_NO) select CMD_TYPE,EGS_NO, AGENT_NO from DEL_EGS_ARC_AGENT_LIST_INC_EXT;
delete from DEL_EGS_ARC_AGENT_LIST_GPTMP_TODAY using DEL_EGS_ARC_AGENT_LIST_GPTMP where DEL_EGS_ARC_AGENT_LIST_GPTMP.EGS_NO=DEL_EGS_ARC_AGENT_LIST_GPTMP_TODAY.EGS_NO AND DEL_EGS_ARC_AGENT_LIST_GPTMP.AGENT_NO=DEL_EGS_ARC_AGENT_LIST_GPTMP_TODAY.AGENT_NO ;
insert into DEL_EGS_ARC_AGENT_LIST_GPTMP_TODAY (CMD_TYPE,EGS_NO,AGENT_NO,AGENT_CODE,AGENT_NAME) select CMD_TYPE,EGS_NO,AGENT_NO,AGENT_CODE,AGENT_NAME from DEL_EGS_ARC_AGENT_LIST_INC_EXT;
delete from DEL_EGS_ARC_AGENT_LIST_GPTMP;
\timing
