\echo ------------------DEL_MOD_APPLY----------------
select now();
\timing
delete from DEL_MOD_APPLY_GPTMP;
insert into DEL_MOD_APPLY_GPTMP (CMD_TYPE,ENTRY_ID, APPLY_TIME) select CMD_TYPE,ENTRY_ID, APPLY_TIME from DEL_MOD_APPLY_INC_EXT;
delete from DEL_MOD_APPLY_GPTMP_TODAY using DEL_MOD_APPLY_GPTMP where DEL_MOD_APPLY_GPTMP.ENTRY_ID=DEL_MOD_APPLY_GPTMP_TODAY.ENTRY_ID AND DEL_MOD_APPLY_GPTMP.APPLY_TIME=DEL_MOD_APPLY_GPTMP_TODAY.APPLY_TIME ;
insert into DEL_MOD_APPLY_GPTMP_TODAY (CMD_TYPE,ENTRY_ID,APPLY_TIME,APPLY_FLAG,APPLY_ER,APPLY_MARK,APPLY_COMM,RSK_CLASS,OP_FLAG,OP_TIME,OP_ER,OP_MARK,OP_COMM) select CMD_TYPE,ENTRY_ID,APPLY_TIME,APPLY_FLAG,APPLY_ER,APPLY_MARK,APPLY_COMM,RSK_CLASS,OP_FLAG,OP_TIME,OP_ER,OP_MARK,OP_COMM from DEL_MOD_APPLY_INC_EXT;
delete from DEL_MOD_APPLY_GPTMP;
\timing
