\echo ------------------DEL_EGS_DECLARE_CERT----------------
select now();
\timing
delete from DEL_EGS_DECLARE_CERT_GPTMP;
insert into DEL_EGS_DECLARE_CERT_GPTMP (CMD_TYPE,DECL_NO, CERT_CODE, CERT_NO) select CMD_TYPE,DECL_NO, CERT_CODE, CERT_NO from DEL_EGS_DECLARE_CERT_INC_EXT;
delete from DEL_EGS_DECLARE_CERT_GPTMP_TODAY using DEL_EGS_DECLARE_CERT_GPTMP where DEL_EGS_DECLARE_CERT_GPTMP.DECL_NO=DEL_EGS_DECLARE_CERT_GPTMP_TODAY.DECL_NO AND DEL_EGS_DECLARE_CERT_GPTMP.CERT_CODE=DEL_EGS_DECLARE_CERT_GPTMP_TODAY.CERT_CODE AND DEL_EGS_DECLARE_CERT_GPTMP.CERT_NO=DEL_EGS_DECLARE_CERT_GPTMP_TODAY.CERT_NO ;
insert into DEL_EGS_DECLARE_CERT_GPTMP_TODAY (CMD_TYPE,DECL_NO,CERT_CODE,CERT_NO) select CMD_TYPE,DECL_NO,CERT_CODE,CERT_NO from DEL_EGS_DECLARE_CERT_INC_EXT;
delete from DEL_EGS_DECLARE_CERT_GPTMP;
\timing
