\echo ------------------DEL_EGS_ARC_MERCHANT_LIST----------------
select now();
\timing
delete from DEL_EGS_ARC_MERCHANT_LIST_GPTMP;
insert into DEL_EGS_ARC_MERCHANT_LIST_GPTMP (CMD_TYPE,EGS_NO, AGENT_CODE, MERCHANT_NO) select CMD_TYPE,EGS_NO, AGENT_CODE, MERCHANT_NO from DEL_EGS_ARC_MERCHANT_LIST_INC_EXT;
delete from DEL_EGS_ARC_MERCHANT_LIST_GPTMP_TODAY using DEL_EGS_ARC_MERCHANT_LIST_GPTMP where DEL_EGS_ARC_MERCHANT_LIST_GPTMP.EGS_NO=DEL_EGS_ARC_MERCHANT_LIST_GPTMP_TODAY.EGS_NO AND DEL_EGS_ARC_MERCHANT_LIST_GPTMP.AGENT_CODE=DEL_EGS_ARC_MERCHANT_LIST_GPTMP_TODAY.AGENT_CODE AND DEL_EGS_ARC_MERCHANT_LIST_GPTMP.MERCHANT_NO=DEL_EGS_ARC_MERCHANT_LIST_GPTMP_TODAY.MERCHANT_NO ;
insert into DEL_EGS_ARC_MERCHANT_LIST_GPTMP_TODAY (CMD_TYPE,EGS_NO,MERCHANT_NO,MERCHANT_NAME,MERCHANT_COUNTRY,EXHIBITION_NO,EXHIBITION_SITE_NO,AGENT_CODE) select CMD_TYPE,EGS_NO,MERCHANT_NO,MERCHANT_NAME,MERCHANT_COUNTRY,EXHIBITION_NO,EXHIBITION_SITE_NO,AGENT_CODE from DEL_EGS_ARC_MERCHANT_LIST_INC_EXT;
delete from DEL_EGS_ARC_MERCHANT_LIST_GPTMP;
\timing
