\echo ------------------DST_IMG----------------
select now();
\timing
delete from DST_IMG_GPTMP;
insert into DST_IMG_GPTMP (CMD_TYPE,PRE_NO, G_NO, ORIGIN_COUNTRY) select CMD_TYPE,PRE_NO, G_NO, ORIGIN_COUNTRY from DST_IMG_INC_EXT;
delete from DST_IMG_GPTMP_TODAY using DST_IMG_GPTMP where DST_IMG_GPTMP.PRE_NO=DST_IMG_GPTMP_TODAY.PRE_NO AND DST_IMG_GPTMP.G_NO=DST_IMG_GPTMP_TODAY.G_NO AND DST_IMG_GPTMP.ORIGIN_COUNTRY=DST_IMG_GPTMP_TODAY.ORIGIN_COUNTRY ;
insert into DST_IMG_GPTMP_TODAY (CMD_TYPE,DST_SEQ_NO,PRE_NO,REL_NO,G_NO,CODE_TS,G_NAME,G_MODEL,G_QTY,G_UNIT,UNIT_1,QTY_1,DECL_PRICE,PRICE_1,TRADE_TOTAL,TRADE_CURR,ORIGIN_COUNTRY,MODIFY_MARK,DECL_DUTY,DECL_TAX,DECL_OTHER,DECL_TOTAL,CHK_DUTY,CHK_TAX,CHK_INTEREST,CHK_OTHER,CHK_TOTAL,IMG_PRICE,CONTRACT_PRICE,NORMAL_PRICE,PARAM_PRICE,NOTE,FACT_QTY) select CMD_TYPE,DST_SEQ_NO,PRE_NO,REL_NO,G_NO,CODE_TS,G_NAME,G_MODEL,G_QTY,G_UNIT,UNIT_1,QTY_1,DECL_PRICE,PRICE_1,TRADE_TOTAL,TRADE_CURR,ORIGIN_COUNTRY,MODIFY_MARK,DECL_DUTY,DECL_TAX,DECL_OTHER,DECL_TOTAL,CHK_DUTY,CHK_TAX,CHK_INTEREST,CHK_OTHER,CHK_TOTAL,IMG_PRICE,CONTRACT_PRICE,NORMAL_PRICE,PARAM_PRICE,NOTE,FACT_QTY from DST_IMG_INC_EXT;
delete from DST_IMG_GPTMP;
\timing
