\echo ------------------DST_DEDUCT----------------
select now();
\timing
delete from DST_DEDUCT_GPTMP;
insert into DST_DEDUCT_GPTMP (CMD_TYPE,PRE_NO, G_NO, ORIGIN_COUNTRY, ENTRY_ID, ENTRY_G_NO) select CMD_TYPE,PRE_NO, G_NO, ORIGIN_COUNTRY, ENTRY_ID, ENTRY_G_NO from DST_DEDUCT_INC_EXT;
delete from DST_DEDUCT_GPTMP_TODAY using DST_DEDUCT_GPTMP where DST_DEDUCT_GPTMP.PRE_NO=DST_DEDUCT_GPTMP_TODAY.PRE_NO AND DST_DEDUCT_GPTMP.G_NO=DST_DEDUCT_GPTMP_TODAY.G_NO AND DST_DEDUCT_GPTMP.ORIGIN_COUNTRY=DST_DEDUCT_GPTMP_TODAY.ORIGIN_COUNTRY AND DST_DEDUCT_GPTMP.ENTRY_ID=DST_DEDUCT_GPTMP_TODAY.ENTRY_ID AND DST_DEDUCT_GPTMP.ENTRY_G_NO=DST_DEDUCT_GPTMP_TODAY.ENTRY_G_NO ;
insert into DST_DEDUCT_GPTMP_TODAY (CMD_TYPE,PRE_NO,REL_NO,G_NO,ENTRY_ID,ENTRY_G_NO,I_E_FLAG,G_QTY,VERIFY_DATE,VERIFY_ER,ORIGIN_COUNTRY) select CMD_TYPE,PRE_NO,REL_NO,G_NO,ENTRY_ID,ENTRY_G_NO,I_E_FLAG,G_QTY,VERIFY_DATE,VERIFY_ER,ORIGIN_COUNTRY from DST_DEDUCT_INC_EXT;
delete from DST_DEDUCT_GPTMP;
\timing
