\echo ------------------DTT_COP_PARAM----------------
select now();
\timing
delete from DTT_COP_PARAM_GPTMP;
insert into DTT_COP_PARAM_GPTMP (CMD_TYPE,CORP_CODE, CUSTOMS_CODE) select CMD_TYPE,CORP_CODE, CUSTOMS_CODE from DTT_COP_PARAM_INC_EXT;
delete from DTT_COP_PARAM_GPTMP_TODAY using DTT_COP_PARAM_GPTMP where DTT_COP_PARAM_GPTMP.CORP_CODE=DTT_COP_PARAM_GPTMP_TODAY.CORP_CODE AND DTT_COP_PARAM_GPTMP.CUSTOMS_CODE=DTT_COP_PARAM_GPTMP_TODAY.CUSTOMS_CODE ;
insert into DTT_COP_PARAM_GPTMP_TODAY (CMD_TYPE,CORP_CODE,CUSTOMS_CODE,CORP_NAME,PROC_ER,PROC_DATE) select CMD_TYPE,CORP_CODE,CUSTOMS_CODE,CORP_NAME,PROC_ER,PROC_DATE from DTT_COP_PARAM_INC_EXT;
delete from DTT_COP_PARAM_GPTMP;
\timing
