\echo ------------------ECO_WORKFLOW----------------
select now();
\timing
delete from ECO_WORKFLOW_GPTMP;
insert into ECO_WORKFLOW_GPTMP (CMD_TYPE,CERTIFICATE_NO, TRANSFER_NUM, PROCESS_STATUS, PROCESS_DATE) select CMD_TYPE,CERTIFICATE_NO, TRANSFER_NUM, PROCESS_STATUS, PROCESS_DATE from ECO_WORKFLOW_INC_EXT;
delete from ECO_WORKFLOW_GPTMP_TODAY using ECO_WORKFLOW_GPTMP where ECO_WORKFLOW_GPTMP.CERTIFICATE_NO=ECO_WORKFLOW_GPTMP_TODAY.CERTIFICATE_NO AND ECO_WORKFLOW_GPTMP.TRANSFER_NUM=ECO_WORKFLOW_GPTMP_TODAY.TRANSFER_NUM AND ECO_WORKFLOW_GPTMP.PROCESS_STATUS=ECO_WORKFLOW_GPTMP_TODAY.PROCESS_STATUS AND ECO_WORKFLOW_GPTMP.PROCESS_DATE=ECO_WORKFLOW_GPTMP_TODAY.PROCESS_DATE ;
insert into ECO_WORKFLOW_GPTMP_TODAY (CMD_TYPE,CERTIFICATE_NO,TRANSFER_NUM,PROCESS_STATUS,PROCESS_DATE,ENTRY_ID,NOTE) select CMD_TYPE,CERTIFICATE_NO,TRANSFER_NUM,PROCESS_STATUS,PROCESS_DATE,ENTRY_ID,NOTE from ECO_WORKFLOW_INC_EXT;
delete from ECO_WORKFLOW_GPTMP;
\timing
