\echo ------------------ECO_PARTS----------------
select now();
\timing
delete from ECO_PARTS_GPTMP;
insert into ECO_PARTS_GPTMP (CMD_TYPE,CERTIFICATE_NO, G_NO, PART_SEQ) select CMD_TYPE,CERTIFICATE_NO, G_NO, PART_SEQ from ECO_PARTS_INC_EXT;
delete from ECO_PARTS_GPTMP_TODAY using ECO_PARTS_GPTMP where ECO_PARTS_GPTMP.CERTIFICATE_NO=ECO_PARTS_GPTMP_TODAY.CERTIFICATE_NO AND ECO_PARTS_GPTMP.G_NO=ECO_PARTS_GPTMP_TODAY.G_NO AND ECO_PARTS_GPTMP.PART_SEQ=ECO_PARTS_GPTMP_TODAY.PART_SEQ ;
insert into ECO_PARTS_GPTMP_TODAY (CMD_TYPE,CERTIFICATE_NO,G_NO,PART_SEQ,PART_HSCODE,PART_NAME,UNIT_PRICE,ORIGIN_COUNTRY,AMT_PERCENT) select CMD_TYPE,CERTIFICATE_NO,G_NO,PART_SEQ,PART_HSCODE,PART_NAME,UNIT_PRICE,ORIGIN_COUNTRY,AMT_PERCENT from ECO_PARTS_INC_EXT;
delete from ECO_PARTS_GPTMP;
\timing
