\echo ------------------EGS_CHECK_LOG----------------
select now();
\timing
delete from EGS_CHECK_LOG_GPTMP;
insert into EGS_CHECK_LOG_GPTMP (CMD_TYPE,EGS_NO, CHK_TIMES, FORM_TYPE, G_NO) select CMD_TYPE,EGS_NO, CHK_TIMES, FORM_TYPE, G_NO from EGS_CHECK_LOG_INC_EXT;
delete from EGS_CHECK_LOG_GPTMP_TODAY using EGS_CHECK_LOG_GPTMP where EGS_CHECK_LOG_GPTMP.EGS_NO=EGS_CHECK_LOG_GPTMP_TODAY.EGS_NO AND EGS_CHECK_LOG_GPTMP.CHK_TIMES=EGS_CHECK_LOG_GPTMP_TODAY.CHK_TIMES AND EGS_CHECK_LOG_GPTMP.FORM_TYPE=EGS_CHECK_LOG_GPTMP_TODAY.FORM_TYPE AND EGS_CHECK_LOG_GPTMP.G_NO=EGS_CHECK_LOG_GPTMP_TODAY.G_NO ;
insert into EGS_CHECK_LOG_GPTMP_TODAY (CMD_TYPE,EGS_NO,EPORT_NO,CHK_TIMES,FORM_TYPE,G_NO,EGS_TYPE,CHK_MARK,CHK_ER,CHK_DATE,CHK_RESULT,MESSAGE,NOTE) select CMD_TYPE,EGS_NO,EPORT_NO,CHK_TIMES,FORM_TYPE,G_NO,EGS_TYPE,CHK_MARK,CHK_ER,CHK_DATE,CHK_RESULT,MESSAGE,NOTE from EGS_CHECK_LOG_INC_EXT;
delete from EGS_CHECK_LOG_GPTMP;
\timing
