\echo ------------------EGS_ADMIT_HS----------------
select now();
\timing
delete from EGS_ADMIT_HS_GPTMP;
insert into EGS_ADMIT_HS_GPTMP (CMD_TYPE,ADM_NO, CODE_TS) select CMD_TYPE,ADM_NO, CODE_TS from EGS_ADMIT_HS_INC_EXT;
delete from EGS_ADMIT_HS_GPTMP_TODAY using EGS_ADMIT_HS_GPTMP where EGS_ADMIT_HS_GPTMP.ADM_NO=EGS_ADMIT_HS_GPTMP_TODAY.ADM_NO AND EGS_ADMIT_HS_GPTMP.CODE_TS=EGS_ADMIT_HS_GPTMP_TODAY.CODE_TS ;
insert into EGS_ADMIT_HS_GPTMP_TODAY (CMD_TYPE,ADM_NO,CODE_TS) select CMD_TYPE,ADM_NO,CODE_TS from EGS_ADMIT_HS_INC_EXT;
delete from EGS_ADMIT_HS_GPTMP;
\timing
