\echo ------------------EGS_ADMIT_LIST----------------
select now();
\timing
delete from EGS_ADMIT_LIST_GPTMP;
insert into EGS_ADMIT_LIST_GPTMP (CMD_TYPE,ADM_NO, G_NO) select CMD_TYPE,ADM_NO, G_NO from EGS_ADMIT_LIST_INC_EXT;
delete from EGS_ADMIT_LIST_GPTMP_TODAY using EGS_ADMIT_LIST_GPTMP where EGS_ADMIT_LIST_GPTMP.ADM_NO=EGS_ADMIT_LIST_GPTMP_TODAY.ADM_NO AND EGS_ADMIT_LIST_GPTMP.G_NO=EGS_ADMIT_LIST_GPTMP_TODAY.G_NO ;
insert into EGS_ADMIT_LIST_GPTMP_TODAY (CMD_TYPE,ADM_NO,G_NO,CODE_TS,G_NAME) select CMD_TYPE,ADM_NO,G_NO,CODE_TS,G_NAME from EGS_ADMIT_LIST_INC_EXT;
delete from EGS_ADMIT_LIST_GPTMP;
\timing
