\echo ------------------EGS_DECLARE_HEAD----------------
select now();
\timing
delete from EGS_DECLARE_HEAD_GPTMP;
insert into EGS_DECLARE_HEAD_GPTMP (CMD_TYPE,DECL_NO) select CMD_TYPE,DECL_NO from EGS_DECLARE_HEAD_INC_EXT;
delete from EGS_DECLARE_HEAD_GPTMP_TODAY using EGS_DECLARE_HEAD_GPTMP where EGS_DECLARE_HEAD_GPTMP.DECL_NO=EGS_DECLARE_HEAD_GPTMP_TODAY.DECL_NO ;
insert into EGS_DECLARE_HEAD_GPTMP_TODAY (CMD_TYPE,EGS_NO,EGS_NAME,ADM_NO,DECL_NO,PRE_DECL_NO,DECL_TYPE,MASTER_CUSTOMS,I_E_PORT,I_E_DATE,I_E_FLAG,DECLARE_DATE,AGENT_CODE,AGENT_NAME,DECLARE_NO,DECLARE_PHONE,LICENSE_NO,TRAF_MODE,BILL_NO,BILL_SUB_NO,TRADE_COUNTRY,GROSS_WT,NET_WT,WRAP_TYPE,PACK_NO,TRANS_MODE,NOTES,DEPOSIT_MARK,REL_DATE,TRANS_DATE,POSTPONE_TIMES,ZS_APPR_NO,TURN_NO,ENTRY_ID,ENTRY_TYPE,DECLARE_SOURCE,CHK_MARK,EX_CUSTOMS_CODE,EX_EGS_NO,EX_EGS_NAME,EX_AGENT_CODE,EX_AGENT_NAME,AUDIT_ER,AUDIT_DATE,AUDIT_NOTE,VERIFY_DATE,VERIFY_ER,CLEAR_DATE,CLEAR_ER,EXE_MARK) select CMD_TYPE,EGS_NO,EGS_NAME,ADM_NO,DECL_NO,PRE_DECL_NO,DECL_TYPE,MASTER_CUSTOMS,I_E_PORT,I_E_DATE,I_E_FLAG,DECLARE_DATE,AGENT_CODE,AGENT_NAME,DECLARE_NO,DECLARE_PHONE,LICENSE_NO,TRAF_MODE,BILL_NO,BILL_SUB_NO,TRADE_COUNTRY,GROSS_WT,NET_WT,WRAP_TYPE,PACK_NO,TRANS_MODE,NOTES,DEPOSIT_MARK,REL_DATE,TRANS_DATE,POSTPONE_TIMES,ZS_APPR_NO,TURN_NO,ENTRY_ID,ENTRY_TYPE,DECLARE_SOURCE,CHK_MARK,EX_CUSTOMS_CODE,EX_EGS_NO,EX_EGS_NAME,EX_AGENT_CODE,EX_AGENT_NAME,AUDIT_ER,AUDIT_DATE,AUDIT_NOTE,VERIFY_DATE,VERIFY_ER,CLEAR_DATE,CLEAR_ER,EXE_MARK from EGS_DECLARE_HEAD_INC_EXT;
delete from EGS_DECLARE_HEAD_GPTMP;
\timing
