\echo ------------------EGS_ARC_LIST----------------
select now();
\timing
delete from EGS_ARC_LIST_GPTMP;
insert into EGS_ARC_LIST_GPTMP (CMD_TYPE,EGS_NO, G_NO) select CMD_TYPE,EGS_NO, G_NO from EGS_ARC_LIST_INC_EXT;
delete from EGS_ARC_LIST_GPTMP_TODAY using EGS_ARC_LIST_GPTMP where EGS_ARC_LIST_GPTMP.EGS_NO=EGS_ARC_LIST_GPTMP_TODAY.EGS_NO AND EGS_ARC_LIST_GPTMP.G_NO=EGS_ARC_LIST_GPTMP_TODAY.G_NO ;
insert into EGS_ARC_LIST_GPTMP_TODAY (CMD_TYPE,EGS_NO,G_NO,CODE_TS,G_NAME) select CMD_TYPE,EGS_NO,G_NO,CODE_TS,G_NAME from EGS_ARC_LIST_INC_EXT;
delete from EGS_ARC_LIST_GPTMP;
\timing
