\echo ------------------EGS_CLEAR_CERT----------------
select now();
\timing
delete from EGS_CLEAR_CERT_GPTMP;
insert into EGS_CLEAR_CERT_GPTMP (CMD_TYPE,CLR_NO, CERT_CODE, CERT_NO) select CMD_TYPE,CLR_NO, CERT_CODE, CERT_NO from EGS_CLEAR_CERT_INC_EXT;
delete from EGS_CLEAR_CERT_GPTMP_TODAY using EGS_CLEAR_CERT_GPTMP where EGS_CLEAR_CERT_GPTMP.CLR_NO=EGS_CLEAR_CERT_GPTMP_TODAY.CLR_NO AND EGS_CLEAR_CERT_GPTMP.CERT_CODE=EGS_CLEAR_CERT_GPTMP_TODAY.CERT_CODE AND EGS_CLEAR_CERT_GPTMP.CERT_NO=EGS_CLEAR_CERT_GPTMP_TODAY.CERT_NO ;
insert into EGS_CLEAR_CERT_GPTMP_TODAY (CMD_TYPE,CLR_NO,CERT_CODE,CERT_NO) select CMD_TYPE,CLR_NO,CERT_CODE,CERT_NO from EGS_CLEAR_CERT_INC_EXT;
delete from EGS_CLEAR_CERT_GPTMP;
\timing
