\echo ------------------EGS_DECLARE_CERT----------------
select now();
\timing
delete from EGS_DECLARE_CERT_GPTMP;
insert into EGS_DECLARE_CERT_GPTMP (CMD_TYPE,DECL_NO, CERT_CODE, CERT_NO) select CMD_TYPE,DECL_NO, CERT_CODE, CERT_NO from EGS_DECLARE_CERT_INC_EXT;
delete from EGS_DECLARE_CERT_GPTMP_TODAY using EGS_DECLARE_CERT_GPTMP where EGS_DECLARE_CERT_GPTMP.DECL_NO=EGS_DECLARE_CERT_GPTMP_TODAY.DECL_NO AND EGS_DECLARE_CERT_GPTMP.CERT_CODE=EGS_DECLARE_CERT_GPTMP_TODAY.CERT_CODE AND EGS_DECLARE_CERT_GPTMP.CERT_NO=EGS_DECLARE_CERT_GPTMP_TODAY.CERT_NO ;
insert into EGS_DECLARE_CERT_GPTMP_TODAY (CMD_TYPE,DECL_NO,CERT_CODE,CERT_NO) select CMD_TYPE,DECL_NO,CERT_CODE,CERT_NO from EGS_DECLARE_CERT_INC_EXT;
delete from EGS_DECLARE_CERT_GPTMP;
\timing
