\echo ------------------EMS_DCR_ENT----------------
select now();
\timing
delete from EMS_DCR_ENT_GPTMP;
insert into EMS_DCR_ENT_GPTMP (CMD_TYPE,EMS_NO, DCR_TIMES, ENTRY_ID) select CMD_TYPE,EMS_NO, DCR_TIMES, ENTRY_ID from EMS_DCR_ENT_INC_EXT;
delete from EMS_DCR_ENT_GPTMP_TODAY using EMS_DCR_ENT_GPTMP where EMS_DCR_ENT_GPTMP.EMS_NO=EMS_DCR_ENT_GPTMP_TODAY.EMS_NO AND EMS_DCR_ENT_GPTMP.DCR_TIMES=EMS_DCR_ENT_GPTMP_TODAY.DCR_TIMES AND EMS_DCR_ENT_GPTMP.ENTRY_ID=EMS_DCR_ENT_GPTMP_TODAY.ENTRY_ID ;
insert into EMS_DCR_ENT_GPTMP_TODAY (CMD_TYPE,EMS_NO,DCR_TIMES,ENTRY_ID,MASTER_CUSTOMS,I_E_FLAG,ITEMS_NUM,DECLARE_DATE,I_E_DATE,DU_CODE,ENT_MARK,NOTE,MODIFY_MARK) select CMD_TYPE,EMS_NO,DCR_TIMES,ENTRY_ID,MASTER_CUSTOMS,I_E_FLAG,ITEMS_NUM,DECLARE_DATE,I_E_DATE,DU_CODE,ENT_MARK,NOTE,MODIFY_MARK from EMS_DCR_ENT_INC_EXT;
delete from EMS_DCR_ENT_GPTMP;
\timing
