\echo ------------------EMS_ENP----------------
select now();
\timing
delete from EMS_ENP_GPTMP;
insert into EMS_ENP_GPTMP (CMD_TYPE,ENP_ID) select CMD_TYPE,ENP_ID from EMS_ENP_INC_EXT;
delete from EMS_ENP_GPTMP_TODAY using EMS_ENP_GPTMP where EMS_ENP_GPTMP.ENP_ID=EMS_ENP_GPTMP_TODAY.ENP_ID ;
insert into EMS_ENP_GPTMP_TODAY (CMD_TYPE,ENP_ID,ENP_SEQ,MASTER_CUSTOMS,I_E_PORT,OWNER_CODE,OWNER_NAME,TRAF_MODE,I_E_MARK,ENP_MARK,ENP_TYPE,EXE_MARK,PROCESS_MARK,ENP_NUM,DEC_DATE,SIGN_DATE,REL_DATE,END_DATE,NOTE_1,NOTE) select CMD_TYPE,ENP_ID,ENP_SEQ,MASTER_CUSTOMS,I_E_PORT,OWNER_CODE,OWNER_NAME,TRAF_MODE,I_E_MARK,ENP_MARK,ENP_TYPE,EXE_MARK,PROCESS_MARK,ENP_NUM,DEC_DATE,SIGN_DATE,REL_DATE,END_DATE,NOTE_1,NOTE from EMS_ENP_INC_EXT;
delete from EMS_ENP_GPTMP;
\timing
