\echo ------------------EMS_WORKFLOW----------------
select now();
\timing
delete from EMS_WORKFLOW_GPTMP;
insert into EMS_WORKFLOW_GPTMP (CMD_TYPE,EMS_NO, STEP_ID, CREATE_DATE) select CMD_TYPE,EMS_NO, STEP_ID, CREATE_DATE from EMS_WORKFLOW_INC_EXT;
delete from EMS_WORKFLOW_GPTMP_TODAY using EMS_WORKFLOW_GPTMP where EMS_WORKFLOW_GPTMP.EMS_NO=EMS_WORKFLOW_GPTMP_TODAY.EMS_NO AND EMS_WORKFLOW_GPTMP.STEP_ID=EMS_WORKFLOW_GPTMP_TODAY.STEP_ID AND EMS_WORKFLOW_GPTMP.CREATE_DATE=EMS_WORKFLOW_GPTMP_TODAY.CREATE_DATE ;
insert into EMS_WORKFLOW_GPTMP_TODAY (CMD_TYPE,EMS_NO,STEP_ID,CREATE_DATE,PROC_ER,PROC_ID,PROC_POS,PROC_RESULT) select CMD_TYPE,EMS_NO,STEP_ID,CREATE_DATE,PROC_ER,PROC_ID,PROC_POS,PROC_RESULT from EMS_WORKFLOW_INC_EXT;
delete from EMS_WORKFLOW_GPTMP;
\timing
