\echo ------------------EMS_COMPLEX2----------------
select now();
\timing
delete from EMS_COMPLEX2_GPTMP;
insert into EMS_COMPLEX2_GPTMP (CMD_TYPE,ICODE_TS, ECODE_TS) select CMD_TYPE,ICODE_TS, ECODE_TS from EMS_COMPLEX2_INC_EXT;
delete from EMS_COMPLEX2_GPTMP_TODAY using EMS_COMPLEX2_GPTMP where EMS_COMPLEX2_GPTMP.ICODE_TS=EMS_COMPLEX2_GPTMP_TODAY.ICODE_TS AND EMS_COMPLEX2_GPTMP.ECODE_TS=EMS_COMPLEX2_GPTMP_TODAY.ECODE_TS ;
insert into EMS_COMPLEX2_GPTMP_TODAY (CMD_TYPE,ICODE_TS,IG_NAME,IG_MODEL,ICLASSIFY,ECODE_TS,EG_NAME,EG_MODEL,ECLASSIFY,INPUT_DATE,LIMIT_TYPE,LIMIT_DESC,NOTE) select CMD_TYPE,ICODE_TS,IG_NAME,IG_MODEL,ICLASSIFY,ECODE_TS,EG_NAME,EG_MODEL,ECLASSIFY,INPUT_DATE,LIMIT_TYPE,LIMIT_DESC,NOTE from EMS_COMPLEX2_INC_EXT;
delete from EMS_COMPLEX2_GPTMP;
\timing
