\echo ------------------EMS_MESSAGE_LOG----------------
select now();
\timing
delete from EMS_MESSAGE_LOG_GPTMP;
insert into EMS_MESSAGE_LOG_GPTMP (CMD_TYPE,EMS_NO, SEND_CUSTOMS, CUSTOMS_CODE, H2000_RECEIVE_DATE) select CMD_TYPE,EMS_NO, SEND_CUSTOMS, CUSTOMS_CODE, H2000_RECEIVE_DATE from EMS_MESSAGE_LOG_INC_EXT;
delete from EMS_MESSAGE_LOG_GPTMP_TODAY using EMS_MESSAGE_LOG_GPTMP where EMS_MESSAGE_LOG_GPTMP.EMS_NO=EMS_MESSAGE_LOG_GPTMP_TODAY.EMS_NO AND EMS_MESSAGE_LOG_GPTMP.SEND_CUSTOMS=EMS_MESSAGE_LOG_GPTMP_TODAY.SEND_CUSTOMS AND EMS_MESSAGE_LOG_GPTMP.CUSTOMS_CODE=EMS_MESSAGE_LOG_GPTMP_TODAY.CUSTOMS_CODE AND EMS_MESSAGE_LOG_GPTMP.H2000_RECEIVE_DATE=EMS_MESSAGE_LOG_GPTMP_TODAY.H2000_RECEIVE_DATE ;
insert into EMS_MESSAGE_LOG_GPTMP_TODAY (CMD_TYPE,EMS_NO,SEND_CUSTOMS,CUSTOMS_CODE,H2000_RECEIVE_DATE,MESSAGE_ID,MESSAGE_FLAG,MESSAGE_TYPE,RECEIVE_DATE,TYPE,SEND_TIMES,APPL_NO,STATUS,FLAG,NOTE) select CMD_TYPE,EMS_NO,SEND_CUSTOMS,CUSTOMS_CODE,H2000_RECEIVE_DATE,MESSAGE_ID,MESSAGE_FLAG,MESSAGE_TYPE,RECEIVE_DATE,TYPE,SEND_TIMES,APPL_NO,STATUS,FLAG,NOTE from EMS_MESSAGE_LOG_INC_EXT;
delete from EMS_MESSAGE_LOG_GPTMP;
\timing
