\echo ------------------EMS_CONSUME_CLR_D----------------
select now();
\timing
delete from EMS_CONSUME_CLR_D_GPTMP;
insert into EMS_CONSUME_CLR_D_GPTMP (CMD_TYPE,EMS_NO, IMG_NO, EXG_NO, EXG_VERSION) select CMD_TYPE,EMS_NO, IMG_NO, EXG_NO, EXG_VERSION from EMS_CONSUME_CLR_D_INC_EXT;
delete from EMS_CONSUME_CLR_D_GPTMP_TODAY using EMS_CONSUME_CLR_D_GPTMP where EMS_CONSUME_CLR_D_GPTMP.EMS_NO=EMS_CONSUME_CLR_D_GPTMP_TODAY.EMS_NO AND EMS_CONSUME_CLR_D_GPTMP.IMG_NO=EMS_CONSUME_CLR_D_GPTMP_TODAY.IMG_NO AND EMS_CONSUME_CLR_D_GPTMP.EXG_NO=EMS_CONSUME_CLR_D_GPTMP_TODAY.EXG_NO AND EMS_CONSUME_CLR_D_GPTMP.EXG_VERSION=EMS_CONSUME_CLR_D_GPTMP_TODAY.EXG_VERSION ;
insert into EMS_CONSUME_CLR_D_GPTMP_TODAY (CMD_TYPE,EMS_NO,IMG_NO,EXG_NO,EXG_VERSION,QTY,DEC_CM_QTY,MODIFY_MARK,ETL_MARK) select CMD_TYPE,EMS_NO,IMG_NO,EXG_NO,EXG_VERSION,QTY,DEC_CM_QTY,MODIFY_MARK,ETL_MARK from EMS_CONSUME_CLR_D_INC_EXT;
delete from EMS_CONSUME_CLR_D_GPTMP;
\timing
