\echo ------------------EMS_CLR_TMP----------------
select now();
\timing
delete from EMS_CLR_TMP_GPTMP;
insert into EMS_CLR_TMP_GPTMP (CMD_TYPE,EMS_NO, G_TYPE, G_NO) select CMD_TYPE,EMS_NO, G_TYPE, G_NO from EMS_CLR_TMP_INC_EXT;
delete from EMS_CLR_TMP_GPTMP_TODAY using EMS_CLR_TMP_GPTMP where EMS_CLR_TMP_GPTMP.EMS_NO=EMS_CLR_TMP_GPTMP_TODAY.EMS_NO AND EMS_CLR_TMP_GPTMP.G_TYPE=EMS_CLR_TMP_GPTMP_TODAY.G_TYPE AND EMS_CLR_TMP_GPTMP.G_NO=EMS_CLR_TMP_GPTMP_TODAY.G_NO ;
insert into EMS_CLR_TMP_GPTMP_TODAY (CMD_TYPE,EMS_NO,G_TYPE,G_NO,CM_QTY,CM_AMOUNT,CLR_INC_QTY,CLR_CUT_QTY,USD_PRICE,OTHER_PRICE,NOTE) select CMD_TYPE,EMS_NO,G_TYPE,G_NO,CM_QTY,CM_AMOUNT,CLR_INC_QTY,CLR_CUT_QTY,USD_PRICE,OTHER_PRICE,NOTE from EMS_CLR_TMP_INC_EXT;
delete from EMS_CLR_TMP_GPTMP;
\timing
