\echo ------------------EMS_ENP_JOU----------------
select now();
\timing
delete from EMS_ENP_JOU_GPTMP;
insert into EMS_ENP_JOU_GPTMP (CMD_TYPE,ENP_ID, ENP_SEQ, ENP_NO) select CMD_TYPE,ENP_ID, ENP_SEQ, ENP_NO from EMS_ENP_JOU_INC_EXT;
delete from EMS_ENP_JOU_GPTMP_TODAY using EMS_ENP_JOU_GPTMP where EMS_ENP_JOU_GPTMP.ENP_ID=EMS_ENP_JOU_GPTMP_TODAY.ENP_ID AND EMS_ENP_JOU_GPTMP.ENP_SEQ=EMS_ENP_JOU_GPTMP_TODAY.ENP_SEQ AND EMS_ENP_JOU_GPTMP.ENP_NO=EMS_ENP_JOU_GPTMP_TODAY.ENP_NO ;
insert into EMS_ENP_JOU_GPTMP_TODAY (CMD_TYPE,ENP_ID,ENP_SEQ,ENP_NO,PROCESS_DATE,PROCESS_MARK,PROCESS_STATUS,NOTE_1) select CMD_TYPE,ENP_ID,ENP_SEQ,ENP_NO,PROCESS_DATE,PROCESS_MARK,PROCESS_STATUS,NOTE_1 from EMS_ENP_JOU_INC_EXT;
delete from EMS_ENP_JOU_GPTMP;
\timing
