\echo ------------------ENTRY_PROC----------------
select now();
\timing
delete from ENTRY_PROC_GPTMP;
insert into ENTRY_PROC_GPTMP (CMD_TYPE,ENTRY_ID, DECL_PORT) select CMD_TYPE,ENTRY_ID, DECL_PORT from ENTRY_PROC_INC_EXT;
delete from ENTRY_PROC_GPTMP_TODAY using ENTRY_PROC_GPTMP where ENTRY_PROC_GPTMP.ENTRY_ID=ENTRY_PROC_GPTMP_TODAY.ENTRY_ID AND ENTRY_PROC_GPTMP.DECL_PORT=ENTRY_PROC_GPTMP_TODAY.DECL_PORT ;
insert into ENTRY_PROC_GPTMP_TODAY (CMD_TYPE,ENTRY_ID,I_E_FLAG,D_DATE,DECL_PORT,SPECIAL_DECLARE,ACE_TIME,ACE_RESULT,QUICK_PASS_MODE,CTR_TIME,CTR_RESULT,CHANNEL,CHANNEL_TIME,CHANNEL_ER,REC_TIME,REC_ER,CHK_TIME,CHK_RESULT,CHK_ER,TAX_PRINT_TIME,REL_TIME,REL_RESULT,REL_ER,GOODS_REL_TIME,GOODS_REL_ER,RTX_TIME,RTX_ER,PREL_TIME,PREL_RESULT,PREL_ER,RECTR_TIME,RECTR_ER,LAST_STEP,LAST_STEP_TIME,RSV_1,RSV_2,RSV_3,RSV_4,RSV_TIME_1,RSV_TIME_2) select CMD_TYPE,ENTRY_ID,I_E_FLAG,D_DATE,DECL_PORT,SPECIAL_DECLARE,ACE_TIME,ACE_RESULT,QUICK_PASS_MODE,CTR_TIME,CTR_RESULT,CHANNEL,CHANNEL_TIME,CHANNEL_ER,REC_TIME,REC_ER,CHK_TIME,CHK_RESULT,CHK_ER,TAX_PRINT_TIME,REL_TIME,REL_RESULT,REL_ER,GOODS_REL_TIME,GOODS_REL_ER,RTX_TIME,RTX_ER,PREL_TIME,PREL_RESULT,PREL_ER,RECTR_TIME,RECTR_ER,LAST_STEP,LAST_STEP_TIME,RSV_1,RSV_2,RSV_3,RSV_4,RSV_TIME_1,RSV_TIME_2 from ENTRY_PROC_INC_EXT;
delete from ENTRY_PROC_GPTMP;
\timing
