\echo ------------------ENTRY_AUTOREL_ERR_LIST----------------
select now();
\timing
delete from ENTRY_AUTOREL_ERR_LIST_GPTMP;
insert into ENTRY_AUTOREL_ERR_LIST_GPTMP (CMD_TYPE,ENTRY_ID) select CMD_TYPE,ENTRY_ID from ENTRY_AUTOREL_ERR_LIST_INC_EXT;
delete from ENTRY_AUTOREL_ERR_LIST_GPTMP_TODAY using ENTRY_AUTOREL_ERR_LIST_GPTMP where ENTRY_AUTOREL_ERR_LIST_GPTMP.ENTRY_ID=ENTRY_AUTOREL_ERR_LIST_GPTMP_TODAY.ENTRY_ID ;
insert into ENTRY_AUTOREL_ERR_LIST_GPTMP_TODAY (CMD_TYPE,ENTRY_ID,I_E_FLAG,DECL_PORT,TRADE_CO,TRADE_NAME,AGENT_CODE,AGENT_NAME,CREATE_DATE,DESCRIPTION) select CMD_TYPE,ENTRY_ID,I_E_FLAG,DECL_PORT,TRADE_CO,TRADE_NAME,AGENT_CODE,AGENT_NAME,CREATE_DATE,DESCRIPTION from ENTRY_AUTOREL_ERR_LIST_INC_EXT;
delete from ENTRY_AUTOREL_ERR_LIST_GPTMP;
\timing
