\echo ------------------ENTRY_GPM_RTX_PRINTLOG----------------
select now();
\timing
delete from ENTRY_GPM_RTX_PRINTLOG_GPTMP;
insert into ENTRY_GPM_RTX_PRINTLOG_GPTMP (CMD_TYPE,ENTRY_ID, PRINT_TYPE, PRINT_DATE) select CMD_TYPE,ENTRY_ID, PRINT_TYPE, PRINT_DATE from ENTRY_GPM_RTX_PRINTLOG_INC_EXT;
delete from ENTRY_GPM_RTX_PRINTLOG_GPTMP_TODAY using ENTRY_GPM_RTX_PRINTLOG_GPTMP where ENTRY_GPM_RTX_PRINTLOG_GPTMP.ENTRY_ID=ENTRY_GPM_RTX_PRINTLOG_GPTMP_TODAY.ENTRY_ID AND ENTRY_GPM_RTX_PRINTLOG_GPTMP.PRINT_TYPE=ENTRY_GPM_RTX_PRINTLOG_GPTMP_TODAY.PRINT_TYPE AND ENTRY_GPM_RTX_PRINTLOG_GPTMP.PRINT_DATE=ENTRY_GPM_RTX_PRINTLOG_GPTMP_TODAY.PRINT_DATE ;
insert into ENTRY_GPM_RTX_PRINTLOG_GPTMP_TODAY (CMD_TYPE,ENTRY_ID,PRINT_TYPE,PRINT_DATE,PRINT_ER) select CMD_TYPE,ENTRY_ID,PRINT_TYPE,PRINT_DATE,PRINT_ER from ENTRY_GPM_RTX_PRINTLOG_INC_EXT;
delete from ENTRY_GPM_RTX_PRINTLOG_GPTMP;
\timing
