\echo ------------------ENTRY_CERTIFICATE----------------
select now();
\timing
delete from ENTRY_CERTIFICATE_GPTMP;
insert into ENTRY_CERTIFICATE_GPTMP (CMD_TYPE,ENTRY_ID, DOCU_CODE, CERT_CODE) select CMD_TYPE,ENTRY_ID, DOCU_CODE, CERT_CODE from ENTRY_CERTIFICATE_INC_EXT;
delete from ENTRY_CERTIFICATE_GPTMP_TODAY using ENTRY_CERTIFICATE_GPTMP where ENTRY_CERTIFICATE_GPTMP.ENTRY_ID=ENTRY_CERTIFICATE_GPTMP_TODAY.ENTRY_ID AND ENTRY_CERTIFICATE_GPTMP.DOCU_CODE=ENTRY_CERTIFICATE_GPTMP_TODAY.DOCU_CODE AND ENTRY_CERTIFICATE_GPTMP.CERT_CODE=ENTRY_CERTIFICATE_GPTMP_TODAY.CERT_CODE ;
insert into ENTRY_CERTIFICATE_GPTMP_TODAY (CMD_TYPE,ENTRY_ID,DOCU_CODE,CERT_CODE) select CMD_TYPE,ENTRY_ID,DOCU_CODE,CERT_CODE from ENTRY_CERTIFICATE_INC_EXT;
delete from ENTRY_CERTIFICATE_GPTMP;
\timing
