\echo ------------------ENTRY_CONTAINER----------------
select now();
\timing
delete from ENTRY_CONTAINER_GPTMP;
insert into ENTRY_CONTAINER_GPTMP (CMD_TYPE,ENTRY_ID, CONTAINER_ID) select CMD_TYPE,ENTRY_ID, CONTAINER_ID from ENTRY_CONTAINER_INC_EXT;
delete from ENTRY_CONTAINER_GPTMP_TODAY using ENTRY_CONTAINER_GPTMP where ENTRY_CONTAINER_GPTMP.ENTRY_ID=ENTRY_CONTAINER_GPTMP_TODAY.ENTRY_ID AND ENTRY_CONTAINER_GPTMP.CONTAINER_ID=ENTRY_CONTAINER_GPTMP_TODAY.CONTAINER_ID ;
insert into ENTRY_CONTAINER_GPTMP_TODAY (CMD_TYPE,ENTRY_ID,CONTAINER_ID,CONTAINER_WT) select CMD_TYPE,ENTRY_ID,CONTAINER_ID,CONTAINER_WT from ENTRY_CONTAINER_INC_EXT;
delete from ENTRY_CONTAINER_GPTMP;
\timing
