\echo ------------------ENTRY_PROC_LOG----------------
select now();
\timing
delete from ENTRY_PROC_LOG_GPTMP;
insert into ENTRY_PROC_LOG_GPTMP (CMD_TYPE,ENTRY_ID, OP_TIME, OP_STEP) select CMD_TYPE,ENTRY_ID, OP_TIME, OP_STEP from ENTRY_PROC_LOG_INC_EXT;
delete from ENTRY_PROC_LOG_GPTMP_TODAY using ENTRY_PROC_LOG_GPTMP where ENTRY_PROC_LOG_GPTMP.ENTRY_ID=ENTRY_PROC_LOG_GPTMP_TODAY.ENTRY_ID AND ENTRY_PROC_LOG_GPTMP.OP_TIME=ENTRY_PROC_LOG_GPTMP_TODAY.OP_TIME AND ENTRY_PROC_LOG_GPTMP.OP_STEP=ENTRY_PROC_LOG_GPTMP_TODAY.OP_STEP ;
insert into ENTRY_PROC_LOG_GPTMP_TODAY (CMD_TYPE,ENTRY_ID,OP_TIME,OP_STEP,OP_TYPE,OP_SOURCE,OP_DESCRIPTION) select CMD_TYPE,ENTRY_ID,OP_TIME,OP_STEP,OP_TYPE,OP_SOURCE,OP_DESCRIPTION from ENTRY_PROC_LOG_INC_EXT;
delete from ENTRY_PROC_LOG_GPTMP;
\timing
