\echo ------------------ENTRY_MODI_LOG----------------
select now();
\timing
delete from ENTRY_MODI_LOG_GPTMP;
insert into ENTRY_MODI_LOG_GPTMP (CMD_TYPE,ENTRY_ID, OP_TIME, MODI_TYPE, ITEM_NAME) select CMD_TYPE,ENTRY_ID, OP_TIME, MODI_TYPE, ITEM_NAME from ENTRY_MODI_LOG_INC_EXT;
delete from ENTRY_MODI_LOG_GPTMP_TODAY using ENTRY_MODI_LOG_GPTMP where ENTRY_MODI_LOG_GPTMP.ENTRY_ID=ENTRY_MODI_LOG_GPTMP_TODAY.ENTRY_ID AND ENTRY_MODI_LOG_GPTMP.OP_TIME=ENTRY_MODI_LOG_GPTMP_TODAY.OP_TIME AND ENTRY_MODI_LOG_GPTMP.MODI_TYPE=ENTRY_MODI_LOG_GPTMP_TODAY.MODI_TYPE AND ENTRY_MODI_LOG_GPTMP.ITEM_NAME=ENTRY_MODI_LOG_GPTMP_TODAY.ITEM_NAME ;
insert into ENTRY_MODI_LOG_GPTMP_TODAY (CMD_TYPE,ENTRY_ID,OP_TIME,MODI_TYPE,ITEM_NAME,ITEM_SOURCE,NOTES,ITEM_CURRENT) select CMD_TYPE,ENTRY_ID,OP_TIME,MODI_TYPE,ITEM_NAME,ITEM_SOURCE,NOTES,ITEM_CURRENT from ENTRY_MODI_LOG_INC_EXT;
delete from ENTRY_MODI_LOG_GPTMP;
\timing
