\echo ------------------ENTRY_QUERY----------------
select now();
\timing
delete from ENTRY_QUERY_GPTMP;
insert into ENTRY_QUERY_GPTMP (CMD_TYPE,ENTRY_ID, G_NO) select CMD_TYPE,ENTRY_ID, G_NO from ENTRY_QUERY_INC_EXT;
delete from ENTRY_QUERY_GPTMP_TODAY using ENTRY_QUERY_GPTMP where ENTRY_QUERY_GPTMP.ENTRY_ID=ENTRY_QUERY_GPTMP_TODAY.ENTRY_ID AND ENTRY_QUERY_GPTMP.G_NO=ENTRY_QUERY_GPTMP_TODAY.G_NO ;
insert into ENTRY_QUERY_GPTMP_TODAY (CMD_TYPE,ENTRY_ID,G_NO,I_E_FLAG,I_E_PORT,I_E_DATE,D_DATE,DESTINATION_PORT,TRAF_NAME,VOYAGE_NO,TRAF_MODE,TRADE_CO,TRADE_NAME,DISTRICT_CODE,OWNER_CODE,OWNER_NAME,AGENT_CODE,AGENT_NAME,BILL_NO,TRADE_COUNTRY,TRADE_MODE,CUT_MODE,TRANS_MODE,FEE_MARK,FEE_CURR,FEE_RATE,INSUR_MARK,INSUR_CURR,INSUR_RATE,OTHER_MARK,OTHER_CURR,OTHER_RATE,PACK_NO,GROSS_WT,NET_WT,WRAP_TYPE,MANUAL_NO,LICENSE_NO,APPR_NO,NOTE_S,DECL_PORT,SPECIAL_FLAG,CODE_TS,G_NAME,G_MODEL,ORIGIN_COUNTRY,TRADE_CURR,EXCHANGE_RATE,DECL_PRICE,DECL_TOTAL,DUTY_MODE,G_QTY,G_UNIT,QTY_1,UNIT_1,QTY_2,UNIT_2,TRADE_TOTAL,RMB_PRICE,USD_PRICE,DUTY_VALUE,DUTY_TYPE,REAL_DUTY,DUTY_CUT) select CMD_TYPE,ENTRY_ID,G_NO,I_E_FLAG,I_E_PORT,I_E_DATE,D_DATE,DESTINATION_PORT,TRAF_NAME,VOYAGE_NO,TRAF_MODE,TRADE_CO,TRADE_NAME,DISTRICT_CODE,OWNER_CODE,OWNER_NAME,AGENT_CODE,AGENT_NAME,BILL_NO,TRADE_COUNTRY,TRADE_MODE,CUT_MODE,TRANS_MODE,FEE_MARK,FEE_CURR,FEE_RATE,INSUR_MARK,INSUR_CURR,INSUR_RATE,OTHER_MARK,OTHER_CURR,OTHER_RATE,PACK_NO,GROSS_WT,NET_WT,WRAP_TYPE,MANUAL_NO,LICENSE_NO,APPR_NO,NOTE_S,DECL_PORT,SPECIAL_FLAG,CODE_TS,G_NAME,G_MODEL,ORIGIN_COUNTRY,TRADE_CURR,EXCHANGE_RATE,DECL_PRICE,DECL_TOTAL,DUTY_MODE,G_QTY,G_UNIT,QTY_1,UNIT_1,QTY_2,UNIT_2,TRADE_TOTAL,RMB_PRICE,USD_PRICE,DUTY_VALUE,DUTY_TYPE,REAL_DUTY,DUTY_CUT from ENTRY_QUERY_INC_EXT;
delete from ENTRY_QUERY_GPTMP;
\timing
