\echo ------------------ENTRY_WORKFLOW----------------
select now();
\timing
delete from ENTRY_WORKFLOW_GPTMP;
insert into ENTRY_WORKFLOW_GPTMP (CMD_TYPE,ENTRY_ID, STEP_ID, CREATE_DATE) select CMD_TYPE,ENTRY_ID, STEP_ID, CREATE_DATE from ENTRY_WORKFLOW_INC_EXT;
delete from ENTRY_WORKFLOW_GPTMP_TODAY using ENTRY_WORKFLOW_GPTMP where ENTRY_WORKFLOW_GPTMP.ENTRY_ID=ENTRY_WORKFLOW_GPTMP_TODAY.ENTRY_ID AND ENTRY_WORKFLOW_GPTMP.STEP_ID=ENTRY_WORKFLOW_GPTMP_TODAY.STEP_ID AND ENTRY_WORKFLOW_GPTMP.CREATE_DATE=ENTRY_WORKFLOW_GPTMP_TODAY.CREATE_DATE ;
insert into ENTRY_WORKFLOW_GPTMP_TODAY (CMD_TYPE,ENTRY_ID,STEP_ID,CREATE_DATE,PROC_POS,STATUS_CODE,PROC_ER,PROC_RESULT,PREV_POS,PREV_ER,RECHK_MARK,RECHK_COMM) select CMD_TYPE,ENTRY_ID,STEP_ID,CREATE_DATE,PROC_POS,STATUS_CODE,PROC_ER,PROC_RESULT,PREV_POS,PREV_ER,RECHK_MARK,RECHK_COMM from ENTRY_WORKFLOW_INC_EXT;
delete from ENTRY_WORKFLOW_GPTMP;
\timing
