\echo ------------------ERR_LOG----------------
select now();
\timing
delete from ERR_LOG_GPTMP;
insert into ERR_LOG_GPTMP (CMD_TYPE,ENTRY_ID, CREATE_DATE) select CMD_TYPE,ENTRY_ID, CREATE_DATE from ERR_LOG_INC_EXT;
delete from ERR_LOG_GPTMP_TODAY using ERR_LOG_GPTMP where ERR_LOG_GPTMP.ENTRY_ID=ERR_LOG_GPTMP_TODAY.ENTRY_ID AND ERR_LOG_GPTMP.CREATE_DATE=ERR_LOG_GPTMP_TODAY.CREATE_DATE ;
insert into ERR_LOG_GPTMP_TODAY (CMD_TYPE,ENTRY_ID,CREATE_DATE,SOURCE,DESCRIPTION) select CMD_TYPE,ENTRY_ID,CREATE_DATE,SOURCE,DESCRIPTION from ERR_LOG_INC_EXT;
delete from ERR_LOG_GPTMP;
\timing
