\echo ------------------EX_APPL_CLOSE----------------
select now();
\timing
delete from EX_APPL_CLOSE_GPTMP;
insert into EX_APPL_CLOSE_GPTMP (CMD_TYPE,MANUAL_NO, CONTR_ITEM) select CMD_TYPE,MANUAL_NO, CONTR_ITEM from EX_APPL_CLOSE_INC_EXT;
delete from EX_APPL_CLOSE_GPTMP_TODAY using EX_APPL_CLOSE_GPTMP where EX_APPL_CLOSE_GPTMP.MANUAL_NO=EX_APPL_CLOSE_GPTMP_TODAY.MANUAL_NO AND EX_APPL_CLOSE_GPTMP.CONTR_ITEM=EX_APPL_CLOSE_GPTMP_TODAY.CONTR_ITEM ;
insert into EX_APPL_CLOSE_GPTMP_TODAY (CMD_TYPE,MANUAL_NO,CONTR_ITEM,CODE_TS,G_NAME,G_MODEL,FACT_QTY,T_IN_QTY,T_EX_QTY,REMAIN_QTY,PROC_MODE,CORR_MANUAL_NO) select CMD_TYPE,MANUAL_NO,CONTR_ITEM,CODE_TS,G_NAME,G_MODEL,FACT_QTY,T_IN_QTY,T_EX_QTY,REMAIN_QTY,PROC_MODE,CORR_MANUAL_NO from EX_APPL_CLOSE_INC_EXT;
delete from EX_APPL_CLOSE_GPTMP;
\timing
