\echo ------------------EX_ARRIVAL_ERR_CHK----------------
select now();
\timing
delete from EX_ARRIVAL_ERR_CHK_GPTMP;
insert into EX_ARRIVAL_ERR_CHK_GPTMP (CMD_TYPE,ENTRY_ID, CHK_DATE) select CMD_TYPE,ENTRY_ID, CHK_DATE from EX_ARRIVAL_ERR_CHK_INC_EXT;
delete from EX_ARRIVAL_ERR_CHK_GPTMP_TODAY using EX_ARRIVAL_ERR_CHK_GPTMP where EX_ARRIVAL_ERR_CHK_GPTMP.ENTRY_ID=EX_ARRIVAL_ERR_CHK_GPTMP_TODAY.ENTRY_ID AND EX_ARRIVAL_ERR_CHK_GPTMP.CHK_DATE=EX_ARRIVAL_ERR_CHK_GPTMP_TODAY.CHK_DATE ;
insert into EX_ARRIVAL_ERR_CHK_GPTMP_TODAY (CMD_TYPE,ENTRY_ID,CHK_FLAG,CHK_DATE,CHK_ER) select CMD_TYPE,ENTRY_ID,CHK_FLAG,CHK_DATE,CHK_ER from EX_ARRIVAL_ERR_CHK_INC_EXT;
delete from EX_ARRIVAL_ERR_CHK_GPTMP;
\timing
