\echo ------------------EX_ARRIVAL_CONTA----------------
select now();
\timing
delete from EX_ARRIVAL_CONTA_GPTMP;
insert into EX_ARRIVAL_CONTA_GPTMP (CMD_TYPE,CONTA_ID, BILL_NO, REC_NO) select CMD_TYPE,CONTA_ID, BILL_NO, REC_NO from EX_ARRIVAL_CONTA_INC_EXT;
delete from EX_ARRIVAL_CONTA_GPTMP_TODAY using EX_ARRIVAL_CONTA_GPTMP where EX_ARRIVAL_CONTA_GPTMP.CONTA_ID=EX_ARRIVAL_CONTA_GPTMP_TODAY.CONTA_ID AND EX_ARRIVAL_CONTA_GPTMP.BILL_NO=EX_ARRIVAL_CONTA_GPTMP_TODAY.BILL_NO AND EX_ARRIVAL_CONTA_GPTMP.REC_NO=EX_ARRIVAL_CONTA_GPTMP_TODAY.REC_NO ;
insert into EX_ARRIVAL_CONTA_GPTMP_TODAY (CMD_TYPE,CONTA_ID,BILL_NO,REC_NO,RECV_DATE,CONTA_MODEL,CONTA_STATUS,SEAL_NO,TARE_WEIGHT,TOTAL_CARGO,TOTAL_MEASURE,TOTAL_PACK_NO,TOTAL_WEIGHT,IN_PORT_FLAG,IN_PORT_ADDR,IN_PORT_DATE,D_PORT_CODE,PLACE,ENTRY_ID,CHK_DATE,CHK_ER) select CMD_TYPE,CONTA_ID,BILL_NO,REC_NO,RECV_DATE,CONTA_MODEL,CONTA_STATUS,SEAL_NO,TARE_WEIGHT,TOTAL_CARGO,TOTAL_MEASURE,TOTAL_PACK_NO,TOTAL_WEIGHT,IN_PORT_FLAG,IN_PORT_ADDR,IN_PORT_DATE,D_PORT_CODE,PLACE,ENTRY_ID,CHK_DATE,CHK_ER from EX_ARRIVAL_CONTA_INC_EXT;
delete from EX_ARRIVAL_CONTA_GPTMP;
\timing
