\echo ------------------EX_ARRIVAL_SHIP----------------
select now();
\timing
delete from EX_ARRIVAL_SHIP_GPTMP;
insert into EX_ARRIVAL_SHIP_GPTMP (CMD_TYPE,VOYAGE_NO, SHIP_NAME_EN, CUSTOMS_CODE, SHIP_ID) select CMD_TYPE,VOYAGE_NO, SHIP_NAME_EN, CUSTOMS_CODE, SHIP_ID from EX_ARRIVAL_SHIP_INC_EXT;
delete from EX_ARRIVAL_SHIP_GPTMP_TODAY using EX_ARRIVAL_SHIP_GPTMP where EX_ARRIVAL_SHIP_GPTMP.VOYAGE_NO=EX_ARRIVAL_SHIP_GPTMP_TODAY.VOYAGE_NO AND EX_ARRIVAL_SHIP_GPTMP.SHIP_NAME_EN=EX_ARRIVAL_SHIP_GPTMP_TODAY.SHIP_NAME_EN AND EX_ARRIVAL_SHIP_GPTMP.CUSTOMS_CODE=EX_ARRIVAL_SHIP_GPTMP_TODAY.CUSTOMS_CODE AND EX_ARRIVAL_SHIP_GPTMP.SHIP_ID=EX_ARRIVAL_SHIP_GPTMP_TODAY.SHIP_ID ;
insert into EX_ARRIVAL_SHIP_GPTMP_TODAY (CMD_TYPE,VOYAGE_NO,SHIP_NAME_EN,CUSTOMS_CODE,SHIP_ID,I_E_DATE,TRAF_MODE,REC_NO) select CMD_TYPE,VOYAGE_NO,SHIP_NAME_EN,CUSTOMS_CODE,SHIP_ID,I_E_DATE,TRAF_MODE,REC_NO from EX_ARRIVAL_SHIP_INC_EXT;
delete from EX_ARRIVAL_SHIP_GPTMP;
\timing
