\echo ------------------EX_DECL_CUR_LIST----------------
select now();
\timing
delete from EX_DECL_CUR_LIST_GPTMP;
insert into EX_DECL_CUR_LIST_GPTMP (CMD_TYPE,PRE_NO, RECORD_NUMBER, G_NO) select CMD_TYPE,PRE_NO, RECORD_NUMBER, G_NO from EX_DECL_CUR_LIST_INC_EXT;
delete from EX_DECL_CUR_LIST_GPTMP_TODAY using EX_DECL_CUR_LIST_GPTMP where EX_DECL_CUR_LIST_GPTMP.PRE_NO=EX_DECL_CUR_LIST_GPTMP_TODAY.PRE_NO AND EX_DECL_CUR_LIST_GPTMP.RECORD_NUMBER=EX_DECL_CUR_LIST_GPTMP_TODAY.RECORD_NUMBER AND EX_DECL_CUR_LIST_GPTMP.G_NO=EX_DECL_CUR_LIST_GPTMP_TODAY.G_NO ;
insert into EX_DECL_CUR_LIST_GPTMP_TODAY (CMD_TYPE,PRE_NO,TURN_NO,BATCH_NO,RECORD_NUMBER,G_NO,CODE_TS,G_NAME,PACK_TYPE,GOODS_PIECE,GOODS_AMOUNT,GOODS_UNIT,GOODS_WEIGHT,GOODS_PRICE,GOODS_CURR,GOODS_CHK_MARK,SEND_PORT,RECV_PORT) select CMD_TYPE,PRE_NO,TURN_NO,BATCH_NO,RECORD_NUMBER,G_NO,CODE_TS,G_NAME,PACK_TYPE,GOODS_PIECE,GOODS_AMOUNT,GOODS_UNIT,GOODS_WEIGHT,GOODS_PRICE,GOODS_CURR,GOODS_CHK_MARK,SEND_PORT,RECV_PORT from EX_DECL_CUR_LIST_INC_EXT;
delete from EX_DECL_CUR_LIST_GPTMP;
\timing
