\echo ------------------EX_ELE_HEAD----------------
select now();
\timing
delete from EX_ELE_HEAD_GPTMP;
insert into EX_ELE_HEAD_GPTMP (CMD_TYPE,LICENSE_NO) select CMD_TYPE,LICENSE_NO from EX_ELE_HEAD_INC_EXT;
delete from EX_ELE_HEAD_GPTMP_TODAY using EX_ELE_HEAD_GPTMP where EX_ELE_HEAD_GPTMP.LICENSE_NO=EX_ELE_HEAD_GPTMP_TODAY.LICENSE_NO ;
insert into EX_ELE_HEAD_GPTMP_TODAY (CMD_TYPE,LICENSE_NO,TRADE_CODE,TRADE_NAME,OWNER_NAME,LIC_ALLOW_DATE,LIC_SIGN_DATE,TRADE_COUNTRY,ORIGIN_COUNTRY,CONTR_NO,IE_PORT1,IE_PORT2,IE_PORT3,TRADE_MODE,TRADE_MODE_NAME,CODE_T_S,G_NAME,UNIT_NAME,LIC_QTY_TOTAL,LIC_USD_PRICE_TOTAL,LIC_MARK,SEND_DATE,RECEIVE_DATE,DELETE_DATE,LIC_ITEMS_NO,CHECK_MARK,SECURITY_ID,REUSE1,REUSE2,NOTE_S) select CMD_TYPE,LICENSE_NO,TRADE_CODE,TRADE_NAME,OWNER_NAME,LIC_ALLOW_DATE,LIC_SIGN_DATE,TRADE_COUNTRY,ORIGIN_COUNTRY,CONTR_NO,IE_PORT1,IE_PORT2,IE_PORT3,TRADE_MODE,TRADE_MODE_NAME,CODE_T_S,G_NAME,UNIT_NAME,LIC_QTY_TOTAL,LIC_USD_PRICE_TOTAL,LIC_MARK,SEND_DATE,RECEIVE_DATE,DELETE_DATE,LIC_ITEMS_NO,CHECK_MARK,SECURITY_ID,REUSE1,REUSE2,NOTE_S from EX_ELE_HEAD_INC_EXT;
delete from EX_ELE_HEAD_GPTMP;
\timing
