\echo ------------------EX_ELE_LIST----------------
select now();
\timing
delete from EX_ELE_LIST_GPTMP;
insert into EX_ELE_LIST_GPTMP (CMD_TYPE,LICENSE_NO, L_G_NO) select CMD_TYPE,LICENSE_NO, L_G_NO from EX_ELE_LIST_INC_EXT;
delete from EX_ELE_LIST_GPTMP_TODAY using EX_ELE_LIST_GPTMP where EX_ELE_LIST_GPTMP.LICENSE_NO=EX_ELE_LIST_GPTMP_TODAY.LICENSE_NO AND EX_ELE_LIST_GPTMP.L_G_NO=EX_ELE_LIST_GPTMP_TODAY.L_G_NO ;
insert into EX_ELE_LIST_GPTMP_TODAY (CMD_TYPE,LICENSE_NO,L_G_NO,G_MODEL,LIC_QTY,LIC_USD_PRICE) select CMD_TYPE,LICENSE_NO,L_G_NO,G_MODEL,LIC_QTY,LIC_USD_PRICE from EX_ELE_LIST_INC_EXT;
delete from EX_ELE_LIST_GPTMP;
\timing
