\echo ------------------EX_TRN_CONTA_ENTRY_CHK----------------
select now();
\timing
delete from EX_TRN_CONTA_ENTRY_CHK_GPTMP;
insert into EX_TRN_CONTA_ENTRY_CHK_GPTMP (CMD_TYPE,ENTRY_ID, ARRIVE_NO, CONTA_ID) select CMD_TYPE,ENTRY_ID, ARRIVE_NO, CONTA_ID from EX_TRN_CONTA_ENTRY_CHK_INC_EXT;
delete from EX_TRN_CONTA_ENTRY_CHK_GPTMP_TODAY using EX_TRN_CONTA_ENTRY_CHK_GPTMP where EX_TRN_CONTA_ENTRY_CHK_GPTMP.ENTRY_ID=EX_TRN_CONTA_ENTRY_CHK_GPTMP_TODAY.ENTRY_ID AND EX_TRN_CONTA_ENTRY_CHK_GPTMP.ARRIVE_NO=EX_TRN_CONTA_ENTRY_CHK_GPTMP_TODAY.ARRIVE_NO AND EX_TRN_CONTA_ENTRY_CHK_GPTMP.CONTA_ID=EX_TRN_CONTA_ENTRY_CHK_GPTMP_TODAY.CONTA_ID ;
insert into EX_TRN_CONTA_ENTRY_CHK_GPTMP_TODAY (CMD_TYPE,ENTRY_ID,ARRIVE_NO,CONTA_ID,CHK_ER,CHK_DATE) select CMD_TYPE,ENTRY_ID,ARRIVE_NO,CONTA_ID,CHK_ER,CHK_DATE from EX_TRN_CONTA_ENTRY_CHK_INC_EXT;
delete from EX_TRN_CONTA_ENTRY_CHK_GPTMP;
\timing
