\echo ------------------EX_TRN_CONTA_ENTRY_ARV----------------
select now();
\timing
delete from EX_TRN_CONTA_ENTRY_ARV_GPTMP;
insert into EX_TRN_CONTA_ENTRY_ARV_GPTMP (CMD_TYPE,ENTRY_ID, CONTA_ID) select CMD_TYPE,ENTRY_ID, CONTA_ID from EX_TRN_CONTA_ENTRY_ARV_INC_EXT;
delete from EX_TRN_CONTA_ENTRY_ARV_GPTMP_TODAY using EX_TRN_CONTA_ENTRY_ARV_GPTMP where EX_TRN_CONTA_ENTRY_ARV_GPTMP.ENTRY_ID=EX_TRN_CONTA_ENTRY_ARV_GPTMP_TODAY.ENTRY_ID AND EX_TRN_CONTA_ENTRY_ARV_GPTMP.CONTA_ID=EX_TRN_CONTA_ENTRY_ARV_GPTMP_TODAY.CONTA_ID ;
insert into EX_TRN_CONTA_ENTRY_ARV_GPTMP_TODAY (CMD_TYPE,ENTRY_ID,CONTA_ID,CUSTOMS_CODE,TRAF_MODE,TRAF_NAME,VOYAGE_NO,BILL_NO,PACK_NO,GROSS_WT,ARV_FLAG,TRN_MODE) select CMD_TYPE,ENTRY_ID,CONTA_ID,CUSTOMS_CODE,TRAF_MODE,TRAF_NAME,VOYAGE_NO,BILL_NO,PACK_NO,GROSS_WT,ARV_FLAG,TRN_MODE from EX_TRN_CONTA_ENTRY_ARV_INC_EXT;
delete from EX_TRN_CONTA_ENTRY_ARV_GPTMP;
\timing
