\echo ------------------EXAM_CONTA_END_LOG----------------
select now();
\timing
delete from EXAM_CONTA_END_LOG_GPTMP;
insert into EXAM_CONTA_END_LOG_GPTMP (CMD_TYPE,EXAM_REC_ID, END_TIME) select CMD_TYPE,EXAM_REC_ID, END_TIME from EXAM_CONTA_END_LOG_INC_EXT;
delete from EXAM_CONTA_END_LOG_GPTMP_TODAY using EXAM_CONTA_END_LOG_GPTMP where EXAM_CONTA_END_LOG_GPTMP.EXAM_REC_ID=EXAM_CONTA_END_LOG_GPTMP_TODAY.EXAM_REC_ID AND EXAM_CONTA_END_LOG_GPTMP.END_TIME=EXAM_CONTA_END_LOG_GPTMP_TODAY.END_TIME ;
insert into EXAM_CONTA_END_LOG_GPTMP_TODAY (CMD_TYPE,EXAM_REC_ID,RSK_NO,END_ER,END_TIME,END_REASON) select CMD_TYPE,EXAM_REC_ID,RSK_NO,END_ER,END_TIME,END_REASON from EXAM_CONTA_END_LOG_INC_EXT;
delete from EXAM_CONTA_END_LOG_GPTMP;
\timing
