\echo ------------------EXC_EXAM----------------
select now();
\timing
delete from EXC_EXAM_GPTMP;
insert into EXC_EXAM_GPTMP (CMD_TYPE,HXD_NO) select CMD_TYPE,HXD_NO from EXC_EXAM_INC_EXT;
delete from EXC_EXAM_GPTMP_TODAY using EXC_EXAM_GPTMP where EXC_EXAM_GPTMP.HXD_NO=EXC_EXAM_GPTMP_TODAY.HXD_NO ;
insert into EXC_EXAM_GPTMP_TODAY (CMD_TYPE,SEQ_NO,HXD_NO,ENTRY_ID,CUS_CODE,DECL_DATE,IMPLE_DATE,IMPLE_ER,RET_DATE,EXC_MARK,DELE_DATE,DELE_ER,DATA_SIGN) select CMD_TYPE,SEQ_NO,HXD_NO,ENTRY_ID,CUS_CODE,DECL_DATE,IMPLE_DATE,IMPLE_ER,RET_DATE,EXC_MARK,DELE_DATE,DELE_ER,DATA_SIGN from EXC_EXAM_INC_EXT;
delete from EXC_EXAM_GPTMP;
\timing
