\echo ------------------EXC_ELE----------------
select now();
\timing
delete from EXC_ELE_GPTMP;
insert into EXC_ELE_GPTMP (CMD_TYPE,HXD_NO) select CMD_TYPE,HXD_NO from EXC_ELE_INC_EXT;
delete from EXC_ELE_GPTMP_TODAY using EXC_ELE_GPTMP where EXC_ELE_GPTMP.HXD_NO=EXC_ELE_GPTMP_TODAY.HXD_NO ;
insert into EXC_ELE_GPTMP_TODAY (CMD_TYPE,SEQ_NO,HXD_NO,WGJ_CODE,ENT_CODE,TRADE_CO,WGJ_STATE,REASON_CODE,PROVIDE_DATE,PROVIDE_NAME,OPER_DATE,OPER_NAME,HG_STATE,HG_OPER_DATE,HG_OPER_NAME,LOSS_STATE,LOSS_DATE,LOSS_NAME,PORT_CODE,PORT_DATE,PORT_NAME,DEAL_STATE,DEAL_DATE,DEAL_NAME,PAPER_BILL,RECV_DATE,CANCEL_DATE,ENTRY_ID,CUS_CODE,DECL_DATE,CHK_MARK,DATA_SIGN) select CMD_TYPE,SEQ_NO,HXD_NO,WGJ_CODE,ENT_CODE,TRADE_CO,WGJ_STATE,REASON_CODE,PROVIDE_DATE,PROVIDE_NAME,OPER_DATE,OPER_NAME,HG_STATE,HG_OPER_DATE,HG_OPER_NAME,LOSS_STATE,LOSS_DATE,LOSS_NAME,PORT_CODE,PORT_DATE,PORT_NAME,DEAL_STATE,DEAL_DATE,DEAL_NAME,PAPER_BILL,RECV_DATE,CANCEL_DATE,ENTRY_ID,CUS_CODE,DECL_DATE,CHK_MARK,DATA_SIGN from EXC_ELE_INC_EXT;
delete from EXC_ELE_GPTMP;
\timing
