\echo ------------------FCB_CONTA_MODI----------------
select now();
\timing
delete from FCB_CONTA_MODI_GPTMP;
insert into FCB_CONTA_MODI_GPTMP (CMD_TYPE,FCB_ID, CONTA_ID) select CMD_TYPE,FCB_ID, CONTA_ID from FCB_CONTA_MODI_INC_EXT;
delete from FCB_CONTA_MODI_GPTMP_TODAY using FCB_CONTA_MODI_GPTMP where FCB_CONTA_MODI_GPTMP.FCB_ID=FCB_CONTA_MODI_GPTMP_TODAY.FCB_ID AND FCB_CONTA_MODI_GPTMP.CONTA_ID=FCB_CONTA_MODI_GPTMP_TODAY.CONTA_ID ;
insert into FCB_CONTA_MODI_GPTMP_TODAY (CMD_TYPE,FCB_ID,CONTA_ID,ESEAL_ID,CONTA_MODEL,CONTA_TYPE,DE_CONSOLIDATOR,CONTA_WT,NOTE) select CMD_TYPE,FCB_ID,CONTA_ID,ESEAL_ID,CONTA_MODEL,CONTA_TYPE,DE_CONSOLIDATOR,CONTA_WT,NOTE from FCB_CONTA_MODI_INC_EXT;
delete from FCB_CONTA_MODI_GPTMP;
\timing
