\echo ------------------FCB_WORKFLOW----------------
select now();
\timing
delete from FCB_WORKFLOW_GPTMP;
insert into FCB_WORKFLOW_GPTMP (CMD_TYPE,FCB_ID, STEP_ID, CREATE_DATE) select CMD_TYPE,FCB_ID, STEP_ID, CREATE_DATE from FCB_WORKFLOW_INC_EXT;
delete from FCB_WORKFLOW_GPTMP_TODAY using FCB_WORKFLOW_GPTMP where FCB_WORKFLOW_GPTMP.FCB_ID=FCB_WORKFLOW_GPTMP_TODAY.FCB_ID AND FCB_WORKFLOW_GPTMP.STEP_ID=FCB_WORKFLOW_GPTMP_TODAY.STEP_ID AND FCB_WORKFLOW_GPTMP.CREATE_DATE=FCB_WORKFLOW_GPTMP_TODAY.CREATE_DATE ;
insert into FCB_WORKFLOW_GPTMP_TODAY (CMD_TYPE,FCB_ID,STEP_ID,CREATE_DATE,PROC_ER,PROC_RESULT,RECHK_COMM,PORT_CUS,MAIN_CUS) select CMD_TYPE,FCB_ID,STEP_ID,CREATE_DATE,PROC_ER,PROC_RESULT,RECHK_COMM,PORT_CUS,MAIN_CUS from FCB_WORKFLOW_INC_EXT;
delete from FCB_WORKFLOW_GPTMP;
\timing
