\echo ------------------FCB_RSK----------------
select now();
\timing
delete from FCB_RSK_GPTMP;
insert into FCB_RSK_GPTMP (CMD_TYPE,FCB_ID, CUSTOMS_CODE) select CMD_TYPE,FCB_ID, CUSTOMS_CODE from FCB_RSK_INC_EXT;
delete from FCB_RSK_GPTMP_TODAY using FCB_RSK_GPTMP where FCB_RSK_GPTMP.FCB_ID=FCB_RSK_GPTMP_TODAY.FCB_ID AND FCB_RSK_GPTMP.CUSTOMS_CODE=FCB_RSK_GPTMP_TODAY.CUSTOMS_CODE ;
insert into FCB_RSK_GPTMP_TODAY (CMD_TYPE,FCB_ID,CUSTOMS_CODE,INPUT_ER,INPUT_TIME,REQUIRE,RELEASE_ER,RELEASE_TIME,RESULT) select CMD_TYPE,FCB_ID,CUSTOMS_CODE,INPUT_ER,INPUT_TIME,REQUIRE,RELEASE_ER,RELEASE_TIME,RESULT from FCB_RSK_INC_EXT;
delete from FCB_RSK_GPTMP;
\timing
