\echo ------------------FORFEIT_FORM----------------
select now();
\timing
delete from FORFEIT_FORM_GPTMP;
insert into FORFEIT_FORM_GPTMP (CMD_TYPE,FMS_ID) select CMD_TYPE,FMS_ID from FORFEIT_FORM_INC_EXT;
delete from FORFEIT_FORM_GPTMP_TODAY using FORFEIT_FORM_GPTMP where FORFEIT_FORM_GPTMP.FMS_ID=FORFEIT_FORM_GPTMP_TODAY.FMS_ID ;
insert into FORFEIT_FORM_GPTMP_TODAY (CMD_TYPE,FMS_ID,DEPARTMENT,DEPARTMENT_NOTE,DISTRICT_CODE,PAYER_NAME,FMS_CLASS,FMS_AMOUNT,OPER_CODE,LAW_ID,TAX_FLAG,LIMIT_DAY,FMS_MODE,CREATE_DATE,CUSTOMS_CODE,SECTION_ID,GROUP_ID) select CMD_TYPE,FMS_ID,DEPARTMENT,DEPARTMENT_NOTE,DISTRICT_CODE,PAYER_NAME,FMS_CLASS,FMS_AMOUNT,OPER_CODE,LAW_ID,TAX_FLAG,LIMIT_DAY,FMS_MODE,CREATE_DATE,CUSTOMS_CODE,SECTION_ID,GROUP_ID from FORFEIT_FORM_INC_EXT;
delete from FORFEIT_FORM_GPTMP;
\timing
