\echo ------------------FORM_CHK----------------
select now();
\timing
delete from FORM_CHK_GPTMP;
insert into FORM_CHK_GPTMP (CMD_TYPE,FORM_ID) select CMD_TYPE,FORM_ID from FORM_CHK_INC_EXT;
delete from FORM_CHK_GPTMP_TODAY using FORM_CHK_GPTMP where FORM_CHK_GPTMP.FORM_ID=FORM_CHK_GPTMP_TODAY.FORM_ID ;
insert into FORM_CHK_GPTMP_TODAY (CMD_TYPE,FORM_ID,FORM_FLAG,TRANS_NO,SHIP_ID,VOYAGE_NO,BILL_NO,BILL_NO_ORI,TRAF_MODE,I_E_FLAG,DECL_PORT,I_E_PORT,I_E_DATE,D_DATE,TRADE_NAME,AGENT_NAME,OWNER_NAME,CONTR_NO,LICENSE_NO,APPR_NO,MANUAL_NO,PACK_NO,GROSS_WT,GEN_DATE,GEN_ER,CHK_MARK,CHK_DATE,CHK_ER,COUNTRY_CODE,NOTE_S,CHK_ER_TRN,CHK_MARK_TRN,PACK_NO_TRN,GROSS_WT_TRN,CHK_DATE_TRN,NOTE_S_RTX,CHK_MARK_TMP,MFT_TYPE,NOTE_S_MFT) select CMD_TYPE,FORM_ID,FORM_FLAG,TRANS_NO,SHIP_ID,VOYAGE_NO,BILL_NO,BILL_NO_ORI,TRAF_MODE,I_E_FLAG,DECL_PORT,I_E_PORT,I_E_DATE,D_DATE,TRADE_NAME,AGENT_NAME,OWNER_NAME,CONTR_NO,LICENSE_NO,APPR_NO,MANUAL_NO,PACK_NO,GROSS_WT,GEN_DATE,GEN_ER,CHK_MARK,CHK_DATE,CHK_ER,COUNTRY_CODE,NOTE_S,CHK_ER_TRN,CHK_MARK_TRN,PACK_NO_TRN,GROSS_WT_TRN,CHK_DATE_TRN,NOTE_S_RTX,CHK_MARK_TMP,MFT_TYPE,NOTE_S_MFT from FORM_CHK_INC_EXT;
delete from FORM_CHK_GPTMP;
\timing
