\echo ------------------GUARANTEE_LIST----------------
select now();
\timing
delete from GUARANTEE_LIST_GPTMP;
insert into GUARANTEE_LIST_GPTMP (CMD_TYPE,ENTRY_ID, G_NO, TAX_TYPE) select CMD_TYPE,ENTRY_ID, G_NO, TAX_TYPE from GUARANTEE_LIST_INC_EXT;
delete from GUARANTEE_LIST_GPTMP_TODAY using GUARANTEE_LIST_GPTMP where GUARANTEE_LIST_GPTMP.ENTRY_ID=GUARANTEE_LIST_GPTMP_TODAY.ENTRY_ID AND GUARANTEE_LIST_GPTMP.G_NO=GUARANTEE_LIST_GPTMP_TODAY.G_NO AND GUARANTEE_LIST_GPTMP.TAX_TYPE=GUARANTEE_LIST_GPTMP_TODAY.TAX_TYPE ;
insert into GUARANTEE_LIST_GPTMP_TODAY (CMD_TYPE,ENTRY_ID,G_NO,CODE_TS,GRT_ACCOUNT,GRT_RATE,APP_REASON,TAX_TYPE,ACTION_NO,COMPANY_NAME_CN,COMPANY_NAME_EN) select CMD_TYPE,ENTRY_ID,G_NO,CODE_TS,GRT_ACCOUNT,GRT_RATE,APP_REASON,TAX_TYPE,ACTION_NO,COMPANY_NAME_CN,COMPANY_NAME_EN from GUARANTEE_LIST_INC_EXT;
delete from GUARANTEE_LIST_GPTMP;
\timing
