\echo ------------------H2000_SMS_SEND----------------
select now();
\timing
delete from H2000_SMS_SEND_GPTMP;
insert into H2000_SMS_SEND_GPTMP (CMD_TYPE,SEQUENCE_NO, FORM_ID, SYSTEM_ID, POS_ID, OP_TIME, PHONE_NO) select CMD_TYPE,SEQUENCE_NO, FORM_ID, SYSTEM_ID, POS_ID, OP_TIME, PHONE_NO from H2000_SMS_SEND_INC_EXT;
delete from H2000_SMS_SEND_GPTMP_TODAY using H2000_SMS_SEND_GPTMP where H2000_SMS_SEND_GPTMP.SEQUENCE_NO=H2000_SMS_SEND_GPTMP_TODAY.SEQUENCE_NO AND H2000_SMS_SEND_GPTMP.FORM_ID=H2000_SMS_SEND_GPTMP_TODAY.FORM_ID AND H2000_SMS_SEND_GPTMP.SYSTEM_ID=H2000_SMS_SEND_GPTMP_TODAY.SYSTEM_ID AND H2000_SMS_SEND_GPTMP.POS_ID=H2000_SMS_SEND_GPTMP_TODAY.POS_ID AND H2000_SMS_SEND_GPTMP.OP_TIME=H2000_SMS_SEND_GPTMP_TODAY.OP_TIME AND H2000_SMS_SEND_GPTMP.PHONE_NO=H2000_SMS_SEND_GPTMP_TODAY.PHONE_NO ;
insert into H2000_SMS_SEND_GPTMP_TODAY (CMD_TYPE,SEQUENCE_NO,FORM_ID,CUSTOMS_CODE,SYSTEM_ID,POS_ID,OP_TIME,PHONE_NO,MSG_TEXT,PROC_FLAG,NOTES) select CMD_TYPE,SEQUENCE_NO,FORM_ID,CUSTOMS_CODE,SYSTEM_ID,POS_ID,OP_TIME,PHONE_NO,MSG_TEXT,PROC_FLAG,NOTES from H2000_SMS_SEND_INC_EXT;
delete from H2000_SMS_SEND_GPTMP;
\timing
