\echo ------------------HIS_TRN_ESEAL_REL----------------
select now();
\timing
delete from HIS_TRN_ESEAL_REL_GPTMP;
insert into HIS_TRN_ESEAL_REL_GPTMP (CMD_TYPE,ESEAL_ID, MODI_TIME) select CMD_TYPE,ESEAL_ID, MODI_TIME from HIS_TRN_ESEAL_REL_INC_EXT;
delete from HIS_TRN_ESEAL_REL_GPTMP_TODAY using HIS_TRN_ESEAL_REL_GPTMP where HIS_TRN_ESEAL_REL_GPTMP.ESEAL_ID=HIS_TRN_ESEAL_REL_GPTMP_TODAY.ESEAL_ID AND HIS_TRN_ESEAL_REL_GPTMP.MODI_TIME=HIS_TRN_ESEAL_REL_GPTMP_TODAY.MODI_TIME ;
insert into HIS_TRN_ESEAL_REL_GPTMP_TODAY (CMD_TYPE,ESEAL_ID,CUSTOMS_CODE,CO_REG_NO,CO_NAME,VE_CUSTOMS_NO,VE_NAME,INPUT_OP_ID,INPUT_DATE,VALID_FLAG,MODI_OP_ID,MODI_TIME) select CMD_TYPE,ESEAL_ID,CUSTOMS_CODE,CO_REG_NO,CO_NAME,VE_CUSTOMS_NO,VE_NAME,INPUT_OP_ID,INPUT_DATE,VALID_FLAG,MODI_OP_ID,MODI_TIME from HIS_TRN_ESEAL_REL_INC_EXT;
delete from HIS_TRN_ESEAL_REL_GPTMP;
\timing
