\echo ------------------IM_COP_RATE----------------
select now();
\timing
delete from IM_COP_RATE_GPTMP;
insert into IM_COP_RATE_GPTMP (CMD_TYPE,TRADE_CO, CHKSTDATE, CHKENDDATE) select CMD_TYPE,TRADE_CO, CHKSTDATE, CHKENDDATE from IM_COP_RATE_INC_EXT;
delete from IM_COP_RATE_GPTMP_TODAY using IM_COP_RATE_GPTMP where IM_COP_RATE_GPTMP.TRADE_CO=IM_COP_RATE_GPTMP_TODAY.TRADE_CO AND IM_COP_RATE_GPTMP.CHKSTDATE=IM_COP_RATE_GPTMP_TODAY.CHKSTDATE AND IM_COP_RATE_GPTMP.CHKENDDATE=IM_COP_RATE_GPTMP_TODAY.CHKENDDATE ;
insert into IM_COP_RATE_GPTMP_TODAY (CMD_TYPE,TRADE_CO,CHKSTDATE,CHKENDDATE,CORCORPNAME,CHKRATE,RECV_DATE) select CMD_TYPE,TRADE_CO,CHKSTDATE,CHKENDDATE,CORCORPNAME,CHKRATE,RECV_DATE from IM_COP_RATE_INC_EXT;
delete from IM_COP_RATE_GPTMP;
\timing
