\echo ------------------IM_CONTRACT_LIST----------------
select now();
\timing
delete from IM_CONTRACT_LIST_GPTMP;
insert into IM_CONTRACT_LIST_GPTMP (CMD_TYPE,MANUAL_NO, CONTR_ITEM) select CMD_TYPE,MANUAL_NO, CONTR_ITEM from IM_CONTRACT_LIST_INC_EXT;
delete from IM_CONTRACT_LIST_GPTMP_TODAY using IM_CONTRACT_LIST_GPTMP where IM_CONTRACT_LIST_GPTMP.MANUAL_NO=IM_CONTRACT_LIST_GPTMP_TODAY.MANUAL_NO AND IM_CONTRACT_LIST_GPTMP.CONTR_ITEM=IM_CONTRACT_LIST_GPTMP_TODAY.CONTR_ITEM ;
insert into IM_CONTRACT_LIST_GPTMP_TODAY (CMD_TYPE,MANUAL_NO,CONTR_ITEM,CODE_TS,CLASS_MARK,G_NAME,G_MODEL,ORIGIN_COUNTRY,DUTY_MODE,DUTY_RATIO,LOCAL_CONTR,APPR_AMT,FACT_AMT,UNIT_PRICE,APPR_QTY,FACT_QTY,TRANSFER_QTY,UNIT_1,IN_COUNT,IM_MODE,CONSUME_NOTE) select CMD_TYPE,MANUAL_NO,CONTR_ITEM,CODE_TS,CLASS_MARK,G_NAME,G_MODEL,ORIGIN_COUNTRY,DUTY_MODE,DUTY_RATIO,LOCAL_CONTR,APPR_AMT,FACT_AMT,UNIT_PRICE,APPR_QTY,FACT_QTY,TRANSFER_QTY,UNIT_1,IN_COUNT,IM_MODE,CONSUME_NOTE from IM_CONTRACT_LIST_INC_EXT;
delete from IM_CONTRACT_LIST_GPTMP;
\timing
