\echo ------------------IM_TRANS_HIS_LIST_REL----------------
select now();
\timing
delete from IM_TRANS_HIS_LIST_REL_GPTMP;
insert into IM_TRANS_HIS_LIST_REL_GPTMP (CMD_TYPE,PRE_NO, RECORD_NUMBER) select CMD_TYPE,PRE_NO, RECORD_NUMBER from IM_TRANS_HIS_LIST_REL_INC_EXT;
delete from IM_TRANS_HIS_LIST_REL_GPTMP_TODAY using IM_TRANS_HIS_LIST_REL_GPTMP where IM_TRANS_HIS_LIST_REL_GPTMP.PRE_NO=IM_TRANS_HIS_LIST_REL_GPTMP_TODAY.PRE_NO AND IM_TRANS_HIS_LIST_REL_GPTMP.RECORD_NUMBER=IM_TRANS_HIS_LIST_REL_GPTMP_TODAY.RECORD_NUMBER ;
insert into IM_TRANS_HIS_LIST_REL_GPTMP_TODAY (CMD_TYPE,PRE_NO,RECORD_NUMBER,TRAF_MODE,SHIP_ID,SHIP_NAME_EN,VOYAGE_NO,BILL_NO,I_E_DATE,ENTRY_NO,BIND_FLAG,REC_FLAG,PACK_NO,GROSS_WT,GOODS_COUNT,CONTA_C,OWNER_NAME,EX_CHECK_FLAG,EX_CHECK_TIME,REAL_PACK_NO,REAL_GROSS_WT,NOTE) select CMD_TYPE,PRE_NO,RECORD_NUMBER,TRAF_MODE,SHIP_ID,SHIP_NAME_EN,VOYAGE_NO,BILL_NO,I_E_DATE,ENTRY_NO,BIND_FLAG,REC_FLAG,PACK_NO,GROSS_WT,GOODS_COUNT,CONTA_C,OWNER_NAME,EX_CHECK_FLAG,EX_CHECK_TIME,REAL_PACK_NO,REAL_GROSS_WT,NOTE from IM_TRANS_HIS_LIST_REL_INC_EXT;
delete from IM_TRANS_HIS_LIST_REL_GPTMP;
\timing
