\echo ------------------IMA_APPL_CLOSE----------------
select now();
\timing
delete from IMA_APPL_CLOSE_GPTMP;
insert into IMA_APPL_CLOSE_GPTMP (CMD_TYPE,MANUAL_NO, CONTR_ITEM) select CMD_TYPE,MANUAL_NO, CONTR_ITEM from IMA_APPL_CLOSE_INC_EXT;
delete from IMA_APPL_CLOSE_GPTMP_TODAY using IMA_APPL_CLOSE_GPTMP where IMA_APPL_CLOSE_GPTMP.MANUAL_NO=IMA_APPL_CLOSE_GPTMP_TODAY.MANUAL_NO AND IMA_APPL_CLOSE_GPTMP.CONTR_ITEM=IMA_APPL_CLOSE_GPTMP_TODAY.CONTR_ITEM ;
insert into IMA_APPL_CLOSE_GPTMP_TODAY (CMD_TYPE,MANUAL_NO,CONTR_ITEM,CODE_TS,G_NAME,G_MODEL,G_QTY,G_UNIT,DECL_PRICE,G_AMT,PROC_MODE,BOOK_NO) select CMD_TYPE,MANUAL_NO,CONTR_ITEM,CODE_TS,G_NAME,G_MODEL,G_QTY,G_UNIT,DECL_PRICE,G_AMT,PROC_MODE,BOOK_NO from IMA_APPL_CLOSE_INC_EXT;
delete from IMA_APPL_CLOSE_GPTMP;
\timing
