\echo ------------------INCOME_INFO----------------
select now();
\timing
delete from INCOME_INFO_GPTMP;
insert into INCOME_INFO_GPTMP (CMD_TYPE,RPTNO) select CMD_TYPE,RPTNO from INCOME_INFO_INC_EXT;
delete from INCOME_INFO_GPTMP_TODAY using INCOME_INFO_GPTMP where INCOME_INFO_GPTMP.RPTNO=INCOME_INFO_GPTMP_TODAY.RPTNO ;
insert into INCOME_INFO_GPTMP_TODAY (CMD_TYPE,RPTNO,CORCORPNAME,TRADE_CO,CSTSETCODE,TXCCY,TXAMT,INCHARGECCY,INCHARGEAMT,OUTCHARGECCY,OUTCHARGEAMT,OPPNAME,COUNTRYCODE,RCVTYPE,ISWRITEOFF,RECV_DATE) select CMD_TYPE,RPTNO,CORCORPNAME,TRADE_CO,CSTSETCODE,TXCCY,TXAMT,INCHARGECCY,INCHARGEAMT,OUTCHARGECCY,OUTCHARGEAMT,OPPNAME,COUNTRYCODE,RCVTYPE,ISWRITEOFF,RECV_DATE from INCOME_INFO_INC_EXT;
delete from INCOME_INFO_GPTMP;
\timing
