\echo ------------------JOB_PARAMETER----------------
select now();
\timing
delete from JOB_PARAMETER_GPTMP;
insert into JOB_PARAMETER_GPTMP (CMD_TYPE,JOB_NAME, PARAMETER_NAME, PARAMETER_VALUE) select CMD_TYPE,JOB_NAME, PARAMETER_NAME, PARAMETER_VALUE from JOB_PARAMETER_INC_EXT;
delete from JOB_PARAMETER_GPTMP_TODAY using JOB_PARAMETER_GPTMP where JOB_PARAMETER_GPTMP.JOB_NAME=JOB_PARAMETER_GPTMP_TODAY.JOB_NAME AND JOB_PARAMETER_GPTMP.PARAMETER_NAME=JOB_PARAMETER_GPTMP_TODAY.PARAMETER_NAME AND JOB_PARAMETER_GPTMP.PARAMETER_VALUE=JOB_PARAMETER_GPTMP_TODAY.PARAMETER_VALUE ;
insert into JOB_PARAMETER_GPTMP_TODAY (CMD_TYPE,JOB_NAME,PARAMETER_NAME,PARAMETER_VALUE,UPDATE_TIME,NOTES) select CMD_TYPE,JOB_NAME,PARAMETER_NAME,PARAMETER_VALUE,UPDATE_TIME,NOTES from JOB_PARAMETER_INC_EXT;
delete from JOB_PARAMETER_GPTMP;
\timing
