\echo ------------------MANIFEST_HEAD_XMS_LOG----------------
select now();
\timing
delete from MANIFEST_HEAD_XMS_LOG_GPTMP;
insert into MANIFEST_HEAD_XMS_LOG_GPTMP (CMD_TYPE,VOYAGE_NO, SHIP_ID, CUSTOMS_CODE, I_E_DATE, TRAF_MODE, I_E_FLAG) select CMD_TYPE,VOYAGE_NO, SHIP_ID, CUSTOMS_CODE, I_E_DATE, TRAF_MODE, I_E_FLAG from MANIFEST_HEAD_XMS_LOG_INC_EXT;
delete from MANIFEST_HEAD_XMS_LOG_GPTMP_TODAY using MANIFEST_HEAD_XMS_LOG_GPTMP where MANIFEST_HEAD_XMS_LOG_GPTMP.VOYAGE_NO=MANIFEST_HEAD_XMS_LOG_GPTMP_TODAY.VOYAGE_NO AND MANIFEST_HEAD_XMS_LOG_GPTMP.SHIP_ID=MANIFEST_HEAD_XMS_LOG_GPTMP_TODAY.SHIP_ID AND MANIFEST_HEAD_XMS_LOG_GPTMP.CUSTOMS_CODE=MANIFEST_HEAD_XMS_LOG_GPTMP_TODAY.CUSTOMS_CODE AND MANIFEST_HEAD_XMS_LOG_GPTMP.I_E_DATE=MANIFEST_HEAD_XMS_LOG_GPTMP_TODAY.I_E_DATE AND MANIFEST_HEAD_XMS_LOG_GPTMP.TRAF_MODE=MANIFEST_HEAD_XMS_LOG_GPTMP_TODAY.TRAF_MODE AND MANIFEST_HEAD_XMS_LOG_GPTMP.I_E_FLAG=MANIFEST_HEAD_XMS_LOG_GPTMP_TODAY.I_E_FLAG ;
insert into MANIFEST_HEAD_XMS_LOG_GPTMP_TODAY (CMD_TYPE,I_E_FLAG,CUSTOMS_CODE,TRAF_MODE,VOYAGE_NO,SHIP_ID,I_E_DATE,CREATE_DATE) select CMD_TYPE,I_E_FLAG,CUSTOMS_CODE,TRAF_MODE,VOYAGE_NO,SHIP_ID,I_E_DATE,CREATE_DATE from MANIFEST_HEAD_XMS_LOG_INC_EXT;
delete from MANIFEST_HEAD_XMS_LOG_GPTMP;
\timing
