\echo ------------------MANIFEST_LIST_CONTA----------------
select now();
\timing
delete from MANIFEST_LIST_CONTA_GPTMP;
insert into MANIFEST_LIST_CONTA_GPTMP (CMD_TYPE,VOYAGE_NO, CUSTOMS_CODE, TRAF_MODE, I_E_FLAG, BILL_NO, CONTA_ID, SHIP_ID) select CMD_TYPE,VOYAGE_NO, CUSTOMS_CODE, TRAF_MODE, I_E_FLAG, BILL_NO, CONTA_ID, SHIP_ID from MANIFEST_LIST_CONTA_INC_EXT;
delete from MANIFEST_LIST_CONTA_GPTMP_TODAY using MANIFEST_LIST_CONTA_GPTMP where MANIFEST_LIST_CONTA_GPTMP.VOYAGE_NO=MANIFEST_LIST_CONTA_GPTMP_TODAY.VOYAGE_NO AND MANIFEST_LIST_CONTA_GPTMP.CUSTOMS_CODE=MANIFEST_LIST_CONTA_GPTMP_TODAY.CUSTOMS_CODE AND MANIFEST_LIST_CONTA_GPTMP.TRAF_MODE=MANIFEST_LIST_CONTA_GPTMP_TODAY.TRAF_MODE AND MANIFEST_LIST_CONTA_GPTMP.I_E_FLAG=MANIFEST_LIST_CONTA_GPTMP_TODAY.I_E_FLAG AND MANIFEST_LIST_CONTA_GPTMP.BILL_NO=MANIFEST_LIST_CONTA_GPTMP_TODAY.BILL_NO AND MANIFEST_LIST_CONTA_GPTMP.CONTA_ID=MANIFEST_LIST_CONTA_GPTMP_TODAY.CONTA_ID AND MANIFEST_LIST_CONTA_GPTMP.SHIP_ID=MANIFEST_LIST_CONTA_GPTMP_TODAY.SHIP_ID ;
insert into MANIFEST_LIST_CONTA_GPTMP_TODAY (CMD_TYPE,I_E_FLAG,CUSTOMS_CODE,TRAF_MODE,VOYAGE_NO,BILL_NO,CONTA_ID,SHIP_ID,RSK_ER,RSK_DATE,RSK_CODE,RSK_LEVEL,RSK_RESULT,RELEASE_ER,RELEASE_DATE) select CMD_TYPE,I_E_FLAG,CUSTOMS_CODE,TRAF_MODE,VOYAGE_NO,BILL_NO,CONTA_ID,SHIP_ID,RSK_ER,RSK_DATE,RSK_CODE,RSK_LEVEL,RSK_RESULT,RELEASE_ER,RELEASE_DATE from MANIFEST_LIST_CONTA_INC_EXT;
delete from MANIFEST_LIST_CONTA_GPTMP;
\timing
