\echo ------------------MNLBAK_SERVICE_LIST----------------
select now();
\timing
delete from MNLBAK_SERVICE_LIST_GPTMP;
insert into MNLBAK_SERVICE_LIST_GPTMP (CMD_TYPE,MANUAL_NO, F_NO) select CMD_TYPE,MANUAL_NO, F_NO from MNLBAK_SERVICE_LIST_INC_EXT;
delete from MNLBAK_SERVICE_LIST_GPTMP_TODAY using MNLBAK_SERVICE_LIST_GPTMP where MNLBAK_SERVICE_LIST_GPTMP.MANUAL_NO=MNLBAK_SERVICE_LIST_GPTMP_TODAY.MANUAL_NO AND MNLBAK_SERVICE_LIST_GPTMP.F_NO=MNLBAK_SERVICE_LIST_GPTMP_TODAY.F_NO ;
insert into MNLBAK_SERVICE_LIST_GPTMP_TODAY (CMD_TYPE,MANUAL_NO,F_NO,FEE_TYPE,FEE_RATE,G_NO,G_NAME,FEE_AMT,FEE_CURR,FEE_RMB,SERVICE_FEE) select CMD_TYPE,MANUAL_NO,F_NO,FEE_TYPE,FEE_RATE,G_NO,G_NAME,FEE_AMT,FEE_CURR,FEE_RMB,SERVICE_FEE from MNLBAK_SERVICE_LIST_INC_EXT;
delete from MNLBAK_SERVICE_LIST_GPTMP;
\timing
