\echo ------------------MNLBAK_FASCICLE_HEAD----------------
select now();
\timing
delete from MNLBAK_FASCICLE_HEAD_GPTMP;
insert into MNLBAK_FASCICLE_HEAD_GPTMP (CMD_TYPE,FASCICLE_NO) select CMD_TYPE,FASCICLE_NO from MNLBAK_FASCICLE_HEAD_INC_EXT;
delete from MNLBAK_FASCICLE_HEAD_GPTMP_TODAY using MNLBAK_FASCICLE_HEAD_GPTMP where MNLBAK_FASCICLE_HEAD_GPTMP.FASCICLE_NO=MNLBAK_FASCICLE_HEAD_GPTMP_TODAY.FASCICLE_NO ;
insert into MNLBAK_FASCICLE_HEAD_GPTMP_TODAY (CMD_TYPE,MANUAL_NO,FASCICLE_NO,PRE_FASCICLE_NO,I_E_PORT,TYPE_ER,TYPE_DATE,LIMIT_DATE,TRADE_CO,CHK_ER,RECHK_ER,PR_DATE,FASCICLE_TYPE,EXE_MARK,CONTR_IN,CONTR_OUT,IN_PNT,EX_PNT,SUPV_MARK,NOTE_S) select CMD_TYPE,MANUAL_NO,FASCICLE_NO,PRE_FASCICLE_NO,I_E_PORT,TYPE_ER,TYPE_DATE,LIMIT_DATE,TRADE_CO,CHK_ER,RECHK_ER,PR_DATE,FASCICLE_TYPE,EXE_MARK,CONTR_IN,CONTR_OUT,IN_PNT,EX_PNT,SUPV_MARK,NOTE_S from MNLBAK_FASCICLE_HEAD_INC_EXT;
delete from MNLBAK_FASCICLE_HEAD_GPTMP;
\timing
