\echo ------------------MNLBAK_EX_CONTRACT_LIST----------------
select now();
\timing
delete from MNLBAK_EX_CONTRACT_LIST_GPTMP;
insert into MNLBAK_EX_CONTRACT_LIST_GPTMP (CMD_TYPE,MANUAL_NO, CONTR_ITEM) select CMD_TYPE,MANUAL_NO, CONTR_ITEM from MNLBAK_EX_CONTRACT_LIST_INC_EXT;
delete from MNLBAK_EX_CONTRACT_LIST_GPTMP_TODAY using MNLBAK_EX_CONTRACT_LIST_GPTMP where MNLBAK_EX_CONTRACT_LIST_GPTMP.MANUAL_NO=MNLBAK_EX_CONTRACT_LIST_GPTMP_TODAY.MANUAL_NO AND MNLBAK_EX_CONTRACT_LIST_GPTMP.CONTR_ITEM=MNLBAK_EX_CONTRACT_LIST_GPTMP_TODAY.CONTR_ITEM ;
insert into MNLBAK_EX_CONTRACT_LIST_GPTMP_TODAY (CMD_TYPE,MANUAL_NO,CONTR_ITEM,CODE_TS,CLASS_MARK,G_NAME,G_MODEL,ORIGIN_COUNTRY,DUTY_MODE,DUTY_RATIO,LOCAL_CONTR,APPR_AMT,FACT_AMT,UNIT_PRICE,APPR_QTY,FACT_QTY,TRANSFER_QTY,UNIT_1,IN_COUNT,WORK_PAY,CURR_WORK,CONSUME_NOTE) select CMD_TYPE,MANUAL_NO,CONTR_ITEM,CODE_TS,CLASS_MARK,G_NAME,G_MODEL,ORIGIN_COUNTRY,DUTY_MODE,DUTY_RATIO,LOCAL_CONTR,APPR_AMT,FACT_AMT,UNIT_PRICE,APPR_QTY,FACT_QTY,TRANSFER_QTY,UNIT_1,IN_COUNT,WORK_PAY,CURR_WORK,CONSUME_NOTE from MNLBAK_EX_CONTRACT_LIST_INC_EXT;
delete from MNLBAK_EX_CONTRACT_LIST_GPTMP;
\timing
