\echo ------------------MNLBAK_SERVICE_FEE----------------
select now();
\timing
delete from MNLBAK_SERVICE_FEE_GPTMP;
insert into MNLBAK_SERVICE_FEE_GPTMP (CMD_TYPE,MANUAL_NO) select CMD_TYPE,MANUAL_NO from MNLBAK_SERVICE_FEE_INC_EXT;
delete from MNLBAK_SERVICE_FEE_GPTMP_TODAY using MNLBAK_SERVICE_FEE_GPTMP where MNLBAK_SERVICE_FEE_GPTMP.MANUAL_NO=MNLBAK_SERVICE_FEE_GPTMP_TODAY.MANUAL_NO ;
insert into MNLBAK_SERVICE_FEE_GPTMP_TODAY (CMD_TYPE,MANUAL_NO,DUE_FEE_AMT,PAY_FEE_AMT,CREATE_DATE,RETURN_ID,RETURN_FLAG,REMAIN_AMT) select CMD_TYPE,MANUAL_NO,DUE_FEE_AMT,PAY_FEE_AMT,CREATE_DATE,RETURN_ID,RETURN_FLAG,REMAIN_AMT from MNLBAK_SERVICE_FEE_INC_EXT;
delete from MNLBAK_SERVICE_FEE_GPTMP;
\timing
