\echo ------------------NORSK_TRADE_MODE----------------
select now();
\timing
delete from NORSK_TRADE_MODE_GPTMP;
insert into NORSK_TRADE_MODE_GPTMP (CMD_TYPE,CCTS_CODE) select CMD_TYPE,CCTS_CODE from NORSK_TRADE_MODE_INC_EXT;
delete from NORSK_TRADE_MODE_GPTMP_TODAY using NORSK_TRADE_MODE_GPTMP where NORSK_TRADE_MODE_GPTMP.CCTS_CODE=NORSK_TRADE_MODE_GPTMP_TODAY.CCTS_CODE ;
insert into NORSK_TRADE_MODE_GPTMP_TODAY (CMD_TYPE,CCTS_CODE,TRADE_MODE,TRADE_NAME,BEGIN_DATE,END_DATE,CUSTOMS_CODE,INPUT_ID,AUTHORIZE_ID,OP_TIME,I_E_FLAG) select CMD_TYPE,CCTS_CODE,TRADE_MODE,TRADE_NAME,BEGIN_DATE,END_DATE,CUSTOMS_CODE,INPUT_ID,AUTHORIZE_ID,OP_TIME,I_E_FLAG from NORSK_TRADE_MODE_INC_EXT;
delete from NORSK_TRADE_MODE_GPTMP;
\timing
