\echo ------------------NORSK_TRADE_MODE_BAK----------------
select now();
\timing
delete from NORSK_TRADE_MODE_BAK_GPTMP;
insert into NORSK_TRADE_MODE_BAK_GPTMP (CMD_TYPE,CCTS_CODE, OP_BAK_TIME) select CMD_TYPE,CCTS_CODE, OP_BAK_TIME from NORSK_TRADE_MODE_BAK_INC_EXT;
delete from NORSK_TRADE_MODE_BAK_GPTMP_TODAY using NORSK_TRADE_MODE_BAK_GPTMP where NORSK_TRADE_MODE_BAK_GPTMP.CCTS_CODE=NORSK_TRADE_MODE_BAK_GPTMP_TODAY.CCTS_CODE AND NORSK_TRADE_MODE_BAK_GPTMP.OP_BAK_TIME=NORSK_TRADE_MODE_BAK_GPTMP_TODAY.OP_BAK_TIME ;
insert into NORSK_TRADE_MODE_BAK_GPTMP_TODAY (CMD_TYPE,CCTS_CODE,TRADE_MODE,TRADE_NAME,BEGIN_DATE,END_DATE,CUSTOMS_CODE,INPUT_ID,AUTHORIZE_ID,OP_TIME,I_E_FLAG,OP_BAK_TYPE,OP_BAK_CUSTOMS,OP_BAK_MAN,OP_BAK_TIME) select CMD_TYPE,CCTS_CODE,TRADE_MODE,TRADE_NAME,BEGIN_DATE,END_DATE,CUSTOMS_CODE,INPUT_ID,AUTHORIZE_ID,OP_TIME,I_E_FLAG,OP_BAK_TYPE,OP_BAK_CUSTOMS,OP_BAK_MAN,OP_BAK_TIME from NORSK_TRADE_MODE_BAK_INC_EXT;
delete from NORSK_TRADE_MODE_BAK_GPTMP;
\timing
