\echo ------------------NORSK_COMPANY----------------
select now();
\timing
delete from NORSK_COMPANY_GPTMP;
insert into NORSK_COMPANY_GPTMP (CMD_TYPE,CCTS_CODE) select CMD_TYPE,CCTS_CODE from NORSK_COMPANY_INC_EXT;
delete from NORSK_COMPANY_GPTMP_TODAY using NORSK_COMPANY_GPTMP where NORSK_COMPANY_GPTMP.CCTS_CODE=NORSK_COMPANY_GPTMP_TODAY.CCTS_CODE ;
insert into NORSK_COMPANY_GPTMP_TODAY (CMD_TYPE,CCTS_CODE,TRADE_CO,TRADE_NAME,BEGIN_DATE,END_DATE,CUSTOMS_CODE,INPUT_ID,AUTHORIZE_ID,OP_TIME,I_E_FLAG) select CMD_TYPE,CCTS_CODE,TRADE_CO,TRADE_NAME,BEGIN_DATE,END_DATE,CUSTOMS_CODE,INPUT_ID,AUTHORIZE_ID,OP_TIME,I_E_FLAG from NORSK_COMPANY_INC_EXT;
delete from NORSK_COMPANY_GPTMP;
\timing
