\echo ------------------NORSK_CONDITION----------------
select now();
\timing
delete from NORSK_CONDITION_GPTMP;
insert into NORSK_CONDITION_GPTMP (CMD_TYPE,CCTS_CODE) select CMD_TYPE,CCTS_CODE from NORSK_CONDITION_INC_EXT;
delete from NORSK_CONDITION_GPTMP_TODAY using NORSK_CONDITION_GPTMP where NORSK_CONDITION_GPTMP.CCTS_CODE=NORSK_CONDITION_GPTMP_TODAY.CCTS_CODE ;
insert into NORSK_CONDITION_GPTMP_TODAY (CMD_TYPE,CCTS_CODE,RSK_COND,RSK_COND_MID,RSK_COND_TXT,NOTE,BEGIN_DATE,END_DATE,CUSTOMS_CODE,INPUT_ID,AUTHORIZE_ID,OP_TIME) select CMD_TYPE,CCTS_CODE,RSK_COND,RSK_COND_MID,RSK_COND_TXT,NOTE,BEGIN_DATE,END_DATE,CUSTOMS_CODE,INPUT_ID,AUTHORIZE_ID,OP_TIME from NORSK_CONDITION_INC_EXT;
delete from NORSK_CONDITION_GPTMP;
\timing
