\echo ------------------OCC_ELE_LIST----------------
select now();
\timing
delete from OCC_ELE_LIST_GPTMP;
insert into OCC_ELE_LIST_GPTMP (CMD_TYPE,CERTIFICATE_NO, AGREEMENT_ID, ISSUE_PLACE, G_NO) select CMD_TYPE,CERTIFICATE_NO, AGREEMENT_ID, ISSUE_PLACE, G_NO from OCC_ELE_LIST_INC_EXT;
delete from OCC_ELE_LIST_GPTMP_TODAY using OCC_ELE_LIST_GPTMP where OCC_ELE_LIST_GPTMP.CERTIFICATE_NO=OCC_ELE_LIST_GPTMP_TODAY.CERTIFICATE_NO AND OCC_ELE_LIST_GPTMP.AGREEMENT_ID=OCC_ELE_LIST_GPTMP_TODAY.AGREEMENT_ID AND OCC_ELE_LIST_GPTMP.ISSUE_PLACE=OCC_ELE_LIST_GPTMP_TODAY.ISSUE_PLACE AND OCC_ELE_LIST_GPTMP.G_NO=OCC_ELE_LIST_GPTMP_TODAY.G_NO ;
insert into OCC_ELE_LIST_GPTMP_TODAY (CMD_TYPE,CERTIFICATE_NO,AGREEMENT_ID,ISSUE_PLACE,G_NO,CODE_TS,G_NAME_MODEL,PACK_NO,PACK_TYPE,G_QTY,G_UNIT,FOB_VALUE,FOB_CURRENCY,BRAND_NAME,REUSE1,REUSE2,HASH_SIGN) select CMD_TYPE,CERTIFICATE_NO,AGREEMENT_ID,ISSUE_PLACE,G_NO,CODE_TS,G_NAME_MODEL,PACK_NO,PACK_TYPE,G_QTY,G_UNIT,FOB_VALUE,FOB_CURRENCY,BRAND_NAME,REUSE1,REUSE2,HASH_SIGN from OCC_ELE_LIST_INC_EXT;
delete from OCC_ELE_LIST_GPTMP;
\timing
