\echo ------------------PAPERLESS_SELFSAVE_CERT----------------
select now();
\timing
delete from PAPERLESS_SELFSAVE_CERT_GPTMP;
insert into PAPERLESS_SELFSAVE_CERT_GPTMP (CMD_TYPE,ENTRY_ID) select CMD_TYPE,ENTRY_ID from PAPERLESS_SELFSAVE_CERT_INC_EXT;
delete from PAPERLESS_SELFSAVE_CERT_GPTMP_TODAY using PAPERLESS_SELFSAVE_CERT_GPTMP where PAPERLESS_SELFSAVE_CERT_GPTMP.ENTRY_ID=PAPERLESS_SELFSAVE_CERT_GPTMP_TODAY.ENTRY_ID ;
insert into PAPERLESS_SELFSAVE_CERT_GPTMP_TODAY (CMD_TYPE,ENTRY_ID,I_E_FLAG,DECL_PORT,REL_TIME,AGENT_CODE,TRADE_CO,TRADE_NAME,AGENT_NAME,PRINT_TIME,PROC_MARK,D_DATE) select CMD_TYPE,ENTRY_ID,I_E_FLAG,DECL_PORT,REL_TIME,AGENT_CODE,TRADE_CO,TRADE_NAME,AGENT_NAME,PRINT_TIME,PROC_MARK,D_DATE from PAPERLESS_SELFSAVE_CERT_INC_EXT;
delete from PAPERLESS_SELFSAVE_CERT_GPTMP;
\timing
