\echo ------------------PAYOUT_REMIT_HEAD----------------
select now();
\timing
delete from PAYOUT_REMIT_HEAD_GPTMP;
insert into PAYOUT_REMIT_HEAD_GPTMP (CMD_TYPE,RPTNO) select CMD_TYPE,RPTNO from PAYOUT_REMIT_HEAD_INC_EXT;
delete from PAYOUT_REMIT_HEAD_GPTMP_TODAY using PAYOUT_REMIT_HEAD_GPTMP where PAYOUT_REMIT_HEAD_GPTMP.RPTNO=PAYOUT_REMIT_HEAD_GPTMP_TODAY.RPTNO ;
insert into PAYOUT_REMIT_HEAD_GPTMP_TODAY (CMD_TYPE,RPTNO,RPTUSER,TRADE_CO,RCVNAME,ACTUCCY,ACTUAMT,CSTSETCODE,COUNTRYCODE,CSTCNTRCTNO,INVOICENO,LCBGNO,CUS_TRADE_CO,RECV_DATE) select CMD_TYPE,RPTNO,RPTUSER,TRADE_CO,RCVNAME,ACTUCCY,ACTUAMT,CSTSETCODE,COUNTRYCODE,CSTCNTRCTNO,INVOICENO,LCBGNO,CUS_TRADE_CO,RECV_DATE from PAYOUT_REMIT_HEAD_INC_EXT;
delete from PAYOUT_REMIT_HEAD_GPTMP;
\timing
