\echo ------------------PES_WORKFLOW----------------
select now();
\timing
delete from PES_WORKFLOW_GPTMP;
insert into PES_WORKFLOW_GPTMP (CMD_TYPE,NOTE_NO, NOTE_TYPE, PROCESS_DATE, STEP_ID) select CMD_TYPE,NOTE_NO, NOTE_TYPE, PROCESS_DATE, STEP_ID from PES_WORKFLOW_INC_EXT;
delete from PES_WORKFLOW_GPTMP_TODAY using PES_WORKFLOW_GPTMP where PES_WORKFLOW_GPTMP.NOTE_NO=PES_WORKFLOW_GPTMP_TODAY.NOTE_NO AND PES_WORKFLOW_GPTMP.NOTE_TYPE=PES_WORKFLOW_GPTMP_TODAY.NOTE_TYPE AND PES_WORKFLOW_GPTMP.PROCESS_DATE=PES_WORKFLOW_GPTMP_TODAY.PROCESS_DATE AND PES_WORKFLOW_GPTMP.STEP_ID=PES_WORKFLOW_GPTMP_TODAY.STEP_ID ;
insert into PES_WORKFLOW_GPTMP_TODAY (CMD_TYPE,NOTE_NO,NOTE_TYPE,PROCESS_DATE,STEP_ID,PROCESS_STATUS,STAT,ENTRY_ID,NOTE,PROCESS_ER) select CMD_TYPE,NOTE_NO,NOTE_TYPE,PROCESS_DATE,STEP_ID,PROCESS_STATUS,STAT,ENTRY_ID,NOTE,PROCESS_ER from PES_WORKFLOW_INC_EXT;
delete from PES_WORKFLOW_GPTMP;
\timing
