\echo ------------------PRE_IM_APPL_CLOSE----------------
select now();
\timing
delete from PRE_IM_APPL_CLOSE_GPTMP;
insert into PRE_IM_APPL_CLOSE_GPTMP (CMD_TYPE,MANUAL_NO, CONTR_ITEM) select CMD_TYPE,MANUAL_NO, CONTR_ITEM from PRE_IM_APPL_CLOSE_INC_EXT;
delete from PRE_IM_APPL_CLOSE_GPTMP_TODAY using PRE_IM_APPL_CLOSE_GPTMP where PRE_IM_APPL_CLOSE_GPTMP.MANUAL_NO=PRE_IM_APPL_CLOSE_GPTMP_TODAY.MANUAL_NO AND PRE_IM_APPL_CLOSE_GPTMP.CONTR_ITEM=PRE_IM_APPL_CLOSE_GPTMP_TODAY.CONTR_ITEM ;
insert into PRE_IM_APPL_CLOSE_GPTMP_TODAY (CMD_TYPE,MANUAL_NO,CONTR_ITEM,CODE_TS,G_NAME,G_MODEL,FACT_QTY,T_IN_QTY,T_EX_QTY,USED_QTY,REMAIN_QTY,PROC_MODE,CORR_MANUAL_NO) select CMD_TYPE,MANUAL_NO,CONTR_ITEM,CODE_TS,G_NAME,G_MODEL,FACT_QTY,T_IN_QTY,T_EX_QTY,USED_QTY,REMAIN_QTY,PROC_MODE,CORR_MANUAL_NO from PRE_IM_APPL_CLOSE_INC_EXT;
delete from PRE_IM_APPL_CLOSE_GPTMP;
\timing
