\echo ------------------PRE_EXA_APPL_CLOSE----------------
select now();
\timing
delete from PRE_EXA_APPL_CLOSE_GPTMP;
insert into PRE_EXA_APPL_CLOSE_GPTMP (CMD_TYPE,MANUAL_NO, CONTR_ITEM) select CMD_TYPE,MANUAL_NO, CONTR_ITEM from PRE_EXA_APPL_CLOSE_INC_EXT;
delete from PRE_EXA_APPL_CLOSE_GPTMP_TODAY using PRE_EXA_APPL_CLOSE_GPTMP where PRE_EXA_APPL_CLOSE_GPTMP.MANUAL_NO=PRE_EXA_APPL_CLOSE_GPTMP_TODAY.MANUAL_NO AND PRE_EXA_APPL_CLOSE_GPTMP.CONTR_ITEM=PRE_EXA_APPL_CLOSE_GPTMP_TODAY.CONTR_ITEM ;
insert into PRE_EXA_APPL_CLOSE_GPTMP_TODAY (CMD_TYPE,MANUAL_NO,CONTR_ITEM,CODE_TS,G_NAME,G_MODEL,G_QTY,DECL_PRICE,G_AMT,PROC_MODE,BOOK_NO) select CMD_TYPE,MANUAL_NO,CONTR_ITEM,CODE_TS,G_NAME,G_MODEL,G_QTY,DECL_PRICE,G_AMT,PROC_MODE,BOOK_NO from PRE_EXA_APPL_CLOSE_INC_EXT;
delete from PRE_EXA_APPL_CLOSE_GPTMP;
\timing
