\echo ------------------PRE_DECL_REL----------------
select now();
\timing
delete from PRE_DECL_REL_GPTMP;
insert into PRE_DECL_REL_GPTMP (CMD_TYPE,DECL_TRAIN_CO) select CMD_TYPE,DECL_TRAIN_CO from PRE_DECL_REL_INC_EXT;
delete from PRE_DECL_REL_GPTMP_TODAY using PRE_DECL_REL_GPTMP where PRE_DECL_REL_GPTMP.DECL_TRAIN_CO=PRE_DECL_REL_GPTMP_TODAY.DECL_TRAIN_CO ;
insert into PRE_DECL_REL_GPTMP_TODAY (CMD_TYPE,TRADE_CO,DECL_TRAIN_CO,DECL_ZG_CODE,DECL_NAME,DECL_SEX,DECL_DEGREE,DECL_ID_CODE,DECL_TEL_BP_CODE,DECL_APPL_TIME,DECL_TEST_SCORE,DECL_APPL_FLAG,DECL_INP_DATE,DECL_NOTE) select CMD_TYPE,TRADE_CO,DECL_TRAIN_CO,DECL_ZG_CODE,DECL_NAME,DECL_SEX,DECL_DEGREE,DECL_ID_CODE,DECL_TEL_BP_CODE,DECL_APPL_TIME,DECL_TEST_SCORE,DECL_APPL_FLAG,DECL_INP_DATE,DECL_NOTE from PRE_DECL_REL_INC_EXT;
delete from PRE_DECL_REL_GPTMP;
\timing
