\echo ------------------PRE_IM_FASCICLE_LIST----------------
select now();
\timing
delete from PRE_IM_FASCICLE_LIST_GPTMP;
insert into PRE_IM_FASCICLE_LIST_GPTMP (CMD_TYPE,FASCICLE_NO, CONTR_ITEM) select CMD_TYPE,FASCICLE_NO, CONTR_ITEM from PRE_IM_FASCICLE_LIST_INC_EXT;
delete from PRE_IM_FASCICLE_LIST_GPTMP_TODAY using PRE_IM_FASCICLE_LIST_GPTMP where PRE_IM_FASCICLE_LIST_GPTMP.FASCICLE_NO=PRE_IM_FASCICLE_LIST_GPTMP_TODAY.FASCICLE_NO AND PRE_IM_FASCICLE_LIST_GPTMP.CONTR_ITEM=PRE_IM_FASCICLE_LIST_GPTMP_TODAY.CONTR_ITEM ;
insert into PRE_IM_FASCICLE_LIST_GPTMP_TODAY (CMD_TYPE,MANUAL_NO,FASCICLE_NO,CONTR_ITEM,APPR_QTY,FACT_QTY) select CMD_TYPE,MANUAL_NO,FASCICLE_NO,CONTR_ITEM,APPR_QTY,FACT_QTY from PRE_IM_FASCICLE_LIST_INC_EXT;
delete from PRE_IM_FASCICLE_LIST_GPTMP;
\timing
