\echo ------------------PRE_REL_ALC_WORK----------------
select now();
\timing
delete from PRE_REL_ALC_WORK_GPTMP;
insert into PRE_REL_ALC_WORK_GPTMP (CMD_TYPE,ENTRY_ID) select CMD_TYPE,ENTRY_ID from PRE_REL_ALC_WORK_INC_EXT;
delete from PRE_REL_ALC_WORK_GPTMP_TODAY using PRE_REL_ALC_WORK_GPTMP where PRE_REL_ALC_WORK_GPTMP.ENTRY_ID=PRE_REL_ALC_WORK_GPTMP_TODAY.ENTRY_ID ;
insert into PRE_REL_ALC_WORK_GPTMP_TODAY (CMD_TYPE,ENTRY_ID,CUSTOMS_CODE,I_E_PORT,D_DATE,REC_DATE,DECL_TYPE,AVR_FLAG,RSK_FLAG,REL_TYPE,TRAF_NAME,VOYAGE_NO,BILL_NO,LAST_STEP,PROC_FLAG,OP_DATE) select CMD_TYPE,ENTRY_ID,CUSTOMS_CODE,I_E_PORT,D_DATE,REC_DATE,DECL_TYPE,AVR_FLAG,RSK_FLAG,REL_TYPE,TRAF_NAME,VOYAGE_NO,BILL_NO,LAST_STEP,PROC_FLAG,OP_DATE from PRE_REL_ALC_WORK_INC_EXT;
delete from PRE_REL_ALC_WORK_GPTMP;
\timing
