\echo ------------------PRE_INVESTER_REL----------------
select now();
\timing
delete from PRE_INVESTER_REL_GPTMP;
insert into PRE_INVESTER_REL_GPTMP (CMD_TYPE,PRE_TRADE_CO, INV_NO) select CMD_TYPE,PRE_TRADE_CO, INV_NO from PRE_INVESTER_REL_INC_EXT;
delete from PRE_INVESTER_REL_GPTMP_TODAY using PRE_INVESTER_REL_GPTMP where PRE_INVESTER_REL_GPTMP.PRE_TRADE_CO=PRE_INVESTER_REL_GPTMP_TODAY.PRE_TRADE_CO AND PRE_INVESTER_REL_GPTMP.INV_NO=PRE_INVESTER_REL_GPTMP_TODAY.INV_NO ;
insert into PRE_INVESTER_REL_GPTMP_TODAY (CMD_TYPE,PRE_TRADE_CO,INV_NO,INV_CO,INV_MOD,INV_FUND,ACT_FUND,INV_DATE,INV_COUNTRY) select CMD_TYPE,PRE_TRADE_CO,INV_NO,INV_CO,INV_MOD,INV_FUND,ACT_FUND,INV_DATE,INV_COUNTRY from PRE_INVESTER_REL_INC_EXT;
delete from PRE_INVESTER_REL_GPTMP;
\timing
