\echo ------------------PRE_APPL_CLOSE----------------
select now();
\timing
delete from PRE_APPL_CLOSE_GPTMP;
insert into PRE_APPL_CLOSE_GPTMP (CMD_TYPE,MANUAL_NO) select CMD_TYPE,MANUAL_NO from PRE_APPL_CLOSE_INC_EXT;
delete from PRE_APPL_CLOSE_GPTMP_TODAY using PRE_APPL_CLOSE_GPTMP where PRE_APPL_CLOSE_GPTMP.MANUAL_NO=PRE_APPL_CLOSE_GPTMP_TODAY.MANUAL_NO ;
insert into PRE_APPL_CLOSE_GPTMP_TODAY (CMD_TYPE,MANUAL_NO,APPL_NO,APPL_DATE,DECL_IN_AMT,DECL_EX_AMT,DECL_IN_COUNT,DECL_EX_COUNT,REMAIN_IN_AMT,REMAIN_EX_AMT,RESOR_IN_COUNT,PRODU_IN_COUNT,RESOR_EX_COUNT,PRODU_EX_COUNT,RESOR_IN_AMT,PRODU_IN_AMT,RESOR_EX_AMT,PRODU_EX_AMT,DC_DATE,TYPE_ER,DECL_CO,CHK_ER,RECHK_ER,CHK_DATE,RECHK_DATE,NOTE_S) select CMD_TYPE,MANUAL_NO,APPL_NO,APPL_DATE,DECL_IN_AMT,DECL_EX_AMT,DECL_IN_COUNT,DECL_EX_COUNT,REMAIN_IN_AMT,REMAIN_EX_AMT,RESOR_IN_COUNT,PRODU_IN_COUNT,RESOR_EX_COUNT,PRODU_EX_COUNT,RESOR_IN_AMT,PRODU_IN_AMT,RESOR_EX_AMT,PRODU_EX_AMT,DC_DATE,TYPE_ER,DECL_CO,CHK_ER,RECHK_ER,CHK_DATE,RECHK_DATE,NOTE_S from PRE_APPL_CLOSE_INC_EXT;
delete from PRE_APPL_CLOSE_GPTMP;
\timing
