\echo ------------------PRICE_LIBRARY----------------
select now();
\timing
delete from PRICE_LIBRARY_GPTMP;
insert into PRICE_LIBRARY_GPTMP (CMD_TYPE,REC_NO, I_E_FLAG, REC_TYPE, CREATE_DATE, POST_MARK) select CMD_TYPE,REC_NO, I_E_FLAG, REC_TYPE, CREATE_DATE, POST_MARK from PRICE_LIBRARY_INC_EXT;
delete from PRICE_LIBRARY_GPTMP_TODAY using PRICE_LIBRARY_GPTMP where PRICE_LIBRARY_GPTMP.REC_NO=PRICE_LIBRARY_GPTMP_TODAY.REC_NO AND PRICE_LIBRARY_GPTMP.I_E_FLAG=PRICE_LIBRARY_GPTMP_TODAY.I_E_FLAG AND PRICE_LIBRARY_GPTMP.REC_TYPE=PRICE_LIBRARY_GPTMP_TODAY.REC_TYPE AND PRICE_LIBRARY_GPTMP.CREATE_DATE=PRICE_LIBRARY_GPTMP_TODAY.CREATE_DATE AND PRICE_LIBRARY_GPTMP.POST_MARK=PRICE_LIBRARY_GPTMP_TODAY.POST_MARK ;
insert into PRICE_LIBRARY_GPTMP_TODAY (CMD_TYPE,REC_NO,I_E_FLAG,REC_TYPE,CREATE_DATE,POST_MARK,CODE_TS,G_NAME,G_NAME_E,BRAND_C,BRAND_E,G_MODEL,ORIGIN_COUNTRY,TRADE_COUNTRY,TRANS_MODE,TRANS_PORT,CURR_CODE,PRICE,DECL_PRICE,PRICE_CO,QTY,UNIT_NAME,TRAF_MODE,TRADE_MODE,TRADE_NAME,OWNER_NAME,WRAP_TYPE,PAY_WAY,NOTE_S,I_E_DATE,INPUT_DATE,BEG_DATE,END_DATE,CUSTOMER_CODE,FORM_ID,ID_TYPE,MARK1,MARK2,MARK3,MARK4) select CMD_TYPE,REC_NO,I_E_FLAG,REC_TYPE,CREATE_DATE,POST_MARK,CODE_TS,G_NAME,G_NAME_E,BRAND_C,BRAND_E,G_MODEL,ORIGIN_COUNTRY,TRADE_COUNTRY,TRANS_MODE,TRANS_PORT,CURR_CODE,PRICE,DECL_PRICE,PRICE_CO,QTY,UNIT_NAME,TRAF_MODE,TRADE_MODE,TRADE_NAME,OWNER_NAME,WRAP_TYPE,PAY_WAY,NOTE_S,I_E_DATE,INPUT_DATE,BEG_DATE,END_DATE,CUSTOMER_CODE,FORM_ID,ID_TYPE,MARK1,MARK2,MARK3,MARK4 from PRICE_LIBRARY_INC_EXT;
delete from PRICE_LIBRARY_GPTMP;
\timing
