\echo ------------------RAM_RG_COPINFO----------------
select now();
\timing
delete from RAM_RG_COPINFO_GPTMP;
insert into RAM_RG_COPINFO_GPTMP (CMD_TYPE,RAM_ID, TYPE, COP_NO) select CMD_TYPE,RAM_ID, TYPE, COP_NO from RAM_RG_COPINFO_INC_EXT;
delete from RAM_RG_COPINFO_GPTMP_TODAY using RAM_RG_COPINFO_GPTMP where RAM_RG_COPINFO_GPTMP.RAM_ID=RAM_RG_COPINFO_GPTMP_TODAY.RAM_ID AND RAM_RG_COPINFO_GPTMP.TYPE=RAM_RG_COPINFO_GPTMP_TODAY.TYPE AND RAM_RG_COPINFO_GPTMP.COP_NO=RAM_RG_COPINFO_GPTMP_TODAY.COP_NO ;
insert into RAM_RG_COPINFO_GPTMP_TODAY (CMD_TYPE,RAM_ID,TYPE,COP_NO,COP_CODE,COP_NAME,COP_TYPE,MASTER_CUSTOMS,CHANGE_NOTE,NOTE,LINKMAN,YD_CHK_DATE,YD_CHK_ER,YD_CHK_MARK,YD_CHK_NOTE,YD_LINK_NO) select CMD_TYPE,RAM_ID,TYPE,COP_NO,COP_CODE,COP_NAME,COP_TYPE,MASTER_CUSTOMS,CHANGE_NOTE,NOTE,LINKMAN,YD_CHK_DATE,YD_CHK_ER,YD_CHK_MARK,YD_CHK_NOTE,YD_LINK_NO from RAM_RG_COPINFO_INC_EXT;
delete from RAM_RG_COPINFO_GPTMP;
\timing
