\echo ------------------RAM_LIST----------------
select now();
\timing
delete from RAM_LIST_GPTMP;
insert into RAM_LIST_GPTMP (CMD_TYPE,RAM_ID, NUM) select CMD_TYPE,RAM_ID, NUM from RAM_LIST_INC_EXT;
delete from RAM_LIST_GPTMP_TODAY using RAM_LIST_GPTMP where RAM_LIST_GPTMP.RAM_ID=RAM_LIST_GPTMP_TODAY.RAM_ID AND RAM_LIST_GPTMP.NUM=RAM_LIST_GPTMP_TODAY.NUM ;
insert into RAM_LIST_GPTMP_TODAY (CMD_TYPE,RAM_ID,NUM,G_NO,CODE_TS,G_NAME,G_MODEL,G_UNIT,G_QTY,DECL_TOTAL,TRADE_CURR,FACT_AMT,RESERVE1,NOTE,CUT_ID,PROJECT_ID,I_DATE) select CMD_TYPE,RAM_ID,NUM,G_NO,CODE_TS,G_NAME,G_MODEL,G_UNIT,G_QTY,DECL_TOTAL,TRADE_CURR,FACT_AMT,RESERVE1,NOTE,CUT_ID,PROJECT_ID,I_DATE from RAM_LIST_INC_EXT;
delete from RAM_LIST_GPTMP;
\timing
