\echo ------------------RAM_STATUS----------------
select now();
\timing
delete from RAM_STATUS_GPTMP;
insert into RAM_STATUS_GPTMP (CMD_TYPE,CUT_ID, G_NO) select CMD_TYPE,CUT_ID, G_NO from RAM_STATUS_INC_EXT;
delete from RAM_STATUS_GPTMP_TODAY using RAM_STATUS_GPTMP where RAM_STATUS_GPTMP.CUT_ID=RAM_STATUS_GPTMP_TODAY.CUT_ID AND RAM_STATUS_GPTMP.G_NO=RAM_STATUS_GPTMP_TODAY.G_NO ;
insert into RAM_STATUS_GPTMP_TODAY (CMD_TYPE,CUT_ID,G_NO,MASTER_CUSTOMS,CUT_MODE,VERIFY_DATE,OWNER_CODE,OWNER_NAME,CODE_TS,G_NAME,G_MODEL,FREEZE_MONTHS,G_UNIT,FACT_AMT,FACT_QTY) select CMD_TYPE,CUT_ID,G_NO,MASTER_CUSTOMS,CUT_MODE,VERIFY_DATE,OWNER_CODE,OWNER_NAME,CODE_TS,G_NAME,G_MODEL,FREEZE_MONTHS,G_UNIT,FACT_AMT,FACT_QTY from RAM_STATUS_INC_EXT;
delete from RAM_STATUS_GPTMP;
\timing
