\echo ------------------RAM_RN_INFO----------------
select now();
\timing
delete from RAM_RN_INFO_GPTMP;
insert into RAM_RN_INFO_GPTMP (CMD_TYPE,RAM_ID) select CMD_TYPE,RAM_ID from RAM_RN_INFO_INC_EXT;
delete from RAM_RN_INFO_GPTMP_TODAY using RAM_RN_INFO_GPTMP where RAM_RN_INFO_GPTMP.RAM_ID=RAM_RN_INFO_GPTMP_TODAY.RAM_ID ;
insert into RAM_RN_INFO_GPTMP_TODAY (CMD_TYPE,PRE_RAM_ID,RAM_ID,COP_CODE,COP_NAME,RAM_TYPE,RN_YEAR,MASTER_CUSTOMS,INPUT_DATE,INPUT_ER,PRE_PRINT_ER,PRE_PRINT_DATE,DECL_DATE,CHK_DATE,CHK_ER,CHECK_NOTE,RECHK_DATE,RECHK_ER,RECHK_NOTE,REPLY_DATE,REPLY_ER,REPLY_CHECK_NOTE,MODIFY_DATE,MODIFY_ER,MODIFY_NOTE,EXE_MARK,PRINT_DATE,PRINT_ER,SOURCE_TYPE,NOTE_PLACE,NOTE_RAM,NOTE_OVER_SCOPE,NOTE_GOODS,NOTE_COP,NOTE_PROJECT,NOTE_ASSETS,OTHER,NOTE) select CMD_TYPE,PRE_RAM_ID,RAM_ID,COP_CODE,COP_NAME,RAM_TYPE,RN_YEAR,MASTER_CUSTOMS,INPUT_DATE,INPUT_ER,PRE_PRINT_ER,PRE_PRINT_DATE,DECL_DATE,CHK_DATE,CHK_ER,CHECK_NOTE,RECHK_DATE,RECHK_ER,RECHK_NOTE,REPLY_DATE,REPLY_ER,REPLY_CHECK_NOTE,MODIFY_DATE,MODIFY_ER,MODIFY_NOTE,EXE_MARK,PRINT_DATE,PRINT_ER,SOURCE_TYPE,NOTE_PLACE,NOTE_RAM,NOTE_OVER_SCOPE,NOTE_GOODS,NOTE_COP,NOTE_PROJECT,NOTE_ASSETS,OTHER,NOTE from RAM_RN_INFO_INC_EXT;
delete from RAM_RN_INFO_GPTMP;
\timing
