\echo ------------------RCP_RECORD_HEAD----------------
select now();
\timing
delete from RCP_RECORD_HEAD_GPTMP;
insert into RCP_RECORD_HEAD_GPTMP (CMD_TYPE,LEVYNO) select CMD_TYPE,LEVYNO from RCP_RECORD_HEAD_INC_EXT;
delete from RCP_RECORD_HEAD_GPTMP_TODAY using RCP_RECORD_HEAD_GPTMP where RCP_RECORD_HEAD_GPTMP.LEVYNO=RCP_RECORD_HEAD_GPTMP_TODAY.LEVYNO ;
insert into RCP_RECORD_HEAD_GPTMP_TODAY (CMD_TYPE,LEVYNO,ORGCODE,CGACCODE,ORGNAME,ENTRYID,TRADEDATE,TOTALAMT,BALANCEMODE,PACTNO,PRERECDATE,PRERECAMT) select CMD_TYPE,LEVYNO,ORGCODE,CGACCODE,ORGNAME,ENTRYID,TRADEDATE,TOTALAMT,BALANCEMODE,PACTNO,PRERECDATE,PRERECAMT from RCP_RECORD_HEAD_INC_EXT;
delete from RCP_RECORD_HEAD_GPTMP;
\timing
