\echo ------------------RCP_INCOME_LIST----------------
select now();
\timing
delete from RCP_INCOME_LIST_GPTMP;
insert into RCP_INCOME_LIST_GPTMP (CMD_TYPE,LEVYNO, LISTNO) select CMD_TYPE,LEVYNO, LISTNO from RCP_INCOME_LIST_INC_EXT;
delete from RCP_INCOME_LIST_GPTMP_TODAY using RCP_INCOME_LIST_GPTMP where RCP_INCOME_LIST_GPTMP.LEVYNO=RCP_INCOME_LIST_GPTMP_TODAY.LEVYNO AND RCP_INCOME_LIST_GPTMP.LISTNO=RCP_INCOME_LIST_GPTMP_TODAY.LISTNO ;
insert into RCP_INCOME_LIST_GPTMP_TODAY (CMD_TYPE,LEVYNO,LISTNO,CUSTOMSDATE) select CMD_TYPE,LEVYNO,LISTNO,CUSTOMSDATE from RCP_INCOME_LIST_INC_EXT;
delete from RCP_INCOME_LIST_GPTMP;
\timing
