\echo ------------------RCP_RECORD_LIST_BAK----------------
select now();
\timing
delete from RCP_RECORD_LIST_BAK_GPTMP;
insert into RCP_RECORD_LIST_BAK_GPTMP (CMD_TYPE,LEVYNO, LISTNO) select CMD_TYPE,LEVYNO, LISTNO from RCP_RECORD_LIST_BAK_INC_EXT;
delete from RCP_RECORD_LIST_BAK_GPTMP_TODAY using RCP_RECORD_LIST_BAK_GPTMP where RCP_RECORD_LIST_BAK_GPTMP.LEVYNO=RCP_RECORD_LIST_BAK_GPTMP_TODAY.LEVYNO AND RCP_RECORD_LIST_BAK_GPTMP.LISTNO=RCP_RECORD_LIST_BAK_GPTMP_TODAY.LISTNO ;
insert into RCP_RECORD_LIST_BAK_GPTMP_TODAY (CMD_TYPE,LEVYNO,LISTNO,COUNTRYAREA,BANKNAMEOUT,BANKACCTOUT,BANKAMTOUT,RECDATEOUT,REMARK) select CMD_TYPE,LEVYNO,LISTNO,COUNTRYAREA,BANKNAMEOUT,BANKACCTOUT,BANKAMTOUT,RECDATEOUT,REMARK from RCP_RECORD_LIST_BAK_INC_EXT;
delete from RCP_RECORD_LIST_BAK_GPTMP;
\timing
