\echo ------------------RCP_INCOME_HEAD_BAK----------------
select now();
\timing
delete from RCP_INCOME_HEAD_BAK_GPTMP;
insert into RCP_INCOME_HEAD_BAK_GPTMP (CMD_TYPE,LEVYNO) select CMD_TYPE,LEVYNO from RCP_INCOME_HEAD_BAK_INC_EXT;
delete from RCP_INCOME_HEAD_BAK_GPTMP_TODAY using RCP_INCOME_HEAD_BAK_GPTMP where RCP_INCOME_HEAD_BAK_GPTMP.LEVYNO=RCP_INCOME_HEAD_BAK_GPTMP_TODAY.LEVYNO ;
insert into RCP_INCOME_HEAD_BAK_GPTMP_TODAY (CMD_TYPE,LEVYNO,BANKORGCODE,PAYEENAME,PAYEEORGCODE,PAYEECGACCODE,PAYEEACCT,PAYERNAME,PAYERCOUNTRYCODE,SWIFTBIC,PAYEEDATE,PAYEECNY,PAYEEAMT,CUSTOMSAMT,PREPAYEEAMT,REFUNDMENTAMT,BALANCEMODE,ACCOUNTPERIOD,BANKTRANO,ADDWORD) select CMD_TYPE,LEVYNO,BANKORGCODE,PAYEENAME,PAYEEORGCODE,PAYEECGACCODE,PAYEEACCT,PAYERNAME,PAYERCOUNTRYCODE,SWIFTBIC,PAYEEDATE,PAYEECNY,PAYEEAMT,CUSTOMSAMT,PREPAYEEAMT,REFUNDMENTAMT,BALANCEMODE,ACCOUNTPERIOD,BANKTRANO,ADDWORD from RCP_INCOME_HEAD_BAK_INC_EXT;
delete from RCP_INCOME_HEAD_BAK_GPTMP;
\timing
