\echo ------------------RCP_RECORD_LIST----------------
select now();
\timing
delete from RCP_RECORD_LIST_GPTMP;
insert into RCP_RECORD_LIST_GPTMP (CMD_TYPE,LEVYNO, LISTNO) select CMD_TYPE,LEVYNO, LISTNO from RCP_RECORD_LIST_INC_EXT;
delete from RCP_RECORD_LIST_GPTMP_TODAY using RCP_RECORD_LIST_GPTMP where RCP_RECORD_LIST_GPTMP.LEVYNO=RCP_RECORD_LIST_GPTMP_TODAY.LEVYNO AND RCP_RECORD_LIST_GPTMP.LISTNO=RCP_RECORD_LIST_GPTMP_TODAY.LISTNO ;
insert into RCP_RECORD_LIST_GPTMP_TODAY (CMD_TYPE,LEVYNO,LISTNO,COUNTRYAREA,BANKNAMEOUT,BANKACCTOUT,BANKAMTOUT,RECDATEOUT,REMARK) select CMD_TYPE,LEVYNO,LISTNO,COUNTRYAREA,BANKNAMEOUT,BANKACCTOUT,BANKAMTOUT,RECDATEOUT,REMARK from RCP_RECORD_LIST_INC_EXT;
delete from RCP_RECORD_LIST_GPTMP;
\timing
