\echo ------------------RED_MAX_NO----------------
select now();
\timing
delete from RED_MAX_NO_GPTMP;
insert into RED_MAX_NO_GPTMP (CMD_TYPE,MASTER_CUSTOMS, YEAR_1, CLASS) select CMD_TYPE,MASTER_CUSTOMS, YEAR_1, CLASS from RED_MAX_NO_INC_EXT;
delete from RED_MAX_NO_GPTMP_TODAY using RED_MAX_NO_GPTMP where RED_MAX_NO_GPTMP.MASTER_CUSTOMS=RED_MAX_NO_GPTMP_TODAY.MASTER_CUSTOMS AND RED_MAX_NO_GPTMP.YEAR_1=RED_MAX_NO_GPTMP_TODAY.YEAR_1 AND RED_MAX_NO_GPTMP.CLASS=RED_MAX_NO_GPTMP_TODAY.CLASS ;
insert into RED_MAX_NO_GPTMP_TODAY (CMD_TYPE,MASTER_CUSTOMS,YEAR_1,CLASS,MAX_NO) select CMD_TYPE,MASTER_CUSTOMS,YEAR_1,CLASS,MAX_NO from RED_MAX_NO_INC_EXT;
delete from RED_MAX_NO_GPTMP;
\timing
