\echo ------------------REL_ALC_WORK----------------
select now();
\timing
delete from REL_ALC_WORK_GPTMP;
insert into REL_ALC_WORK_GPTMP (CMD_TYPE,ENTRY_ID) select CMD_TYPE,ENTRY_ID from REL_ALC_WORK_INC_EXT;
delete from REL_ALC_WORK_GPTMP_TODAY using REL_ALC_WORK_GPTMP where REL_ALC_WORK_GPTMP.ENTRY_ID=REL_ALC_WORK_GPTMP_TODAY.ENTRY_ID ;
insert into REL_ALC_WORK_GPTMP_TODAY (CMD_TYPE,ENTRY_ID,STEP_ID,REC_DATE,CUSTOMS_CODE,I_E_PORT,TRAF_NAME,VOYAGE_NO,BILL_NO,PROC_FLAG,OP_DATE,PASSED_FLAG) select CMD_TYPE,ENTRY_ID,STEP_ID,REC_DATE,CUSTOMS_CODE,I_E_PORT,TRAF_NAME,VOYAGE_NO,BILL_NO,PROC_FLAG,OP_DATE,PASSED_FLAG from REL_ALC_WORK_INC_EXT;
delete from REL_ALC_WORK_GPTMP;
\timing
