\echo ------------------RETURN_REL----------------
select now();
\timing
delete from RETURN_REL_GPTMP;
insert into RETURN_REL_GPTMP (CMD_TYPE,RET_TRANS_NO, RET_TYPE, RET_TIME) select CMD_TYPE,RET_TRANS_NO, RET_TYPE, RET_TIME from RETURN_REL_INC_EXT;
delete from RETURN_REL_GPTMP_TODAY using RETURN_REL_GPTMP where RETURN_REL_GPTMP.RET_TRANS_NO=RETURN_REL_GPTMP_TODAY.RET_TRANS_NO AND RETURN_REL_GPTMP.RET_TYPE=RETURN_REL_GPTMP_TODAY.RET_TYPE AND RETURN_REL_GPTMP.RET_TIME=RETURN_REL_GPTMP_TODAY.RET_TIME ;
insert into RETURN_REL_GPTMP_TODAY (CMD_TYPE,RET_TRANS_NO,RET_TYPE,RET_TIME,RET_CODE,RET_MESS) select CMD_TYPE,RET_TRANS_NO,RET_TYPE,RET_TIME,RET_CODE,RET_MESS from RETURN_REL_INC_EXT;
delete from RETURN_REL_GPTMP;
\timing
