\echo ------------------RISK_CONTROL----------------
select now();
\timing
delete from RISK_CONTROL_GPTMP;
insert into RISK_CONTROL_GPTMP (CMD_TYPE,RISK_CONTROL_CODE, RISK_TYPE, RISK_SCHEDULE) select CMD_TYPE,RISK_CONTROL_CODE, RISK_TYPE, RISK_SCHEDULE from RISK_CONTROL_INC_EXT;
delete from RISK_CONTROL_GPTMP_TODAY using RISK_CONTROL_GPTMP where RISK_CONTROL_GPTMP.RISK_CONTROL_CODE=RISK_CONTROL_GPTMP_TODAY.RISK_CONTROL_CODE AND RISK_CONTROL_GPTMP.RISK_TYPE=RISK_CONTROL_GPTMP_TODAY.RISK_TYPE AND RISK_CONTROL_GPTMP.RISK_SCHEDULE=RISK_CONTROL_GPTMP_TODAY.RISK_SCHEDULE ;
insert into RISK_CONTROL_GPTMP_TODAY (CMD_TYPE,RISK_CONTROL_CODE,RISK_TYPE,RISK_SCHEDULE,RISK_SOURCE,RISK_RANGE,RISK_PRIORITY,RISK_DEPT,RISK_ADM_CODE,RISK_ADM,RISK_DATE,RISK_OPEN,RISK_CLOSE,RISK_REASON,RISK_ACTIVITY,RISK_COP_INF) select CMD_TYPE,RISK_CONTROL_CODE,RISK_TYPE,RISK_SCHEDULE,RISK_SOURCE,RISK_RANGE,RISK_PRIORITY,RISK_DEPT,RISK_ADM_CODE,RISK_ADM,RISK_DATE,RISK_OPEN,RISK_CLOSE,RISK_REASON,RISK_ACTIVITY,RISK_COP_INF from RISK_CONTROL_INC_EXT;
delete from RISK_CONTROL_GPTMP;
\timing
