\echo ------------------RSK_CONDITION----------------
select now();
\timing
delete from RSK_CONDITION_GPTMP;
insert into RSK_CONDITION_GPTMP (CMD_TYPE,CCTS_CODE) select CMD_TYPE,CCTS_CODE from RSK_CONDITION_INC_EXT;
delete from RSK_CONDITION_GPTMP_TODAY using RSK_CONDITION_GPTMP where RSK_CONDITION_GPTMP.CCTS_CODE=RSK_CONDITION_GPTMP_TODAY.CCTS_CODE ;
insert into RSK_CONDITION_GPTMP_TODAY (CMD_TYPE,CCTS_CODE,TRADE_CO,TRADE_NAME,CORP_TYPE,RSK_COND,RSK_COND_MID,RSK_COND_TXT,BEGIN_DATE,END_DATE,CUSTOMS_CODE,SMUGGLE_MODE,INPUT_ID,AUTHORIZE_ID,OP_TIME) select CMD_TYPE,CCTS_CODE,TRADE_CO,TRADE_NAME,CORP_TYPE,RSK_COND,RSK_COND_MID,RSK_COND_TXT,BEGIN_DATE,END_DATE,CUSTOMS_CODE,SMUGGLE_MODE,INPUT_ID,AUTHORIZE_ID,OP_TIME from RSK_CONDITION_INC_EXT;
delete from RSK_CONDITION_GPTMP;
\timing
