\echo ------------------RSK_CODE_TS----------------
select now();
\timing
delete from RSK_CODE_TS_GPTMP;
insert into RSK_CODE_TS_GPTMP (CMD_TYPE,CCTS_CODE) select CMD_TYPE,CCTS_CODE from RSK_CODE_TS_INC_EXT;
delete from RSK_CODE_TS_GPTMP_TODAY using RSK_CODE_TS_GPTMP where RSK_CODE_TS_GPTMP.CCTS_CODE=RSK_CODE_TS_GPTMP_TODAY.CCTS_CODE ;
insert into RSK_CODE_TS_GPTMP_TODAY (CMD_TYPE,CCTS_CODE,CODE_TS,I_E_FLAG,CUSTOMS_CODE,BEGIN_DATE,END_DATE,INPUT_ID,AUTHORIZE_ID,OP_TIME,NOTE) select CMD_TYPE,CCTS_CODE,CODE_TS,I_E_FLAG,CUSTOMS_CODE,BEGIN_DATE,END_DATE,INPUT_ID,AUTHORIZE_ID,OP_TIME,NOTE from RSK_CODE_TS_INC_EXT;
delete from RSK_CODE_TS_GPTMP;
\timing
