\echo ------------------RSK_EXAM_LIST_CONTAINER----------------
select now();
\timing
delete from RSK_EXAM_LIST_CONTAINER_GPTMP;
insert into RSK_EXAM_LIST_CONTAINER_GPTMP (CMD_TYPE,EXAM_REC_ID, CONTAINER_ID) select CMD_TYPE,EXAM_REC_ID, CONTAINER_ID from RSK_EXAM_LIST_CONTAINER_INC_EXT;
delete from RSK_EXAM_LIST_CONTAINER_GPTMP_TODAY using RSK_EXAM_LIST_CONTAINER_GPTMP where RSK_EXAM_LIST_CONTAINER_GPTMP.EXAM_REC_ID=RSK_EXAM_LIST_CONTAINER_GPTMP_TODAY.EXAM_REC_ID AND RSK_EXAM_LIST_CONTAINER_GPTMP.CONTAINER_ID=RSK_EXAM_LIST_CONTAINER_GPTMP_TODAY.CONTAINER_ID ;
insert into RSK_EXAM_LIST_CONTAINER_GPTMP_TODAY (CMD_TYPE,EXAM_REC_ID,C_NO,CONTAINER_ID,CONTAINER_ID_RESULT,NEW_SEAL_NO,SEAL_NO,SEAL_NO_RESULT,HOLLOW_AREA1,HOLLOW_AREA2,MANUAL_FLAG,CONTA_RESULT) select CMD_TYPE,EXAM_REC_ID,C_NO,CONTAINER_ID,CONTAINER_ID_RESULT,NEW_SEAL_NO,SEAL_NO,SEAL_NO_RESULT,HOLLOW_AREA1,HOLLOW_AREA2,MANUAL_FLAG,CONTA_RESULT from RSK_EXAM_LIST_CONTAINER_INC_EXT;
delete from RSK_EXAM_LIST_CONTAINER_GPTMP;
\timing
