\echo ------------------RSK_REPLICATION_LOG----------------
select now();
\timing
delete from RSK_REPLICATION_LOG_GPTMP;
insert into RSK_REPLICATION_LOG_GPTMP (CMD_TYPE,CUSTOMS_CODE, TABLE_NAME, REPLI_DATE) select CMD_TYPE,CUSTOMS_CODE, TABLE_NAME, REPLI_DATE from RSK_REPLICATION_LOG_INC_EXT;
delete from RSK_REPLICATION_LOG_GPTMP_TODAY using RSK_REPLICATION_LOG_GPTMP where RSK_REPLICATION_LOG_GPTMP.CUSTOMS_CODE=RSK_REPLICATION_LOG_GPTMP_TODAY.CUSTOMS_CODE AND RSK_REPLICATION_LOG_GPTMP.TABLE_NAME=RSK_REPLICATION_LOG_GPTMP_TODAY.TABLE_NAME AND RSK_REPLICATION_LOG_GPTMP.REPLI_DATE=RSK_REPLICATION_LOG_GPTMP_TODAY.REPLI_DATE ;
insert into RSK_REPLICATION_LOG_GPTMP_TODAY (CMD_TYPE,CUSTOMS_CODE,TABLE_NAME,TABLE_C_NAME,REPLI_DATE,REPLI_ER) select CMD_TYPE,CUSTOMS_CODE,TABLE_NAME,TABLE_C_NAME,REPLI_DATE,REPLI_ER from RSK_REPLICATION_LOG_INC_EXT;
delete from RSK_REPLICATION_LOG_GPTMP;
\timing
