\echo ------------------RSK_EXAM_OP_LOG----------------
select now();
\timing
delete from RSK_EXAM_OP_LOG_GPTMP;
insert into RSK_EXAM_OP_LOG_GPTMP (CMD_TYPE,EXAM_REC_ID, OP_TIME, MODI_TYPE, TABLE_NAME, ITEM_NAME) select CMD_TYPE,EXAM_REC_ID, OP_TIME, MODI_TYPE, TABLE_NAME, ITEM_NAME from RSK_EXAM_OP_LOG_INC_EXT;
delete from RSK_EXAM_OP_LOG_GPTMP_TODAY using RSK_EXAM_OP_LOG_GPTMP where RSK_EXAM_OP_LOG_GPTMP.EXAM_REC_ID=RSK_EXAM_OP_LOG_GPTMP_TODAY.EXAM_REC_ID AND RSK_EXAM_OP_LOG_GPTMP.OP_TIME=RSK_EXAM_OP_LOG_GPTMP_TODAY.OP_TIME AND RSK_EXAM_OP_LOG_GPTMP.MODI_TYPE=RSK_EXAM_OP_LOG_GPTMP_TODAY.MODI_TYPE AND RSK_EXAM_OP_LOG_GPTMP.TABLE_NAME=RSK_EXAM_OP_LOG_GPTMP_TODAY.TABLE_NAME AND RSK_EXAM_OP_LOG_GPTMP.ITEM_NAME=RSK_EXAM_OP_LOG_GPTMP_TODAY.ITEM_NAME ;
insert into RSK_EXAM_OP_LOG_GPTMP_TODAY (CMD_TYPE,EXAM_REC_ID,OP_TIME,OP_ER,MODI_TYPE,FORM_ID,TABLE_NAME,ITEM_NAME,ITEM_SOURCE,ITEM_CURRENT,NOTE) select CMD_TYPE,EXAM_REC_ID,OP_TIME,OP_ER,MODI_TYPE,FORM_ID,TABLE_NAME,ITEM_NAME,ITEM_SOURCE,ITEM_CURRENT,NOTE from RSK_EXAM_OP_LOG_INC_EXT;
delete from RSK_EXAM_OP_LOG_GPTMP;
\timing
