\echo ------------------RSK_VS_EXAM----------------
select now();
\timing
delete from RSK_VS_EXAM_GPTMP;
insert into RSK_VS_EXAM_GPTMP (CMD_TYPE,FORM_ID, FORM_TYPE, RSK_NO, D_DATE, EXAM_REC_ID) select CMD_TYPE,FORM_ID, FORM_TYPE, RSK_NO, D_DATE, EXAM_REC_ID from RSK_VS_EXAM_INC_EXT;
delete from RSK_VS_EXAM_GPTMP_TODAY using RSK_VS_EXAM_GPTMP where RSK_VS_EXAM_GPTMP.FORM_ID=RSK_VS_EXAM_GPTMP_TODAY.FORM_ID AND RSK_VS_EXAM_GPTMP.FORM_TYPE=RSK_VS_EXAM_GPTMP_TODAY.FORM_TYPE AND RSK_VS_EXAM_GPTMP.RSK_NO=RSK_VS_EXAM_GPTMP_TODAY.RSK_NO AND RSK_VS_EXAM_GPTMP.D_DATE=RSK_VS_EXAM_GPTMP_TODAY.D_DATE AND RSK_VS_EXAM_GPTMP.EXAM_REC_ID=RSK_VS_EXAM_GPTMP_TODAY.EXAM_REC_ID ;
insert into RSK_VS_EXAM_GPTMP_TODAY (CMD_TYPE,FORM_ID,FORM_TYPE,RSK_NO,D_DATE,EXAM_REC_ID) select CMD_TYPE,FORM_ID,FORM_TYPE,RSK_NO,D_DATE,EXAM_REC_ID from RSK_VS_EXAM_INC_EXT;
delete from RSK_VS_EXAM_GPTMP;
\timing
