\echo ------------------RSK_CASE_FEEDBACK_LIST----------------
select now();
\timing
delete from RSK_CASE_FEEDBACK_LIST_GPTMP;
insert into RSK_CASE_FEEDBACK_LIST_GPTMP (CMD_TYPE,ENTRY_ID, CASE_ID, PROC_NO) select CMD_TYPE,ENTRY_ID, CASE_ID, PROC_NO from RSK_CASE_FEEDBACK_LIST_INC_EXT;
delete from RSK_CASE_FEEDBACK_LIST_GPTMP_TODAY using RSK_CASE_FEEDBACK_LIST_GPTMP where RSK_CASE_FEEDBACK_LIST_GPTMP.ENTRY_ID=RSK_CASE_FEEDBACK_LIST_GPTMP_TODAY.ENTRY_ID AND RSK_CASE_FEEDBACK_LIST_GPTMP.CASE_ID=RSK_CASE_FEEDBACK_LIST_GPTMP_TODAY.CASE_ID AND RSK_CASE_FEEDBACK_LIST_GPTMP.PROC_NO=RSK_CASE_FEEDBACK_LIST_GPTMP_TODAY.PROC_NO ;
insert into RSK_CASE_FEEDBACK_LIST_GPTMP_TODAY (CMD_TYPE,ENTRY_ID,CASE_ID,PROC_NO,PROC_RESULT) select CMD_TYPE,ENTRY_ID,CASE_ID,PROC_NO,PROC_RESULT from RSK_CASE_FEEDBACK_LIST_INC_EXT;
delete from RSK_CASE_FEEDBACK_LIST_GPTMP;
\timing
