\echo ------------------RSK_ASSAY_APPLICATION----------------
select now();
\timing
delete from RSK_ASSAY_APPLICATION_GPTMP;
insert into RSK_ASSAY_APPLICATION_GPTMP (CMD_TYPE,ENTRY_ID, G_NO) select CMD_TYPE,ENTRY_ID, G_NO from RSK_ASSAY_APPLICATION_INC_EXT;
delete from RSK_ASSAY_APPLICATION_GPTMP_TODAY using RSK_ASSAY_APPLICATION_GPTMP where RSK_ASSAY_APPLICATION_GPTMP.ENTRY_ID=RSK_ASSAY_APPLICATION_GPTMP_TODAY.ENTRY_ID AND RSK_ASSAY_APPLICATION_GPTMP.G_NO=RSK_ASSAY_APPLICATION_GPTMP_TODAY.G_NO ;
insert into RSK_ASSAY_APPLICATION_GPTMP_TODAY (CMD_TYPE,ENTRY_ID,G_NO,APPLY_NO,ASSAY_AGENT_NAME,CUSTOMS_DEPARTMENT,G_NAME,TRADE_NAME,OWNER_NAME,TRADE_MODE,G_QTY,DECL_PRICE,DECL_TOTAL,ORIGIN_COUNTRY,WRAP_TYPE,G_DESCRIPITION,ASSAY_AIM,ASSAY_AIM_OTHER,CODE_TS,DRAFT_CODE_TS,SAMPLE_TIME,SAMPLE_ADDR,SAMPLE_DESCRIPITION,OP_ER_PHONE,OWNER_NAME_PHONE,APPLY_OP_ER,APPLY_TIME,FEEDBACK_CERT_NO,FEEDBACK_DESCRIPITION,FEEDBACK_RESULT,FEEDBACK_CODE_TS,FEEDBACK_OP_ER,FEEDBACK_TIME) select CMD_TYPE,ENTRY_ID,G_NO,APPLY_NO,ASSAY_AGENT_NAME,CUSTOMS_DEPARTMENT,G_NAME,TRADE_NAME,OWNER_NAME,TRADE_MODE,G_QTY,DECL_PRICE,DECL_TOTAL,ORIGIN_COUNTRY,WRAP_TYPE,G_DESCRIPITION,ASSAY_AIM,ASSAY_AIM_OTHER,CODE_TS,DRAFT_CODE_TS,SAMPLE_TIME,SAMPLE_ADDR,SAMPLE_DESCRIPITION,OP_ER_PHONE,OWNER_NAME_PHONE,APPLY_OP_ER,APPLY_TIME,FEEDBACK_CERT_NO,FEEDBACK_DESCRIPITION,FEEDBACK_RESULT,FEEDBACK_CODE_TS,FEEDBACK_OP_ER,FEEDBACK_TIME from RSK_ASSAY_APPLICATION_INC_EXT;
delete from RSK_ASSAY_APPLICATION_GPTMP;
\timing
