\echo ------------------RSK_OP_LOG----------------
select now();
\timing
delete from RSK_OP_LOG_GPTMP;
insert into RSK_OP_LOG_GPTMP (CMD_TYPE,FORM_ID, OP_TIME) select CMD_TYPE,FORM_ID, OP_TIME from RSK_OP_LOG_INC_EXT;
delete from RSK_OP_LOG_GPTMP_TODAY using RSK_OP_LOG_GPTMP where RSK_OP_LOG_GPTMP.FORM_ID=RSK_OP_LOG_GPTMP_TODAY.FORM_ID AND RSK_OP_LOG_GPTMP.OP_TIME=RSK_OP_LOG_GPTMP_TODAY.OP_TIME ;
insert into RSK_OP_LOG_GPTMP_TODAY (CMD_TYPE,FORM_ID,FORM_TYPE,CUSTOMS_CODE,OP_ER,OP_TIME,OP_POS) select CMD_TYPE,FORM_ID,FORM_TYPE,CUSTOMS_CODE,OP_ER,OP_TIME,OP_POS from RSK_OP_LOG_INC_EXT;
delete from RSK_OP_LOG_GPTMP;
\timing
