\echo ------------------RSK_INSTR_PROC_REL----------------
select now();
\timing
delete from RSK_INSTR_PROC_REL_GPTMP;
insert into RSK_INSTR_PROC_REL_GPTMP (CMD_TYPE,RSK_NO, RSK_POS) select CMD_TYPE,RSK_NO, RSK_POS from RSK_INSTR_PROC_REL_INC_EXT;
delete from RSK_INSTR_PROC_REL_GPTMP_TODAY using RSK_INSTR_PROC_REL_GPTMP where RSK_INSTR_PROC_REL_GPTMP.RSK_NO=RSK_INSTR_PROC_REL_GPTMP_TODAY.RSK_NO AND RSK_INSTR_PROC_REL_GPTMP.RSK_POS=RSK_INSTR_PROC_REL_GPTMP_TODAY.RSK_POS ;
insert into RSK_INSTR_PROC_REL_GPTMP_TODAY (CMD_TYPE,RSK_NO,RSK_POS,RSK_REQUEST_STR,RSK_PROC_TYPE_STR,INFO_REQUEST_DETAIL) select CMD_TYPE,RSK_NO,RSK_POS,RSK_REQUEST_STR,RSK_PROC_TYPE_STR,INFO_REQUEST_DETAIL from RSK_INSTR_PROC_REL_INC_EXT;
delete from RSK_INSTR_PROC_REL_GPTMP;
\timing
