\echo ------------------RSK_TRADE_CO----------------
select now();
\timing
delete from RSK_TRADE_CO_GPTMP;
insert into RSK_TRADE_CO_GPTMP (CMD_TYPE,CCTS_CODE) select CMD_TYPE,CCTS_CODE from RSK_TRADE_CO_INC_EXT;
delete from RSK_TRADE_CO_GPTMP_TODAY using RSK_TRADE_CO_GPTMP where RSK_TRADE_CO_GPTMP.CCTS_CODE=RSK_TRADE_CO_GPTMP_TODAY.CCTS_CODE ;
insert into RSK_TRADE_CO_GPTMP_TODAY (CMD_TYPE,CCTS_CODE,TRADE_CO,TRADE_NAME,BEGIN_DATE,END_DATE,CUSTOMS_CODE,INPUT_ID,AUTHORIZE_ID,OP_TIME,I_E_FLAG) select CMD_TYPE,CCTS_CODE,TRADE_CO,TRADE_NAME,BEGIN_DATE,END_DATE,CUSTOMS_CODE,INPUT_ID,AUTHORIZE_ID,OP_TIME,I_E_FLAG from RSK_TRADE_CO_INC_EXT;
delete from RSK_TRADE_CO_GPTMP;
\timing
