\echo ------------------RSK_CASE_TRANSFER_G_NO----------------
select now();
\timing
delete from RSK_CASE_TRANSFER_G_NO_GPTMP;
insert into RSK_CASE_TRANSFER_G_NO_GPTMP (CMD_TYPE,ENTRY_ID, CASE_ID, G_NO) select CMD_TYPE,ENTRY_ID, CASE_ID, G_NO from RSK_CASE_TRANSFER_G_NO_INC_EXT;
delete from RSK_CASE_TRANSFER_G_NO_GPTMP_TODAY using RSK_CASE_TRANSFER_G_NO_GPTMP where RSK_CASE_TRANSFER_G_NO_GPTMP.ENTRY_ID=RSK_CASE_TRANSFER_G_NO_GPTMP_TODAY.ENTRY_ID AND RSK_CASE_TRANSFER_G_NO_GPTMP.CASE_ID=RSK_CASE_TRANSFER_G_NO_GPTMP_TODAY.CASE_ID AND RSK_CASE_TRANSFER_G_NO_GPTMP.G_NO=RSK_CASE_TRANSFER_G_NO_GPTMP_TODAY.G_NO ;
insert into RSK_CASE_TRANSFER_G_NO_GPTMP_TODAY (CMD_TYPE,ENTRY_ID,CASE_ID,G_NO,G_NAME) select CMD_TYPE,ENTRY_ID,CASE_ID,G_NO,G_NAME from RSK_CASE_TRANSFER_G_NO_INC_EXT;
delete from RSK_CASE_TRANSFER_G_NO_GPTMP;
\timing
