\echo ------------------RSK_UNLOCK_OP_LOG----------------
select now();
\timing
delete from RSK_UNLOCK_OP_LOG_GPTMP;
insert into RSK_UNLOCK_OP_LOG_GPTMP (CMD_TYPE,FORM_ID, RSK_NO, UNLOCK_TIME) select CMD_TYPE,FORM_ID, RSK_NO, UNLOCK_TIME from RSK_UNLOCK_OP_LOG_INC_EXT;
delete from RSK_UNLOCK_OP_LOG_GPTMP_TODAY using RSK_UNLOCK_OP_LOG_GPTMP where RSK_UNLOCK_OP_LOG_GPTMP.FORM_ID=RSK_UNLOCK_OP_LOG_GPTMP_TODAY.FORM_ID AND RSK_UNLOCK_OP_LOG_GPTMP.RSK_NO=RSK_UNLOCK_OP_LOG_GPTMP_TODAY.RSK_NO AND RSK_UNLOCK_OP_LOG_GPTMP.UNLOCK_TIME=RSK_UNLOCK_OP_LOG_GPTMP_TODAY.UNLOCK_TIME ;
insert into RSK_UNLOCK_OP_LOG_GPTMP_TODAY (CMD_TYPE,FORM_ID,RSK_NO,FORM_TYPE,CUSTOMS_CODE,UNLOCK_ER,UNLOCK_TIME,UNLOCK_REASON) select CMD_TYPE,FORM_ID,RSK_NO,FORM_TYPE,CUSTOMS_CODE,UNLOCK_ER,UNLOCK_TIME,UNLOCK_REASON from RSK_UNLOCK_OP_LOG_INC_EXT;
delete from RSK_UNLOCK_OP_LOG_GPTMP;
\timing
