\echo ------------------RSK_CONTA_CAPACITY----------------
select now();
\timing
delete from RSK_CONTA_CAPACITY_GPTMP;
insert into RSK_CONTA_CAPACITY_GPTMP (CMD_TYPE,CCTS_CODE) select CMD_TYPE,CCTS_CODE from RSK_CONTA_CAPACITY_INC_EXT;
delete from RSK_CONTA_CAPACITY_GPTMP_TODAY using RSK_CONTA_CAPACITY_GPTMP where RSK_CONTA_CAPACITY_GPTMP.CCTS_CODE=RSK_CONTA_CAPACITY_GPTMP_TODAY.CCTS_CODE ;
insert into RSK_CONTA_CAPACITY_GPTMP_TODAY (CMD_TYPE,CCTS_CODE,CONTA_MODEL,CONTA_BULK,CONTA_WEIGHT_LOW,CONTA_WEIGHT_HIGH,CUSTOMS_CODE,INPUT_ID,BEGIN_DATE,END_DATE) select CMD_TYPE,CCTS_CODE,CONTA_MODEL,CONTA_BULK,CONTA_WEIGHT_LOW,CONTA_WEIGHT_HIGH,CUSTOMS_CODE,INPUT_ID,BEGIN_DATE,END_DATE from RSK_CONTA_CAPACITY_INC_EXT;
delete from RSK_CONTA_CAPACITY_GPTMP;
\timing
