\echo ------------------SERVICE_FEE----------------
select now();
\timing
delete from SERVICE_FEE_GPTMP;
insert into SERVICE_FEE_GPTMP (CMD_TYPE,MANUAL_NO) select CMD_TYPE,MANUAL_NO from SERVICE_FEE_INC_EXT;
delete from SERVICE_FEE_GPTMP_TODAY using SERVICE_FEE_GPTMP where SERVICE_FEE_GPTMP.MANUAL_NO=SERVICE_FEE_GPTMP_TODAY.MANUAL_NO ;
insert into SERVICE_FEE_GPTMP_TODAY (CMD_TYPE,MANUAL_NO,DUE_FEE_AMT,PAY_FEE_AMT,CREATE_DATE,RETURN_ID,RETURN_FLAG,REMAIN_AMT) select CMD_TYPE,MANUAL_NO,DUE_FEE_AMT,PAY_FEE_AMT,CREATE_DATE,RETURN_ID,RETURN_FLAG,REMAIN_AMT from SERVICE_FEE_INC_EXT;
delete from SERVICE_FEE_GPTMP;
\timing
