\echo ------------------SPECIAL_ENTRY----------------
select now();
\timing
delete from SPECIAL_ENTRY_GPTMP;
insert into SPECIAL_ENTRY_GPTMP (CMD_TYPE,ENTRY_ID, OP_TIME) select CMD_TYPE,ENTRY_ID, OP_TIME from SPECIAL_ENTRY_INC_EXT;
delete from SPECIAL_ENTRY_GPTMP_TODAY using SPECIAL_ENTRY_GPTMP where SPECIAL_ENTRY_GPTMP.ENTRY_ID=SPECIAL_ENTRY_GPTMP_TODAY.ENTRY_ID AND SPECIAL_ENTRY_GPTMP.OP_TIME=SPECIAL_ENTRY_GPTMP_TODAY.OP_TIME ;
insert into SPECIAL_ENTRY_GPTMP_TODAY (CMD_TYPE,ENTRY_ID,OP_TIME,OP_ER,OP_NOTE,OP_FLAG,REV_ER,REV_TIME,END_ER,END_TIME,END_NOTE) select CMD_TYPE,ENTRY_ID,OP_TIME,OP_ER,OP_NOTE,OP_FLAG,REV_ER,REV_TIME,END_ER,END_TIME,END_NOTE from SPECIAL_ENTRY_INC_EXT;
delete from SPECIAL_ENTRY_GPTMP;
\timing
