\echo ------------------STATUS_DETAIL----------------
select now();
\timing
delete from STATUS_DETAIL_GPTMP;
insert into STATUS_DETAIL_GPTMP (CMD_TYPE,ENTRY_ID, DETAIL_COUNT) select CMD_TYPE,ENTRY_ID, DETAIL_COUNT from STATUS_DETAIL_INC_EXT;
delete from STATUS_DETAIL_GPTMP_TODAY using STATUS_DETAIL_GPTMP where STATUS_DETAIL_GPTMP.ENTRY_ID=STATUS_DETAIL_GPTMP_TODAY.ENTRY_ID AND STATUS_DETAIL_GPTMP.DETAIL_COUNT=STATUS_DETAIL_GPTMP_TODAY.DETAIL_COUNT ;
insert into STATUS_DETAIL_GPTMP_TODAY (CMD_TYPE,ENTRY_ID,DETAIL_COUNT,STATUS_NUMBER,STATUS_RESULT,STATUS_DETAIL) select CMD_TYPE,ENTRY_ID,DETAIL_COUNT,STATUS_NUMBER,STATUS_RESULT,STATUS_DETAIL from STATUS_DETAIL_INC_EXT;
delete from STATUS_DETAIL_GPTMP;
\timing
