\echo ------------------STL_DATA_HEAD----------------
select now();
\timing
delete from STL_DATA_HEAD_GPTMP;
insert into STL_DATA_HEAD_GPTMP (CMD_TYPE,UCR_CODE) select CMD_TYPE,UCR_CODE from STL_DATA_HEAD_INC_EXT;
delete from STL_DATA_HEAD_GPTMP_TODAY using STL_DATA_HEAD_GPTMP where STL_DATA_HEAD_GPTMP.UCR_CODE=STL_DATA_HEAD_GPTMP_TODAY.UCR_CODE ;
insert into STL_DATA_HEAD_GPTMP_TODAY (CMD_TYPE,UCR_CODE,ENTRY_ID,CREATE_DATE,STEP_ID,STATUS_CODE,I_E_FLAG,I_E_PORT,DESTINATION_CUSTOMS_CODE,TRADE_CO,TRAF_NAME,VOYAGE_NO,BILL_NO,OUT_PORT_DATE,TRADE_PORT,PACK_NO,REL_DATE,HASH_SIGN,CUSTOMS_REMARK,CUSTOMS_REMARK_NOTES,CUSTOMS_REMARK_3,CUSTOMS_REMARK_NOTES_3,CARRIER_NAME,CONSIGNEE_NAME,CONSIGNOR_NAME,NOTIFYPARTY_NAME,SUBMITTER_NAME,FIRSTARRIVALLOCATION_CODE,ARRIVAL_DATETIME,ROUTINGCOUNTRY_CODE,DESTINATION_PORT,UPDATE_DATE) select CMD_TYPE,UCR_CODE,ENTRY_ID,CREATE_DATE,STEP_ID,STATUS_CODE,I_E_FLAG,I_E_PORT,DESTINATION_CUSTOMS_CODE,TRADE_CO,TRAF_NAME,VOYAGE_NO,BILL_NO,OUT_PORT_DATE,TRADE_PORT,PACK_NO,REL_DATE,HASH_SIGN,CUSTOMS_REMARK,CUSTOMS_REMARK_NOTES,CUSTOMS_REMARK_3,CUSTOMS_REMARK_NOTES_3,CARRIER_NAME,CONSIGNEE_NAME,CONSIGNOR_NAME,NOTIFYPARTY_NAME,SUBMITTER_NAME,FIRSTARRIVALLOCATION_CODE,ARRIVAL_DATETIME,ROUTINGCOUNTRY_CODE,DESTINATION_PORT,UPDATE_DATE from STL_DATA_HEAD_INC_EXT;
delete from STL_DATA_HEAD_GPTMP;
\timing
