\echo ------------------TCS_SEND_LOG----------------
select now();
\timing
delete from TCS_SEND_LOG_GPTMP;
insert into TCS_SEND_LOG_GPTMP (CMD_TYPE,TRANS_NO) select CMD_TYPE,TRANS_NO from TCS_SEND_LOG_INC_EXT;
delete from TCS_SEND_LOG_GPTMP_TODAY using TCS_SEND_LOG_GPTMP where TCS_SEND_LOG_GPTMP.TRANS_NO=TCS_SEND_LOG_GPTMP_TODAY.TRANS_NO ;
insert into TCS_SEND_LOG_GPTMP_TODAY (CMD_TYPE,TRANS_NO,ENTRY_ID,TAX_ID,SEND_DATE,ACCOUNT_ORG_CODE,ORIGINAL_SOURCE,GEN_DATE,TAX_TYPE,DELAY_MARK,DUTY_FLAG,P_DATE,BUDGET_SUBJECT_CODE,TREASURY_CODE,BUDGET_LEVEL_CODE,REAL_TAX,C_DATE,PAY_MODE,PAYER_BANK_NAME,PAYER_ACCOUNT_NO,REMARK1,REMARK2,REMARK3,TREASURY_RESPONSE_DATE,RESPONSE_OP_DATE,TREASURY_RESULT,TREASURY_ADD_WORD) select CMD_TYPE,TRANS_NO,ENTRY_ID,TAX_ID,SEND_DATE,ACCOUNT_ORG_CODE,ORIGINAL_SOURCE,GEN_DATE,TAX_TYPE,DELAY_MARK,DUTY_FLAG,P_DATE,BUDGET_SUBJECT_CODE,TREASURY_CODE,BUDGET_LEVEL_CODE,REAL_TAX,C_DATE,PAY_MODE,PAYER_BANK_NAME,PAYER_ACCOUNT_NO,REMARK1,REMARK2,REMARK3,TREASURY_RESPONSE_DATE,RESPONSE_OP_DATE,TREASURY_RESULT,TREASURY_ADD_WORD from TCS_SEND_LOG_INC_EXT;
delete from TCS_SEND_LOG_GPTMP;
\timing
