\echo ------------------TCS_DETAIL_HEAD----------------
select now();
\timing
delete from TCS_DETAIL_HEAD_GPTMP;
insert into TCS_DETAIL_HEAD_GPTMP (CMD_TYPE,ACCOUNT_ORG_CODE, IN_TREASURY_DATE, PACK_NO, CURRENT_PACK_NO) select CMD_TYPE,ACCOUNT_ORG_CODE, IN_TREASURY_DATE, PACK_NO, CURRENT_PACK_NO from TCS_DETAIL_HEAD_INC_EXT;
delete from TCS_DETAIL_HEAD_GPTMP_TODAY using TCS_DETAIL_HEAD_GPTMP where TCS_DETAIL_HEAD_GPTMP.ACCOUNT_ORG_CODE=TCS_DETAIL_HEAD_GPTMP_TODAY.ACCOUNT_ORG_CODE AND TCS_DETAIL_HEAD_GPTMP.IN_TREASURY_DATE=TCS_DETAIL_HEAD_GPTMP_TODAY.IN_TREASURY_DATE AND TCS_DETAIL_HEAD_GPTMP.PACK_NO=TCS_DETAIL_HEAD_GPTMP_TODAY.PACK_NO AND TCS_DETAIL_HEAD_GPTMP.CURRENT_PACK_NO=TCS_DETAIL_HEAD_GPTMP_TODAY.CURRENT_PACK_NO ;
insert into TCS_DETAIL_HEAD_GPTMP_TODAY (CMD_TYPE,MSG_ID,ACCOUNT_ORG_CODE,IN_TREASURY_DATE,PACK_NO,CHILD_PACK_NUM,CURRENT_PACK_NO,ALL_NUM,ALL_AMOUNT,CURRENT_NUM,CURRENT_AMOUNT,VERIFY_MARK,VERIFY_NOTE,MAX_ITEM_NO,RECEIVE_DATE) select CMD_TYPE,MSG_ID,ACCOUNT_ORG_CODE,IN_TREASURY_DATE,PACK_NO,CHILD_PACK_NUM,CURRENT_PACK_NO,ALL_NUM,ALL_AMOUNT,CURRENT_NUM,CURRENT_AMOUNT,VERIFY_MARK,VERIFY_NOTE,MAX_ITEM_NO,RECEIVE_DATE from TCS_DETAIL_HEAD_INC_EXT;
delete from TCS_DETAIL_HEAD_GPTMP;
\timing
