\echo ------------------TCS_ERROR_LOG----------------
select now();
\timing
delete from TCS_ERROR_LOG_GPTMP;
insert into TCS_ERROR_LOG_GPTMP (CMD_TYPE,GUID) select CMD_TYPE,GUID from TCS_ERROR_LOG_INC_EXT;
delete from TCS_ERROR_LOG_GPTMP_TODAY using TCS_ERROR_LOG_GPTMP where TCS_ERROR_LOG_GPTMP.GUID=TCS_ERROR_LOG_GPTMP_TODAY.GUID ;
insert into TCS_ERROR_LOG_GPTMP_TODAY (CMD_TYPE,GUID,BIZ_ID,CREATE_TIME,ERR_ID,NOTE) select CMD_TYPE,GUID,BIZ_ID,CREATE_TIME,ERR_ID,NOTE from TCS_ERROR_LOG_INC_EXT;
delete from TCS_ERROR_LOG_GPTMP;
\timing
