\echo ------------------TEMP_DEL_EMS_HEAD----------------
select now();
\timing
delete from TEMP_DEL_EMS_HEAD_GPTMP;
insert into TEMP_DEL_EMS_HEAD_GPTMP (CMD_TYPE,EMS_NO) select CMD_TYPE,EMS_NO from TEMP_DEL_EMS_HEAD_INC_EXT;
delete from TEMP_DEL_EMS_HEAD_GPTMP_TODAY using TEMP_DEL_EMS_HEAD_GPTMP where TEMP_DEL_EMS_HEAD_GPTMP.EMS_NO=TEMP_DEL_EMS_HEAD_GPTMP_TODAY.EMS_NO ;
insert into TEMP_DEL_EMS_HEAD_GPTMP_TODAY (CMD_TYPE,EMS_NO) select CMD_TYPE,EMS_NO from TEMP_DEL_EMS_HEAD_INC_EXT;
delete from TEMP_DEL_EMS_HEAD_GPTMP;
\timing
