\echo ------------------TEMP_DB----------------
select now();
\timing
delete from TEMP_DB_GPTMP;
insert into TEMP_DB_GPTMP (CMD_TYPE,PRE_NO, PROCESS_STEP) select CMD_TYPE,PRE_NO, PROCESS_STEP from TEMP_DB_INC_EXT;
delete from TEMP_DB_GPTMP_TODAY using TEMP_DB_GPTMP where TEMP_DB_GPTMP.PRE_NO=TEMP_DB_GPTMP_TODAY.PRE_NO AND TEMP_DB_GPTMP.PROCESS_STEP=TEMP_DB_GPTMP_TODAY.PROCESS_STEP ;
insert into TEMP_DB_GPTMP_TODAY (CMD_TYPE,PRE_NO,PROCESS_STEP) select CMD_TYPE,PRE_NO,PROCESS_STEP from TEMP_DB_INC_EXT;
delete from TEMP_DB_GPTMP;
\timing
