\echo ------------------TEMP_PAGE_RANGE----------------
select now();
\timing
delete from TEMP_PAGE_RANGE_GPTMP;
insert into TEMP_PAGE_RANGE_GPTMP (CMD_TYPE,PR_KEY, PR_DETAIL) select CMD_TYPE,PR_KEY, PR_DETAIL from TEMP_PAGE_RANGE_INC_EXT;
delete from TEMP_PAGE_RANGE_GPTMP_TODAY using TEMP_PAGE_RANGE_GPTMP where TEMP_PAGE_RANGE_GPTMP.PR_KEY=TEMP_PAGE_RANGE_GPTMP_TODAY.PR_KEY AND TEMP_PAGE_RANGE_GPTMP.PR_DETAIL=TEMP_PAGE_RANGE_GPTMP_TODAY.PR_DETAIL ;
insert into TEMP_PAGE_RANGE_GPTMP_TODAY (CMD_TYPE,PR_KEY,PR_DETAIL) select CMD_TYPE,PR_KEY,PR_DETAIL from TEMP_PAGE_RANGE_INC_EXT;
delete from TEMP_PAGE_RANGE_GPTMP;
\timing
