\echo ------------------TEP_DEBIT_REC_RESPONSE----------------
select now();
\timing
delete from TEP_DEBIT_REC_RESPONSE_GPTMP;
insert into TEP_DEBIT_REC_RESPONSE_GPTMP (CMD_TYPE,TRANS_NO, RESPONSE_DATE) select CMD_TYPE,TRANS_NO, RESPONSE_DATE from TEP_DEBIT_REC_RESPONSE_INC_EXT;
delete from TEP_DEBIT_REC_RESPONSE_GPTMP_TODAY using TEP_DEBIT_REC_RESPONSE_GPTMP where TEP_DEBIT_REC_RESPONSE_GPTMP.TRANS_NO=TEP_DEBIT_REC_RESPONSE_GPTMP_TODAY.TRANS_NO AND TEP_DEBIT_REC_RESPONSE_GPTMP.RESPONSE_DATE=TEP_DEBIT_REC_RESPONSE_GPTMP_TODAY.RESPONSE_DATE ;
insert into TEP_DEBIT_REC_RESPONSE_GPTMP_TODAY (CMD_TYPE,TRANS_NO,RESPONSE_DATE,RESPONSE_TIME,REC_CODE,MEMO) select CMD_TYPE,TRANS_NO,RESPONSE_DATE,RESPONSE_TIME,REC_CODE,MEMO from TEP_DEBIT_REC_RESPONSE_INC_EXT;
delete from TEP_DEBIT_REC_RESPONSE_GPTMP;
\timing
