\echo ------------------TEP_LOG----------------
select now();
\timing
delete from TEP_LOG_GPTMP;
insert into TEP_LOG_GPTMP (CMD_TYPE,STEP_ID, BIZ_ID, CREATE_DATE) select CMD_TYPE,STEP_ID, BIZ_ID, CREATE_DATE from TEP_LOG_INC_EXT;
delete from TEP_LOG_GPTMP_TODAY using TEP_LOG_GPTMP where TEP_LOG_GPTMP.STEP_ID=TEP_LOG_GPTMP_TODAY.STEP_ID AND TEP_LOG_GPTMP.BIZ_ID=TEP_LOG_GPTMP_TODAY.BIZ_ID AND TEP_LOG_GPTMP.CREATE_DATE=TEP_LOG_GPTMP_TODAY.CREATE_DATE ;
insert into TEP_LOG_GPTMP_TODAY (CMD_TYPE,STEP_ID,BIZ_ID,CREATE_DATE,OPER_ID,OPER_DECRIPTION,NOTE_S) select CMD_TYPE,STEP_ID,BIZ_ID,CREATE_DATE,OPER_ID,OPER_DECRIPTION,NOTE_S from TEP_LOG_INC_EXT;
delete from TEP_LOG_GPTMP;
\timing
