\echo ------------------TEP_STATUS_QUERY----------------
select now();
\timing
delete from TEP_STATUS_QUERY_GPTMP;
insert into TEP_STATUS_QUERY_GPTMP (CMD_TYPE,TRANS_NO, SENDER_ID, DEAL_TIME) select CMD_TYPE,TRANS_NO, SENDER_ID, DEAL_TIME from TEP_STATUS_QUERY_INC_EXT;
delete from TEP_STATUS_QUERY_GPTMP_TODAY using TEP_STATUS_QUERY_GPTMP where TEP_STATUS_QUERY_GPTMP.TRANS_NO=TEP_STATUS_QUERY_GPTMP_TODAY.TRANS_NO AND TEP_STATUS_QUERY_GPTMP.SENDER_ID=TEP_STATUS_QUERY_GPTMP_TODAY.SENDER_ID AND TEP_STATUS_QUERY_GPTMP.DEAL_TIME=TEP_STATUS_QUERY_GPTMP_TODAY.DEAL_TIME ;
insert into TEP_STATUS_QUERY_GPTMP_TODAY (CMD_TYPE,TRANS_NO,SENDER_ID,DEAL_TIME,TRANS_STATUS,SENDT_FLAG,RESERVE) select CMD_TYPE,TRANS_NO,SENDER_ID,DEAL_TIME,TRANS_STATUS,SENDT_FLAG,RESERVE from TEP_STATUS_QUERY_INC_EXT;
delete from TEP_STATUS_QUERY_GPTMP;
\timing
