\echo ------------------TEP_EPLAT_RESPONSE----------------
select now();
\timing
delete from TEP_EPLAT_RESPONSE_GPTMP;
insert into TEP_EPLAT_RESPONSE_GPTMP (CMD_TYPE,MSG_TYPE, CREATE_DATE) select CMD_TYPE,MSG_TYPE, CREATE_DATE from TEP_EPLAT_RESPONSE_INC_EXT;
delete from TEP_EPLAT_RESPONSE_GPTMP_TODAY using TEP_EPLAT_RESPONSE_GPTMP where TEP_EPLAT_RESPONSE_GPTMP.MSG_TYPE=TEP_EPLAT_RESPONSE_GPTMP_TODAY.MSG_TYPE AND TEP_EPLAT_RESPONSE_GPTMP.CREATE_DATE=TEP_EPLAT_RESPONSE_GPTMP_TODAY.CREATE_DATE ;
insert into TEP_EPLAT_RESPONSE_GPTMP_TODAY (CMD_TYPE,MSG_TYPE,CREATE_DATE,CUSTOMS_CODE,RETURN_CODE,ERR_RETURN_CODE,ERR_RETURN_INFO,SPT1) select CMD_TYPE,MSG_TYPE,CREATE_DATE,CUSTOMS_CODE,RETURN_CODE,ERR_RETURN_CODE,ERR_RETURN_INFO,SPT1 from TEP_EPLAT_RESPONSE_INC_EXT;
delete from TEP_EPLAT_RESPONSE_GPTMP;
\timing
