\echo ------------------TEP_ERR_LOG----------------
select now();
\timing
delete from TEP_ERR_LOG_GPTMP;
insert into TEP_ERR_LOG_GPTMP (CMD_TYPE,ERR_NO, CREATE_DATE) select CMD_TYPE,ERR_NO, CREATE_DATE from TEP_ERR_LOG_INC_EXT;
delete from TEP_ERR_LOG_GPTMP_TODAY using TEP_ERR_LOG_GPTMP where TEP_ERR_LOG_GPTMP.ERR_NO=TEP_ERR_LOG_GPTMP_TODAY.ERR_NO AND TEP_ERR_LOG_GPTMP.CREATE_DATE=TEP_ERR_LOG_GPTMP_TODAY.CREATE_DATE ;
insert into TEP_ERR_LOG_GPTMP_TODAY (CMD_TYPE,ERR_NO,CREATE_DATE,TEP_TYPE,STEP_ID,NOTE) select CMD_TYPE,ERR_NO,CREATE_DATE,TEP_TYPE,STEP_ID,NOTE from TEP_ERR_LOG_INC_EXT;
delete from TEP_ERR_LOG_GPTMP;
\timing
