\echo ------------------TRADE_GPM_RTX----------------
select now();
\timing
delete from TRADE_GPM_RTX_GPTMP;
insert into TRADE_GPM_RTX_GPTMP (CMD_TYPE,TRADE_MODE, SIGN_TYPE, SIGN_MODE) select CMD_TYPE,TRADE_MODE, SIGN_TYPE, SIGN_MODE from TRADE_GPM_RTX_INC_EXT;
delete from TRADE_GPM_RTX_GPTMP_TODAY using TRADE_GPM_RTX_GPTMP where TRADE_GPM_RTX_GPTMP.TRADE_MODE=TRADE_GPM_RTX_GPTMP_TODAY.TRADE_MODE AND TRADE_GPM_RTX_GPTMP.SIGN_TYPE=TRADE_GPM_RTX_GPTMP_TODAY.SIGN_TYPE AND TRADE_GPM_RTX_GPTMP.SIGN_MODE=TRADE_GPM_RTX_GPTMP_TODAY.SIGN_MODE ;
insert into TRADE_GPM_RTX_GPTMP_TODAY (CMD_TYPE,TRADE_MODE,SIGN_TYPE,SIGN_MODE) select CMD_TYPE,TRADE_MODE,SIGN_TYPE,SIGN_MODE from TRADE_GPM_RTX_INC_EXT;
delete from TRADE_GPM_RTX_GPTMP;
\timing
