\echo ------------------TRANSFER_FEE----------------
select now();
\timing
delete from TRANSFER_FEE_GPTMP;
insert into TRANSFER_FEE_GPTMP (CMD_TYPE,MANUAL_NO, RTN_MANUAL_NO) select CMD_TYPE,MANUAL_NO, RTN_MANUAL_NO from TRANSFER_FEE_INC_EXT;
delete from TRANSFER_FEE_GPTMP_TODAY using TRANSFER_FEE_GPTMP where TRANSFER_FEE_GPTMP.MANUAL_NO=TRANSFER_FEE_GPTMP_TODAY.MANUAL_NO AND TRANSFER_FEE_GPTMP.RTN_MANUAL_NO=TRANSFER_FEE_GPTMP_TODAY.RTN_MANUAL_NO ;
insert into TRANSFER_FEE_GPTMP_TODAY (CMD_TYPE,MANUAL_NO,RTN_MANUAL_NO,TRANSFER_FEE) select CMD_TYPE,MANUAL_NO,RTN_MANUAL_NO,TRANSFER_FEE from TRANSFER_FEE_INC_EXT;
delete from TRANSFER_FEE_GPTMP;
\timing
