\echo ------------------TRN_PARAMETER----------------
select now();
\timing
delete from TRN_PARAMETER_GPTMP;
insert into TRN_PARAMETER_GPTMP (CMD_TYPE,CUSTOMS_CODE, P_NAME) select CMD_TYPE,CUSTOMS_CODE, P_NAME from TRN_PARAMETER_INC_EXT;
delete from TRN_PARAMETER_GPTMP_TODAY using TRN_PARAMETER_GPTMP where TRN_PARAMETER_GPTMP.CUSTOMS_CODE=TRN_PARAMETER_GPTMP_TODAY.CUSTOMS_CODE AND TRN_PARAMETER_GPTMP.P_NAME=TRN_PARAMETER_GPTMP_TODAY.P_NAME ;
insert into TRN_PARAMETER_GPTMP_TODAY (CMD_TYPE,CUSTOMS_CODE,P_NAME,P_VALUE,OPERATOR_NO,MODI_DATE) select CMD_TYPE,CUSTOMS_CODE,P_NAME,P_VALUE,OPERATOR_NO,MODI_DATE from TRN_PARAMETER_INC_EXT;
delete from TRN_PARAMETER_GPTMP;
\timing
