\echo ------------------TRN_SHIP----------------
select now();
\timing
delete from TRN_SHIP_GPTMP;
insert into TRN_SHIP_GPTMP (CMD_TYPE,CUSTOM_NO) select CMD_TYPE,CUSTOM_NO from TRN_SHIP_INC_EXT;
delete from TRN_SHIP_GPTMP_TODAY using TRN_SHIP_GPTMP where TRN_SHIP_GPTMP.CUSTOM_NO=TRN_SHIP_GPTMP_TODAY.CUSTOM_NO ;
insert into TRN_SHIP_GPTMP_TODAY (CMD_TYPE,CUSTOM_NO,VALID_FLAG,CK_FLAG,MAN_CUSTOM_NO,DR_NAME,CO_NAME,SHIP_NO,VALID_DATE,OPERATOR_NO,INPUT_DATE,CO_ADDRESS,CO_TELE,CO_MAIL,TRAF_FLAG,TRAF_NOTE) select CMD_TYPE,CUSTOM_NO,VALID_FLAG,CK_FLAG,MAN_CUSTOM_NO,DR_NAME,CO_NAME,SHIP_NO,VALID_DATE,OPERATOR_NO,INPUT_DATE,CO_ADDRESS,CO_TELE,CO_MAIL,TRAF_FLAG,TRAF_NOTE from TRN_SHIP_INC_EXT;
delete from TRN_SHIP_GPTMP;
\timing
