\echo ------------------TRN_COP_REL----------------
select now();
\timing
delete from TRN_COP_REL_GPTMP;
insert into TRN_COP_REL_GPTMP (CMD_TYPE,CO_REG_NO) select CMD_TYPE,CO_REG_NO from TRN_COP_REL_INC_EXT;
delete from TRN_COP_REL_GPTMP_TODAY using TRN_COP_REL_GPTMP where TRN_COP_REL_GPTMP.CO_REG_NO=TRN_COP_REL_GPTMP_TODAY.CO_REG_NO ;
insert into TRN_COP_REL_GPTMP_TODAY (CMD_TYPE,CO_REG_NO,CO_CUSTOMS_NO,MAIN_PORT,CO_NAME,CO_ADDRESS,CO_PHONE_NO,VALID_FLAG,VALID_DATE,INPUT_DATE,INPUT_OP_ID,PERMIT_FLAG,PERMIT_DATE,PERMIT_OP_ID,RESERV_FIELD,CO_REG_TYPE,CO_PROPERTY,CO_DEAL_RANGE,CO_AUTHORIZE_NO,CO_DEAL_DATE,CO_CORPORATION_REP,CO_ABROAD_NAME,GANG_AO_CARS,GANG_AO_CARS_USED,CK_FLAG,NOTE_FIELD) select CMD_TYPE,CO_REG_NO,CO_CUSTOMS_NO,MAIN_PORT,CO_NAME,CO_ADDRESS,CO_PHONE_NO,VALID_FLAG,VALID_DATE,INPUT_DATE,INPUT_OP_ID,PERMIT_FLAG,PERMIT_DATE,PERMIT_OP_ID,RESERV_FIELD,CO_REG_TYPE,CO_PROPERTY,CO_DEAL_RANGE,CO_AUTHORIZE_NO,CO_DEAL_DATE,CO_CORPORATION_REP,CO_ABROAD_NAME,GANG_AO_CARS,GANG_AO_CARS_USED,CK_FLAG,NOTE_FIELD from TRN_COP_REL_INC_EXT;
delete from TRN_COP_REL_GPTMP;
\timing
