\echo ------------------TRN_I_E_PORT----------------
select now();
\timing
delete from TRN_I_E_PORT_GPTMP;
insert into TRN_I_E_PORT_GPTMP (CMD_TYPE,VE_CUSTOMS_NO, I_E_PORT) select CMD_TYPE,VE_CUSTOMS_NO, I_E_PORT from TRN_I_E_PORT_INC_EXT;
delete from TRN_I_E_PORT_GPTMP_TODAY using TRN_I_E_PORT_GPTMP where TRN_I_E_PORT_GPTMP.VE_CUSTOMS_NO=TRN_I_E_PORT_GPTMP_TODAY.VE_CUSTOMS_NO AND TRN_I_E_PORT_GPTMP.I_E_PORT=TRN_I_E_PORT_GPTMP_TODAY.I_E_PORT ;
insert into TRN_I_E_PORT_GPTMP_TODAY (CMD_TYPE,VE_CUSTOMS_NO,MAIN_PORT,I_E_PORT,INPUT_OP_ID,INPUT_DATE) select CMD_TYPE,VE_CUSTOMS_NO,MAIN_PORT,I_E_PORT,INPUT_OP_ID,INPUT_DATE from TRN_I_E_PORT_INC_EXT;
delete from TRN_I_E_PORT_GPTMP;
\timing
