\echo ------------------TRN_VE_REL----------------
select now();
\timing
delete from TRN_VE_REL_GPTMP;
insert into TRN_VE_REL_GPTMP (CMD_TYPE,VE_CUSTOMS_NO) select CMD_TYPE,VE_CUSTOMS_NO from TRN_VE_REL_INC_EXT;
delete from TRN_VE_REL_GPTMP_TODAY using TRN_VE_REL_GPTMP where TRN_VE_REL_GPTMP.VE_CUSTOMS_NO=TRN_VE_REL_GPTMP_TODAY.VE_CUSTOMS_NO ;
insert into TRN_VE_REL_GPTMP_TODAY (CMD_TYPE,VE_CUSTOMS_NO,CAR_EC_NO,VE_TYPE,MAIN_PORT,VE_NAME,CO_REG_NO,CO_NAME,CK_FLAG,VALID_FLAG,VALID_DATE,INPUT_DATE,INPUT_OP_ID,RESERV_FIELD,VE_WT,REG_TYPE,VE_NO1,VE_BELONG_AREA,VE_PROPERTY,VE_BRAND,VE_OILTANK_VOL,VE_INDEX_NO,VE_IE_CERF_NO,VE_COLOR,VE_MOTOR_NO,VE_FRAME_NO,VE_TON,NOTE_FIELD,VE_IE_PORT,GPS_ID,SIM_1,SIM_2,GPS_PROVIDER,GPS_FLAG,TRANS_NO) select CMD_TYPE,VE_CUSTOMS_NO,CAR_EC_NO,VE_TYPE,MAIN_PORT,VE_NAME,CO_REG_NO,CO_NAME,CK_FLAG,VALID_FLAG,VALID_DATE,INPUT_DATE,INPUT_OP_ID,RESERV_FIELD,VE_WT,REG_TYPE,VE_NO1,VE_BELONG_AREA,VE_PROPERTY,VE_BRAND,VE_OILTANK_VOL,VE_INDEX_NO,VE_IE_CERF_NO,VE_COLOR,VE_MOTOR_NO,VE_FRAME_NO,VE_TON,NOTE_FIELD,VE_IE_PORT,GPS_ID,SIM_1,SIM_2,GPS_PROVIDER,GPS_FLAG,TRANS_NO from TRN_VE_REL_INC_EXT;
delete from TRN_VE_REL_GPTMP;
\timing
