\echo ------------------YD_DECLARE_REL----------------
select now();
\timing
delete from YD_DECLARE_REL_GPTMP;
insert into YD_DECLARE_REL_GPTMP (CMD_TYPE,TRADE_CO, CUSTOMS_CODE) select CMD_TYPE,TRADE_CO, CUSTOMS_CODE from YD_DECLARE_REL_INC_EXT;
delete from YD_DECLARE_REL_GPTMP_TODAY using YD_DECLARE_REL_GPTMP where YD_DECLARE_REL_GPTMP.TRADE_CO=YD_DECLARE_REL_GPTMP_TODAY.TRADE_CO AND YD_DECLARE_REL_GPTMP.CUSTOMS_CODE=YD_DECLARE_REL_GPTMP_TODAY.CUSTOMS_CODE ;
insert into YD_DECLARE_REL_GPTMP_TODAY (CMD_TYPE,TRADE_CO,CUSTOMS_CODE) select CMD_TYPE,TRADE_CO,CUSTOMS_CODE from YD_DECLARE_REL_INC_EXT;
delete from YD_DECLARE_REL_GPTMP;
\timing
